Peano
exahype2.solvers.rkfd.fd4.amr Namespace Reference
Functions
linearise_index (index, dimensions)
linearise_index_reverse (index, dimensions)
__compute_interpolation_matrix_nd_csr (patch_size, halo_size, patch_index_linear=None, d=3)
Compute the interpolation matrix, which used to prepare halo layer data for fine cells at the refinement boundary.
__compute_restriction_matrix_nd_csr (patch_size, halo_size, patchIndexLinear, d=3)
Compute the interpolation matrix, which used to prepare halo layer data for fine cells at the refinement boundary.
__compute_interpolation_matrices_1d (value, patch_size)
__compute_restriction_matrices_1d (value, patch_size)
compute the restriction matrix, which used to prepare halo layer data for coarse cells at the refinement boundary.
switch_to_FD4_second_order_interpolation (CellCenteredFiniteDifferences solver)
switch_to_FD4_second_order_restriction (CellCenteredFiniteDifferences solver)
switch_to_FD4_third_order_interpolation (CellCenteredFiniteDifferences solver)
switch_to_FD4_third_order_restriction (CellCenteredFiniteDifferences solver)
switch_to_FD4_matrix_interpolation (CellCenteredFiniteDifferences solver)
switch_to_FD4_matrix_restriction (CellCenteredFiniteDifferences solver)
switch_to_FD4_tensor_product_interpolation (CellCenteredFiniteDifferences solver, variant)
This routine accepts the solver object and an identifier object and then enables this interpolation.
switch_to_FD4_tensor_product_restriction (CellCenteredFiniteDifferences solver, variant)
Consult the docu of switch_to_FD4_tensor_product_interpolation().
Function Documentation
__compute_interpolation_matrices_1d()
exahype2.solvers.rkfd.fd4.amr.__compute_interpolation_matrices_1d (value, patch_size) private
compute the interpolation matrix, which used to prepare halo layer data for fine cells at the refinement boundary.
the matrix formulation depends on the interpolation scheme.
The matrix is only 1d mapping, say, the matrix is P_ij (it is a 3 patch_size \times patch_size matrix)
and u^f_i and u^c_j are solution at fine and coarse level, respectively. we have
u^f_i = P_ij u^c_j
The interpolation routine for high dimensions can be found in a tensor-manner
u^f_ij = P_ik P_jl u^c_kl
The interpolation along the normal direction will use a slight difference matrix as we can always interpolate rather than extrapolate.
In fd4 scheme we require the interpolations for three halo layers, so the matrix P'_ij have a size of 3*6, 6 is for 6 layers of coarse volume.
Please note this method is limited due to no access to the diagonal volumes and the high order interpolation is achieved by tensor product way.
We use TP to indicate this in our interpolation scheme name.
TP_constant: constant interpolation in both surface direction and normal direction
Tangential:                       Normal:
1  0  0  0  0  0 ...              0  0  1  0  0  0
1  0  0  0  0  0 ...              0  0  1  0  0  0
1  0  0  0  0  0 ...              0  0  1  0  0  0
0  1  0  0  0  0 ...
0  1  0  0  0  0 ...
0  1  0  0  0  0 ...
...
TP_linear_with_linear_extrap_normal_interp:
linear interpolation within the patch and along the normal direction, and extrapolate at the boundary of the surface
Tangential:                       Normal:
4/3  -1/3  0    0  0  0 ...       0  1/3  2/3  0    0  0
1    0     0    0  0  0 ...       0  0    1    0    0  0
2/3  1/3   0    0  0  0 ...       0  0    2/3  1/3  0  0
1/3  2/3   0    0  0  0 ...
0    1     0    0  0  0 ...
0    2/3   1/3  0  0  0 ...
...
Definition at line 410 of file amr.py.
Referenced by exahype2.solvers.rkfd.fd4.amr.switch_to_FD4_tensor_product_interpolation().
__compute_interpolation_matrix_nd_csr()
exahype2.solvers.rkfd.fd4.amr.__compute_interpolation_matrix_nd_csr (patch_size, halo_size, patch_index_linear = None, d = 3) private
Compute the interpolation matrix, which used to prepare halo layer data for fine cells at the refinement boundary.
The matrix is an nd mapping, so each axis is interpolated by one matrix.
For a matrix P_ij that is generated, the mapping between coarse and fine values is
u^f_i = P_ij u^c_j
Definition at line 36 of file amr.py.
References exahype2.solvers.rkfd.fd4.amr.linearise_index().
Referenced by exahype2.solvers.rkfd.fd4.amr.switch_to_FD4_matrix_interpolation().
__compute_restriction_matrices_1d()
exahype2.solvers.rkfd.fd4.amr.__compute_restriction_matrices_1d (value, patch_size) private
compute the restriction matrix, which used to prepare halo layer data for coarse cells at the refinement boundary.
the matrix formulation depends on the interpolation scheme.
The matrix is only 1d mapping, say, the matrix is Q_ij (it is a patch_size \times 3 patch_size matrix)and u^f_i and u^c_j are solution at fine and coarse level, respectively. we have
u^c_i = Q_ij u^f_j
The interpolation routine for high dimensions can be found in a tensor-manner
u^c_ij = Q_ik Q_jl u^f_kl
The interpolation along the normal direction will use a slight difference matrix as we need some extrapolation in linear scheme. In fd4 scheme we require the interpolations for three halo layers, so the matrix Q'_ij have a size of 6*3, 6 is for 6 layers of fine volume.
Please note this method is limited due to no access to the diagonal volumes and the high order restriction is achieved by tensor product way. We use TP to indicate this in our restriction scheme name.
TP_inject_normal_extrap: directly use the central-surface fine cell to assign the coarse cell, but extrapolate along normal direction. Notice we can still do the average for the outmost layer to improve accuracy.
Tangential: Normal: 0 1 0 0 0 0 0 0 0 0 0 0... 0 0 0 1/3 1/3 1/3 0 0 0 0 1 0 0 0 0 0 0 0... 0 0 0 0 -2 3 0 0 0 0 0 0 0 0 0 0 0 0... 0 0 0 0 -5 6 0 0 0 0 0 0 0 1 0 0 0 0... ...
TP_average_normal_extrp: average value in fine cells if possible, but extrapolate along normal direction.
Tangential: Normal: 1/3 1/3 1/3 0 0 0 0 0 0 0 0 0... 0 0 0 1/3 1/3 1/3 0 0 0 1/3 1/3 1/3 0 0 0 0 0 0... 0 0 0 0 -2 3 0 0 0 0 0 0 1/3 1/3 1/3 0 0 0... 0 0 0 0 -5 6 0 0 0 0 0 0 0 0 0 1/3 1/3 1/3... ...
Definition at line 496 of file amr.py.
Referenced by exahype2.solvers.rkfd.fd4.amr.switch_to_FD4_tensor_product_restriction().
__compute_restriction_matrix_nd_csr()
exahype2.solvers.rkfd.fd4.amr.__compute_restriction_matrix_nd_csr (patch_size, halo_size, patchIndexLinear, d = 3) private
Compute the interpolation matrix, which used to prepare halo layer data for fine cells at the refinement boundary.
The matrix is an nd mapping, so each axis is interpolated by one matrix.
For a matrix P_ij that is generated, the mapping between coarse and fine values is
u^f_i = P_ij u^c_j
Definition at line 284 of file amr.py.
References exahype2.solvers.rkfd.fd4.amr.linearise_index_reverse().
Referenced by exahype2.solvers.rkfd.fd4.amr.switch_to_FD4_matrix_restriction().
linearise_index()
exahype2.solvers.rkfd.fd4.amr.linearise_index (index, dimensions)
Definition at line 18 of file amr.py.
Referenced by exahype2.solvers.rkfd.fd4.amr.__compute_interpolation_matrix_nd_csr().
linearise_index_reverse()
exahype2.solvers.rkfd.fd4.amr.linearise_index_reverse (index, dimensions)
Definition at line 27 of file amr.py.
Referenced by exahype2.solvers.rkfd.fd4.amr.__compute_restriction_matrix_nd_csr().
switch_to_FD4_matrix_interpolation()
exahype2.solvers.rkfd.fd4.amr.switch_to_FD4_matrix_interpolation (CellCenteredFiniteDifferences solver)
Definition at line 587 of file amr.py.
References exahype2.solvers.rkfd.fd4.amr.__compute_interpolation_matrix_nd_csr().
switch_to_FD4_matrix_restriction()
exahype2.solvers.rkfd.fd4.amr.switch_to_FD4_matrix_restriction (CellCenteredFiniteDifferences solver)
Definition at line 639 of file amr.py.
References exahype2.solvers.rkfd.fd4.amr.__compute_restriction_matrix_nd_csr().
switch_to_FD4_second_order_interpolation()
exahype2.solvers.rkfd.fd4.amr.switch_to_FD4_second_order_interpolation (CellCenteredFiniteDifferences solver)
Definition at line 571 of file amr.py.
switch_to_FD4_second_order_restriction()
exahype2.solvers.rkfd.fd4.amr.switch_to_FD4_second_order_restriction (CellCenteredFiniteDifferences solver)
Definition at line 575 of file amr.py.
switch_to_FD4_tensor_product_interpolation()
exahype2.solvers.rkfd.fd4.amr.switch_to_FD4_tensor_product_interpolation (CellCenteredFiniteDifferences solver, variant)
This routine accepts the solver object and an identifier object and then enables this interpolation.
To do this, we have to set the tensor product interpolation, and we have to export the right matrices into the solver. Please do not switch the interpolation scheme more than once.
Definition at line 694 of file amr.py.
References exahype2.solvers.rkfd.fd4.amr.__compute_interpolation_matrices_1d().
switch_to_FD4_tensor_product_restriction()
exahype2.solvers.rkfd.fd4.amr.switch_to_FD4_tensor_product_restriction (CellCenteredFiniteDifferences solver, variant)
Consult the docu of switch_to_FD4_tensor_product_interpolation().
Definition at line 723 of file amr.py.
References exahype2.solvers.rkfd.fd4.amr.__compute_restriction_matrices_1d().
switch_to_FD4_third_order_interpolation()
exahype2.solvers.rkfd.fd4.amr.switch_to_FD4_third_order_interpolation (CellCenteredFiniteDifferences solver)
Definition at line 579 of file amr.py.
switch_to_FD4_third_order_restriction()
exahype2.solvers.rkfd.fd4.amr.switch_to_FD4_third_order_restriction (CellCenteredFiniteDifferences solver)
Definition at line 583 of file amr.py.