Peano
ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T > Class Template Reference
#include <ContextDynamicRupture.h>
Public Member Functions
ContextDynamicRupture (std::string &topography_string, int coarsestMeshLevel, double coarsestMeshSize, double maxAdaptiveDepth, tarch::la::Vector< Dimensions, double > _domainOffset, tarch::la::Vector< Dimensions, double > _domainSize, T *_nodes, T *_dudx)
void initRuptureModel (std::string &filename_rupture_model)
~ContextDynamicRupture ()
void riemannSolver (T *FL, T *FR, const T *const QL, const T *const QR, const double t, const double dt, const tarch::la::Vector< Dimensions, double > &cellSize, const int direction, bool isBoundaryFace, int faceIndex, int surface=2)
void initialStressTensor (T &sxx, T &syy, T &szz, T &sxy, T &sxz, T &syz, double *const x)
void preStress (T &T0_n, T &T0_m, T &T0_l, double *const x, double t, T *const l, T *const m, T *const n)
T boxcar (T &f, double x, T w)
void tauStrength (T &tau_str, T sigma_n, T S, double *const x, double t)
void slipWeakening (T &v1, T &v2, T &Vel, T &tau1, T &tau2, T phi_1, T phi_2, T eta, T tau_str, T sigma_n)
void slipWeakeningFriction (T vn_p, T vn_m, T Tn_p, T Tn_m, T zn_p, T zn_m, T &vn_hat_p, T &vn_hat_m, T &Tn_hat_p, T &Tn_hat_m, T vm_p, T vm_m, T Tm_p, T Tm_m, T zl_p, T zl_m, T &vm_hat_p, T &vm_hat_m, T &Tm_hat_p, T &Tm_hat_m, T vl_p, T vl_m, T Tl_p, T Tl_m, T zm_p, T zm_m, T &vl_hat_p, T &vl_hat_m, T &Tl_hat_p, T &Tl_hat_m, T *const l, T *const m, T *const n, double *const x, T S, double t)
Public Member Functions inherited from ContextCurvilinear< Shortcuts, basisSize, numberOfVariables+numberOfParameters, T >
ContextCurvilinear (std::string &topography_string, int coarsestMeshLevel, double coarsestMeshSize, double maxAdaptiveDepth, tarch::la::Vector< Dimensions, double > _domainOffset, tarch::la::Vector< Dimensions, double > _domainSize, T *_nodes, T *_dudx)
Root * getRoot ()
~ContextCurvilinear ()
void initUnknownsPatch (T *luh, const tarch::la::Vector< Dimensions, double > &center, const tarch::la::Vector< Dimensions, double > &dx, double t, double dt, std::function< void(const T *const x, const tarch::la::Vector< Dimensions, double > &center, const double t, const double dt, T *Q)> initUnknownsPointwise)
void correctPointSourceLocation (double pointSourceLocation[][3])
void getElementSize (const T *const luh, tarch::la::Vector< Dimensions, double > &dx)
void getElementCenter (const T *const luh, tarch::la::Vector< Dimensions, double > &center)
Data Fields
double domainSize [Dimensions]
AsagiReader * asagiReader
easi::Component * model
T S_c
T mu_d
T mu_s
T t0_rupture
T f_cy
These define the position of the area with frictional cohesion.
T f_wy
T f_cz
T f_wz
Data Fields inherited from ContextCurvilinear< Shortcuts, basisSize, numberOfVariables+numberOfParameters, T >
double max_dx
Additional Inherited Members
Protected Attributes inherited from ContextCurvilinear< Shortcuts, basisSize, numberOfVariables+numberOfParameters, T >
Curvi::Interface * interface
double nodes [basisSize]
double dudx [basisSize][basisSize]
double domainOffset [3]
const int meshLevel
Detailed Description
template<class Shortcuts, int basisSize, int numberOfVariables, int numberOfParameters, typename T>
class ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >
Definition at line 11 of file ContextDynamicRupture.h.
Constructor & Destructor Documentation
ContextDynamicRupture()
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::ContextDynamicRupture (std::string & topography_string, int coarsestMeshLevel, double coarsestMeshSize, double maxAdaptiveDepth, tarch::la::Vector< Dimensions, double > _domainOffset, tarch::la::Vector< Dimensions, double > _domainSize, T * _nodes, T * _dudx)
Definition at line 14 of file ContextDynamicRupture.h.
References ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::domainSize.
~ContextDynamicRupture()
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::~ContextDynamicRupture ()
Definition at line 65 of file ContextDynamicRupture.h.
References ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::asagiReader.
Member Function Documentation
boxcar()
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > T ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::boxcar (T & f, double x, T w)
Definition at line 122 of file dynamicRupture.h.
References std::abs(), and w.
initialStressTensor()
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > void ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::initialStressTensor (T & sxx, T & syy, T & szz, T & sxy, T & sxz, T & syz, double *const x)
Definition at line 10 of file dynamicRupture.h.
initRuptureModel()
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > void ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::initRuptureModel (std::string & filename_rupture_model)
Definition at line 37 of file ContextDynamicRupture.h.
References ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::asagiReader, ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::f_cy, ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::f_cz, ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::f_wy, ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::f_wz, ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::model, ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::mu_d, ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::mu_s, ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::S_c, and ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::t0_rupture.
preStress()
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > void ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::preStress (T & T0_n, T & T0_m, T & T0_l, double *const x, double t, T *const l, T *const m, T *const n)
Definition at line 37 of file dynamicRupture.h.
References m, and Numerics::rotateIntoOrthogonalBasis().
riemannSolver()
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > void ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::riemannSolver (T * FL, T * FR, const T *const QL, const T *const QR, const double t, const double dt, const tarch::la::Vector< Dimensions, double > & cellSize, const int direction, bool isBoundaryFace, int faceIndex, int surface = 2)
Definition at line 8 of file riemannsolverDynamicRupture.h.
References std::abs(), assertion3, cellSize, Numerics::computeFluctuationsLeft(), Numerics::computeFluctuationsRight(), Numerics::createLocalBasis(), InnerNode::evalPerturbation(), Root::getChild(), InnerNode::getCoordinates(), InnerNode::getFaceNormal(), InnerNode::getPosition(), int, r, Numerics::riemannSolverBoundary(), Numerics::riemannSolverNodal(), Numerics::rotateIntoOrthogonalBasis(), and Numerics::rotateIntoPhysicalBasis().
slipWeakening()
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > void ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::slipWeakening (T & v1, T & v2, T & Vel, T & tau1, T & tau2, T phi_1, T phi_2, T eta, T tau_str, T sigma_n)
Definition at line 141 of file dynamicRupture.h.
slipWeakeningFriction()
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > void ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::slipWeakeningFriction (T vn_p, T vn_m, T Tn_p, T Tn_m, T zn_p, T zn_m, T & vn_hat_p, T & vn_hat_m, T & Tn_hat_p, T & Tn_hat_m, T vm_p, T vm_m, T Tm_p, T Tm_m, T zl_p, T zl_m, T & vm_hat_p, T & vm_hat_m, T & Tm_hat_p, T & Tm_hat_m, T vl_p, T vl_m, T Tl_p, T Tl_m, T zm_p, T zm_m, T & vl_hat_p, T & vl_hat_m, T & Tl_hat_p, T & Tl_hat_m, T *const l, T *const m, T *const n, double *const x, T S, double t)
continuity of normal velocity
continuity of normal stress
continuity of normal velocity
Definition at line 163 of file dynamicRupture.h.
References m.
tauStrength()
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > void ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::tauStrength (T & tau_str, T sigma_n, T S, double *const x, double t)
Definition at line 75 of file dynamicRupture.h.
Field Documentation
asagiReader
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > AsagiReader* ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::asagiReader
Definition at line 119 of file ContextDynamicRupture.h.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::initRuptureModel(), and ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::~ContextDynamicRupture().
domainSize
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > double ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::domainSize[Dimensions]
Definition at line 117 of file ContextDynamicRupture.h.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::ContextDynamicRupture().
f_cy
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > T ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::f_cy
These define the position of the area with frictional cohesion.
Specifically, these define a rectangle of size 2*f_wy x 2*f_wz in the y-z axis centered around the point f_cy x f_cz. If within this rectangle, frictional cohesion applies, otherwise it does not. i.e. if -f_wy < y - f_cy < f_wy and -f_wz < z - f_cz < f_wz, frictional cohesion applies.
Definition at line 140 of file ContextDynamicRupture.h.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::initRuptureModel().
f_cz
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > T ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::f_cz
Definition at line 142 of file ContextDynamicRupture.h.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::initRuptureModel().
f_wy
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > T ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::f_wy
Definition at line 141 of file ContextDynamicRupture.h.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::initRuptureModel().
f_wz
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > T ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::f_wz
Definition at line 143 of file ContextDynamicRupture.h.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::initRuptureModel().
model
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > easi::Component* ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::model
Definition at line 120 of file ContextDynamicRupture.h.
Referenced by peano4.datamodel.ModelToDataRepository.ModelToDataRepository::__get_full_namespace(), peano4.datamodel.ModelToDataRepository.ModelToDataRepository::__parse_data_declarations_in_model(), peano4.datamodel.ModelToDataRepository.ModelToDataRepository::construct_output(), and ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::initRuptureModel().
mu_d
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > T ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::mu_d
Definition at line 124 of file ContextDynamicRupture.h.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::initRuptureModel().
mu_s
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > T ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::mu_s
Definition at line 125 of file ContextDynamicRupture.h.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::initRuptureModel().
S_c
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > T ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::S_c
Definition at line 123 of file ContextDynamicRupture.h.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::initRuptureModel().
t0_rupture
template<class Shortcuts , int basisSize, int numberOfVariables, int numberOfParameters, typename T > T ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::t0_rupture
Definition at line 129 of file ContextDynamicRupture.h.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::initRuptureModel().
The documentation for this class was generated from the following files:
applications/exahype2/exaseis/ExaSeis_core/Curvilinear/ContextDynamicRupture.h
applications/exahype2/exaseis/ExaSeis_core/Numerics/dynamicRupture.h
applications/exahype2/exaseis/ExaSeis_core/Numerics/riemannsolverDynamicRupture.h
applications/exahype2/exaseis/ExaSeis_core/Numerics/riemannsolverPMLDynamicRupture.h