Peano
toolbox::blockstructured::tests::IandRSecondOrderTest Class Reference
#include <IandRSecondOrderTest.h>
Public Member Functions
IandRSecondOrderTest ()
Cosntructor.
virtual ~IandRSecondOrderTest ()=default
Destructor, empty.
virtual void run () override
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void compareInterpolateLinearCaseToTensorProduct ()
The second order interpolation and restriction scheme is tested by comparing the results to the tensor product scheme.
void compareRestrictLinearCaseToTensorProduct ()
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Definition at line 17 of file IandRSecondOrderTest.h.
Constructor & Destructor Documentation
IandRSecondOrderTest()
toolbox::blockstructured::tests::IandRSecondOrderTest::IandRSecondOrderTest ()
Cosntructor.
Definition at line 8 of file IandRSecondOrderTest.cpp.
~IandRSecondOrderTest()
virtual toolbox::blockstructured::tests::IandRSecondOrderTest::~IandRSecondOrderTest () virtual default
Destructor, empty.
Member Function Documentation
compareInterpolateLinearCaseToTensorProduct()
void toolbox::blockstructured::tests::IandRSecondOrderTest::compareInterpolateLinearCaseToTensorProduct () private
The second order interpolation and restriction scheme is tested by comparing the results to the tensor product scheme.
Definition at line 16 of file IandRSecondOrderTest.cpp.
References peano4::datamanagement::FaceMarker::getRelativePositionWithinFatherFace(), toolbox::blockstructured::interpolateHaloLayer_AoS_second_order(), toolbox::blockstructured::interpolateHaloLayer_AoS_tensor_product(), peano4::grid::GridTraversalEvent::setRelativePositionToFather(), and validateNumericalEqualsWithEpsWithParams3.
compareRestrictLinearCaseToTensorProduct()
void toolbox::blockstructured::tests::IandRSecondOrderTest::compareRestrictLinearCaseToTensorProduct () private
Definition at line 136 of file IandRSecondOrderTest.cpp.
References peano4::datamanagement::FaceMarker::getRelativePositionWithinFatherFace(), toolbox::blockstructured::restrictHaloLayer_AoS_second_order(), toolbox::blockstructured::restrictHaloLayer_AoS_tensor_product(), peano4::grid::GridTraversalEvent::setRelativePositionToFather(), and validateNumericalEqualsWithEpsWithParams3.
run()
void toolbox::blockstructured::tests::IandRSecondOrderTest::run () override virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 11 of file IandRSecondOrderTest.cpp.
References testMethod.
The documentation for this class was generated from the following files:
src/toolbox/blockstructured/tests/IandRSecondOrderTest.h
src/toolbox/blockstructured/tests/IandRSecondOrderTest.cpp