Peano
tl::cartesian_product_view< Vs > Class Template Reference
#include <cartesian_product.h>
Data Structures
class cursor
class sentinel
Public Member Functions
cartesian_product_view ()=default
cartesian_product_view (Vs... bases)
constexpr auto begin ()
constexpr auto begin () const
constexpr auto end ()
constexpr auto end () const
constexpr auto end ()
constexpr auto end () const
constexpr auto size ()
constexpr auto size () const
Private Attributes
std::tuple< Vs... > bases_
Static Private Attributes
template<class... Ts>
static constexpr bool am_common
template<class... Ts>
static constexpr bool am_sized = (std::ranges::sized_range<Ts> && ...)
template<class... Ts>
static constexpr bool am_bidirectional
template<class... Ts>
static constexpr bool am_random_access
template<class... Ts>
static constexpr bool am_distanceable
Detailed Description
template<std::ranges::forward_range... Vs>
requires (std::ranges::view<Vs> && ...)
class tl::cartesian_product_view< Vs >
Definition at line 1141 of file cartesian_product.h.
Constructor & Destructor Documentation
cartesian_product_view() [1/2]
template<std::ranges::forward_range... Vs> tl::cartesian_product_view< Vs >::cartesian_product_view () default
cartesian_product_view() [2/2]
template<std::ranges::forward_range... Vs> tl::cartesian_product_view< Vs >::cartesian_product_view (Vs... bases) explicit
Definition at line 1319 of file cartesian_product.h.
Member Function Documentation
begin() [1/2]
template<std::ranges::forward_range... Vs> constexpr auto tl::cartesian_product_view< Vs >::begin () constexpr
Definition at line 1321 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::bases_.
Referenced by tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::end(), tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::end(), tl::cartesian_product_view< std::ranges::iota_view< W, B > >::end(), tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::end(), tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::end(), and tl::cartesian_product_view< std::ranges::iota_view< W, B > >::end().
begin() [2/2]
template<std::ranges::forward_range... Vs> constexpr auto tl::cartesian_product_view< Vs >::begin () const constexpr
Definition at line 1324 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::bases_.
end() [1/4]
template<std::ranges::forward_range... Vs> constexpr auto tl::cartesian_product_view< Vs >::end () constexpr
Definition at line 1328 of file cartesian_product.h.
References tl::as_sentinel, and tl::cartesian_product_view< Vs >::bases_.
end() [2/4]
template<std::ranges::forward_range... Vs> constexpr auto tl::cartesian_product_view< Vs >::end () constexpr
Definition at line 1336 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::bases_.
end() [3/4]
template<std::ranges::forward_range... Vs> constexpr auto tl::cartesian_product_view< Vs >::end () const constexpr
Definition at line 1332 of file cartesian_product.h.
References tl::as_sentinel, and tl::cartesian_product_view< Vs >::bases_.
end() [4/4]
template<std::ranges::forward_range... Vs> constexpr auto tl::cartesian_product_view< Vs >::end () const constexpr
Definition at line 1340 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::bases_.
size() [1/2]
template<std::ranges::forward_range... Vs> constexpr auto tl::cartesian_product_view< Vs >::size () constexpr
Definition at line 1344 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::bases_.
Referenced by peano4.visualisation.input.Patch.Patch::__repr__(), tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::end(), tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::end(), tl::cartesian_product_view< std::ranges::iota_view< W, B > >::end(), tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::end(), tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::end(), and tl::cartesian_product_view< std::ranges::iota_view< W, B > >::end().
size() [2/2]
template<std::ranges::forward_range... Vs> constexpr auto tl::cartesian_product_view< Vs >::size () const constexpr
Definition at line 1352 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::bases_.
Referenced by peano4.visualisation.input.Patch.Patch::__repr__().
Field Documentation
am_bidirectional
template<std::ranges::forward_range... Vs> template<class... Ts> constexpr bool tl::cartesian_product_view< Vs >::am_bidirectional static constexpr private
Initial value:
=
         ((std::ranges::bidirectional_range<Ts> && ...) && (std::ranges::common_range<Ts> && ...))
Definition at line 1154 of file cartesian_product.h.
am_common
template<std::ranges::forward_range... Vs> template<class... Ts> constexpr bool tl::cartesian_product_view< Vs >::am_common static constexpr private
Initial value:
= (std::ranges::common_range<Ts> && ...)
         || ((std::ranges::random_access_range<Ts> && ...) && (std::ranges::sized_range<Ts> && ...))
Definition at line 1146 of file cartesian_product.h.
am_distanceable
template<std::ranges::forward_range... Vs> template<class... Ts> constexpr bool tl::cartesian_product_view< Vs >::am_distanceable static constexpr private
Initial value:
=
         ((std::sized_sentinel_for<std::ranges::iterator_t<Ts>, std::ranges::iterator_t<Ts>>) && ...)
         && am_sized<Ts...>
Definition at line 1164 of file cartesian_product.h.
am_random_access
template<std::ranges::forward_range... Vs> template<class... Ts> constexpr bool tl::cartesian_product_view< Vs >::am_random_access static constexpr private
Initial value:
=
         ((std::ranges::random_access_range<Ts> && ...) &&
            (std::ranges::sized_range<Ts> && ...))
Definition at line 1159 of file cartesian_product.h.
am_sized
template<std::ranges::forward_range... Vs> template<class... Ts> constexpr bool tl::cartesian_product_view< Vs >::am_sized = (std::ranges::sized_range<Ts> && ...) static constexpr private
Definition at line 1150 of file cartesian_product.h.
bases_
template<std::ranges::forward_range... Vs> std::tuple<Vs...> tl::cartesian_product_view< Vs >::bases_ private
Definition at line 1168 of file cartesian_product.h.
Referenced by tl::cartesian_product_view< Vs >::begin(), tl::cartesian_product_view< Vs >::begin(), tl::cartesian_product_view< Vs >::end(), tl::cartesian_product_view< Vs >::end(), tl::cartesian_product_view< Vs >::size(), and tl::cartesian_product_view< Vs >::size().
The documentation for this class was generated from the following file:
src/tarch/accelerator/cpp/cartesian_product.h