Peano
Root Class Reference
#include <root.h>
Public Member Functions
Root (YAML::Node const &node, double a_offset[3], double a_size[3], uint a_grid[3])
~Root ()
void init (uint modes[3])
BlockBoundary traverse (int a_index[3])
BlockBoundary traverseProjection (double coords[3])
Block traverse ()
Node * getChild () const
void checkInit ()
std::string toString (int depth=0)
void multiplyToTopography (std::function< double(double, double)> factor)
Private Attributes
bool isInit
Coordinate coords [2]
uint grid [3]
double size [3]
double offset [3]
bool top
easi::Component * model
std::function< double(double, double)> topo
std::function< double(double, double)> final_topo
Node * child
Detailed Description
Definition at line 9 of file root.h.
Constructor & Destructor Documentation
Root()
Root::Root (YAML::Node const & node, double a_offset[3], double a_size[3], uint a_grid[3])
Definition at line 11 of file root.h.
References child, coords, coordToLowercaseString(), final_topo, getNormal(), isInit, model, offset, size, stringToCoord(), top, and topo.
~Root()
Root::~Root ()
Definition at line 85 of file root.h.
References child, and model.
Member Function Documentation
checkInit()
void Root::checkInit ()
Definition at line 134 of file root.h.
References isInit.
Referenced by toString(), traverse(), traverse(), and traverseProjection().
getChild()
Node * Root::getChild () const
Definition at line 130 of file root.h.
References child.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::riemannSolver().
init()
void Root::init (uint modes[3])
Definition at line 90 of file root.h.
References child, coords, final_topo, getNormal(), Node::init(), isInit, offset, size, and top.
Referenced by Curvi::Interface::initTree().
multiplyToTopography()
void Root::multiplyToTopography (std::function< double(double, double)> factor)
Definition at line 149 of file root.h.
References final_topo, and topo.
toString()
std::string Root::toString (int depth = 0)
Definition at line 140 of file root.h.
References checkInit(), child, coords, coordToString(), top, and Node::toString().
Referenced by Curvi::Interface::initTree().
traverse() [1/2]
Block Root::traverse ()
Definition at line 124 of file root.h.
References checkInit(), child, and Node::traverse().
traverse() [2/2]
BlockBoundary Root::traverse (int a_index[3])
Definition at line 111 of file root.h.
References checkInit(), child, and Node::traverse().
Referenced by Curvi::Interface::getElement().
traverseProjection()
BlockBoundary Root::traverseProjection (double coords[3])
Definition at line 118 of file root.h.
References checkInit(), child, coords, and Node::traverseProjection().
Referenced by Curvi::Interface::invertProjection().
Field Documentation
child
Node* Root::child private
Definition at line 169 of file root.h.
Referenced by getChild(), init(), Root(), toString(), traverse(), traverse(), traverseProjection(), and ~Root().
coords
Coordinate Root::coords[2] private
Definition at line 159 of file root.h.
Referenced by init(), Root(), toString(), and traverseProjection().
final_topo
std::function<double(double,double)> Root::final_topo private
Definition at line 167 of file root.h.
Referenced by init(), multiplyToTopography(), and Root().
grid
uint Root::grid[3] private
Definition at line 160 of file root.h.
isInit
bool Root::isInit private
Definition at line 157 of file root.h.
Referenced by checkInit(), init(), and Root().
model
easi::Component* Root::model private
Definition at line 165 of file root.h.
Referenced by peano4.datamodel.ModelToDataRepository.ModelToDataRepository::__get_full_namespace(), peano4.datamodel.ModelToDataRepository.ModelToDataRepository::__parse_data_declarations_in_model(), peano4.datamodel.ModelToDataRepository.ModelToDataRepository::construct_output(), Root(), and ~Root().
offset
double Root::offset[3] private
Definition at line 162 of file root.h.
Referenced by peano4.visualisation.input.Patch.Patch::__repr__(), init(), and Root().
size
double Root::size[3] private
Definition at line 161 of file root.h.
Referenced by peano4.visualisation.input.Patch.Patch::__repr__(), init(), and Root().
top
bool Root::top private
Definition at line 163 of file root.h.
Referenced by init(), Root(), and toString().
topo
std::function<double(double,double)> Root::topo private
Definition at line 166 of file root.h.
Referenced by multiplyToTopography(), and Root().
The documentation for this class was generated from the following file:
src/toolbox/curvi/kdTree/root.h