Peano
tarch::la::Vector< Size, Scalar > Struct Template Reference
Simple vector class.
#include <Vector.h>
Public Member Functions
Vector () InlineMethod=default
Clang requires the always_inline attribute, as it otherwise makes weird decisions.
GPUCallableMethod Vector (const Scalar *values) InlineMethod
GPUCallableMethod Vector (std::initializer_list< Scalar > values) InlineMethod
Initialisation via initialisation list.
GPUCallableMethod Vector (const std::bitset< Size > &values) InlineMethod
GPUCallableMethod Vector (const Scalar &initialValue) InlineMethod
Construct new vector and initialise all components with initialValue.
~Vector () InlineMethod=default
GPUCallableMethod Vector< Size, Scalar > & operator= (const Vector< Size, Scalar > &toAssign) InlineMethod=default
Assignment operator for any vector type.
GPUCallableMethod Vector (const Vector< Size, Scalar > &toCopy) InlineMethod=default
Copy constructor to copy from any vector type.
GPUCallableMethod int size () const InlineMethod
Returns the number of components of the vector.
GPUCallableMethod const Scalar & operator[] (int index) const InlineMethod
Returns read-only ref.
GPUCallableMethod Scalar & operator[] (int index) InlineMethod
Returns ref.
GPUCallableMethod const Scalar & operator() (int index) const InlineMethod
Returns read-only ref.
GPUCallableMethod Scalar & operator() (int index) InlineMethod
Returns ref.
GPUCallableMethod Scalar * data () InlineMethod
This routine returns a pointer to the first data element.
GPUCallableMethod const Scalar * data () const InlineMethod
Private Attributes
Scalar _values [Size]
Detailed Description
template<int Size, typename Scalar>
struct tarch::la::Vector< Size, Scalar >
Simple vector class.
Most features concerning vectors are deployed into separate headers:
Access only few elements within vector (subvector): VectorSlice.h
Functions over the vector such as norms: VectorOperations.h
Binary operators over vectors: VectorScalarOperations.h and VectorVectorOperations.h
There are multiple ways how to construct a vector:
You can use the standard constructor which gives a vector with garbage entries. You can then set individual entries manually.
You can use the constructor with a scalar which initialises all entries with the same value.
You can use initialiser lists, i.e. lists in curly brackets { and }, to construct a vector from a list.
To access entries of a vector, the class provides both access via an array notation, i.e. through [...], and with round brackets. The latter notation resembles Matlab. No matter which accessor you use, enumeration always starts with zero.
The class wraps an array of fixed size. Therefore, you can access the raw data via data(), but this violates ideas of object-oriented programming and hence should be done with care. Peano for example does this if and only if it has to hand over raw pointers to MPI, e.g.
Definition at line 84 of file Vector.h.
Constructor & Destructor Documentation
Vector() [1/6]
template<int Size, typename Scalar > tarch::la::Vector< Size, Scalar >::Vector () default
Clang requires the always_inline attribute, as it otherwise makes weird decisions.
Vector() [2/6]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar >::Vector (const Scalar * values)
Definition at line 3 of file Vector.cpph.
Vector() [3/6]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar >::Vector (std::initializer_list< Scalar > values)
Initialisation via initialisation list.
There is seemingly a bug in this constructor.
You can't inline an initialisation list, as the realisation of this routine relies on an iterator and the iterator within the C++ std lib won't be inlined.
For instance, the arguments peano4::initSingletons to are two objects of type tarch::la::Vector, with length Dimensions. However, passing in two initializer lists which are longer than Dimensions will cause the second to borrow from the first.
Definition at line 16 of file Vector.cpph.
Vector() [4/6]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar >::Vector (const std::bitset< Size > & values)
Definition at line 27 of file Vector.cpph.
Vector() [5/6]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar >::Vector (const Scalar & initialValue)
Construct new vector and initialise all components with initialValue.
Definition at line 35 of file Vector.cpph.
References tarch::la::Vector< Size, Scalar >::_values, and tarch::la::max().
~Vector()
template<int Size, typename Scalar > tarch::la::Vector< Size, Scalar >::~Vector () default
Vector() [6/6]
template<int Size, typename Scalar > GPUCallableMethod tarch::la::Vector< Size, Scalar >::Vector (const Vector< Size, Scalar > & toCopy) default
Copy constructor to copy from any vector type.
See also
operator= for default copy.
Member Function Documentation
data() [1/2]
template<int Size, typename Scalar > GPUCallableMethod const Scalar * tarch::la::Vector< Size, Scalar >::data () const
Definition at line 217 of file Vector.h.
References tarch::la::Vector< Size, Scalar >::_values.
Referenced by peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__generate_dastgen_input_file(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__get_file_name(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__get_full_qualified_file_name(), swift2.particle.Particle.Particle::__init__(), swift2.particle.Particle.Particle::_add_dependency_checks(), swift2.particle.Particle.Particle::_dependency_checks_modify_steps(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_boolean_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_boolean_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_double_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_double_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_enum_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_integer_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_integer_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_peano_double_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_peano_integer_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_string_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_user_defined_attributes(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::_get_dictionary_for_output(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::construct_output(), peano4.datamodel.DynamicArrayOverPrimitivesToStdVector.DynamicArrayOverPrimitivesToStdVector::construct_output(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::construct_output(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::construct_output(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::construct_output(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::get_header_file_include(), peano4.datamodel.DynamicArrayOverPrimitivesToStdVector.DynamicArrayOverPrimitivesToStdVector::get_header_file_include(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::get_header_file_include(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::get_header_file_include(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::get_header_file_include(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::get_stack_container(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::get_stack_container(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::get_stack_container(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::get_stack_container(), peano4.datamodel.DaStGen2.DaStGen2::hosts_smart_pointer_attribute(), swift2.particle.Particle.Particle::readme_descriptor(), swift2.particle.SPHLeapfrogFixedSearchRadius.SPHLeapfrogFixedSearchRadius::set_parameters(), swift2.particle.SPHParticle.SPHParticle::set_parameters(), and swift2.particle.tests.testLeapfrogFixedTimeStepSize.testLeapfrogFixedTimeStepSize::set_parameters().
data() [2/2]
template<int Size, typename Scalar > GPUCallableMethod Scalar * tarch::la::Vector< Size, Scalar >::data ()
This routine returns a pointer to the first data element.
Not a beautiful one as it harms the OO idea, but in many cases it is convenient to have this operation.
Definition at line 212 of file Vector.h.
References tarch::la::Vector< Size, Scalar >::_values.
Referenced by peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__generate_dastgen_input_file(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__get_file_name(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__get_full_qualified_file_name(), swift2.particle.Particle.Particle::__init__(), swift2.particle.Particle.Particle::_add_dependency_checks(), swift2.particle.Particle.Particle::_dependency_checks_modify_steps(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_boolean_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_boolean_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_double_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_double_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_enum_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_integer_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_integer_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_peano_double_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_peano_integer_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_string_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_user_defined_attributes(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::_get_dictionary_for_output(), toolbox::multiprecision::compress(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::construct_output(), peano4.datamodel.DynamicArrayOverPrimitivesToStdVector.DynamicArrayOverPrimitivesToStdVector::construct_output(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::construct_output(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::construct_output(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::construct_output(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::get_header_file_include(), peano4.datamodel.DynamicArrayOverPrimitivesToStdVector.DynamicArrayOverPrimitivesToStdVector::get_header_file_include(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::get_header_file_include(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::get_header_file_include(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::get_header_file_include(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::get_stack_container(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::get_stack_container(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::get_stack_container(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::get_stack_container(), peano4.datamodel.DaStGen2.DaStGen2::hosts_smart_pointer_attribute(), swift2.particle.Particle.Particle::readme_descriptor(), swift2.particle.SPHLeapfrogFixedSearchRadius.SPHLeapfrogFixedSearchRadius::set_parameters(), swift2.particle.SPHParticle.SPHParticle::set_parameters(), and swift2.particle.tests.testLeapfrogFixedTimeStepSize.testLeapfrogFixedTimeStepSize::set_parameters().
operator()() [1/2]
template<int Size, typename Scalar > GPUCallableMethod const Scalar & tarch::la::Vector< Size, Scalar >::operator() (int index) const
Returns read-only ref.
to component of given index.
If we use the vector on the GPU, we cannot have assertions. If we use SYCL on the CPU for the multitasking, we cannot have assertions in the SYCL part either, as SYCL aims to be platform-independent, i.e. has to assume that the code generated also will be deployed to a GPU. See discussion on tarch_accelerator_SYCL.
See also
operator[] for remarks on SSE
Definition at line 184 of file Vector.h.
References tarch::la::Vector< Size, Scalar >::_values, assertion3, tarch::la::max(), and tarch::toString().
operator()() [2/2]
template<int Size, typename Scalar > GPUCallableMethod Scalar & tarch::la::Vector< Size, Scalar >::operator() (int index)
Returns ref.
to component of given index.
See also
operator[] for remarks on SSE
Definition at line 198 of file Vector.h.
References tarch::la::Vector< Size, Scalar >::_values, assertion3, tarch::la::max(), and tarch::toString().
operator=()
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > & tarch::la::Vector< Size, Scalar >::operator= (const Vector< Size, Scalar > & toAssign) default
Assignment operator for any vector type.
Default assignment as this class needs to be trivially copyable.
operator[]() [1/2]
template<int Size, typename Scalar > GPUCallableMethod const Scalar & tarch::la::Vector< Size, Scalar >::operator[] (int index) const
Returns read-only ref.
to component of given index.
SSE Optimisation
We have to manually inline this operation. Otherwise, icc interprets operator calls, i.e. vector element accesses, as function calls and does not vectorise loops containing vector element accesses.
Definition at line 150 of file Vector.h.
References tarch::la::Vector< Size, Scalar >::_values, assertion3, tarch::la::max(), and tarch::toString().
operator[]() [2/2]
template<int Size, typename Scalar > GPUCallableMethod Scalar & tarch::la::Vector< Size, Scalar >::operator[] (int index)
Returns ref.
to component of given index.
See also
operator[] for remarks on SSE
Definition at line 164 of file Vector.h.
References tarch::la::Vector< Size, Scalar >::_values, assertion3, tarch::la::max(), and tarch::toString().
size()
template<int Size, typename Scalar > GPUCallableMethod int Vector< Size, Scalar >::size () const
Returns the number of components of the vector.
Definition at line 44 of file Vector.cpph.
References tarch::la::max().
Referenced by peano4.visualisation.input.Patch.Patch::__repr__().
Field Documentation
_values
template<int Size, typename Scalar > Scalar tarch::la::Vector< Size, Scalar >::_values[Size] private
Definition at line 86 of file Vector.h.
Referenced by tarch::la::Vector< Size, Scalar >::data(), tarch::la::Vector< Size, Scalar >::data(), tarch::la::Vector< Size, Scalar >::operator()(), tarch::la::Vector< Size, Scalar >::operator()(), tarch::la::Vector< Size, Scalar >::operator[](), tarch::la::Vector< Size, Scalar >::operator[](), and tarch::la::Vector< Size, Scalar >::Vector().
The documentation for this struct was generated from the following files:
src/tarch/la/SmartPointerVector.h
src/tarch/la/Vector.h
src/tarch/la/Vector.cpph