Peano
mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre Class Reference
Concrete implementation for Gauss Legendre nodes.
Public Member Functions
get_Gauss_Lobatto_nodes (self, poly_degree)
Return coordinates of Gauss-Lobatto nodes in [-1, 1] for given polynomial degree.
nodal_points (self, degree)
Set nodal points xi_0, xi_1, ..., xi_p.
node1d (self, degree, j)
Return the j-th nodal point of a Lagrange polynomial of given degree :arg degree: polynomial degree :arg j: index of node.
lagrange_polynomial (self, degree, k)
Returns k-th basis function L^{(m)}_k(xi) of degree m as a numpy polynomial object :arg degree: polynomial degree :arg k: index of basis function (= index of node)
evaluate (self, degree, k, xi)
Evaluate the k-th basis function L^{(m)}_k(xi) of degree m at point xi in [-1,+1], return L^{(m)}_k(xi) :arg degree: polynomial degree :arg k: index of basis function :arg xi: position xi.
evaluate_derivative (self, degree, k, xi)
Evaluate the derivative of the k-basis function L^{(m)}_k(xi) of degree m at point xi in [-1,+1] return dL^{(m)}_k(xi)/dxi :arg degree: polynomial degree :arg k: index of basis function :arg xi: position xi.
plot_basis_functions (self)
Implement the below code in a method.
Public Member Functions inherited from mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasis
__init__ (self, dim)
Initialise a new instance :arg dim: dimension.
Additional Inherited Members
Data Fields inherited from mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasis
dim
Initialise a new instance :arg dim: dimension.
Detailed Description
Concrete implementation for Gauss Legendre nodes.
Definition at line 26 of file nodal_basis.py.
Member Function Documentation
evaluate()
mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.evaluate (self, degree, k, xi)
Evaluate the k-th basis function L^{(m)}_k(xi) of degree m at point xi in [-1,+1], return L^{(m)}_k(xi) :arg degree: polynomial degree :arg k: index of basis function :arg xi: position xi.
Definition at line 102 of file nodal_basis.py.
References mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.lagrange_polynomial().
evaluate_derivative()
mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.evaluate_derivative (self, degree, k, xi)
Evaluate the derivative of the k-basis function L^{(m)}_k(xi) of degree m at point xi in [-1,+1] return dL^{(m)}_k(xi)/dxi :arg degree: polynomial degree :arg k: index of basis function :arg xi: position xi.
Definition at line 114 of file nodal_basis.py.
References mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.lagrange_polynomial().
get_Gauss_Lobatto_nodes()
mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.get_Gauss_Lobatto_nodes (self, poly_degree)
Return coordinates of Gauss-Lobatto nodes in [-1, 1] for given polynomial degree.
Roots of deriv(P_{n-1}), where P_{n-1} is the Legendre polynomial and n is the number of nodal points; plus endpoints of the interval.
Definition at line 29 of file nodal_basis.py.
Referenced by mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.nodal_points().
lagrange_polynomial()
mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.lagrange_polynomial (self, degree, k)
Returns k-th basis function L^{(m)}_k(xi) of degree m as a numpy polynomial object :arg degree: polynomial degree :arg k: index of basis function (= index of node)
Definition at line 88 of file nodal_basis.py.
References mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.nodal_points().
Referenced by mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.evaluate(), and mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.evaluate_derivative().
nodal_points()
mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.nodal_points (self, degree)
Set nodal points xi_0, xi_1, ..., xi_p.
Definition at line 65 of file nodal_basis.py.
References mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.get_Gauss_Lobatto_nodes().
Referenced by mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.lagrange_polynomial(), and mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.node1d().
node1d()
mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.node1d (self, degree, j)
Return the j-th nodal point of a Lagrange polynomial of given degree :arg degree: polynomial degree :arg j: index of node.
Reimplemented from mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasis.
Definition at line 79 of file nodal_basis.py.
References mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.nodal_points().
plot_basis_functions()
mghype.api.matrixgenerators.blockmatrix.nodal_basis.NodalBasisGaussLegendre.plot_basis_functions (self)
Implement the below code in a method.
Definition at line 127 of file nodal_basis.py.
The documentation for this class was generated from the following file:
src/mghype/api/matrixgenerators/blockmatrix/nodal_basis.py