Peano
KernelBenchmarks-main.cpp File Reference
#include "KernelBenchmarks-main.h"
#include "config.h"
#include "Constants.h"
#include "repositories/DataRepository.h"
#include "repositories/SolverRepository.h"
#include "repositories/StepRepository.h"
#include "exahype2/CellData.h"
#include "exahype2/dg/DGUtils.h"
#include "kernels/AderSolver/FusedSpaceTimePredictorVolumeIntegral.h"
#include "kernels/AderSolver/FaceIntegral.h"
#include "kernels/AderSolver/MaxScaledEigenvalue.h"
#include "kernels/AderSolver/Quadrature.h"
#include "kernels/AderSolver/DGMatrices.h"
#include "kernels/AderSolver/RiemannSolver.h"
#include "kernels/AderSolver/BufferSizes.h"
#include "peano4/peano4.h"
#include "tarch/NonCriticalAssertions.h"
#include "tarch/accelerator/accelerator.h"
#include "tarch/accelerator/Device.h"
#include "tarch/multicore/multicore.h"
#include "tarch/multicore/Core.h"
#include "tarch/multicore/BooleanSemaphore.h"
#include "tarch/multicore/Lock.h"
#include "tarch/logging/Log.h"
#include "tarch/timing/Measurement.h"
#include "tarch/timing/Watch.h"
#include <cstring>
#include <fenv.h>
Functions
void initInputData (double *Q)
Set input data.
void allocateAndStoreOutcome (const double *const *Q, const double *const maxEigenvalue, const int numberOfCells)
Allocates and stores outcome of one compute kernel.
void freeOutcome (const int numberOfCells)
void validateOutcome (const double *const *Q, const double *const maxEigenvalue, const int numberOfCells)
Validate data against pre-stored simulation outcome.
void reportRuntime (const std::string &kernelIdentificator, const tarch::timing::Measurement &timingKernelLaunch, int numberOfCells)
Reports the runtime and throughput of the benchmarks.
double runKernels (int device, exahype2::CellData< double, double > &cellData, int cellIndex, tarch::timing::Measurement &measurement)
void runBenchmarks (int numberOfCells)
Run the benchmark for one particular number of cells.
int main (int argc, char **argv)
Main routine of the SPH code.
Variables
tarch::logging::Log _log ("::")
constexpr double TimeStamp = 0.0
constexpr double TimeStepSize = 1e-6
const tarch::la::Vector< Dimensions, double > CellCenter = benchmarks::exahype2::kernelbenchmarks::DomainOffset + 0.5*benchmarks::exahype2::kernelbenchmarks::DomainSize
const tarch::la::Vector< Dimensions, double > CellSize = benchmarks::exahype2::kernelbenchmarks::DomainSize / 81.0
constexpr int NumberOfInputEntriesPerCell
constexpr int NumberOfOutputEntriesPerCell = 0
constexpr int NumberOfFiniteVolumesPerCell
double ** validQ = nullptr
double * validMaxEigenvalue = nullptr
bool outcomeIsInvalid = false
tarch::timing::Measurement timingComputeKernel
Function Documentation
allocateAndStoreOutcome()
void allocateAndStoreOutcome (const double *const * Q, const double *const maxEigenvalue, const int numberOfCells)
Allocates and stores outcome of one compute kernel.
Make a persistent snapshot of a solution and assume, from hereon, that this snapshot is the valid data. You can call this routine as often as you want. Only the very first call will trigger a snapshot.
Note: needs to freed using the freeOutcome() routine.
Definition at line 129 of file KernelBenchmarks-main.cpp.
References logInfo, maxEigenvalue, benchmarks::exahype2::kernelbenchmarks::NumberOfOutputEntriesPerCell, validMaxEigenvalue, and validQ.
Referenced by runBenchmarks().
freeOutcome()
void freeOutcome (const int numberOfCells)
Definition at line 146 of file KernelBenchmarks-main.cpp.
References validMaxEigenvalue, and validQ.
Referenced by main().
initInputData()
void initInputData (double * Q)
Set input data.
We use the values from the centralMost Cell in the domain with an arbitrary cell size of 1/81 of the domain size.
TODO: should we update this to actual initial conditions?
Definition at line 95 of file KernelBenchmarks-main.cpp.
References CellCenter, CellSize, dfor, and exahype2::dg::getQuadraturePoint().
main()
int main (int argc, char ** argv)
Main routine of the SPH code.
Definition at line 429 of file KernelBenchmarks-main.cpp.
References freeOutcome(), tarch::multicore::Core::getInstance(), peano4::init(), logInfo, outcomeIsInvalid, runBenchmarks(), and peano4::shutdown().
reportRuntime()
void reportRuntime (const std::string & kernelIdentificator, const tarch::timing::Measurement & timingKernelLaunch, int numberOfCells)
Reports the runtime and throughput of the benchmarks.
First set of outputs refers to the time of the compute kernel itself. Second set of outputs refers to the time including the kernel launch overhead. The throughput is measured in the updates of volumes per second (dof/s).
Definition at line 228 of file KernelBenchmarks-main.cpp.
References tarch::timing::Measurement::getValue(), logInfo, timingComputeKernel, and tarch::timing::Measurement::toString().
runBenchmarks()
void runBenchmarks (int numberOfCells)
Run the benchmark for one particular number of cells.
Parameters
numberOfCells Number of cells to study
Definition at line 349 of file KernelBenchmarks-main.cpp.
References allocateAndStoreOutcome(), assessKernel(), CellCenter, exahype2::CellData< inType, outType, NumFaceTypes >::cellCentre, CellSize, exahype2::CellData< inType, outType, NumFaceTypes >::cellSize, tarch::accelerator::Device::DefaultDevice, double, exahype2::CellData< inType, outType, NumFaceTypes >::dt, tarch::timing::Measurement::erase(), tarch::freeMemory(), tarch::timing::Watch::getCalendarTime(), tarch::Heap, benchmarks::exahype2::kernelbenchmarks::initInputData(), exahype2::CellData< inType, outType, NumFaceTypes >::maxEigenvalue, benchmarks::exahype2::kernelbenchmarks::NumberOfInputEntriesPerCell, benchmarks::exahype2::kernelbenchmarks::NumberOfOutputEntriesPerCell, exahype2::CellData< inType, outType, NumFaceTypes >::QIn, exahype2::CellData< inType, outType, NumFaceTypes >::QOut, benchmarks::exahype2::kernelbenchmarks::reportRuntime(), runKernels(), tarch::timing::Measurement::setValue(), tarch::timing::Watch::stop(), exahype2::CellData< inType, outType, NumFaceTypes >::t, TimeStamp, TimeStepSize, timingComputeKernel, and validateOutcome().
Referenced by main().
runKernels()
double runKernels (int device, exahype2::CellData< double, double > & cellData, int cellIndex, tarch::timing::Measurement & measurement)
Definition at line 248 of file KernelBenchmarks-main.cpp.
References CellCenter, CellSize, tarch::timing::Watch::getCalendarTime(), maxEigenvalue, exahype2::CellData< inType, outType, NumFaceTypes >::QIn, tarch::timing::Measurement::setValue(), tarch::timing::Watch::stop(), TimeStamp, and TimeStepSize.
Referenced by runBenchmarks().
validateOutcome()
void validateOutcome (const double *const * Q, const double *const maxEigenvalue, const int numberOfCells)
Validate data against pre-stored simulation outcome.
Works if and only if storeOutcome has been performed before. Does not abort in case there are errors. If there are errors, we return a status code != 0.
Definition at line 165 of file KernelBenchmarks-main.cpp.
References std::abs(), tarch::la::equals(), logError, maxEigenvalue, benchmarks::exahype2::kernelbenchmarks::NumberOfOutputEntriesPerCell, outcomeIsInvalid, validMaxEigenvalue, and validQ.
Referenced by runBenchmarks().
Variable Documentation
_log
tarch::logging::Log _log("::") ("::")
CellCenter
const tarch::la::Vector<Dimensions,double> CellCenter = benchmarks::exahype2::kernelbenchmarks::DomainOffset + 0.5*benchmarks::exahype2::kernelbenchmarks::DomainSize
Definition at line 49 of file KernelBenchmarks-main.cpp.
Referenced by initInputData(), benchmarks::exahype2::kernelbenchmarks::initInputData(), runBenchmarks(), and runKernels().
CellSize
const tarch::la::Vector<Dimensions,double> CellSize = benchmarks::exahype2::kernelbenchmarks::DomainSize / 81.0
Definition at line 50 of file KernelBenchmarks-main.cpp.
Referenced by initInputData(), benchmarks::exahype2::kernelbenchmarks::initInputData(), runBenchmarks(), and runKernels().
NumberOfFiniteVolumesPerCell
constexpr int NumberOfFiniteVolumesPerCell constexpr
Initial value:
= AderSolver::Order
  * AderSolver::Order
Definition at line 72 of file KernelBenchmarks-main.cpp.
NumberOfInputEntriesPerCell
constexpr int NumberOfInputEntriesPerCell constexpr
Initial value:
= (AderSolver::Order + 1)
  * (AderSolver::Order + 1)
  * (AderSolver::NumberOfUnknowns + AderSolver::NumberOfAuxiliaryVariables)
Definition at line 55 of file KernelBenchmarks-main.cpp.
NumberOfOutputEntriesPerCell
constexpr int NumberOfOutputEntriesPerCell = 0 constexpr
Definition at line 63 of file KernelBenchmarks-main.cpp.
outcomeIsInvalid
bool outcomeIsInvalid = false
Definition at line 83 of file KernelBenchmarks-main.cpp.
Referenced by main(), and validateOutcome().
TimeStamp
constexpr double TimeStamp = 0.0 constexpr
Definition at line 47 of file KernelBenchmarks-main.cpp.
Referenced by runBenchmarks(), and runKernels().
TimeStepSize
constexpr double TimeStepSize = 1e-6 constexpr
Definition at line 48 of file KernelBenchmarks-main.cpp.
Referenced by runBenchmarks(), and runKernels().
timingComputeKernel
tarch::timing::Measurement timingComputeKernel
Definition at line 85 of file KernelBenchmarks-main.cpp.
Referenced by benchmarks::exahype2::kernelbenchmarks::reportRuntime(), reportRuntime(), runBenchmarks(), variant1::runBenchmarks(), variant2::runBenchmarks(), variant3::runBenchmarks(), variant4::runBenchmarks(), variant5::runBenchmarks(), and variant6::runBenchmarks().
validMaxEigenvalue
double* validMaxEigenvalue = nullptr
Definition at line 82 of file KernelBenchmarks-main.cpp.
Referenced by allocateAndStoreOutcome(), freeOutcome(), and validateOutcome().
validQ
double** validQ = nullptr
Definition at line 81 of file KernelBenchmarks-main.cpp.
Referenced by allocateAndStoreOutcome(), freeOutcome(), and validateOutcome().