Peano
tarch::accelerator::tests::MemoryManagerTest Class Reference
#include <MemoryManagerTest.h>
Public Member Functions
MemoryManagerTest ()
virtual ~MemoryManagerTest () override=default
virtual void run () override
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testMemoryAllocationsForOneDevice ()
void testMemoryAllocationsForMultipleDevices ()
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Definition at line 11 of file MemoryManagerTest.h.
Constructor & Destructor Documentation
MemoryManagerTest()
tarch::accelerator::tests::MemoryManagerTest::MemoryManagerTest ()
Definition at line 9 of file MemoryManagerTest.cpp.
~MemoryManagerTest()
virtual tarch::accelerator::tests::MemoryManagerTest::~MemoryManagerTest () override virtual default
Member Function Documentation
run()
void tarch::accelerator::tests::MemoryManagerTest::run () override virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 13 of file MemoryManagerTest.cpp.
References testMethod.
testMemoryAllocationsForMultipleDevices()
void tarch::accelerator::tests::MemoryManagerTest::testMemoryAllocationsForMultipleDevices () private
Definition at line 288 of file MemoryManagerTest.cpp.
References tarch::accelerator::MemoryManager::allocate(), tarch::accelerator::MemoryManager::clear(), tarch::accelerator::MemoryManager::free(), tarch::accelerator::MemoryManager::getInstance(), tarch::Heap, validate, and validateEquals.
testMemoryAllocationsForOneDevice()
void tarch::accelerator::tests::MemoryManagerTest::testMemoryAllocationsForOneDevice () private
Definition at line 19 of file MemoryManagerTest.cpp.
References tarch::accelerator::MemoryManager::allocate(), tarch::accelerator::MemoryManager::clear(), tarch::accelerator::MemoryManager::free(), tarch::accelerator::MemoryManager::getInstance(), tarch::Heap, validate, and validateEquals.
The documentation for this class was generated from the following files:
src/tarch/accelerator/tests/MemoryManagerTest.h
src/tarch/accelerator/tests/MemoryManagerTest.cpp