Peano
swift2.api.actionsets.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets Class Reference
Slight modification of toolbox's update particle action set.
Public Member Functions
__init__ (self, particle_set, particle_particle_interaction_kernel, touch_vertex_first_time_compute_particle_update_kernel, touch_vertex_last_time_compute_particle_update_kernel, prepare_traversal_kernel, unprepare_traversal_kernel, additional_includes, active_particle_set, alter_particle_position_or_interaction_radius, wait_for_all_tasks_to_finish_after_traversal)
Construct.
get_body_of_operation (self, operation_name)
Return actual C++ code snippets to be inserted into C++ code.
get_attributes (self)
Return attributes as copied and pasted into the generated class.
get_action_set_name (self)
Return unique action set name.
Public Member Functions inherited from peano4.toolbox.particles.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets
get_body_of_getGridControlEvents (self)
get_body_of_prepareTraversal (self)
get_body_of_unprepareTraversal (self)
user_should_modify_template (self)
Is the user allowed to modify the output.
get_includes (self)
Return include statements that you need.
get_constructor_body (self)
Define a tailored constructor body.
Public Member Functions inherited from peano4.solversteps.ActionSet.ActionSet
get_static_initialisations (self, full_qualified_classname)
get_destructor_body (self)
Additional Inherited Members
Data Fields inherited from peano4.toolbox.particles.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets
d
Data Fields inherited from peano4.solversteps.ActionSet.ActionSet
descend_invocation_order
parallel
Static Public Attributes inherited from peano4.solversteps.ActionSet.ActionSet
str OPERATION_BEGIN_TRAVERSAL = "beginTraversal"
str OPERATION_END_TRAVERSAL = "endTraversal"
str OPERATION_CREATE_PERSISTENT_VERTEX = "createPersistentVertex"
str OPERATION_DESTROY_PERSISTENT_VERTEX = "destroyPersistentVertex"
str OPERATION_CREATE_HANGING_VERTEX = "createHangingVertex"
str OPERATION_DESTROY_HANGING_VERTEX = "destroyHangingVertex"
str OPERATION_CREATE_PERSISTENT_FACE = "createPersistentFace"
str OPERATION_DESTROY_PERSISTENT_FACE = "destroyPersistentFace"
str OPERATION_CREATE_HANGING_FACE = "createHangingFace"
str OPERATION_DESTROY_HANGING_FACE = "destroyHangingFace"
str OPERATION_CREATE_CELL = "createCell"
str OPERATION_DESTROY_CELL = "destroyCell"
str OPERATION_TOUCH_VERTEX_FIRST_TIME = "touchVertexFirstTime"
str OPERATION_TOUCH_VERTEX_LAST_TIME = "touchVertexLastTime"
str OPERATION_TOUCH_FACE_FIRST_TIME = "touchFaceFirstTime"
str OPERATION_TOUCH_FACE_LAST_TIME = "touchFaceLastTime"
str OPERATION_TOUCH_CELL_FIRST_TIME = "touchCellFirstTime"
str OPERATION_TOUCH_CELL_LAST_TIME = "touchCellLastTime"
Protected Attributes inherited from peano4.toolbox.particles.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets
_particle_set
Detailed Description
Slight modification of toolbox's update particle action set.
The interesting stuff is actually happing in TaskGarphKernelWrappers.py however.
Definition at line 13 of file UpdateParticle_MultiLevelInteraction_Sets.py.
Constructor & Destructor Documentation
__init__()
swift2.api.actionsets.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.__init__ (self, particle_set, particle_particle_interaction_kernel, touch_vertex_first_time_compute_particle_update_kernel, touch_vertex_last_time_compute_particle_update_kernel, prepare_traversal_kernel, unprepare_traversal_kernel, additional_includes, active_particle_set, alter_particle_position_or_interaction_radius, wait_for_all_tasks_to_finish_after_traversal)
Construct.
Parameters
wait_for_all_tasks_to_finish_after_traversal Boolean If this one is set, we insert a wait into the unprepare traversal event. Each rank then waits for all tasks to be completed before it continues. We have a strong synchronisation point.
Reimplemented from peano4.toolbox.particles.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.
Definition at line 25 of file UpdateParticle_MultiLevelInteraction_Sets.py.
References swift2.api.actionsets.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.__init__().
Referenced by swift2.api.actionsets.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.__init__().
Member Function Documentation
get_action_set_name()
swift2.api.actionsets.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.get_action_set_name (self)
Return unique action set name.
Returns a description (word) for the mapping which is also used as class name for the generated type. As a consequence, the result should be one word (if possible) and uppercase. Also, every subclass should overwrite this routine.
The generator will take the result and construct eventually classes similar to MyStep2Dummy.h and MyStep2Dummy.cpp or similar for the example below, where we return Dummy.
Reimplemented from peano4.toolbox.particles.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.
Definition at line 102 of file UpdateParticle_MultiLevelInteraction_Sets.py.
get_attributes()
swift2.api.actionsets.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.get_attributes (self)
Return attributes as copied and pasted into the generated class.
Please note that action sets are not persistent, i.e. there is one object creation per grid sweep per tree.
Reimplemented from peano4.toolbox.particles.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.
Definition at line 94 of file UpdateParticle_MultiLevelInteraction_Sets.py.
References swift2.api.actionsets.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.get_attributes().
Referenced by swift2.api.actionsets.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.get_attributes().
get_body_of_operation()
swift2.api.actionsets.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.get_body_of_operation (self, operation_name)
Return actual C++ code snippets to be inserted into C++ code.
See class' string constants starting with OPERATION_ for possible values of operation_name.
Reimplemented from peano4.toolbox.particles.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.
Definition at line 86 of file UpdateParticle_MultiLevelInteraction_Sets.py.
References swift2.api.actionsets.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.get_body_of_operation().
Referenced by swift2.api.actionsets.UpdateParticle_MultiLevelInteraction_Sets.UpdateParticle_MultiLevelInteraction_Sets.get_body_of_operation().
The documentation for this class was generated from the following file:
python/swift2/api/actionsets/UpdateParticle_MultiLevelInteraction_Sets.py