Peano
SPMCChannel< Item, CELLS_PER_CONSUMER > Class Template Reference
#include <channel.h>
Data Structures
struct ItemWrapper
class Reader
Public Member Functions
SPMCChannel (u32 consumerCountHint=1)
Reader getReader (u32 consumerIdHint=0)
bool put (Item item)
void close ()
bool isClosed () const
Private Member Functions
bool tryPut (ItemWrapper *wrapper, Item item)
std::optional< Item > tryGet (ItemWrapper *wrapper)
Private Attributes
std::unique_ptr< ItemWrapper[]> buf
u32 bufSize = 0
std::atomic_bool closed = false
u64 insertionCandidateIdxHint = 0
u64 version = 1
Detailed Description
template<typename Item, u32 CELLS_PER_CONSUMER = 16>
class SPMCChannel< Item, CELLS_PER_CONSUMER >
Definition at line 10 of file channel.h.
Constructor & Destructor Documentation
SPMCChannel()
template<typename Item , u32 CELLS_PER_CONSUMER = 16> SPMCChannel< Item, CELLS_PER_CONSUMER >::SPMCChannel (u32 consumerCountHint = 1) explicit
Definition at line 101 of file channel.h.
Member Function Documentation
close()
template<typename Item , u32 CELLS_PER_CONSUMER = 16> void SPMCChannel< Item, CELLS_PER_CONSUMER >::close ()
Definition at line 129 of file channel.h.
Referenced by ThreadPoolTaskBackend::createNewTasks().
getReader()
template<typename Item , u32 CELLS_PER_CONSUMER = 16> Reader SPMCChannel< Item, CELLS_PER_CONSUMER >::getReader (u32 consumerIdHint = 0)
Definition at line 105 of file channel.h.
Referenced by ThreadPoolTaskBackend::producerConsumerLoop().
isClosed()
template<typename Item , u32 CELLS_PER_CONSUMER = 16> bool SPMCChannel< Item, CELLS_PER_CONSUMER >::isClosed () const
Definition at line 133 of file channel.h.
Referenced by ThreadPoolTaskBackend::createNewTasks(), and ThreadPoolTaskBackend::producerConsumerLoop().
put()
template<typename Item , u32 CELLS_PER_CONSUMER = 16> bool SPMCChannel< Item, CELLS_PER_CONSUMER >::put (Item item)
Definition at line 109 of file channel.h.
References SPMCChannel< Item, CELLS_PER_CONSUMER >::bufSize, SPMCChannel< Item, CELLS_PER_CONSUMER >::insertionCandidateIdxHint, and SPMCChannel< Item, CELLS_PER_CONSUMER >::tryPut().
Referenced by ThreadPoolTaskBackend::createNewTasks().
tryGet()
template<typename Item , u32 CELLS_PER_CONSUMER = 16> std::optional< Item > SPMCChannel< Item, CELLS_PER_CONSUMER >::tryGet (ItemWrapper * wrapper) private
Definition at line 33 of file channel.h.
References SPMCChannel< Item, CELLS_PER_CONSUMER >::ItemWrapper::item, and SPMCChannel< Item, CELLS_PER_CONSUMER >::ItemWrapper::itemVersion.
Referenced by SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::getFast(), and SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::getOther().
tryPut()
template<typename Item , u32 CELLS_PER_CONSUMER = 16> bool SPMCChannel< Item, CELLS_PER_CONSUMER >::tryPut (ItemWrapper * wrapper, Item item) private
Definition at line 23 of file channel.h.
References SPMCChannel< Item, CELLS_PER_CONSUMER >::ItemWrapper::item, and SPMCChannel< Item, CELLS_PER_CONSUMER >::ItemWrapper::itemVersion.
Referenced by SPMCChannel< Item, CELLS_PER_CONSUMER >::put().
Field Documentation
buf
template<typename Item , u32 CELLS_PER_CONSUMER = 16> std::unique_ptr<ItemWrapper[]> SPMCChannel< Item, CELLS_PER_CONSUMER >::buf private
Definition at line 16 of file channel.h.
Referenced by SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::getFast(), and SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::getOther().
bufSize
template<typename Item , u32 CELLS_PER_CONSUMER = 16> u32 SPMCChannel< Item, CELLS_PER_CONSUMER >::bufSize = 0 private
Definition at line 17 of file channel.h.
Referenced by SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::getOther(), and SPMCChannel< Item, CELLS_PER_CONSUMER >::put().
closed
template<typename Item , u32 CELLS_PER_CONSUMER = 16> std::atomic_bool SPMCChannel< Item, CELLS_PER_CONSUMER >::closed = false private
Definition at line 18 of file channel.h.
insertionCandidateIdxHint
template<typename Item , u32 CELLS_PER_CONSUMER = 16> u64 SPMCChannel< Item, CELLS_PER_CONSUMER >::insertionCandidateIdxHint = 0 private
Definition at line 20 of file channel.h.
Referenced by SPMCChannel< Item, CELLS_PER_CONSUMER >::put().
version
template<typename Item , u32 CELLS_PER_CONSUMER = 16> u64 SPMCChannel< Item, CELLS_PER_CONSUMER >::version = 1 private
Definition at line 21 of file channel.h.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/lang/channel.h