Peano
toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest Class Reference
This is just a default test case that demonstrated how to write unit tests in Peano.
#include <CompressedFloatingPointNumbersTest.h>
Public Member Functions
CompressedFloatingPointNumbersTest ()
virtual ~CompressedFloatingPointNumbersTest ()
virtual void run ()
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testDecomposeWithLongInt ()
void testDecomposeWithInt ()
void testDecomposeWithChar ()
void testBatchDecomposition ()
void testBatchDecompositionWithArrayOfFour ()
void testErrorComputation ()
void testTinyValues ()
void testDecompose ()
Something taken from the ParCo presentation.
void testComposeDecompose ()
Static Private Attributes
static tarch::logging::Log _log
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
This is just a default test case that demonstrated how to write unit tests in Peano.
Feel free to rename, remove, or duplicate it.
Definition at line 23 of file CompressedFloatingPointNumbersTest.h.
Constructor & Destructor Documentation
CompressedFloatingPointNumbersTest()
toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::CompressedFloatingPointNumbersTest ()
Definition at line 16 of file CompressedFloatingPointNumbersTest.cpp.
~CompressedFloatingPointNumbersTest()
toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::~CompressedFloatingPointNumbersTest () virtual
Definition at line 21 of file CompressedFloatingPointNumbersTest.cpp.
Member Function Documentation
run()
void toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::run () virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 25 of file CompressedFloatingPointNumbersTest.cpp.
References testMethod.
testBatchDecomposition()
void toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testBatchDecomposition () private
Definition at line 257 of file CompressedFloatingPointNumbersTest.cpp.
References std::abs(), toolbox::multiprecision::compose(), toolbox::multiprecision::decomposeIntoEightVariants(), logWarning, and validateWithParams4.
testBatchDecompositionWithArrayOfFour()
void toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testBatchDecompositionWithArrayOfFour () private
Definition at line 338 of file CompressedFloatingPointNumbersTest.cpp.
References std::abs(), toolbox::multiprecision::compose(), toolbox::multiprecision::decomposeIntoFourVariants(), and validateWithParams4.
testComposeDecompose()
void toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testComposeDecompose () private
 From ExaHyPE:
assertion in file /home/tobias/git/ExaHyPE/Code/./ExaHyPE/exahype/solvers/ADERDGSolver.cpp, line 2983 failed: tarch::la::equals(DataHeap::getInstance().getData(heapIndex)[i], reconstructedValue, CompressionAccuracy) parameter DataHeap::getInstance().getData(heapIndex)[i]: 1.68855695855260723448e+00 parameter reconstructedValue: 1.01768855695855017984e+03 parameter DataHeap::getInstance().getData(heapIndex)[i] - reconstructedValue: -1.01599999999999761258e+03 parameter CompressionAccuracy: 1.00000000000000006228e-09 parameter bytesForMantissa: 5 ExaHyPE-Euler: /home/tobias/git/ExaHyPE/Code/./ExaHyPE/exahype/solvers/ADERDGSolver.cpp:2983: void exahype::solvers::ADERDGSolver::glueTogether(int, int, int): Assertion ‘false’ failed.
But I used /4.0 here for the accuracy.
Definition at line 454 of file CompressedFloatingPointNumbersTest.cpp.
References toolbox::multiprecision::compose(), toolbox::multiprecision::decompose(), toolbox::multiprecision::findMostAgressiveCompression(), validateEquals, and validateNumericalEqualsWithParams1.
testDecompose()
void toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testDecompose () private
Something taken from the ParCo presentation.
Definition at line 380 of file CompressedFloatingPointNumbersTest.cpp.
References std::abs(), toolbox::multiprecision::compose(), toolbox::multiprecision::decomposeIntoEightVariants(), validateWithParams5, and validateWithParams6.
testDecomposeWithChar()
void toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testDecomposeWithChar () private
Definition at line 199 of file CompressedFloatingPointNumbersTest.cpp.
References std::abs(), toolbox::multiprecision::compose(), toolbox::multiprecision::decompose(), and validateWithParams4.
testDecomposeWithInt()
void toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testDecomposeWithInt () private
Definition at line 141 of file CompressedFloatingPointNumbersTest.cpp.
References std::abs(), toolbox::multiprecision::compose(), toolbox::multiprecision::decompose(), validateEqualsWithParams2, validateNumericalEqualsWithParams2, and validateWithParams4.
testDecomposeWithLongInt()
void toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testDecomposeWithLongInt () private
Definition at line 83 of file CompressedFloatingPointNumbersTest.cpp.
References toolbox::multiprecision::compose(), toolbox::multiprecision::decompose(), and validateEqualsWithParams2.
testErrorComputation()
void toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testErrorComputation () private
Definition at line 441 of file CompressedFloatingPointNumbersTest.cpp.
References std::abs(), toolbox::multiprecision::compose(), toolbox::multiprecision::decomposeIntoEightVariants(), and validateNumericalEquals.
testTinyValues()
void toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testTinyValues () private
Definition at line 42 of file CompressedFloatingPointNumbersTest.cpp.
References toolbox::multiprecision::compose(), toolbox::multiprecision::decompose(), toolbox::multiprecision::findMostAgressiveCompression(), validateEquals, validateEqualsWithParams2, validateEqualsWithParams7, validateNumericalEqualsWithParams2, and validateNumericalEqualsWithParams4.
Field Documentation
_log
tarch::logging::Log toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::_log static private
Definition at line 25 of file CompressedFloatingPointNumbersTest.h.
The documentation for this class was generated from the following files:
src/toolbox/multiprecision/tests/CompressedFloatingPointNumbersTest.h
src/toolbox/multiprecision/tests/CompressedFloatingPointNumbersTest.cpp