Peano
ccz4-main.cpp File Reference
#include <iomanip>
#include "config.h"
#include "Constants.h"
#include "ccz4-main.h"
#include "exahype2/UnitTests.h"
#include "exahype2/UserInterface.h"
#include "observers/CreateGrid.h"
#include "observers/CreateGridAndConvergeLoadBalancing.h"
#include "observers/CreateGridButPostponeRefinement.h"
#include "observers/InitGrid.h"
#include "observers/PlotSolution.h"
#include "observers/CheckpointSolution.h"
#include "observers/TimeStep.h"
#include "peano4/peano4.h"
#include "peano4/UnitTests.h"
#include "repositories/DataRepository.h"
#include "repositories/SolverRepository.h"
#include "repositories/StepRepository.h"
#include "tarch/UnitTests.h"
#include "peano4/grid/Spacetree.h"
#include "peano4/parallel/SpacetreeSet.h"
#include "tarch/logging/Log.h"
#include "tarch/logging/LogFilter.h"
#include "tarch/logging/Statistics.h"
#include "tarch/multicore/Core.h"
#include "tarch/multicore/multicore.h"
#include "tarch/multicore/otter.h"
#include "tarch/NonCriticalAssertions.h"
#include "tarch/tests/TreeTestCaseCollection.h"
#include "tarch/timing/Measurement.h"
#include "tarch/timing/Watch.h"
#include "toolbox/blockstructured/UnitTests.h"
#include "toolbox/loadbalancing/loadbalancing.h"
Functions
bool selectNextAlgorithmicStep ()
Decide which step to run next.
void step ()
int main (int argc, char **argv)
Main routine of the SPH code.
Variables
tarch::logging::Log _log ("::")
tarch::timing::Measurement timePerMeshSweepMeasurement
tarch::timing::Measurement gridConstructionMeasurement
tarch::timing::Measurement timeStepMeasurement
tarch::timing::Measurement plotMeasurement
Function Documentation
main()
int main (int argc, char ** argv)
Main routine of the SPH code.
Definition at line 530 of file ccz4-main.cpp.
References tarch::mpi::Rank::abort(), tarch::tests::TreeTestCaseCollection::addTestCase(), tarch::logging::Statistics::clear(), tarch::timing::Measurement::getAccumulatedValue(), tarch::timing::Watch::getCalendarTime(), peano4::parallel::Node::getInstance(), tarch::logging::Statistics::getInstance(), tarch::mpi::Rank::getInstance(), tarch::multicore::Core::getInstance(), tarch::tests::TestCase::getNumberOfErrors(), exahype2::getUnitTests(), peano4::getUnitTests(), tarch::getUnitTests(), toolbox::blockstructured::getUnitTests(), tarch::timing::Measurement::getValue(), gridConstructionMeasurement, tarch::initNonCriticalAssertionEnvironment(), tarch::mpi::Rank::isGlobalMaster(), logError, logInfo, OTTER_FINALISE, OTTER_INITIALISE, plotMeasurement, tarch::tests::TreeTestCaseCollection::run(), selectNextAlgorithmicStep(), tarch::timing::Measurement::setValue(), tarch::shutdownNonCriticalAssertionEnvironment(), tarch::timing::Watch::start(), step(), tarch::timing::Watch::stop(), timePerMeshSweepMeasurement, timeStepMeasurement, tarch::timing::Measurement::toString(), and tarch::logging::Statistics::writeToCSV().
selectNextAlgorithmicStep()
bool selectNextAlgorithmicStep ()
Decide which step to run next.
Control of the parallel grid construction
Returns
continues to run
Definition at line 68 of file ccz4-main.cpp.
References peano4::parallel::SpacetreeSet::getGridStatistics(), peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), peano4::grid::GridStatistics::getMinH(), tarch::hasNonCriticalAssertionBeenViolated(), logDebug, logError, logInfo, logWarning, tarch::la::max(), peano4::parallel::Node::setNextProgramStep(), and toString().
Referenced by main().
step()
void step ()
[Additional mesh sweep case step]
[Additional mesh sweep case step]
Definition at line 254 of file ccz4-main.cpp.
References _log, assertion, otter::phase::create_grid, otter::phase::create_grid_converge, otter::phase::create_grid_no_refine, tarch::timing::Watch::getCalendarTime(), peano4::parallel::Node::getCurrentProgramStep(), peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), tarch::logging::LogFilter::getInstance(), tarch::mpi::Rank::getInstance(), tarch::multicore::Core::getInstance(), tarch::multicore::Core::getNumberOfThreads(), gridConstructionMeasurement, otter::phase::init, logInfo, OTTER_DEFINE_TASK, OTTER_PHASE_SWITCH, OTTER_TASK_END, OTTER_TASK_START, OTTER_TASK_WAIT_IMPLICIT, otter::phase::plot, plotMeasurement, tarch::timing::Measurement::setValue(), tarch::timing::Watch::start(), otter::label::step, tarch::timing::Watch::stop(), tarch::logging::LogFilter::switchProgramPhase(), otter::phase::timestep, timeStepMeasurement, and peano4::parallel::SpacetreeSet::traverse().
Referenced by main().
Variable Documentation
_log
tarch::logging::Log _log("::") ("::")
Referenced by step().
gridConstructionMeasurement
tarch::timing::Measurement gridConstructionMeasurement
Definition at line 55 of file ccz4-main.cpp.
Referenced by main(), and step().
plotMeasurement
tarch::timing::Measurement plotMeasurement
Definition at line 57 of file ccz4-main.cpp.
Referenced by main(), and step().
timePerMeshSweepMeasurement
tarch::timing::Measurement timePerMeshSweepMeasurement
Definition at line 54 of file ccz4-main.cpp.
Referenced by main().
timeStepMeasurement
tarch::timing::Measurement timeStepMeasurement
Definition at line 56 of file ccz4-main.cpp.
Referenced by main(), and step().