Peano
mghype::matrixfree::solvers::SolverStatistics Class Reference
#include <SolverStatistics.h>
Public Member Functions
SolverStatistics (double tolerance=0.0)
bool terminationCriterionHolds ()
void updateGlobalResidual (double residual, const tarch::la::Vector< Dimensions, double > &h)
void updateGlobalPrecondResidual (double residual)
void updateGlobalSolutionUpdates (double deltaU, const tarch::la::Vector< Dimensions, double > &h)
void updateMinMaxMeshSize (const tarch::la::Vector< Dimensions, double > &h)
void clearGlobalPrecondResidualUpdate ()
double getGlobalResidualMaxNorm () const
std::array< double, 2 > getGlobalPrecondResidualNorms () const
std::string toString () const
void merge (const SolverStatistics &statistics)
std::string reportPrecondNorms () const
void clearGlobalResidualAndSolutionUpdate ()
Clear the global mesh stats.
void synchroniseGlobalResidualAndSolutionUpdate ()
Synchronise the global stats between MPI ranks.
Protected Attributes
const double _tolerance
double _minH
Observed mesh width.
double _maxH
Observed mesh width.
double _globalResidualMaxNorm
double _globalResidualEukledianNormSquared
double _globalResidualHNormSquared
double _initialGlobalResidualMaxNorm
double _initialGlobalResidualEukledianNormSquared
double _initialGlobalResidualHNormSquared
double _previousGlobalResidualMaxNorm
double _previousGlobalResidualEukledianNormSquared
double _previousGlobalResidualHNormSquared
double _globalDeltaUMaxNorm
double _globalDeltaUEukledianNormSquared
double _globalDeltaUHNormSquared
double _globalPrecondResidualMaxNorm
double _globalPrecondResidualEukledianNormSquared
Static Protected Attributes
static tarch::logging::Log _log
Detailed Description
Definition at line 25 of file SolverStatistics.h.
Constructor & Destructor Documentation
SolverStatistics()
mghype::matrixfree::solvers::SolverStatistics::SolverStatistics (double tolerance = 0.0)
Parameters
tolerance You can use the default parameter if you later on merge it into a proper class.
Definition at line 10 of file SolverStatistics.cpp.
References clearGlobalPrecondResidualUpdate(), and clearGlobalResidualAndSolutionUpdate().
Member Function Documentation
clearGlobalPrecondResidualUpdate()
void mghype::matrixfree::solvers::SolverStatistics::clearGlobalPrecondResidualUpdate ()
Definition at line 80 of file SolverStatistics.cpp.
Referenced by SolverStatistics().
clearGlobalResidualAndSolutionUpdate()
void mghype::matrixfree::solvers::SolverStatistics::clearGlobalResidualAndSolutionUpdate ()
Clear the global mesh stats.
Most solvers call this one in beginMeshSweep().
Definition at line 67 of file SolverStatistics.cpp.
Referenced by SolverStatistics().
getGlobalPrecondResidualNorms()
std::array< double, 2 > mghype::matrixfree::solvers::SolverStatistics::getGlobalPrecondResidualNorms () const
Definition at line 21 of file SolverStatistics.cpp.
getGlobalResidualMaxNorm()
double mghype::matrixfree::solvers::SolverStatistics::getGlobalResidualMaxNorm () const
Definition at line 17 of file SolverStatistics.cpp.
merge()
void mghype::matrixfree::solvers::SolverStatistics::merge (const SolverStatistics & statistics)
Definition at line 172 of file SolverStatistics.cpp.
References _globalDeltaUMaxNorm, _globalResidualEukledianNormSquared, _globalResidualMaxNorm, _maxH, and _minH.
reportPrecondNorms()
std::string mghype::matrixfree::solvers::SolverStatistics::reportPrecondNorms () const
Definition at line 136 of file SolverStatistics.cpp.
synchroniseGlobalResidualAndSolutionUpdate()
void mghype::matrixfree::solvers::SolverStatistics::synchroniseGlobalResidualAndSolutionUpdate ()
Synchronise the global stats between MPI ranks.
Becomes nop if there is no MPI. The routine also takes care of the minimum and maximum mesh size tracked.
Definition at line 147 of file SolverStatistics.cpp.
References tarch::mpi::Rank::getGlobalMasterRank(), and tarch::mpi::Rank::getInstance().
terminationCriterionHolds()
bool mghype::matrixfree::solvers::SolverStatistics::terminationCriterionHolds ()
Definition at line 26 of file SolverStatistics.cpp.
References tarch::la::equals(), logDebug, logInfo, and logWarning.
toString()
std::string mghype::matrixfree::solvers::SolverStatistics::toString () const
Definition at line 121 of file SolverStatistics.cpp.
Referenced by mghype::matrixfree::solvers::Solver::toString().
updateGlobalPrecondResidual()
void mghype::matrixfree::solvers::SolverStatistics::updateGlobalPrecondResidual (double residual)
Definition at line 94 of file SolverStatistics.cpp.
References std::abs().
updateGlobalResidual()
void mghype::matrixfree::solvers::SolverStatistics::updateGlobalResidual (double residual, const tarch::la::Vector< Dimensions, double > & h)
Definition at line 85 of file SolverStatistics.cpp.
References std::abs(), and tarch::la::volume().
updateGlobalSolutionUpdates()
void mghype::matrixfree::solvers::SolverStatistics::updateGlobalSolutionUpdates (double deltaU, const tarch::la::Vector< Dimensions, double > & h)
Definition at line 102 of file SolverStatistics.cpp.
References std::abs(), and tarch::la::volume().
updateMinMaxMeshSize()
void mghype::matrixfree::solvers::SolverStatistics::updateMinMaxMeshSize (const tarch::la::Vector< Dimensions, double > & h)
Definition at line 112 of file SolverStatistics.cpp.
References tarch::la::max(), and tarch::la::min().
Field Documentation
_globalDeltaUEukledianNormSquared
double mghype::matrixfree::solvers::SolverStatistics::_globalDeltaUEukledianNormSquared protected
Definition at line 116 of file SolverStatistics.h.
_globalDeltaUHNormSquared
double mghype::matrixfree::solvers::SolverStatistics::_globalDeltaUHNormSquared protected
Definition at line 117 of file SolverStatistics.h.
_globalDeltaUMaxNorm
double mghype::matrixfree::solvers::SolverStatistics::_globalDeltaUMaxNorm protected
Definition at line 115 of file SolverStatistics.h.
Referenced by merge().
_globalPrecondResidualEukledianNormSquared
double mghype::matrixfree::solvers::SolverStatistics::_globalPrecondResidualEukledianNormSquared protected
Definition at line 120 of file SolverStatistics.h.
_globalPrecondResidualMaxNorm
double mghype::matrixfree::solvers::SolverStatistics::_globalPrecondResidualMaxNorm protected
Definition at line 119 of file SolverStatistics.h.
_globalResidualEukledianNormSquared
double mghype::matrixfree::solvers::SolverStatistics::_globalResidualEukledianNormSquared protected
Definition at line 104 of file SolverStatistics.h.
Referenced by merge().
_globalResidualHNormSquared
double mghype::matrixfree::solvers::SolverStatistics::_globalResidualHNormSquared protected
Definition at line 105 of file SolverStatistics.h.
_globalResidualMaxNorm
double mghype::matrixfree::solvers::SolverStatistics::_globalResidualMaxNorm protected
Definition at line 103 of file SolverStatistics.h.
Referenced by merge().
_initialGlobalResidualEukledianNormSquared
double mghype::matrixfree::solvers::SolverStatistics::_initialGlobalResidualEukledianNormSquared protected
Definition at line 108 of file SolverStatistics.h.
_initialGlobalResidualHNormSquared
double mghype::matrixfree::solvers::SolverStatistics::_initialGlobalResidualHNormSquared protected
Definition at line 109 of file SolverStatistics.h.
_initialGlobalResidualMaxNorm
double mghype::matrixfree::solvers::SolverStatistics::_initialGlobalResidualMaxNorm protected
Definition at line 107 of file SolverStatistics.h.
_log
tarch::logging::Log mghype::matrixfree::solvers::SolverStatistics::_log static protected
Definition at line 86 of file SolverStatistics.h.
_maxH
double mghype::matrixfree::solvers::SolverStatistics::_maxH protected
Observed mesh width.
Definition at line 101 of file SolverStatistics.h.
Referenced by merge().
_minH
double mghype::matrixfree::solvers::SolverStatistics::_minH protected
Observed mesh width.
Definition at line 96 of file SolverStatistics.h.
Referenced by merge().
_previousGlobalResidualEukledianNormSquared
double mghype::matrixfree::solvers::SolverStatistics::_previousGlobalResidualEukledianNormSquared protected
Definition at line 112 of file SolverStatistics.h.
_previousGlobalResidualHNormSquared
double mghype::matrixfree::solvers::SolverStatistics::_previousGlobalResidualHNormSquared protected
Definition at line 113 of file SolverStatistics.h.
_previousGlobalResidualMaxNorm
double mghype::matrixfree::solvers::SolverStatistics::_previousGlobalResidualMaxNorm protected
Definition at line 111 of file SolverStatistics.h.
_tolerance
const double mghype::matrixfree::solvers::SolverStatistics::_tolerance protected
See also
terminationCriterionHolds()
Definition at line 91 of file SolverStatistics.h.
The documentation for this class was generated from the following files:
src/mghype/matrixfree/solvers/SolverStatistics.h
src/mghype/matrixfree/solvers/SolverStatistics.cpp