Peano
swift2::kernels::legacy::hydroDimensions Namespace Reference
Functions
template<typename T >
InlineMethod T pow_dimension (T x)
returns x^ndim
template<typename T >
InlineMethod T pow_inv_dimension (T x)
Returns \(x^{1/d}\).
template<typename T >
InlineMethod T pow_dimension_plus_one (T x)
returns x^{ndim+1}
template<typename T >
InlineMethod T pow_dimension_minus_one (T x)
returns x^{ndim-1}
Function Documentation
pow_dimension()
template<typename T > InlineMethod T swift2::kernels::legacy::hydroDimensions::pow_dimension (T x)
returns x^ndim
Definition at line 20 of file hydro_dimensions.h.
Referenced by swift2::kernels::legacy::hydro_end_density(), and swift2::kernels::legacy::hydro_update_smoothing_length_and_rerun_if_required().
pow_dimension_minus_one()
template<typename T > InlineMethod T swift2::kernels::legacy::hydroDimensions::pow_dimension_minus_one (T x)
returns x^{ndim-1}
Definition at line 68 of file hydro_dimensions.h.
pow_dimension_plus_one()
template<typename T > InlineMethod T swift2::kernels::legacy::hydroDimensions::pow_dimension_plus_one (T x)
returns x^{ndim+1}
Definition at line 51 of file hydro_dimensions.h.
References temp.
Referenced by swift2::kernels::legacy::force_kernel().
pow_inv_dimension()
template<typename T > InlineMethod T swift2::kernels::legacy::hydroDimensions::pow_inv_dimension (T x)
Returns \(x^{1/d}\).
Definition at line 35 of file hydro_dimensions.h.