Peano
FaceBoundary Class Reference
#include <faceBoundary.h>
Public Member Functions
~FaceBoundary ()
FaceBoundary (Face const &face)
FaceBoundary (const FaceBoundary &other)
FaceBoundary & operator= (FaceBoundary other)
FaceBoundary (double a_offset[3], double a_size[3], int a_range[3], Coordinate a_coords[2])
FaceBoundary (Coordinate a_coords[2], double a_position, Edge &a_left, Edge &a_right, Edge &a_bottom, Edge &a_top)
Coordinate getCoord (int i) const
void getCoord (Coordinate a_coord[2]) const
int getIndexSize (int i) const
void getIndexSize (int a_index_size[3]) const
double getPosition () const
Edge & getEdge (Coordinate coord, bool upper)
void getIndexRange (Coordinate coord, std::vector< int > &a_range) const
void setEdge (Coordinate coord, bool upper, Edge const &other)
void split (Coordinate c, int intersection_index, Edge intersection_path, FaceBoundary &left, FaceBoundary &right)
void checkConformity ()
std::string printNodes ()
Private Attributes
Edge left_edge
Edge right_edge
Edge bottom_edge
Edge top_edge
Coordinate coords [2]
int index_size [3]
double position
Friends
std::ostream & operator<< (std::ostream &ss, const FaceBoundary &f)
Detailed Description
Definition at line 30 of file faceBoundary.h.
Constructor & Destructor Documentation
~FaceBoundary()
FaceBoundary::~FaceBoundary ()
Definition at line 36 of file faceBoundary.h.
FaceBoundary() [1/4]
FaceBoundary::FaceBoundary (Face const & face)
Definition at line 76 of file faceBoundary.cpp.
References bottom_edge, checkConformity(), coords, coordToString(), Face::getCoord(), Face::getIndexRange(), Face::getIndexSize(), Face::getPosition(), index_size, left_edge, NCOORDS, position, Edge::push_back(), right_edge, and top_edge.
Referenced by split().
FaceBoundary() [2/4]
FaceBoundary::FaceBoundary (const FaceBoundary & other)
Definition at line 19 of file faceBoundary.cpp.
References checkConformity(), coords, index_size, and position.
FaceBoundary() [3/4]
FaceBoundary::FaceBoundary (double a_offset[3], double a_size[3], int a_range[3], Coordinate a_coords[2])
Definition at line 120 of file faceBoundary.cpp.
References bottom_edge, coords, double, getNormal(), index_size, left_edge, NCOORDS, position, Edge::resize(), right_edge, and top_edge.
FaceBoundary() [4/4]
FaceBoundary::FaceBoundary (Coordinate a_coords[2], double a_position, Edge & a_left, Edge & a_right, Edge & a_bottom, Edge & a_top)
Definition at line 45 of file faceBoundary.cpp.
References checkConformity(), coords, getNormal(), index_size, left_edge, Edge::numNodes(), and top_edge.
Member Function Documentation
checkConformity()
void FaceBoundary::checkConformity ()
Definition at line 365 of file faceBoundary.cpp.
References bottom_edge, coords, Edge::getDirection(), index_size, left_edge, Edge::numNodes(), right_edge, and top_edge.
Referenced by FaceBoundary(), FaceBoundary(), FaceBoundary(), and operator=().
getCoord() [1/2]
void FaceBoundary::getCoord (Coordinate a_coord[2]) const
Definition at line 210 of file faceBoundary.cpp.
References coords.
getCoord() [2/2]
Coordinate FaceBoundary::getCoord (int i) const
Definition at line 206 of file faceBoundary.cpp.
References coords.
getEdge()
Edge & FaceBoundary::getEdge (Coordinate coord, bool upper)
Definition at line 227 of file faceBoundary.cpp.
References bottom_edge, coords, left_edge, right_edge, and top_edge.
Referenced by BlockBoundary::BlockBoundary(), and split().
getIndexRange()
void FaceBoundary::getIndexRange (Coordinate coord, std::vector< int > & a_range) const
getIndexSize() [1/2]
void FaceBoundary::getIndexSize (int a_index_size[3]) const
Definition at line 219 of file faceBoundary.cpp.
References index_size.
getIndexSize() [2/2]
int FaceBoundary::getIndexSize (int i) const
Definition at line 215 of file faceBoundary.cpp.
References index_size.
getPosition()
double FaceBoundary::getPosition () const
Definition at line 223 of file faceBoundary.cpp.
References position.
operator=()
FaceBoundary & FaceBoundary::operator= (FaceBoundary other)
Definition at line 32 of file faceBoundary.cpp.
References bottom_edge, checkConformity(), coords, index_size, left_edge, position, right_edge, and top_edge.
printNodes()
std::string FaceBoundary::printNodes ()
Definition at line 397 of file faceBoundary.cpp.
References bottom_edge, left_edge, Edge::printEdge(), right_edge, and top_edge.
setEdge()
void FaceBoundary::setEdge (Coordinate coord, bool upper, Edge const & other)
Definition at line 248 of file faceBoundary.cpp.
References bottom_edge, coords, left_edge, right_edge, and top_edge.
split()
void FaceBoundary::split (Coordinate c, int intersection_index, Edge intersection_path, FaceBoundary & left, FaceBoundary & right)
Definition at line 280 of file faceBoundary.cpp.
References bottom_edge, coords, coordToString(), FaceBoundary(), Edge::getDirection(), getEdge(), NCOORDS, Edge::numNodes(), position, Edge::remesh(), Edge::size(), Edge::split(), and top_edge.
Referenced by Face::split().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & ss, const FaceBoundary & f) friend
Definition at line 266 of file faceBoundary.cpp.
Field Documentation
bottom_edge
Edge FaceBoundary::bottom_edge private
Definition at line 81 of file faceBoundary.h.
Referenced by checkConformity(), FaceBoundary(), FaceBoundary(), getEdge(), operator=(), printNodes(), setEdge(), and split().
coords
Coordinate FaceBoundary::coords[2] private
Definition at line 84 of file faceBoundary.h.
Referenced by checkConformity(), FaceBoundary(), FaceBoundary(), FaceBoundary(), FaceBoundary(), getCoord(), getCoord(), getEdge(), operator=(), setEdge(), and split().
index_size
int FaceBoundary::index_size[3] private
Definition at line 85 of file faceBoundary.h.
Referenced by checkConformity(), FaceBoundary(), FaceBoundary(), FaceBoundary(), FaceBoundary(), getIndexSize(), getIndexSize(), and operator=().
left_edge
Edge FaceBoundary::left_edge private
Definition at line 79 of file faceBoundary.h.
Referenced by checkConformity(), FaceBoundary(), FaceBoundary(), FaceBoundary(), getEdge(), operator=(), printNodes(), and setEdge().
position
double FaceBoundary::position private
Definition at line 86 of file faceBoundary.h.
Referenced by FaceBoundary(), FaceBoundary(), FaceBoundary(), getPosition(), operator=(), and split().
right_edge
Edge FaceBoundary::right_edge private
Definition at line 80 of file faceBoundary.h.
Referenced by checkConformity(), FaceBoundary(), FaceBoundary(), getEdge(), operator=(), printNodes(), and setEdge().
top_edge
Edge FaceBoundary::top_edge private
Definition at line 82 of file faceBoundary.h.
Referenced by checkConformity(), FaceBoundary(), FaceBoundary(), FaceBoundary(), getEdge(), operator=(), printNodes(), setEdge(), and split().
The documentation for this class was generated from the following files:
src/toolbox/curvi/geometry/faceBoundary.h
src/toolbox/curvi/geometry/faceBoundary.cpp