Peano
TP::TwoPunctures Class Reference
#include <TwoPunctures.h>
Public Member Functions
double *_d0contig __attribute__ ((aligned(32)))
double *_d0contig_low __attribute__ ((aligned(32)))
TwoPunctures ()
void set_initial_guess (derivs v)
double TestSolution (double A, double B, double X, double R, double phi)
void TestVector_w (double *par, int nvar, int n1, int n2, int n3, double *w)
void Run ()
void Interpolate (const double *const pos, double *Q, bool low_res=false)
Interpolation function for an external caller.
int Index (int ivar, int i, int j, int k, int nvar, int n1, int n2, int n3)
void allocate_derivs (derivs *v, int n)
void free_derivs (derivs *v, int n)
void Derivatives_AB3 (int nvar, int n1, int n2, int n3, derivs v)
void F_of_v (int nvar, int n1, int n2, int n3, derivs v, double *F, derivs u)
void J_times_dv (int nvar, int n1, int n2, int n3, derivs dv, double *Jdv, derivs u)
void JFD_times_dv (int i, int j, int k, int nvar, int n1, int n2, int n3, derivs dv, derivs u, double *values)
void SetMatrix_JFD (int nvar, int n1, int n2, int n3, derivs u, int *ncols, int **cols, double **Matrix)
double PunctEvalAtArbitPosition (double *v, int ivar, double A, double B, double phi, int nvar, int n1, int n2, int n3)
void calculate_derivs (int i, int j, int k, int ivar, int nvar, int n1, int n2, int n3, derivs v, derivs vv)
double interpol (double a, double b, double c, derivs v)
double PunctTaylorExpandAtArbitPosition (int ivar, int nvar, int n1, int n2, int n3, derivs v, double x, double y, double z)
double PunctIntPolAtArbitPosition (int ivar, int nvar, int n1, int n2, int n3, derivs v, double x, double y, double z)
void SpecCoef (int n1, int n2, int n3, int ivar, double *v, double *cf)
double PunctEvalAtArbitPositionFast (double *v, int ivar, double A, double B, double phi, int nvar, int n1, int n2, int n3)
Fast Spectral Interpolation Routine Stuff.
double PunctEvalAtArbitPositionFaster (double A, double B, double phi)
double PunctEvalAtArbitPositionFasterLowRes (double A, double B, double phi)
double PunctIntPolAtArbitPositionFast (derivs v, double x, double y, double z, bool low_res=false)
void AB_To_XR (int nvar, double A, double B, double *X, double *R, derivs U)
void C_To_c (int nvar, double X, double R, double *x, double *r, derivs U)
void rx3_To_xyz (int nvar, double x, double r, double phi, double *y, double *z, derivs U)
double BY_KKofxyz (double x, double y, double z)
void BY_Aijofxyz (double x, double y, double z, double Aij[3][3])
void NonLinEquations (double rho_adm, double A, double B, double X, double R, double x, double r, double phi, double y, double z, derivs U, double *values)
void LinEquations (double A, double B, double X, double R, double x, double r, double phi, double y, double z, derivs dU, derivs U, double *values)
void TestRelax (int nvar, int n1, int n2, int n3, derivs v, double *dv)
void Newton (int nvar, int n1, int n2, int n3, derivs v, double tol, int itmax)
int bicgstab (int const nvar, int const n1, int const n2, int const n3, derivs v, derivs dv, int const output, int const itmax, double const tol, double *TP_RESTRICT const normres)
double norm_inf (double const *TP_RESTRICT const F, int const ntotal)
void relax (double *TP_RESTRICT const dv, int const nvar, int const n1, int const n2, int const n3, double const *TP_RESTRICT const rhs, int const *TP_RESTRICT const ncols, int const *TP_RESTRICT const *TP_RESTRICT const cols, double const *TP_RESTRICT const *TP_RESTRICT const JFD)
void resid (double *TP_RESTRICT const res, int const ntotal, double const *TP_RESTRICT const dv, double const *TP_RESTRICT const rhs, int const *TP_RESTRICT const ncols, int const *TP_RESTRICT const *TP_RESTRICT const cols, double const *TP_RESTRICT const *TP_RESTRICT const JFD)
void LineRelax_al (double *TP_RESTRICT const dv, int const j, int const k, int const nvar, int const n1, int const n2, int const n3, double const *TP_RESTRICT const rhs, int const *TP_RESTRICT const ncols, int const *TP_RESTRICT const *TP_RESTRICT const cols, double const *TP_RESTRICT const *TP_RESTRICT const JFD)
void LineRelax_be (double *TP_RESTRICT const dv, int const i, int const k, int const nvar, int const n1, int const n2, int const n3, double const *TP_RESTRICT const rhs, int const *TP_RESTRICT const ncols, int const *TP_RESTRICT const *TP_RESTRICT const cols, double const *TP_RESTRICT const *TP_RESTRICT const JFD)
Public Member Functions inherited from TP::Parameters
Parameters ()
void PrintParameters ()
Public Member Functions inherited from TP::LoggingAdapter
void TP_LOG (const char *fmt,...)
void TP_ERROR (const char *fmt,...)
void TP_INFO (const char *fmt,...)
void TP_WARN (const char *fmt,...)
LoggingAdapter ()
Data Fields
GRID_SETUP_METHOD gsm
int nvar
int n1
int n2
int n3
int _n1_low
int _n2_low
int _n3_low
derivs u
derivs v
derivs cf_v
int antisymmetric_lapse
int averaged_lapse
int pmn_lapse
int brownsville_lapse
bool runned
an internal check
Data Fields inherited from TP::Parameters
bool verbose
bool keep_u_around
bool give_bare_mass
double adm_tol
std::string grid_setup_method
std::string initial_lapse
double Newton_tol
int Newton_maxit
double TP_epsilon
double TP_Tiny
double TP_Extend_Radius
double par_b
double par_bv
double par_m_plus
double par_m_minus
double target_M_plus
double target_M_minus
double par_P_plus [3]
double par_P_minus [3]
double par_S_plus [3]
double par_S_minus [3]
double center_offset [3]
double initial_lapse_psi_exponent
bool swap_xz
bool use_sources
bool rescale_sources
bool use_external_initial_guess
bool do_residuum_debug_output
bool do_initial_debug_output
bool multiply_old_lapse
bool schedule_in_ADMBase_InitialData
bool solve_momentum_constraint
std::string metric_type
std::string conformal_storage
int conformal_state
double J1
double J2
double J3
double mp
double mm
double mp_adm
double mm_adm
Data Fields inherited from TP::LoggingAdapter
logger * log
Additional Inherited Members
Static Public Attributes inherited from TP::Parameters
static constexpr int npoints_A = 30
static constexpr int npoints_B = 30
static constexpr int npoints_phi = 16
static constexpr int npoints_A_low = 3
static constexpr int npoints_B_low = 3
static constexpr int npoints_phi_low = 4
Detailed Description
Definition at line 47 of file TwoPunctures.h.
Constructor & Destructor Documentation
TwoPunctures()
TP::TwoPunctures::TwoPunctures ()
Definition at line 65 of file TwoPunctures.h.
References n1, n2, n3, nvar, and runned.
Member Function Documentation
__attribute__() [1/2]
double *_d0contig TP::TwoPunctures::__attribute__ ((aligned(32)))
__attribute__() [2/2]
double *_d0contig_low TP::TwoPunctures::__attribute__ ((aligned(32)))
AB_To_XR()
void TP::TwoPunctures::AB_To_XR (int nvar, double A, double B, double * X, double * R, derivs U)
Definition at line 18 of file CoordTransf.cpp.
References TP::DERIVS::d1, TP::DERIVS::d11, TP::DERIVS::d12, TP::DERIVS::d13, TP::DERIVS::d2, TP::DERIVS::d22, TP::DERIVS::d23, nvar, Pih, and X.
Referenced by F_of_v(), J_times_dv(), JFD_times_dv(), and set_initial_guess().
allocate_derivs()
void TP::TwoPunctures::allocate_derivs (derivs * v, int n)
Definition at line 52 of file FuncAndJacobian.cpp.
References TP::Utilities::dvector(), and m.
Referenced by bicgstab(), F_of_v(), J_times_dv(), JFD_times_dv(), Newton(), PunctTaylorExpandAtArbitPosition(), Run(), set_initial_guess(), SetMatrix_JFD(), and TestRelax().
bicgstab()
int TP::TwoPunctures::bicgstab (int const nvar, int const n1, int const n2, int const n3, derivs v, derivs dv, int const output, int const itmax, double const tol, double *TP_RESTRICT const normres)
Definition at line 277 of file Newton.cpp.
References allocate_derivs(), beta, TP::DERIVS::d0, TP::Utilities::dmatrix(), dv, TP::Utilities::dvector(), F_of_v(), free_derivs(), TP::Utilities::free_dmatrix(), TP::Utilities::free_dvector(), TP::Utilities::free_imatrix(), TP::Utilities::free_ivector(), TP::Utilities::imatrix(), TP::Utilities::ivector(), J_times_dv(), n1, n2, n3, TP::Utilities::norm2(), TP::NRELAX, nvar, r, relax(), rho, TP::Utilities::scalarproduct(), SetMatrix_JFD(), TP::StencilSize, u, and v.
Referenced by Newton().
BY_Aijofxyz()
void TP::TwoPunctures::BY_Aijofxyz (double x, double y, double z, double Aij[3][3])
Definition at line 83 of file Equations.cpp.
References TP::Parameters::par_b, TP::Parameters::par_P_minus, TP::Parameters::par_P_plus, TP::Parameters::par_S_minus, TP::Parameters::par_S_plus, TP::Parameters::TP_epsilon, and TP::Parameters::TP_Tiny.
Referenced by Interpolate().
BY_KKofxyz()
double TP::TwoPunctures::BY_KKofxyz (double x, double y, double z)
Definition at line 25 of file Equations.cpp.
References TP::Parameters::par_b, TP::Parameters::par_P_minus, TP::Parameters::par_P_plus, TP::Parameters::par_S_minus, and TP::Parameters::par_S_plus.
Referenced by LinEquations(), and NonLinEquations().
C_To_c()
void TP::TwoPunctures::C_To_c (int nvar, double X, double R, double * x, double * r, derivs U)
Definition at line 53 of file CoordTransf.cpp.
References TP::DERIVS::d1, TP::DERIVS::d11, TP::DERIVS::d12, TP::DERIVS::d13, TP::DERIVS::d2, TP::DERIVS::d22, TP::DERIVS::d23, nvar, TP::Parameters::par_b, r, and X.
Referenced by F_of_v(), J_times_dv(), JFD_times_dv(), and set_initial_guess().
calculate_derivs()
void TP::TwoPunctures::calculate_derivs (int i, int j, int k, int ivar, int nvar, int n1, int n2, int n3, derivs v, derivs vv)
Definition at line 727 of file FuncAndJacobian.cpp.
References TP::DERIVS::d0, TP::DERIVS::d1, TP::DERIVS::d11, TP::DERIVS::d12, TP::DERIVS::d13, TP::DERIVS::d2, TP::DERIVS::d22, TP::DERIVS::d23, TP::DERIVS::d3, TP::DERIVS::d33, Index(), n1, n2, n3, nvar, Pih, and v.
Referenced by PunctTaylorExpandAtArbitPosition().
Derivatives_AB3()
void TP::TwoPunctures::Derivatives_AB3 (int nvar, int n1, int n2, int n3, derivs v)
Definition at line 86 of file FuncAndJacobian.cpp.
References TP::Utilities::chder(), TP::Utilities::chebft_Zeros(), TP::DERIVS::d0, TP::DERIVS::d1, TP::DERIVS::d11, TP::DERIVS::d12, TP::DERIVS::d13, TP::DERIVS::d2, TP::DERIVS::d22, TP::DERIVS::d23, TP::DERIVS::d3, TP::DERIVS::d33, TP::Utilities::dvector(), TP::Utilities::fourder(), TP::Utilities::fourder2(), TP::Utilities::fourft(), TP::Utilities::free_dvector(), TP::Utilities::free_ivector(), Index(), TP::Utilities::ivector(), TP::Utilities::maximum3(), n1, n2, n3, nvar, r, and v.
Referenced by F_of_v(), J_times_dv(), and set_initial_guess().
F_of_v()
void TP::TwoPunctures::F_of_v (int nvar, int n1, int n2, int n3, derivs v, double * F, derivs u)
Definition at line 194 of file FuncAndJacobian.cpp.
References AB_To_XR(), allocate_derivs(), assert, C_To_c(), TP::DERIVS::d0, TP::DERIVS::d1, TP::DERIVS::d11, TP::DERIVS::d12, TP::DERIVS::d13, TP::DERIVS::d2, TP::DERIVS::d22, TP::DERIVS::d23, TP::DERIVS::d3, TP::DERIVS::d33, Derivatives_AB3(), TP::Parameters::do_residuum_debug_output, TP::Utilities::dvector(), FAC, free_derivs(), TP::Utilities::free_dvector(), Index(), n1, n2, n3, NonLinEquations(), nvar, TP::Parameters::par_b, TP::Parameters::par_m_minus, TP::Parameters::par_m_plus, Pi, Pih, r, rx3_To_xyz(), TP::TP_MyProc(), u, TP::Parameters::use_sources, v, and X.
Referenced by bicgstab(), Newton(), Run(), and TestRelax().
free_derivs()
void TP::TwoPunctures::free_derivs (derivs * v, int n)
Definition at line 69 of file FuncAndJacobian.cpp.
References TP::Utilities::free_dvector(), and m.
Referenced by bicgstab(), F_of_v(), Interpolate(), J_times_dv(), JFD_times_dv(), Newton(), PunctTaylorExpandAtArbitPosition(), set_initial_guess(), SetMatrix_JFD(), and TestRelax().
Index()
int TP::TwoPunctures::Index (int ivar, int i, int j, int k, int nvar, int n1, int n2, int n3)
Definition at line 28 of file FuncAndJacobian.cpp.
References n1, n2, n3, and nvar.
Referenced by calculate_derivs(), Derivatives_AB3(), F_of_v(), J_times_dv(), JFD_times_dv(), LineRelax_al(), LineRelax_be(), set_initial_guess(), and SetMatrix_JFD().
interpol()
double TP::TwoPunctures::interpol (double a, double b, double c, derivs v)
Definition at line 751 of file FuncAndJacobian.cpp.
References a, TP::DERIVS::d0, TP::DERIVS::d1, TP::DERIVS::d11, TP::DERIVS::d12, TP::DERIVS::d13, TP::DERIVS::d2, TP::DERIVS::d22, TP::DERIVS::d23, TP::DERIVS::d3, TP::DERIVS::d33, and v.
Referenced by PunctTaylorExpandAtArbitPosition().
Interpolate()
void TP::TwoPunctures::Interpolate (const double *const pos, double * Q, bool low_res = false)
Interpolation function for an external caller.
psi[ind] = static_psi;
psix[ind] = px / static_psi; psiy[ind] = py / static_psi; psiz[ind] = pz / static_psi;
psixx[ind] = pxx / static_psi; psixy[ind] = pxy / static_psi; psixz[ind] = pxz / static_psi; psiyy[ind] = pyy / static_psi; psiyz[ind] = pyz / static_psi; psizz[ind] = pzz / static_psi;
puncture_u[ind] = U; /// @TODO: Also no storage for this
SWAP (psix[ind], psiz[ind]);
SWAP (psixx[ind], psizz[ind]); SWAP (psixy[ind], psiyz[ind]);
Definition at line 421 of file TwoPunctures.cpp.
References antisymmetric_lapse, assert, averaged_lapse, brownsville_lapse, BY_Aijofxyz(), TP::Parameters::center_offset, cf_v, TP::Parameters::conformal_state, EXTEND, free_derivs(), TP::Utilities::free_dvector(), TP::Z4VectorShortcuts::g11, TP::Z4VectorShortcuts::g12, TP::Z4VectorShortcuts::g13, TP::Z4VectorShortcuts::g22, TP::Z4VectorShortcuts::g23, TP::Z4VectorShortcuts::g33, gsm, TP::GSM_evaluation, TP::GSM_Taylor_expansion, TP::Parameters::initial_lapse_psi_exponent, TP::Z4VectorShortcuts::K11, TP::Z4VectorShortcuts::K12, TP::Z4VectorShortcuts::K13, TP::Z4VectorShortcuts::K22, TP::Z4VectorShortcuts::K23, TP::Z4VectorShortcuts::K33, TP::Z4VectorShortcuts::lapse, TP::Parameters::mm, TP::Parameters::mp, TP::Parameters::multiply_old_lapse, n1, n2, n3, nvar, TP::Parameters::par_b, pmn_lapse, PunctIntPolAtArbitPositionFast(), PunctTaylorExpandAtArbitPosition(), TP::Z4VectorShortcuts::Qlen, TP::Parameters::rescale_sources, runned, SWAP, TP::Parameters::swap_xz, TP::Parameters::TP_epsilon, TP::LoggingAdapter::TP_ERROR(), TP::Parameters::TP_Extend_Radius, TP::Parameters::TP_Tiny, TP::LoggingAdapter::TP_WARN(), u, TP::Parameters::use_sources, v, and xp.
Referenced by TP_bindding::GradientCal().
J_times_dv()
void TP::TwoPunctures::J_times_dv (int nvar, int n1, int n2, int n3, derivs dv, double * Jdv, derivs u)
Definition at line 372 of file FuncAndJacobian.cpp.
References AB_To_XR(), allocate_derivs(), C_To_c(), TP::DERIVS::d0, TP::DERIVS::d1, TP::DERIVS::d11, TP::DERIVS::d12, TP::DERIVS::d13, TP::DERIVS::d2, TP::DERIVS::d22, TP::DERIVS::d23, TP::DERIVS::d3, TP::DERIVS::d33, Derivatives_AB3(), dv, TP::Utilities::dvector(), FAC, free_derivs(), TP::Utilities::free_dvector(), Index(), LinEquations(), n1, n2, n3, nvar, Pi, Pih, r, rx3_To_xyz(), u, and X.
Referenced by bicgstab().
JFD_times_dv()
void TP::TwoPunctures::JFD_times_dv (int i, int j, int k, int nvar, int n1, int n2, int n3, derivs dv, derivs u, double * values)
Definition at line 452 of file FuncAndJacobian.cpp.
References AB_To_XR(), allocate_derivs(), C_To_c(), TP::DERIVS::d0, TP::DERIVS::d1, TP::DERIVS::d11, TP::DERIVS::d12, TP::DERIVS::d13, TP::DERIVS::d2, TP::DERIVS::d22, TP::DERIVS::d23, TP::DERIVS::d3, TP::DERIVS::d33, dv, FAC, free_derivs(), Index(), LinEquations(), n1, n2, n3, nvar, Pi, r, rx3_To_xyz(), u, and X.
Referenced by SetMatrix_JFD().
LinEquations()
void TP::TwoPunctures::LinEquations (double A, double B, double X, double R, double x, double r, double phi, double y, double z, derivs dU, derivs U, double * values)
Definition at line 181 of file Equations.cpp.
References BY_KKofxyz(), TP::DERIVS::d0, TP::DERIVS::d11, TP::DERIVS::d22, TP::DERIVS::d33, TP::Parameters::par_b, TP::Parameters::par_m_minus, and TP::Parameters::par_m_plus.
Referenced by J_times_dv(), and JFD_times_dv().
LineRelax_al()
void TP::TwoPunctures::LineRelax_al (double *TP_RESTRICT const dv, int const j, int const k, int const nvar, int const n1, int const n2, int const n3, double const *TP_RESTRICT const rhs, int const *TP_RESTRICT const ncols, int const *TP_RESTRICT const *TP_RESTRICT const cols, double const *TP_RESTRICT const *TP_RESTRICT const JFD)
Definition at line 57 of file Newton.cpp.
References dv, Index(), m, n1, n2, n3, and nvar.
Referenced by relax().
LineRelax_be()
void TP::TwoPunctures::LineRelax_be (double *TP_RESTRICT const dv, int const i, int const k, int const nvar, int const n1, int const n2, int const n3, double const *TP_RESTRICT const rhs, int const *TP_RESTRICT const ncols, int const *TP_RESTRICT const *TP_RESTRICT const cols, double const *TP_RESTRICT const *TP_RESTRICT const JFD)
Definition at line 117 of file Newton.cpp.
References dv, Index(), m, n1, n2, n3, and nvar.
Referenced by relax().
Newton()
void TP::TwoPunctures::Newton (int nvar, int n1, int n2, int n3, derivs v, double tol, int itmax)
Definition at line 452 of file Newton.cpp.
References allocate_derivs(), bicgstab(), TP::DERIVS::d0, dv, TP::Utilities::dvector(), F_of_v(), free_derivs(), TP::Utilities::free_dvector(), n1, n2, n3, norm_inf(), nvar, TP::Parameters::par_m_minus, TP::Parameters::par_m_plus, u, v, and TP::Parameters::verbose.
Referenced by Run().
NonLinEquations()
void TP::TwoPunctures::NonLinEquations (double rho_adm, double A, double B, double X, double R, double x, double r, double phi, double y, double z, derivs U, double * values)
Definition at line 153 of file Equations.cpp.
References BY_KKofxyz(), TP::DERIVS::d0, TP::DERIVS::d11, TP::DERIVS::d22, TP::DERIVS::d33, TP::Parameters::par_b, TP::Parameters::par_m_minus, TP::Parameters::par_m_plus, and Pi.
Referenced by F_of_v().
norm_inf()
double TP::TwoPunctures::norm_inf (double const *TP_RESTRICT const F, int const ntotal)
Definition at line 22 of file Newton.cpp.
Referenced by Newton().
PunctEvalAtArbitPosition()
double TP::TwoPunctures::PunctEvalAtArbitPosition (double * v, int ivar, double A, double B, double phi, int nvar, int n1, int n2, int n3)
Definition at line 685 of file FuncAndJacobian.cpp.
References TP::Utilities::chebev(), TP::Utilities::chebft_Zeros(), TP::Utilities::dmatrix(), TP::Utilities::dvector(), TP::Utilities::fourev(), TP::Utilities::fourft(), TP::Utilities::free_dmatrix(), TP::Utilities::free_dvector(), TP::Utilities::maximum3(), n1, n2, n3, nvar, and v.
Referenced by PunctIntPolAtArbitPosition(), and Run().
PunctEvalAtArbitPositionFast()
double TP::TwoPunctures::PunctEvalAtArbitPositionFast (double * v, int ivar, double A, double B, double phi, int nvar, int n1, int n2, int n3)
Fast Spectral Interpolation Routine Stuff.
Definition at line 853 of file FuncAndJacobian.cpp.
References TP::Utilities::chebev(), TP::Utilities::dmatrix(), TP::Utilities::dvector(), TP::Utilities::fourev(), TP::Utilities::free_dmatrix(), TP::Utilities::free_dvector(), TP::Utilities::maximum3(), n1, n2, n3, nvar, and v.
PunctEvalAtArbitPositionFaster()
double TP::TwoPunctures::PunctEvalAtArbitPositionFaster (double A, double B, double phi)
Definition at line 921 of file FuncAndJacobian.cpp.
References TP::chebev_wrec(), TP::Utilities::fourev(), TP::Parameters::npoints_A, TP::Parameters::npoints_B, TP::Parameters::npoints_phi, and TP::recurrence().
Referenced by PunctIntPolAtArbitPositionFast().
PunctEvalAtArbitPositionFasterLowRes()
double TP::TwoPunctures::PunctEvalAtArbitPositionFasterLowRes (double A, double B, double phi)
Definition at line 966 of file FuncAndJacobian.cpp.
References TP::chebev_wrec(), TP::Utilities::fourev(), n2, n3, TP::Parameters::npoints_A_low, TP::Parameters::npoints_B_low, TP::Parameters::npoints_phi_low, and TP::recurrence().
Referenced by PunctIntPolAtArbitPositionFast().
PunctIntPolAtArbitPosition()
double TP::TwoPunctures::PunctIntPolAtArbitPosition (int ivar, int nvar, int n1, int n2, int n3, derivs v, double x, double y, double z)
Definition at line 813 of file FuncAndJacobian.cpp.
References TP::DERIVS::d0, TP::min(), n1, n2, n3, nvar, TP::Parameters::par_b, Pi, Piq, PunctEvalAtArbitPosition(), v, and X.
Referenced by Run(), and set_initial_guess().
PunctIntPolAtArbitPositionFast()
double TP::TwoPunctures::PunctIntPolAtArbitPositionFast (derivs v, double x, double y, double z, bool low_res = false)
Definition at line 1027 of file FuncAndJacobian.cpp.
References TP::min(), TP::Parameters::par_b, Pi, Piq, PunctEvalAtArbitPositionFaster(), PunctEvalAtArbitPositionFasterLowRes(), and X.
Referenced by Interpolate().
PunctTaylorExpandAtArbitPosition()
double TP::TwoPunctures::PunctTaylorExpandAtArbitPosition (int ivar, int nvar, int n1, int n2, int n3, derivs v, double x, double y, double z)
Definition at line 762 of file FuncAndJacobian.cpp.
References a, allocate_derivs(), calculate_derivs(), free_derivs(), interpol(), TP::min(), n1, n2, n3, nvar, TP::Parameters::par_b, Pi, Piq, v, and X.
Referenced by Interpolate().
relax()
void TP::TwoPunctures::relax (double *TP_RESTRICT const dv, int const nvar, int const n1, int const n2, int const n3, double const *TP_RESTRICT const rhs, int const *TP_RESTRICT const ncols, int const *TP_RESTRICT const *TP_RESTRICT const cols, double const *TP_RESTRICT const *TP_RESTRICT const JFD)
Definition at line 176 of file Newton.cpp.
References dv, LineRelax_al(), LineRelax_be(), n1, n2, n3, TP::N_PlaneRelax, and nvar.
Referenced by bicgstab(), and TestRelax().
resid()
void TP::TwoPunctures::resid (double *TP_RESTRICT const res, int const ntotal, double const *TP_RESTRICT const dv, double const *TP_RESTRICT const rhs, int const *TP_RESTRICT const ncols, int const *TP_RESTRICT const *TP_RESTRICT const cols, double const *TP_RESTRICT const *TP_RESTRICT const JFD)
Definition at line 38 of file Newton.cpp.
References dv, and m.
Referenced by TestRelax().
Run()
void TP::TwoPunctures::Run ()
Definition at line 189 of file TwoPunctures.cpp.
References _n1_low, _n2_low, _n3_low, TP::Parameters::adm_tol, allocate_derivs(), antisymmetric_lapse, averaged_lapse, brownsville_lapse, TP::Parameters::center_offset, cf_v, TP::Parameters::conformal_state, TP::Parameters::conformal_storage, TP::DERIVS::d0, TP::DERIVS::d1, TP::DERIVS::d11, TP::DERIVS::d12, TP::DERIVS::d13, TP::DERIVS::d2, TP::DERIVS::d22, TP::DERIVS::d23, TP::DERIVS::d3, TP::DERIVS::d33, TP::Utilities::dvector(), F_of_v(), TP::Parameters::give_bare_mass, TP::Parameters::grid_setup_method, gsm, TP::GSM_evaluation, TP::GSM_Taylor_expansion, TP::Parameters::initial_lapse, TP::Parameters::initial_lapse_psi_exponent, TP::Parameters::J1, TP::Parameters::J2, TP::Parameters::J3, TP::Parameters::metric_type, TP::Parameters::mm, TP::Parameters::mm_adm, TP::Parameters::mp, TP::Parameters::mp_adm, n1, n2, n3, Newton(), TP::Parameters::Newton_maxit, TP::Parameters::Newton_tol, TP::Parameters::npoints_A, TP::Parameters::npoints_A_low, TP::Parameters::npoints_B, TP::Parameters::npoints_B_low, TP::Parameters::npoints_phi, TP::Parameters::npoints_phi_low, nvar, TP::Parameters::par_b, TP::Parameters::par_m_minus, TP::Parameters::par_m_plus, TP::Parameters::par_P_minus, TP::Parameters::par_P_plus, TP::Parameters::par_S_minus, TP::Parameters::par_S_plus, pmn_lapse, PunctEvalAtArbitPosition(), PunctIntPolAtArbitPosition(), runned, set_initial_guess(), SpecCoef(), TP::Parameters::target_M_minus, TP::Parameters::target_M_plus, TP::LoggingAdapter::TP_ERROR(), TP::LoggingAdapter::TP_INFO(), u, TP::Parameters::use_external_initial_guess, TP::Parameters::use_sources, and v.
Referenced by benchmarks::exahype2::ccz4::prepareTwoPunctures().
rx3_To_xyz()
void TP::TwoPunctures::rx3_To_xyz (int nvar, double x, double r, double phi, double * y, double * z, derivs U)
Definition at line 116 of file CoordTransf.cpp.
References TP::DERIVS::d1, TP::DERIVS::d11, TP::DERIVS::d12, TP::DERIVS::d13, TP::DERIVS::d2, TP::DERIVS::d22, TP::DERIVS::d23, TP::DERIVS::d3, TP::DERIVS::d33, nvar, r, and r_inv.
Referenced by F_of_v(), J_times_dv(), JFD_times_dv(), and set_initial_guess().
set_initial_guess()
void TP::TwoPunctures::set_initial_guess (derivs v)
Definition at line 16 of file TwoPunctures.cpp.
References AB_To_XR(), allocate_derivs(), assert, C_To_c(), TP::DERIVS::d0, TP::DERIVS::d1, TP::DERIVS::d11, TP::DERIVS::d12, TP::DERIVS::d13, TP::DERIVS::d2, TP::DERIVS::d22, TP::DERIVS::d23, TP::DERIVS::d3, TP::DERIVS::d33, Derivatives_AB3(), TP::Parameters::do_initial_debug_output, free_derivs(), Index(), n1, n2, n3, nvar, Pi, Pih, PunctIntPolAtArbitPosition(), r, rx3_To_xyz(), TP::Parameters::solve_momentum_constraint, TP::TP_MyProc(), v, and X.
Referenced by Run().
SetMatrix_JFD()
void TP::TwoPunctures::SetMatrix_JFD (int nvar, int n1, int n2, int n3, derivs u, int * ncols, int ** cols, double ** Matrix)
Definition at line 594 of file FuncAndJacobian.cpp.
References allocate_derivs(), dv, TP::Utilities::dvector(), free_derivs(), TP::Utilities::free_dvector(), Index(), JFD_times_dv(), TP::Utilities::maximum2(), TP::Utilities::minimum2(), n1, n2, n3, nvar, and u.
Referenced by bicgstab(), and TestRelax().
SpecCoef()
void TP::TwoPunctures::SpecCoef (int n1, int n2, int n3, int ivar, double * v, double * cf)
Definition at line 1061 of file FuncAndJacobian.cpp.
References TP::Utilities::chebft_Zeros(), TP::Utilities::d3tensor(), TP::Utilities::dvector(), TP::Utilities::fourft(), TP::Utilities::free_d3tensor(), TP::Utilities::free_dvector(), m, TP::Utilities::maximum3(), n1, n2, n3, and v.
Referenced by Run().
TestRelax()
void TP::TwoPunctures::TestRelax (int nvar, int n1, int n2, int n3, derivs v, double * dv)
Definition at line 225 of file Newton.cpp.
References allocate_derivs(), TP::Utilities::dmatrix(), dv, TP::Utilities::dvector(), F_of_v(), free_derivs(), TP::Utilities::free_dmatrix(), TP::Utilities::free_dvector(), TP::Utilities::free_imatrix(), TP::Utilities::free_ivector(), TP::Utilities::imatrix(), TP::Utilities::ivector(), n1, n2, n3, TP::Utilities::norm1(), TP::NRELAX, nvar, relax(), resid(), SetMatrix_JFD(), TP::StencilSize, TP::Step_Relax, u, and v.
TestSolution()
double TP::TwoPunctures::TestSolution (double A, double B, double X, double R, double phi)
TestVector_w()
void TP::TwoPunctures::TestVector_w (double * par, int nvar, int n1, int n2, int n3, double * w)
Field Documentation
_n1_low
int TP::TwoPunctures::_n1_low
Definition at line 56 of file TwoPunctures.h.
Referenced by Run().
_n2_low
int TP::TwoPunctures::_n2_low
Definition at line 56 of file TwoPunctures.h.
Referenced by Run().
_n3_low
int TP::TwoPunctures::_n3_low
Definition at line 56 of file TwoPunctures.h.
Referenced by Run().
antisymmetric_lapse
int TP::TwoPunctures::antisymmetric_lapse
Definition at line 58 of file TwoPunctures.h.
Referenced by Interpolate(), and Run().
averaged_lapse
int TP::TwoPunctures::averaged_lapse
Definition at line 58 of file TwoPunctures.h.
Referenced by Interpolate(), and Run().
brownsville_lapse
int TP::TwoPunctures::brownsville_lapse
Definition at line 58 of file TwoPunctures.h.
Referenced by Interpolate(), and Run().
cf_v
derivs TP::TwoPunctures::cf_v
Definition at line 57 of file TwoPunctures.h.
Referenced by Interpolate(), and Run().
gsm
GRID_SETUP_METHOD TP::TwoPunctures::gsm
Definition at line 54 of file TwoPunctures.h.
Referenced by Interpolate(), and Run().
n1
int TP::TwoPunctures::n1
Definition at line 55 of file TwoPunctures.h.
Referenced by bicgstab(), calculate_derivs(), Derivatives_AB3(), F_of_v(), Index(), Interpolate(), J_times_dv(), JFD_times_dv(), LineRelax_al(), LineRelax_be(), Newton(), PunctEvalAtArbitPosition(), PunctEvalAtArbitPositionFast(), PunctIntPolAtArbitPosition(), PunctTaylorExpandAtArbitPosition(), relax(), Run(), set_initial_guess(), SetMatrix_JFD(), SpecCoef(), TestRelax(), and TwoPunctures().
n2
int TP::TwoPunctures::n2
Definition at line 55 of file TwoPunctures.h.
Referenced by bicgstab(), calculate_derivs(), Derivatives_AB3(), F_of_v(), Index(), Interpolate(), J_times_dv(), JFD_times_dv(), LineRelax_al(), LineRelax_be(), Newton(), PunctEvalAtArbitPosition(), PunctEvalAtArbitPositionFast(), PunctEvalAtArbitPositionFasterLowRes(), PunctIntPolAtArbitPosition(), PunctTaylorExpandAtArbitPosition(), relax(), Run(), set_initial_guess(), SetMatrix_JFD(), SpecCoef(), TestRelax(), and TwoPunctures().
n3
int TP::TwoPunctures::n3
Definition at line 55 of file TwoPunctures.h.
Referenced by bicgstab(), calculate_derivs(), Derivatives_AB3(), F_of_v(), Index(), Interpolate(), J_times_dv(), JFD_times_dv(), LineRelax_al(), LineRelax_be(), Newton(), PunctEvalAtArbitPosition(), PunctEvalAtArbitPositionFast(), PunctEvalAtArbitPositionFasterLowRes(), PunctIntPolAtArbitPosition(), PunctTaylorExpandAtArbitPosition(), relax(), Run(), set_initial_guess(), SetMatrix_JFD(), SpecCoef(), TestRelax(), and TwoPunctures().
nvar
int TP::TwoPunctures::nvar
Definition at line 55 of file TwoPunctures.h.
Referenced by AB_To_XR(), bicgstab(), C_To_c(), calculate_derivs(), Derivatives_AB3(), F_of_v(), Index(), Interpolate(), J_times_dv(), JFD_times_dv(), LineRelax_al(), LineRelax_be(), Newton(), PunctEvalAtArbitPosition(), PunctEvalAtArbitPositionFast(), PunctIntPolAtArbitPosition(), PunctTaylorExpandAtArbitPosition(), relax(), Run(), rx3_To_xyz(), set_initial_guess(), SetMatrix_JFD(), TestRelax(), and TwoPunctures().
pmn_lapse
int TP::TwoPunctures::pmn_lapse
Definition at line 58 of file TwoPunctures.h.
Referenced by Interpolate(), and Run().
runned
bool TP::TwoPunctures::runned
an internal check
Definition at line 61 of file TwoPunctures.h.
Referenced by Interpolate(), Run(), and TwoPunctures().
u
derivs TP::TwoPunctures::u
Definition at line 57 of file TwoPunctures.h.
Referenced by bicgstab(), F_of_v(), Interpolate(), J_times_dv(), JFD_times_dv(), Newton(), Run(), SetMatrix_JFD(), and TestRelax().
v
derivs TP::TwoPunctures::v
Definition at line 57 of file TwoPunctures.h.
Referenced by bicgstab(), calculate_derivs(), Derivatives_AB3(), F_of_v(), interpol(), Interpolate(), Newton(), PunctEvalAtArbitPosition(), PunctEvalAtArbitPositionFast(), PunctIntPolAtArbitPosition(), PunctTaylorExpandAtArbitPosition(), Run(), set_initial_guess(), SpecCoef(), and TestRelax().
The documentation for this class was generated from the following files:
applications/exahype2/ccz4/libtwopunctures/TwoPunctures.h
applications/exahype2/ccz4/libtwopunctures/CoordTransf.cpp
applications/exahype2/ccz4/libtwopunctures/Equations.cpp
applications/exahype2/ccz4/libtwopunctures/FuncAndJacobian.cpp
applications/exahype2/ccz4/libtwopunctures/Newton.cpp
applications/exahype2/ccz4/libtwopunctures/TwoPunctures.cpp