Peano
TP Namespace Reference
This file contains aliases for making access to the long state vector Q as used eg.
Namespaces
namespace Utilities
namespace Z4VectorShortcuts
Data Structures
struct DERIVS
class error
Another nice thing: The TwoPunctures Error, borrowed from Pizza.
struct logger
By inheriting this class, you can do something with output if you need.
struct LoggingAdapter
The LoggingAdapter: Logging in Cactus/printf style without macros.
struct Parameters
struct std_cerr_logger
Default stdout logger, using iostream.
class TwoPunctures
Typedefs
typedef struct TP::DERIVS derivs
Enumerations
enum GRID_SETUP_METHOD { GSM_Taylor_expansion , GSM_evaluation }
Functions
static double min (double const x, double const y)
void recurrence (double x, int m, double *recvec)
double chebev_wrec (double recvec[], double coeff[], int m)
int TP_MyProc ()
Variables
const int StencilSize = 19
const int N_PlaneRelax = 1
const int NRELAX = 200
const int Step_Relax = 1
Detailed Description
This file contains aliases for making access to the long state vector Q as used eg.
in ExaHyPE and at the functional interface of this code, more readable.
With these constants, you can write Q[g11], Q[K22] and Q[B33] instead of Q[0], Q[9] and Q[34]. Your code is again meaningful in terms of physics.
The list os converted from the PDENames function from Trentos Fortran code with this expression:
‍perl -p -i -e "s/^\s+Name\‍((.*)\‍)\s* = '(.+)'/\"const int \$2 = \".(\$1-1).';';/eg" FileHoldingPDEDefs.tmp
Methods have been implemented already in the ExaHyPE SRHD application to deal even more naturally with physical expressions which are stored in a long and unintuitive vector. See end of this file for comments.
Typedef Documentation
derivs
typedef struct TP::DERIVS TP::derivs
Enumeration Type Documentation
GRID_SETUP_METHOD
enum TP::GRID_SETUP_METHOD
Enumerator
GSM_Taylor_expansion
GSM_evaluation
Definition at line 34 of file TwoPunctures.h.
Function Documentation
chebev_wrec()
double TP::chebev_wrec (double recvec[], double coeff[], int m)
Definition at line 906 of file FuncAndJacobian.cpp.
References m.
Referenced by TP::TwoPunctures::PunctEvalAtArbitPositionFaster(), and TP::TwoPunctures::PunctEvalAtArbitPositionFasterLowRes().
min()
static double TP::min (double const x, double const y) static
Definition at line 21 of file FuncAndJacobian.cpp.
Referenced by TP::TwoPunctures::PunctIntPolAtArbitPosition(), TP::TwoPunctures::PunctIntPolAtArbitPositionFast(), and TP::TwoPunctures::PunctTaylorExpandAtArbitPosition().
recurrence()
void TP::recurrence (double x, int m, double * recvec)
Definition at line 896 of file FuncAndJacobian.cpp.
References m.
Referenced by TP::TwoPunctures::PunctEvalAtArbitPositionFaster(), and TP::TwoPunctures::PunctEvalAtArbitPositionFasterLowRes().
TP_MyProc()
int TP::TP_MyProc ()
Definition at line 24 of file TwoPunctures.h.
Referenced by TP::TwoPunctures::F_of_v(), and TP::TwoPunctures::set_initial_guess().
Variable Documentation
N_PlaneRelax
const int TP::N_PlaneRelax = 1
Definition at line 16 of file Newton.cpp.
Referenced by TP::TwoPunctures::relax().
NRELAX
const int TP::NRELAX = 200
Definition at line 17 of file Newton.cpp.
Referenced by TP::TwoPunctures::bicgstab(), and TP::TwoPunctures::TestRelax().
StencilSize
const int TP::StencilSize = 19
Definition at line 15 of file Newton.cpp.
Referenced by TP::TwoPunctures::bicgstab(), and TP::TwoPunctures::TestRelax().
Step_Relax
const int TP::Step_Relax = 1
Definition at line 18 of file Newton.cpp.
Referenced by TP::TwoPunctures::TestRelax().