Peano
tarch::la Namespace Reference
My collection of tiny vector operations.
Namespaces
namespace tests
Data Structures
class CompressedFloat
class DynamicMatrix
My standard matrix is a matrix where the size is fixed at compile time.
class Matrix
Static (i.e.
class ShallowMatrix
Shallow matrix wrapping an existing array.
struct SmartPointerVector
Simple SmartPointerVector class.
struct Vector
Simple vector class.
struct VectorCompare
Comparison operator for boolean vectors.
Functions
DynamicMatrix transpose (const DynamicMatrix &matrix)
template<int Rows, int Cols, typename Scalar >
void modifiedGramSchmidt (Matrix< Rows, Cols, Scalar > A, Matrix< Rows, Cols, Scalar > &Q, Matrix< Cols, Cols, Scalar > &R)
Produces an economy-size QR decomposition of a matrix A, A is changed.
void modifiedGramSchmidt (DynamicMatrix A, DynamicMatrix &Q, DynamicMatrix &R)
template<int Rows, typename Scalar >
void lu (Matrix< Rows, Rows, Scalar > &A, Vector< Rows, int > &pivots)
Performs an in-situ LU-decomposition of the square matrix A.
template<int Rows, typename Scalar >
void lu (Matrix< Rows, Rows, Scalar > &A)
In-situ LU without pivoting.
template<int Rows, typename Scalar >
Vector< Rows, Scalar > backSubstitution (const Matrix< Rows, Rows, Scalar > &R, const Vector< Rows, Scalar > &f)
Back substitution following LU decomposition.
void backSubstitution (const DynamicMatrix &R, const double *f, double *x)
DynamicMatrix invertUpperTriangular (const DynamicMatrix &R)
template<int Rows, typename Scalar >
Matrix< Rows, Rows, Scalar > invert (const Matrix< Rows, Rows, Scalar > &M)
Invert matrix with LU decomposition.
template<typename Scalar >
Matrix< 2, 2, Scalar > invert (const Matrix< 2, 2, Scalar > &M)
Specialisation of inversion.
template<typename Scalar >
Matrix< 3, 3, Scalar > invert (const Matrix< 3, 3, Scalar > &M)
Specialisation of inversion.
template<typename Scalar >
double det (const Matrix< 2, 2, Scalar > &R)
template<typename Scalar >
double det (const Matrix< 3, 3, Scalar > &R)
template<int Rows, int Cols, typename Scalar >
Matrix< Rows, Cols, Scalar > buildMatrix (const Scalar *values)
Deep copy builder function.
template<int Rows, int Cols, int X, typename Scalar >
Matrix< Rows, Cols, Scalar > multiply (const Matrix< Rows, X, Scalar > &lhs, const Matrix< X, Cols, Scalar > &rhs)
Performs a matrix x matrix multiplication.
template<int Rows, int Cols, int X, typename Scalar >
Matrix< Rows, Cols, Scalar > multiplyComponents (const Matrix< Rows, X, Scalar > &lhs, const Matrix< X, Cols, Scalar > &rhs)
template<int Rows, int Cols, int X, typename Scalar >
Matrix< Rows, Cols, Scalar > operator* (const Matrix< Rows, X, Scalar > &lhs, const Matrix< X, Cols, Scalar > &rhs)
template<int Rows, int Cols, typename Scalar >
bool operator== (const Matrix< Rows, Cols, Scalar > &lhs, const Matrix< Rows, Cols, Scalar > &rhs)
Bitwise comparison of the components of two matrices on equality.
template<int Rows, int Cols, typename Scalar >
bool equals (const Matrix< Rows, Cols, Scalar > &lhs, const Matrix< Rows, Cols, Scalar > &rhs, const Scalar &tolerance=NUMERICAL_ZERO_DIFFERENCE)
Compares to matrices on equality by means of a numerical accuracy.
template<int Rows, int Cols, typename Scalar >
Matrix< Rows, Cols, Scalar > operator+ (const Matrix< Rows, Cols, Scalar > &lhs, const Matrix< Rows, Cols, Scalar > &rhs)
template<int Rows, int Cols, typename Scalar >
Matrix< Rows, Cols, Scalar > operator- (const Matrix< Rows, Cols, Scalar > &lhs, const Matrix< Rows, Cols, Scalar > &rhs)
template<int Rows, int Cols, typename Scalar >
std::pair< int, int > equalsReturnIndex (const Matrix< Rows, Cols, Scalar > &lhs, const Matrix< Rows, Cols, Scalar > &rhs, const Scalar &tolerance=NUMERICAL_ZERO_DIFFERENCE)
Return Index of element which is not equals.
template<int Rows, int Cols, typename Scalar >
Scalar sum (const Matrix< Rows, Cols, Scalar > &matrix)
Computes the sum of all entries of the matrix.
template<int Rows, int Cols, typename Scalar >
Matrix< Cols, Rows, Scalar > transpose (const Matrix< Rows, Cols, Scalar > &matrix)
template<int Rows, typename Scalar >
static Matrix< Rows, Rows, Scalar > identity ()
Returns the identity matrix.
template<int Rows, typename Scalar >
Vector< Rows, Scalar > diag (const Matrix< Rows, Rows, Scalar > &matrix)
Extract diagonal vector from matrix.
template<int Rows, int Cols, typename Scalar >
Vector< Cols, Scalar > row (const Matrix< Rows, Cols, Scalar > &matrix, int whichRow)
Extract row from matrix.
template<int Rows, int Cols, typename Scalar >
Vector< Rows, Scalar > col (const Matrix< Rows, Cols, Scalar > &matrix, int whichColumn)
Extract row from matrix.
template<int Rows, int Cols, typename Scalar >
Matrix< Rows, Cols, Scalar > & operator*= (Matrix< Rows, Cols, Scalar > &matrix, const Scalar &scalar)
template<int Rows, int Cols, typename Scalar >
Matrix< Rows, Cols, Scalar > operator* (const Matrix< Rows, Cols, Scalar > &matrix, const Scalar &scalar)
Multiplies every component of the matrix with the scalar.
template<int Rows, int Cols, typename Scalar >
Matrix< Rows, Cols, Scalar > operator* (const Scalar &scalar, const Matrix< Rows, Cols, Scalar > &matrix)
Multiplies every component of the matrix with the scalar.
template<int Rows, int Cols>
Matrix< Rows, Cols, std::complex< double > > operator* (const double &scalar, const Matrix< Rows, Cols, std::complex< double > > &matrix)
template<int Rows, int Cols, typename Scalar >
Vector< Rows, Scalar > multiply (const Matrix< Rows, Cols, Scalar > &matrix, const Vector< Cols, Scalar > &vector)
Performs a matrix x vector multiplication.
template<int Rows, int Cols, typename Scalar >
void matVec (const Matrix< Rows, Cols, Scalar > &matrix, Scalar alpha, const Vector< Cols, Scalar > &v, Vector< Rows, Scalar > &r)
Compute r = r + alpha * M * v in-situ.
template<int Rows, int Cols, typename Scalar >
Vector< Rows, Scalar > operator* (const Matrix< Rows, Cols, Scalar > &matrix, const Vector< Cols, Scalar > &vector)
Performs a matrix x vector multiplication.
template<int Size, typename Scalar >
Matrix< Size, Size, Scalar > outerDot (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs)
Outer dot product.
double relativeEpsNormaledAgainstValueGreaterOne (double valueA, double valueB=std::numeric_limits< double >::min(), double eps=NUMERICAL_ZERO_DIFFERENCE)
Determine a relative tolerance from one or two values.
double relativeEps (double valueA, double valueB=std::numeric_limits< double >::min(), double eps=NUMERICAL_ZERO_DIFFERENCE)
Determine a relative tolerance from one or two values.
double max (double a, double b, double c)
I need the maximum of three values all the time, to I decided to write a function for this.
double pow (double base, double exponent)
Wrapper around std::pow which is redirected to Intel's implementation on Intel machines.
double convertAbsoluteIntoRelativeValue (double referenceValue, double value)
Convert an absolute value into a relative one.
GPUCallableMethod double abs (double value) InlineMethod
Returns the absolute value of a type by redirecting to std::abs.
GPUCallableMethod int abs (int value) InlineMethod
Returns the absolute value of the given int.
GPUCallableMethod double abs (const std::complex< double > &value) InlineMethod
GPUCallableMethod int aPowI (int i, int a) InlineMethod
Computes the i-th power of a in integer arithmetic.
GPUCallableMethod bool greater (double lhs, double rhs, double tolerance=NUMERICAL_ZERO_DIFFERENCE) InlineMethod
GPUCallableMethod bool greaterEquals (double lhs, double rhs, double tolerance=NUMERICAL_ZERO_DIFFERENCE) InlineMethod
GPUCallableMethod bool equals (double lhs, double rhs, double tolerance=NUMERICAL_ZERO_DIFFERENCE) InlineMethod
GPUCallableMethod bool smaller (double lhs, double rhs, double tolerance=NUMERICAL_ZERO_DIFFERENCE) InlineMethod
GPUCallableMethod bool smallerEquals (double lhs, double rhs, double tolerance=NUMERICAL_ZERO_DIFFERENCE) InlineMethod
GPUCallableMethod bool equals (const std::complex< double > &lhs, const std::complex< double > &rhs, double tolerance=NUMERICAL_ZERO_DIFFERENCE) InlineMethod
GPUCallableMethod int sign (double value, double tolerance=NUMERICAL_ZERO_DIFFERENCE) InlineMethod
GPUCallableMethod int round (double value) InlineMethod
GPUCallableMethod int round (float value) InlineMethod
template<int Rows, int Cols, typename Scalar >
Vector< Rows, Scalar > multiply (const ShallowMatrix< Rows, Cols, Scalar > &matrix, const Vector< Cols, Scalar > &vector)
Performs a matrix x vector multiplication.
template<int Rows, int Cols, typename Scalar >
Vector< Rows, Scalar > multiply (const ShallowMatrix< Rows, Cols, Scalar > &matrix, const SmartPointerVector< Cols, Scalar > &vector)
template<typename NewScalarType , int Size, typename Scalar >
tarch::la::SmartPointerVector< Size, NewScalarType > convertScalar (const tarch::la::SmartPointerVector< Size, Scalar > &SmartPointerVector)
template<typename NewScalarType , int Size, typename Scalar >
tarch::la::Vector< Size, NewScalarType > convertScalar (const tarch::la::Vector< Size, Scalar > &vector)
Convert the scalar type underlying a vector.
template<int Size, typename Scalar >
Scalar norm1 (const Vector< Size, Scalar > &vector)
Computes the 1-norm of the vector, i.e.
template<int Size>
double norm1 (const Vector< Size, std::complex< double > > &vector)
Specialisation that is different to standard definition.
template<int Size, typename Scalar >
GPUCallableMethod Scalar norm2 (const Vector< Size, Scalar > &vector) InlineMethod
Computes the 2-norm of the vector, i.e.
template<int Size, typename Scalar >
GPUCallableMethod Scalar norm2Squared (const Vector< Size, Scalar > &vector) InlineMethod
template<int Size>
GPUCallableMethod double norm2 (const Vector< Size, std::complex< double > > &vector) InlineMethod
Specialisation that is different to standard definition.
template<int Size>
GPUCallableMethod double norm2Squared (const Vector< Size, std::complex< double > > &vector) InlineMethod
template<int Size, typename Scalar >
Scalar normMax (const Vector< Size, Scalar > &vector)
Computes the max-norm of the vector.
template<int Size>
double normMax (const Vector< Size, std::complex< double > > &vector)
Specialisation that is different to standard definition.
template<int Size, typename Scalar >
Vector< Size, Scalar > abs (const Vector< Size, Scalar > &vector)
Computes the absolute component values of the vector, creating a temporary vector to hold the result.
template<int Size>
Vector< Size, double > abs (const Vector< Size, std::complex< double > > &vector)
Specialisation that is different to standard definition.
template<int Size, typename Scalar >
Scalar sum (const Vector< Size, Scalar > &vector)
Sums up the component values of the vector.
template<int Size, typename Scalar >
Scalar volume (const Vector< Size, Scalar > &vector)
Computes the volume of the tetrahedron spanned by the Cartesian unit vectors scaled by the corresponding components of the given vector.
template<int Size, typename Scalar >
bool allEntriesAreTheSame (const Vector< Size, Scalar > &vector)
template<int Size, typename Scalar >
Scalar average (const Vector< Size, Scalar > &vector)
Computes the volume of the tetrahedron spanned by the Cartesian unit vectors scaled by the corresponding components of the given vector.
template<int Size, typename Scalar >
int indexMax (const Vector< Size, Scalar > &vector)
Returns the index of the element with maximal value (NOT absolute value).
template<int Size, typename Scalar >
int indexMin (const Vector< Size, Scalar > &vector)
Returns the index of the element with minimal value (NOT absolute value).
template<int Size, typename Scalar >
Scalar max (const Vector< Size, Scalar > &vector)
Returns the element with maximal value (NOT absolute value).
template<int Size, typename Scalar >
Scalar maxAbs (const Vector< Size, Scalar > &vector)
Returns the element with maximal absolute value.
template<int Size, typename Scalar >
Scalar min (const Vector< Size, Scalar > &vector)
Returns the element with minimal value (NOT absolute value).
template<int Size, typename Scalar >
Vector< Size, Scalar > invertEntries (const Vector< Size, Scalar > &vector)
template<int Size>
Vector< Size, double > real (const Vector< Size, std::complex< double > > &vector)
template<int Size>
Vector< Size, double > imag (const Vector< Size, std::complex< double > > &vector)
template<int Size>
double maxReal (const Vector< Size, std::complex< double > > &vector)
template<int Size>
double maxImag (const Vector< Size, std::complex< double > > &vector)
template<int Size, typename Scalar >
bool contains (const Vector< Size, Scalar > &vector, const Scalar &value)
template<int Size, typename Scalar >
int count (const Vector< Size, Scalar > &vector, const Scalar &value)
template<int Size, typename Scalar >
int isEntryNan (const Vector< Size, Scalar > &vector)
template<int Size, typename Scalar >
int isEntryFinite (const Vector< Size, Scalar > &vector)
template<int Size, typename Scalar >
std::vector< Scalar > toSTLVector (const Vector< Size, Scalar > &vector)
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > & operator*= (Vector< Size, Scalar > &vector, const Scalar &scalar) InlineMethod
Multiplies every component of the vector with the scalar and assigns the result to the vector.
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > & operator/= (Vector< Size, Scalar > &vector, const Scalar &scalar) InlineMethod
Divides every component of the vector by the scalar and assigns the result to the vector.
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > & operator+= (Vector< Size, Scalar > &vector, const Scalar &scalar) InlineMethod
Adds every component of the vector to the scalar and assigns the result to the vector.
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > & operator-= (Vector< Size, Scalar > &vector, const Scalar &scalar) InlineMethod
Subtracts the scalar from every component of the vector and assigns the result to the vector.
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > operator* (const Vector< Size, Scalar > &vector, const Scalar &scalar) InlineMethod
Multiplies every component of the vector with the scalar and returns the result.
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > operator* (const Scalar &scalar, const Vector< Size, Scalar > &vector) InlineMethod
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > operator/ (const Vector< Size, Scalar > &vector, const Scalar &scalar) InlineMethod
Divides every component of the vector by the scalar and returns the result.
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > operator+ (const Vector< Size, Scalar > &vector, const Scalar &scalar) InlineMethod
Adds the scalar to every component of the vector and returns the result.
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > operator+ (const Scalar &scalar, const Vector< Size, Scalar > &vector) InlineMethod
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > operator- (const Vector< Size, Scalar > &vector, const Scalar &scalar) InlineMethod
Subtracts the scalar from every component of the vector and returns the result.
template<int Size, typename Scalar >
bool equals (const Vector< Size, Scalar > &lhs, const Scalar &cmp, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
!!! Vectorisation remark
template<int Size, typename Scalar >
bool oneEquals (const Vector< Size, Scalar > &lhs, const Scalar &cmp, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
template<int Size, typename Scalar >
bool oneGreater (const Vector< Size, Scalar > &lhs, const Scalar &cmp, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
template<int Size, typename Scalar >
bool oneGreaterEquals (const Vector< Size, Scalar > &lhs, const Scalar &cmp, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
template<int Size, typename Scalar >
bool allGreater (const Vector< Size, Scalar > &lhs, const Scalar &cmp, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
template<int Size, typename Scalar >
bool allGreaterEquals (const Vector< Size, Scalar > &lhs, const Scalar &cmp, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
template<int Size, typename Scalar >
bool oneSmaller (const Vector< Size, Scalar > &lhs, const Scalar &cmp, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
template<int Size, typename Scalar >
bool oneSmallerEquals (const Vector< Size, Scalar > &lhs, const Scalar &cmp, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
template<int Size, typename Scalar >
bool allSmaller (const Vector< Size, Scalar > &lhs, const Scalar &cmp, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
template<int Size, typename Scalar >
bool allSmallerEquals (const Vector< Size, Scalar > &lhs, const Scalar &cmp, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
template<int Size>
bool equals (const Vector< Size, int > &lhs, const int &cmp)
Specialisation for int.
template<int Size>
bool oneEquals (const Vector< Size, int > &lhs, const int &cmp)
template<int Size>
bool oneGreater (const Vector< Size, int > &lhs, const int &cmp)
template<int Size>
bool oneGreaterEquals (const Vector< Size, int > &lhs, const int &cmp)
template<int Size>
bool oneSmaller (const Vector< Size, int > &lhs, const int &cmp)
template<int Size>
bool oneSmallerEquals (const Vector< Size, int > &lhs, const int &cmp)
template<int Size>
bool allGreater (const Vector< Size, int > &lhs, const int &cmp)
template<int Size>
bool allGreaterEquals (const Vector< Size, int > &lhs, const int &cmp)
template<int Size>
bool allSmaller (const Vector< Size, int > &lhs, const int &cmp)
template<int Size>
bool allSmallerEquals (const Vector< Size, int > &lhs, const int &cmp)
template<int Size, typename Scalar >
Vector< Size, Scalar > remainder (const Vector< Size, Scalar > &vector, double h)
Return the remainder of a division.
template<int SizeLhs, int SizeRhs, typename Scalar >
Vector< SizeLhs, Scalar > slice (const Vector< SizeRhs, Scalar > &vector, int fromIndex, int stride=1)
Returns subpart of the vector.
template<int SizeLhs, int SizeRhs, typename Scalar >
void slice (Vector< SizeLhs, Scalar > &toVector, const Vector< SizeRhs, Scalar > &fromVector, int fromIndexInToVector, int strideInToVector=1)
Setter.
template<int SizeLhs, int SizeRhs, typename Scalar >
Vector< SizeLhs, Scalar > expandOrSlice (const Vector< SizeRhs, Scalar > &vector)
Take a scalar or vector and map it onto a vector.
template<int SizeLhs, typename Scalar >
Vector< SizeLhs, Scalar > expandOrSlice (const Scalar &scalar)
Delegates to slice().
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > & operator+= (Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs) InlineMethod
Adds rVector to lVector and assigns the result to lVector.
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > & operator-= (Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs) InlineMethod
Subtracts rVector from lVector and assigns the result to lVector.
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > operator+ (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs) InlineMethod
Adds rVector to lVector.
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > operator- (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs) InlineMethod
Subtracts rVector from lVector.
template<int Size, typename Scalar >
GPUCallableMethod Vector< Size, Scalar > multiplyComponents (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs) InlineMethod
Multiplies every component of the vectors with each other and writes the results into result.
template<int Size, typename Scalar >
GPUCallableMethod Scalar operator* (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs) InlineMethod
Performs the dot (=inner) product of two vectors.
template<int Size, typename Scalar >
GPUCallableMethod Scalar dot (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs) InlineMethod
Performs the dot (=inner) product of two vectors.
template<int Size, typename Scalar >
GPUCallableMethod Scalar innerDot (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs) InlineMethod
Performs the dot (=inner) product of two vectors.
template<typename Scalar >
GPUCallableMethod Vector< 3, Scalar > cross (const Vector< 3, Scalar > &lhs, const Vector< 3, Scalar > &rhs) InlineMethod
Performs the cross product of two 3D vectors into result.
template<int Size, typename Scalar >
bool equals (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
Compares to vectors on equality by means of a numerical accuracy.
template<int Size, typename Scalar >
bool firstGreater (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
Compares sequentially every component pair of lVector and rVector, and stops as soon as one is greater than the other.
template<int Size, typename Scalar >
bool oneGreater (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
Returns true, if one component of lVector is greater than the corresponding component in rVector up to numerical accuracy.
template<int Size, typename Scalar >
bool oneGreaterEquals (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
Returns true, if one component of lVector is greater or equals than the corresponding component in rVector up to numerical accuracy.
template<int Size, typename Scalar >
bool allGreater (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
Returns true, if all components of lVector are greater than the corresponding components in rVector up to numerical accuracy.
template<int Size, typename Scalar >
bool allGreaterEquals (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
Returns true, if all components of lVector are greater or equals than the corresponding components in rVector up to numerical accuracy.
template<int Size, typename Scalar >
bool allSmaller (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
template<int Size, typename Scalar >
bool allSmallerEquals (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
template<int Size, typename Scalar >
bool oneSmaller (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
template<int Size, typename Scalar >
bool oneSmallerEquals (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
template<int Size, typename Scalar >
Vector< Size, Scalar > max (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs)
Component-wise max evaluation.
template<int Size, typename Scalar >
Vector< Size, Scalar > min (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs)
Component-wise min evaluation.
template<int Size, typename Scalar >
bool operator== (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs)
Bit-wise comparison of the components of two vectors for equality.
template<int Size, typename Scalar >
bool operator!= (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs)
Bit-wise comparison of the components of two vectors for inequality.
template<int Size, typename Scalar >
int equalsReturnIndex (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
Return Index of element which is not equals.
template<int Size>
int equalsReturnIndex (const Vector< Size, int > &lhs, const Vector< Size, int > &rhs)
template<int Size>
int countEqualEntries (const Vector< Size, int > &lhs, const Vector< Size, int > &rhs)
Run through both vectors and count how many entries are the same.
template<int Size, typename Scalar >
int countEqualEntries (const Vector< Size, Scalar > &lhs, const Vector< Size, Scalar > &rhs, const Scalar tolerance=NUMERICAL_ZERO_DIFFERENCE)
Variables
constexpr double PI = 3.1415926535897932384626433832795028841972
constexpr double E = 2.7182818284590452353602874713526624977572
constexpr double NUMERICAL_ZERO_DIFFERENCE = 1.0e-8
Detailed Description
My collection of tiny vector operations.
The coolest thing about this one is that it supports Matlab/Python-ensque vector notations. Otherwise, it is pretty trivial.
Function Documentation
abs() [1/5]
GPUCallableMethod double tarch::la::abs (const std::complex< double > & value)
Definition at line 10 of file ScalarOperations.cpph.
abs() [2/5]
template<int Size, typename Scalar > Vector< Size, Scalar > tarch::la::abs (const Vector< Size, Scalar > & vector)
Computes the absolute component values of the vector, creating a temporary vector to hold the result.
Returns
A copy of the temporary holding the result.
abs() [3/5]
template<int Size> Vector< Size, double > tarch::la::abs (const Vector< Size, std::complex< double > > & vector)
Specialisation that is different to standard definition.
Works as result type is not part of the signature
abs() [4/5]
GPUCallableMethod double tarch::la::abs (double value)
Returns the absolute value of a type by redirecting to std::abs.
Definition at line 15 of file ScalarOperations.cpph.
References std::abs().
Referenced by swift2::kernels::legacy::hydro_prepare_force(), norm1(), norm1(), tarch::la::tests::ScalarTest::testAbs(), toolbox::particles::tests::MultiscaleTransitionsTest::testSievePredicate(), tarch::la::Matrix< Rows, Cols, Scalar >::toPrettyString(), and tarch::la::ShallowMatrix< Rows, Cols, Scalar >::toPrettyString().
abs() [5/5]
GPUCallableMethod int tarch::la::abs (int value)
Returns the absolute value of the given int.
Definition at line 5 of file ScalarOperations.cpph.
allEntriesAreTheSame()
template<int Size, typename Scalar > bool tarch::la::allEntriesAreTheSame (const Vector< Size, Scalar > & vector)
Definition at line 21 of file VectorOperations.cpph.
References equals().
allGreater() [1/3]
template<int Size> bool tarch::la::allGreater (const Vector< Size, int > & lhs, const int & cmp)
Definition at line 435 of file VectorScalarOperations.cpph.
allGreater() [2/3]
template<int Size, typename Scalar > bool tarch::la::allGreater (const Vector< Size, Scalar > & lhs, const Scalar & cmp, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 269 of file VectorScalarOperations.cpph.
References greater().
Referenced by toolbox::particles::assignmentchecks::tests::internal::dropParticle(), and tarch::la::tests::VectorTest::testVectorVectorOperations().
allGreater() [3/3]
template<int Size, typename Scalar > bool tarch::la::allGreater (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Returns true, if all components of lVector are greater than the corresponding components in rVector up to numerical accuracy.
Parameters
tolerance Absolute tolerance. If you prefer to use a relative measure, you might want to use tarch::la::relativeEps()
Definition at line 237 of file VectorVectorOperations.cpph.
References greater().
allGreaterEquals() [1/3]
template<int Size> bool tarch::la::allGreaterEquals (const Vector< Size, int > & lhs, const int & cmp)
Definition at line 456 of file VectorScalarOperations.cpph.
allGreaterEquals() [2/3]
template<int Size, typename Scalar > bool tarch::la::allGreaterEquals (const Vector< Size, Scalar > & lhs, const Scalar & cmp, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 279 of file VectorScalarOperations.cpph.
References greaterEquals().
Referenced by peano4::grid::Spacetree::evaluateGridControlEvents(), toolbox::finiteelements::BSplinesStencilFactory::getElementWiseAssemblyMatrix(), toolbox::finiteelements::BSplinesStencilFactory::getElementWiseAssemblyMatrix(), peano4::grid::isContained(), peano4::grid::overlaps(), peano4::grid::overlaps(), and toolbox::particles::particleWillStayWithinComputationalDomain().
allGreaterEquals() [3/3]
template<int Size, typename Scalar > bool tarch::la::allGreaterEquals (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Returns true, if all components of lVector are greater or equals than the corresponding components in rVector up to numerical accuracy.
Definition at line 251 of file VectorVectorOperations.cpph.
References greaterEquals().
allSmaller() [1/3]
template<int Size> bool tarch::la::allSmaller (const Vector< Size, int > & lhs, const int & cmp)
Definition at line 477 of file VectorScalarOperations.cpph.
allSmaller() [2/3]
template<int Size, typename Scalar > bool tarch::la::allSmaller (const Vector< Size, Scalar > & lhs, const Scalar & cmp, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 289 of file VectorScalarOperations.cpph.
References smaller().
Referenced by toolbox::particles::assignmentchecks::tests::internal::dropParticle(), peano4::grid::Spacetree::evaluateGridControlEvents(), toolbox::finiteelements::BSplinesStencilFactory::getElementWiseAssemblyMatrix(), and toolbox::finiteelements::BSplinesStencilFactory::getElementWiseAssemblyMatrix().
allSmaller() [3/3]
template<int Size, typename Scalar > bool tarch::la::allSmaller (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 265 of file VectorVectorOperations.cpph.
References smaller().
allSmallerEquals() [1/3]
template<int Size> bool tarch::la::allSmallerEquals (const Vector< Size, int > & lhs, const int & cmp)
Definition at line 498 of file VectorScalarOperations.cpph.
allSmallerEquals() [2/3]
template<int Size, typename Scalar > bool tarch::la::allSmallerEquals (const Vector< Size, Scalar > & lhs, const Scalar & cmp, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 299 of file VectorScalarOperations.cpph.
References smallerEquals().
Referenced by peano4::grid::isContained(), peano4::grid::overlaps(), peano4::grid::overlaps(), and toolbox::particles::particleWillStayWithinComputationalDomain().
allSmallerEquals() [3/3]
template<int Size, typename Scalar > bool tarch::la::allSmallerEquals (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 279 of file VectorVectorOperations.cpph.
References smallerEquals().
aPowI()
GPUCallableMethod int tarch::la::aPowI (int i, int a)
Computes the i-th power of a in integer arithmetic.
Definition at line 20 of file ScalarOperations.cpph.
References a.
Referenced by peano4::utils::dDelinearisedWithoutLookup(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::getCellsPerPatch(), peano4::utils::getKeyForDDeLinearisedLookup(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::getVerticesPerPatch(), peano4::utils::setupLookupTableForDDelinearised(), peano4::utils::tests::LinearisedTest::testDelinearisedVector(), and peano4::utils::tests::LinearisedTest::testLookupTableDelinearised().
average()
template<int Size, typename Scalar > Scalar tarch::la::average (const Vector< Size, Scalar > & vector)
Computes the volume of the tetrahedron spanned by the Cartesian unit vectors scaled by the corresponding components of the given vector.
Definition at line 161 of file VectorOperations.cpph.
backSubstitution() [1/2]
void tarch::la::backSubstitution (const DynamicMatrix & R, const double * f, double * x)
Definition at line 5 of file LUDecompositionDynamic.cpp.
References tarch::la::DynamicMatrix::cols(), greater(), and smaller().
backSubstitution() [2/2]
template<int Rows, typename Scalar > Vector< Rows, Scalar > tarch::la::backSubstitution (const Matrix< Rows, Rows, Scalar > & R, const Vector< Rows, Scalar > & f)
Back substitution following LU decomposition.
Accepts an upper triangular matrix and a rhs. It then returns the solution x to \(Rx=f \) i.e. \(x=R^{-1}f \). We assume that R is a proper, non-normalised upper triangular matrix. It does not have to have 1s on the diagonals.
Parameters
R the upper matrix from the LU decomposition
Referenced by invertUpperTriangular().
buildMatrix()
template<int Rows, int Cols, typename Scalar > Matrix< Rows, Cols, Scalar > tarch::la::buildMatrix (const Scalar * values)
Deep copy builder function.
Become friend of builder mechanism.
We faced issues with some compiler versions with offering a constructor that simply takes a pointer to scalars. Further to that, it is not clear if such a constructor would create a deep copy or a shallow copy. Therefore, I decided to introduce an explicit builder function.
col()
template<int Rows, int Cols, typename Scalar > Vector< Rows, Scalar > tarch::la::col (const Matrix< Rows, Cols, Scalar > & matrix, int whichColumn)
Extract row from matrix.
Referenced by tarch::la::DynamicMatrix::batchedMultiplyAoS(), tarch::la::DynamicMatrix::insertEmptyColumns(), tarch::la::DynamicMatrix::insertEmptyRows(), invertUpperTriangular(), tarch::la::DynamicMatrix::multiply(), tarch::la::DynamicMatrix::multiplyBySmallMatrix(), tarch::la::DynamicMatrix::operator()(), tarch::la::DynamicMatrix::operator()(), operator*(), tarch::la::DynamicMatrix::operator==(), tarch::la::DynamicMatrix::operator==(), tarch::la::DynamicMatrix::removeColumn(), tarch::la::DynamicMatrix::replicateRows(), tarch::la::DynamicMatrix::scale(), tarch::la::DynamicMatrix::serialise(), tarch::la::DynamicMatrix::serialise(), tarch::la::DynamicMatrix::shiftColumnsRight(), tarch::la::DynamicMatrix::shiftRowsDown(), and tarch::la::DynamicMatrix::toString().
contains()
template<int Size, typename Scalar > bool tarch::la::contains (const Vector< Size, Scalar > & vector, const Scalar & value)
Definition at line 48 of file VectorOperations.cpph.
Referenced by peano4::grid::GridTraversalEventGenerator::createEnterCellTraversalEvent(), peano4::grid::Spacetree::isCellSplitCandidate(), peano4::grid::Spacetree::mergeGridVertexRefinementStateAtHorizontalDomainBoundary(), peano4::grid::Spacetree::receiveAndMergeGridVertexAtVerticalBoundary(), peano4::grid::Spacetree::sendUserData(), and peano4::grid::Spacetree::shouldEraseAdjacencyInformation().
convertAbsoluteIntoRelativeValue()
double tarch::la::convertAbsoluteIntoRelativeValue (double referenceValue, double value)
Convert an absolute value into a relative one.
That is if the referenceValue is smaller than one, then we do nothing. Otherwise, we divide the absolute value by the reference value.
Definition at line 26 of file Scalar.cpp.
References std::abs().
convertScalar() [1/2]
template<typename NewScalarType , int Size, typename Scalar > tarch::la::SmartPointerVector< Size, NewScalarType > tarch::la::convertScalar (const tarch::la::SmartPointerVector< Size, Scalar > & SmartPointerVector)
Definition at line 140 of file SmartPointerVector.cpph.
References max().
Referenced by toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_secondOrder(), and toolbox::blockstructured::internal::projectCells_AoS().
convertScalar() [2/2]
template<typename NewScalarType , int Size, typename Scalar > tarch::la::Vector< Size, NewScalarType > tarch::la::convertScalar (const tarch::la::Vector< Size, Scalar > & vector)
Convert the scalar type underlying a vector.
This routine takes a vector of size Size over type Scalar and returns a new vector of the same size but with type NewScalarType. A typical usage looks similar to
tarch::la::Vector< Dimensions, int > myVector = ...
tarch::la::Vector< Dimensions, double > converted = tarch::la::convertScalar<double>(myVector);
The conversion assumes that C++ natively supports a conversion from Scalar to NewScalarType. We do not employ any explicit typecasting under the hood.
Definition at line 63 of file Vector.cpph.
References max().
count()
template<int Size, typename Scalar > int tarch::la::count (const Vector< Size, Scalar > & vector, const Scalar & value)
Definition at line 10 of file VectorOperations.cpph.
References equals().
Referenced by exahype2::fv::plotPatch().
countEqualEntries() [1/2]
template<int Size> int tarch::la::countEqualEntries (const Vector< Size, int > & lhs, const Vector< Size, int > & rhs)
Run through both vectors and count how many entries are the same.
Definition at line 371 of file VectorVectorOperations.cpph.
Referenced by peano4::grid::Spacetree::mergeGridVertexRefinementStateAtHorizontalDomainBoundary().
countEqualEntries() [2/2]
template<int Size, typename Scalar > int tarch::la::countEqualEntries (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 386 of file VectorVectorOperations.cpph.
cross()
template<typename Scalar > GPUCallableMethod Vector< 3, Scalar > tarch::la::cross (const Vector< 3, Scalar > & lhs, const Vector< 3, Scalar > & rhs)
Performs the cross product of two 3D vectors into result.
Referenced by tarch::la::tests::VectorTest::testVectorVectorOperations().
det() [1/2]
template<typename Scalar > double tarch::la::det (const Matrix< 2, 2, Scalar > & R)
Definition at line 75 of file LUDecomposition.cpph.
det() [2/2]
template<typename Scalar > double tarch::la::det (const Matrix< 3, 3, Scalar > & R)
Definition at line 159 of file LUDecomposition.cpph.
diag()
template<int Rows, typename Scalar > Vector< Rows, Scalar > tarch::la::diag (const Matrix< Rows, Rows, Scalar > & matrix)
Extract diagonal vector from matrix.
dot()
template<int Size, typename Scalar > GPUCallableMethod Scalar tarch::la::dot (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs)
Performs the dot (=inner) product of two vectors.
For the outer dot product consult the file MatrixVectorOperations.h.
Definition at line 149 of file VectorVectorOperations.cpph.
References innerDot().
Referenced by swift2::kernels::legacy::density_kernel(), swift2::kernels::legacy::force_kernel(), and tarch::la::tests::VectorTest::testVectorVectorOperations().
equals() [1/6]
template<int Rows, int Cols, typename Scalar > bool tarch::la::equals (const Matrix< Rows, Cols, Scalar > & lhs, const Matrix< Rows, Cols, Scalar > & rhs, const Scalar & tolerance = NUMERICAL_ZERO_DIFFERENCE)
Compares to matrices on equality by means of a numerical accuracy.
Definition at line 100 of file MatrixMatrixOperations.cpph.
Referenced by examples::exahype2::mgccz4::FiniteVolumeMGCCZ4::adjustSolution(), examples::exahype2::mgccz4::ADERDGMGCCZ4::adjustSolution(), allEntriesAreTheSame(), tarch::plotter::PVDTimeSeriesWriter::appendNewData(), swift2::boundaryconditions::applyFixedBoundaryCondition(), exahype2::fd::applySommerfeldConditions(), swift2::timestepping::computeAdmissibleTimeStepSizeFromGlobalMeshSizeAndMaximumVelocity(), count(), peano4::grid::internal::equals(), toolbox::particles::TrajectoryDatabase::getAction(), toolbox::particles::TrajectoryDatabase::getAction(), toolbox::blockstructured::GlobalDatabase::getAction(), toolbox::finiteelements::getElementWiseAssemblyMatrix(), exahype2::getInterpolationWeights(), benchmarks::swift2::hydro::kernel_throughput::initNohProblemIC(), ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::initUnknownsPatch(), peano4::grid::Spacetree::mergeGridVertexRefinementStateAtHorizontalDomainBoundary(), tarch::la::DynamicMatrix::operator==(), tarch::la::DynamicMatrix::operator==(), tarch::plotter::PVDTimeSeriesWriter::parseFile(), toolbox::particles::particleIsDuplicate(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::plotCell(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::plotCell(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::plotCell(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::plotCell(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::plotVertex(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::plotVertex(), applications::exahype2::ccz4::CCZ4::refinementCriterion(), exahype2::removeTimeStepAccumulationErrorsFromCell(), tarch::plotter::griddata::blockstructured::restartPreprocess(), exahype2::runTimeStepOnCell(), mghype::matrixfree::solvers::SolverStatistics::terminationCriterionHolds(), tarch::la::tests::ScalarTest::testComparison(), peano4::grid::tests::GridControlEventTest::testMerge1(), tarch::la::tests::GramSchmidtTest::testModifiedGramSchmidt(), tarch::la::tests::VectorTest::testVectorVectorOperations(), peano4::grid::internal::twoEventsAreAdjacent(), and validateOutcome().
equals() [2/6]
GPUCallableMethod bool tarch::la::equals (const std::complex< double > & lhs, const std::complex< double > & rhs, double tolerance = NUMERICAL_ZERO_DIFFERENCE)
Parameters
tolerance Absolute tolerance when we compare two values.
Definition at line 74 of file ScalarOperations.cpph.
References std::abs().
equals() [3/6]
template<int Size> bool tarch::la::equals (const Vector< Size, int > & lhs, const int & cmp)
Specialisation for int.
Definition at line 309 of file VectorScalarOperations.cpph.
equals() [4/6]
template<int Size, typename Scalar > bool tarch::la::equals (const Vector< Size, Scalar > & lhs, const Scalar & cmp, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
!!! Vectorisation remark
The Intel compiler refuses to vectorise these code fragments if they exit early. As a consequence, we have to remove early exit instructions though they might be faster for very long vectors. In Peano, vectors typically are pretty short and thus we have no early exit condition if you use the Intel compiler.
Definition at line 143 of file VectorScalarOperations.cpph.
equals() [5/6]
template<int Size, typename Scalar > bool tarch::la::equals (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Compares to vectors on equality by means of a numerical accuracy.
Parameters
tolerance Absolute tolerance. If you prefer to use a relative measure, you might want to use tarch::la::relativeEps()
Definition at line 174 of file VectorVectorOperations.cpph.
equals() [6/6]
GPUCallableMethod bool tarch::la::equals (double lhs, double rhs, double tolerance = NUMERICAL_ZERO_DIFFERENCE)
Parameters
tolerance Absolute tolerance when we compare two values.
Definition at line 65 of file ScalarOperations.cpph.
References std::abs().
equalsReturnIndex() [1/3]
template<int Rows, int Cols, typename Scalar > std::pair< int, int > tarch::la::equalsReturnIndex (const Matrix< Rows, Cols, Scalar > & lhs, const Matrix< Rows, Cols, Scalar > & rhs, const Scalar & tolerance = NUMERICAL_ZERO_DIFFERENCE)
Return Index of element which is not equals.
Definition at line 153 of file MatrixMatrixOperations.cpph.
References std::abs().
Referenced by tarch::la::tests::MatrixTest::testMatrixMatrixOperations(), and tarch::la::tests::VectorTest::testVectorVectorOperations().
equalsReturnIndex() [2/3]
template<int Size> int tarch::la::equalsReturnIndex (const Vector< Size, int > & lhs, const Vector< Size, int > & rhs)
Definition at line 359 of file VectorVectorOperations.cpph.
equalsReturnIndex() [3/3]
template<int Size, typename Scalar > int tarch::la::equalsReturnIndex (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Return Index of element which is not equals.
Definition at line 346 of file VectorVectorOperations.cpph.
References std::abs().
expandOrSlice() [1/2]
template<int SizeLhs, typename Scalar > Vector< SizeLhs, Scalar > tarch::la::expandOrSlice (const Scalar & scalar)
Delegates to slice().
See also
expandOrSlice()
expandOrSlice() [2/2]
template<int SizeLhs, int SizeRhs, typename Scalar > Vector< SizeLhs, Scalar > tarch::la::expandOrSlice (const Vector< SizeRhs, Scalar > & vector)
Take a scalar or vector and map it onto a vector.
expandOrSlice() is a variant of the slice() operation that I need within for loops, e.g.. It is either given a scalar or a vector with N' entries, and it delivers a vector with N entries. N<N'. That is, if we hand in a scalar, expandOrSlice() expands it into a proper vector. It maps expandOrSlide() onto the constructor with one scalar argument. If we pass in a vector, it slices, i.e. takes the first N entries of this vector to create a new one. The case distinction is realised via overloading.
This version here equals slice().
firstGreater()
template<int Size, typename Scalar > bool tarch::la::firstGreater (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Compares sequentially every component pair of lVector and rVector, and stops as soon as one is greater than the other.
Defines an absolute pairwise ordering between (unequal) vectors.
Parameters
tolerance Absolute tolerance. If you prefer to use a relative measure, you might want to use tarch::la::relativeEps()
Definition at line 189 of file VectorVectorOperations.cpph.
Referenced by tarch::la::VectorCompare< N >::operator()(), and tarch::la::tests::VectorTest::testVectorVectorOperations().
greater()
GPUCallableMethod bool tarch::la::greater (double lhs, double rhs, double tolerance = NUMERICAL_ZERO_DIFFERENCE)
Parameters
tolerance Absolute tolerance when we compare two values.
Definition at line 29 of file ScalarOperations.cpph.
Referenced by allGreater(), allGreater(), toolbox::particles::applyPeriodicBoundaryConditions(), backSubstitution(), swift2::kernels::gravity::computeGravitationalForce(), swift2::kernels::legacy::densityKernelEvaluatePairInteractionPredicate(), exahype2::discretiseAndTruncateTimeStepSizes(), toolbox::blockstructured::GlobalDatabase::dumpDatabaseSnapshot(), toolbox::particles::TrajectoryDatabase::dumpDatabaseSnapshot(), swift2::kernels::legacy::force_kernel(), exahype2::getMinTimeStampOfNeighboursAhead(), modifiedGramSchmidt(), sign(), peano4::grid::internal::sort(), and tarch::la::tests::ScalarTest::testComparison().
greaterEquals()
GPUCallableMethod bool tarch::la::greaterEquals (double lhs, double rhs, double tolerance = NUMERICAL_ZERO_DIFFERENCE)
Parameters
tolerance Absolute tolerance when we compare two values.
Definition at line 38 of file ScalarOperations.cpph.
Referenced by allGreaterEquals(), allGreaterEquals(), toolbox::particles::createParticlesAlignedWithGlobalCartesianMesh(), toolbox::particles::internal::fitsIntoLevel(), toolbox::particles::internal::fitsIntoLevel(), exahype2::getInterpolationWeights(), toolbox::particles::internal::getParticleAssociationWithinCell(), toolbox::particles::FileReader::getParticlesWithinVoxel(), toolbox::particles::FileReaderHDF5::getParticlesWithinVoxel(), swift2::boundaryconditions::getUpdateDueToFixedBoundaryCondition(), toolbox::particles::insertParticleIntoCell(), toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_linear(), peano4::datamanagement::CellMarker::isContained(), toolbox::particles::mirrorParticleAlongPeriodicDomains(), peano4::datamanagement::CellMarker::overlaps(), exahype2::removeTimeStepAccumulationErrorsFromCell(), exahype2::runTimeStepOnCell(), and tarch::la::tests::ScalarTest::testComparison().
identity()
template<int Rows, typename Scalar > static Matrix< Rows, Rows, Scalar > tarch::la::identity () static
Returns the identity matrix.
imag()
template<int Size> Vector< Size, double > tarch::la::imag (const Vector< Size, std::complex< double > > & vector)
indexMax()
template<int Size, typename Scalar > int tarch::la::indexMax (const Vector< Size, Scalar > & vector)
Returns the index of the element with maximal value (NOT absolute value).
Definition at line 184 of file VectorOperations.cpph.
References indexMax().
Referenced by indexMax(), and tarch::la::tests::VectorTest::testVectorOperations().
indexMin()
template<int Size, typename Scalar > int tarch::la::indexMin (const Vector< Size, Scalar > & vector)
Returns the index of the element with minimal value (NOT absolute value).
Definition at line 193 of file VectorOperations.cpph.
References indexMin().
Referenced by indexMin(), and tarch::la::tests::VectorTest::testVectorOperations().
innerDot()
template<int Size, typename Scalar > GPUCallableMethod Scalar tarch::la::innerDot (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs)
Performs the dot (=inner) product of two vectors.
For the outer dot product consult the file MatrixVectorOperations.h.
Definition at line 135 of file VectorVectorOperations.cpph.
Referenced by dot(), and operator*().
invert() [1/3]
template<typename Scalar > Matrix< 2, 2, Scalar > tarch::la::invert (const Matrix< 2, 2, Scalar > & M)
Specialisation of inversion.
This one inverts directly and is usually faster than BLAS.
invert() [2/3]
template<typename Scalar > Matrix< 3, 3, Scalar > tarch::la::invert (const Matrix< 3, 3, Scalar > & M)
Specialisation of inversion.
This one inverts directly and is usually faster than BLAS.
invert() [3/3]
template<int Rows, typename Scalar > Matrix< Rows, Rows, Scalar > tarch::la::invert (const Matrix< Rows, Rows, Scalar > & M)
Invert matrix with LU decomposition.
We first invoke the LU decomposition through a call to lu(). After that, we compute the mat vec and return the result. This is not an optimised version in any way. For small matrices, it should be pretty fast. For larger matrices, you might want to consider the Lapack version available through the alternative invert() version.
Referenced by tarch::la::tests::LUDecompositionTest::testInversion0(), and tarch::la::tests::LUDecompositionTest::testInversion1().
invertEntries()
template<int Size, typename Scalar > Vector< Size, Scalar > tarch::la::invertEntries (const Vector< Size, Scalar > & vector)
invertUpperTriangular()
tarch::la::DynamicMatrix tarch::la::invertUpperTriangular (const DynamicMatrix & R)
Definition at line 22 of file LUDecompositionDynamic.cpp.
References backSubstitution(), col(), and tarch::la::DynamicMatrix::cols().
Referenced by toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_secondOrder(), toolbox::blockstructured::interpolateHaloLayer_AoS_second_order(), toolbox::blockstructured::interpolateHaloLayer_AoS_third_order(), toolbox::blockstructured::restrictInnerHalfOfHaloLayer_AoS_second_order(), and toolbox::blockstructured::restrictInnerHalfOfHaloLayer_AoS_third_order().
isEntryFinite()
template<int Size, typename Scalar > int tarch::la::isEntryFinite (const Vector< Size, Scalar > & vector)
Definition at line 39 of file VectorOperations.cpph.
Referenced by swift2::kernels::legacy::leapfrog_drift_global_time_step_size(), and swift2::timestepping::leapfrogDriftWithGlobalTimeStepSize().
isEntryNan()
template<int Size, typename Scalar > int tarch::la::isEntryNan (const Vector< Size, Scalar > & vector)
Definition at line 30 of file VectorOperations.cpph.
Referenced by swift2::kernels::legacy::force_kernel().
lu() [1/2]
template<int Rows, typename Scalar > void tarch::la::lu (Matrix< Rows, Rows, Scalar > & A)
In-situ LU without pivoting.
See the other LU routine.
Definition at line 57 of file LUDecomposition.cpph.
lu() [2/2]
template<int Rows, typename Scalar > void tarch::la::lu (Matrix< Rows, Rows, Scalar > & A, Vector< Rows, int > & pivots)
Performs an in-situ LU-decomposition of the square matrix A.
Returns pivot values, too. The storage format is normalised such that the diagonal values of the lower triangular matrix are one.
Definition at line 21 of file LUDecomposition.cpph.
References std::abs(), max(), and temp.
Referenced by tarch::la::tests::LUDecompositionTest::testLU().
matVec()
template<int Rows, int Cols, typename Scalar > void tarch::la::matVec (const Matrix< Rows, Cols, Scalar > & matrix, Scalar alpha, const Vector< Cols, Scalar > & v, Vector< Rows, Scalar > & r)
Compute r = r + alpha * M * v in-situ.
Compute r = r + alpha * M * v.
Definition at line 24 of file MatrixVectorOperations.cpph.
References r.
Referenced by mghype::applyMatrixFromHWeightedLinearCombination().
max() [1/3]
template<int Size, typename Scalar > Vector< Size, Scalar > tarch::la::max (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs)
Component-wise max evaluation.
max() [2/3]
template<int Size, typename Scalar > Scalar tarch::la::max (const Vector< Size, Scalar > & vector)
Returns the element with maximal value (NOT absolute value).
Definition at line 202 of file VectorOperations.cpph.
max() [3/3]
double tarch::la::max (double a, double b, double c)
I need the maximum of three values all the time, to I decided to write a function for this.
Definition at line 8 of file Scalar.cpp.
References a.
Referenced by exahype2::fd::applyBoundaryConditions(), exahype2::fv::applyBoundaryConditions(), exahype2::fd::applySommerfeldConditions(), tarch::la::DynamicMatrix::batchedMultiplyAoS(), tarch::la::DynamicMatrix::batchedMultiplyAoS(), tarch::la::Matrix< Rows, Cols, Scalar >::cols(), tarch::la::ShallowMatrix< Rows, Cols, Scalar >::cols(), mghype::matrixfree::solvers::dgcgcoupling::computeAndRestrictHierarchicalResidual(), mghype::matrixfree::solvers::dgcgcoupling::computeAndRestrictResidual(), tarch::la::Matrix< Rows, Cols, Scalar >::convertScalar(), tarch::la::ShallowMatrix< Rows, Cols, Scalar >::convertScalar(), convertScalar(), convertScalar(), peano4::grid::internal::createBoundingBoxEvent(), toolbox::particles::createEquallySpacedParticles(), toolbox::particles::createParticlesAlignedWithGlobalCartesianMesh(), tarch::la::DynamicMatrix::DynamicMatrix(), tarch::la::DynamicMatrix::DynamicMatrix(), tarch::la::DynamicMatrix::DynamicMatrix(), examples::regulargridupscaling::MyObserver::enterCell(), toolbox::particles::getAdjacentCellsOwningParticle(), toolbox::finiteelements::BSplinesStencilFactory::getElementWiseAssemblyMatrix(), toolbox::finiteelements::BSplinesStencilFactory::getElementWiseAssemblyMatrix(), toolbox::finiteelements::getHelmholtzShiftMatrix(), toolbox::finiteelements::getHelmholtzShiftMatrix(), toolbox::finiteelements::getIdentity(), toolbox::finiteelements::getLaplacian(), toolbox::finiteelements::getLaplacian(), toolbox::finiteelements::getMassMatrix(), toolbox::finiteelements::getPoissonMatrixWithJumpingCoefficient(), tarch::la::DynamicMatrix::id(), mghype::matrixfree::solvers::dgcgcoupling::injectSolution(), tarch::la::DynamicMatrix::insertEmptyColumns(), tarch::la::DynamicMatrix::insertEmptyRows(), toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_linear(), toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_secondOrder(), peano4::grid::Spacetree::loadVertices(), lu(), tarch::la::Matrix< Rows, Cols, Scalar >::Matrix(), tarch::la::DynamicMatrix::multiply(), tarch::la::DynamicMatrix::multiplyBySmallMatrix(), tarch::la::SmartPointerVector< Size, Scalar >::operator()(), tarch::la::Vector< Size, Scalar >::operator()(), tarch::la::SmartPointerVector< Size, Scalar >::operator()(), tarch::la::Vector< Size, Scalar >::operator()(), tarch::la::Matrix< Rows, Cols, Scalar >::operator()(), tarch::la::ShallowMatrix< Rows, Cols, Scalar >::operator()(), tarch::la::Matrix< Rows, Cols, Scalar >::operator()(), tarch::la::ShallowMatrix< Rows, Cols, Scalar >::operator()(), operator*(), tarch::la::SmartPointerVector< Size, Scalar >::operator=(), tarch::la::ShallowMatrix< Rows, Cols, Scalar >::operator=(), tarch::la::SmartPointerVector< Size, Scalar >::operator=(), tarch::la::SmartPointerVector< Size, Scalar >::operator=(), tarch::la::DynamicMatrix::operator=(), tarch::la::DynamicMatrix::operator==(), tarch::la::DynamicMatrix::operator==(), tarch::la::SmartPointerVector< Size, Scalar >::operator[](), tarch::la::Vector< Size, Scalar >::operator[](), tarch::la::SmartPointerVector< Size, Scalar >::operator[](), tarch::la::Vector< Size, Scalar >::operator[](), peano4::grid::TraversalVTKPlotter::plotCell(), toolbox::blockstructured::internal::projectCells_AoS(), peano4::datamanagement::reconstructXOfParentVertex(), applications::exahype2::ccz4::CCZ4::refinementCriterion(), toolbox::particles::internal::relativeGrabOwnershipSpatialSortingTolerance(), toolbox::particles::internal::relativeReleaseOwnershipSpatialSortingTolerance(), tarch::la::DynamicMatrix::removeColumn(), tarch::la::DynamicMatrix::replicateCols(), tarch::la::DynamicMatrix::replicateRows(), toolbox::blockstructured::restrictInnerHalfOfHaloLayer_AoS_averaging(), tarch::la::Matrix< Rows, Cols, Scalar >::rows(), tarch::la::ShallowMatrix< Rows, Cols, Scalar >::rows(), selectNextAlgorithmicStep(), tarch::la::DynamicMatrix::serialise(), tarch::la::DynamicMatrix::shiftColumnsRight(), tarch::la::DynamicMatrix::shiftRowsDown(), tarch::la::Matrix< Rows, Cols, Scalar >::size(), tarch::la::ShallowMatrix< Rows, Cols, Scalar >::size(), tarch::la::SmartPointerVector< Size, Scalar >::size(), tarch::la::Vector< Size, Scalar >::size(), tarch::la::SmartPointerVector< Size, Scalar >::SmartPointerVector(), tarch::la::SmartPointerVector< Size, Scalar >::SmartPointerVector(), tarch::la::SmartPointerVector< Size, Scalar >::SmartPointerVector(), tarch::la::SmartPointerVector< Size, Scalar >::SmartPointerVector(), tarch::la::SmartPointerVector< Size, Scalar >::SmartPointerVector(), tarch::la::tests::MatrixTest::testAssignment(), tarch::la::tests::DynamicMatrixTest::testBatchedMultiplyAoS(), tarch::la::tests::ScalarTest::testComparison(), tarch::la::tests::MatrixTest::testConstruction(), tarch::la::tests::VectorTest::testConstruction(), peano4::grid::tests::GridTraversalEventGeneratorTest::testCreateLeaveCellTraversalEvent1(), tarch::la::tests::LUDecompositionTest::testInversion0(), tarch::la::tests::LUDecompositionTest::testInversion1(), tarch::la::tests::LUDecompositionTest::testLU(), tarch::la::tests::MatrixTest::testMatrixMatrixOperations(), tarch::la::tests::MatrixTest::testMatrixOperations(), tarch::la::tests::GramSchmidtTest::testModifiedGramSchmidt(), tarch::la::tests::MatrixVectorTest::testMultiplication(), tarch::la::tests::MatrixTest::testTransposedMatrix(), tarch::la::tests::VectorTest::testVectorOperations(), tarch::la::tests::VectorTest::testVectorVectorOperations(), tarch::la::tests::VectorTest::testWrappedVector(), tarch::la::Matrix< Rows, Cols, Scalar >::toPrettyString(), tarch::la::ShallowMatrix< Rows, Cols, Scalar >::toPrettyString(), tarch::la::Matrix< Rows, Cols, Scalar >::toString(), tarch::la::ShallowMatrix< Rows, Cols, Scalar >::toString(), tarch::la::DynamicMatrix::toString(), toString(), toString(), tarch::la::SmartPointerVector< Size, Scalar >::toVector(), peano4::grid::Spacetree::traverse(), peano4::grid::internal::twoEventsAreAdjacent(), toolbox::particles::updateContainedInAdjacentCellProperty(), mghype::matrixfree::solvers::SolverStatistics::updateMinMaxMeshSize(), exahype2::fv::updateParticleState(), tarch::la::Vector< Size, Scalar >::Vector(), and tarch::la::DynamicMatrix::vectorToString().
maxAbs()
template<int Size, typename Scalar > Scalar tarch::la::maxAbs (const Vector< Size, Scalar > & vector)
Returns the element with maximal absolute value.
Definition at line 213 of file VectorOperations.cpph.
References std::abs().
maxImag()
template<int Size> double tarch::la::maxImag (const Vector< Size, std::complex< double > > & vector)
Definition at line 255 of file VectorOperations.cpph.
maxReal()
template<int Size> double tarch::la::maxReal (const Vector< Size, std::complex< double > > & vector)
Definition at line 246 of file VectorOperations.cpph.
min() [1/2]
template<int Size, typename Scalar > Vector< Size, Scalar > tarch::la::min (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs)
Component-wise min evaluation.
min() [2/2]
template<int Size, typename Scalar > Scalar tarch::la::min (const Vector< Size, Scalar > & vector)
Returns the element with minimal value (NOT absolute value).
Definition at line 264 of file VectorOperations.cpph.
Referenced by swift2::boundaryconditions::applyFixedBoundaryCondition(), peano4::grid::internal::createBoundingBoxEvent(), toolbox::particles::createEquallySpacedParticles(), toolbox::particles::createParticlesAlignedWithGlobalCartesianMesh(), peano4::grid::Spacetree::descend(), toolbox::particles::internal::fitsIntoLevel(), toolbox::particles::internal::fitsIntoLevel(), toolbox::particles::insertParticleIntoCell(), operator+(), tarch::la::tests::VectorTest::testVectorOperations(), peano4::grid::internal::twoEventsAreAdjacent(), mghype::matrixfree::solvers::SolverStatistics::updateMinMaxMeshSize(), and swift2::kernels::legacy::updateSmoothingLengthAndRerunIfRequired().
modifiedGramSchmidt() [1/2]
void tarch::la::modifiedGramSchmidt (DynamicMatrix A, DynamicMatrix & Q, DynamicMatrix & R)
Definition at line 5 of file GramSchmidt.cpp.
References tarch::la::DynamicMatrix::cols(), greater(), and tarch::la::DynamicMatrix::rows().
modifiedGramSchmidt() [2/2]
template<int Rows, int Cols, typename Scalar > void tarch::la::modifiedGramSchmidt (Matrix< Rows, Cols, Scalar > A, Matrix< Rows, Cols, Scalar > & Q, Matrix< Cols, Cols, Scalar > & R)
Produces an economy-size QR decomposition of a matrix A, A is changed.
Preconditions:
The column vectors of A have to be linear independent.
If A has n columns and m rows, then:
n <= m for A
Q has to have same size than A
R has to be a n * n matrix
Postconditions:
A is changed
Q holds an orthonormal basis of range(A) in its column vectors.
R is an upper triangular matrix, with all main diagonal element unequal to zero iff A has full rank.
The algorithm is taken from the book Numerical Mathematics, Second Edition, by Alfio Querteroni, Riccardo Sacco, and Fausto Saleri, Springer, 2007, pages 85-87.
Classic usage:
modifiedGramSchmidt(M, Q, R); tarch::la::Vector<9, double> p = tarch::la::backSubstitution(R,tarch::la::transpose(Q)*f);
Definition at line 2 of file GramSchmidt.cpph.
Referenced by toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_secondOrder(), toolbox::blockstructured::interpolateHaloLayer_AoS_second_order(), toolbox::blockstructured::interpolateHaloLayer_AoS_third_order(), toolbox::blockstructured::restrictInnerHalfOfHaloLayer_AoS_second_order(), toolbox::blockstructured::restrictInnerHalfOfHaloLayer_AoS_third_order(), and tarch::la::tests::GramSchmidtTest::testModifiedGramSchmidt().
multiply() [1/4]
template<int Rows, int Cols, typename Scalar > Vector< Rows, Scalar > tarch::la::multiply (const Matrix< Rows, Cols, Scalar > & matrix, const Vector< Cols, Scalar > & vector)
Performs a matrix x vector multiplication.
The result vector has to be created outside and given as a parameter.
multiply() [2/4]
template<int Rows, int Cols, int X, typename Scalar > Matrix< Rows, Cols, Scalar > tarch::la::multiply (const Matrix< Rows, X, Scalar > & lhs, const Matrix< X, Cols, Scalar > & rhs)
Performs a matrix x matrix multiplication.
The resulting matrix has to be created outside and given as a parameter.
Referenced by tarch::la::tests::GramSchmidtTest::testModifiedGramSchmidt(), and tarch::la::tests::MatrixVectorTest::testMultiplication().
multiply() [3/4]
template<int Rows, int Cols, typename Scalar > Vector< Rows, Scalar > tarch::la::multiply (const ShallowMatrix< Rows, Cols, Scalar > & matrix, const SmartPointerVector< Cols, Scalar > & vector)
multiply() [4/4]
template<int Rows, int Cols, typename Scalar > Vector< Rows, Scalar > tarch::la::multiply (const ShallowMatrix< Rows, Cols, Scalar > & matrix, const Vector< Cols, Scalar > & vector)
Performs a matrix x vector multiplication.
The result vector has to be created outside and given as a parameter.
multiplyComponents() [1/2]
template<int Rows, int Cols, int X, typename Scalar > Matrix< Rows, Cols, Scalar > tarch::la::multiplyComponents (const Matrix< Rows, X, Scalar > & lhs, const Matrix< X, Cols, Scalar > & rhs)
Referenced by exahype2::fd::applyBoundaryConditions(), exahype2::fv::applyBoundaryConditions(), exahype2::fd::applySommerfeldConditions(), toolbox::particles::getAdjacentCellsOwningParticle(), toolbox::finiteelements::getPoissonMatrixWithJumpingCoefficient(), exahype2::dg::getQuadraturePoint(), toolbox::particles::insertParticleIntoCell(), toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_linear(), peano4::grid::Spacetree::loadVertices(), peano4::grid::TraversalVTKPlotter::plotCell(), toolbox::blockstructured::internal::projectCells_AoS(), peano4::datamanagement::reconstructXOfParentVertex(), toolbox::particles::updateContainedInAdjacentCellProperty(), and toolbox::particles::updateContainedInAdjacentCellProperty().
multiplyComponents() [2/2]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > tarch::la::multiplyComponents (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs)
Multiplies every component of the vectors with each other and writes the results into result.
norm1() [1/2]
template<int Size, typename Scalar > Scalar tarch::la::norm1 (const Vector< Size, Scalar > & vector)
Computes the 1-norm of the vector, i.e.
it sums up abs. component values.
Definition at line 70 of file VectorOperations.cpph.
References abs().
Referenced by tarch::la::tests::VectorTest::testVectorOperations().
norm1() [2/2]
template<int Size> double tarch::la::norm1 (const Vector< Size, std::complex< double > > & vector)
Specialisation that is different to standard definition.
Works as result type is not part of the signature
Definition at line 79 of file VectorOperations.cpph.
References abs().
norm2() [1/2]
template<int Size, typename Scalar > GPUCallableMethod Scalar tarch::la::norm2 (const Vector< Size, Scalar > & vector)
Computes the 2-norm of the vector, i.e.
it takes the square-root of summed up squared component values.
Definition at line 99 of file VectorOperations.cpph.
References norm2Squared().
Referenced by exahype2::fd::applySommerfeldConditions(), swift2::kernels::gravity::computeGravitationalForce(), swift2::kernels::legacy::density_kernel(), swift2::kernels::legacy::force_kernel(), toolbox::particles::TrajectoryDatabase::getAction(), swift2::kernels::legacy::hydro_prepare_force(), benchmarks::swift2::hydro::kernel_throughput::initNohProblemIC(), benchmarks::exahype2::ccz4::CCZ4SBH_FV::isCellOverlappingWithBHImpactArea(), swift2::statistics::reduceVelocityAndSearchRadius(), benchmarks::exahype2::ccz4::CCZ4SBH_FD4::refinementCriterion(), applications::exahype2::ccz4::CCZ4::refinementCriterion(), and toolbox::particles::potentials::springPotential().
norm2() [2/2]
template<int Size> GPUCallableMethod double tarch::la::norm2 (const Vector< Size, std::complex< double > > & vector)
Specialisation that is different to standard definition.
Works as result type is not part of the signature
Definition at line 116 of file VectorOperations.cpph.
References norm2Squared().
norm2Squared() [1/2]
template<int Size, typename Scalar > GPUCallableMethod Scalar tarch::la::norm2Squared (const Vector< Size, Scalar > & vector)
Definition at line 89 of file VectorOperations.cpph.
Referenced by swift2::kernels::adoptInteractionRadiusAndTriggerRerun(), swift2::kernels::legacy::densityKernelEvaluatePairInteractionPredicate(), norm2(), and norm2().
norm2Squared() [2/2]
template<int Size> GPUCallableMethod double tarch::la::norm2Squared (const Vector< Size, std::complex< double > > & vector)
Definition at line 105 of file VectorOperations.cpph.
normMax() [1/2]
template<int Size, typename Scalar > Scalar tarch::la::normMax (const Vector< Size, Scalar > & vector)
Computes the max-norm of the vector.
Definition at line 121 of file VectorOperations.cpph.
References std::abs().
Referenced by toolbox::particles::assignmentchecks::internal::ParticleIdentifier::getVertexDepth().
normMax() [2/2]
template<int Size> double tarch::la::normMax (const Vector< Size, std::complex< double > > & vector)
Specialisation that is different to standard definition.
Works as result type is not part of the signature
Definition at line 132 of file VectorOperations.cpph.
References std::abs().
oneEquals() [1/2]
template<int Size> bool tarch::la::oneEquals (const Vector< Size, int > & lhs, const int & cmp)
Definition at line 330 of file VectorScalarOperations.cpph.
oneEquals() [2/2]
template<int Size, typename Scalar > bool tarch::la::oneEquals (const Vector< Size, Scalar > & lhs, const Scalar & cmp, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 164 of file VectorScalarOperations.cpph.
oneGreater() [1/3]
template<int Size> bool tarch::la::oneGreater (const Vector< Size, int > & lhs, const int & cmp)
Definition at line 351 of file VectorScalarOperations.cpph.
oneGreater() [2/3]
template<int Size, typename Scalar > bool tarch::la::oneGreater (const Vector< Size, Scalar > & lhs, const Scalar & cmp, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 185 of file VectorScalarOperations.cpph.
Referenced by swift2::kernels::flagBoundaryParticles(), swift2::kernels::coalesced::forAllParticlePairs(), swift2::kernels::forAllParticlePairs(), swift2::kernels::internal::identifyInteractingParticles(), toolbox::particles::assignmentchecks::tests::internal::liftParticle(), and tarch::la::tests::VectorTest::testVectorVectorOperations().
oneGreater() [3/3]
template<int Size, typename Scalar > bool tarch::la::oneGreater (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Returns true, if one component of lVector is greater than the corresponding component in rVector up to numerical accuracy.
Parameters
tolerance Absolute tolerance. If you prefer to use a relative measure, you might want to use tarch::la::relativeEps()
Definition at line 207 of file VectorVectorOperations.cpph.
oneGreaterEquals() [1/3]
template<int Size> bool tarch::la::oneGreaterEquals (const Vector< Size, int > & lhs, const int & cmp)
Definition at line 372 of file VectorScalarOperations.cpph.
oneGreaterEquals() [2/3]
template<int Size, typename Scalar > bool tarch::la::oneGreaterEquals (const Vector< Size, Scalar > & lhs, const Scalar & cmp, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 206 of file VectorScalarOperations.cpph.
Referenced by swift2::boundaryconditions::isVertexOnGlobalBoundary(), and tarch::la::tests::VectorTest::testVectorVectorOperations().
oneGreaterEquals() [3/3]
template<int Size, typename Scalar > bool tarch::la::oneGreaterEquals (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Returns true, if one component of lVector is greater or equals than the corresponding component in rVector up to numerical accuracy.
Definition at line 222 of file VectorVectorOperations.cpph.
oneSmaller() [1/3]
template<int Size> bool tarch::la::oneSmaller (const Vector< Size, int > & lhs, const int & cmp)
Definition at line 393 of file VectorScalarOperations.cpph.
oneSmaller() [2/3]
template<int Size, typename Scalar > bool tarch::la::oneSmaller (const Vector< Size, Scalar > & lhs, const Scalar & cmp, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 227 of file VectorScalarOperations.cpph.
Referenced by swift2::kernels::flagBoundaryParticles(), toolbox::particles::assignmentchecks::tests::internal::liftParticle(), and toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditions().
oneSmaller() [3/3]
template<int Size, typename Scalar > bool tarch::la::oneSmaller (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 293 of file VectorVectorOperations.cpph.
References smaller().
oneSmallerEquals() [1/3]
template<int Size> bool tarch::la::oneSmallerEquals (const Vector< Size, int > & lhs, const int & cmp)
Definition at line 414 of file VectorScalarOperations.cpph.
oneSmallerEquals() [2/3]
template<int Size, typename Scalar > bool tarch::la::oneSmallerEquals (const Vector< Size, Scalar > & lhs, const Scalar & cmp, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 248 of file VectorScalarOperations.cpph.
Referenced by swift2::boundaryconditions::isVertexOnGlobalBoundary(), and peano4::grid::internal::refinementEventOverrulesCoarsening().
oneSmallerEquals() [3/3]
template<int Size, typename Scalar > bool tarch::la::oneSmallerEquals (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs, const Scalar tolerance = NUMERICAL_ZERO_DIFFERENCE)
Definition at line 308 of file VectorVectorOperations.cpph.
References smallerEquals().
operator!=()
template<int Size, typename Scalar > bool tarch::la::operator!= (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs)
Bit-wise comparison of the components of two vectors for inequality.
This method should not be used for floating-point valued vectors. Instead, !equals() is the suitable comparison.
Definition at line 337 of file VectorVectorOperations.cpph.
operator*() [1/8]
template<int Rows, int Cols> Matrix< Rows, Cols, std::complex< double > > tarch::la::operator* (const double & scalar, const Matrix< Rows, Cols, std::complex< double > > & matrix)
operator*() [2/8]
template<int Rows, int Cols, typename Scalar > Matrix< Rows, Cols, Scalar > tarch::la::operator* (const Matrix< Rows, Cols, Scalar > & matrix, const Scalar & scalar)
Multiplies every component of the matrix with the scalar.
No temporary objects are created during the operation.
operator*() [3/8]
template<int Rows, int Cols, typename Scalar > Vector< Rows, Scalar > tarch::la::operator* (const Matrix< Rows, Cols, Scalar > & matrix, const Vector< Cols, Scalar > & vector)
Performs a matrix x vector multiplication.
The result vector is created inside, multiply is used to execute the multiplication.
operator*() [4/8]
template<int Rows, int Cols, int X, typename Scalar > Matrix< Rows, Cols, Scalar > tarch::la::operator* (const Matrix< Rows, X, Scalar > & lhs, const Matrix< X, Cols, Scalar > & rhs)
operator*() [5/8]
template<int Rows, int Cols, typename Scalar > Matrix< Rows, Cols, Scalar > tarch::la::operator* (const Scalar & scalar, const Matrix< Rows, Cols, Scalar > & matrix)
Multiplies every component of the matrix with the scalar.
No temporary objects are created during the operation.
operator*() [6/8]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > tarch::la::operator* (const Scalar & scalar, const Vector< Size, Scalar > & vector)
operator*() [7/8]
template<int Size, typename Scalar > GPUCallableMethod Scalar tarch::la::operator* (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs)
Performs the dot (=inner) product of two vectors.
For the outer dot product consult the file MatrixVectorOperations.h.
Definition at line 125 of file VectorVectorOperations.cpph.
References innerDot().
operator*() [8/8]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > tarch::la::operator* (const Vector< Size, Scalar > & vector, const Scalar & scalar)
Multiplies every component of the vector with the scalar and returns the result.
A temporary vector is created during the operation and copied as result.
operator*=() [1/2]
template<int Rows, int Cols, typename Scalar > Matrix< Rows, Cols, Scalar > & tarch::la::operator*= (Matrix< Rows, Cols, Scalar > & matrix, const Scalar & scalar)
operator*=() [2/2]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > & tarch::la::operator*= (Vector< Size, Scalar > & vector, const Scalar & scalar)
Multiplies every component of the vector with the scalar and assigns the result to the vector.
No temporary objects are created during the operation.
operator+() [1/4]
template<int Rows, int Cols, typename Scalar > Matrix< Rows, Cols, Scalar > tarch::la::operator+ (const Matrix< Rows, Cols, Scalar > & lhs, const Matrix< Rows, Cols, Scalar > & rhs)
operator+() [2/4]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > tarch::la::operator+ (const Scalar & scalar, const Vector< Size, Scalar > & vector)
operator+() [3/4]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > tarch::la::operator+ (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs)
Adds rVector to lVector.
A temporary vector is created and copied to store return back the result.
operator+() [4/4]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > tarch::la::operator+ (const Vector< Size, Scalar > & vector, const Scalar & scalar)
Adds the scalar to every component of the vector and returns the result.
A temporary vector is created during the operation and copied as result.
operator+=() [1/2]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > & tarch::la::operator+= (Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs)
Adds rVector to lVector and assigns the result to lVector.
No temporary vector is created.
operator+=() [2/2]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > & tarch::la::operator+= (Vector< Size, Scalar > & vector, const Scalar & scalar)
Adds every component of the vector to the scalar and assigns the result to the vector.
No temporary objects are created during the operation.
operator-() [1/3]
template<int Rows, int Cols, typename Scalar > Matrix< Rows, Cols, Scalar > tarch::la::operator- (const Matrix< Rows, Cols, Scalar > & lhs, const Matrix< Rows, Cols, Scalar > & rhs)
operator-() [2/3]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > tarch::la::operator- (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs)
Subtracts rVector from lVector.
A temporary vector is created and copied to store return back the result.
operator-() [3/3]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > tarch::la::operator- (const Vector< Size, Scalar > & vector, const Scalar & scalar)
Subtracts the scalar from every component of the vector and returns the result.
A temporary vector is created during the operation and copied as result.
operator-=() [1/2]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > & tarch::la::operator-= (Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs)
Subtracts rVector from lVector and assigns the result to lVector.
No temporary vector is created.
operator-=() [2/2]
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > & tarch::la::operator-= (Vector< Size, Scalar > & vector, const Scalar & scalar)
Subtracts the scalar from every component of the vector and assigns the result to the vector.
No temporary objects are created during the operation.
operator/()
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > tarch::la::operator/ (const Vector< Size, Scalar > & vector, const Scalar & scalar)
Divides every component of the vector by the scalar and returns the result.
A temporary vector is created during the operation and copied as result.
operator/=()
template<int Size, typename Scalar > GPUCallableMethod Vector< Size, Scalar > & tarch::la::operator/= (Vector< Size, Scalar > & vector, const Scalar & scalar)
Divides every component of the vector by the scalar and assigns the result to the vector.
No temporary objects are created during the operation.
operator==() [1/2]
template<int Rows, int Cols, typename Scalar > bool tarch::la::operator== (const Matrix< Rows, Cols, Scalar > & lhs, const Matrix< Rows, Cols, Scalar > & rhs)
Bitwise comparison of the components of two matrices on equality.
Definition at line 84 of file MatrixMatrixOperations.cpph.
operator==() [2/2]
template<int Size, typename Scalar > bool tarch::la::operator== (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs)
Bit-wise comparison of the components of two vectors for equality.
This method should not be used for floating-point valued vectors. Instead, equals() is the suitable comparison.
Definition at line 323 of file VectorVectorOperations.cpph.
outerDot()
template<int Size, typename Scalar > Matrix< Size, Size, Scalar > tarch::la::outerDot (const Vector< Size, Scalar > & lhs, const Vector< Size, Scalar > & rhs)
Outer dot product.
pow()
double tarch::la::pow (double base, double exponent)
Wrapper around std::pow which is redirected to Intel's implementation on Intel machines.
Definition at line 23 of file Scalar.cpp.
real()
template<int Size> Vector< Size, double > tarch::la::real (const Vector< Size, std::complex< double > > & vector)
relativeEps()
double tarch::la::relativeEps (double valueA, double valueB = std::numeric_limits<double>::min(), double eps = NUMERICAL_ZERO_DIFFERENCE)
Determine a relative tolerance from one or two values.
This routine takes eps and scales it with the maximum of the absolute values of the arguments.
The version with two arguments can be seen as wrapper around a 'scalar' relativeEps() variant which forwards the bigger value. This is very often used in combination with the greater and smaller macros, where you wanna compare prescribing a comparison tolerance.
If you have only one argument, set valueB=valueA.
Definition at line 14 of file Scalar.cpp.
References std::abs().
Referenced by peano4::grid::internal::twoEventsAreAdjacent().
relativeEpsNormaledAgainstValueGreaterOne()
double tarch::la::relativeEpsNormaledAgainstValueGreaterOne (double valueA, double valueB = std::numeric_limits<double>::min(), double eps = NUMERICAL_ZERO_DIFFERENCE)
Determine a relative tolerance from one or two values.
This routine takes NUMERICAL_ZERO_DIFFERENCE or any other quantity and scales it with value if value is bigger than one. If it falls below one, then it returns the original eps.
The version with two arguments can be seen as wrapper around a 'scalar' relativeEps() variant which forwards the bigger value. This is very often used in combination with the greater and smaller macros, where you wanna compare prescribing a comparison tolerance.
If you have only one argument, set valueB=valueA.
Definition at line 10 of file Scalar.cpp.
References std::abs().
Referenced by tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::PeanoTextPatchFileWriter(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VTKBinaryFileWriter(), tarch::plotter::griddata::unstructured::vtk::VTKTextFileWriter::VTKTextFileWriter(), and tarch::plotter::griddata::unstructured::vtk::VTUTextFileWriter::VTUTextFileWriter().
remainder()
template<int Size, typename Scalar > Vector< Size, Scalar > tarch::la::remainder (const Vector< Size, Scalar > & vector, double h)
Return the remainder of a division.
Per component x_i, the function computes x_i/h and then returns the remaining fraction of x_i which did not fit into h. The function therefore resembles modulo.
Referenced by toolbox::particles::createParticlesAlignedWithGlobalCartesianMesh().
round() [1/2]
GPUCallableMethod int tarch::la::round (double value)
Definition at line 93 of file ScalarOperations.cpph.
round() [2/2]
GPUCallableMethod int tarch::la::round (float value)
Definition at line 98 of file ScalarOperations.cpph.
row()
template<int Rows, int Cols, typename Scalar > Vector< Cols, Scalar > tarch::la::row (const Matrix< Rows, Cols, Scalar > & matrix, int whichRow)
Extract row from matrix.
Referenced by tarch::la::DynamicMatrix::insertEmptyColumns(), tarch::la::DynamicMatrix::insertEmptyRows(), tarch::la::DynamicMatrix::multiply(), tarch::la::DynamicMatrix::multiplyBySmallMatrix(), tarch::la::DynamicMatrix::operator()(), tarch::la::DynamicMatrix::operator()(), operator*(), tarch::la::DynamicMatrix::operator==(), tarch::la::DynamicMatrix::operator==(), tarch::la::DynamicMatrix::removeColumn(), tarch::la::DynamicMatrix::replicateCols(), tarch::la::DynamicMatrix::scale(), tarch::la::DynamicMatrix::serialise(), tarch::la::DynamicMatrix::serialise(), tarch::la::DynamicMatrix::shiftColumnsRight(), tarch::la::DynamicMatrix::shiftRowsDown(), and tarch::la::DynamicMatrix::toString().
sign()
GPUCallableMethod int tarch::la::sign (double value, double tolerance = NUMERICAL_ZERO_DIFFERENCE)
Returns
-10, or 1 depending on the sign of value
Definition at line 83 of file ScalarOperations.cpph.
References greater().
slice() [1/2]
template<int SizeLhs, int SizeRhs, typename Scalar > Vector< SizeLhs, Scalar > tarch::la::slice (const Vector< SizeRhs, Scalar > & vector, int fromIndex, int stride = 1)
Returns subpart of the vector.
The name is due to historical reasons and compability with Bernhard Gatzhammer's PreCiSE code. But the implementation is extended such that one can also retrieve discontinuous parts of a vector.
!!! Examples
Take first 3 element from a vector:
tarch::la::slice<3>(myVector,0)
Take the elements 2,3,5,6 from a vector:
tarch::la::slice<3>(myVector,2,2)
Referenced by tarch::la::tests::VectorTest::testWrappedVector().
slice() [2/2]
template<int SizeLhs, int SizeRhs, typename Scalar > void tarch::la::slice (Vector< SizeLhs, Scalar > & toVector, const Vector< SizeRhs, Scalar > & fromVector, int fromIndexInToVector, int strideInToVector = 1)
Setter.
Definition at line 20 of file VectorSlice.cpph.
References assertion6, and toString().
smaller()
GPUCallableMethod bool tarch::la::smaller (double lhs, double rhs, double tolerance = NUMERICAL_ZERO_DIFFERENCE)
Parameters
tolerance Absolute tolerance when we compare two values.
Definition at line 47 of file ScalarOperations.cpph.
Referenced by allSmaller(), allSmaller(), toolbox::particles::applyPeriodicBoundaryConditions(), backSubstitution(), toolbox::particles::createParticlesAlignedWithGlobalCartesianMesh(), swift2::kernels::legacy::densityKernelEvaluatePairInteractionPredicate(), swift2::kernels::legacy::force_kernel(), exahype2::getMinTimeStampOfNeighboursAhead(), tarch::timing::Measurement::getStandardDeviation(), tarch::timing::Measurement::getValue(), toolbox::particles::insertParticleIntoCell(), oneSmaller(), tarch::plotter::PVDTimeSeriesWriter::parseFile(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::PeanoTextPatchFileWriter(), peano4::grid::internal::sort(), benchmarks::exahype2::ccz4::CCZ4SBH_FD4::startTimeStep(), tarch::la::tests::ScalarTest::testComparison(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VTKBinaryFileWriter(), tarch::plotter::griddata::unstructured::vtk::VTKTextFileWriter::VTKTextFileWriter(), and tarch::plotter::griddata::unstructured::vtk::VTUTextFileWriter::VTUTextFileWriter().
smallerEquals()
GPUCallableMethod bool tarch::la::smallerEquals (double lhs, double rhs, double tolerance = NUMERICAL_ZERO_DIFFERENCE)
Parameters
tolerance Absolute tolerance when we compare two values.
Definition at line 56 of file ScalarOperations.cpph.
Referenced by allSmallerEquals(), allSmallerEquals(), toolbox::particles::createEquallySpacedParticles(), exahype2::getInterpolationWeights(), toolbox::particles::getParticleReassociationInstructionWithinCellWithIntraCellReassignment(), toolbox::particles::FileReader::getParticlesWithinVoxel(), toolbox::particles::FileReaderHDF5::getParticlesWithinVoxel(), swift2::boundaryconditions::getUpdateDueToFixedBoundaryCondition(), toolbox::particles::insertParticleIntoCell(), toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_linear(), peano4::datamanagement::CellMarker::isContained(), peano4::datamanagement::VertexMarker::isContainedInAdjacentCells(), peano4::datamanagement::VertexMarker::isContainedInAdjacentCellsByDimension(), toolbox::particles::mirrorParticleAlongPeriodicDomains(), oneSmallerEquals(), peano4::datamanagement::CellMarker::overlaps(), exahype2::fv::internal::projectValueOntoParticle_piecewiseLinear(), tarch::timing::Measurement::setValue(), tarch::la::tests::ScalarTest::testComparison(), peano4::grid::internal::twoEventsAreAdjacent(), and tarch::logging::Statistics::writeToCSV().
sum() [1/2]
template<int Rows, int Cols, typename Scalar > Scalar tarch::la::sum (const Matrix< Rows, Cols, Scalar > & matrix)
Computes the sum of all entries of the matrix.
Definition at line 101 of file MatrixOperations.cpph.
Referenced by tarch::la::tests::VectorTest::testVectorOperations().
sum() [2/2]
template<int Size, typename Scalar > Scalar tarch::la::sum (const Vector< Size, Scalar > & vector)
Sums up the component values of the vector.
Definition at line 166 of file VectorOperations.cpph.
toSTLVector()
template<int Size, typename Scalar > std::vector< Scalar > tarch::la::toSTLVector (const Vector< Size, Scalar > & vector)
Definition at line 2 of file VectorOperations.cpph.
transpose() [1/2]
tarch::la::DynamicMatrix tarch::la::transpose (const DynamicMatrix & matrix)
Definition at line 3 of file DynamicMatrixOperations.cpp.
References tarch::la::DynamicMatrix::cols(), and tarch::la::DynamicMatrix::rows().
Referenced by toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_secondOrder(), toolbox::blockstructured::interpolateHaloLayer_AoS_second_order(), toolbox::blockstructured::interpolateHaloLayer_AoS_third_order(), toolbox::blockstructured::restrictInnerHalfOfHaloLayer_AoS_second_order(), toolbox::blockstructured::restrictInnerHalfOfHaloLayer_AoS_third_order(), tarch::la::tests::GramSchmidtTest::testModifiedGramSchmidt(), and tarch::la::tests::MatrixTest::testTransposedMatrix().
transpose() [2/2]
template<int Rows, int Cols, typename Scalar > Matrix< Cols, Rows, Scalar > tarch::la::transpose (const Matrix< Rows, Cols, Scalar > & matrix)
volume()
template<int Size, typename Scalar > Scalar tarch::la::volume (const Vector< Size, Scalar > & vector)
Computes the volume of the tetrahedron spanned by the Cartesian unit vectors scaled by the corresponding components of the given vector.
Definition at line 175 of file VectorOperations.cpph.
Referenced by exahype2::dg::cellIntegral_patchwise_in_situ_GaussLegendre(), exahype2::dg::cellIntegral_patchwise_in_situ_GaussLegendre_functors(), toolbox::finiteelements::getPoissonMatrixWithJumpingCoefficient(), peano4::grid::internal::sort(), peano4::grid::internal::twoEventsAreAdjacent(), mghype::matrixfree::solvers::SolverStatistics::updateGlobalResidual(), and mghype::matrixfree::solvers::SolverStatistics::updateGlobalSolutionUpdates().
Variable Documentation
E
constexpr double tarch::la::E = 2.7182818284590452353602874713526624977572 constexpr
Definition at line 13 of file Scalar.h.
NUMERICAL_ZERO_DIFFERENCE
constexpr double tarch::la::NUMERICAL_ZERO_DIFFERENCE = 1.0e-8 constexpr
Definition at line 17 of file Scalar.h.
Referenced by toolbox::particles::dropParticle(), swift2::kernels::legacy::forceKernelEvaluatePairInteractionPredicate(), toolbox::particles::getAdjacentCellsOwningParticle(), tarch::timing::GlidingAverageMeasurement::getStandardDeviation(), toolbox::particles::liftParticleAssociatedWithVertex(), swift2::kernels::localParticleCanBeUpdatedInCellKernel(), swift2::kernels::localParticleCanBeUpdatedInCellKernelFromAnyOtherParticle(), swift2::kernels::localParticleCanBeUpdatedInCellKernelFromAnyOtherParticleWithinIterationRange(), swift2::markAllParticlesAsUpdatedWithinCell(), toolbox::particles::relativeSpatialOwnershipTolerance(), exahype2::removeTimeStepAccumulationErrorsFromCell(), toolbox::particles::sieveParticle(), toolbox::particles::tests::MultiscaleTransitionsTest::testLiftDropOfParticleAssociatedWithVertex03(), toolbox::particles::tests::MultiscaleTransitionsTest::testLiftDropOfParticleAssociatedWithVertex04(), and toolbox::particles::updateContainedInAdjacentCellProperty().
PI
constexpr double tarch::la::PI = 3.1415926535897932384626433832795028841972 constexpr
Definition at line 12 of file Scalar.h.
Referenced by tests::multigrid::matrixfree::poisson::getPointWiseRhs(), tutorials::mghype::examples::getPointWiseRhs(), and benchmarks::multigrid::petsc::poisson::DGPoisson::initNode().