Peano
MatrixFreeMain.template.cpp File Reference
#include "{{MAIN_NAME}}.h"
#include "peano4/peano4.h"
#include "peano4/UnitTests.h"
#include "peano4/grid/Spacetree.h"
#include "peano4/parallel/SpacetreeSet.h"
#include "{{SUBDIRECTORY}}observers/CreateGrid.h"
#include "{{SUBDIRECTORY}}observers/InitSolution.h"
#include "{{SUBDIRECTORY}}observers/Solve.h"
#include "{{SUBDIRECTORY}}observers/Plot.h"
#include "{{subdirectory}}repositories/DataRepository.h"
#include "{{subdirectory}}repositories/StepRepository.h"
#include "{{subdirectory}}repositories/SolverRepository.h"
#include "repositories/DataRepository.h"
#include "repositories/StepRepository.h"
#include "repositories/SolverRepository.h"
#include "tarch/UnitTests.h"
#include "tarch/logging/Log.h"
#include "tarch/logging/LogFilter.h"
#include "tarch/logging/LogFilterFileReader.h"
#include "tarch/logging/Statistics.h"
#include "tarch/multicore/Core.h"
#include "tarch/multicore/multicore.h"
#include "tarch/multicore/otter.h"
#include "tarch/tests/TreeTestCaseCollection.h"
#include "tarch/timing/Measurement.h"
#include "tarch/timing/Watch.h"
#include "toolbox/finiteelements/UnitTests.h"
#include <fenv.h>
Functions
bool selectNextAlgorithmicStep ()
void step ()
int main (int argc, char **argv)
Main routine of the SPH code.
Variables
tarch::logging::Log _log ("::")
tarch::timing::Measurement createGridMeasurement
tarch::timing::Measurement initMeasurement
tarch::timing::Measurement solveMeasurement
tarch::timing::Measurement plotMeasurement
Function Documentation
main()
int main (int argc, char ** argv)
Main routine of the SPH code.
Definition at line 270 of file MatrixFreeMain.template.cpp.
References tarch::logging::Statistics::clear(), createGridMeasurement, tarch::timing::Measurement::getAccumulatedValue(), peano4::parallel::Node::getInstance(), tarch::logging::Statistics::getInstance(), tarch::mpi::Rank::getInstance(), peano4::init(), initMeasurement, logInfo, logWarning, OTTER_FINALISE, OTTER_INITIALISE, tarch::logging::LogFilterFileReader::parsePlainTextFile(), plotMeasurement, selectNextAlgorithmicStep(), peano4::shutdown(), solveMeasurement, step(), tarch::timing::Measurement::toString(), and tarch::logging::Statistics::writeToCSV().
selectNextAlgorithmicStep()
bool selectNextAlgorithmicStep ()
Definition at line 58 of file MatrixFreeMain.template.cpp.
References assertionMsg, peano4::parallel::Node::getCurrentProgramStep(), peano4::parallel::SpacetreeSet::getGridStatistics(), peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), peano4::grid::GridStatistics::getStationarySweeps(), logInfo, and peano4::parallel::Node::setNextProgramStep().
Referenced by main().
step()
void step ()
Definition at line 184 of file MatrixFreeMain.template.cpp.
References _log, assertion, createGridMeasurement, peano4::parallel::Node::getCurrentProgramStep(), peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), tarch::logging::LogFilter::getInstance(), tarch::mpi::Rank::getInstance(), initMeasurement, logInfo, plotMeasurement, tarch::timing::Measurement::setValue(), solveMeasurement, tarch::logging::LogFilter::switchProgramPhase(), and peano4::parallel::SpacetreeSet::traverse().
Referenced by swift2::dependencychecks::internal::checkFutureStages(), swift2::dependencychecks::internal::checkPastStages(), and main().
Variable Documentation
_log
tarch::logging::Log _log("::") ("::")
Referenced by swift2::kernels::adoptInteractionRadiusAndTriggerRerun(), exahype2::fd::applyBoundaryConditions(), exahype2::dg::applyBoundaryConditions(), exahype2::fv::applyBoundaryConditions(), exahype2::fd::applySommerfeldConditions(), toolbox::particles::createParticlesAlignedWithGlobalCartesianMesh(), exahype2::discretiseAndTruncateTimeStepSizes(), exahype2::getInterpolationWeights(), tarch::getMemoryUsage(), swift2::boundaryconditions::getUpdateDueToFixedBoundaryCondition(), tarch::hasNonCriticalAssertionBeenViolated(), swift2::kernels::legacy::hydro_end_force(), swift2::kernels::legacy::hydro_prepare_force(), swift2::kernels::legacy::hydro_update_smoothing_length_and_rerun_if_required(), benchmarks::swift2::hydro::kernel_throughput::initNohProblemIC(), toolbox::particles::insertParticleIntoCell(), toolbox::particles::particleIsDuplicate(), exahype2::fv::internal::projectValueOntoParticle_piecewiseLinear(), exahype2::fd::fd4::reconstruct_first_derivatives(), exahype2::removeTimeStepAccumulationErrorsFromCell(), swift2::statistics::reportSearchRadiusVTDt(), swift2::dastgenTest::reportStep(), variant1::runBenchmarks(), variant2::runBenchmarks(), variant3::runBenchmarks(), variant4::runBenchmarks(), variant5::runBenchmarks(), variant6::runBenchmarks(), step(), exahype2::fd::fd4::timeStep_patchwise_heap_functors(), exahype2::fv::musclhancock::timeStepWithMusclHancock_patchwise_heap_functors(), tarch::triggerNonCriticalAssertion(), and exahype2::fv::validatePatch().
createGridMeasurement
tarch::timing::Measurement createGridMeasurement
Definition at line 48 of file MatrixFreeMain.template.cpp.
Referenced by main(), and step().
initMeasurement
tarch::timing::Measurement initMeasurement
Definition at line 49 of file MatrixFreeMain.template.cpp.
Referenced by main(), and step().
plotMeasurement
tarch::timing::Measurement plotMeasurement
Definition at line 51 of file MatrixFreeMain.template.cpp.
Referenced by main(), and step().
solveMeasurement
tarch::timing::Measurement solveMeasurement
Definition at line 50 of file MatrixFreeMain.template.cpp.
Referenced by main(), and step().