Peano
Index Class Reference
#include <index.h>
Static Public Member Functions
static std::vector< int > getIndexRange (int start, int size)
static std::vector< double > getRange (int start, int size, double dx, double ox=0)
Detailed Description
Definition at line 9 of file index.h.
Member Function Documentation
getIndexRange()
static std::vector< int > Index::getIndexRange (int start, int size) static
Definition at line 11 of file index.h.
Referenced by getRange(), and Interpolation::Lagrange::interpolate1D().
getRange()
static std::vector< double > Index::getRange (int start, int size, double dx, double ox = 0) static
Definition at line 20 of file index.h.
References dx, and getIndexRange().
Referenced by Edge::Edge(), Edge::remesh(), and Edge::split().
The documentation for this class was generated from the following file:
src/toolbox/curvi/index.h