Peano
TaskNumber.h File Reference
#include <functional>
#include <set>
#include <string>
#include <vector>
#include "tarch/multicore/Task.h"
#include "peano4/datamanagement/VertexEnumerator.h"
#include "peano4/datamanagement/VertexMarker.h"
#include "TaskNumber.cpph"
Data Structures
struct swift2::TaskNumber
Task Number.
Namespaces
namespace swift2
This file is part of the SWIFT 2 project.
Typedefs
using swift2::PendingDependencies = std::set<std::pair<::swift2::TaskNumber, ::swift2::TaskNumber>>
Pending dependencies container.
Functions
std::string swift2::toString (const std::set< TaskNumber > &numbers)
std::string swift2::toString (const TaskNumber numbers[TwoPowerD])
int swift2::flatten (const TaskNumber &numbers)
Alias around method flatten().
std::set< int > swift2::flatten (const std::set< TaskNumber > &numbers)
template<typename Vertex >
std::set<::swift2::TaskNumber > swift2::getVertexNumbersOfParentVertices (const peano4::datamanagement::VertexMarker &marker, peano4::datamanagement::VertexEnumerator< Vertex > coarseGridVertices, ::swift2::TaskNumber::TaskAssociation taskAssociation)
Get numbers of parent vertices.
template<typename Vertex >
std::set<::swift2::TaskNumber > swift2::getVertexNumbersOfParentVertices (tarch::la::Vector< Dimensions, int > position, peano4::datamanagement::VertexEnumerator< Vertex > coarseGridVertices, ::swift2::TaskNumber::TaskAssociation taskAssociation, int dimension)
std::set<::swift2::TaskNumber > swift2::getDependenciesForTask (const ::swift2::TaskNumber &task, PendingDependencies &pendingDependencies)
Extract set of dependencies for given task.
bool operator== (const swift2::TaskNumber &lhs, const swift2::TaskNumber &rhs)
bool operator!= (const swift2::TaskNumber &lhs, const swift2::TaskNumber &rhs)
Function Documentation
operator!=()
bool operator!= (const swift2::TaskNumber & lhs, const swift2::TaskNumber & rhs)
Definition at line 45 of file TaskNumber.cpp.
References swift2::TaskNumber::equals().
operator==()
bool operator== (const swift2::TaskNumber & lhs, const swift2::TaskNumber & rhs)
Definition at line 40 of file TaskNumber.cpp.
References swift2::TaskNumber::equals().
Referenced by tarch::logging::LogFilter::FilterListEntry::operator!=().