var dir_18cbaa6b16df9dabffb87837412a0ada =
[
    [ "CollocatedDLinearDiscretisationWithPointJacobi.Abstract.template.cpp", "dd/d2d/CollocatedDLinearDiscretisationWithPointJacobi_8Abstract_8template_8cpp.html", "dd/d2d/CollocatedDLinearDiscretisationWithPointJacobi_8Abstract_8template_8cpp" ],
    [ "CollocatedDLinearDiscretisationWithPointJacobi.Abstract.template.h", "d1/dfc/CollocatedDLinearDiscretisationWithPointJacobi_8Abstract_8template_8h.html", null ],
    [ "CollocatedDLinearDiscretisationWithPointJacobi.template.cpp", "d9/d7e/CollocatedDLinearDiscretisationWithPointJacobi_8template_8cpp.html", null ],
    [ "CollocatedDLinearDiscretisationWithPointJacobi.template.h", "da/d05/CollocatedDLinearDiscretisationWithPointJacobi_8template_8h.html", null ],
    [ "CollocatedMG.Abstract.template.cpp", "d1/d80/CollocatedMG_8Abstract_8template_8cpp.html", "d1/d80/CollocatedMG_8Abstract_8template_8cpp" ],
    [ "CollocatedMG.Abstract.template.h", "d9/de5/CollocatedMG_8Abstract_8template_8h.html", null ],
    [ "CollocatedMG.template.cpp", "d2/dd3/CollocatedMG_8template_8cpp.html", null ],
    [ "CollocatedMG.template.h", "d7/d26/CollocatedMG_8template_8h.html", null ],
    [ "CollocatedMGSingleThreaded.Abstract.template.cpp", "d4/df1/CollocatedMGSingleThreaded_8Abstract_8template_8cpp.html", "d4/df1/CollocatedMGSingleThreaded_8Abstract_8template_8cpp" ],
    [ "CollocatedMGSingleThreaded.Abstract.template.h", "db/d65/CollocatedMGSingleThreaded_8Abstract_8template_8h.html", null ],
    [ "CollocatedMGSingleThreaded.template.cpp", "d6/d78/CollocatedMGSingleThreaded_8template_8cpp.html", null ],
    [ "CollocatedMGSingleThreaded.template.h", "df/d04/CollocatedMGSingleThreaded_8template_8h.html", null ],
    [ "ContinuousGalerkinDiscretisationGaussLobattoWithBlockJacobi.Abstract.template.cpp", "d8/d43/ContinuousGalerkinDiscretisationGaussLobattoWithBlockJacobi_8Abstract_8template_8cpp.html", "d8/d43/ContinuousGalerkinDiscretisationGaussLobattoWithBlockJacobi_8Abstract_8template_8cpp" ],
    [ "ContinuousGalerkinDiscretisationGaussLobattoWithBlockJacobi.Abstract.template.h", "d0/d7b/ContinuousGalerkinDiscretisationGaussLobattoWithBlockJacobi_8Abstract_8template_8h.html", null ],
    [ "ContinuousGalerkinDiscretisationGaussLobattoWithBlockJacobi.template.cpp", "dc/dc0/ContinuousGalerkinDiscretisationGaussLobattoWithBlockJacobi_8template_8cpp.html", null ],
    [ "ContinuousGalerkinDiscretisationGaussLobattoWithBlockJacobi.template.h", "d6/d08/ContinuousGalerkinDiscretisationGaussLobattoWithBlockJacobi_8template_8h.html", null ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver.Abstract.generic.template.cpp", "d8/d8f/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_8Abstract_8generic_8template_8cpp.html", "d8/d8f/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_8Abstract_8generic_8template_8cpp" ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver.Abstract.generic.template.h", "db/d4a/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_8Abstract_8generic_8template_8h.html", null ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver.Abstract.template.cpp", "d6/d5e/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_8Abstract_8template_8cpp.html", null ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver.Abstract.template.h", "d1/d30/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_8Abstract_8template_8h.html", "d1/d30/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_8Abstract_8template_8h" ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver.template.cpp", "d0/df1/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_8template_8cpp.html", null ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver.template.h", "d6/d7e/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_8template_8h.html", null ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_Tasks.Abstract.template.cpp", "d8/dbd/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver__Tasks_8Abstract_8template_8cpp.html", null ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_Tasks.Abstract.template.h", "d2/d18/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver__Tasks_8Abstract_8template_8h.html", null ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_Tasks.template.cpp", "d3/d8e/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver__Tasks_8template_8cpp.html", null ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_Tasks.template.h", "d3/d4a/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver__Tasks_8template_8h.html", null ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_Unshifted.Abstract.template.cpp", "df/d9f/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver__Unshifted_8Abstract_8template_8cpp.html", null ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_Unshifted.Abstract.template.h", "d7/d6e/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver__Unshifted_8Abstract_8template_8h.html", "d7/d6e/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver__Unshifted_8Abstract_8template_8h" ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_Unshifted.template.cpp", "d0/d02/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver__Unshifted_8template_8cpp.html", null ],
    [ "DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver_Unshifted.template.h", "d0/d77/DiscontinuousGalerkinDiscretisationPointWiseRiemannSolver__Unshifted_8template_8h.html", null ]
];