var dir_463c02a3bfb450a7124731a555175db3 =
[
    [ "__init__.py", "d0/d89/python_2exahype2_2solvers_2aderdg_2kernels_2____init_____8py.html", null ],
    [ "AMRRoutines.py", "d8/d3e/AMRRoutines_8py.html", "d8/d3e/AMRRoutines_8py" ],
    [ "AMRRoutines.template.cpp", "d2/d0f/AMRRoutines_8template_8cpp.html", null ],
    [ "AMRRoutines.template.h", "d0/d11/AMRRoutines_8template_8h.html", null ],
    [ "BufferSizes.py", "d8/da8/BufferSizes_8py.html", "d8/da8/BufferSizes_8py" ],
    [ "BufferSizes.template.h", "d2/dc3/BufferSizes_8template_8h.html", null ],
    [ "CellErrorIntegral.template.cpp", "d6/dcf/CellErrorIntegral_8template_8cpp.html", null ],
    [ "CellErrorIntegral.template.h", "d6/de1/CellErrorIntegral_8template_8h.html", null ],
    [ "DGMatrices.py", "de/db7/DGMatrices_8py.html", "de/db7/DGMatrices_8py" ],
    [ "DGMatrices.template.cpp", "db/d76/DGMatrices_8template_8cpp.html", null ],
    [ "DGMatrices.template.h", "db/d97/DGMatrices_8template_8h.html", null ],
    [ "FaceIntegral.template.cpp", "d9/d4d/FaceIntegral_8template_8cpp.html", "d9/d4d/FaceIntegral_8template_8cpp" ],
    [ "FaceIntegral.template.h", "d9/d99/FaceIntegral_8template_8h.html", null ],
    [ "FusedSpaceTimePredictorVolumeIntegral.py", "d3/dab/FusedSpaceTimePredictorVolumeIntegral_8py.html", "d3/dab/FusedSpaceTimePredictorVolumeIntegral_8py" ],
    [ "FusedSpaceTimePredictorVolumeIntegral.template.h", "df/de1/FusedSpaceTimePredictorVolumeIntegral_8template_8h.html", null ],
    [ "FusedSpaceTimePredictorVolumeIntegralLinear.template.cpp", "d9/d29/FusedSpaceTimePredictorVolumeIntegralLinear_8template_8cpp.html", null ],
    [ "FusedSpaceTimePredictorVolumeIntegralNonlinear.template.cpp", "d7/d47/FusedSpaceTimePredictorVolumeIntegralNonlinear_8template_8cpp.html", null ],
    [ "Gemms.py", "df/d16/Gemms_8py.html", "df/d16/Gemms_8py" ],
    [ "Gemms.template.cpp", "da/d13/aderdg_2kernels_2Gemms_8template_8cpp.html", null ],
    [ "Gemms.template.h", "d6/dec/aderdg_2kernels_2Gemms_8template_8h.html", null ],
    [ "MaxScaledEigenvalue.template.cpp", "de/df2/MaxScaledEigenvalue_8template_8cpp.html", null ],
    [ "MaxScaledEigenvalue.template.h", "d7/d7b/MaxScaledEigenvalue_8template_8h.html", null ],
    [ "PointSources.template.cpp", "d6/d09/PointSources_8template_8cpp.html", null ],
    [ "PointSources.template.h", "d0/d01/PointSources_8template_8h.html", null ],
    [ "Quadrature.py", "db/df1/aderdg_2kernels_2Quadrature_8py.html", "db/df1/aderdg_2kernels_2Quadrature_8py" ],
    [ "Quadrature.template.cpp", "d5/d22/aderdg_2kernels_2Quadrature_8template_8cpp.html", null ],
    [ "Quadrature.template.h", "d0/d35/aderdg_2kernels_2Quadrature_8template_8h.html", null ],
    [ "RiemannSolver.template.h", "d2/dad/aderdg_2kernels_2RiemannSolver_8template_8h.html", null ],
    [ "RiemannSolverLinear.template.cpp", "d9/dff/RiemannSolverLinear_8template_8cpp.html", "d9/dff/RiemannSolverLinear_8template_8cpp" ],
    [ "RiemannSolverNonlinear.template.cpp", "d8/d9f/RiemannSolverNonlinear_8template_8cpp.html", "d8/d9f/RiemannSolverNonlinear_8template_8cpp" ]
];