Peano
RefinementControl.h File Reference
#include "peano4/grid/GridControlEvent.h"
#include "tarch/multicore/BooleanSemaphore.h"
#include <list>
#include <vector>
Data Structures
class exahype2::RefinementControl
Manage refine/erase requests within ExaHyPE 2.
Namespaces
namespace exahype2
For the generic kernels that I use here most of the time.
Enumerations
enum class exahype2::RefinementCommand { exahype2::Keep , exahype2::Refine , exahype2::Erase }
Functions
RefinementCommand exahype2::getDefaultRefinementCommand ()
The default is coarsen as this is the lowest priority command.
exahype2::RefinementCommand operator&& (exahype2::RefinementCommand lhs, exahype2::RefinementCommand rhs)
If one of the flags says refine, then refine.
std::string toString (exahype2::RefinementCommand value)
Function Documentation
operator&&()
exahype2::RefinementCommand operator&& (exahype2::RefinementCommand lhs, exahype2::RefinementCommand rhs)
If one of the flags says refine, then refine.
If one of the two flags says keep and noone says refine, return keep. Coarsen if and only if both say coarsen.
Definition at line 11 of file RefinementControl.cpp.
References exahype2::Erase, exahype2::Keep, and exahype2::Refine.
toString()
std::string toString (exahype2::RefinementCommand value)
Definition at line 21 of file RefinementControl.cpp.
References exahype2::Erase, exahype2::Keep, and exahype2::Refine.
Referenced by exahype2::RefinementControl::addCommand(), tarch::accelerator::allocateRawData(), peano4::stacks::STDVectorStackOverObjectsWithSmartPointers< T >::clone(), peano4::stacks::STDVectorStackOverSmartPointers< T >::clone(), toolbox::particles::SieveParticles< T >::cloneParticlesToBeSieved(), tarch::accelerator::copyFrom(), tarch::accelerator::copyTo(), toolbox::particles::ensureAllParticleListsAreGatheredOrEmpty(), peano4::stacks::STDVectorStackOverSmartPointers< T >::gather(), peano4::parallel::Node::getGridDataExchangeMetaInformation(), peano4::datamanagement::CellMarker::getInvokingParentCellsCentre(), peano4::datamanagement::VertexMarker::getInvokingParentCellsCentre(), peano4::datamanagement::VertexMarker::getNumberOfAdjacentTrees(), peano4::datamanagement::FaceMarker::getRelativePositionWithinFatherCell(), peano4::datamanagement::FaceMarker::getRelativePositionWithinFatherCell(), peano4::datamanagement::VertexMarker::isAdjacentToParallelDomainBoundary(), exahype2::enumerator::FaceAoSLexicographicEnumerator::operator()(), operator<<(), peano4::stacks::STDVectorOverContainerOfPointers< T >::prepareMetaDataToSendOut(), tarch::accelerator::reallocateRawData(), mghype::matrixfree::solvers::cgmultigrid::restrictToNextLevel(), runParallel(), runParallel(), peano4::datamanagement::VertexMarker::select(), selectNextAlgorithmicStep(), tarch::la::slice(), peano4::stacks::STDVectorStackOverSmartPointers< T >::startReceive(), peano4::parallel::tests::PingPongTest::testDaStGenArray(), peano4::SplitInstruction::toString(), peano4::stacks::STDVectorStackOverObjectsWithSmartPointers< T >::toString(), peano4::stacks::STDVectorStackOverSmartPointers< T >::toString(), toolbox::particles::assignmentchecks::internal::ParticleIdentifier::toString(), peano4::stacks::STDVectorOverContainerOfPointers< T >::tryToFinishSendOrReceive(), peano4::stacks::STDVectorStackOverObjectsWithSmartPointers< T >::tryToFinishSendOrReceive(), peano4::stacks::STDVectorStackOverSmartPointers< T >::tryToFinishSendOrReceive(), toolbox::loadbalancing::LoadBalancer::update(), mghype::matrixfree::solvers::dgcgcoupling::updateRestrictionCounters(), and peano4::stacks::STDVectorOverContainerOfPointers< T >::workInReceivedMetaData().