var namespaceexahype2_1_1solvers_1_1aderdg_1_1actionsets_1_1AdaptivityCriterion =
[
    [ "AdaptivityCriterion", "d7/dac/classexahype2_1_1solvers_1_1aderdg_1_1actionsets_1_1AdaptivityCriterion_1_1AdaptivityCriterion.html", "d7/dac/classexahype2_1_1solvers_1_1aderdg_1_1actionsets_1_1AdaptivityCriterion_1_1AdaptivityCriterion" ]
];