Peano
petscReader Namespace Reference
Functions
getMatDimensions (fName)
readUntil (line, character, index=0)
getFirstColNumberAndEntryFromLine (line)
convertLineToVector (line, dim)
populateMatrix (fName)
populateRHS (fName, solDim=None)
getRankOfMatrix (mat)
Variables
dim = getMatDimensions("mat.xml")
mat = populateMatrix("mat.xml")
rhs = populateRHS("rhs.xml")
int numCells = 27 * 27
int solDim = 4 * numCells
sol = populateRHS("solution.xml")
Function Documentation
convertLineToVector()
petscReader.convertLineToVector (line, dim)
Definition at line 39 of file petscReader.py.
References getFirstColNumberAndEntryFromLine(), and readUntil().
Referenced by populateMatrix().
getFirstColNumberAndEntryFromLine()
petscReader.getFirstColNumberAndEntryFromLine (line)
Definition at line 22 of file petscReader.py.
References int, and readUntil().
Referenced by convertLineToVector().
getMatDimensions()
petscReader.getMatDimensions (fName)
Definition at line 4 of file petscReader.py.
Referenced by populateMatrix(), and populateRHS().
getRankOfMatrix()
petscReader.getRankOfMatrix (mat)
Definition at line 84 of file petscReader.py.
populateMatrix()
petscReader.populateMatrix (fName)
Definition at line 51 of file petscReader.py.
References convertLineToVector(), and getMatDimensions().
populateRHS()
petscReader.populateRHS (fName, solDim = None)
Definition at line 67 of file petscReader.py.
References getMatDimensions().
readUntil()
petscReader.readUntil (line, character, index = 0)
Definition at line 15 of file petscReader.py.
Referenced by convertLineToVector(), and getFirstColNumberAndEntryFromLine().
Variable Documentation
dim
petscReader.dim = getMatDimensions("mat.xml")
Definition at line 91 of file petscReader.py.
mat
petscReader.mat = populateMatrix("mat.xml")
Definition at line 94 of file petscReader.py.
numCells
int petscReader.numCells = 27 * 27
Definition at line 105 of file petscReader.py.
rhs
petscReader.rhs = populateRHS("rhs.xml")
Definition at line 99 of file petscReader.py.
sol
petscReader.sol = populateRHS("solution.xml")
Definition at line 108 of file petscReader.py.
solDim
int petscReader.solDim = 4 * numCells
Definition at line 106 of file petscReader.py.