Peano
exahype2.solvers.aderdg.ErrorMeasurement.ErrorMeasurement Class Reference
Public Member Functions
__init__ (self, solver, error_measurement_implementation=PDETerms.User_Defined_Implementation, delta_between_database_flushes=0, output_file_name="ADERDGErrorMeasurement", data_delta_between_snapshots="1e+16", time_delta_between_snapshots=0.0, clear_database_after_flush=True)
Detailed Description
Definition at line 16 of file ErrorMeasurement.py.
Constructor & Destructor Documentation
__init__()
exahype2.solvers.aderdg.ErrorMeasurement.ErrorMeasurement.__init__ (self, solver, error_measurement_implementation = PDETerms.User_Defined_Implementation, delta_between_database_flushes = 0, output_file_name = "ADERDGErrorMeasurement", data_delta_between_snapshots = "1e+16", time_delta_between_snapshots = 0.0, clear_database_after_flush = True)
Reimplemented from exahype2.solvers.ErrorMeasurement.ErrorMeasurement.
Definition at line 17 of file ErrorMeasurement.py.
References exahype2.solvers.aderdg.ErrorMeasurement.ErrorMeasurement.__init__(), exahype2.solvers.aderdg.ErrorMeasurement.create_postprocessing_kernel_for_error_measurement_for_adaptive_timestepping(), and exahype2.solvers.aderdg.ErrorMeasurement.create_postprocessing_kernel_for_error_measurement_for_fixed_timestepping().
Referenced by exahype2.solvers.aderdg.ErrorMeasurement.ErrorMeasurement.__init__().
The documentation for this class was generated from the following file:
python/exahype2/solvers/aderdg/ErrorMeasurement.py