Peano
tarch::accelerator::MemoryManager Class Reference
Singleton that manages persistent memory on different accelerators.
#include <MemoryManager.h>
Data Structures
struct MemoryPages
Public Member Functions
MemoryManager (const MemoryManager &copy)=delete
virtual ~MemoryManager ()
Invoke clear().
void * allocate (std::size_t sizeInBytes, MemoryLocation location, int device)
Return a pointer to a new memory block of size bytes on device.
template<class T >
T * allocate (std::size_t count, MemoryLocation location, int device=Device::DefaultDevice)
void free (void *pointer, int device=Device::DefaultDevice)
Free does not actually free data, but instead hands the memory block back to the singleton, such that the next allocate() call can reuse the memory region.
void clear ()
Idempotent function.
const std::map< int, MemoryPages > & getMemoryPages () const
int getNumberOfFreePages () const
int getNumberOfUsedPages () const
int getNumberOfFreePages (int device) const
int getNumberOfUsedPages (int device) const
int getFreeAllocatedMemory (MemoryUsageFormat format) const
int getUsedAllocatedMemory (MemoryUsageFormat format) const
int getFreeAllocatedMemory (MemoryUsageFormat format, int device) const
int getUsedAllocatedMemory (MemoryUsageFormat format, int device) const
std::size_t getFreeAllocatedMemoryInBytes () const
std::size_t getUsedAllocatedMemoryInBytes () const
std::size_t getFreeAllocatedMemoryInBytes (int device) const
std::size_t getUsedAllocatedMemoryInBytes (int device) const
Static Public Member Functions
static MemoryManager & getInstance ()
static std::string getStatistics ()
Private Types
typedef std::map< std::size_t, std::vector< std::pair< void *, MemoryLocation > > > FreePages
Map of pages (memory blocks) per size.
typedef std::map< void *, std::pair< std::size_t, MemoryLocation > > UsedPages
Counterpart of FreePages, i.e.
Private Member Functions
MemoryManager ()=default
void clearWithoutLock ()
Private Attributes
tarch::multicore::BooleanSemaphore _semaphore
std::map< int, MemoryPages > _memoryPages
Map from device number onto memory.
Static Private Attributes
static tarch::logging::Log _log
Detailed Description
Singleton that manages persistent memory on different accelerators.
The idea is that this is basically a heap rep for accelerators and that code requiring heap memory does not allocate this memory but instead grabs it from here. As it is not freed afterwards, we avoid overheads that arise from frequent re-allocation.
Definition at line 30 of file MemoryManager.h.
Member Typedef Documentation
FreePages
typedef std::map<std::size_t, std::vector<std::pair<void*, MemoryLocation> > > tarch::accelerator::MemoryManager::FreePages private
Map of pages (memory blocks) per size.
Definition at line 39 of file MemoryManager.h.
UsedPages
typedef std::map<void*, std::pair<std::size_t, MemoryLocation> > tarch::accelerator::MemoryManager::UsedPages private
Counterpart of FreePages, i.e.
map of memory blocks (addresses) onto sizes.
Definition at line 45 of file MemoryManager.h.
Constructor & Destructor Documentation
MemoryManager() [1/2]
tarch::accelerator::MemoryManager::MemoryManager () private default
MemoryManager() [2/2]
tarch::accelerator::MemoryManager::MemoryManager (const MemoryManager & copy) delete
~MemoryManager()
tarch::accelerator::MemoryManager::~MemoryManager () virtual
Invoke clear().
Definition at line 77 of file MemoryManager.cpp.
Member Function Documentation
allocate() [1/2]
template<class T > T * tarch::accelerator::MemoryManager::allocate (std::size_t count, MemoryLocation location, int device = Device::DefaultDevice)
Definition at line 97 of file MemoryManager.h.
References allocate().
allocate() [2/2]
void * tarch::accelerator::MemoryManager::allocate (std::size_t sizeInBytes, MemoryLocation location, int device)
Return a pointer to a new memory block of size bytes on device.
This operation is thread-safe. If tries to recycle data that has been allocated before. If this is not successful, it acquires new data on the device and then hands out this new data.
Before we return the address of the new data, we memorise it as booked data and store the size corresponding to this device. This is important: When we return the data through free(), we have to look up what the underlying size is and bucket sort the pointer for reusage appropriately.
The routine could, in theory, hand out a pointer to a memory block which points to a chunk of memory that is bigger than size. In the context of Peano this would however be stupid: Most Peano codes work with rather regular chunks of data and if we use big chunks to host smaller data footprint, we actually run risk to fragment the device memory.
The routine takes a memory location as input argument where the new memory block shall be placed. Then, it forwards the actual memory allocation to the respective accelerator.
Definition at line 19 of file MemoryManager.cpp.
References tarch::accelerator::allocateRawData(), and assertion.
Referenced by allocate(), exahype2::CellData< inType, outType, NumFaceTypes >::CellData(), exahype2::CellFaceData< inType, outType >::CellFaceData(), exahype2::FaceData< inType, outType >::FaceData(), tarch::accelerator::tests::MemoryManagerTest::testMemoryAllocationsForMultipleDevices(), and tarch::accelerator::tests::MemoryManagerTest::testMemoryAllocationsForOneDevice().
clear()
void tarch::accelerator::MemoryManager::clear ()
Idempotent function.
Run over _memoryPages, i.e. handle device by device. If a device still has used pages, the user code has not properly freed data. We issue an error.
This operation is thread-safe.
Definition at line 104 of file MemoryManager.cpp.
Referenced by peano4.output.Makefile.Makefile::__init__(), tarch::accelerator::tests::MemoryManagerTest::testMemoryAllocationsForMultipleDevices(), and tarch::accelerator::tests::MemoryManagerTest::testMemoryAllocationsForOneDevice().
clearWithoutLock()
void tarch::accelerator::MemoryManager::clearWithoutLock () private
Definition at line 81 of file MemoryManager.cpp.
References tarch::accelerator::freeRawData(), logDebug, and logWarning.
free()
void tarch::accelerator::MemoryManager::free (void * pointer, int device = Device::DefaultDevice)
Free does not actually free data, but instead hands the memory block back to the singleton, such that the next allocate() call can reuse the memory region.
Definition at line 58 of file MemoryManager.cpp.
References assertion.
Referenced by tarch::accelerator::tests::MemoryManagerTest::testMemoryAllocationsForMultipleDevices(), tarch::accelerator::tests::MemoryManagerTest::testMemoryAllocationsForOneDevice(), exahype2::CellData< inType, outType, NumFaceTypes >::~CellData(), exahype2::CellFaceData< inType, outType >::~CellFaceData(), and exahype2::FaceData< inType, outType >::~FaceData().
getFreeAllocatedMemory() [1/2]
int tarch::accelerator::MemoryManager::getFreeAllocatedMemory (MemoryUsageFormat format) const
Definition at line 142 of file MemoryManager.cpp.
References tarch::convertMemorySize().
Referenced by getStatistics().
getFreeAllocatedMemory() [2/2]
int tarch::accelerator::MemoryManager::getFreeAllocatedMemory (MemoryUsageFormat format, int device) const
Definition at line 150 of file MemoryManager.cpp.
References tarch::convertMemorySize().
getFreeAllocatedMemoryInBytes() [1/2]
std::size_t tarch::accelerator::MemoryManager::getFreeAllocatedMemoryInBytes () const
Definition at line 164 of file MemoryManager.cpp.
getFreeAllocatedMemoryInBytes() [2/2]
std::size_t tarch::accelerator::MemoryManager::getFreeAllocatedMemoryInBytes (int device) const
Definition at line 180 of file MemoryManager.cpp.
getInstance()
tarch::accelerator::MemoryManager::getInstance () static
Initial value:
{% if COMPUTE_MAX_EIGENVALUE==True %}
  tarch::copyFrom(
    maxEigenvalue,
    &maxEigenvalueAfterTimeStep,
    1,
    tarch::MemoryLocation::Pinned,
    targetDevice
  )
Definition at line 14 of file MemoryManager.cpp.
Referenced by exahype2::CellData< inType, outType, NumFaceTypes >::CellData(), exahype2::CellFaceData< inType, outType >::CellFaceData(), exahype2::FaceData< inType, outType >::FaceData(), getStatistics(), tarch::accelerator::tests::MemoryManagerTest::testMemoryAllocationsForMultipleDevices(), tarch::accelerator::tests::MemoryManagerTest::testMemoryAllocationsForOneDevice(), exahype2::CellData< inType, outType, NumFaceTypes >::~CellData(), exahype2::CellFaceData< inType, outType >::~CellFaceData(), and exahype2::FaceData< inType, outType >::~FaceData().
getMemoryPages()
const std::map< int, tarch::accelerator::MemoryManager::MemoryPages > & tarch::accelerator::MemoryManager::getMemoryPages () const
Definition at line 110 of file MemoryManager.cpp.
Referenced by getStatistics().
getNumberOfFreePages() [1/2]
int tarch::accelerator::MemoryManager::getNumberOfFreePages () const
Definition at line 114 of file MemoryManager.cpp.
Referenced by getStatistics().
getNumberOfFreePages() [2/2]
int tarch::accelerator::MemoryManager::getNumberOfFreePages (int device) const
Definition at line 130 of file MemoryManager.cpp.
getNumberOfUsedPages() [1/2]
int tarch::accelerator::MemoryManager::getNumberOfUsedPages () const
Definition at line 122 of file MemoryManager.cpp.
Referenced by getStatistics().
getNumberOfUsedPages() [2/2]
int tarch::accelerator::MemoryManager::getNumberOfUsedPages (int device) const
Definition at line 138 of file MemoryManager.cpp.
getStatistics()
std::string tarch::accelerator::MemoryManager::getStatistics () static
Definition at line 196 of file MemoryManager.cpp.
References getFreeAllocatedMemory(), tarch::getFreeMemory(), getInstance(), getMemoryPages(), tarch::getMemoryUsage(), getNumberOfFreePages(), getNumberOfUsedPages(), tarch::getTotalMemory(), getUsedAllocatedMemory(), and tarch::MByte.
Referenced by step().
getUsedAllocatedMemory() [1/2]
int tarch::accelerator::MemoryManager::getUsedAllocatedMemory (MemoryUsageFormat format) const
Definition at line 146 of file MemoryManager.cpp.
References tarch::convertMemorySize().
Referenced by getStatistics().
getUsedAllocatedMemory() [2/2]
int tarch::accelerator::MemoryManager::getUsedAllocatedMemory (MemoryUsageFormat format, int device) const
Definition at line 157 of file MemoryManager.cpp.
References tarch::convertMemorySize().
getUsedAllocatedMemoryInBytes() [1/2]
std::size_t tarch::accelerator::MemoryManager::getUsedAllocatedMemoryInBytes () const
Definition at line 172 of file MemoryManager.cpp.
getUsedAllocatedMemoryInBytes() [2/2]
std::size_t tarch::accelerator::MemoryManager::getUsedAllocatedMemoryInBytes (int device) const
Definition at line 188 of file MemoryManager.cpp.
Field Documentation
_log
tarch::logging::Log tarch::accelerator::MemoryManager::_log static private
Definition at line 32 of file MemoryManager.h.
_memoryPages
std::map<int , MemoryPages> tarch::accelerator::MemoryManager::_memoryPages private
Map from device number onto memory.
Definition at line 55 of file MemoryManager.h.
_semaphore
tarch::multicore::BooleanSemaphore tarch::accelerator::MemoryManager::_semaphore private
Definition at line 34 of file MemoryManager.h.
The documentation for this class was generated from the following files:
src/tarch/accelerator/MemoryManager.h
src/tarch/accelerator/MemoryManager.cpp
python/exahype2/solvers/fv/godunov/kernels/cuda/Loop.template.h
python/exahype2/solvers/fv/godunov/kernels/sycl/Loop.template.h