Peano
tarch::accelerator::Device Class Reference
Device.
#include <Device.h>
Public Member Functions
~Device ()=default
std::map< void *, std::size_t > & getMemoryBlockTable ()
const std::map< void *, std::size_t > & getMemoryBlockTable () const
multicore::BooleanSemaphore & getMemoryBlockSemaphore ()
const multicore::BooleanSemaphore & getMemoryBlockSemaphore () const
bool init ()
void shutdown ()
Shutdown accelerator environment.
bool isInitialised () const
int getNumberOfDevices () const
Return the number of GPUs that are available.
Static Public Member Functions
static Device & getInstance ()
Static Public Attributes
static constexpr int DefaultDevice = 0
Private Member Functions
Device ()=default
void checkForMemoryLeaks ()
Private Attributes
std::map< void *, std::size_t > _memoryBlockTable
multicore::BooleanSemaphore _memoryBlockSemaphore
Static Private Attributes
static tarch::logging::Log _log
Detailed Description
Device.
Any accelerator implementation has to provide a singleton Device. Its full qualified name is tarch::accelerator::Device. If no accelerator variant is switched on, Peano provides a default Device implementation that does nothing.
Author
Tobias Weinzierl
Definition at line 27 of file Device.h.
Constructor & Destructor Documentation
Device()
tarch::accelerator::Device::Device () private default
~Device()
tarch::accelerator::Device::~Device () default
Member Function Documentation
checkForMemoryLeaks()
void tarch::accelerator::Device::checkForMemoryLeaks () private
Definition at line 34 of file Device.cpp.
References logDebug, and logWarning.
getInstance()
tarch::accelerator::Device & tarch::accelerator::Device::getInstance () static
Returns
Singleton instance
Definition at line 13 of file Device.cpp.
Referenced by benchmarks::exahype2::ccz4::MulticoreOrchestration::getNumberOfTasksToHoldBack(), peano4::init(), swift2::parseCommandLineArguments(), peano4::shutdown(), and writeCopyrightMessage().
getMemoryBlockSemaphore() [1/2]
tarch::multicore::BooleanSemaphore & tarch::accelerator::Device::getMemoryBlockSemaphore ()
Definition at line 26 of file Device.cpp.
getMemoryBlockSemaphore() [2/2]
const tarch::multicore::BooleanSemaphore & tarch::accelerator::Device::getMemoryBlockSemaphore () const
Definition at line 30 of file Device.cpp.
getMemoryBlockTable() [1/2]
std::map< void *, std::size_t > & tarch::accelerator::Device::getMemoryBlockTable ()
Definition at line 18 of file Device.cpp.
getMemoryBlockTable() [2/2]
const std::map< void *, std::size_t > & tarch::accelerator::Device::getMemoryBlockTable () const
Definition at line 22 of file Device.cpp.
getNumberOfDevices()
int tarch::accelerator::Device::getNumberOfDevices () const
Return the number of GPUs that are available.
It is then Peano's policy that you access these GPUs with numbers from 0 to N. We work with logical GPU numbers, i.e. they might be mapped onto different numbers internally. How this mapping is realised however is strongly depending on the used accelerator implementation.
Definition at line 65 of file Device.cpp.
init()
bool tarch::accelerator::Device::init ()
Definition at line 53 of file Device.cpp.
Referenced by swift2::parseCommandLineArguments().
isInitialised()
bool tarch::accelerator::Device::isInitialised () const
Returns
Accelerator environment is up and running. Most accelerator implementations work properly with the defaults. They just return true always.
Definition at line 63 of file Device.cpp.
shutdown()
void tarch::accelerator::Device::shutdown ()
Shutdown accelerator environment.
Definition at line 57 of file Device.cpp.
Referenced by peano4::shutdown().
Field Documentation
_log
tarch::logging::Log tarch::accelerator::Device::_log static private
Definition at line 29 of file Device.h.
_memoryBlockSemaphore
multicore::BooleanSemaphore tarch::accelerator::Device::_memoryBlockSemaphore private
Definition at line 32 of file Device.h.
_memoryBlockTable
std::map<void*, std::size_t> tarch::accelerator::Device::_memoryBlockTable private
Definition at line 31 of file Device.h.
DefaultDevice
constexpr int tarch::accelerator::Device::DefaultDevice = 0 static constexpr
Definition at line 40 of file Device.h.
Referenced by runBenchmarks().
The documentation for this class was generated from the following files:
src/tarch/accelerator/Device.h
src/tarch/accelerator/Device.cpp