Peano
swift2::kernels::ompoffloading Namespace Reference
Functions
template<typename ParticleContainer >
void forAllParticles (const peano4::datamanagement::VertexMarker &marker, ParticleContainer &assignedParticles, int numberOfCoalescedAssignedParticles, ParticleUnaryOperatorOnVertex< typename ParticleContainer::DoFType > auto f, UpdateParticleAssignedToVertexPredicate< typename ParticleContainer::DoFType > predicate)
Please consult cousing routine in swift2/kernels/ParticleSetIterators.h for generic docu.
template<typename ParticleContainer >
void forAllParticles (const peano4::datamanagement::CellMarker &marker, ParticleContainer &localParticles, const std::vector< int > &numberOfCoalescedLocalParticlesPerVertex, ParticleUnaryOperatorOnCell< PCParticle< ParticleContainer > > auto f, UpdateParticleAssignedToCellPredicate< PCParticle< ParticleContainer > > predicate)
Please consult cousing routine in swift2/kernels/ParticleSetIterators.h for generic docu.
template<typename LocalParticleContainer , typename ActiveParticleContainer >
void forAllParticlePairs (const swift2::CellMetaData &cellMetaData, LocalParticleContainer &localParticles, ActiveParticleContainer &activeParticles, ParticleBinaryOperator< PCParticle< LocalParticleContainer >, PCParticle< ActiveParticleContainer > > auto f, UpdateParticleAssignedToCellPredicate< PCParticle< LocalParticleContainer > > localParticlePredicate, UpdateParticlePairWithinCellPredicate< PCParticle< LocalParticleContainer > > particlePairPredicate)
Please consult cousing routine in swift2/kernels/ParticleSetIterators.h for generic docu.
Function Documentation
forAllParticlePairs()
template<typename LocalParticleContainer , typename ActiveParticleContainer > void swift2::kernels::ompoffloading::forAllParticlePairs (const swift2::CellMetaData & cellMetaData, LocalParticleContainer & localParticles, ActiveParticleContainer & activeParticles, ParticleBinaryOperator< PCParticle< LocalParticleContainer >, PCParticle< ActiveParticleContainer > > auto f, UpdateParticleAssignedToCellPredicate< PCParticle< LocalParticleContainer > > localParticlePredicate, UpdateParticlePairWithinCellPredicate< PCParticle< LocalParticleContainer > > particlePairPredicate)
Please consult cousing routine in swift2/kernels/ParticleSetIterators.h for generic docu.
Definition at line 55 of file ParticleSetIterators.cpph.
References swift2::kernels::forAllParticlePairs().
Referenced by runBenchmark().
forAllParticles() [1/2]
template<typename ParticleContainer > void swift2::kernels::ompoffloading::forAllParticles (const peano4::datamanagement::CellMarker & marker, ParticleContainer & localParticles, const std::vector< int > & numberOfCoalescedLocalParticlesPerVertex, ParticleUnaryOperatorOnCell< PCParticle< ParticleContainer > > auto f, UpdateParticleAssignedToCellPredicate< PCParticle< ParticleContainer > > predicate)
Please consult cousing routine in swift2/kernels/ParticleSetIterators.h for generic docu.
Definition at line 32 of file ParticleSetIterators.cpph.
References swift2::kernels::forAllParticles().
forAllParticles() [2/2]
template<typename ParticleContainer > void swift2::kernels::ompoffloading::forAllParticles (const peano4::datamanagement::VertexMarker & marker, ParticleContainer & assignedParticles, int numberOfCoalescedAssignedParticles, ParticleUnaryOperatorOnVertex< typename ParticleContainer::DoFType > auto f, UpdateParticleAssignedToVertexPredicate< typename ParticleContainer::DoFType > predicate)
Please consult cousing routine in swift2/kernels/ParticleSetIterators.h for generic docu.
Definition at line 10 of file ParticleSetIterators.cpph.
References swift2::kernels::forAllParticles().
Referenced by runBenchmark().