Peano
tarch::la::tests::GramSchmidtTest Class Reference
Provides tests for types Vector, DynamicVector and all Vector functionality.
#include <GramSchmidtTest.h>
Public Member Functions
GramSchmidtTest ()
Cosntructor.
virtual ~GramSchmidtTest ()
Destructor, empty.
virtual void run () override
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testModifiedGramSchmidt ()
Tests constructors.
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Provides tests for types Vector, DynamicVector and all Vector functionality.
Definition at line 18 of file GramSchmidtTest.h.
Constructor & Destructor Documentation
GramSchmidtTest()
tarch::la::tests::GramSchmidtTest::GramSchmidtTest ()
Cosntructor.
Definition at line 10 of file GramSchmidtTest.cpp.
~GramSchmidtTest()
virtual tarch::la::tests::GramSchmidtTest::~GramSchmidtTest () virtual
Destructor, empty.
Definition at line 36 of file GramSchmidtTest.h.
Member Function Documentation
run()
void tarch::la::tests::GramSchmidtTest::run () override virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 15 of file GramSchmidtTest.cpp.
References testMethod.
testModifiedGramSchmidt()
void tarch::la::tests::GramSchmidtTest::testModifiedGramSchmidt () private
Tests constructors.
Definition at line 20 of file GramSchmidtTest.cpp.
References tarch::la::Matrix< Rows, Cols, Scalar >::cols(), tarch::la::equals(), tarch::la::max(), tarch::la::modifiedGramSchmidt(), tarch::la::multiply(), tarch::la::transpose(), and validate.
The documentation for this class was generated from the following files:
src/tarch/la/tests/GramSchmidtTest.h
src/tarch/la/tests/GramSchmidtTest.cpp