Peano
mghype.api.matrixgenerators.StencilToElement Namespace Reference
Functions
StencilToElement (stencil, dimensions)
convertStencilToElementMatrix3d (stencil)
We return a square matrix with 2**Dimensions rows.
convertStencilToElementMatrix2d (stencil)
This is borrowed from src/toolbox/ElementMatrix.cpp.
dLinearised (vector, max, dimensions)
Function Documentation
convertStencilToElementMatrix2d()
mghype.api.matrixgenerators.StencilToElement.convertStencilToElementMatrix2d (stencil)
This is borrowed from src/toolbox/ElementMatrix.cpp.
In particular toolbox::finiteelements::getElementWiseAssemblyMatrix()
Definition at line 62 of file StencilToElement.py.
References mghype.api.matrixgenerators.StencilToElement.dLinearised(), and int.
Referenced by mghype.api.matrixgenerators.StencilToElement.StencilToElement().
convertStencilToElementMatrix3d()
mghype.api.matrixgenerators.StencilToElement.convertStencilToElementMatrix3d (stencil)
We return a square matrix with 2**Dimensions rows.
Much of this code is identical to 2d version. We could even reuse this for the 2d version with clever indexing, but it the code is much more readable this way.
Definition at line 11 of file StencilToElement.py.
References mghype.api.matrixgenerators.StencilToElement.dLinearised(), and int.
Referenced by mghype.api.matrixgenerators.StencilToElement.StencilToElement().
dLinearised()
mghype.api.matrixgenerators.StencilToElement.dLinearised (vector, max, dimensions)
Definition at line 105 of file StencilToElement.py.
Referenced by mghype.api.matrixgenerators.StencilToElement.convertStencilToElementMatrix2d(), and mghype.api.matrixgenerators.StencilToElement.convertStencilToElementMatrix3d().
StencilToElement()
mghype.api.matrixgenerators.StencilToElement.StencilToElement (stencil, dimensions)
Definition at line 3 of file StencilToElement.py.
References mghype.api.matrixgenerators.StencilToElement.convertStencilToElementMatrix2d(), and mghype.api.matrixgenerators.StencilToElement.convertStencilToElementMatrix3d().