var searchData=
[
  ['package_20installation_0',['Package Installation',['../page_installation_home.html#autotoc_md167',1,'']]],
  ['packages_1',['Prebuilt Environments and Packages',['../page_installation_home.html#autotoc_md170',1,'']]],
  ['page_2',['New (top-level) documentation page',['../page_documentation_home.html#autotoc_md68',1,'']]],
  ['papers_3',['Reference papers',['../applications_exahype2_exaseis.html#autotoc_md268',1,'']]],
  ['parallel_20behaviour_4',['Parallel behaviour',['../page_exahype_tracer.html#autotoc_md50',1,'Parallel behaviour'],['../page_peano_amr.html#autotoc_md205',1,'Parallel behaviour']]],
  ['parallel_20execution_5',['Parallel execution',['../page_peano4_particles_mesh_consistency.html#autotoc_md201',1,'Parallel execution'],['../page_peano4_particles_mesh_traversal.html#autotoc_md209',1,'Parallel execution']]],
  ['parallel_20plotting_6',['Parallel plotting',['../tarch_plotting.html#autotoc_md255',1,'']]],
  ['parallelisation_7',['Parallelisation',['../page_faq_home.html#autotoc_md249',1,'']]],
  ['parallelism_8',['Solver and kernel parallelism',['../page_peano_performance_optimisation.html#autotoc_md242',1,'']]],
  ['paraview_9',['ParaView',['../documentation_tarch_visualisation_paraview.html',1,'documentation_tarch_visualisation']]],
  ['part_201_20the_20acoustic_20equations_10',['Part 1 - The Acoustic Equations',['../page_exahype2_tutorials_acoustic.html',1,'page_exahype2_tutorials']]],
  ['part_202_20solution_20to_20exercise_201_11',['Part 2 - Solution to Exercise 1',['../page_exahype2_tutorials_shallow_water_solution.html',1,'page_exahype2_tutorials_shallow_water']]],
  ['part_202_20solution_20to_20exercise_202_12',['Part 2 - Solution to Exercise 2',['../page_exahype2_tutorials_shallow_water_solution_2.html',1,'page_exahype2_tutorials_shallow_water']]],
  ['part_202_20the_20shallow_20water_20equations_13',['Part 2 - The Shallow Water Equations',['../page_exahype2_tutorials_shallow_water.html',1,'page_exahype2_tutorials']]],
  ['part_203_20the_20euler_20equations_20over_20an_20airfoil_14',['Part 3 - The Euler Equations over an Airfoil',['../page_exahype2_tutorials_euler.html',1,'page_exahype2_tutorials']]],
  ['part_204_20a_202d_20euler_20shock_20with_20a_20posteriori_20limiting_15',['Part 4 - A 2D Euler Shock with a-posteriori Limiting',['../page_exahype2_tutorials_limiting.html',1,'page_exahype2_tutorials']]],
  ['part_205_203d_20elastic_20waves_20and_20a_20taste_20of_20hpc_16',['Part 5 - 3D Elastic Waves and a Taste of HPC',['../page_exahype2_tutorials_elastic.html',1,'page_exahype2_tutorials']]],
  ['particle_20allocation_17',['Particle allocation',['../page_peano4_particles_realisation_particle_lift_flavours.html#autotoc_md206',1,'']]],
  ['particle_20interaction_20sets_18',['Particle interaction sets',['../page_peano4_particles_mesh_traversal.html',1,'page_peano4_particles']]],
  ['particle_20once_19',['Updating a particle once',['../page_peano4_particles_mesh_traversal.html#autotoc_md196',1,'']]],
  ['particle_20set_20storage_20',['Particle-set storage',['../page_peano4_particles_realisation_particle_lift_flavours.html',1,'page_peano4_particles_realisation']]],
  ['particle_20sorting_20and_20mesh_20consistency_21',['Particle sorting and mesh consistency',['../page_peano4_particles_mesh_consistency.html',1,'page_peano4_particles']]],
  ['particle_20storage_22',['Multiscale particle storage',['../page_peano4_particles_mesh_storage.html',1,'page_peano4_particles']]],
  ['particle_20storage_20and_20exchange_23',['Particle storage and exchange',['../page_peano4_particles_realisation.html',1,'page_peano4_particles']]],
  ['particles_24',['Particles',['../page_peano4_particles.html',1,'page_peano4_home']]],
  ['particles_2dmesh_2dconsistency_2edox_25',['particles-mesh-consistency.dox',['../particles-mesh-consistency_8dox.html',1,'']]],
  ['particles_2dmesh_2dtraversal_2edox_26',['particles-mesh-traversal.dox',['../particles-mesh-traversal_8dox.html',1,'']]],
  ['particles_2drealisation_2edox_27',['particles-realisation.dox',['../particles-realisation_8dox.html',1,'']]],
  ['particles_2dstorage_2edox_28',['particles-storage.dox',['../particles-storage_8dox.html',1,'']]],
  ['particles_2edox_29',['particles.dox',['../particles_8dox.html',1,'']]],
  ['partition_30',['Partition',['../page_peano_domain_decomposition.html#autotoc_md191',1,'Inter-rank partition'],['../page_machines_lumi.html#autotoc_md153',1,'LUMI-G GPU Partition']]],
  ['party_20tools_31',['Third-party tools',['../page_third_party_home.html',1,'index']]],
  ['patch_20data_20consistent_32',['Keeping face and patch data consistent',['../documentation_exahype2_solvers_finite_volumes.html#autotoc_md79',1,'']]],
  ['patch_20file_20format_33',['Patch file format',['../tarch_patch_file_format.html',1,'documentation_tarch_visualisation']]],
  ['patch_20files_34',['Visualise the patch files',['../page_exahype_visualisation.html#autotoc_md131',1,'']]],
  ['patch_20operations_35',['Block-structured patch operations',['../page_exahype2_blockstructured.html',1,'page_exahype2_home']]],
  ['patch_20with_20halo_36',['Augment patch with halo',['../documentation_exahype2_solvers_finite_volumes.html#autotoc_md81',1,'']]],
  ['path_37',['Manually Adding the Python Path',['../page_installation_home.html#autotoc_md168',1,'']]],
  ['pattern_38',['Action set pattern',['../tarch_plotting.html#autotoc_md253',1,'']]],
  ['pde_20terms_20without_20state_39',['Provide the additional PDE terms without state',['../page_exahype_gpu.html#autotoc_md88',1,'']]],
  ['peano_40',['Peano',['../page_installation_home.html#autotoc_md160',1,'Configure Peano'],['../index.html',1,'Peano']]],
  ['peano_204_41',['Peano 4',['../page_peano4_home.html',1,'index']]],
  ['peano_20data_42',['Peano data',['../page_exahype_runtime_analysis.html#autotoc_md19',1,'']]],
  ['peano_20s_20internal_20compiler_20specific_20switches_43',['Realisation of Peano&apos;s internal compiler-specific switches',['../page_compiler_specific_settings_home.html#autotoc_md41',1,'']]],
  ['performance_20analysis_44',['Performance analysis',['../page_faq_home.html#autotoc_md245',1,'']]],
  ['performance_20considerations_45',['Performance considerations',['../page_peano_amr.html#autotoc_md210',1,'']]],
  ['performance_20optimisation_46',['Performance optimisation',['../page_exahype_performance_optimisation.html',1,'Performance optimisation'],['../page_peano_performance_optimisation.html',1,'Performance optimisation']]],
  ['performance_5foptimisation_2edox_47',['performance_optimisation.dox',['../exahype2_2performance__optimisation_8dox.html',1,'(Global Namespace)'],['../peano4_2performance__optimisation_8dox.html',1,'(Global Namespace)']]],
  ['periodic_20domains_48',['Periodic domains',['../page_peano_domain_decomposition.html#autotoc_md211',1,'']]],
  ['persistent_20storage_20and_20exchange_49',['Persistent storage and exchange',['../page_peano4_particles_realisation_particle_lift_flavours.html#autotoc_md214',1,'']]],
  ['perspective_50',['FAQs and Troubleshooting (User Perspective)',['../page_faq_home.html',1,'index']]],
  ['phase_202_51',['SuperMUC-NG Phase 2',['../page_machines_supermuc.html#autotoc_md138',1,'']]],
  ['pictures_20for_20developers_52',['Tweaking your pictures (for developers)',['../documentation_tarch_visualisation.html#autotoc_md258',1,'']]],
  ['pipeline_53',['How do I run the pipeline?',['../page_continuous_integration.html#autotoc_md126',1,'']]],
  ['plan_20evaluation_54',['Refinement-plan evaluation',['../page_peano_amr.html#autotoc_md192',1,'']]],
  ['plotting_55',['Plotting',['../tarch_plotting.html#autotoc_md255',1,'Parallel plotting'],['../tarch_plotting.html',1,'Plotting']]],
  ['plotting_2edox_56',['plotting.dox',['../plotting_8dox.html',1,'']]],
  ['point_57',['Safe update point',['../page_peano4_particles_mesh_consistency.html#autotoc_md183',1,'']]],
  ['point_20communication_58',['Point-to-point communication',['../page_tarch_mpi.html#autotoc_md236',1,'']]],
  ['point_20to_20point_20communication_59',['Point-to-point communication',['../page_tarch_mpi.html#autotoc_md236',1,'']]],
  ['policy_60',['Merge policy',['../page_peano4_particles_realisation_particle_lift_flavours.html#autotoc_md216',1,'']]],
  ['pools_61',['Pools',['../page_architecture_home.html#autotoc_md24',1,'Grid representation and data pools'],['../page_peano_localisation.html#autotoc_md173',1,'Rank-local pools']]],
  ['popular_20subbranches_62',['Popular subbranches',['../page_version_control_home.html#autotoc_md264',1,'']]],
  ['port_20forwarding_20jupyterlab_63',['With Port Forwarding (JupyterLab)',['../page_installation_with_docker.html#autotoc_md279',1,'']]],
  ['posteriori_20limiting_64',['Part 4 - A 2D Euler Shock with a-posteriori Limiting',['../page_exahype2_tutorials_limiting.html',1,'page_exahype2_tutorials']]],
  ['prebuilt_20environments_20and_20packages_65',['Prebuilt Environments and Packages',['../page_installation_home.html#autotoc_md170',1,'']]],
  ['predicates_66',['Storage predicates',['../page_peano_localisation.html#autotoc_md175',1,'']]],
  ['predictor_67',['Predictor',['../page_exahype2_numerics_ADER-DG.html#autotoc_md31',1,'']]],
  ['prerequisites_68',['Prerequisites',['../page_installation_home.html#autotoc_md150',1,'Dependencies and Prerequisites'],['../page_installation_with_spack.html#autotoc_md270',1,'Prerequisites']]],
  ['probe_20data_69',['Error norms and probe data',['../page_exahype_runtime_analysis.html#autotoc_md9',1,'']]],
  ['probing_20data_70',['Probing data',['../documentation_tarch_visualisation_probing-data.html',1,'documentation_tarch_visualisation']]],
  ['producing_20requests_71',['Producing requests',['../page_peano_amr.html#autotoc_md200',1,'']]],
  ['profiling_20and_20assertions_72',['Logging, profiling and assertions',['../tarch_logging.html',1,'page_tarch_home']]],
  ['profiling_20support_73',['Logging Devices, Formats, Backends And Profiling Support',['../tarch_logging.html#tarch_logging_backends',1,'']]],
  ['program_20steps_74',['Program steps',['../page_architecture_home.html#autotoc_md21',1,'']]],
  ['programmer_20s_20view_75',['GPU support (programmer&apos;s view)',['../page_exahype_gpu.html#autotoc_md67',1,'']]],
  ['programming_76',['MPI programming',['../page_tarch_mpi.html',1,'page_tarch_home']]],
  ['project_77',['How do I add new runners to project?',['../page_continuous_integration.html#autotoc_md129',1,'']]],
  ['projecting_20solver_20data_78',['Projecting solver data',['../page_exahype_tracer.html#autotoc_md20',1,'']]],
  ['provide_20the_20additional_20pde_20terms_20without_20state_79',['Provide the additional PDE terms without state',['../page_exahype_gpu.html#autotoc_md88',1,'']]],
  ['python_20api_80',['Python API',['../page_architecture_home.html#autotoc_md84',1,'Python API'],['../peano_main.html#autotoc_md181',1,'Python API'],['../page_faq_home.html#autotoc_md240',1,'Python API']]],
  ['python_20configuration_81',['Python Configuration',['../page_installation_home.html#autotoc_md166',1,'']]],
  ['python_20conventions_20style_20guide_82',['Python Conventions / Style Guide',['../page_conventions_home.html#autotoc_md42',1,'']]],
  ['python_20dependencies_83',['Python Dependencies',['../page_installation_home.html#autotoc_md169',1,'']]],
  ['python_20path_84',['Manually Adding the Python Path',['../page_installation_home.html#autotoc_md168',1,'']]],
  ['pyvista_85',['PyVista',['../documentation_tarch_visualisation_pyvista.html',1,'documentation_tarch_visualisation']]]
];
