var searchData=
[
  ['d_20dimensional_20exclusive_20loops_0',['d-dimensional exclusive loops',['../peano_utilities.html#autotoc_md238',1,'']]],
  ['d_20dimensional_20loops_1',['d-dimensional loops',['../peano_utilities.html#autotoc_md232',1,'']]],
  ['dam_20break_2',['Exercise 1 - A Dam Break',['../page_exahype2_tutorials_shallow_water.html#autotoc_md71',1,'']]],
  ['data_3',['Data',['../peano_action_sets.html#autotoc_md220',1,'Coarse-grid data'],['../page_exahype_runtime_analysis.html#autotoc_md9',1,'Error norms and probe data']]],
  ['data_4',['Localisation of generated data',['../page_peano_localisation.html',1,'page_peano4_home']]],
  ['data_5',['Data',['../peano_action_sets.html#autotoc_md219',1,'Markers and data'],['../page_exahype_runtime_analysis.html#autotoc_md19',1,'Peano data']]],
  ['data_6',['Probing data',['../documentation_tarch_visualisation_probing-data.html',1,'documentation_tarch_visualisation']]],
  ['data_7',['Data',['../page_exahype_tracer.html#autotoc_md20',1,'Projecting solver data'],['../page_exahype_domain-decomposition.html#autotoc_md5',1,'Solver data']]],
  ['data_20access_8',['Data access',['../page_exahype_performance_optimisation.html#autotoc_md8',1,'']]],
  ['data_20consistency_9',['Data consistency',['../page_architecture_home.html#autotoc_md64',1,'']]],
  ['data_20consistent_10',['Keeping face and patch data consistent',['../documentation_exahype2_solvers_finite_volumes.html#autotoc_md79',1,'']]],
  ['data_20flow_11',['Data flow',['../documentation_exahype2_solvers_aderdg.html#autotoc_md122',1,'']]],
  ['data_20pools_12',['Grid representation and data pools',['../page_architecture_home.html#autotoc_md24',1,'']]],
  ['data_20structures_13',['Data structures',['../documentation_exahype2_solvers_finite_volumes.html#autotoc_md69',1,'']]],
  ['data_20transfer_14',['Solver data transfer',['../page_exahype_amr.html#autotoc_md72',1,'']]],
  ['debugging_15',['Debugging',['../page_faq_home.html#autotoc_md246',1,'']]],
  ['decision_20semantics_16',['Decision semantics',['../page_exahype_amr.html#autotoc_md7',1,'']]],
  ['decomposition_17',['decomposition',['../page_exahype_domain-decomposition.html',1,'Domain decomposition'],['../page_peano_domain_decomposition.html',1,'Domain decomposition']]],
  ['decomposition_18',['Decomposition',['../page_peano_runtime_analysis.html#autotoc_md234',1,'Inter-rank decomposition'],['../page_peano_performance_optimisation.html#autotoc_md224',1,'Interpreting the decomposition'],['../page_peano_runtime_analysis.html#autotoc_md235',1,'Intra-rank decomposition'],['../page_peano_domain_decomposition.html#autotoc_md194',1,'Intra-rank task decomposition']]],
  ['dependencies_19',['Python Dependencies',['../page_installation_home.html#autotoc_md169',1,'']]],
  ['dependencies_20and_20prerequisites_20',['Dependencies and Prerequisites',['../page_installation_home.html#autotoc_md150',1,'']]],
  ['developers_21',['Developers',['../page_installation_with_docker.html#autotoc_md280',1,'Build (for Developers)'],['../documentation_tarch_visualisation.html#autotoc_md258',1,'Tweaking your pictures (for developers)']]],
  ['devices_20formats_20backends_20and_20profiling_20support_22',['Logging Devices, Formats, Backends And Profiling Support',['../tarch_logging.html#tarch_logging_backends',1,'']]],
  ['dg_23',['ADER-DG',['../page_exahype2_numerics_ADER-DG.html',1,'page_numerics']]],
  ['dg_20solvers_24',['ADER-DG solvers',['../documentation_exahype2_solvers_aderdg.html',1,'page_solvers']]],
  ['dg_2edox_25',['DG.dox',['../DG_8dox.html',1,'']]],
  ['difference_26',['Finite Difference',['../page_exahype2_numerics_finite-differences.html',1,'page_numerics']]],
  ['dimensional_20exclusive_20loops_27',['d-dimensional exclusive loops',['../peano_utilities.html#autotoc_md238',1,'']]],
  ['dimensional_20loops_28',['d-dimensional loops',['../peano_utilities.html#autotoc_md232',1,'']]],
  ['dine_29',['DINE',['../page_machines_dine.html',1,'DINE'],['../page_machines_dine.html#autotoc_md156',1,'DINE']]],
  ['dine_2edox_30',['dine.dox',['../dine_8dox.html',1,'']]],
  ['dirichlet_20boundary_20conditions_31',['Dirichlet boundary conditions',['../page_exahype_boundary_conditions.html#autotoc_md18',1,'']]],
  ['discontinuous_20galerkin_32',['Discontinuous Galerkin',['../page_exahype2_numerics_DG.html',1,'Discontinuous Galerkin'],['../page_exahype_visualisation.html#autotoc_md135',1,'Discontinuous Galerkin']]],
  ['distributed_20requests_33',['Distributed requests',['../page_exahype_amr.html#autotoc_md46',1,'']]],
  ['do_20i_20add_20new_20runners_20to_20project_34',['How do I add new runners to project?',['../page_continuous_integration.html#autotoc_md129',1,'']]],
  ['do_20i_20run_20the_20pipeline_35',['How do I run the pipeline?',['../page_continuous_integration.html#autotoc_md126',1,'']]],
  ['do_20i_20write_20my_20own_20tests_36',['How do I write my own tests?',['../page_continuous_integration.html#autotoc_md127',1,'']]],
  ['docker_37',['Docker',['../page_installation_with_docker.html',1,'Installation with Docker'],['../page_exahype2_tutorials.html#autotoc_md157',1,'Option B: Build from Source (No Docker)']]],
  ['docker_20image_20recommended_38',['Option A: The Tutorials Docker Image (Recommended)',['../page_exahype2_tutorials.html#autotoc_md155',1,'']]],
  ['documentation_20doxygen_39',['Documentation (Doxygen)',['../page_documentation_home.html',1,'index']]],
  ['documentation_20inside_20the_20code_40',['Adding (low-level) documentation inside the code',['../page_documentation_home.html#autotoc_md86',1,'']]],
  ['documentation_20page_41',['New (top-level) documentation page',['../page_documentation_home.html#autotoc_md68',1,'']]],
  ['documentation_2edox_42',['documentation.dox',['../documentation_8dox.html',1,'']]],
  ['domain_20decomposition_43',['Domain decomposition',['../page_exahype_domain-decomposition.html',1,'Domain decomposition'],['../page_peano_domain_decomposition.html',1,'Domain decomposition']]],
  ['domain_2ddecomposition_2edox_44',['domain-decomposition.dox',['../domain-decomposition_8dox.html',1,'']]],
  ['domain_5fdecomposition_2edox_45',['domain_decomposition.dox',['../domain__decomposition_8dox.html',1,'']]],
  ['domains_46',['Periodic domains',['../page_peano_domain_decomposition.html#autotoc_md211',1,'']]],
  ['doxygen_47',['Doxygen',['../page_documentation_home.html',1,'Documentation (Doxygen)'],['../page_documentation_home.html#autotoc_md121',1,'Install doxygen']]],
  ['doxygen_20cheat_20sheet_48',['Doxygen cheat sheet',['../page_documentation_home.html#autotoc_md102',1,'']]],
  ['drains_49',['Regrid drains',['../page_exahype_amr.html#autotoc_md49',1,'']]],
  ['dual_20grid_20interpretation_50',['Dual-grid interpretation',['../page_peano4_particles_mesh_storage.html#autotoc_md199',1,'']]],
  ['dynamic_20mesh_20changes_51',['Dynamic mesh changes',['../page_peano4_particles_mesh_consistency.html#autotoc_md184',1,'']]]
];
