var searchData=
[
  ['tailor_20the_20compute_20kernels_0',['Tailor the compute kernels',['../page_exahype_gpu.html#autotoc_md99',1,'']]],
  ['tarch_1',['Technical Architecture (tarch)',['../page_tarch_home.html',1,'index']]],
  ['task_20balance_2',['Traversal task balance',['../page_exahype_performance_optimisation.html#autotoc_md34',1,'']]],
  ['task_20decomposition_3',['Intra-rank task decomposition',['../page_peano_domain_decomposition.html#autotoc_md194',1,'']]],
  ['task_20graph_4',['Traversal task graph',['../page_architecture_home.html#autotoc_md27',1,'']]],
  ['task_20local_20copies_5',['Task-local copies',['../page_peano_localisation.html#autotoc_md176',1,'']]],
  ['tasking_6',['Tasking',['../page_exahype_multicore.html',1,'Tasking'],['../page_tarch_tasking.html',1,'Tasking']]],
  ['tasking_2edox_7',['tasking.dox',['../exahype2_2tasking_8dox.html',1,'(Global Namespace)'],['../tarch_2tasking_8dox.html',1,'(Global Namespace)']]],
  ['tasks_8',['Tasks',['../page_exahype_multicore.html#autotoc_md4',1,'Solver tasks'],['../page_exahype_performance_optimisation.html#autotoc_md36',1,'Solver tasks'],['../page_tarch_tasking.html#autotoc_md251',1,'Tasks'],['../page_exahype_multicore.html#autotoc_md2',1,'Traversal tasks']]],
  ['taste_20of_20hpc_9',['Taste of HPC',['../page_exahype2_tutorials_elastic.html#autotoc_md145',1,'A Taste of HPC'],['../page_exahype2_tutorials_elastic.html',1,'Part 5 - 3D Elastic Waves and a Taste of HPC']]],
  ['technical_20architecture_20tarch_10',['Technical Architecture (tarch)',['../page_tarch_home.html',1,'index']]],
  ['techniques_11',['Advanced techniques',['../page_exahype_gpu.html#autotoc_md104',1,'']]],
  ['template_12',['Config template',['../page_continuous_integration.html#autotoc_md130',1,'']]],
  ['terms_20without_20state_13',['Provide the additional PDE terms without state',['../page_exahype_gpu.html#autotoc_md88',1,'']]],
  ['test_14',['Test',['../page_continuous_integration.html#autotoc_md128',1,'Anatomy of a test'],['../page_installation_home.html#autotoc_md164',1,'Test']]],
  ['test_20architecture_15',['Test architecture',['../tarch_tests.html#autotoc_md257',1,'']]],
  ['test_20routines_16',['Test routines',['../tarch_tests.html#autotoc_md261',1,'']]],
  ['testing_2edox_17',['testing.dox',['../testing_8dox.html',1,'']]],
  ['tests_18',['Tests',['../page_continuous_integration.html#autotoc_md127',1,'How do I write my own tests?'],['../tarch_tests.html#autotoc_md259',1,'Running the tests']]],
  ['tests_19',['Unit tests',['../tarch_tests.html',1,'page_tarch_home']]],
  ['tex_20',['TeX',['../page_documentation_home.html#autotoc_md115',1,'']]],
  ['the_20acoustic_20equations_21',['The Acoustic Equations',['../page_exahype2_tutorials_acoustic.html',1,'Part 1 - The Acoustic Equations'],['../page_exahype2_tutorials_acoustic.html#autotoc_md35',1,'The Acoustic Equations']]],
  ['the_20additional_20pde_20terms_20without_20state_22',['Provide the additional PDE terms without state',['../page_exahype_gpu.html#autotoc_md88',1,'']]],
  ['the_20code_23',['Adding (low-level) documentation inside the code',['../page_documentation_home.html#autotoc_md86',1,'']]],
  ['the_20compute_20kernels_24',['Tailor the compute kernels',['../page_exahype_gpu.html#autotoc_md99',1,'']]],
  ['the_20configuration_25',['The Configuration',['../page_exahype2_tutorials_limiting.html#autotoc_md63',1,'The Configuration'],['../page_exahype2_tutorials_shallow_water.html#autotoc_md59',1,'The Configuration'],['../page_exahype2_tutorials_acoustic.html#autotoc_md39',1,'The Configuration'],['../page_exahype2_tutorials_euler.html#autotoc_md58',1,'The Configuration'],['../page_exahype2_tutorials_elastic.html#autotoc_md142',1,'The Configuration']]],
  ['the_20decomposition_26',['Interpreting the decomposition',['../page_peano_performance_optimisation.html#autotoc_md224',1,'']]],
  ['the_20elastic_20wave_20equations_27',['The Elastic Wave Equations',['../page_exahype2_tutorials_elastic.html#autotoc_md141',1,'']]],
  ['the_20equations_28',['The Equations',['../page_exahype2_tutorials_limiting.html#autotoc_md48',1,'']]],
  ['the_20euler_20equations_29',['The Euler Equations',['../page_exahype2_tutorials_euler.html#autotoc_md33',1,'']]],
  ['the_20euler_20equations_20over_20an_20airfoil_30',['Part 3 - The Euler Equations over an Airfoil',['../page_exahype2_tutorials_euler.html',1,'page_exahype2_tutorials']]],
  ['the_20exahype_202_20extension_31',['Building the ExaHyPE 2 extension',['../page_exahype2_home.html#autotoc_md28',1,'']]],
  ['the_20generated_20main_20routine_32',['The generated main routine',['../peano_main.html',1,'page_peano4_home']]],
  ['the_20gpu_20offloading_20works_33',['How the GPU offloading works',['../page_exahype_gpu.html#autotoc_md62',1,'']]],
  ['the_20implementation_20file_34',['The Implementation File',['../page_exahype2_tutorials_acoustic.html#autotoc_md44',1,'The Implementation File'],['../page_exahype2_tutorials_euler.html#autotoc_md77',1,'The Implementation File'],['../page_exahype2_tutorials_elastic.html#autotoc_md143',1,'The Implementation File']]],
  ['the_20implementation_20files_35',['The Implementation Files',['../page_exahype2_tutorials_limiting.html#autotoc_md65',1,'']]],
  ['the_20limiter_36',['Why We Need the Limiter',['../page_exahype2_tutorials_limiting.html#autotoc_md90',1,'']]],
  ['the_20logging_20interface_37',['Using The Logging Interface',['../tarch_logging.html#tarch_logging_interface',1,'']]],
  ['the_20muscl_20hancock_20scheme_38',['The MUSCL-Hancock Scheme',['../page_tutorials_exahype2_numerics_higher_order_finite_volumes.html#autotoc_md25',1,'']]],
  ['the_20patch_20files_39',['Visualise the patch files',['../page_exahype_visualisation.html#autotoc_md131',1,'']]],
  ['the_20pipeline_40',['How do I run the pipeline?',['../page_continuous_integration.html#autotoc_md126',1,'']]],
  ['the_20python_20path_41',['Manually Adding the Python Path',['../page_installation_home.html#autotoc_md168',1,'']]],
  ['the_20repository_42',['Remove the Repository',['../page_installation_with_spack.html#autotoc_md275',1,'']]],
  ['the_20shallow_20water_20equations_43',['The Shallow Water Equations',['../page_exahype2_tutorials_shallow_water.html',1,'Part 2 - The Shallow Water Equations'],['../page_exahype2_tutorials_shallow_water.html#autotoc_md15',1,'The Shallow Water Equations']]],
  ['the_20tests_44',['Running the tests',['../tarch_tests.html#autotoc_md259',1,'']]],
  ['the_20thread_20stack_45',['Large generated records exhaust the thread stack',['../page_exahype_faq.html#autotoc_md0',1,'']]],
  ['the_20tutorials_20docker_20image_20recommended_46',['Option A: The Tutorials Docker Image (Recommended)',['../page_exahype2_tutorials.html#autotoc_md155',1,'']]],
  ['the_20visualisation_47',['Extend the visualisation',['../page_exahype_extend-visualisation.html',1,'page_exahype2_home']]],
  ['third_20party_20tools_48',['Third-party tools',['../page_third_party_home.html',1,'index']]],
  ['thread_20stack_49',['Large generated records exhaust the thread stack',['../page_exahype_faq.html#autotoc_md0',1,'']]],
  ['time_20series_50',['File writers and time series',['../tarch_plotting.html#autotoc_md254',1,'']]],
  ['tinyhttpproxy_51',['Connecting to SuperMUC using TinyHTTPProxy',['../page_machines_supermuc.html#autotoc_md137',1,'']]],
  ['to_20add_20new_20files_52',['How to add new files',['../page_documentation_home.html#autotoc_md54',1,'']]],
  ['to_20exercise_201_53',['Part 2 - Solution to Exercise 1',['../page_exahype2_tutorials_shallow_water_solution.html',1,'page_exahype2_tutorials_shallow_water']]],
  ['to_20exercise_202_54',['Part 2 - Solution to Exercise 2',['../page_exahype2_tutorials_shallow_water_solution_2.html',1,'page_exahype2_tutorials_shallow_water']]],
  ['to_20existing_20code_20snippets_55',['Links to existing code snippets',['../page_documentation_home.html#autotoc_md120',1,'']]],
  ['to_20point_20communication_56',['Point-to-point communication',['../page_tarch_mpi.html#autotoc_md236',1,'']]],
  ['to_20project_57',['How do I add new runners to project?',['../page_continuous_integration.html#autotoc_md129',1,'']]],
  ['to_20supermuc_20using_20tinyhttpproxy_58',['Connecting to SuperMUC using TinyHTTPProxy',['../page_machines_supermuc.html#autotoc_md137',1,'']]],
  ['toolchains_20and_20compiler_20settings_59',['Vendor toolchains and compiler settings',['../page_compiler_specific_settings_home.html#autotoc_md47',1,'']]],
  ['tools_60',['Third-party tools',['../page_third_party_home.html',1,'index']]],
  ['top_20level_20documentation_20page_61',['New (top-level) documentation page',['../page_documentation_home.html#autotoc_md68',1,'']]],
  ['tracer_62',['Adding a tracer',['../page_exahype_tracer.html#autotoc_md17',1,'']]],
  ['tracer_2edox_63',['tracer.dox',['../tracer_8dox.html',1,'']]],
  ['tracers_64',['Tracers',['../page_exahype_tracer.html#autotoc_md37',1,'Moving tracers'],['../page_exahype_tracer.html',1,'Tracers']]],
  ['tracing_65',['Build modes and tracing',['../page_compiler_specific_settings_home.html#autotoc_md95',1,'']]],
  ['trajectories_66',['Writing trajectories',['../page_exahype_tracer.html#autotoc_md23',1,'']]],
  ['transfer_67',['Solver data transfer',['../page_exahype_amr.html#autotoc_md72',1,'']]],
  ['traversal_20events_68',['Action sets and traversal events',['../peano_action_sets.html',1,'page_peano4_home']]],
  ['traversal_20lifecycle_69',['Traversal lifecycle',['../peano_action_sets.html#autotoc_md185',1,'']]],
  ['traversal_20task_20balance_70',['Traversal task balance',['../page_exahype_performance_optimisation.html#autotoc_md34',1,'']]],
  ['traversal_20task_20graph_71',['Traversal task graph',['../page_architecture_home.html#autotoc_md27',1,'']]],
  ['traversal_20tasks_72',['Traversal tasks',['../page_exahype_multicore.html#autotoc_md2',1,'']]],
  ['troubleshooting_73',['FAQ and troubleshooting',['../page_exahype_faq.html',1,'page_exahype2_home']]],
  ['troubleshooting_74',['MPI troubleshooting',['../page_faq_home.html#autotoc_md247',1,'']]],
  ['troubleshooting_20user_20perspective_75',['FAQs and Troubleshooting (User Perspective)',['../page_faq_home.html',1,'index']]],
  ['tunnelling_76',['Tunnelling',['../page_peano4_particles_mesh_consistency.html#autotoc_md189',1,'']]],
  ['tutorials_77',['Tutorials',['../page_exahype2_tutorials.html',1,'Tutorials'],['../page_documentation_home.html#autotoc_md100',1,'Tutorials']]],
  ['tutorials_20docker_20image_20recommended_78',['Option A: The Tutorials Docker Image (Recommended)',['../page_exahype2_tutorials.html#autotoc_md155',1,'']]],
  ['tweaking_20your_20pictures_20for_20developers_79',['Tweaking your pictures (for developers)',['../documentation_tarch_visualisation.html#autotoc_md258',1,'']]],
  ['two_20sweep_20schedule_80',['Two-sweep schedule',['../documentation_exahype2_solvers_aderdg.html#autotoc_md123',1,'']]],
  ['types_81',['Interaction types',['../page_peano4_particles_mesh_traversal.html#autotoc_md203',1,'']]]
];
