var searchData=
[
  ['observer_20lifecycle_0',['Observer lifecycle',['../page_peano_domain_decomposition.html#autotoc_md198',1,'']]],
  ['of_20a_20test_1',['Anatomy of a test',['../page_continuous_integration.html#autotoc_md128',1,'']]],
  ['of_20generated_20data_2',['Localisation of generated data',['../page_peano_localisation.html',1,'page_peano4_home']]],
  ['of_20hpc_3',['A Taste of HPC',['../page_exahype2_tutorials_elastic.html#autotoc_md145',1,'']]],
  ['of_20hpc_4',['Part 5 - 3D Elastic Waves and a Taste of HPC',['../page_exahype2_tutorials_elastic.html',1,'page_exahype2_tutorials']]],
  ['of_20peano_20s_20internal_20compiler_20specific_20switches_5',['Realisation of Peano&apos;s internal compiler-specific switches',['../page_compiler_specific_settings_home.html#autotoc_md41',1,'']]],
  ['offline_20conversion_6',['Offline conversion',['../documentation_tarch_visualisation_offline-conversion.html',1,'documentation_tarch_visualisation']]],
  ['offloading_7',['Offloading',['../page_compiler_specific_settings_home.html#autotoc_md82',1,'OpenMP and OpenMP offloading'],['../page_compiler_specific_settings_home.html#autotoc_md98',1,'OpenMP and OpenMP offloading'],['../page_compiler_specific_settings_home.html#autotoc_md112',1,'OpenMP and OpenMP offloading'],['../page_compiler_specific_settings_home.html#autotoc_md116',1,'OpenMP and OpenMP offloading'],['../page_compiler_specific_settings_home.html#autotoc_md101',1,'SYCL and SYCL offloading']]],
  ['offloading_20with_20clang_8',['OpenMP offloading with Clang',['../page_machines_ncc.html#autotoc_md171',1,'']]],
  ['offloading_20with_20nvc_9',['OpenMP offloading with NVC++',['../page_machines_ncc.html#autotoc_md172',1,'']]],
  ['offloading_20with_20oneapi_10',['SYCL offloading with oneAPI',['../page_machines_ncc.html#autotoc_md174',1,'']]],
  ['offloading_20works_11',['How the GPU offloading works',['../page_exahype_gpu.html#autotoc_md62',1,'']]],
  ['on_20cartesian_20boxes_12',['Boundary conditions on Cartesian boxes',['../page_exahype_boundary_conditions.html#autotoc_md16',1,'']]],
  ['once_13',['Updating a particle once',['../page_peano4_particles_mesh_traversal.html#autotoc_md196',1,'']]],
  ['oneapi_14',['OneAPI',['../page_compiler_specific_settings_home.html#autotoc_md92',1,'Intel (oneAPI)'],['../page_machines_ncc.html#autotoc_md174',1,'SYCL offloading with oneAPI']]],
  ['openmp_15',['OpenMP',['../page_compiler_specific_settings_home.html#autotoc_md106',1,'']]],
  ['openmp_20and_20openmp_20offloading_16',['OpenMP and OpenMP offloading',['../page_compiler_specific_settings_home.html#autotoc_md82',1,'OpenMP and OpenMP offloading'],['../page_compiler_specific_settings_home.html#autotoc_md98',1,'OpenMP and OpenMP offloading'],['../page_compiler_specific_settings_home.html#autotoc_md112',1,'OpenMP and OpenMP offloading'],['../page_compiler_specific_settings_home.html#autotoc_md116',1,'OpenMP and OpenMP offloading']]],
  ['openmp_20offloading_20with_20clang_17',['OpenMP offloading with Clang',['../page_machines_ncc.html#autotoc_md171',1,'']]],
  ['openmp_20offloading_20with_20nvc_18',['OpenMP offloading with NVC++',['../page_machines_ncc.html#autotoc_md172',1,'']]],
  ['operations_19',['Block-structured patch operations',['../page_exahype2_blockstructured.html',1,'page_exahype2_home']]],
  ['operations_20',['Container operations',['../page_peano4_particles_realisation_particle_lift_flavours.html#autotoc_md212',1,'']]],
  ['optimisation_21',['optimisation',['../page_exahype_performance_optimisation.html',1,'Performance optimisation'],['../page_peano_performance_optimisation.html',1,'Performance optimisation']]],
  ['option_20a_3a_20the_20tutorials_20docker_20image_20recommended_22',['Option A: The Tutorials Docker Image (Recommended)',['../page_exahype2_tutorials.html#autotoc_md155',1,'']]],
  ['option_20b_3a_20build_20from_20source_20no_20docker_23',['Option B: Build from Source (No Docker)',['../page_exahype2_tutorials.html#autotoc_md157',1,'']]],
  ['optional_24',['Optional',['../page_installation_home.html#autotoc_md158',1,'']]],
  ['order_25',['Action-set order',['../peano_action_sets.html#autotoc_md221',1,'']]],
  ['order_20finite_20volumes_26',['Higher Order Finite Volumes',['../page_tutorials_exahype2_numerics_higher_order_finite_volumes.html',1,'page_numerics']]],
  ['organisation_27',['Organisation',['../page_architecture_home.html#autotoc_md10',1,'Code organisation'],['../documentation_exahype2_solvers_finite_volumes.html#autotoc_md91',1,'Code organisation'],['../page_architecture_home.html#autotoc_md89',1,'Repository organisation']]],
  ['out_20cells_20which_20are_20not_20a_20fit_28',['Mask out cells which are not a fit',['../page_exahype_gpu.html#autotoc_md107',1,'']]],
  ['outflow_20conditions_29',['Inflow and outflow conditions',['../page_exahype_boundary_conditions.html#autotoc_md43',1,'']]],
  ['output_30',['Solution output',['../page_exahype_visualisation.html#autotoc_md132',1,'']]],
  ['output_31',['Visualisation and output',['../page_exahype_visualisation.html',1,'page_exahype2_home']]],
  ['over_20an_20airfoil_32',['Part 3 - The Euler Equations over an Airfoil',['../page_exahype2_tutorials_euler.html',1,'page_exahype2_tutorials']]],
  ['overhead_33',['Boundary and replication overhead',['../page_peano_performance_optimisation.html#autotoc_md228',1,'']]],
  ['overview_34',['Overview',['../page_installation_with_spack.html#autotoc_md269',1,'']]],
  ['own_20tests_35',['How do I write my own tests?',['../page_continuous_integration.html#autotoc_md127',1,'']]],
  ['ownership_36',['Ownership',['../page_exahype_domain-decomposition.html#autotoc_md40',1,'Adaptive ownership'],['../page_peano4_particles_mesh_storage.html#autotoc_md202',1,'Rank ownership']]]
];
