var searchData=
[
  ['c_20conventions_20style_20guide_0',['C++ conventions / Style Guide',['../page_conventions_home.html#autotoc_md74',1,'']]],
  ['c_20core_1',['C++ core',['../page_faq_home.html#autotoc_md248',1,'']]],
  ['cartesian_2',['Cartesian',['../applications_exahype2_exaseis_cartesian.html',1,'applications_exahype2_exaseis']]],
  ['cartesian_20boxes_3',['Boundary conditions on Cartesian boxes',['../page_exahype_boundary_conditions.html#autotoc_md16',1,'']]],
  ['cells_20which_20are_20not_20a_20fit_4',['Mask out cells which are not a fit',['../page_exahype_gpu.html#autotoc_md107',1,'']]],
  ['changes_5',['Dynamic mesh changes',['../page_peano4_particles_mesh_consistency.html#autotoc_md184',1,'']]],
  ['cheat_20sheet_6',['Doxygen cheat sheet',['../page_documentation_home.html#autotoc_md102',1,'']]],
  ['check_7',['Compile, run and check',['../page_exahype_gpu.html#autotoc_md96',1,'']]],
  ['choosing_20granularity_8',['Choosing granularity',['../page_exahype_multicore.html#autotoc_md6',1,'']]],
  ['ci_9',['CI',['../page_continuous_integration.html',1,'Continuous Integration (CI)'],['../page_continuous_integration.html#autotoc_md125',1,'Gitlab CI']]],
  ['clang_10',['OpenMP offloading with Clang',['../page_machines_ncc.html#autotoc_md171',1,'']]],
  ['cleanup_11',['Cleanup',['../page_installation_with_spack.html#autotoc_md276',1,'']]],
  ['cmake_12',['CMake',['../page_installation_home.html#autotoc_md162',1,'CMake'],['../page_faq_home.html#autotoc_md222',1,'CMake']]],
  ['coarse_20grid_20data_13',['Coarse-grid data',['../peano_action_sets.html#autotoc_md220',1,'']]],
  ['code_14',['Adding (low-level) documentation inside the code',['../page_documentation_home.html#autotoc_md86',1,'']]],
  ['code_20formatting_15',['Code Formatting',['../page_conventions_home.html#autotoc_md76',1,'']]],
  ['code_20organisation_16',['Code organisation',['../page_architecture_home.html#autotoc_md10',1,'Code organisation'],['../documentation_exahype2_solvers_finite_volumes.html#autotoc_md91',1,'Code organisation']]],
  ['code_20snippets_17',['Code snippets',['../page_documentation_home.html#autotoc_md113',1,'Code snippets'],['../page_documentation_home.html#autotoc_md120',1,'Links to existing code snippets']]],
  ['coding_20conventions_20and_20ides_18',['Coding Conventions and IDEs',['../page_conventions_home.html',1,'index']]],
  ['collectives_19',['Collectives',['../page_tarch_mpi.html#autotoc_md241',1,'']]],
  ['commandlinesink_20',['CommandLineSink',['../tarch_logging.html#tarch_logging_command_line_sink',1,'']]],
  ['comments_21',['Comments',['../page_documentation_home.html#autotoc_md111',1,'']]],
  ['communication_22',['Point-to-point communication',['../page_tarch_mpi.html#autotoc_md236',1,'']]],
  ['comparing_20solutions_23',['Rendering and comparing solutions',['../page_exahype_runtime_analysis.html#autotoc_md12',1,'']]],
  ['compilation_24',['Compilation',['../page_faq_home.html#autotoc_md223',1,'']]],
  ['compile_20run_20and_20check_25',['Compile, run and check',['../page_exahype_gpu.html#autotoc_md96',1,'']]],
  ['compiler_20images_26',['Building Compiler Images',['../page_installation_with_docker.html#autotoc_md282',1,'']]],
  ['compiler_20settings_27',['Vendor toolchains and compiler settings',['../page_compiler_specific_settings_home.html#autotoc_md47',1,'']]],
  ['compiler_20specific_20settings_28',['Vendor Software Stacks and System- and Compiler-specific Settings',['../page_compiler_specific_settings_home.html',1,'index']]],
  ['compiler_20specific_20switches_29',['Realisation of Peano&apos;s internal compiler-specific switches',['../page_compiler_specific_settings_home.html#autotoc_md41',1,'']]],
  ['compiler_2dspecific_2dsettings_2edox_30',['compiler-specific-settings.dox',['../compiler-specific-settings_8dox.html',1,'']]],
  ['complex_20boundaries_31',['More complex boundaries',['../page_exahype_boundary_conditions.html#autotoc_md56',1,'']]],
  ['compute_20kernels_32',['Compute kernels',['../page_exahype_gpu.html#autotoc_md80',1,'Enable stateless compute kernels'],['../page_exahype_gpu.html#autotoc_md99',1,'Tailor the compute kernels']]],
  ['conditions_33',['Boundary conditions',['../page_exahype_boundary_conditions.html',1,'page_exahype2_home']]],
  ['conditions_34',['Conditions',['../page_exahype_boundary_conditions.html#autotoc_md18',1,'Dirichlet boundary conditions'],['../page_exahype_boundary_conditions.html#autotoc_md43',1,'Inflow and outflow conditions'],['../page_exahype_boundary_conditions.html#autotoc_md30',1,'Neumann boundary conditions']]],
  ['conditions_20on_20cartesian_20boxes_35',['Boundary conditions on Cartesian boxes',['../page_exahype_boundary_conditions.html#autotoc_md16',1,'']]],
  ['config_20template_36',['Config template',['../page_continuous_integration.html#autotoc_md130',1,'']]],
  ['configuration_37',['Configuration',['../page_installation_home.html#autotoc_md166',1,'Python Configuration'],['../page_exahype2_tutorials_limiting.html#autotoc_md63',1,'The Configuration'],['../page_exahype2_tutorials_shallow_water.html#autotoc_md59',1,'The Configuration'],['../page_exahype2_tutorials_acoustic.html#autotoc_md39',1,'The Configuration'],['../page_exahype2_tutorials_euler.html#autotoc_md58',1,'The Configuration'],['../page_exahype2_tutorials_elastic.html#autotoc_md142',1,'The Configuration']]],
  ['configurations_20for_20some_20machines_38',['Reference Configurations for Some Machines',['../page_machines_home.html',1,'index']]],
  ['configure_20peano_39',['Configure Peano',['../page_installation_home.html#autotoc_md160',1,'']]],
  ['connecting_20to_20supermuc_20using_20tinyhttpproxy_40',['Connecting to SuperMUC using TinyHTTPProxy',['../page_machines_supermuc.html#autotoc_md137',1,'']]],
  ['considerations_41',['Performance considerations',['../page_peano_amr.html#autotoc_md210',1,'']]],
  ['consistency_42',['Data consistency',['../page_architecture_home.html#autotoc_md64',1,'']]],
  ['consistency_43',['Particle sorting and mesh consistency',['../page_peano4_particles_mesh_consistency.html',1,'page_peano4_particles']]],
  ['consistent_44',['Keeping face and patch data consistent',['../documentation_exahype2_solvers_finite_volumes.html#autotoc_md79',1,'']]],
  ['container_20operations_45',['Container operations',['../page_peano4_particles_realisation_particle_lift_flavours.html#autotoc_md212',1,'']]],
  ['content_46',['Content',['../index.html#autotoc_md146',1,'']]],
  ['continuous_20integration_20ci_47',['Continuous Integration (CI)',['../page_continuous_integration.html',1,'index']]],
  ['continuous_2dintegration_2edox_48',['continuous-integration.dox',['../continuous-integration_8dox.html',1,'']]],
  ['control_20events_49',['Grid control events',['../page_peano_amr.html#autotoc_md186',1,'']]],
  ['control_20flow_50',['SPMD control flow',['../peano_main.html#autotoc_md180',1,'']]],
  ['control_20git_51',['Version Control (Git)',['../page_version_control_home.html',1,'index']]],
  ['conventions_52',['Conventions',['../page_version_control_home.html#autotoc_md260',1,'Naming conventions'],['../page_conventions_home.html#autotoc_md29',1,'Syntax Conventions']]],
  ['conventions_20and_20ides_53',['Coding Conventions and IDEs',['../page_conventions_home.html',1,'index']]],
  ['conventions_20style_20guide_54',['Conventions Style Guide',['../page_conventions_home.html#autotoc_md74',1,'C++ conventions / Style Guide'],['../page_conventions_home.html#autotoc_md42',1,'Python Conventions / Style Guide']]],
  ['conventions_2edox_55',['conventions.dox',['../conventions_8dox.html',1,'']]],
  ['conversion_56',['Offline conversion',['../documentation_tarch_visualisation_offline-conversion.html',1,'documentation_tarch_visualisation']]],
  ['copies_57',['Task-local copies',['../page_peano_localisation.html#autotoc_md176',1,'']]],
  ['copying_58',['Copying',['../page_peano4_particles_realisation_particle_lift_flavours.html#autotoc_md218',1,'']]],
  ['core_59',['C++ core',['../page_faq_home.html#autotoc_md248',1,'']]],
  ['corrector_60',['Corrector',['../page_exahype2_numerics_ADER-DG.html#autotoc_md52',1,'']]],
  ['cost_61',['Kernel cost',['../page_exahype_performance_optimisation.html#autotoc_md22',1,'']]],
  ['critical_20assertions_62',['Non-critical assertions',['../tarch_NonCriticalAssertions.html',1,'page_tarch_home']]]
];
