var searchData=
[
  ['s_20internal_20compiler_20specific_20switches_0',['Realisation of Peano&apos;s internal compiler-specific switches',['../page_compiler_specific_settings_home.html#autotoc_md41',1,'']]],
  ['s_20view_1',['GPU support (programmer&apos;s view)',['../page_exahype_gpu.html#autotoc_md67',1,'']]],
  ['safe_20update_20point_2',['Safe update point',['../page_peano4_particles_mesh_consistency.html#autotoc_md183',1,'']]],
  ['schedule_3',['Two-sweep schedule',['../documentation_exahype2_solvers_aderdg.html#autotoc_md123',1,'']]],
  ['scheme_4',['Scheme',['../documentation_exahype2_solvers_finite_volumes.html#autotoc_md53',1,'Storage scheme'],['../page_tutorials_exahype2_numerics_higher_order_finite_volumes.html#autotoc_md25',1,'The MUSCL-Hancock Scheme']]],
  ['schemes_5',['MUSCL Schemes',['../page_tutorials_exahype2_numerics_higher_order_finite_volumes.html#autotoc_md13',1,'']]],
  ['scope_6',['Scope',['../applications_exahype2_exaskred.html#autotoc_md256',1,'']]],
  ['selection_7',['Level selection',['../page_peano4_particles_mesh_storage.html#autotoc_md190',1,'']]],
  ['semantics_8',['Decision semantics',['../page_exahype_amr.html#autotoc_md7',1,'']]],
  ['sequence_9',['Sorting sequence',['../page_peano4_particles_mesh_consistency.html#autotoc_md182',1,'']]],
  ['series_10',['File writers and time series',['../tarch_plotting.html#autotoc_md254',1,'']]],
  ['set_20order_11',['Action-set order',['../peano_action_sets.html#autotoc_md221',1,'']]],
  ['set_20pattern_12',['Action set pattern',['../tarch_plotting.html#autotoc_md253',1,'']]],
  ['set_20storage_13',['Particle-set storage',['../page_peano4_particles_realisation_particle_lift_flavours.html',1,'page_peano4_particles_realisation']]],
  ['sets_14',['Local and active sets',['../page_peano4_particles_mesh_traversal.html#autotoc_md193',1,'']]],
  ['sets_15',['Particle interaction sets',['../page_peano4_particles_mesh_traversal.html',1,'page_peano4_particles']]],
  ['sets_20and_20traversal_20events_16',['Action sets and traversal events',['../peano_action_sets.html',1,'page_peano4_home']]],
  ['settings_17',['Settings',['../page_compiler_specific_settings_home.html',1,'Vendor Software Stacks and System- and Compiler-specific Settings'],['../page_compiler_specific_settings_home.html#autotoc_md47',1,'Vendor toolchains and compiler settings']]],
  ['shallow_20water_20equations_18',['Shallow Water Equations',['../page_exahype2_tutorials_shallow_water.html',1,'Part 2 - The Shallow Water Equations'],['../page_exahype2_tutorials_shallow_water.html#autotoc_md15',1,'The Shallow Water Equations']]],
  ['shear_20wave_19',['Exercise - Launch a Shear Wave',['../page_exahype2_tutorials_elastic.html#autotoc_md149',1,'']]],
  ['sheet_20',['Doxygen cheat sheet',['../page_documentation_home.html#autotoc_md102',1,'']]],
  ['shock_20with_20a_20posteriori_20limiting_21',['Part 4 - A 2D Euler Shock with a-posteriori Limiting',['../page_exahype2_tutorials_limiting.html',1,'page_exahype2_tutorials']]],
  ['sieve_22',['Sieve',['../page_peano4_particles_mesh_consistency.html#autotoc_md195',1,'']]],
  ['snippets_23',['Snippets',['../page_documentation_home.html#autotoc_md113',1,'Code snippets'],['../page_documentation_home.html#autotoc_md120',1,'Links to existing code snippets']]],
  ['software_20environment_20and_20modules_24',['Software Environment and Modules',['../page_machines_supermuc.html#autotoc_md139',1,'Software Environment and Modules'],['../page_machines_lumi.html#autotoc_md159',1,'Software Environment and Modules']]],
  ['software_20stacks_20and_20system_20and_20compiler_20specific_20settings_25',['Vendor Software Stacks and System- and Compiler-specific Settings',['../page_compiler_specific_settings_home.html',1,'index']]],
  ['solution_20output_26',['Solution output',['../page_exahype_visualisation.html#autotoc_md132',1,'']]],
  ['solution_20to_20exercise_201_27',['Part 2 - Solution to Exercise 1',['../page_exahype2_tutorials_shallow_water_solution.html',1,'page_exahype2_tutorials_shallow_water']]],
  ['solution_20to_20exercise_202_28',['Part 2 - Solution to Exercise 2',['../page_exahype2_tutorials_shallow_water_solution_2.html',1,'page_exahype2_tutorials_shallow_water']]],
  ['solutions_29',['Rendering and comparing solutions',['../page_exahype_runtime_analysis.html#autotoc_md12',1,'']]],
  ['solver_30',['Finite Volume solver',['../documentation_exahype2_solvers_finite_volumes.html',1,'page_solvers']]],
  ['solver_20and_20kernel_20parallelism_31',['Solver and kernel parallelism',['../page_peano_performance_optimisation.html#autotoc_md242',1,'']]],
  ['solver_20data_32',['Solver data',['../page_exahype_tracer.html#autotoc_md20',1,'Projecting solver data'],['../page_exahype_domain-decomposition.html#autotoc_md5',1,'Solver data']]],
  ['solver_20data_20transfer_33',['Solver data transfer',['../page_exahype_amr.html#autotoc_md72',1,'']]],
  ['solver_20specific_20rendering_20recommendations_34',['Solver-specific rendering recommendations',['../page_exahype_visualisation.html#autotoc_md133',1,'']]],
  ['solver_20state_35',['Solver state',['../page_exahype_domain-decomposition.html#autotoc_md11',1,'']]],
  ['solver_20tasks_36',['Solver tasks',['../page_exahype_multicore.html#autotoc_md4',1,'Solver tasks'],['../page_exahype_performance_optimisation.html#autotoc_md36',1,'Solver tasks']]],
  ['solvers_37',['ADER-DG solvers',['../documentation_exahype2_solvers_aderdg.html',1,'page_solvers']]],
  ['solvers_38',['Solvers',['../page_solvers.html',1,'page_exahype2_home']]],
  ['some_20machines_39',['Reference Configurations for Some Machines',['../page_machines_home.html',1,'index']]],
  ['sorting_40',['Movement and sorting',['../page_peano4_particles_mesh_traversal.html#autotoc_md207',1,'']]],
  ['sorting_20and_20mesh_20consistency_41',['Particle sorting and mesh consistency',['../page_peano4_particles_mesh_consistency.html',1,'page_peano4_particles']]],
  ['sorting_20sequence_42',['Sorting sequence',['../page_peano4_particles_mesh_consistency.html#autotoc_md182',1,'']]],
  ['source_20no_20docker_43',['Option B: Build from Source (No Docker)',['../page_exahype2_tutorials.html#autotoc_md157',1,'']]],
  ['spack_44',['Installation with Spack',['../page_installation_with_spack.html',1,'page_installation_with_environments']]],
  ['specific_20rendering_20recommendations_45',['Solver-specific rendering recommendations',['../page_exahype_visualisation.html#autotoc_md133',1,'']]],
  ['specific_20settings_46',['Vendor Software Stacks and System- and Compiler-specific Settings',['../page_compiler_specific_settings_home.html',1,'index']]],
  ['specific_20switches_47',['Realisation of Peano&apos;s internal compiler-specific switches',['../page_compiler_specific_settings_home.html#autotoc_md41',1,'']]],
  ['spmd_20control_20flow_48',['SPMD control flow',['../peano_main.html#autotoc_md180',1,'']]],
  ['stack_49',['Large generated records exhaust the thread stack',['../page_exahype_faq.html#autotoc_md0',1,'']]],
  ['stacks_20and_20system_20and_20compiler_20specific_20settings_50',['Vendor Software Stacks and System- and Compiler-specific Settings',['../page_compiler_specific_settings_home.html',1,'index']]],
  ['standing_20sweep_20replay_51',['Standing-sweep replay',['../page_peano_performance_optimisation.html#autotoc_md233',1,'']]],
  ['start_52',['Quick Start',['../page_exahype2_tutorials.html#autotoc_md147',1,'']]],
  ['started_53',['Getting Started',['../page_installation_with_spack.html#autotoc_md271',1,'']]],
  ['state_54',['State',['../page_exahype_gpu.html#autotoc_md88',1,'Provide the additional PDE terms without state'],['../page_peano_domain_decomposition.html#autotoc_md213',1,'Rank-wide application state'],['../page_exahype_domain-decomposition.html#autotoc_md11',1,'Solver state']]],
  ['stateless_20compute_20kernels_55',['Enable stateless compute kernels',['../page_exahype_gpu.html#autotoc_md80',1,'']]],
  ['static_20refinement_56',['Exercise 2 - Bathymetry and Static Refinement',['../page_exahype2_tutorials_shallow_water.html#autotoc_md75',1,'']]],
  ['steps_57',['Steps',['../page_architecture_home.html#autotoc_md21',1,'Program steps'],['../peano_main.html#autotoc_md178',1,'Registered steps']]],
  ['storage_58',['storage',['../page_peano4_particles_mesh_storage.html',1,'Multiscale particle storage'],['../page_peano4_particles_realisation_particle_lift_flavours.html',1,'Particle-set storage']]],
  ['storage_20and_20exchange_59',['Particle storage and exchange',['../page_peano4_particles_realisation.html',1,'page_peano4_particles']]],
  ['storage_20and_20exchange_60',['Persistent storage and exchange',['../page_peano4_particles_realisation_particle_lift_flavours.html#autotoc_md214',1,'']]],
  ['storage_20predicates_61',['Storage predicates',['../page_peano_localisation.html#autotoc_md175',1,'']]],
  ['storage_20scheme_62',['Storage scheme',['../documentation_exahype2_solvers_finite_volumes.html#autotoc_md53',1,'']]],
  ['structural_20model_63',['Structural model',['../page_peano_domain_decomposition.html#autotoc_md188',1,'']]],
  ['structured_20patch_20operations_64',['Block-structured patch operations',['../page_exahype2_blockstructured.html',1,'page_exahype2_home']]],
  ['structures_65',['Data structures',['../documentation_exahype2_solvers_finite_volumes.html#autotoc_md69',1,'']]],
  ['style_20guide_66',['Style Guide',['../page_conventions_home.html#autotoc_md74',1,'C++ conventions / Style Guide'],['../page_conventions_home.html#autotoc_md42',1,'Python Conventions / Style Guide']]],
  ['subbranches_67',['Popular subbranches',['../page_version_control_home.html#autotoc_md264',1,'']]],
  ['subpages_68',['New (high-level) subpages',['../page_documentation_home.html#autotoc_md78',1,'']]],
  ['suitability_69',['Assess suitability',['../page_exahype_gpu.html#autotoc_md70',1,'']]],
  ['supermuc_70',['SuperMUC',['../page_machines_supermuc.html',1,'page_machines_home']]],
  ['supermuc_20ng_20phase_202_71',['SuperMUC-NG Phase 2',['../page_machines_supermuc.html#autotoc_md138',1,'']]],
  ['supermuc_20using_20tinyhttpproxy_72',['Connecting to SuperMUC using TinyHTTPProxy',['../page_machines_supermuc.html#autotoc_md137',1,'']]],
  ['supermuc_2edox_73',['supermuc.dox',['../supermuc_8dox.html',1,'']]],
  ['support_74',['GPU support',['../page_exahype_gpu.html',1,'page_exahype2_home']]],
  ['support_75',['Logging Devices, Formats, Backends And Profiling Support',['../tarch_logging.html#tarch_logging_backends',1,'']]],
  ['support_76',['SYCL support',['../tarch_accelerator_SYCL.html',1,'page_tarch_home']]],
  ['support_77',['Support',['../page_exahype_gpu.html#autotoc_md60',1,'Using ExaHyPE with GPU support'],['../page_installation_with_apptainer.html#autotoc_md267',1,'With GPU Support'],['../page_installation_with_docker.html#autotoc_md278',1,'With GPU Support']]],
  ['support_20programmer_20s_20view_78',['GPU support (programmer&apos;s view)',['../page_exahype_gpu.html#autotoc_md67',1,'']]],
  ['sweep_20lifecycle_79',['Sweep lifecycle',['../page_peano_amr.html#autotoc_md197',1,'']]],
  ['sweep_20replay_80',['Standing-sweep replay',['../page_peano_performance_optimisation.html#autotoc_md233',1,'']]],
  ['sweep_20schedule_81',['Two-sweep schedule',['../documentation_exahype2_solvers_aderdg.html#autotoc_md123',1,'']]],
  ['switches_82',['Realisation of Peano&apos;s internal compiler-specific switches',['../page_compiler_specific_settings_home.html#autotoc_md41',1,'']]],
  ['sycl_20and_20sycl_20offloading_83',['SYCL and SYCL offloading',['../page_compiler_specific_settings_home.html#autotoc_md101',1,'']]],
  ['sycl_20offloading_20with_20oneapi_84',['SYCL offloading with oneAPI',['../page_machines_ncc.html#autotoc_md174',1,'']]],
  ['sycl_20support_85',['SYCL support',['../tarch_accelerator_SYCL.html',1,'page_tarch_home']]],
  ['sycl_2edox_86',['sycl.dox',['../sycl_8dox.html',1,'']]],
  ['synchronisation_87',['Synchronisation',['../page_tarch_mpi.html#autotoc_md243',1,'Synchronisation'],['../page_tarch_tasking.html#autotoc_md252',1,'Synchronisation']]],
  ['syntax_20conventions_88',['Syntax Conventions',['../page_conventions_home.html#autotoc_md29',1,'']]],
  ['system_20and_20compiler_20specific_20settings_89',['Vendor Software Stacks and System- and Compiler-specific Settings',['../page_compiler_specific_settings_home.html',1,'index']]]
];
