var searchData=
[
  ['a_202d_20euler_20shock_20with_20a_20posteriori_20limiting_0',['Part 4 - A 2D Euler Shock with a-posteriori Limiting',['../page_exahype2_tutorials_limiting.html',1,'page_exahype2_tutorials']]],
  ['a_20dam_20break_1',['Exercise 1 - A Dam Break',['../page_exahype2_tutorials_shallow_water.html#autotoc_md71',1,'']]],
  ['a_20fit_2',['Mask out cells which are not a fit',['../page_exahype_gpu.html#autotoc_md107',1,'']]],
  ['a_20limiter_3',['Why a Limiter',['../page_exahype2_tutorials_limiting.html#autotoc_md45',1,'']]],
  ['a_20particle_20once_4',['Updating a particle once',['../page_peano4_particles_mesh_traversal.html#autotoc_md196',1,'']]],
  ['a_20posteriori_20limiting_5',['Part 4 - A 2D Euler Shock with a-posteriori Limiting',['../page_exahype2_tutorials_limiting.html',1,'page_exahype2_tutorials']]],
  ['a_20shear_20wave_6',['Exercise - Launch a Shear Wave',['../page_exahype2_tutorials_elastic.html#autotoc_md149',1,'']]],
  ['a_20taste_20of_20hpc_7',['A Taste of HPC',['../page_exahype2_tutorials_elastic.html#autotoc_md145',1,'']]],
  ['a_20taste_20of_20hpc_8',['Part 5 - 3D Elastic Waves and a Taste of HPC',['../page_exahype2_tutorials_elastic.html',1,'page_exahype2_tutorials']]],
  ['a_20test_9',['Anatomy of a test',['../page_continuous_integration.html#autotoc_md128',1,'']]],
  ['a_20tracer_10',['Adding a tracer',['../page_exahype_tracer.html#autotoc_md17',1,'']]],
  ['a_3a_20the_20tutorials_20docker_20image_20recommended_11',['Option A: The Tutorials Docker Image (Recommended)',['../page_exahype2_tutorials.html#autotoc_md155',1,'']]],
  ['access_12',['Data access',['../page_exahype_performance_optimisation.html#autotoc_md8',1,'']]],
  ['acoustic_20equations_13',['Acoustic Equations',['../page_exahype2_tutorials_acoustic.html',1,'Part 1 - The Acoustic Equations'],['../page_exahype2_tutorials_acoustic.html#autotoc_md35',1,'The Acoustic Equations']]],
  ['action_20set_20order_14',['Action-set order',['../peano_action_sets.html#autotoc_md221',1,'']]],
  ['action_20set_20pattern_15',['Action set pattern',['../tarch_plotting.html#autotoc_md253',1,'']]],
  ['action_20sets_20and_20traversal_20events_16',['Action sets and traversal events',['../peano_action_sets.html',1,'page_peano4_home']]],
  ['action_5fsets_2edox_17',['action_sets.dox',['../action__sets_8dox.html',1,'']]],
  ['active_20sets_18',['Local and active sets',['../page_peano4_particles_mesh_traversal.html#autotoc_md193',1,'']]],
  ['adaptive_20interfaces_19',['Adaptive interfaces',['../documentation_exahype2_solvers_aderdg.html#autotoc_md124',1,'']]],
  ['adaptive_20levels_20',['Enabling adaptive levels',['../page_exahype_amr.html#autotoc_md3',1,'']]],
  ['adaptive_20mesh_20refinement_21',['Adaptive mesh refinement',['../page_exahype_amr.html',1,'Adaptive mesh refinement'],['../page_peano_amr.html',1,'Adaptive mesh refinement'],['../page_peano_performance_optimisation.html#autotoc_md239',1,'Adaptive mesh refinement']]],
  ['adaptive_20ownership_22',['Adaptive ownership',['../page_exahype_domain-decomposition.html#autotoc_md40',1,'']]],
  ['adaptive_20runs_23',['Adaptive runs',['../page_exahype_performance_optimisation.html#autotoc_md61',1,'']]],
  ['add_20new_20files_24',['How to add new files',['../page_documentation_home.html#autotoc_md54',1,'']]],
  ['add_20new_20runners_20to_20project_25',['How do I add new runners to project?',['../page_continuous_integration.html#autotoc_md129',1,'']]],
  ['adding_20a_20tracer_26',['Adding a tracer',['../page_exahype_tracer.html#autotoc_md17',1,'']]],
  ['adding_20low_20level_20documentation_20inside_20the_20code_27',['Adding (low-level) documentation inside the code',['../page_documentation_home.html#autotoc_md86',1,'']]],
  ['adding_20the_20python_20path_28',['Manually Adding the Python Path',['../page_installation_home.html#autotoc_md168',1,'']]],
  ['additional_20pde_20terms_20without_20state_29',['Provide the additional PDE terms without state',['../page_exahype_gpu.html#autotoc_md88',1,'']]],
  ['ader_20dg_30',['ADER-DG',['../page_exahype2_numerics_ADER-DG.html',1,'page_numerics']]],
  ['ader_20dg_20solvers_31',['ADER-DG solvers',['../documentation_exahype2_solvers_aderdg.html',1,'page_solvers']]],
  ['ader_2ddg_2edox_32',['ader-dg.dox',['../numerics_2ader-dg_8dox.html',1,'(Global Namespace)'],['../solvers_2ader-dg_8dox.html',1,'(Global Namespace)']]],
  ['advanced_20techniques_33',['Advanced techniques',['../page_exahype_gpu.html#autotoc_md104',1,'']]],
  ['airfoil_34',['Part 3 - The Euler Equations over an Airfoil',['../page_exahype2_tutorials_euler.html',1,'page_exahype2_tutorials']]],
  ['allocation_35',['Particle allocation',['../page_peano4_particles_realisation_particle_lift_flavours.html#autotoc_md206',1,'']]],
  ['amd_36',['AMD',['../page_compiler_specific_settings_home.html#autotoc_md114',1,'']]],
  ['amr_2edox_37',['amr.dox',['../exahype2_2amr_8dox.html',1,'(Global Namespace)'],['../peano4_2amr_8dox.html',1,'(Global Namespace)']]],
  ['an_20airfoil_38',['Part 3 - The Euler Equations over an Airfoil',['../page_exahype2_tutorials_euler.html',1,'page_exahype2_tutorials']]],
  ['analysis_39',['Analysis',['../page_peano_domain_decomposition.html#autotoc_md215',1,'Analysis'],['../page_peano_performance_optimisation.html#autotoc_md244',1,'MPI analysis'],['../page_faq_home.html#autotoc_md245',1,'Performance analysis']]],
  ['analysis_40',['analysis',['../page_exahype_runtime_analysis.html',1,'Runtime analysis'],['../page_peano_runtime_analysis.html',1,'Runtime analysis']]],
  ['anatomy_20of_20a_20test_41',['Anatomy of a test',['../page_continuous_integration.html#autotoc_md128',1,'']]],
  ['and_20a_20taste_20of_20hpc_42',['Part 5 - 3D Elastic Waves and a Taste of HPC',['../page_exahype2_tutorials_elastic.html',1,'page_exahype2_tutorials']]],
  ['and_20active_20sets_43',['Local and active sets',['../page_peano4_particles_mesh_traversal.html#autotoc_md193',1,'']]],
  ['and_20assertion_20architecture_44',['Logging And Assertion Architecture',['../tarch_logging.html#tarch_logging_architecture',1,'']]],
  ['and_20assertions_45',['Logging, profiling and assertions',['../tarch_logging.html',1,'page_tarch_home']]],
  ['and_20check_46',['Compile, run and check',['../page_exahype_gpu.html#autotoc_md96',1,'']]],
  ['and_20comparing_20solutions_47',['Rendering and comparing solutions',['../page_exahype_runtime_analysis.html#autotoc_md12',1,'']]],
  ['and_20compiler_20settings_48',['Vendor toolchains and compiler settings',['../page_compiler_specific_settings_home.html#autotoc_md47',1,'']]],
  ['and_20data_49',['Markers and data',['../peano_action_sets.html#autotoc_md219',1,'']]],
  ['and_20data_20pools_50',['Grid representation and data pools',['../page_architecture_home.html#autotoc_md24',1,'']]],
  ['and_20exchange_51',['Particle storage and exchange',['../page_peano4_particles_realisation.html',1,'page_peano4_particles']]],
  ['and_20exchange_52',['Persistent storage and exchange',['../page_peano4_particles_realisation_particle_lift_flavours.html#autotoc_md214',1,'']]],
  ['and_20ides_53',['Coding Conventions and IDEs',['../page_conventions_home.html',1,'index']]],
  ['and_20kernel_20parallelism_54',['Solver and kernel parallelism',['../page_peano_performance_optimisation.html#autotoc_md242',1,'']]],
  ['and_20mesh_20consistency_55',['Particle sorting and mesh consistency',['../page_peano4_particles_mesh_consistency.html',1,'page_peano4_particles']]],
  ['and_20migration_56',['Regridding and migration',['../page_peano_domain_decomposition.html#autotoc_md208',1,'']]],
  ['and_20modules_57',['And Modules',['../page_machines_supermuc.html#autotoc_md139',1,'Software Environment and Modules'],['../page_machines_lumi.html#autotoc_md159',1,'Software Environment and Modules']]],
  ['and_20netcdf_58',['HDF5 and NetCDF',['../page_third-party_hdf5.html',1,'page_third_party_home']]],
  ['and_20openmp_20offloading_59',['And OpenMP offloading',['../page_compiler_specific_settings_home.html#autotoc_md82',1,'OpenMP and OpenMP offloading'],['../page_compiler_specific_settings_home.html#autotoc_md98',1,'OpenMP and OpenMP offloading'],['../page_compiler_specific_settings_home.html#autotoc_md112',1,'OpenMP and OpenMP offloading'],['../page_compiler_specific_settings_home.html#autotoc_md116',1,'OpenMP and OpenMP offloading']]],
  ['and_20outflow_20conditions_60',['Inflow and outflow conditions',['../page_exahype_boundary_conditions.html#autotoc_md43',1,'']]],
  ['and_20output_61',['Visualisation and output',['../page_exahype_visualisation.html',1,'page_exahype2_home']]],
  ['and_20packages_62',['Prebuilt Environments and Packages',['../page_installation_home.html#autotoc_md170',1,'']]],
  ['and_20patch_20data_20consistent_63',['Keeping face and patch data consistent',['../documentation_exahype2_solvers_finite_volumes.html#autotoc_md79',1,'']]],
  ['and_20prerequisites_64',['Dependencies and Prerequisites',['../page_installation_home.html#autotoc_md150',1,'']]],
  ['and_20probe_20data_65',['Error norms and probe data',['../page_exahype_runtime_analysis.html#autotoc_md9',1,'']]],
  ['and_20profiling_20support_66',['Logging Devices, Formats, Backends And Profiling Support',['../tarch_logging.html#tarch_logging_backends',1,'']]],
  ['and_20replication_20overhead_67',['Boundary and replication overhead',['../page_peano_performance_optimisation.html#autotoc_md228',1,'']]],
  ['and_20running_68',['And Running',['../page_machines_supermuc.html#autotoc_md140',1,'Building and Running'],['../page_machines_lumi.html#autotoc_md161',1,'Building and Running']]],
  ['and_20sorting_69',['Movement and sorting',['../page_peano4_particles_mesh_traversal.html#autotoc_md207',1,'']]],
  ['and_20static_20refinement_70',['Exercise 2 - Bathymetry and Static Refinement',['../page_exahype2_tutorials_shallow_water.html#autotoc_md75',1,'']]],
  ['and_20sycl_20offloading_71',['SYCL and SYCL offloading',['../page_compiler_specific_settings_home.html#autotoc_md101',1,'']]],
  ['and_20system_20and_20compiler_20specific_20settings_72',['Vendor Software Stacks and System- and Compiler-specific Settings',['../page_compiler_specific_settings_home.html',1,'index']]],
  ['and_20time_20series_73',['File writers and time series',['../tarch_plotting.html#autotoc_md254',1,'']]],
  ['and_20tracing_74',['Build modes and tracing',['../page_compiler_specific_settings_home.html#autotoc_md95',1,'']]],
  ['and_20traversal_20events_75',['Action sets and traversal events',['../peano_action_sets.html',1,'page_peano4_home']]],
  ['and_20troubleshooting_76',['FAQ and troubleshooting',['../page_exahype_faq.html',1,'page_exahype2_home']]],
  ['and_20troubleshooting_20user_20perspective_77',['FAQs and Troubleshooting (User Perspective)',['../page_faq_home.html',1,'index']]],
  ['and_20visualising_78',['And Visualising',['../page_exahype2_tutorials_limiting.html#autotoc_md83',1,'Running and Visualising'],['../page_exahype2_tutorials_acoustic.html#autotoc_md55',1,'Running and Visualising'],['../page_exahype2_tutorials_euler.html#autotoc_md85',1,'Running and Visualising']]],
  ['and_20visualising_20in_203d_79',['Running and Visualising in 3D',['../page_exahype2_tutorials_elastic.html#autotoc_md144',1,'']]],
  ['api_80',['API',['../page_architecture_home.html#autotoc_md84',1,'Python API'],['../peano_main.html#autotoc_md181',1,'Python API'],['../page_faq_home.html#autotoc_md240',1,'Python API']]],
  ['application_20state_81',['Rank-wide application state',['../page_peano_domain_decomposition.html#autotoc_md213',1,'']]],
  ['applications_82',['Applications',['../page_exahype_applications.html',1,'page_exahype2_home']]],
  ['applications_2edox_83',['applications.dox',['../applications_8dox.html',1,'']]],
  ['apptainer_84',['Installation with Apptainer',['../page_installation_with_apptainer.html',1,'page_installation_with_environments']]],
  ['architecture_85',['Architecture',['../page_architecture_home.html',1,'Architecture'],['../tarch_logging.html#tarch_logging_architecture',1,'Logging And Assertion Architecture'],['../page_architecture_home.html#autotoc_md14',1,'Runtime architecture'],['../tarch_tests.html#autotoc_md257',1,'Test architecture']]],
  ['architecture_20tarch_86',['Technical Architecture (tarch)',['../page_tarch_home.html',1,'index']]],
  ['architecture_2edox_87',['architecture.dox',['../architecture_8dox.html',1,'']]],
  ['are_20not_20a_20fit_88',['Mask out cells which are not a fit',['../page_exahype_gpu.html#autotoc_md107',1,'']]],
  ['assertion_20architecture_89',['Logging And Assertion Architecture',['../tarch_logging.html#tarch_logging_architecture',1,'']]],
  ['assertions_90',['Assertions',['../tarch_logging.html#tarch_logging_assertions',1,'']]],
  ['assertions_91',['assertions',['../tarch_logging.html',1,'Logging, profiling and assertions'],['../tarch_NonCriticalAssertions.html',1,'Non-critical assertions']]],
  ['assess_20suitability_92',['Assess suitability',['../page_exahype_gpu.html#autotoc_md70',1,'']]],
  ['augment_20patch_20with_20halo_93',['Augment patch with halo',['../documentation_exahype2_solvers_finite_volumes.html#autotoc_md81',1,'']]]
];
