var searchData=
[
  ['rank_20decomposition_0',['Rank decomposition',['../page_peano_runtime_analysis.html#autotoc_md234',1,'Inter-rank decomposition'],['../page_peano_runtime_analysis.html#autotoc_md235',1,'Intra-rank decomposition']]],
  ['rank_20imbalance_1',['Rank imbalance',['../page_peano_performance_optimisation.html#autotoc_md225',1,'Inter-rank imbalance'],['../page_peano_performance_optimisation.html#autotoc_md226',1,'Intra-rank imbalance']]],
  ['rank_20local_20pools_2',['Rank-local pools',['../page_peano_localisation.html#autotoc_md173',1,'']]],
  ['rank_20ownership_3',['Rank ownership',['../page_peano4_particles_mesh_storage.html#autotoc_md202',1,'']]],
  ['rank_20partition_4',['Inter-rank partition',['../page_peano_domain_decomposition.html#autotoc_md191',1,'']]],
  ['rank_20task_20decomposition_5',['Intra-rank task decomposition',['../page_peano_domain_decomposition.html#autotoc_md194',1,'']]],
  ['rank_20wide_20application_20state_6',['Rank-wide application state',['../page_peano_domain_decomposition.html#autotoc_md213',1,'']]],
  ['rationale_7',['Rationale',['../page_documentation_home.html#autotoc_md51',1,'']]],
  ['reading_8',['Further reading',['../page_exahype_gpu.html#autotoc_md110',1,'']]],
  ['readme_2edox_9',['README.dox',['../applications_2exagrype_2README_8dox.html',1,'(Global Namespace)'],['../applications_2exaseis_2cartesian_2README_8dox.html',1,'(Global Namespace)'],['../applications_2exaseis_2README_8dox.html',1,'(Global Namespace)'],['../applications_2exaskred_2README_8dox.html',1,'(Global Namespace)'],['../utilities_2apptainer_2README_8dox.html',1,'(Global Namespace)'],['../utilities_2docker_2README_8dox.html',1,'(Global Namespace)'],['../utilities_2README_8dox.html',1,'(Global Namespace)'],['../utilities_2spack_2README_8dox.html',1,'(Global Namespace)']]],
  ['realisation_20of_20peano_20s_20internal_20compiler_20specific_20switches_10',['Realisation of Peano&apos;s internal compiler-specific switches',['../page_compiler_specific_settings_home.html#autotoc_md41',1,'']]],
  ['recent_20updates_11',['Recent Updates',['../index.html#autotoc_md148',1,'']]],
  ['recommendations_12',['Solver-specific rendering recommendations',['../page_exahype_visualisation.html#autotoc_md133',1,'']]],
  ['recommended_13',['Option A: The Tutorials Docker Image (Recommended)',['../page_exahype2_tutorials.html#autotoc_md155',1,'']]],
  ['records_20exhaust_20the_20thread_20stack_14',['Large generated records exhaust the thread stack',['../page_exahype_faq.html#autotoc_md0',1,'']]],
  ['reference_20configurations_20for_20some_20machines_15',['Reference Configurations for Some Machines',['../page_machines_home.html',1,'index']]],
  ['reference_20papers_16',['Reference papers',['../applications_exahype2_exaseis.html#autotoc_md268',1,'']]],
  ['refinement_17',['refinement',['../page_exahype_amr.html',1,'Adaptive mesh refinement'],['../page_peano_amr.html',1,'Adaptive mesh refinement']]],
  ['refinement_18',['Refinement',['../page_peano_performance_optimisation.html#autotoc_md239',1,'Adaptive mesh refinement'],['../page_exahype2_tutorials_shallow_water.html#autotoc_md75',1,'Exercise 2 - Bathymetry and Static Refinement']]],
  ['refinement_20plan_20evaluation_19',['Refinement-plan evaluation',['../page_peano_amr.html#autotoc_md192',1,'']]],
  ['registered_20steps_20',['Registered steps',['../peano_main.html#autotoc_md178',1,'']]],
  ['regrid_20drains_21',['Regrid drains',['../page_exahype_amr.html#autotoc_md49',1,'']]],
  ['regridding_22',['Regridding',['../page_architecture_home.html#autotoc_md66',1,'Regridding'],['../page_peano_runtime_analysis.html#autotoc_md237',1,'Regridding']]],
  ['regridding_20and_20migration_23',['Regridding and migration',['../page_peano_domain_decomposition.html#autotoc_md208',1,'']]],
  ['remarks_24',['Historical remarks',['../page_exahype2_home.html#autotoc_md32',1,'']]],
  ['remove_20the_20repository_25',['Remove the Repository',['../page_installation_with_spack.html#autotoc_md275',1,'']]],
  ['rendering_20and_20comparing_20solutions_26',['Rendering and comparing solutions',['../page_exahype_runtime_analysis.html#autotoc_md12',1,'']]],
  ['rendering_20recommendations_27',['Solver-specific rendering recommendations',['../page_exahype_visualisation.html#autotoc_md133',1,'']]],
  ['replay_28',['Standing-sweep replay',['../page_peano_performance_optimisation.html#autotoc_md233',1,'']]],
  ['replication_20overhead_29',['Boundary and replication overhead',['../page_peano_performance_optimisation.html#autotoc_md228',1,'']]],
  ['repository_30',['Remove the Repository',['../page_installation_with_spack.html#autotoc_md275',1,'']]],
  ['repository_20organisation_31',['Repository organisation',['../page_architecture_home.html#autotoc_md89',1,'']]],
  ['representation_20and_20data_20pools_32',['Grid representation and data pools',['../page_architecture_home.html#autotoc_md24',1,'']]],
  ['requests_33',['Requests',['../page_exahype_amr.html#autotoc_md46',1,'Distributed requests'],['../page_peano_amr.html#autotoc_md200',1,'Producing requests']]],
  ['required_34',['Required',['../page_installation_home.html#autotoc_md154',1,'']]],
  ['routine_35',['The generated main routine',['../peano_main.html',1,'page_peano4_home']]],
  ['routines_36',['Test routines',['../tarch_tests.html#autotoc_md261',1,'']]],
  ['run_20and_20check_37',['Compile, run and check',['../page_exahype_gpu.html#autotoc_md96',1,'']]],
  ['run_20the_20pipeline_38',['How do I run the pipeline?',['../page_continuous_integration.html#autotoc_md126',1,'']]],
  ['runge_20kutta_39',['Runge-Kutta',['../page_exahype2_numerics_Runge-Kutta.html',1,'page_numerics']]],
  ['runge_2dkutta_2edox_40',['Runge-Kutta.dox',['../Runge-Kutta_8dox.html',1,'']]],
  ['runners_20to_20project_41',['How do I add new runners to project?',['../page_continuous_integration.html#autotoc_md129',1,'']]],
  ['running_42',['Running',['../page_machines_supermuc.html#autotoc_md140',1,'Building and Running'],['../page_machines_lumi.html#autotoc_md161',1,'Building and Running']]],
  ['running_20and_20visualising_43',['Running and Visualising',['../page_exahype2_tutorials_limiting.html#autotoc_md83',1,'Running and Visualising'],['../page_exahype2_tutorials_acoustic.html#autotoc_md55',1,'Running and Visualising'],['../page_exahype2_tutorials_euler.html#autotoc_md85',1,'Running and Visualising']]],
  ['running_20and_20visualising_20in_203d_44',['Running and Visualising in 3D',['../page_exahype2_tutorials_elastic.html#autotoc_md144',1,'']]],
  ['running_20the_20tests_45',['Running the tests',['../tarch_tests.html#autotoc_md259',1,'']]],
  ['runs_46',['Runs',['../page_exahype_performance_optimisation.html#autotoc_md61',1,'Adaptive runs'],['../page_exahype_performance_optimisation.html#autotoc_md38',1,'Hybrid runs']]],
  ['runtime_47',['Runtime',['../page_tarch_tasking.html#autotoc_md250',1,'Runtime'],['../page_faq_home.html#autotoc_md231',1,'Runtime']]],
  ['runtime_20analysis_48',['Runtime analysis',['../page_exahype_runtime_analysis.html',1,'Runtime analysis'],['../page_peano_runtime_analysis.html',1,'Runtime analysis']]],
  ['runtime_20architecture_49',['Runtime architecture',['../page_architecture_home.html#autotoc_md14',1,'']]],
  ['runtime_5fanalysis_2edox_50',['runtime_analysis.dox',['../exahype2_2runtime__analysis_8dox.html',1,'(Global Namespace)'],['../peano4_2runtime__analysis_8dox.html',1,'(Global Namespace)']]],
  ['rusanov_20flux_51',['Rusanov flux',['../page_exahype2_numerics_fv.html#autotoc_md26',1,'']]]
];
