var searchData=
[
  ['radial_2ddam_2dbreak_2epy_0',['radial-dam-break.py',['../da/d00/radial-dam-break_8py.html',1,'']]],
  ['rank_2ecpp_1',['Rank.cpp',['../d5/dcd/Rank_8cpp.html',1,'']]],
  ['rank_2eh_2',['Rank.h',['../df/df3/Rank_8h.html',1,'']]],
  ['readme_2edox_3',['Readme.dox',['../d5/d78/benchmarks_2swift2_2hydro_2kernel-throughput_2Readme_8dox.html',1,'(Global Namespace)'],['../d0/d60/tests_2multigrid_2matrixfree_2poisson_2Readme_8dox.html',1,'(Global Namespace)']]],
  ['readme_2edox_4',['README.dox',['../d7/dd9/applications_2exahype2_2ccz4_2README_8dox.html',1,'(Global Namespace)'],['../db/de8/applications_2exahype2_2exaseis_2cartesian_2README_8dox.html',1,'(Global Namespace)'],['../d3/d47/applications_2exahype2_2exaseis_2README_8dox.html',1,'(Global Namespace)'],['../df/d7c/applications_2exahype2_2navier-stokes_2breaking-dam_2README_8dox.html',1,'(Global Namespace)'],['../d1/d9a/applications_2exahype2_2navier-stokes_2gaussian-explosion_2README_8dox.html',1,'(Global Namespace)'],['../d7/d93/applications_2exahype2_2navier-stokes_2point-explosion_2README_8dox.html',1,'(Global Namespace)'],['../d2/dda/applications_2exahype2_2navier-stokes_2README_8dox.html',1,'(Global Namespace)'],['../d6/dae/applications_2exahype2_2shallow-water_2artificial-tsunami_2README_8dox.html',1,'(Global Namespace)'],['../d9/d3b/applications_2exahype2_2shallow-water_2chile-tsunami_2README_8dox.html',1,'(Global Namespace)'],['../d6/d67/applications_2exahype2_2shallow-water_2circular-island_2README_8dox.html',1,'(Global Namespace)'],['../df/d58/applications_2exahype2_2shallow-water_2dam-break-landslide_2README_8dox.html',1,'(Global Namespace)'],['../dc/de7/applications_2exahype2_2shallow-water_2oscillating-lake_2README_8dox.html',1,'(Global Namespace)'],['../da/d96/applications_2exahype2_2shallow-water_2radial-dam-break_2README_8dox.html',1,'(Global Namespace)'],['../dd/d37/applications_2exahype2_2shallow-water_2README_8dox.html',1,'(Global Namespace)'],['../d7/da8/applications_2exahype2_2shallow-water_2tafjord-landslide_2README_8dox.html',1,'(Global Namespace)'],['../de/dc7/applications_2exahype2_2shallow-water_2three-mounds-channel_2README_8dox.html',1,'(Global Namespace)'],['../d5/de0/applications_2exahype2_2shallow-water_2tohoku-tsunami_2README_8dox.html',1,'(Global Namespace)'],['../df/d5e/apptainer_2README_8dox.html',1,'(Global Namespace)'],['../dd/d30/benchmarks_2exahype2_2ccz4_2gauge-wave_2README_8dox.html',1,'(Global Namespace)'],['../dd/da3/benchmarks_2exahype2_2ccz4_2performance-testbed_2README_8dox.html',1,'(Global Namespace)'],['../d1/d30/benchmarks_2exahype2_2ccz4_2single-black-hole_2README_8dox.html',1,'(Global Namespace)'],['../df/d40/benchmarks_2exahype2_2shallow-water_2artificial-tsunami_2README_8dox.html',1,'(Global Namespace)'],['../da/d05/benchmarks_2exahype2_2shallow-water_2kernel-benchmarks_2README_8dox.html',1,'(Global Namespace)'],['../d0/d41/benchmarks_2swift2_2hydro_2noh-implosion-test-2D_2README_8dox.html',1,'(Global Namespace)'],['../d3/d7a/benchmarks_2swift2_2hydro_2noh-implosion-test-3D_2README_8dox.html',1,'(Global Namespace)'],['../d5/df1/docker_2README_8dox.html',1,'(Global Namespace)'],['../da/d88/spack_2README_8dox.html',1,'(Global Namespace)'],['../d9/d1e/tests_2multigrid_2petsc_2poisson_2README_8dox.html',1,'(Global Namespace)'],['../df/d13/tests_2swift2_2hydro-simple-sph-physics_2noh-2d_2README_8dox.html',1,'(Global Namespace)'],['../d9/de6/tests_2swift2_2hydro-simple-sph-physics_2noh-3d_2README_8dox.html',1,'(Global Namespace)'],['../df/d32/tutorials_2exahype2_2symhype_2acoustic_2README_8dox.html',1,'(Global Namespace)'],['../d8/d5f/tutorials_2exahype2_2symhype_2advection_2README_8dox.html',1,'(Global Namespace)'],['../df/d59/tutorials_2exahype2_2symhype_2elastic_2README_8dox.html',1,'(Global Namespace)'],['../d4/da6/tutorials_2exahype2_2symhype_2euler_2README_8dox.html',1,'(Global Namespace)'],['../d8/dbb/tutorials_2exahype2_2symhype_2swe_2README_8dox.html',1,'(Global Namespace)'],['../d3/d09/tutorials_2mghype_2petsc_2continuous-galerkin-poisson_2README_8dox.html',1,'(Global Namespace)'],['../d8/d91/tutorials_2mghype_2petsc_2discontinuous-galerkin-poisson_2README_8dox.html',1,'(Global Namespace)'],['../da/d32/tutorials_2mghype_2petsc_2hybrid-dg-poisson_2README_8dox.html',1,'(Global Namespace)'],['../d3/dc7/tutorials_2mghype_2petsc_2mixed-dg-poisson_2README_8dox.html',1,'(Global Namespace)'],['../df/de9/tutorials_2peano4_2finite-volumes_2README_8dox.html',1,'(Global Namespace)']]],
  ['readme_2epy_5',['Readme.py',['../d5/dba/Readme_8py.html',1,'']]],
  ['reconstructpatch_2epy_6',['ReconstructPatch.py',['../d5/d09/ReconstructPatch_8py.html',1,'']]],
  ['reconstructpatch_2etemplate_2ecpp_7',['ReconstructPatch.template.cpp',['../d5/dbe/ReconstructPatch_8template_8cpp.html',1,'']]],
  ['reconstructpatch_2etemplate_2eh_8',['ReconstructPatch.template.h',['../d8/d97/ReconstructPatch_8template_8h.html',1,'']]],
  ['reconstructpatchfused_2etemplate_2ecpp_9',['ReconstructPatchFused.template.cpp',['../d7/d3b/ReconstructPatchFused_8template_8cpp.html',1,'']]],
  ['reconstructpatchfused_2etemplate_2eh_10',['ReconstructPatchFused.template.h',['../d7/de6/ReconstructPatchFused_8template_8h.html',1,'']]],
  ['recursivelock_2ecpp_11',['RecursiveLock.cpp',['../d9/d11/RecursiveLock_8cpp.html',1,'']]],
  ['recursivelock_2eh_12',['RecursiveLock.h',['../df/d3e/RecursiveLock_8h.html',1,'']]],
  ['recursivesemaphore_2ecpp_13',['RecursiveSemaphore.cpp',['../d1/df6/cpp_2RecursiveSemaphore_8cpp.html',1,'(Global Namespace)'],['../d4/d57/omp_2RecursiveSemaphore_8cpp.html',1,'(Global Namespace)'],['../db/d1f/RecursiveSemaphore_8cpp.html',1,'(Global Namespace)'],['../de/d96/sycl_2RecursiveSemaphore_8cpp.html',1,'(Global Namespace)'],['../d9/d5f/tbb_2RecursiveSemaphore_8cpp.html',1,'(Global Namespace)']]],
  ['recursivesemaphore_2eh_14',['RecursiveSemaphore.h',['../d6/dc7/cpp_2RecursiveSemaphore_8h.html',1,'(Global Namespace)'],['../dc/dbd/omp_2RecursiveSemaphore_8h.html',1,'(Global Namespace)'],['../da/dd9/RecursiveSemaphore_8h.html',1,'(Global Namespace)'],['../dc/dd3/sycl_2RecursiveSemaphore_8h.html',1,'(Global Namespace)'],['../d5/d03/tbb_2RecursiveSemaphore_8h.html',1,'(Global Namespace)']]],
  ['refinementcontrol_2ecpp_15',['RefinementControl.cpp',['../d1/da7/RefinementControl_8cpp.html',1,'']]],
  ['refinementcontrol_2eh_16',['RefinementControl.h',['../dc/d99/RefinementControl_8h.html',1,'']]],
  ['refinementcontrolservice_2ecpp_17',['RefinementControlService.cpp',['../d8/db6/RefinementControlService_8cpp.html',1,'']]],
  ['refinementcontrolservice_2eh_18',['RefinementControlService.h',['../d5/dfa/RefinementControlService_8h.html',1,'']]],
  ['render_2epy_19',['render.py',['../d3/dba/render_8py.html',1,'']]],
  ['reports_2ecpph_20',['Reports.cpph',['../d0/d78/Reports_8cpph.html',1,'']]],
  ['reports_2eh_21',['Reports.h',['../d6/db5/Reports_8h.html',1,'']]],
  ['resetandupdateresidual_2epy_22',['ResetAndUpdateResidual.py',['../dc/d20/CollocatedMGSolver_2ResetAndUpdateResidual_8py.html',1,'(Global Namespace)'],['../dd/d37/CollocatedSolver_2ResetAndUpdateResidual_8py.html',1,'(Global Namespace)']]],
  ['restriction_2ecpp_23',['Restriction.cpp',['../dd/de0/Restriction_8cpp.html',1,'']]],
  ['restriction_2ecpph_24',['Restriction.cpph',['../d2/da5/Restriction_8cpph.html',1,'']]],
  ['restriction_2eh_25',['Restriction.h',['../dc/de8/Restriction_8h.html',1,'']]],
  ['restriction_2epy_26',['Restriction.py',['../db/d5f/Restriction_8py.html',1,'']]],
  ['riemann_2ecpp_27',['Riemann.cpp',['../df/da6/Riemann_8cpp.html',1,'']]],
  ['riemann_2eh_28',['Riemann.h',['../dd/d41/Riemann_8h.html',1,'']]],
  ['riemann_2epy_29',['riemann.py',['../df/d2f/riemann_8py.html',1,'']]],
  ['riemannsolver_2eh_30',['riemannSolver.h',['../de/daf/riemannSolver_8h.html',1,'']]],
  ['riemannsolver_2etemplate_2ecpp_31',['RiemannSolver.template.cpp',['../d8/d78/RiemannSolver_8template_8cpp.html',1,'']]],
  ['riemannsolver_2etemplate_2eh_32',['RiemannSolver.template.h',['../d2/dad/aderdg_2kernels_2RiemannSolver_8template_8h.html',1,'(Global Namespace)'],['../db/dd6/fv_2godunov_2kernels_2RiemannSolver_8template_8h.html',1,'(Global Namespace)']]],
  ['riemannsolveranisotropic_2eh_33',['riemannsolverAnisotropic.h',['../d8/dd8/riemannsolverAnisotropic_8h.html',1,'']]],
  ['riemannsolverdynamicrupture_2eh_34',['riemannsolverDynamicRupture.h',['../d1/d65/riemannsolverDynamicRupture_8h.html',1,'']]],
  ['riemannsolverfused_2etemplate_2ecpp_35',['RiemannSolverFused.template.cpp',['../dd/df5/RiemannSolverFused_8template_8cpp.html',1,'']]],
  ['riemannsolverfused_2etemplate_2eh_36',['RiemannSolverFused.template.h',['../d1/d69/RiemannSolverFused_8template_8h.html',1,'']]],
  ['riemannsolverisotropic_2eh_37',['riemannsolverIsotropic.h',['../d9/d83/riemannsolverIsotropic_8h.html',1,'']]],
  ['riemannsolverlinear_2etemplate_2ecpp_38',['RiemannSolverLinear.template.cpp',['../d9/dff/RiemannSolverLinear_8template_8cpp.html',1,'']]],
  ['riemannsolvernonlinear_2etemplate_2ecpp_39',['RiemannSolverNonlinear.template.cpp',['../d8/d9f/RiemannSolverNonlinear_8template_8cpp.html',1,'']]],
  ['riemannsolverpml_2eh_40',['riemannsolverPML.h',['../d3/d57/riemannsolverPML_8h.html',1,'']]],
  ['riemannsolverpmldynamicrupture_2eh_41',['riemannsolverPMLDynamicRupture.h',['../d0/d24/riemannsolverPMLDynamicRupture_8h.html',1,'']]],
  ['riemannsolverroutines_2eh_42',['riemannsolverRoutines.h',['../d4/ddf/riemannsolverRoutines_8h.html',1,'']]],
  ['riemanntest_2ecpp_43',['RiemannTest.cpp',['../de/dde/rusanov_2tests_2RiemannTest_8cpp.html',1,'(Global Namespace)'],['../df/dc3/tests_2RiemannTest_8cpp.html',1,'(Global Namespace)']]],
  ['riemanntest_2eh_44',['RiemannTest.h',['../d5/d5b/rusanov_2tests_2RiemannTest_8h.html',1,'(Global Namespace)'],['../d0/ddb/tests_2RiemannTest_8h.html',1,'(Global Namespace)']]],
  ['rolloverupdatedface_2epy_45',['RollOverUpdatedFace.py',['../db/d5f/fv_2actionsets_2RollOverUpdatedFace_8py.html',1,'(Global Namespace)'],['../d5/d91/rkfd_2actionsets_2RollOverUpdatedFace_8py.html',1,'(Global Namespace)']]],
  ['root_2eh_46',['root.h',['../de/d99/root_8h.html',1,'']]],
  ['runge_2dkutta_2edox_47',['Runge-Kutta.dox',['../d3/d5d/Runge-Kutta_8dox.html',1,'']]],
  ['rungekuttadg_2epy_48',['RungeKuttaDG.py',['../d6/df9/RungeKuttaDG_8py.html',1,'']]],
  ['runner_5fdo_5fghost_2eh_49',['runner_do_ghost.h',['../d9/d8d/runner__do__ghost_8h.html',1,'']]],
  ['running_2edox_50',['running.dox',['../d6/dbc/running_8dox.html',1,'']]],
  ['runtest1_2epy_51',['runTest1.py',['../da/d75/runTest1_8py.html',1,'']]],
  ['runtime_5fanalysis_2edox_52',['runtime_analysis.dox',['../de/dcf/exahype2_2runtime__analysis_8dox.html',1,'(Global Namespace)'],['../db/d1d/swift2_2runtime__analysis_8dox.html',1,'(Global Namespace)']]],
  ['rusanov_2ecpp_53',['Rusanov.cpp',['../d7/dff/Rusanov_8cpp.html',1,'']]],
  ['rusanov_2eh_54',['Rusanov.h',['../d8/d0c/omp_2Rusanov_8h.html',1,'(Global Namespace)'],['../d2/de6/Rusanov_8h.html',1,'(Global Namespace)']]],
  ['rusanov_2epy_55',['Rusanov.py',['../d5/ddb/Rusanov_8py.html',1,'']]]
];
