var searchData=
[
  ['dam_0',['Breaking Dam',['../d5/d87/applications_exahype2_navier_stokes_breaking_dam.html',1,'applications_exahype2_navier_stokes']]],
  ['dam_20break_1',['Radial Dam Break',['../dd/d59/applications_exahype2_shallow_water_radial_dam_break.html',1,'applications_exahype2_shallow_water']]],
  ['dam_20break_20on_20an_20inclined_20plane_2',['Landslide Dam Break on an Inclined Plane',['../d3/dca/applications_exahype2_shallow_water_dam_break_landslide.html',1,'applications_exahype2_shallow_water']]],
  ['dastgen_3',['DaStGen',['../dd/db7/page_dastgen_home.html',1,'index']]],
  ['dastgen2_20test_4',['DastGen2 Test',['../d5/de2/tests_swift2_dastgen_test.html',1,'swift_tests']]],
  ['data_20consistency_5',['Sorting: Preserving the mesh-particle data consistency',['../db/d91/page_toolbox_particles_mesh_consistency.html',1,'toolbox_particles']]],
  ['data_20files_6',['Probing data files',['../df/d1d/documentation_tarch_visualisation_probing-data.html',1,'documentation_tarch_visualisation']]],
  ['data_20to_20mesh_20entities_7',['Assigning data to mesh entities',['../d6/dd6/tutorials_peano4_assign_data_to_mesh.html',1,'tutorials_peano4_tutorials']]],
  ['data_20with_20pyvista_8',['Explore data with PyVista',['../dc/d4f/documentation_tarch_visualisation_pyvista.html',1,'documentation_tarch_visualisation']]],
  ['debugging_20hints_9',['Debugging Hints',['../da/d3f/swift_debugging.html',1,'page_swift2_home']]],
  ['decomposition_10',['Domain decomposition',['../d4/d00/page_peano_domain_decomposition.html',1,'page_peano4_home']]],
  ['decomposition_11',['Load Balancing (Domain Decomposition)',['../d1/de1/toolbox_loadbalancing.html',1,'page_toolbox_home']]],
  ['degree_20of_20freedom_20layout_12',['Terminology and degree of freedom layout',['../de/d44/page_multigrid_terminology.html',1,'page_multigrid_home']]],
  ['density_20calculation_20test_13',['Density Calculation Test',['../db/d44/tests_swift2_test_density_calculation.html',1,'swift_tests']]],
  ['design_20patterns_20of_20larger_20exahype_20applications_14',['Design patterns of larger ExaHyPE applications',['../dc/d25/tutorials_exahype2_design-patterns.html',1,'page_exahype2_tutorials']]],
  ['design_20principle_3a_20unfolding_20the_20linear_20algebra_20steps_20over_20the_20mesh_20entities_15',['Design principle: Unfolding the linear algebra steps over the mesh entities',['../dd/d88/page_multigrid_unfolding.html',1,'page_multigrid_home']]],
  ['details_16',['Realisation details',['../db/dba/page_toolbox_particles_realisation.html',1,'toolbox_particles']]],
  ['dg_17',['ADER-DG',['../db/d9a/page_tutorials_exahype2_numerics_ADER-DG.html',1,'page_exahype2_tutorials']]],
  ['dg_20for_20the_20poisson_20equation_18',['Matrix-free mixed DG for the Poisson equation',['../d0/d2c/tutorials_multigrid_matrixfree_mixed_DG_poisson.html',1,'page_mghype_tutorials']]],
  ['dg_20solvers_19',['ADER-DG solvers',['../d6/d97/documentation_exahype2_solvers_aderdg.html',1,'page_exahype2_home']]],
  ['dg_20with_20jumping_20coefficients_20or_20precomputed_20cell_20operators_20',['Matrix-free DG with jumping coefficients or precomputed cell operators',['../d9/d7f/tutorials_multigrid_matrixfree_jumping_coefficients_and_optimisation.html',1,'page_mghype_tutorials']]],
  ['differences_21',['Finite Differences',['../dc/de5/page_tutorials_exahype2_numerics_finite-differences.html',1,'page_exahype2_tutorials']]],
  ['discontinuous_20galerkin_22',['Discontinuous Galerkin',['../d7/d08/exahype2_dg.html',1,'Discontinuous Galerkin'],['../d2/d39/page_tutorials_exahype2_numerics_discontinous-Galerkin.html',1,'Discontinuous Galerkin']]],
  ['discontinuous_20galerkin_20adaptive_20mesh_20refinement_23',['Discontinuous Galerkin adaptive mesh refinement',['../d6/d39/exahype2_dg_DG_AMD.html',1,'page_exahype2_home']]],
  ['discontinuous_20galerkin_20for_20the_20poisson_20equation_24',['Matrix-free Discontinuous Galerkin for the Poisson equation',['../d5/d36/tutorials_multigrid_matrixfree_discontinuous_galerkin_poisson.html',1,'page_mghype_tutorials']]],
  ['discontinuous_20galerkin_20for_20the_20poisson_20equation_20with_20petsc_25',['Discontinuous Galerkin for the Poisson equation with PETSc',['../d3/d42/tutorials_documentation_multigrid_petsc_discontinuous_galerkin_poisson.html',1,'page_mghype_tutorials']]],
  ['discontinuous_20galerkin_20solver_20with_20petsc_26',['Discontinuous Galerkin Solver with PETSc',['../d3/df9/petsc_dg_solver.html',1,'multigrid_architecture']]],
  ['docker_27',['Installation with Docker',['../df/dbb/page_installation_with_docker.html',1,'page_installation_home']]],
  ['documentation_20doxygen_28',['Documentation (Doxygen)',['../db/dc1/page_documentation_home.html',1,'index']]],
  ['domain_20decomposition_29',['Domain decomposition',['../d4/d00/page_peano_domain_decomposition.html',1,'page_peano4_home']]],
  ['domain_20decomposition_30',['Load Balancing (Domain Decomposition)',['../d1/de1/toolbox_loadbalancing.html',1,'page_toolbox_home']]],
  ['down_20on_20a_20circular_20island_31',['Solitary wave run-up and run-down on a circular island',['../d8/d84/applications_exahype2_shallow_water_circular_island.html',1,'applications_exahype2_shallow_water']]],
  ['doxygen_32',['Documentation (Doxygen)',['../db/dc1/page_documentation_home.html',1,'index']]]
];
