var searchData=
[
  ['s_20task_20graph_20compiler_0',['SWIFT&apos;s task graph compiler',['../da/d44/swift_graph_compiler.html',1,'page_swift2_home']]],
  ['schwarzschild_20black_20hole_1',['Schwarzschild black hole',['../d2/df4/benchmarks_exahype2_ccz4_single_black_hole_performance.html',1,'Performance Test (Single Schwarzschild black hole)'],['../d7/d0f/benchmarks_exahype2_ccz4_single_black_hole.html',1,'Solver coupling (Single Schwarzschild black hole)']]],
  ['scratch_2',['Building your project from scratch',['../d3/dac/swift_building_project_from_scratch.html',1,'page_swift2_home']]],
  ['sedov_20blast_20simple_20sph_3',['Sedov Blast (Simple SPH)',['../db/db8/tests_swift2_hydro_simple_sph_sedov_blast.html',1,'swift_tests']]],
  ['services_20and_20singletons_4',['Services and singletons',['../d1/d94/tarch_services.html',1,'page_tarch_home']]],
  ['sets_20and_20events_5',['Action sets and events',['../da/d1b/peano_action_sets.html',1,'page_peano4_home']]],
  ['settings_6',['Vendor Software Stacks and System- and Compiler-specific Settings',['../dd/d83/page_compiler_specific_settings_home.html',1,'index']]],
  ['shallow_20water_7',['Shallow Water',['../db/dce/applications_exahype2_shallow_water.html',1,'page_exahype_applications']]],
  ['shallow_20water_20equation_20swe_8',['The Shallow Water Equation (SWE)',['../d0/d10/page_tutorials_exahype2_symhype_swe.html',1,'page_exahype2_tutorials']]],
  ['shallow_20water_20equations_9',['Benchmarks of Compute Kernels for the Shallow Water Equations',['../d5/d56/benchmarks_exahype2_shallow_water_kernel_benchmarks.html',1,'']]],
  ['shockwave_201d_20simple_20sph_10',['Sod Shockwave 1d (Simple SPH)',['../d7/da9/tests_swift2_hydro_simple_sph_sod_1d.html',1,'swift_tests']]],
  ['simple_20sph_11',['Simple SPH',['../db/db8/tests_swift2_hydro_simple_sph_sedov_blast.html',1,'Sedov Blast (Simple SPH)'],['../d7/da9/tests_swift2_hydro_simple_sph_sod_1d.html',1,'Sod Shockwave 1d (Simple SPH)']]],
  ['single_20schwarzschild_20black_20hole_12',['Single Schwarzschild black hole',['../d2/df4/benchmarks_exahype2_ccz4_single_black_hole_performance.html',1,'Performance Test (Single Schwarzschild black hole)'],['../d7/d0f/benchmarks_exahype2_ccz4_single_black_hole.html',1,'Solver coupling (Single Schwarzschild black hole)']]],
  ['singletons_13',['Services and singletons',['../d1/d94/tarch_services.html',1,'page_tarch_home']]],
  ['situ_20visualisation_20in_20paraview_14',['In-situ visualisation in Paraview',['../dd/d1f/documentation_tarch_visualisation_paraview.html',1,'documentation_tarch_visualisation']]],
  ['smoothing_20length_20computation_20tests_15',['Smoothing Length Computation Tests',['../dc/dee/tests_swift2_test_smoothing_length_computation.html',1,'swift_tests']]],
  ['sod_20shockwave_201d_20simple_20sph_16',['Sod Shockwave 1d (Simple SPH)',['../d7/da9/tests_swift2_hydro_simple_sph_sod_1d.html',1,'swift_tests']]],
  ['software_20stacks_20and_20system_20and_20compiler_20specific_20settings_17',['Vendor Software Stacks and System- and Compiler-specific Settings',['../dd/d83/page_compiler_specific_settings_home.html',1,'index']]],
  ['solitary_20wave_20run_20up_20and_20run_20down_20on_20a_20circular_20island_18',['Solitary wave run-up and run-down on a circular island',['../d8/d84/applications_exahype2_shallow_water_circular_island.html',1,'applications_exahype2_shallow_water']]],
  ['solver_19',['Localisation of a solver',['../d5/d5f/page_peano_localisation.html',1,'page_peano4_home']]],
  ['solver_20coupling_20',['Boundary conditions and solver coupling',['../d9/de5/swift_boundary_conditions.html',1,'page_swift2_home']]],
  ['solver_20coupling_20single_20schwarzschild_20black_20hole_21',['Solver coupling (Single Schwarzschild black hole)',['../d7/d0f/benchmarks_exahype2_ccz4_single_black_hole.html',1,'page_exahype_benchmarks']]],
  ['solver_20gauge_20wave_22',['RKDG Solver (Gauge Wave)',['../d4/d54/benchmarks_exahype2_ccz4_gauge_wave.html',1,'page_exahype_benchmarks']]],
  ['solver_20with_20petsc_23',['Solver with PETSc',['../db/df0/petsc_collocated_solver.html',1,'Collocated Solver with PETSc'],['../d3/df9/petsc_dg_solver.html',1,'Discontinuous Galerkin Solver with PETSc']]],
  ['solvers_24',['solvers',['../d6/d97/documentation_exahype2_solvers_aderdg.html',1,'ADER-DG solvers'],['../d5/d35/documentation_exahype2_solvers_enclave_solvers.html',1,'Enclave and optimistic solvers'],['../d2/d72/page_exahype_solvers.html',1,'ExaHyPE 2 solvers']]],
  ['solvers_25',['Solvers',['../da/d7d/page_multigrid_solvers.html',1,'page_multigrid_home']]],
  ['solvers_20and_20additional_20mesh_20traversals_26',['Coupling of various solvers and additional mesh traversals',['../da/d8c/tutorials_exahype2_coupling.html',1,'page_exahype2_tutorials']]],
  ['solvers_20with_20new_20algorithmic_20steps_27',['Creating new particle types (solvers) with new algorithmic steps',['../d2/daf/swift_particle_new_solver.html',1,'page_swift2_home']]],
  ['some_20machines_28',['Reference Configurations for Some Machines',['../d6/d5c/page_machines.html',1,'page_compiler_specific_settings_home']]],
  ['sorting_3a_20preserving_20the_20mesh_20particle_20data_20consistency_29',['Sorting: Preserving the mesh-particle data consistency',['../db/d91/page_toolbox_particles_mesh_consistency.html',1,'toolbox_particles']]],
  ['spack_30',['Installation with Spack',['../d6/db6/page_installation_with_spack.html',1,'page_installation_home']]],
  ['specific_20settings_31',['Vendor Software Stacks and System- and Compiler-specific Settings',['../dd/d83/page_compiler_specific_settings_home.html',1,'index']]],
  ['sph_32',['SPH',['../db/db8/tests_swift2_hydro_simple_sph_sedov_blast.html',1,'Sedov Blast (Simple SPH)'],['../d7/da9/tests_swift2_hydro_simple_sph_sod_1d.html',1,'Sod Shockwave 1d (Simple SPH)']]],
  ['stacks_20and_20system_20and_20compiler_20specific_20settings_33',['Vendor Software Stacks and System- and Compiler-specific Settings',['../dd/d83/page_compiler_specific_settings_home.html',1,'index']]],
  ['statistics_20profiling_20and_20assertions_34',['Logging, tracing, statistics, profiling and assertions',['../d1/d9e/tarch_logging.html',1,'page_tarch_home']]],
  ['steps_35',['Creating new particle types (solvers) with new algorithmic steps',['../d2/daf/swift_particle_new_solver.html',1,'page_swift2_home']]],
  ['steps_20over_20the_20mesh_20entities_36',['Design principle: Unfolding the linear algebra steps over the mesh entities',['../dd/d88/page_multigrid_unfolding.html',1,'page_multigrid_home']]],
  ['stokes_37',['Navier Stokes',['../de/dd5/applications_exahype2_navier_stokes.html',1,'page_exahype_applications']]],
  ['storage_20within_20mesh_38',['Multiscale particle storage within mesh',['../d0/d45/page_toolbox_particles_mesh_storage.html',1,'toolbox_particles']]],
  ['strategies_39',['Load balancing strategies',['../d2/d5f/page_toolbox_loadbalancing_strategies.html',1,'toolbox_loadbalancing']]],
  ['support_40',['Adding GPU support',['../d0/d35/tutorials_exahype_gpu.html',1,'page_exahype2_tutorials']]],
  ['support_20and_20aggressive_20vectorisation_41',['GPU support (and aggressive vectorisation)',['../d1/d26/page_exahype_gpu.html',1,'page_exahype2_home']]],
  ['swe_42',['The Shallow Water Equation (SWE)',['../d0/d10/page_tutorials_exahype2_symhype_swe.html',1,'page_exahype2_tutorials']]],
  ['sweeps_43',['sweeps',['../d2/dee/page_exahype2_coupling.html',1,'Coupling ExaHyPE to other codes and adding additional mesh sweeps'],['../da/dd4/tutorials_exahype2_additional_mesh_sweeps.html',1,'Introducing additional mesh sweeps']]],
  ['swift_202_44',['Swift 2',['../d6/dba/page_swift2_home.html',1,'index']]],
  ['swift_20s_20task_20graph_20compiler_45',['SWIFT&apos;s task graph compiler',['../da/d44/swift_graph_compiler.html',1,'page_swift2_home']]],
  ['symmetrical_20paraboloid_46',['Oscillation in a symmetrical paraboloid',['../d4/df2/applications_exahype2_shallow_water_oscillating_lake.html',1,'applications_exahype2_shallow_water']]],
  ['system_20and_20compiler_20specific_20settings_47',['Vendor Software Stacks and System- and Compiler-specific Settings',['../dd/d83/page_compiler_specific_settings_home.html',1,'index']]]
];
