var searchData=
[
  ['paraview_0',['ParaView',['../documentation_tarch_visualisation_paraview.html',1,'documentation_tarch_visualisation']]],
  ['part_201_20the_20acoustic_20equations_1',['Part 1 - The Acoustic Equations',['../page_exahype2_tutorials_acoustic.html',1,'page_exahype2_tutorials']]],
  ['part_202_20solution_20to_20exercise_201_2',['Part 2 - Solution to Exercise 1',['../page_exahype2_tutorials_shallow_water_solution.html',1,'page_exahype2_tutorials_shallow_water']]],
  ['part_202_20solution_20to_20exercise_202_3',['Part 2 - Solution to Exercise 2',['../page_exahype2_tutorials_shallow_water_solution_2.html',1,'page_exahype2_tutorials_shallow_water']]],
  ['part_202_20the_20shallow_20water_20equations_4',['Part 2 - The Shallow Water Equations',['../page_exahype2_tutorials_shallow_water.html',1,'page_exahype2_tutorials']]],
  ['part_203_20the_20euler_20equations_20over_20an_20airfoil_5',['Part 3 - The Euler Equations over an Airfoil',['../page_exahype2_tutorials_euler.html',1,'page_exahype2_tutorials']]],
  ['part_204_20a_202d_20euler_20shock_20with_20a_20posteriori_20limiting_6',['Part 4 - A 2D Euler Shock with a-posteriori Limiting',['../page_exahype2_tutorials_limiting.html',1,'page_exahype2_tutorials']]],
  ['part_205_203d_20elastic_20waves_20and_20a_20taste_20of_20hpc_7',['Part 5 - 3D Elastic Waves and a Taste of HPC',['../page_exahype2_tutorials_elastic.html',1,'page_exahype2_tutorials']]],
  ['particle_20interaction_20sets_8',['Particle interaction sets',['../page_peano4_particles_mesh_traversal.html',1,'page_peano4_particles']]],
  ['particle_20set_20storage_9',['Particle-set storage',['../page_peano4_particles_realisation_particle_lift_flavours.html',1,'page_peano4_particles_realisation']]],
  ['particle_20sorting_20and_20mesh_20consistency_10',['Particle sorting and mesh consistency',['../page_peano4_particles_mesh_consistency.html',1,'page_peano4_particles']]],
  ['particle_20storage_11',['Multiscale particle storage',['../page_peano4_particles_mesh_storage.html',1,'page_peano4_particles']]],
  ['particle_20storage_20and_20exchange_12',['Particle storage and exchange',['../page_peano4_particles_realisation.html',1,'page_peano4_particles']]],
  ['particles_13',['Particles',['../page_peano4_particles.html',1,'page_peano4_home']]],
  ['party_20tools_14',['Third-party tools',['../page_third_party_home.html',1,'index']]],
  ['patch_20file_20format_15',['Patch file format',['../tarch_patch_file_format.html',1,'documentation_tarch_visualisation']]],
  ['patch_20operations_16',['Block-structured patch operations',['../page_exahype2_blockstructured.html',1,'page_exahype2_home']]],
  ['peano_17',['Peano',['../index.html',1,'']]],
  ['peano_204_18',['Peano 4',['../page_peano4_home.html',1,'index']]],
  ['performance_20optimisation_19',['Performance optimisation',['../page_exahype_performance_optimisation.html',1,'Performance optimisation'],['../page_peano_performance_optimisation.html',1,'Performance optimisation']]],
  ['perspective_20',['FAQs and Troubleshooting (User Perspective)',['../page_faq_home.html',1,'index']]],
  ['plotting_21',['Plotting',['../tarch_plotting.html',1,'page_tarch_home']]],
  ['posteriori_20limiting_22',['Part 4 - A 2D Euler Shock with a-posteriori Limiting',['../page_exahype2_tutorials_limiting.html',1,'page_exahype2_tutorials']]],
  ['probing_20data_23',['Probing data',['../documentation_tarch_visualisation_probing-data.html',1,'documentation_tarch_visualisation']]],
  ['profiling_20and_20assertions_24',['Logging, profiling and assertions',['../tarch_logging.html',1,'page_tarch_home']]],
  ['programming_25',['MPI programming',['../page_tarch_mpi.html',1,'page_tarch_home']]],
  ['pyvista_26',['PyVista',['../documentation_tarch_visualisation_pyvista.html',1,'documentation_tarch_visualisation']]]
];
