var searchData=
[
  ['a_20channel_20with_20three_20mounds_0',['Flooding problem in a channel with three mounds',['../d1/db6/applications_exahype2_shallow_water_three_mounds_channel.html',1,'applications_exahype2_shallow_water']]],
  ['a_20circular_20island_1',['Solitary wave run-up and run-down on a circular island',['../d8/d84/applications_exahype2_shallow_water_circular_island.html',1,'applications_exahype2_shallow_water']]],
  ['a_20peano_20code_2',['The typical main.cpp in a Peano code',['../d7/d01/peano_main.html',1,'page_peano4_home']]],
  ['a_20solver_3',['Localisation of a solver',['../d5/d5f/page_peano_localisation.html',1,'page_peano4_home']]],
  ['a_20symmetrical_20paraboloid_4',['Oscillation in a symmetrical paraboloid',['../d4/df2/applications_exahype2_shallow_water_oscillating_lake.html',1,'applications_exahype2_shallow_water']]],
  ['acoustic_20wave_20equation_5',['The Acoustic Wave Equation',['../dd/dea/page_tutorials_exahype2_symhype_acoustic.html',1,'page_exahype2_tutorials']]],
  ['action_20sets_20and_20events_6',['Action sets and events',['../da/d1b/peano_action_sets.html',1,'page_peano4_home']]],
  ['adaptive_20mesh_20refinement_7',['Adaptive mesh refinement',['../d7/dbe/page_exahype_amr.html',1,'page_exahype2_home']]],
  ['adaptive_20mesh_20refinement_8',['Discontinuous Galerkin adaptive mesh refinement',['../d6/d39/exahype2_dg_DG_AMD.html',1,'page_exahype2_home']]],
  ['adaptive_20mesh_20refinement_20amr_9',['Adaptive Mesh Refinement (AMR)',['../da/dbb/page_peano_amr.html',1,'page_peano4_home']]],
  ['adding_20additional_20mesh_20sweeps_10',['Coupling ExaHyPE to other codes and adding additional mesh sweeps',['../d2/dee/page_exahype2_coupling.html',1,'page_exahype2_home']]],
  ['adding_20gpu_20support_11',['Adding GPU support',['../d0/d35/tutorials_exahype_gpu.html',1,'page_exahype2_tutorials']]],
  ['additional_20mesh_20sweeps_12',['additional mesh sweeps',['../d2/dee/page_exahype2_coupling.html',1,'Coupling ExaHyPE to other codes and adding additional mesh sweeps'],['../da/dd4/tutorials_exahype2_additional_mesh_sweeps.html',1,'Introducing additional mesh sweeps']]],
  ['additional_20mesh_20traversals_13',['Coupling of various solvers and additional mesh traversals',['../da/d8c/tutorials_exahype2_coupling.html',1,'page_exahype2_tutorials']]],
  ['ader_20dg_14',['ADER-DG',['../db/d9a/page_tutorials_exahype2_numerics_ADER-DG.html',1,'page_exahype2_tutorials']]],
  ['ader_20dg_20solvers_15',['ADER-DG solvers',['../d6/d97/documentation_exahype2_solvers_aderdg.html',1,'page_exahype2_home']]],
  ['advanced_20usage_20of_20exagrype_16',['Advanced Usage of ExaGRyPE',['../df/d1a/tutorials_exahype2_applications_exagrype_advanced.html',1,'tutorials_exahype2_applications_exagrype']]],
  ['advection_20equation_17',['The Advection Equation',['../dd/d5a/page_tutorials_exahype2_symhype_advection.html',1,'page_exahype2_tutorials']]],
  ['aggressive_20vectorisation_18',['GPU support (and aggressive vectorisation)',['../d1/d26/page_exahype_gpu.html',1,'page_exahype2_home']]],
  ['algebra_20steps_20over_20the_20mesh_20entities_19',['Design principle: Unfolding the linear algebra steps over the mesh entities',['../dd/d88/page_multigrid_unfolding.html',1,'page_multigrid_home']]],
  ['algorithmic_20steps_20',['Creating new particle types (solvers) with new algorithmic steps',['../d2/daf/swift_particle_new_solver.html',1,'page_swift2_home']]],
  ['amr_21',['Adaptive Mesh Refinement (AMR)',['../da/dbb/page_peano_amr.html',1,'page_peano4_home']]],
  ['an_20inclined_20plane_22',['Landslide Dam Break on an Inclined Plane',['../d3/dca/applications_exahype2_shallow_water_dam_break_landslide.html',1,'applications_exahype2_shallow_water']]],
  ['analysis_23',['analysis',['../d4/da7/page_exahype_runtime_analysis.html',1,'Runtime analysis'],['../d0/dd8/swift_runtime_analysis.html',1,'Runtime analysis']]],
  ['and_20adding_20additional_20mesh_20sweeps_24',['Coupling ExaHyPE to other codes and adding additional mesh sweeps',['../d2/dee/page_exahype2_coupling.html',1,'page_exahype2_home']]],
  ['and_20additional_20mesh_20traversals_25',['Coupling of various solvers and additional mesh traversals',['../da/d8c/tutorials_exahype2_coupling.html',1,'page_exahype2_tutorials']]],
  ['and_20aggressive_20vectorisation_26',['GPU support (and aggressive vectorisation)',['../d1/d26/page_exahype_gpu.html',1,'page_exahype2_home']]],
  ['and_20assertions_27',['Logging, tracing, statistics, profiling and assertions',['../d1/d9e/tarch_logging.html',1,'page_tarch_home']]],
  ['and_20checkpointing_28',['Extend the visualisation (and checkpointing)',['../dc/d02/page_exahype_extend-visualisation.html',1,'page_exahype2_home']]],
  ['and_20degree_20of_20freedom_20layout_29',['Terminology and degree of freedom layout',['../de/d44/page_multigrid_terminology.html',1,'page_multigrid_home']]],
  ['and_20events_30',['Action sets and events',['../da/d1b/peano_action_sets.html',1,'page_peano4_home']]],
  ['and_20ides_31',['Coding Conventions and IDEs',['../d3/d61/page_conventions_home.html',1,'index']]],
  ['and_20initial_20mesh_20construction_32',['Initial conditions, particle insertion and initial mesh construction',['../d4/d9b/swift_initial_conditions.html',1,'page_swift2_home']]],
  ['and_20optimistic_20solvers_33',['Enclave and optimistic solvers',['../d5/d35/documentation_exahype2_solvers_enclave_solvers.html',1,'page_exahype2_home']]],
  ['and_20output_34',['Visualisation and output',['../d2/d2d/page_exahype_visualisation.html',1,'page_exahype2_home']]],
  ['and_20run_20down_20on_20a_20circular_20island_35',['Solitary wave run-up and run-down on a circular island',['../d8/d84/applications_exahype2_shallow_water_circular_island.html',1,'applications_exahype2_shallow_water']]],
  ['and_20singletons_36',['Services and singletons',['../d1/d94/tarch_services.html',1,'page_tarch_home']]],
  ['and_20solver_20coupling_37',['Boundary conditions and solver coupling',['../d9/de5/swift_boundary_conditions.html',1,'page_swift2_home']]],
  ['and_20system_20and_20compiler_20specific_20settings_38',['Vendor Software Stacks and System- and Compiler-specific Settings',['../dd/d83/page_compiler_specific_settings_home.html',1,'index']]],
  ['and_20troubleshooting_39',['FAQ and troubleshooting',['../d8/d6f/page_exahype_faq.html',1,'page_exahype2_home']]],
  ['and_20troubleshooting_20user_20perspective_40',['FAQs and Troubleshooting (User Perspective)',['../d7/d3c/page_faq_home.html',1,'index']]],
  ['api_20intro_41',['python api intro',['../de/de4/peano_python_api.html',1,'page_peano4_home']]],
  ['applications_42',['Applications',['../d2/d0b/page_exahype_applications.html',1,'page_exahype2_home']]],
  ['applications_43',['applications',['../dc/d25/tutorials_exahype2_design-patterns.html',1,'Design patterns of larger ExaHyPE applications'],['../df/db4/page_peano_merging_applications.html',1,'Merging/coupling various applications']]],
  ['apptainer_44',['Installation with Apptainer',['../db/d56/page_installation_with_apptainer.html',1,'page_installation_home']]],
  ['architecture_45',['Architecture',['../db/d3f/page_architecture_home.html',1,'Architecture'],['../da/dc1/multigrid_architecture.html',1,'Architecture'],['../d5/d3d/swift_architecture.html',1,'Architecture']]],
  ['architecture_20tarch_46',['Technical Architecture (tarch)',['../dd/d46/page_tarch_home.html',1,'index']]],
  ['artificial_20tsunami_47',['Artificial Tsunami',['../d7/db3/benchmarks_exahype2_shallow_water_artificial_tsunami.html',1,'Artificial Tsunami'],['../d6/d5c/applications_exahype2_shallow_water_artificial_tsunami.html',1,'Artificial Tsunami']]],
  ['assertions_48',['assertions',['../d1/d9e/tarch_logging.html',1,'Logging, tracing, statistics, profiling and assertions'],['../db/d11/tarch_NoncriticalAssertions.html',1,'Noncritical assertions']]],
  ['assigning_20data_20to_20mesh_20entities_49',['Assigning data to mesh entities',['../d6/dd6/tutorials_peano4_assign_data_to_mesh.html',1,'tutorials_peano4_tutorials']]]
];
