var searchData=
[
  ['paraboloid_0',['Oscillation in a symmetrical paraboloid',['../d4/df2/applications_exahype2_shallow_water_oscillating_lake.html',1,'applications_exahype2_shallow_water']]],
  ['parallelisation_1',['Parallelisation',['../db/dc1/page_exahype_parallelisation.html',1,'Parallelisation'],['../dc/d3c/swift_parallelisation.html',1,'Parallelisation']]],
  ['paraview_2',['In-situ visualisation in Paraview',['../dd/d1f/documentation_tarch_visualisation_paraview.html',1,'documentation_tarch_visualisation']]],
  ['particle_20data_20consistency_3',['Sorting: Preserving the mesh-particle data consistency',['../db/d91/page_toolbox_particles_mesh_consistency.html',1,'toolbox_particles']]],
  ['particle_20insertion_20and_20initial_20mesh_20construction_4',['Initial conditions, particle insertion and initial mesh construction',['../d4/d9b/swift_initial_conditions.html',1,'page_swift2_home']]],
  ['particle_20list_20flavours_5',['Particle list flavours',['../de/d40/page_toolbox_particles_realisation_particle_lift_flavours.html',1,'page_toolbox_particles_realisation']]],
  ['particle_20memory_20pools_6',['Particle memory pools',['../db/d9c/toolbox_particles_memorypool.html',1,'page_toolbox_particles_realisation']]],
  ['particle_20storage_20within_20mesh_7',['Multiscale particle storage within mesh',['../d0/d45/page_toolbox_particles_mesh_storage.html',1,'toolbox_particles']]],
  ['particle_20types_20solvers_20with_20new_20algorithmic_20steps_8',['Creating new particle types (solvers) with new algorithmic steps',['../d2/daf/swift_particle_new_solver.html',1,'page_swift2_home']]],
  ['particles_9',['Particles',['../d0/d9e/toolbox_particles.html',1,'page_toolbox_home']]],
  ['patch_20files_10',['Peano patch files',['../da/d59/tarch_patch_file_format.html',1,'documentation_tarch_visualisation']]],
  ['patterns_20of_20larger_20exahype_20applications_11',['Design patterns of larger ExaHyPE applications',['../dc/d25/tutorials_exahype2_design-patterns.html',1,'page_exahype2_tutorials']]],
  ['peano_12',['Peano',['../index.html',1,'']]],
  ['peano_204_13',['Peano 4',['../dd/da2/page_peano4_home.html',1,'index']]],
  ['peano_204_20finite_20volumes_20tutorial_14',['Peano 4 Finite Volumes Tutorial',['../dd/d17/page_peano4_tutorials_finite_volumes.html',1,'tutorials_peano4_tutorials']]],
  ['peano_204_20petsc_20projects_15',['Peano 4 PETSc projects',['../d2/d05/documentation_multigrid_petsc.html',1,'page_multigrid_home']]],
  ['peano_20code_16',['The typical main.cpp in a Peano code',['../d7/d01/peano_main.html',1,'page_peano4_home']]],
  ['peano_20patch_20files_17',['Peano patch files',['../da/d59/tarch_patch_file_format.html',1,'documentation_tarch_visualisation']]],
  ['performance_20optimisation_18',['Performance optimisation',['../d7/dfe/page_exahype_performance_optimisation.html',1,'Performance optimisation'],['../da/d8a/page_peano_performance_optimisation.html',1,'Performance optimisation'],['../d3/dc8/page_swift_performance_optimisation.html',1,'Performance optimisation']]],
  ['performance_20test_20single_20schwarzschild_20black_20hole_19',['Performance Test (Single Schwarzschild black hole)',['../d2/df4/benchmarks_exahype2_ccz4_single_black_hole_performance.html',1,'page_exahype_benchmarks']]],
  ['perspective_20',['FAQs and Troubleshooting (User Perspective)',['../d7/d3c/page_faq_home.html',1,'index']]],
  ['petsc_21',['PETSc',['../db/df0/petsc_collocated_solver.html',1,'Collocated Solver with PETSc'],['../dc/de6/tutorials_documentation_multigrid_petsc_continuous_galerkin_poisson.html',1,'Continuous Galerkin for the Poisson equation with PETSc'],['../d3/d42/tutorials_documentation_multigrid_petsc_discontinuous_galerkin_poisson.html',1,'Discontinuous Galerkin for the Poisson equation with PETSc'],['../d3/df9/petsc_dg_solver.html',1,'Discontinuous Galerkin Solver with PETSc'],['../d7/d6a/tutorials_documentation_multigrid_petsc_hybrid_galerkin_poisson.html',1,'Hybrid Galerkin for the Poisson equation with PETSc'],['../d5/d6b/tutorials_documentation_multigrid_petsc_mixed_galerkin_poisson.html',1,'Mixed Galerkin for the Poisson equation with PETSc']]],
  ['petsc_20projects_22',['Peano 4 PETSc projects',['../d2/d05/documentation_multigrid_petsc.html',1,'page_multigrid_home']]],
  ['plane_23',['Landslide Dam Break on an Inclined Plane',['../d3/dca/applications_exahype2_shallow_water_dam_break_landslide.html',1,'applications_exahype2_shallow_water']]],
  ['planet_20orbit_24',['Planet orbit',['../d3/da0/tutorials_swift2_planet_orbit.html',1,'Planet orbit'],['../d9/d7c/tests_swift2_planet_orbit.html',1,'Planet orbit']]],
  ['plotting_25',['Plotting',['../d3/d14/tarch_plotting.html',1,'page_tarch_home']]],
  ['point_20explosion_26',['Point Explosion',['../dd/d75/applications_exahype2_navier_stokes_point_explosion.html',1,'applications_exahype2_navier_stokes']]],
  ['poisson_20equation_27',['Poisson equation',['../df/d82/tutorials_mghype_numerics_continuous_galerkin_poisson.html',1,'Continuous Galerkin for the Poisson equation'],['../d5/d36/tutorials_multigrid_matrixfree_discontinuous_galerkin_poisson.html',1,'Matrix-free Discontinuous Galerkin for the Poisson equation'],['../d0/d2c/tutorials_multigrid_matrixfree_mixed_DG_poisson.html',1,'Matrix-free mixed DG for the Poisson equation'],['../d1/ded/benchmarks_documentation_multigrid_petsc_poisson.html',1,'Poisson equation']]],
  ['poisson_20equation_20with_20petsc_28',['Poisson equation with PETSc',['../dc/de6/tutorials_documentation_multigrid_petsc_continuous_galerkin_poisson.html',1,'Continuous Galerkin for the Poisson equation with PETSc'],['../d3/d42/tutorials_documentation_multigrid_petsc_discontinuous_galerkin_poisson.html',1,'Discontinuous Galerkin for the Poisson equation with PETSc'],['../d7/d6a/tutorials_documentation_multigrid_petsc_hybrid_galerkin_poisson.html',1,'Hybrid Galerkin for the Poisson equation with PETSc'],['../d5/d6b/tutorials_documentation_multigrid_petsc_mixed_galerkin_poisson.html',1,'Mixed Galerkin for the Poisson equation with PETSc']]],
  ['poisson_20tests_29',['Poisson tests',['../db/d33/tests_multigrid_matrixfree_poisson.html',1,'']]],
  ['pools_30',['Particle memory pools',['../db/d9c/toolbox_particles_memorypool.html',1,'page_toolbox_particles_realisation']]],
  ['precomputed_20cell_20operators_31',['Matrix-free DG with jumping coefficients or precomputed cell operators',['../d9/d7f/tutorials_multigrid_matrixfree_jumping_coefficients_and_optimisation.html',1,'page_mghype_tutorials']]],
  ['preserving_20the_20mesh_20particle_20data_20consistency_32',['Sorting: Preserving the mesh-particle data consistency',['../db/d91/page_toolbox_particles_mesh_consistency.html',1,'toolbox_particles']]],
  ['principle_3a_20unfolding_20the_20linear_20algebra_20steps_20over_20the_20mesh_20entities_33',['Design principle: Unfolding the linear algebra steps over the mesh entities',['../dd/d88/page_multigrid_unfolding.html',1,'page_multigrid_home']]],
  ['probing_20data_20files_34',['Probing data files',['../df/d1d/documentation_tarch_visualisation_probing-data.html',1,'documentation_tarch_visualisation']]],
  ['problem_20in_20a_20channel_20with_20three_20mounds_35',['Flooding problem in a channel with three mounds',['../d1/db6/applications_exahype2_shallow_water_three_mounds_channel.html',1,'applications_exahype2_shallow_water']]],
  ['profiling_20and_20assertions_36',['Logging, tracing, statistics, profiling and assertions',['../d1/d9e/tarch_logging.html',1,'page_tarch_home']]],
  ['programming_37',['programming',['../dd/d83/page_tarch_mpi.html',1,'MPI programming'],['../d1/d24/page_tarch_multicore.html',1,'Multicore programming']]],
  ['project_20from_20scratch_38',['Building your project from scratch',['../d3/dac/swift_building_project_from_scratch.html',1,'page_swift2_home']]],
  ['projects_39',['Peano 4 PETSc projects',['../d2/d05/documentation_multigrid_petsc.html',1,'page_multigrid_home']]],
  ['python_20api_20intro_40',['python api intro',['../de/de4/peano_python_api.html',1,'page_peano4_home']]],
  ['pyvista_41',['Explore data with PyVista',['../dc/d4f/documentation_tarch_visualisation_pyvista.html',1,'documentation_tarch_visualisation']]]
];
