var searchData=
[
  ['calculation_20test_0',['Density Calculation Test',['../db/d44/tests_swift2_test_density_calculation.html',1,'swift_tests']]],
  ['cartesian_20loh_201_1',['Cartesian LOH.1',['../de/dc5/applications_exahype2_exaseis_cartesian.html',1,'applications_exahype2_exaseis']]],
  ['cell_20operators_2',['Matrix-free DG with jumping coefficients or precomputed cell operators',['../d9/d7f/tutorials_multigrid_matrixfree_jumping_coefficients_and_optimisation.html',1,'page_mghype_tutorials']]],
  ['channel_20with_20three_20mounds_3',['Flooding problem in a channel with three mounds',['../d1/db6/applications_exahype2_shallow_water_three_mounds_channel.html',1,'applications_exahype2_shallow_water']]],
  ['checkpointing_4',['Checkpointing',['../d1/d42/page_exahype_checkpointing.html',1,'page_exahype2_home']]],
  ['checkpointing_5',['Extend the visualisation (and checkpointing)',['../dc/d02/page_exahype_extend-visualisation.html',1,'page_exahype2_home']]],
  ['chile_20tsunami_6',['2010 Chile Tsunami',['../d3/df2/applications_exahype2_shallow_water_chile_tsunami.html',1,'applications_exahype2_shallow_water']]],
  ['ci_7',['Continuous Integration (CI)',['../d2/d98/page_continuous_integration.html',1,'index']]],
  ['circular_20island_8',['Solitary wave run-up and run-down on a circular island',['../d8/d84/applications_exahype2_shallow_water_circular_island.html',1,'applications_exahype2_shallow_water']]],
  ['clusters_9',['Run ExaGRyPE on Clusters',['../d8/da0/tutorials_exahype2_applications_exagrype_clusters.html',1,'tutorials_exahype2_applications_exagrype']]],
  ['code_10',['The typical main.cpp in a Peano code',['../d7/d01/peano_main.html',1,'page_peano4_home']]],
  ['codes_20and_20adding_20additional_20mesh_20sweeps_11',['Coupling ExaHyPE to other codes and adding additional mesh sweeps',['../d2/dee/page_exahype2_coupling.html',1,'page_exahype2_home']]],
  ['coding_20conventions_20and_20ides_12',['Coding Conventions and IDEs',['../d3/d61/page_conventions_home.html',1,'index']]],
  ['coefficients_20or_20precomputed_20cell_20operators_13',['Matrix-free DG with jumping coefficients or precomputed cell operators',['../d9/d7f/tutorials_multigrid_matrixfree_jumping_coefficients_and_optimisation.html',1,'page_mghype_tutorials']]],
  ['collocated_20solver_20with_20petsc_14',['Collocated Solver with PETSc',['../db/df0/petsc_collocated_solver.html',1,'multigrid_architecture']]],
  ['command_20line_20conversation_20into_20vtk_20file_20formats_15',['Offline (command-line) conversation into VTK file formats',['../de/dbe/documentation_tarch_visualisation_offline-conversion.html',1,'documentation_tarch_visualisation']]],
  ['compiler_16',['SWIFT&apos;s task graph compiler',['../da/d44/swift_graph_compiler.html',1,'page_swift2_home']]],
  ['compiler_20specific_20settings_17',['Vendor Software Stacks and System- and Compiler-specific Settings',['../dd/d83/page_compiler_specific_settings_home.html',1,'index']]],
  ['computation_20tests_18',['Smoothing Length Computation Tests',['../dc/dee/tests_swift2_test_smoothing_length_computation.html',1,'swift_tests']]],
  ['compute_20kernels_20for_20the_20shallow_20water_20equations_19',['Benchmarks of Compute Kernels for the Shallow Water Equations',['../d5/d56/benchmarks_exahype2_shallow_water_kernel_benchmarks.html',1,'']]],
  ['conditions_20',['Boundary conditions',['../d3/de0/page_exahype_boundary_conditions.html',1,'page_exahype2_home']]],
  ['conditions_21',['Boundary Conditions',['../d8/d87/documentation_multigrid_boundary_conditions.html',1,'page_multigrid_home']]],
  ['conditions_22',['Test boundary conditions',['../dc/d0d/tests_swift2_test_boundary_conditions.html',1,'swift_tests']]],
  ['conditions_20and_20solver_20coupling_23',['Boundary conditions and solver coupling',['../d9/de5/swift_boundary_conditions.html',1,'page_swift2_home']]],
  ['conditions_20particle_20insertion_20and_20initial_20mesh_20construction_24',['Initial conditions, particle insertion and initial mesh construction',['../d4/d9b/swift_initial_conditions.html',1,'page_swift2_home']]],
  ['configuration_25',['Multicore configuration',['../d3/d21/page_exahype_multicore.html',1,'page_exahype2_home']]],
  ['configurations_20for_20some_20machines_26',['Reference Configurations for Some Machines',['../d6/d5c/page_machines.html',1,'page_compiler_specific_settings_home']]],
  ['configure_20exagrype_27',['Configure ExaGRyPE',['../dc/d0c/tutorials_exahype2_applications_exagrype_setup.html',1,'tutorials_exahype2_applications_exagrype']]],
  ['consistency_28',['Sorting: Preserving the mesh-particle data consistency',['../db/d91/page_toolbox_particles_mesh_consistency.html',1,'toolbox_particles']]],
  ['construction_29',['Initial conditions, particle insertion and initial mesh construction',['../d4/d9b/swift_initial_conditions.html',1,'page_swift2_home']]],
  ['continuous_20galerkin_20for_20the_20poisson_20equation_30',['Continuous Galerkin for the Poisson equation',['../df/d82/tutorials_mghype_numerics_continuous_galerkin_poisson.html',1,'page_mghype_tutorials']]],
  ['continuous_20galerkin_20for_20the_20poisson_20equation_20with_20petsc_31',['Continuous Galerkin for the Poisson equation with PETSc',['../dc/de6/tutorials_documentation_multigrid_petsc_continuous_galerkin_poisson.html',1,'page_mghype_tutorials']]],
  ['continuous_20integration_20ci_32',['Continuous Integration (CI)',['../d2/d98/page_continuous_integration.html',1,'index']]],
  ['control_20git_33',['Version Control (Git)',['../d3/d9b/page_version_control_home.html',1,'index']]],
  ['conventions_20and_20ides_34',['Coding Conventions and IDEs',['../d3/d61/page_conventions_home.html',1,'index']]],
  ['conversation_20into_20vtk_20file_20formats_35',['Offline (command-line) conversation into VTK file formats',['../de/dbe/documentation_tarch_visualisation_offline-conversion.html',1,'documentation_tarch_visualisation']]],
  ['coupling_36',['Boundary conditions and solver coupling',['../d9/de5/swift_boundary_conditions.html',1,'page_swift2_home']]],
  ['coupling_20exahype_20to_20other_20codes_20and_20adding_20additional_20mesh_20sweeps_37',['Coupling ExaHyPE to other codes and adding additional mesh sweeps',['../d2/dee/page_exahype2_coupling.html',1,'page_exahype2_home']]],
  ['coupling_20of_20various_20solvers_20and_20additional_20mesh_20traversals_38',['Coupling of various solvers and additional mesh traversals',['../da/d8c/tutorials_exahype2_coupling.html',1,'page_exahype2_tutorials']]],
  ['coupling_20single_20schwarzschild_20black_20hole_39',['Solver coupling (Single Schwarzschild black hole)',['../d7/d0f/benchmarks_exahype2_ccz4_single_black_hole.html',1,'page_exahype_benchmarks']]],
  ['coupling_20various_20applications_40',['Merging/coupling various applications',['../df/db4/page_peano_merging_applications.html',1,'page_peano4_home']]],
  ['cpp_20in_20a_20peano_20code_41',['The typical main.cpp in a Peano code',['../d7/d01/peano_main.html',1,'page_peano4_home']]],
  ['creating_20new_20particle_20types_20solvers_20with_20new_20algorithmic_20steps_42',['Creating new particle types (solvers) with new algorithmic steps',['../d2/daf/swift_particle_new_solver.html',1,'page_swift2_home']]]
];
