var searchData=
[
  ['tōhoku_20tsunami_0',['2011 Tōhoku Tsunami',['../df/d26/applications_exahype2_shallow_water_tohoku_tsunami.html',1,'applications_exahype2_shallow_water']]],
  ['tafjord_20region_20of_20norway_1',['Landslide on the Tafjord Region of Norway',['../dd/d1f/applications_exahype2_shallow_water_tafjord_landslide.html',1,'applications_exahype2_shallow_water']]],
  ['tarch_2',['Technical Architecture (tarch)',['../dd/d46/page_tarch_home.html',1,'index']]],
  ['task_20graph_20compiler_3',['SWIFT&apos;s task graph compiler',['../da/d44/swift_graph_compiler.html',1,'page_swift2_home']]],
  ['task_20tracing_4',['Otter task tracing',['../d3/d0d/tarch_multicore_otter.html',1,'']]],
  ['tbb_20extensions_5',['TBB extensions',['../d7/d2b/tbb_extension.html',1,'']]],
  ['technical_20architecture_20tarch_6',['Technical Architecture (tarch)',['../dd/d46/page_tarch_home.html',1,'index']]],
  ['terminology_7',['Terminology',['../de/d8e/swift_terminology.html',1,'page_swift2_home']]],
  ['terminology_20and_20degree_20of_20freedom_20layout_8',['Terminology and degree of freedom layout',['../de/d44/page_multigrid_terminology.html',1,'page_multigrid_home']]],
  ['test_9',['test',['../dd/dc4/benchmarks_swift2_hydro_noh_imposion_test_2D.html',1,'2D Noh implosion test'],['../dd/d57/benchmarks_swift2_hydro_noh_imposion_test_3D.html',1,'3D Noh implosion test']]],
  ['test_10',['Test',['../d5/de2/tests_swift2_dastgen_test.html',1,'DastGen2 Test'],['../db/d44/tests_swift2_test_density_calculation.html',1,'Density Calculation Test']]],
  ['test_20boundary_20conditions_11',['Test boundary conditions',['../dc/d0d/tests_swift2_test_boundary_conditions.html',1,'swift_tests']]],
  ['test_20in_202d_12',['Noh implosion test in 2D',['../da/d75/tests_swift2_hydro_simple_sph_noh_2d.html',1,'swift_tests']]],
  ['test_20in_203d_13',['Noh implosion test in 3D',['../de/d0b/tests_swift2_hydro_simple_sph_noh_3d.html',1,'swift_tests']]],
  ['test_20single_20schwarzschild_20black_20hole_14',['Performance Test (Single Schwarzschild black hole)',['../d2/df4/benchmarks_exahype2_ccz4_single_black_hole_performance.html',1,'page_exahype_benchmarks']]],
  ['tests_15',['Poisson tests',['../db/d33/tests_multigrid_matrixfree_poisson.html',1,'']]],
  ['tests_16',['Tests',['../dc/dee/tests_swift2_test_smoothing_length_computation.html',1,'Smoothing Length Computation Tests'],['../d9/d95/swift_tests.html',1,'Tests']]],
  ['tests_17',['Unit tests',['../d3/d5f/tarch_tests.html',1,'page_tarch_home']]],
  ['the_20acoustic_20wave_20equation_18',['The Acoustic Wave Equation',['../dd/dea/page_tutorials_exahype2_symhype_acoustic.html',1,'page_exahype2_tutorials']]],
  ['the_20advection_20equation_19',['The Advection Equation',['../dd/d5a/page_tutorials_exahype2_symhype_advection.html',1,'page_exahype2_tutorials']]],
  ['the_20elastic_20wave_20equation_20',['The Elastic Wave Equation',['../d2/d68/page_tutorials_exahype2_symhype_elastic.html',1,'page_exahype2_tutorials']]],
  ['the_20euler_20equation_21',['The Euler Equation',['../dd/d92/page_tutorials_exahype2_symhype_euler.html',1,'page_exahype2_tutorials']]],
  ['the_20linear_20algebra_20steps_20over_20the_20mesh_20entities_22',['Design principle: Unfolding the linear algebra steps over the mesh entities',['../dd/d88/page_multigrid_unfolding.html',1,'page_multigrid_home']]],
  ['the_20mesh_20particle_20data_20consistency_23',['Sorting: Preserving the mesh-particle data consistency',['../db/d91/page_toolbox_particles_mesh_consistency.html',1,'toolbox_particles']]],
  ['the_20poisson_20equation_24',['the Poisson equation',['../df/d82/tutorials_mghype_numerics_continuous_galerkin_poisson.html',1,'Continuous Galerkin for the Poisson equation'],['../d5/d36/tutorials_multigrid_matrixfree_discontinuous_galerkin_poisson.html',1,'Matrix-free Discontinuous Galerkin for the Poisson equation'],['../d0/d2c/tutorials_multigrid_matrixfree_mixed_DG_poisson.html',1,'Matrix-free mixed DG for the Poisson equation']]],
  ['the_20poisson_20equation_20with_20petsc_25',['the Poisson equation with PETSc',['../dc/de6/tutorials_documentation_multigrid_petsc_continuous_galerkin_poisson.html',1,'Continuous Galerkin for the Poisson equation with PETSc'],['../d3/d42/tutorials_documentation_multigrid_petsc_discontinuous_galerkin_poisson.html',1,'Discontinuous Galerkin for the Poisson equation with PETSc'],['../d7/d6a/tutorials_documentation_multigrid_petsc_hybrid_galerkin_poisson.html',1,'Hybrid Galerkin for the Poisson equation with PETSc'],['../d5/d6b/tutorials_documentation_multigrid_petsc_mixed_galerkin_poisson.html',1,'Mixed Galerkin for the Poisson equation with PETSc']]],
  ['the_20shallow_20water_20equation_20swe_26',['The Shallow Water Equation (SWE)',['../d0/d10/page_tutorials_exahype2_symhype_swe.html',1,'page_exahype2_tutorials']]],
  ['the_20shallow_20water_20equations_27',['Benchmarks of Compute Kernels for the Shallow Water Equations',['../d5/d56/benchmarks_exahype2_shallow_water_kernel_benchmarks.html',1,'']]],
  ['the_20tafjord_20region_20of_20norway_28',['Landslide on the Tafjord Region of Norway',['../dd/d1f/applications_exahype2_shallow_water_tafjord_landslide.html',1,'applications_exahype2_shallow_water']]],
  ['the_20typical_20main_20cpp_20in_20a_20peano_20code_29',['The typical main.cpp in a Peano code',['../d7/d01/peano_main.html',1,'page_peano4_home']]],
  ['the_20visualisation_20and_20checkpointing_30',['Extend the visualisation (and checkpointing)',['../dc/d02/page_exahype_extend-visualisation.html',1,'page_exahype2_home']]],
  ['three_20mounds_31',['Flooding problem in a channel with three mounds',['../d1/db6/applications_exahype2_shallow_water_three_mounds_channel.html',1,'applications_exahype2_shallow_water']]],
  ['throughput_20benchmark_32',['Kernel throughput benchmark',['../db/d2e/benchmarks_swift2_hydro_kernel_throughput.html',1,'swift_benchmarks']]],
  ['to_20mesh_20entities_33',['Assigning data to mesh entities',['../d6/dd6/tutorials_peano4_assign_data_to_mesh.html',1,'tutorials_peano4_tutorials']]],
  ['to_20other_20codes_20and_20adding_20additional_20mesh_20sweeps_34',['Coupling ExaHyPE to other codes and adding additional mesh sweeps',['../d2/dee/page_exahype2_coupling.html',1,'page_exahype2_home']]],
  ['to_20use_20exagrype_35',['How to Use ExaGRyPE',['../da/dce/tutorials_exahype2_applications_exagrype.html',1,'page_exahype2_tutorials']]],
  ['todo_20list_36',['Todo List',['../dd/da0/todo.html',1,'']]],
  ['toolbox_37',['Toolbox',['../d7/d66/page_toolbox_home.html',1,'index']]],
  ['tracers_38',['Tracers',['../df/db9/page_exahype_tracer.html',1,'page_exahype2_home']]],
  ['tracing_39',['Otter task tracing',['../d3/d0d/tarch_multicore_otter.html',1,'']]],
  ['tracing_20statistics_20profiling_20and_20assertions_40',['Logging, tracing, statistics, profiling and assertions',['../d1/d9e/tarch_logging.html',1,'page_tarch_home']]],
  ['traversal_41',['Mesh traversal',['../d6/de2/page_toolbox_particles_mesh_traversal.html',1,'toolbox_particles']]],
  ['traversals_42',['Coupling of various solvers and additional mesh traversals',['../da/d8c/tutorials_exahype2_coupling.html',1,'page_exahype2_tutorials']]],
  ['troubleshooting_43',['FAQ and troubleshooting',['../d8/d6f/page_exahype_faq.html',1,'page_exahype2_home']]],
  ['troubleshooting_44',['TroubleShooting',['../df/dbc/tutorials_exahype2_applications_exagrype_faq.html',1,'tutorials_exahype2_applications_exagrype']]],
  ['troubleshooting_20user_20perspective_45',['FAQs and Troubleshooting (User Perspective)',['../d7/d3c/page_faq_home.html',1,'index']]],
  ['tsunami_46',['Tsunami',['../d3/df2/applications_exahype2_shallow_water_chile_tsunami.html',1,'2010 Chile Tsunami'],['../df/d26/applications_exahype2_shallow_water_tohoku_tsunami.html',1,'2011 Tōhoku Tsunami'],['../d7/db3/benchmarks_exahype2_shallow_water_artificial_tsunami.html',1,'Artificial Tsunami'],['../d6/d5c/applications_exahype2_shallow_water_artificial_tsunami.html',1,'Artificial Tsunami']]],
  ['tutorial_47',['Peano 4 Finite Volumes Tutorial',['../dd/d17/page_peano4_tutorials_finite_volumes.html',1,'tutorials_peano4_tutorials']]],
  ['tutorials_48',['Tutorials',['../d8/d60/page_exahype2_tutorials.html',1,'Tutorials'],['../d4/d49/page_mghype_tutorials.html',1,'Tutorials'],['../d3/d1a/tutorials_peano4_tutorials.html',1,'Tutorials'],['../d1/dad/swift_tutorials.html',1,'Tutorials']]],
  ['tutorials_20overview_49',['Tutorials Overview',['../d5/dda/page_tutorials_overview.html',1,'index']]],
  ['types_20solvers_20with_20new_20algorithmic_20steps_50',['Creating new particle types (solvers) with new algorithmic steps',['../d2/daf/swift_particle_new_solver.html',1,'page_swift2_home']]],
  ['typical_20main_20cpp_20in_20a_20peano_20code_51',['The typical main.cpp in a Peano code',['../d7/d01/peano_main.html',1,'page_peano4_home']]]
];
