var PlotPatchesOverFacesInPeanoBlockFormat_8py =
[
    [ "peano4.toolbox.blockstructured.PlotPatchesOverFacesInPeanoBlockFormat.PlotPatchesOverFacesInPeanoBlockFormat", "d3/d6d/classpeano4_1_1toolbox_1_1blockstructured_1_1PlotPatchesOverFacesInPeanoBlockFormat_1_1PlotPatchesOverFacesInPeanoBlockFormat.html", "d3/d6d/classpeano4_1_1toolbox_1_1blockstructured_1_1PlotPatchesOverFacesInPeanoBlockFormat_1_1PlotPatchesOverFacesInPeanoBlockFormat" ]
];