Peano
tarch::multicore::Core Class Reference
Core.
#include <Core.h>
Public Member Functions
~Core ()=default
bool init ()
void shutdown ()
Shutdown parallel environment.
bool isInitialised () const
int getNumberOfThreads () const
Returns the number of threads that is used.
int getCoreNumber () const
int getThreadNumber () const
void yield ()
Wrapper around backend-specific yield.
Static Public Member Functions
static Core & getInstance ()
Private Member Functions
Core ()=default
Private Attributes
int _numberOfThreads
Static Private Attributes
static tarch::logging::Log _log
Detailed Description
Core.
Any shared memory implementation has to provide a singleton Core. Its full qualified name is tarch::multicore::Core. If no shared memory variant is switched on, Peano provides a default Core implementation that does nothing.
Author
Tobias Weinzierl
Definition at line 46 of file Core.h.
Constructor & Destructor Documentation
Core()
tarch::multicore::Core::Core () private default
Definition at line 32 of file Core.cpp.
~Core()
tarch::multicore::Core::~Core () default
Definition at line 37 of file Core.cpp.
Member Function Documentation
getCoreNumber()
int tarch::multicore::Core::getCoreNumber () const
Returns
Physical core the process is running on
Definition at line 73 of file Core.cpp.
getInstance()
tarch::multicore::Core & tarch::multicore::Core::getInstance () static
Returns
Singleton instance
Definition at line 56 of file Core.cpp.
Referenced by examples::regulargridupscaling::MyObserver::enterCell(), tarch::logging::Log::error(), toolbox::loadbalancing::DefaultConfiguration::getMaxLocalTreesPerRank(), tarch::logging::CommandLineLogger::indent(), tarch::logging::Log::info(), peano4::init(), swift2::TaskEnumerator::lockResources(), main(), swift2::parseCommandLineArguments(), peano4::grid::TraversalVTKPlotter::plotCell(), runParallel(), peano4::shutdown(), step(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithBlockingReceives(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithBlockingSends(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithBlockingSendsAndReceives(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithNonblockingReceives(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithNonblockingSends(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithNonblockingSendsAndReceives(), exahype2::LoadBalancingConfiguration::translateSetMaxNumberOfTreesIntoRealNumberOfTrees(), toolbox::loadbalancing::LoadBalancer::updateIntraRankLoadBalancing(), tarch::logging::Log::warning(), and writeCopyrightMessage().
getNumberOfThreads()
int tarch::multicore::Core::getNumberOfThreads () const
Returns the number of threads that is used.
Returns
Number of threads available.
Definition at line 71 of file Core.cpp.
Referenced by examples::regulargridupscaling::MyObserver::enterCell(), toolbox::loadbalancing::DefaultConfiguration::getMaxLocalTreesPerRank(), main(), runParallel(), step(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithBlockingReceives(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithBlockingSends(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithBlockingSendsAndReceives(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithNonblockingReceives(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithNonblockingSends(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithNonblockingSendsAndReceives(), exahype2::LoadBalancingConfiguration::translateSetMaxNumberOfTreesIntoRealNumberOfTrees(), and toolbox::loadbalancing::LoadBalancer::updateIntraRankLoadBalancing().
getThreadNumber()
int tarch::multicore::Core::getThreadNumber () const
Returns
Logical thread number
Definition at line 82 of file Core.cpp.
init()
bool tarch::multicore::Core::init ()
Definition at line 63 of file Core.cpp.
Referenced by swift2::parseCommandLineArguments().
isInitialised()
bool tarch::multicore::Core::isInitialised () const
Returns
Shared memory environment is up and running. Most shared memory implementations work properly with the defaults. They just return true always.
Definition at line 69 of file Core.cpp.
shutdown()
void tarch::multicore::Core::shutdown ()
Shutdown parallel environment.
Definition at line 67 of file Core.cpp.
Referenced by peano4::shutdown().
yield()
void tarch::multicore::Core::yield ()
Wrapper around backend-specific yield.
For most backends, this should not really be a yield(). It should interrupt the current task, not the current thread, and tell the runtime to continue with another task.
Definition at line 84 of file Core.cpp.
Referenced by swift2::TaskEnumerator::lockResources().
Field Documentation
_log
tarch::logging::Log tarch::multicore::Core::_log static private
Definition at line 48 of file Core.h.
_numberOfThreads
int tarch::multicore::Core::_numberOfThreads private
Definition at line 52 of file Core.h.
The documentation for this class was generated from the following files:
src/tarch/multicore/Core.h
src/tarch/multicore/Core.cpp
src/tarch/multicore/tbb/Core.cpp