Peano
examples::exahype2::mgccz4::FiniteVolumeMGCCZ4 Class Reference
#include <FiniteVolumeMGCCZ4.h>
Public Member Functions
FiniteVolumeMGCCZ4 ()
void adjustSolution (double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &volumeCentre, const tarch::la::Vector< Dimensions, double > &volumeH, double t, double dt) override
void sourceTerm (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &volumeCentre, const tarch::la::Vector< Dimensions, double > &volumeH, double t, double dt, double *__restrict__ S)
virtual void boundaryConditions (const double *__restrict__ Qinside, double *__restrict__ Qoutside, const tarch::la::Vector< Dimensions, double > &faceCentre, const tarch::la::Vector< Dimensions, double > &volumeH, double t, int normal) override
double maxEigenvalue (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &faceCentre, const tarch::la::Vector< Dimensions, double > &volumeH, double t, int normal)
void nonconservativeProduct (const double *__restrict__ Q, const double *__restrict__ deltaQ, const tarch::la::Vector< Dimensions, double > &faceCentre, const tarch::la::Vector< Dimensions, double > &volumeH, double t, int normal, double *__restrict__ BgradQ)
Static Private Attributes
static tarch::logging::Log _log
Detailed Description
Definition at line 27 of file FiniteVolumeMGCCZ4.h.
Constructor & Destructor Documentation
FiniteVolumeMGCCZ4()
examples::exahype2::mgccz4::FiniteVolumeMGCCZ4::FiniteVolumeMGCCZ4 ()
Definition at line 23 of file FiniteVolumeMGCCZ4.cpp.
Member Function Documentation
adjustSolution()
void examples::exahype2::mgccz4::FiniteVolumeMGCCZ4::adjustSolution (double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & volumeCentre, const tarch::la::Vector< Dimensions, double > & volumeH, double t, double dt) override
Definition at line 35 of file FiniteVolumeMGCCZ4.cpp.
References assertion3, examples::exahype2::mgccz4::enforceMGCCZ4constraints(), tarch::la::equals(), examples::exahype2::mgccz4::forcedflat(), examples::exahype2::mgccz4::gaugeWave(), examples::exahype2::mgccz4::linearWave(), logError, logTraceInWith4Arguments, and logTraceOut.
boundaryConditions()
void examples::exahype2::mgccz4::FiniteVolumeMGCCZ4::boundaryConditions (const double *__restrict__ Qinside, double *__restrict__ Qoutside, const tarch::la::Vector< Dimensions, double > & faceCentre, const tarch::la::Vector< Dimensions, double > & volumeH, double t, int normal) override virtual
Definition at line 96 of file FiniteVolumeMGCCZ4.cpp.
References assertion4, logTraceInWith4Arguments, and logTraceOut.
maxEigenvalue()
double examples::exahype2::mgccz4::FiniteVolumeMGCCZ4::maxEigenvalue (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & faceCentre, const tarch::la::Vector< Dimensions, double > & volumeH, double t, int normal)
Definition at line 113 of file FiniteVolumeMGCCZ4.cpp.
References std::abs().
nonconservativeProduct()
void examples::exahype2::mgccz4::FiniteVolumeMGCCZ4::nonconservativeProduct (const double *__restrict__ Q, const double *__restrict__ deltaQ, const tarch::la::Vector< Dimensions, double > & faceCentre, const tarch::la::Vector< Dimensions, double > & volumeH, double t, int normal, double *__restrict__ BgradQ)
Definition at line 165 of file FiniteVolumeMGCCZ4.cpp.
References assertion, logTraceInWith4Arguments, logTraceOut, nonCriticalAssertion4, and pdencp_().
sourceTerm()
void examples::exahype2::mgccz4::FiniteVolumeMGCCZ4::sourceTerm (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & volumeCentre, const tarch::la::Vector< Dimensions, double > & volumeH, double t, double dt, double *__restrict__ S)
Definition at line 72 of file FiniteVolumeMGCCZ4.cpp.
References assertion3, logTraceInWith4Arguments, logTraceOut, nonCriticalAssertion3, and pdesource_().
Field Documentation
_log
tarch::logging::Log examples::exahype2::mgccz4::FiniteVolumeMGCCZ4::_log static private
Definition at line 29 of file FiniteVolumeMGCCZ4.h.
The documentation for this class was generated from the following files:
applications/exahype2/mgccz4/FiniteVolumeMGCCZ4.h
applications/exahype2/mgccz4/FiniteVolumeMGCCZ4.cpp