Peano
tarch::plotter::griddata::unstructured::UnstructuredGridWriter Class Reference abstract
#include <UnstructuredGridWriter.h>
Data Structures
class CellDataWriter
A writer for data on elements.
class CellWriter
Writes the cell.
class VertexDataWriter
A writer for scalar data on points (vertices).
class VertexWriter
This is the vertex writer you have to create to plot the vertices.
Public Member Functions
virtual ~UnstructuredGridWriter ()=default
virtual bool writeToFile ()=0
virtual bool isOpen ()=0
virtual void clear ()=0
Clear the writer, i.e.
virtual CellDataWriter * createCellDataWriter (const std::string &identifier, int recordsPerCell)=0
Caller has to destroy this instance manually.
virtual VertexDataWriter * createVertexDataWriter (const std::string &identifier, int recordsPerVertex)=0
Caller has to destroy this instance manually.
virtual VertexWriter * createVertexWriter ()=0
Caller has to destroy this instance manually.
virtual CellWriter * createCellWriter ()=0
Caller has to destroy this instance manually.
Detailed Description
Definition at line 20 of file UnstructuredGridWriter.h.
Constructor & Destructor Documentation
~UnstructuredGridWriter()
virtual tarch::plotter::griddata::unstructured::UnstructuredGridWriter::~UnstructuredGridWriter () virtual default
Member Function Documentation
clear()
virtual void tarch::plotter::griddata::unstructured::UnstructuredGridWriter::clear () pure virtual
Clear the writer, i.e.
erase all the data. However, as the writer does not track how many vertex and cell writers you've created, it's up to you to ensure that none of these instances is left.
Implemented in tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter, tarch::plotter::griddata::unstructured::vtk::VTKTextFileWriter, and tarch::plotter::griddata::unstructured::vtk::VTUTextFileWriter.
Referenced by peano4.output.Makefile.Makefile::__init__().
createCellDataWriter()
virtual CellDataWriter * tarch::plotter::griddata::unstructured::UnstructuredGridWriter::createCellDataWriter (const std::string & identifier, int recordsPerCell) pure virtual
Caller has to destroy this instance manually.
Implemented in tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter, tarch::plotter::griddata::unstructured::vtk::VTKTextFileWriter, and tarch::plotter::griddata::unstructured::vtk::VTUTextFileWriter.
createCellWriter()
virtual CellWriter * tarch::plotter::griddata::unstructured::UnstructuredGridWriter::createCellWriter () pure virtual
Caller has to destroy this instance manually.
Do not create more than one cell writer.
Implemented in tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter, tarch::plotter::griddata::unstructured::vtk::VTKTextFileWriter, and tarch::plotter::griddata::unstructured::vtk::VTUTextFileWriter.
Referenced by tarch::plotter::pointdata::vtk::VTKWriter::VTKWriter().
createVertexDataWriter()
virtual VertexDataWriter * tarch::plotter::griddata::unstructured::UnstructuredGridWriter::createVertexDataWriter (const std::string & identifier, int recordsPerVertex) pure virtual
Caller has to destroy this instance manually.
Implemented in tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter, tarch::plotter::griddata::unstructured::vtk::VTKTextFileWriter, and tarch::plotter::griddata::unstructured::vtk::VTUTextFileWriter.
createVertexWriter()
virtual VertexWriter * tarch::plotter::griddata::unstructured::UnstructuredGridWriter::createVertexWriter () pure virtual
Caller has to destroy this instance manually.
Do not create more than one vertex writer.
Implemented in tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter, tarch::plotter::griddata::unstructured::vtk::VTKTextFileWriter, and tarch::plotter::griddata::unstructured::vtk::VTUTextFileWriter.
Referenced by tarch::plotter::pointdata::vtk::VTKWriter::VTKWriter().
isOpen()
virtual bool tarch::plotter::griddata::unstructured::UnstructuredGridWriter::isOpen () pure virtual
Returns
Whether writer is ready to accept data.
Implemented in tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter, tarch::plotter::griddata::unstructured::vtk::VTKTextFileWriter, and tarch::plotter::griddata::unstructured::vtk::VTUTextFileWriter.
writeToFile()
virtual bool tarch::plotter::griddata::unstructured::UnstructuredGridWriter::writeToFile () pure virtual
Returns
Write has been successful
Implemented in tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter, tarch::plotter::griddata::unstructured::vtk::VTKTextFileWriter, and tarch::plotter::griddata::unstructured::vtk::VTUTextFileWriter.
The documentation for this class was generated from the following file:
src/tarch/plotter/griddata/unstructured/UnstructuredGridWriter.h