Peano
DefaultIteratorCRTP< TGrid, Derived, TIterationOrder > Class Template Reference
#include <linked_grid_iterator.h>
Public Types
using Grid = TGrid
using Item = Item<TGrid>
Public Member Functions
DefaultIteratorCRTP ()=default
DefaultIteratorCRTP (TIterationOrder order)
DefaultIteratorCRTP (Grid *top)
std::optional< Item > next ()
Protected Member Functions
constexpr EventEmitFlag emitFlags ()
bool enter (TGrid *)
bool exit (TGrid *)
bool hasNext ()
Protected Attributes
TIterationOrder iterationOrder
TGrid * cell = nullptr
Direction state = Direction::Enter
bool hasEmittedLast = false
Detailed Description
template<typename TGrid, typename Derived, typename TIterationOrder = NaturalOrder<TGrid>>
class DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >
Definition at line 54 of file linked_grid_iterator.h.
Member Typedef Documentation
Grid
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> using DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::Grid = TGrid
Definition at line 85 of file linked_grid_iterator.h.
Item
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> using DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::Item = Item<TGrid>
Definition at line 86 of file linked_grid_iterator.h.
Constructor & Destructor Documentation
DefaultIteratorCRTP() [1/3]
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::DefaultIteratorCRTP () default
DefaultIteratorCRTP() [2/3]
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::DefaultIteratorCRTP (TIterationOrder order) explicit
Definition at line 90 of file linked_grid_iterator.h.
DefaultIteratorCRTP() [3/3]
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::DefaultIteratorCRTP (Grid * top) explicit
Definition at line 92 of file linked_grid_iterator.h.
Member Function Documentation
emitFlags()
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> constexpr EventEmitFlag DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::emitFlags () constexpr protected
Definition at line 64 of file linked_grid_iterator.h.
References EmitEnter, and EmitExit.
enter()
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> bool DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::enter (TGrid *) protected
Definition at line 68 of file linked_grid_iterator.h.
exit()
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> bool DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::exit (TGrid *) protected
Definition at line 72 of file linked_grid_iterator.h.
hasNext()
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> bool DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::hasNext () protected
Definition at line 76 of file linked_grid_iterator.h.
next()
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> std::optional< Item > DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::next ()
Definition at line 94 of file linked_grid_iterator.h.
References EmitEnter, EmitExit, Enter, and Exit.
Referenced by LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::next(), LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >::next(), BottomUpIteratorCRTP< Spacetree, Derived, TIterationOrder >::next(), and BottomUpLeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >::next().
Field Documentation
cell
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> TGrid* DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::cell = nullptr protected
Definition at line 58 of file linked_grid_iterator.h.
hasEmittedLast
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> bool DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::hasEmittedLast = false protected
Definition at line 62 of file linked_grid_iterator.h.
iterationOrder
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> TIterationOrder DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::iterationOrder protected
Definition at line 56 of file linked_grid_iterator.h.
state
template<typename TGrid , typename Derived , typename TIterationOrder = NaturalOrder<TGrid>> Direction DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::state = Direction::Enter protected
Definition at line 60 of file linked_grid_iterator.h.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/grid/linked_grid_iterator.h