Peano
toolbox::blockstructured::tests::InterpolationTest Class Reference
#include <InterpolationTest.h>
Public Member Functions
InterpolationTest ()
Cosntructor.
virtual ~InterpolationTest ()=default
Destructor, empty.
virtual void run () override
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testRestrictHaloLayer_AoS_averaging ()
void testRestrictCellForBreakingDam ()
void testInterpolateCellDataAssociatedToVolumesIntoOverlappingCell_linear ()
Trivial interpolation test for constant data.
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Definition at line 17 of file InterpolationTest.h.
Constructor & Destructor Documentation
InterpolationTest()
toolbox::blockstructured::tests::InterpolationTest::InterpolationTest ()
Cosntructor.
Definition at line 13 of file InterpolationTest.cpp.
~InterpolationTest()
virtual toolbox::blockstructured::tests::InterpolationTest::~InterpolationTest () virtual default
Destructor, empty.
Member Function Documentation
run()
void toolbox::blockstructured::tests::InterpolationTest::run () override virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 18 of file InterpolationTest.cpp.
References testMethod.
testInterpolateCellDataAssociatedToVolumesIntoOverlappingCell_linear()
void toolbox::blockstructured::tests::InterpolationTest::testInterpolateCellDataAssociatedToVolumesIntoOverlappingCell_linear () private
Trivial interpolation test for constant data.
Definition at line 25 of file InterpolationTest.cpp.
References toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_linear(), and validateNumericalEqualsWithParams1.
testRestrictCellForBreakingDam()
void toolbox::blockstructured::tests::InterpolationTest::testRestrictCellForBreakingDam () private
Definition at line 60 of file InterpolationTest.cpp.
References toolbox::blockstructured::restrictCell_AoS_averaging(), and validateNumericalEquals.
testRestrictHaloLayer_AoS_averaging()
void toolbox::blockstructured::tests::InterpolationTest::testRestrictHaloLayer_AoS_averaging () private
   Tests this averaging
   The test results from a real test with the Euler equations and four
   unknowns per coordinate axis. The input is as follows:
parameter tarch::la::DynamicMatrix::vectorToString(fineGridFaceEulerQUpdate.value,4*2*5): (entries=40,
{
 0.100047, 0.000933957, 0,0,0.00493399,
 0.100045, 0.000870917, 0,0,0.0045799,
 0.100039, 0.000801622, 0,0,0.00422816,
 0.100045, 0.00081321,  0,0,0.0042177,
 0.100047, 0.000933957, 0,0,0.00493399,
 0.100045, 0.000870917, 2.71051e-20,0,0.0045799,
 0.100039, 0.000801622, 0,0,0.00422816,
 0.100045,0.00081321,0,0,0.0042177
})
Definition at line 130 of file InterpolationTest.cpp.
References toolbox::blockstructured::restrictHaloLayer_AoS_averaging(), peano4::grid::GridTraversalEvent::setRelativePositionToFather(), and validateNumericalEquals.
The documentation for this class was generated from the following files:
src/toolbox/blockstructured/tests/InterpolationTest.h
src/toolbox/blockstructured/tests/InterpolationTest.cpp