Peano
tarch Namespace Reference
tarch denotes the Technical Architectures.
Namespaces
namespace accelerator
namespace la
My collection of tiny vector operations.
namespace logging
namespace mpi
namespace multicore
This page describes Peano 4's multithreading namespace.
namespace plotter
namespace reader
namespace services
namespace tests
namespace timing
Data Structures
class Enumerator
Simple rank-global enumerator.
Enumerations
enum class MemoryLocation { Heap , Device , Pinned }
enum class MemoryUsageFormat { MByte , GByte }
Functions
template<class T = double>
T * allocateMemory (std::size_t count, MemoryLocation location, int device=accelerator::Device::DefaultDevice)
Allocates memory on the specified memory location.
template<class T = double>
T * reallocateMemory (void *memoryPtr, std::size_t count, MemoryLocation location, int device=accelerator::Device::DefaultDevice)
void freeMemory (void *memoryPtr, MemoryLocation location, int device=accelerator::Device::DefaultDevice)
Free memory.
template<class To , class From >
void copyTo (To *to, const From *from, std::size_t count, MemoryLocation location, int device=accelerator::Device::DefaultDevice)
template<class From , class To >
void copyFrom (const From *from, To *to, std::size_t count, MemoryLocation location, int device=accelerator::Device::DefaultDevice)
std::size_t padSizeToAlignment (std::size_t size, std::size_t alignment)
std::string toString (MemoryLocation value)
void shutdownNonCriticalAssertionEnvironment ()
peano4::shutdownParallelEnvironment().
void initNonCriticalAssertionEnvironment ()
Register the assertion tag from the global communicator.
void enableNonCriticalAssertions (bool value)
Switch noncritical assertions on/off.
void triggerNonCriticalAssertion (std::string file, int line, std::string expression, std::string parameterValuePairs)
Trigger a non-critical assertion.
bool hasNonCriticalAssertionBeenViolated ()
int convertMemorySize (long long value, MemoryUsageFormat format)
int getMemoryUsage (MemoryUsageFormat format)
Method for getting the application's memory footprint.
int getTotalMemory (MemoryUsageFormat format)
int getFreeMemory (MemoryUsageFormat format)
tarch::tests::TestCase * getUnitTests ()
Please destroy after usage.
Detailed Description
tarch denotes the Technical Architectures.
It is used within Peano, but it is designed in a way that it is more or less independent of Peano, i.e. Peano uses the tarch but not the other way round.
Please note that the tarch in the Peano4 repository/branch is not the same as the tarch in previous Peano versions. I've cleaned it up quite a lot and old features that are not used anymore are removed.
level
PeanoDebug = 1: Enable tracing
PeanoDebug = 2: Enable assertions (includes level 1)
PeanoDebug = 4: Enable debug messages (includes level 2)
libraries
By default, Peano 4 builds all core libraries in three different versions:
A debug variant which holds a compile with PeanoDebug=4
A trace variant which holds a compile with PeanoDebug=1
A production variants with PeanoDebug=0
Note: The trace variant does not contain any assertions, as assertions are typically expensive and slow down the code considerably.
Enumeration Type Documentation
MemoryLocation
enum class tarch::MemoryLocation strong
Enumerator
Heap
Create data on the heap of the host.
The alignment of this routine can be controlled via the compile time constant AlignmentOnHeap. It is typically set (to a default) within the corresponding compiler-specific header-file in tarch/compiler.
Device
Create data on the device.
Pinned
Definition at line 8 of file MemoryLocation.h.
MemoryUsageFormat
enum class tarch::MemoryUsageFormat strong
Enumerator
MByte
GByte
Definition at line 38 of file tarch.h.
Function Documentation
allocateMemory()
template<class T = double> T * tarch::allocateMemory (std::size_t count, MemoryLocation location, int device = accelerator::Device::DefaultDevice)
Allocates memory on the specified memory location.
The device id is an optional argument that is required for memory allocation on an accelerator. Default is 0 (DefaultDevice). For memory allocation on accelerators, passing a device id >= 0 is necessary.
Parameters
count Number of elements to allocate memory for.
location Location on where to allocate the memory.
device (Optional) device id for memory allocation on accelerators.
Definition at line 89 of file accelerator.h.
References tarch::accelerator::allocateRawData().
Referenced by toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_secondOrder(), tarch::la::SmartPointerVector< Size, Scalar >::SmartPointerVector(), toolbox::blockstructured::tests::IandRVolumetricTest::testMatrixInterpolation(), and exahype2::fv::musclhancock::timeStepWithMusclHancock_patchwise_heap_functors().
convertMemorySize()
int tarch::convertMemorySize (long long value, MemoryUsageFormat format)
Definition at line 37 of file tarch.cpp.
References GByte, logError, and MByte.
Referenced by tarch::accelerator::MemoryManager::getFreeAllocatedMemory(), tarch::accelerator::MemoryManager::getFreeAllocatedMemory(), getFreeMemory(), getMemoryUsage(), getTotalMemory(), tarch::accelerator::MemoryManager::getUsedAllocatedMemory(), and tarch::accelerator::MemoryManager::getUsedAllocatedMemory().
copyFrom()
template<class From , class To > void tarch::copyFrom (const From * from, To * to, std::size_t count, MemoryLocation location, int device = accelerator::Device::DefaultDevice)
Definition at line 139 of file accelerator.h.
References tarch::accelerator::copyFrom().
copyTo()
template<class To , class From > void tarch::copyTo (To * to, const From * from, std::size_t count, MemoryLocation location, int device = accelerator::Device::DefaultDevice)
Definition at line 127 of file accelerator.h.
References tarch::accelerator::copyTo().
enableNonCriticalAssertions()
void tarch::enableNonCriticalAssertions (bool value)
Switch noncritical assertions on/off.
Definition at line 41 of file NonCriticalAssertions.cpp.
freeMemory()
void tarch::freeMemory (void * memoryPtr, MemoryLocation location, int device = accelerator::Device::DefaultDevice)
Free memory.
This routine is thread-safe in the sense that it checks if data actually point to something that is not nullptr. If data is the nullptr, the operation degenerates to nop. This is important as we use the routine within smart pointers, where we don't want to check manually if data is actually nullptr or not.
Definition at line 122 of file accelerator.cpp.
Referenced by exahype2::fd::applySommerfeldConditions(), toolbox::blockstructured::tests::IandRInMatricesTest::compareInterpolateLinearCaseToTensorProductPatch(), toolbox::blockstructured::tests::IandRInMatricesTest::compareRestrictLinearCaseToTensorProductPatch(), tarch::la::DynamicMatrix::insertEmptyColumns(), tarch::la::DynamicMatrix::insertEmptyRows(), toolbox::blockstructured::interpolateHaloLayer_AoS_linear_with_constant_extrapolation(), toolbox::blockstructured::interpolateHaloLayer_AoS_linear_with_constant_extrapolation_and_linear_normal_interpolation(), toolbox::blockstructured::interpolateHaloLayer_AoS_linear_with_linear_extrapolation(), toolbox::blockstructured::interpolateHaloLayer_AoS_linear_with_linear_extrapolation_and_linear_normal_interpolation(), toolbox::blockstructured::interpolateHaloLayer_AoS_piecewise_constant(), tarch::la::DynamicMatrix::removeColumn(), tarch::la::DynamicMatrix::replicateCols(), tarch::la::DynamicMatrix::replicateRows(), runBenchmark(), runBenchmarks(), variant1::runBenchmarks(), variant2::runBenchmarks(), variant3::runBenchmarks(), variant4::runBenchmarks(), variant5::runBenchmarks(), variant6::runBenchmarks(), toolbox::particles::memorypool::GlobalContinuousMemoryPool< T >::scatter(), toolbox::particles::memorypool::VertexWiseContinuousMemoryPool< T >::scatter(), toolbox::particles::memorypool::GlobalContinuousMemoryPool< T >::scatterAndUpdateIterator(), toolbox::particles::memorypool::VertexWiseContinuousMemoryPool< T >::scatterAndUpdateIterator(), tarch::la::DynamicMatrix::shiftColumnsRight(), tarch::la::DynamicMatrix::shiftRowsDown(), tarch::la::SmartPointerVector< Size, Scalar >::SmartPointerVector(), exahype2::fv::tests::ApplySplit1DRiemannToPatchTest::testIterateGrid(), toolbox::blockstructured::tests::IandRVolumetricTest::testMatrixInterpolation(), exahype2::fd::fd4::timeStep_patchwise_heap_functors(), exahype2::fv::musclhancock::timeStepWithMusclHancock_patchwise_heap_functors(), peano4::stacks::STDVectorStackOverSmartPointers< T >::tryToFinishSendOrReceive(), and tarch::la::DynamicMatrix::~DynamicMatrix().
getFreeMemory()
int tarch::getFreeMemory (MemoryUsageFormat format)
Definition at line 73 of file tarch.cpp.
References convertMemorySize().
Referenced by tarch::accelerator::MemoryManager::getStatistics().
getMemoryUsage()
int tarch::getMemoryUsage (MemoryUsageFormat format)
Method for getting the application's memory footprint.
We use the exact version of KiloByte with 1024 bytes.
The implementation is based on C-version of Michael Moltenbrey.
Definition at line 105 of file tarch.cpp.
References _log, convertMemorySize(), and logError.
Referenced by tarch::accelerator::MemoryManager::getStatistics().
getTotalMemory()
int tarch::getTotalMemory (MemoryUsageFormat format)
Definition at line 66 of file tarch.cpp.
References convertMemorySize().
Referenced by tarch::accelerator::MemoryManager::getStatistics().
getUnitTests()
tarch::tests::TestCase * tarch::getUnitTests ()
Please destroy after usage.
Definition at line 17 of file UnitTests.cpp.
References tarch::tests::TreeTestCaseCollection::addTestCase().
Referenced by main(), and runTests().
hasNonCriticalAssertionBeenViolated()
bool tarch::hasNonCriticalAssertionBeenViolated ()
Definition at line 93 of file NonCriticalAssertions.cpp.
References _log, tarch::mpi::Rank::getCommunicator(), tarch::mpi::Rank::getInstance(), tarch::mpi::IntegerMessage::getValue(), logError, and tarch::mpi::IntegerMessage::receive().
Referenced by selectNextAlgorithmicStep().
initNonCriticalAssertionEnvironment()
void tarch::initNonCriticalAssertionEnvironment ()
Register the assertion tag from the global communicator.
Definition at line 53 of file NonCriticalAssertions.cpp.
References tarch::mpi::Rank::reserveFreeTag().
Referenced by peano4::init(), and main().
padSizeToAlignment()
std::size_t tarch::padSizeToAlignment (std::size_t size, std::size_t alignment)
Definition at line 126 of file accelerator.cpp.
References assertion1.
Referenced by tarch::accelerator::allocateRawData().
reallocateMemory()
template<class T = double> T * tarch::reallocateMemory (void * memoryPtr, std::size_t count, MemoryLocation location, int device = accelerator::Device::DefaultDevice)
Definition at line 100 of file accelerator.h.
References tarch::accelerator::reallocateRawData().
shutdownNonCriticalAssertionEnvironment()
void tarch::shutdownNonCriticalAssertionEnvironment ()
peano4::shutdownParallelEnvironment().
Definition at line 46 of file NonCriticalAssertions.cpp.
References tarch::mpi::Rank::releaseTag().
Referenced by main(), and peano4::shutdown().
toString()
std::string tarch::toString (MemoryLocation value)
Definition at line 6 of file MemoryLocation.cpp.
Referenced by tarch::la::DynamicMatrix::insertEmptyColumns(), tarch::la::DynamicMatrix::insertEmptyRows(), tarch::timing::Measurement::max(), tarch::timing::Measurement::min(), tarch::la::SmartPointerVector< Size, Scalar >::operator()(), tarch::la::Vector< Size, Scalar >::operator()(), tarch::la::SmartPointerVector< Size, Scalar >::operator()(), tarch::la::Vector< Size, Scalar >::operator()(), tarch::la::SmartPointerVector< Size, Scalar >::operator[](), tarch::la::Vector< Size, Scalar >::operator[](), tarch::la::SmartPointerVector< Size, Scalar >::operator[](), tarch::la::Vector< Size, Scalar >::operator[](), tarch::la::tests::VectorTest::testAssignment(), tarch::la::tests::VectorTest::testVectorScalarOperations(), and tarch::la::tests::VectorTest::testWrappedVector().
triggerNonCriticalAssertion()
void tarch::triggerNonCriticalAssertion (std::string file, int line, std::string expression, std::string parameterValuePairs)
Trigger a non-critical assertion.
You can either use this routine, or you can use the macros. They invoke this routine eventually.
The routine reports only details about the very first non-critical assertion. All follow-up logs on this rank are ignored, i.e. we only get a note and no detail. Once logged locally, we send the assertion message to the global master if we are not working on the global marker ourselves.
Definition at line 60 of file NonCriticalAssertions.cpp.
References _log, tarch::mpi::Rank::getGlobalMasterRank(), tarch::mpi::Rank::getInstance(), tarch::mpi::Rank::getRank(), logDebug, logError, and tarch::mpi::IntegerMessage::send().