Peano
grid.cpp File Reference
#include "grid.h"
#include "GridVertex.h"
#include "AutomatonState.h"
#include "GridControlEvent.h"
#include "GridStatistics.h"
#include "Spacetree.h"
#include "peano4/utils/Loop.h"
Functions
std::ostream & operator<< (std::ostream &out, const peano4::SplitInstruction &instruction)
std::ostream & operator<< (std::ostream &out, const peano4::SplitInstruction::Mode &mode)
peano4::grid::GridStatistics operator+ (peano4::grid::GridStatistics lhs, peano4::grid::GridStatistics rhs)
Function Documentation
operator+()
peano4::grid::GridStatistics operator+ (peano4::grid::GridStatistics lhs, peano4::grid::GridStatistics rhs)
Definition at line 217 of file grid.cpp.
References peano4::grid::GridStatistics::getCoarseningHasBeenVetoed(), peano4::grid::GridStatistics::getMinH(), peano4::grid::GridStatistics::getNumberOfLocalRefinedCells(), peano4::grid::GridStatistics::getNumberOfLocalUnrefinedCells(), peano4::grid::GridStatistics::getNumberOfRemoteRefinedCells(), peano4::grid::GridStatistics::getNumberOfRemoteUnrefinedCells(), peano4::grid::GridStatistics::getRemovedEmptySubtree(), peano4::grid::GridStatistics::getStationarySweeps(), and tarch::la::min().
operator<<() [1/2]
std::ostream & operator<< (std::ostream & out, const peano4::SplitInstruction & instruction)
Definition at line 30 of file grid.cpp.
References peano4::SplitInstruction::toString().
operator<<() [2/2]
std::ostream & operator<< (std::ostream & out, const peano4::SplitInstruction::Mode & mode)
Definition at line 35 of file grid.cpp.
References peano4::SplitInstruction::toString().