Peano
peano4.toolbox.api.EnumerateCellsAndVertices Namespace Reference
Data Structures
class AssignNumbersToMesh
Gives each mesh entity a unique number.
class ClearNumbersOnMesh
Clear all the numbers on the mesh.
Functions
construct_marker_name (task_name)
create_vertex_marker (task_name, full_qualified_enumerator_type="tarch::Enumerator", enumerator_include=""" #include "tarch/Enumerator.h" """)
Create vertex marker.
create_cell_marker (task_name)
Create cell marker for tasking.
Variables
str TaskMarkerIdentifier = "TaskMarker"
int UndefinedNumber = -1
Function Documentation
construct_marker_name()
peano4.toolbox.api.EnumerateCellsAndVertices.construct_marker_name (task_name)
Definition at line 15 of file EnumerateCellsAndVertices.py.
Referenced by swift2.api.actionsets.TaskGraphKernelWrappers.construct_touch_cell_first_time_call(), swift2.api.actionsets.TaskGraphKernelWrappers.construct_touch_vertex_first_time_call(), and swift2.api.actionsets.TaskGraphKernelWrappers.construct_touch_vertex_last_time_call().
create_cell_marker()
peano4.toolbox.api.EnumerateCellsAndVertices.create_cell_marker (task_name)
Create cell marker for tasking.
This marker can be used for cells.
See also
create_vertex_marker() for some usage information.
Definition at line 76 of file EnumerateCellsAndVertices.py.
Referenced by swift2.Project.Project.generate_Peano4_project().
create_vertex_marker()
peano4.toolbox.api.EnumerateCellsAndVertices.create_vertex_marker (task_name, full_qualified_enumerator_type = "tarch::Enumerator", enumerator_include = """ #include "tarch/Enumerator.h" """)
Create vertex marker.
This marker can be used for vertices. The numbers are then typically used for some kind of task system or external referencing. Similar systems are also used linear algebra, i.e. where you enumerate mesh entities, but this one is different as a vertex holds information about its adjacent cells' numbers.
If you want to use the action sets from this file, you have to run create markers for the vertices and the cells, and you have to add them to the mesh:
cell_marker_for_tasks   = peano4.toolbox.api.EnumerateCellsAndVertices.create_cell_marker(current_species_set.name)
vertex_marker_for_tasks = peano4.toolbox.api.EnumerateCellsAndVertices.create_vertex_marker(current_species_set.name)
self._project.datamodel.add_cell(cell_marker_for_tasks)
self._project.datamodel.add_vertex(vertex_marker_for_tasks)
Furthermore, you have to add the use_vertex and use_cell instructions to each observer (algorithm step) before you add the action sets to the sets in turn.
Please note that this marker not only holds an index for the vertex. It also hosts the markers of the adjacent cells.
Definition at line 19 of file EnumerateCellsAndVertices.py.
Referenced by swift2.Project.Project.generate_Peano4_project().
Variable Documentation
TaskMarkerIdentifier
str peano4.toolbox.api.EnumerateCellsAndVertices.TaskMarkerIdentifier = "TaskMarker"
Definition at line 11 of file EnumerateCellsAndVertices.py.
UndefinedNumber
int peano4.toolbox.api.EnumerateCellsAndVertices.UndefinedNumber = -1
Definition at line 12 of file EnumerateCellsAndVertices.py.