Peano
Node Class Reference abstract
#include <node.h>
Public Member Functions
virtual BlockBoundary traverse (int index[3])=0
virtual BlockBoundary traverseProjection (double coordinate[3])=0
virtual Block traverse ()=0
virtual void init (BlockBoundary &boundary, uint modes[3])=0
virtual std::string toString (int depth=0)=0
Detailed Description
Definition at line 14 of file node.h.
Member Function Documentation
init()
virtual void Node::init (BlockBoundary & boundary, uint modes[3]) pure virtual
Implemented in Leaf, and InnerNode.
Referenced by InnerNode::init(), and Root::init().
toString()
virtual std::string Node::toString (int depth = 0) pure virtual
Implemented in InnerNode, and Leaf.
Referenced by InnerNode::toString(), and Root::toString().
traverse() [1/2]
virtual Block Node::traverse () pure virtual
Implemented in InnerNode, and Leaf.
traverse() [2/2]
virtual BlockBoundary Node::traverse (int index[3]) pure virtual
Implemented in InnerNode, and Leaf.
Referenced by InnerNode::traverse(), Root::traverse(), InnerNode::traverse(), and Root::traverse().
traverseProjection()
virtual BlockBoundary Node::traverseProjection (double coordinate[3]) pure virtual
Implemented in InnerNode, and Leaf.
Referenced by InnerNode::traverseProjection(), and Root::traverseProjection().
The documentation for this class was generated from the following file:
src/toolbox/curvi/kdTree/node.h