Peano
exahype2::dg::tests::DGUtilsTest Class Reference
#include <DGUtilsTest.h>
Public Member Functions
DGUtilsTest ()
virtual ~DGUtilsTest ()=default
void run () override
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testGetIndex ()
void testComputeGradientOnConstantSolution ()
void testEvaluatePolynomialOrder1 ()
void testEvaluatePolynomialOrder2 ()
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Definition at line 18 of file DGUtilsTest.h.
Constructor & Destructor Documentation
DGUtilsTest()
exahype2::dg::tests::DGUtilsTest::DGUtilsTest ()
Definition at line 12 of file DGUtilsTest.cpp.
~DGUtilsTest()
virtual exahype2::dg::tests::DGUtilsTest::~DGUtilsTest () virtual default
Member Function Documentation
run()
void exahype2::dg::tests::DGUtilsTest::run () override virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 17 of file DGUtilsTest.cpp.
References testMethod.
testComputeGradientOnConstantSolution()
void exahype2::dg::tests::DGUtilsTest::testComputeGradientOnConstantSolution () private
Definition at line 149 of file DGUtilsTest.cpp.
References exahype2::dg::computeGradient(), exahype2::dg::tests::DerivativeOperatorLagrangeP3, exahype2::dg::getNodesPerCell(), and validateNumericalEquals.
testEvaluatePolynomialOrder1()
void exahype2::dg::tests::DGUtilsTest::testEvaluatePolynomialOrder1 () private
Definition at line 25 of file DGUtilsTest.cpp.
References exahype2::dg::evaluatePolynomial(), exahype2::dg::tests::QuadratureNodes1dP1, peano4::grid::GridTraversalEvent::setH(), peano4::grid::GridTraversalEvent::setX(), peano4::datamanagement::CellMarker::toString(), and validateNumericalEqualsWithParams1.
testEvaluatePolynomialOrder2()
void exahype2::dg::tests::DGUtilsTest::testEvaluatePolynomialOrder2 () private
Definition at line 71 of file DGUtilsTest.cpp.
References exahype2::dg::evaluatePolynomial(), exahype2::dg::tests::QuadratureNodes1dP1, exahype2::dg::tests::QuadratureNodes1dP2, peano4::grid::GridTraversalEvent::setH(), peano4::grid::GridTraversalEvent::setX(), peano4::datamanagement::CellMarker::toString(), and validateNumericalEqualsWithParams1.
testGetIndex()
void exahype2::dg::tests::DGUtilsTest::testGetIndex () private
Definition at line 127 of file DGUtilsTest.cpp.
References exahype2::dg::getIndex(), exahype2::dg::getNodesPerCell(), exahype2::dg::getStrides(), and validateEquals.
The documentation for this class was generated from the following files:
src/exahype2/dg/tests/DGUtilsTest.h
src/exahype2/dg/tests/DGUtilsTest.cpp