var petsc_2api_2actionsets_2PlotDGDataInPeanoBlockFormat_8py =
[
    [ "api.actionsets.PlotDGDataInPeanoBlockFormat.PlotDGDataInPeanoBlockFormat", "d1/dc9/classapi_1_1actionsets_1_1PlotDGDataInPeanoBlockFormat_1_1PlotDGDataInPeanoBlockFormat.html", "d1/dc9/classapi_1_1actionsets_1_1PlotDGDataInPeanoBlockFormat_1_1PlotDGDataInPeanoBlockFormat" ]
];