Peano
toolbox::loadbalancing::Statistics Class Reference
Statistics helper routine for load balancing.
#include <Statistics.h>
Public Member Functions
Statistics ()
Set all the MPI requests to nullptr.
~Statistics ()=default
void updateGlobalView ()
int getLocalNumberOfInnerUnrefinedCells () const
int getGlobalNumberOfInnerUnrefinedCells () const
int getLocalNumberOfTrees () const
int getGlobalNumberOfTrees () const
void incLocalNumberOfSplits (int delta=1)
int getNumberOfStateUpdatesWithoutAnySplit () const
int getGlobalNumberOfRanksWithEnabledLoadBalancing () const
bool hasConsistentViewOfWorld () const
If the stats spot some inconsistencies (local number of cells is bigger than global number, e.g.) this means that the non-blocking data exchange is lagging behind.
void notifyOfStateChange (State state)
std::string toString () const
Private Member Functions
void waitForGlobalDataExchange ()
Private Attributes
int _localNumberOfInnerUnrefinedCells
int _globalNumberOfInnerUnrefinedCells
int _localNumberOfTrees
int _globalNumberOfTrees
bool _isLocalLoadBalancingEnabled
int _globalNumberOfRanksWithEnabledLoadBalancing
int _localNumberOfSplits
This is my local accumulator where I keep track of how often I did split in this iteration.
int _globalNumberOfSplits
Lags behind global number by one iteration in an MPI world as data will arrive with one iteration delay.
int _numberOfStateUpdatesWithoutAnySplit
bool _isViewConsistent
MPI_Request * _globalNumberOfInnerUnrefinedCellsRequest
Required for local stats, but also replicated in cell count metrics.
MPI_Request * _globalNumberOfSplitsRequest
MPI_Request * _globalNumberOfTreesRequest
MPI_Request * _globalNumberOfRanksWithEnabledLoadBalancingRequest
int _globalNumberOfInnerUnrefinedCellsBufferIn
int _globalNumberOfInnerUnrefinedCellsBufferOut
int _globalNumberOfSplitsIn
int _globalNumberOfSplitsOut
int _globalNumberOfTreesIn
int _globalNumberOfTreesOut
int _globalNumberOfRanksWithEnabledLoadBalancingIn
int _globalNumberOfRanksWithEnabledLoadBalancingOut
Static Private Attributes
static tarch::logging::Log _log
Detailed Description
Statistics helper routine for load balancing.
Please note that we assume a SPMD paradigm, i.e. if one rank uses statistics, the other ranks all have to use such an object, too. The individual objects communicate with each other.
Definition at line 23 of file Statistics.h.
Constructor & Destructor Documentation
Statistics()
toolbox::loadbalancing::Statistics::Statistics ()
Set all the MPI requests to nullptr.
Definition at line 10 of file Statistics.cpp.
References _globalNumberOfInnerUnrefinedCellsRequest, _globalNumberOfRanksWithEnabledLoadBalancingRequest, _globalNumberOfSplitsRequest, and _globalNumberOfTreesRequest.
~Statistics()
toolbox::loadbalancing::Statistics::~Statistics () default
Member Function Documentation
getGlobalNumberOfInnerUnrefinedCells()
int toolbox::loadbalancing::Statistics::getGlobalNumberOfInnerUnrefinedCells () const
Definition at line 147 of file Statistics.cpp.
getGlobalNumberOfRanksWithEnabledLoadBalancing()
int toolbox::loadbalancing::Statistics::getGlobalNumberOfRanksWithEnabledLoadBalancing () const
Definition at line 164 of file Statistics.cpp.
getGlobalNumberOfTrees()
int toolbox::loadbalancing::Statistics::getGlobalNumberOfTrees () const
Definition at line 153 of file Statistics.cpp.
getLocalNumberOfInnerUnrefinedCells()
int toolbox::loadbalancing::Statistics::getLocalNumberOfInnerUnrefinedCells () const
Definition at line 143 of file Statistics.cpp.
getLocalNumberOfTrees()
int toolbox::loadbalancing::Statistics::getLocalNumberOfTrees () const
Definition at line 151 of file Statistics.cpp.
getNumberOfStateUpdatesWithoutAnySplit()
int toolbox::loadbalancing::Statistics::getNumberOfStateUpdatesWithoutAnySplit () const
Definition at line 160 of file Statistics.cpp.
hasConsistentViewOfWorld()
bool toolbox::loadbalancing::Statistics::hasConsistentViewOfWorld () const
If the stats spot some inconsistencies (local number of cells is bigger than global number, e.g.) this means that the non-blocking data exchange is lagging behind.
In this case, this routine returns false;
Definition at line 168 of file Statistics.cpp.
incLocalNumberOfSplits()
void toolbox::loadbalancing::Statistics::incLocalNumberOfSplits (int delta = 1)
Definition at line 155 of file Statistics.cpp.
References assertion.
notifyOfStateChange()
void toolbox::loadbalancing::Statistics::notifyOfStateChange (State state)
Definition at line 170 of file Statistics.cpp.
References state, and toolbox::loadbalancing::SwitchedOff.
Referenced by toolbox::loadbalancing::LoadBalancer::LoadBalancer().
toString()
std::string toolbox::loadbalancing::Statistics::toString () const
Definition at line 174 of file Statistics.cpp.
updateGlobalView()
void toolbox::loadbalancing::Statistics::updateGlobalView ()
Definition at line 51 of file Statistics.cpp.
References peano4::parallel::SpacetreeSet::getGridStatistics(), peano4::parallel::SpacetreeSet::getInstance(), tarch::mpi::Rank::getInstance(), peano4::parallel::SpacetreeSet::getLocalSpacetrees(), peano4::grid::GridStatistics::getNumberOfLocalUnrefinedCells(), and logDebug.
waitForGlobalDataExchange()
void toolbox::loadbalancing::Statistics::waitForGlobalDataExchange () private
Definition at line 30 of file Statistics.cpp.
Field Documentation
_globalNumberOfInnerUnrefinedCells
int toolbox::loadbalancing::Statistics::_globalNumberOfInnerUnrefinedCells private
Definition at line 58 of file Statistics.h.
_globalNumberOfInnerUnrefinedCellsBufferIn
int toolbox::loadbalancing::Statistics::_globalNumberOfInnerUnrefinedCellsBufferIn private
Definition at line 93 of file Statistics.h.
_globalNumberOfInnerUnrefinedCellsBufferOut
int toolbox::loadbalancing::Statistics::_globalNumberOfInnerUnrefinedCellsBufferOut private
Definition at line 94 of file Statistics.h.
_globalNumberOfInnerUnrefinedCellsRequest
MPI_Request* toolbox::loadbalancing::Statistics::_globalNumberOfInnerUnrefinedCellsRequest private
Required for local stats, but also replicated in cell count metrics.
Definition at line 87 of file Statistics.h.
Referenced by Statistics().
_globalNumberOfRanksWithEnabledLoadBalancing
int toolbox::loadbalancing::Statistics::_globalNumberOfRanksWithEnabledLoadBalancing private
Definition at line 64 of file Statistics.h.
_globalNumberOfRanksWithEnabledLoadBalancingIn
int toolbox::loadbalancing::Statistics::_globalNumberOfRanksWithEnabledLoadBalancingIn private
Definition at line 99 of file Statistics.h.
_globalNumberOfRanksWithEnabledLoadBalancingOut
int toolbox::loadbalancing::Statistics::_globalNumberOfRanksWithEnabledLoadBalancingOut private
Definition at line 100 of file Statistics.h.
_globalNumberOfRanksWithEnabledLoadBalancingRequest
MPI_Request* toolbox::loadbalancing::Statistics::_globalNumberOfRanksWithEnabledLoadBalancingRequest private
Definition at line 90 of file Statistics.h.
Referenced by Statistics().
_globalNumberOfSplits
int toolbox::loadbalancing::Statistics::_globalNumberOfSplits private
Lags behind global number by one iteration in an MPI world as data will arrive with one iteration delay.
Definition at line 77 of file Statistics.h.
_globalNumberOfSplitsIn
int toolbox::loadbalancing::Statistics::_globalNumberOfSplitsIn private
Definition at line 95 of file Statistics.h.
_globalNumberOfSplitsOut
int toolbox::loadbalancing::Statistics::_globalNumberOfSplitsOut private
Definition at line 96 of file Statistics.h.
_globalNumberOfSplitsRequest
MPI_Request* toolbox::loadbalancing::Statistics::_globalNumberOfSplitsRequest private
Definition at line 88 of file Statistics.h.
Referenced by Statistics().
_globalNumberOfTrees
int toolbox::loadbalancing::Statistics::_globalNumberOfTrees private
Definition at line 61 of file Statistics.h.
_globalNumberOfTreesIn
int toolbox::loadbalancing::Statistics::_globalNumberOfTreesIn private
Definition at line 97 of file Statistics.h.
_globalNumberOfTreesOut
int toolbox::loadbalancing::Statistics::_globalNumberOfTreesOut private
Definition at line 98 of file Statistics.h.
_globalNumberOfTreesRequest
MPI_Request* toolbox::loadbalancing::Statistics::_globalNumberOfTreesRequest private
Definition at line 89 of file Statistics.h.
Referenced by Statistics().
_isLocalLoadBalancingEnabled
bool toolbox::loadbalancing::Statistics::_isLocalLoadBalancingEnabled private
Definition at line 63 of file Statistics.h.
_isViewConsistent
bool toolbox::loadbalancing::Statistics::_isViewConsistent private
Definition at line 81 of file Statistics.h.
_localNumberOfInnerUnrefinedCells
int toolbox::loadbalancing::Statistics::_localNumberOfInnerUnrefinedCells private
Definition at line 57 of file Statistics.h.
_localNumberOfSplits
int toolbox::loadbalancing::Statistics::_localNumberOfSplits private
This is my local accumulator where I keep track of how often I did split in this iteration.
At the end of each iteration, I roll this one over into global or send it out.
Definition at line 71 of file Statistics.h.
_localNumberOfTrees
int toolbox::loadbalancing::Statistics::_localNumberOfTrees private
Definition at line 60 of file Statistics.h.
_log
tarch::logging::Log toolbox::loadbalancing::Statistics::_log static private
Definition at line 55 of file Statistics.h.
_numberOfStateUpdatesWithoutAnySplit
int toolbox::loadbalancing::Statistics::_numberOfStateUpdatesWithoutAnySplit private
Definition at line 79 of file Statistics.h.
The documentation for this class was generated from the following files:
src/toolbox/loadbalancing/Statistics.h
src/toolbox/loadbalancing/Statistics.cpp