Peano
peano4::grid::GridTraversalEvent Struct Reference
#include <GridTraversalEvent.h>
Public Types
enum ObjectConstruction { NoData }
Public Member Functions
GridTraversalEvent ()=default
GridTraversalEvent (const tarch::la::Vector< Dimensions, double > &__x, const tarch::la::Vector< Dimensions, double > &__h, const std::bitset< TwoPowerD > &__hasBeenRefined, const std::bitset< TwoPowerD > &__willBeRefined, const std::bitset< TwoPowerD > &__isVertexLocal, const std::bitset< TwoPowerD > &__isParentVertexLocal, const std::bitset< TwoPowerD > &__isVertexParentOfSubtree, const std::bitset< TwoTimesD > &__isFaceLocal, const bool __isCellLocal, const bool __isParentCellLocal, const std::bitset< TwoPowerD > &__isVertexAdjacentToParallelDomainBoundary, const std::bitset< TwoTimesD > &__isFaceAdjacentToParallelDomainBoundary, const tarch::la::Vector< TwoPowerD, int > &__numberOfAdjacentTreesPerVertex, const std::bitset< ThreePowerD > &__isAdjacentCellLocal, const tarch::la::Vector< TwoPowerD, int > &__vertexDataFrom, const tarch::la::Vector< TwoPowerD, int > &__vertexDataTo, const tarch::la::Vector< TwoTimesD, int > &__faceDataFrom, const tarch::la::Vector< TwoTimesD, int > &__faceDataTo, const int __cellData, const tarch::la::Vector< Dimensions, int > &__relativePositionToFather, const int __invokingSpacetree, const bool __invokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing)
GridTraversalEvent (const GridTraversalEvent &copy)
tarch::la::Vector< Dimensions, double > getX () const
double getX (int index) const
void setX (int index, double value)
void setX (const tarch::la::Vector< Dimensions, double > &value)
tarch::la::Vector< Dimensions, double > getH () const
double getH (int index) const
void setH (int index, double value)
void setH (const tarch::la::Vector< Dimensions, double > &value)
std::bitset< TwoPowerD > getHasBeenRefined () const
bool getHasBeenRefined (int index) const
void setHasBeenRefined (int index, bool value)
void setHasBeenRefined (const std::bitset< TwoPowerD > &value)
void flipHasBeenRefined (int index)
std::bitset< TwoPowerD > getWillBeRefined () const
bool getWillBeRefined (int index) const
void setWillBeRefined (int index, bool value)
void setWillBeRefined (const std::bitset< TwoPowerD > &value)
void flipWillBeRefined (int index)
std::bitset< TwoPowerD > getIsVertexLocal () const
bool getIsVertexLocal (int index) const
void setIsVertexLocal (int index, bool value)
void setIsVertexLocal (const std::bitset< TwoPowerD > &value)
void flipIsVertexLocal (int index)
std::bitset< TwoPowerD > getIsParentVertexLocal () const
bool getIsParentVertexLocal (int index) const
void setIsParentVertexLocal (int index, bool value)
void setIsParentVertexLocal (const std::bitset< TwoPowerD > &value)
void flipIsParentVertexLocal (int index)
std::bitset< TwoPowerD > getIsVertexParentOfSubtree () const
bool getIsVertexParentOfSubtree (int index) const
void setIsVertexParentOfSubtree (int index, bool value)
void setIsVertexParentOfSubtree (const std::bitset< TwoPowerD > &value)
void flipIsVertexParentOfSubtree (int index)
std::bitset< TwoTimesD > getIsFaceLocal () const
bool getIsFaceLocal (int index) const
void setIsFaceLocal (int index, bool value)
void setIsFaceLocal (const std::bitset< TwoTimesD > &value)
void flipIsFaceLocal (int index)
bool getIsCellLocal () const
void setIsCellLocal (bool value)
bool getIsParentCellLocal () const
void setIsParentCellLocal (bool value)
std::bitset< TwoPowerD > getIsVertexAdjacentToParallelDomainBoundary () const
bool getIsVertexAdjacentToParallelDomainBoundary (int index) const
void setIsVertexAdjacentToParallelDomainBoundary (int index, bool value)
void setIsVertexAdjacentToParallelDomainBoundary (const std::bitset< TwoPowerD > &value)
void flipIsVertexAdjacentToParallelDomainBoundary (int index)
std::bitset< TwoTimesD > getIsFaceAdjacentToParallelDomainBoundary () const
void setIsFaceAdjacentToParallelDomainBoundary (const std::bitset< TwoTimesD > &value)
bool getIsFaceAdjacentToParallelDomainBoundary (int index) const
void setIsFaceAdjacentToParallelDomainBoundary (int index, bool value)
void flipIsFaceAdjacentToParallelDomainBoundary (int index)
tarch::la::Vector< TwoPowerD, int > getNumberOfAdjacentTreesPerVertex () const
void setNumberOfAdjacentTreesPerVertex (const tarch::la::Vector< TwoPowerD, int > &value)
int getNumberOfAdjacentTreesPerVertex (int index) const
void setNumberOfAdjacentTreesPerVertex (int index, int value)
std::bitset< ThreePowerD > getIsAdjacentCellLocal () const
void setIsAdjacentCellLocal (const std::bitset< ThreePowerD > &value)
bool getIsAdjacentCellLocal (int index) const
void setIsAdjacentCellLocal (int index, bool value)
void flipIsAdjacentCellLocal (int index)
tarch::la::Vector< TwoPowerD, int > getVertexDataFrom () const
void setVertexDataFrom (const tarch::la::Vector< TwoPowerD, int > &value)
int getVertexDataFrom (int index) const
void setVertexDataFrom (int index, int value)
tarch::la::Vector< TwoPowerD, int > getVertexDataTo () const
void setVertexDataTo (const tarch::la::Vector< TwoPowerD, int > &value)
int getVertexDataTo (int index) const
void setVertexDataTo (int index, int value)
tarch::la::Vector< TwoTimesD, int > getFaceDataFrom () const
void setFaceDataFrom (const tarch::la::Vector< TwoTimesD, int > &value)
int getFaceDataFrom (int index) const
void setFaceDataFrom (int index, int value)
tarch::la::Vector< TwoTimesD, int > getFaceDataTo () const
void setFaceDataTo (const tarch::la::Vector< TwoTimesD, int > &value)
int getFaceDataTo (int index) const
void setFaceDataTo (int index, int value)
int getCellData () const
void setCellData (int value)
tarch::la::Vector< Dimensions, int > getRelativePositionToFather () const
void setRelativePositionToFather (const tarch::la::Vector< Dimensions, int > &value)
int getRelativePositionToFather (int index) const
void setRelativePositionToFather (int index, int value)
int getInvokingSpacetree () const
void setInvokingSpacetree (int value)
bool getInvokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing () const
void setInvokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing (bool value)
int getSenderRank () const
GridTraversalEvent (ObjectConstruction)
std::string toString () const
Static Public Member Functions
static MPI_Datatype getForkDatatype ()
Hands out MPI datatype if we work without the LLVM MPI extension.
static MPI_Datatype getJoinDatatype ()
static MPI_Datatype getBoundaryExchangeDatatype ()
static MPI_Datatype getMultiscaleDataExchangeDatatype ()
static MPI_Datatype getGlobalCommunciationDatatype ()
static void freeForkDatatype ()
static void freeJoinDatatype ()
static void freeBoundaryExchangeDatatype ()
static void freeMultiscaleDataExchangeDatatype ()
static void freeGlobalCommunciationDatatype ()
static void initDatatype ()
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
static void shutdownDatatype ()
Free the underlying MPI datatype.
static void send (const peano4::grid::GridTraversalEvent &buffer, int destination, int tag, MPI_Comm communicator)
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
static void receive (peano4::grid::GridTraversalEvent &buffer, int source, int tag, MPI_Comm communicator)
static void send (const peano4::grid::GridTraversalEvent &buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
static void receive (peano4::grid::GridTraversalEvent &buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
static void sendAndPollDanglingMessages (const peano4::grid::GridTraversalEvent &message, int destination, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
static void receiveAndPollDanglingMessages (peano4::grid::GridTraversalEvent &message, int source, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
Private Attributes
tarch::la::Vector< Dimensions, double > _x
tarch::la::Vector< Dimensions, double > _h
std::bitset< TwoPowerD > _hasBeenRefined
std::bitset< TwoPowerD > _willBeRefined
std::bitset< TwoPowerD > _isVertexLocal
std::bitset< TwoPowerD > _isParentVertexLocal
std::bitset< TwoPowerD > _isVertexParentOfSubtree
std::bitset< TwoTimesD > _isFaceLocal
bool _isCellLocal
bool _isParentCellLocal
std::bitset< TwoPowerD > _isVertexAdjacentToParallelDomainBoundary
std::bitset< TwoTimesD > _isFaceAdjacentToParallelDomainBoundary
tarch::la::Vector< TwoPowerD, int > _numberOfAdjacentTreesPerVertex
std::bitset< ThreePowerD > _isAdjacentCellLocal
tarch::la::Vector< TwoPowerD, int > _vertexDataFrom
tarch::la::Vector< TwoPowerD, int > _vertexDataTo
tarch::la::Vector< TwoTimesD, int > _faceDataFrom
tarch::la::Vector< TwoTimesD, int > _faceDataTo
int _cellData
tarch::la::Vector< Dimensions, int > _relativePositionToFather
int _invokingSpacetree
bool _invokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing
int _senderDestinationRank
Static Private Attributes
static MPI_Datatype Datatype = MPI_DATATYPE_NULL
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
Detailed Description
Definition at line 26 of file GridTraversalEvent.h.
Member Enumeration Documentation
ObjectConstruction
enum peano4::grid::GridTraversalEvent::ObjectConstruction
Enumerator
NoData
Definition at line 268 of file GridTraversalEvent.h.
Constructor & Destructor Documentation
GridTraversalEvent() [1/4]
peano4::grid::GridTraversalEvent::GridTraversalEvent () default
GridTraversalEvent() [2/4]
peano4::grid::GridTraversalEvent::GridTraversalEvent (const tarch::la::Vector< Dimensions, double > & __x, const tarch::la::Vector< Dimensions, double > & __h, const std::bitset< TwoPowerD > & __hasBeenRefined, const std::bitset< TwoPowerD > & __willBeRefined, const std::bitset< TwoPowerD > & __isVertexLocal, const std::bitset< TwoPowerD > & __isParentVertexLocal, const std::bitset< TwoPowerD > & __isVertexParentOfSubtree, const std::bitset< TwoTimesD > & __isFaceLocal, const bool __isCellLocal, const bool __isParentCellLocal, const std::bitset< TwoPowerD > & __isVertexAdjacentToParallelDomainBoundary, const std::bitset< TwoTimesD > & __isFaceAdjacentToParallelDomainBoundary, const tarch::la::Vector< TwoPowerD, int > & __numberOfAdjacentTreesPerVertex, const std::bitset< ThreePowerD > & __isAdjacentCellLocal, const tarch::la::Vector< TwoPowerD, int > & __vertexDataFrom, const tarch::la::Vector< TwoPowerD, int > & __vertexDataTo, const tarch::la::Vector< TwoTimesD, int > & __faceDataFrom, const tarch::la::Vector< TwoTimesD, int > & __faceDataTo, const int __cellData, const tarch::la::Vector< Dimensions, int > & __relativePositionToFather, const int __invokingSpacetree, const bool __invokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing)
Definition at line 8 of file GridTraversalEvent.cpp.
References setCellData(), setFaceDataFrom(), setFaceDataTo(), setH(), setHasBeenRefined(), setInvokingSpacetree(), setInvokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing(), setIsAdjacentCellLocal(), setIsCellLocal(), setIsFaceAdjacentToParallelDomainBoundary(), setIsFaceLocal(), setIsParentCellLocal(), setIsParentVertexLocal(), setIsVertexAdjacentToParallelDomainBoundary(), setIsVertexLocal(), setIsVertexParentOfSubtree(), setNumberOfAdjacentTreesPerVertex(), setRelativePositionToFather(), setVertexDataFrom(), setVertexDataTo(), setWillBeRefined(), and setX().
GridTraversalEvent() [3/4]
peano4::grid::GridTraversalEvent::GridTraversalEvent (const GridTraversalEvent & copy)
Definition at line 56 of file GridTraversalEvent.cpp.
References setH(), and setX().
GridTraversalEvent() [4/4]
peano4::grid::GridTraversalEvent::GridTraversalEvent (ObjectConstruction)
Definition at line 270 of file GridTraversalEvent.h.
Member Function Documentation
flipHasBeenRefined()
void peano4::grid::GridTraversalEvent::flipHasBeenRefined (int index)
Definition at line 69 of file GridTraversalEvent.h.
References _hasBeenRefined.
flipIsAdjacentCellLocal()
void peano4::grid::GridTraversalEvent::flipIsAdjacentCellLocal (int index)
Definition at line 156 of file GridTraversalEvent.h.
References _isAdjacentCellLocal.
flipIsFaceAdjacentToParallelDomainBoundary()
void peano4::grid::GridTraversalEvent::flipIsFaceAdjacentToParallelDomainBoundary (int index)
Definition at line 137 of file GridTraversalEvent.h.
References _isFaceAdjacentToParallelDomainBoundary.
flipIsFaceLocal()
void peano4::grid::GridTraversalEvent::flipIsFaceLocal (int index)
Definition at line 101 of file GridTraversalEvent.h.
References _isFaceLocal.
flipIsParentVertexLocal()
void peano4::grid::GridTraversalEvent::flipIsParentVertexLocal (int index)
Definition at line 87 of file GridTraversalEvent.h.
References _isParentVertexLocal.
flipIsVertexAdjacentToParallelDomainBoundary()
void peano4::grid::GridTraversalEvent::flipIsVertexAdjacentToParallelDomainBoundary (int index)
Definition at line 121 of file GridTraversalEvent.h.
References _isVertexAdjacentToParallelDomainBoundary.
flipIsVertexLocal()
void peano4::grid::GridTraversalEvent::flipIsVertexLocal (int index)
Definition at line 81 of file GridTraversalEvent.h.
References _isVertexLocal.
flipIsVertexParentOfSubtree()
void peano4::grid::GridTraversalEvent::flipIsVertexParentOfSubtree (int index)
Definition at line 93 of file GridTraversalEvent.h.
References _isVertexParentOfSubtree.
flipWillBeRefined()
void peano4::grid::GridTraversalEvent::flipWillBeRefined (int index)
Definition at line 75 of file GridTraversalEvent.h.
References _willBeRefined.
freeBoundaryExchangeDatatype()
void peano4::grid::GridTraversalEvent::freeBoundaryExchangeDatatype () static
Definition at line 167 of file GridTraversalEvent.cpp.
freeForkDatatype()
void peano4::grid::GridTraversalEvent::freeForkDatatype () static
Definition at line 146 of file GridTraversalEvent.cpp.
freeGlobalCommunciationDatatype()
void peano4::grid::GridTraversalEvent::freeGlobalCommunciationDatatype () static
Definition at line 153 of file GridTraversalEvent.cpp.
freeJoinDatatype()
void peano4::grid::GridTraversalEvent::freeJoinDatatype () static
Definition at line 160 of file GridTraversalEvent.cpp.
freeMultiscaleDataExchangeDatatype()
void peano4::grid::GridTraversalEvent::freeMultiscaleDataExchangeDatatype () static
Definition at line 174 of file GridTraversalEvent.cpp.
getBoundaryExchangeDatatype()
MPI_Datatype peano4::grid::GridTraversalEvent::getBoundaryExchangeDatatype () static
Definition at line 143 of file GridTraversalEvent.cpp.
getCellData()
int peano4::grid::GridTraversalEvent::getCellData () const
Definition at line 178 of file GridTraversalEvent.h.
References _cellData.
Referenced by examples::regulargridupscaling::MyObserver::enterCell().
getFaceDataFrom() [1/2]
tarch::la::Vector< TwoTimesD, int > peano4::grid::GridTraversalEvent::getFaceDataFrom () const
Definition at line 168 of file GridTraversalEvent.h.
References _faceDataFrom.
Referenced by peano4::grid::Spacetree::receiveAndMergeUserData().
getFaceDataFrom() [2/2]
int peano4::grid::GridTraversalEvent::getFaceDataFrom (int index) const
Definition at line 170 of file GridTraversalEvent.h.
References _faceDataFrom.
getFaceDataTo() [1/2]
tarch::la::Vector< TwoTimesD, int > peano4::grid::GridTraversalEvent::getFaceDataTo () const
Definition at line 173 of file GridTraversalEvent.h.
References _faceDataTo.
Referenced by peano4::grid::Spacetree::receiveAndMergeUserData().
getFaceDataTo() [2/2]
int peano4::grid::GridTraversalEvent::getFaceDataTo (int index) const
Definition at line 175 of file GridTraversalEvent.h.
References _faceDataTo.
getForkDatatype()
MPI_Datatype peano4::grid::GridTraversalEvent::getForkDatatype () static
Hands out MPI datatype if we work without the LLVM MPI extension.
If we work with this additional feature, this is the routine where the lazy initialisation is done and the datatype is also cached.
Definition at line 140 of file GridTraversalEvent.cpp.
getGlobalCommunciationDatatype()
MPI_Datatype peano4::grid::GridTraversalEvent::getGlobalCommunciationDatatype () static
Definition at line 141 of file GridTraversalEvent.cpp.
getH() [1/2]
tarch::la::Vector< Dimensions, double > peano4::grid::GridTraversalEvent::getH () const
Definition at line 60 of file GridTraversalEvent.h.
References _h.
Referenced by examples::regulargridupscaling::MyObserver::enterCell(), and peano4::grid::TraversalVTKPlotter::plotCell().
getH() [2/2]
double peano4::grid::GridTraversalEvent::getH (int index) const
Definition at line 61 of file GridTraversalEvent.h.
References _h.
getHasBeenRefined() [1/2]
std::bitset< TwoPowerD > peano4::grid::GridTraversalEvent::getHasBeenRefined () const
Definition at line 65 of file GridTraversalEvent.h.
References _hasBeenRefined.
Referenced by peano4::datamanagement::FaceMarker::FaceMarker().
getHasBeenRefined() [2/2]
bool peano4::grid::GridTraversalEvent::getHasBeenRefined (int index) const
Definition at line 66 of file GridTraversalEvent.h.
References _hasBeenRefined.
getInvokingSpacetree()
int peano4::grid::GridTraversalEvent::getInvokingSpacetree () const
Definition at line 188 of file GridTraversalEvent.h.
References _invokingSpacetree.
getInvokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing()
bool peano4::grid::GridTraversalEvent::getInvokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing () const
Definition at line 190 of file GridTraversalEvent.h.
References _invokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing.
getIsAdjacentCellLocal() [1/2]
std::bitset< ThreePowerD > peano4::grid::GridTraversalEvent::getIsAdjacentCellLocal () const
Definition at line 152 of file GridTraversalEvent.h.
References _isAdjacentCellLocal.
getIsAdjacentCellLocal() [2/2]
bool peano4::grid::GridTraversalEvent::getIsAdjacentCellLocal (int index) const
Definition at line 154 of file GridTraversalEvent.h.
References _isAdjacentCellLocal.
getIsCellLocal()
bool peano4::grid::GridTraversalEvent::getIsCellLocal () const
Definition at line 103 of file GridTraversalEvent.h.
References _isCellLocal.
getIsFaceAdjacentToParallelDomainBoundary() [1/2]
std::bitset< TwoTimesD > peano4::grid::GridTraversalEvent::getIsFaceAdjacentToParallelDomainBoundary () const
Definition at line 125 of file GridTraversalEvent.h.
References _isFaceAdjacentToParallelDomainBoundary.
getIsFaceAdjacentToParallelDomainBoundary() [2/2]
bool peano4::grid::GridTraversalEvent::getIsFaceAdjacentToParallelDomainBoundary (int index) const
Definition at line 131 of file GridTraversalEvent.h.
References _isFaceAdjacentToParallelDomainBoundary.
getIsFaceLocal() [1/2]
std::bitset< TwoTimesD > peano4::grid::GridTraversalEvent::getIsFaceLocal () const
Definition at line 97 of file GridTraversalEvent.h.
References _isFaceLocal.
Referenced by peano4::grid::Spacetree::receiveAndMergeUserData().
getIsFaceLocal() [2/2]
bool peano4::grid::GridTraversalEvent::getIsFaceLocal (int index) const
Definition at line 98 of file GridTraversalEvent.h.
References _isFaceLocal.
getIsParentCellLocal()
bool peano4::grid::GridTraversalEvent::getIsParentCellLocal () const
Definition at line 106 of file GridTraversalEvent.h.
References _isParentCellLocal.
getIsParentVertexLocal() [1/2]
std::bitset< TwoPowerD > peano4::grid::GridTraversalEvent::getIsParentVertexLocal () const
Definition at line 83 of file GridTraversalEvent.h.
References _isParentVertexLocal.
getIsParentVertexLocal() [2/2]
bool peano4::grid::GridTraversalEvent::getIsParentVertexLocal (int index) const
Definition at line 84 of file GridTraversalEvent.h.
References _isParentVertexLocal.
getIsVertexAdjacentToParallelDomainBoundary() [1/2]
std::bitset< TwoPowerD > peano4::grid::GridTraversalEvent::getIsVertexAdjacentToParallelDomainBoundary () const
Definition at line 109 of file GridTraversalEvent.h.
References _isVertexAdjacentToParallelDomainBoundary.
getIsVertexAdjacentToParallelDomainBoundary() [2/2]
bool peano4::grid::GridTraversalEvent::getIsVertexAdjacentToParallelDomainBoundary (int index) const
Definition at line 112 of file GridTraversalEvent.h.
References _isVertexAdjacentToParallelDomainBoundary.
getIsVertexLocal() [1/2]
std::bitset< TwoPowerD > peano4::grid::GridTraversalEvent::getIsVertexLocal () const
Definition at line 77 of file GridTraversalEvent.h.
References _isVertexLocal.
Referenced by peano4::grid::Spacetree::receiveAndMergeUserData().
getIsVertexLocal() [2/2]
bool peano4::grid::GridTraversalEvent::getIsVertexLocal (int index) const
Definition at line 78 of file GridTraversalEvent.h.
References _isVertexLocal.
getIsVertexParentOfSubtree() [1/2]
std::bitset< TwoPowerD > peano4::grid::GridTraversalEvent::getIsVertexParentOfSubtree () const
Definition at line 89 of file GridTraversalEvent.h.
References _isVertexParentOfSubtree.
getIsVertexParentOfSubtree() [2/2]
bool peano4::grid::GridTraversalEvent::getIsVertexParentOfSubtree (int index) const
Definition at line 90 of file GridTraversalEvent.h.
References _isVertexParentOfSubtree.
getJoinDatatype()
MPI_Datatype peano4::grid::GridTraversalEvent::getJoinDatatype () static
Definition at line 142 of file GridTraversalEvent.cpp.
getMultiscaleDataExchangeDatatype()
MPI_Datatype peano4::grid::GridTraversalEvent::getMultiscaleDataExchangeDatatype () static
Definition at line 144 of file GridTraversalEvent.cpp.
getNumberOfAdjacentTreesPerVertex() [1/2]
tarch::la::Vector< TwoPowerD, int > peano4::grid::GridTraversalEvent::getNumberOfAdjacentTreesPerVertex () const
Definition at line 141 of file GridTraversalEvent.h.
References _numberOfAdjacentTreesPerVertex.
getNumberOfAdjacentTreesPerVertex() [2/2]
int peano4::grid::GridTraversalEvent::getNumberOfAdjacentTreesPerVertex (int index) const
Definition at line 147 of file GridTraversalEvent.h.
References _numberOfAdjacentTreesPerVertex.
getRelativePositionToFather() [1/2]
tarch::la::Vector< Dimensions, int > peano4::grid::GridTraversalEvent::getRelativePositionToFather () const
Definition at line 181 of file GridTraversalEvent.h.
References _relativePositionToFather.
getRelativePositionToFather() [2/2]
int peano4::grid::GridTraversalEvent::getRelativePositionToFather (int index) const
Definition at line 185 of file GridTraversalEvent.h.
References _relativePositionToFather.
getSenderRank()
int peano4::grid::GridTraversalEvent::getSenderRank () const
Returns
The rank of the sender of an object. It only make ssense to call this routine after you've invoked receive with MPI_ANY_SOURCE.
Definition at line 181 of file GridTraversalEvent.cpp.
getVertexDataFrom() [1/2]
tarch::la::Vector< TwoPowerD, int > peano4::grid::GridTraversalEvent::getVertexDataFrom () const
Definition at line 158 of file GridTraversalEvent.h.
References _vertexDataFrom.
Referenced by peano4::grid::Spacetree::receiveAndMergeUserData().
getVertexDataFrom() [2/2]
int peano4::grid::GridTraversalEvent::getVertexDataFrom (int index) const
Definition at line 160 of file GridTraversalEvent.h.
References _vertexDataFrom.
getVertexDataTo() [1/2]
tarch::la::Vector< TwoPowerD, int > peano4::grid::GridTraversalEvent::getVertexDataTo () const
Definition at line 163 of file GridTraversalEvent.h.
References _vertexDataTo.
Referenced by peano4::grid::Spacetree::receiveAndMergeUserData().
getVertexDataTo() [2/2]
int peano4::grid::GridTraversalEvent::getVertexDataTo (int index) const
Definition at line 165 of file GridTraversalEvent.h.
References _vertexDataTo.
getWillBeRefined() [1/2]
std::bitset< TwoPowerD > peano4::grid::GridTraversalEvent::getWillBeRefined () const
Definition at line 71 of file GridTraversalEvent.h.
References _willBeRefined.
Referenced by peano4::datamanagement::FaceMarker::FaceMarker().
getWillBeRefined() [2/2]
bool peano4::grid::GridTraversalEvent::getWillBeRefined (int index) const
Definition at line 72 of file GridTraversalEvent.h.
References _willBeRefined.
getX() [1/2]
tarch::la::Vector< Dimensions, double > peano4::grid::GridTraversalEvent::getX () const
Definition at line 55 of file GridTraversalEvent.h.
References _x.
Referenced by examples::regulargridupscaling::MyObserver::enterCell(), and peano4::grid::TraversalVTKPlotter::plotCell().
getX() [2/2]
double peano4::grid::GridTraversalEvent::getX (int index) const
Definition at line 56 of file GridTraversalEvent.h.
References _x.
initDatatype()
void peano4::grid::GridTraversalEvent::initDatatype () static
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
Definition at line 183 of file GridTraversalEvent.cpp.
References TwoPowerD, and TwoTimesD.
receive() [1/2]
void peano4::grid::GridTraversalEvent::receive (peano4::grid::GridTraversalEvent & buffer, int source, int tag, MPI_Comm communicator) static
Definition at line 381 of file GridTraversalEvent.cpp.
References _senderDestinationRank.
Referenced by receiveAndPollDanglingMessages().
receive() [2/2]
void peano4::grid::GridTraversalEvent::receive (peano4::grid::GridTraversalEvent & buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Definition at line 407 of file GridTraversalEvent.cpp.
References _senderDestinationRank.
receiveAndPollDanglingMessages()
void peano4::grid::GridTraversalEvent::receiveAndPollDanglingMessages (peano4::grid::GridTraversalEvent & message, int source, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 455 of file GridTraversalEvent.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), receive(), tarch::services::ServiceRepository::receiveDanglingMessages(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
send() [1/2]
void peano4::grid::GridTraversalEvent::send (const peano4::grid::GridTraversalEvent & buffer, int destination, int tag, MPI_Comm communicator) static
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
However, this did not work with newer C++11 versions, as a member function using this as pointer usually doesn't see the vtable while the init sees the object from outside, i.e. including a vtable. So this routine now is basically an alias for a blocking MPI_Send.
Definition at line 376 of file GridTraversalEvent.cpp.
Referenced by sendAndPollDanglingMessages().
send() [2/2]
void peano4::grid::GridTraversalEvent::send (const peano4::grid::GridTraversalEvent & buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
In systems with heavy MPI usage, this can help to avoid deadlocks.
Definition at line 388 of file GridTraversalEvent.cpp.
sendAndPollDanglingMessages()
void peano4::grid::GridTraversalEvent::sendAndPollDanglingMessages (const peano4::grid::GridTraversalEvent & message, int destination, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 430 of file GridTraversalEvent.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), tarch::services::ServiceRepository::receiveDanglingMessages(), send(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
setCellData()
void peano4::grid::GridTraversalEvent::setCellData (int value)
Definition at line 179 of file GridTraversalEvent.h.
References _cellData.
Referenced by GridTraversalEvent().
setFaceDataFrom() [1/2]
void peano4::grid::GridTraversalEvent::setFaceDataFrom (const tarch::la::Vector< TwoTimesD, int > & value)
Definition at line 169 of file GridTraversalEvent.h.
References _faceDataFrom.
Referenced by GridTraversalEvent().
setFaceDataFrom() [2/2]
void peano4::grid::GridTraversalEvent::setFaceDataFrom (int index, int value)
Definition at line 171 of file GridTraversalEvent.h.
References _faceDataFrom.
setFaceDataTo() [1/2]
void peano4::grid::GridTraversalEvent::setFaceDataTo (const tarch::la::Vector< TwoTimesD, int > & value)
Definition at line 174 of file GridTraversalEvent.h.
References _faceDataTo.
Referenced by GridTraversalEvent().
setFaceDataTo() [2/2]
void peano4::grid::GridTraversalEvent::setFaceDataTo (int index, int value)
Definition at line 176 of file GridTraversalEvent.h.
References _faceDataTo.
setH() [1/2]
void peano4::grid::GridTraversalEvent::setH (const tarch::la::Vector< Dimensions, double > & value)
Definition at line 63 of file GridTraversalEvent.h.
References _h.
setH() [2/2]
void peano4::grid::GridTraversalEvent::setH (int index, double value)
Definition at line 62 of file GridTraversalEvent.h.
References _h.
Referenced by GridTraversalEvent(), exahype2::dg::tests::DGUtilsTest::testEvaluatePolynomialOrder1(), and exahype2::dg::tests::DGUtilsTest::testEvaluatePolynomialOrder2().
setHasBeenRefined() [1/2]
void peano4::grid::GridTraversalEvent::setHasBeenRefined (const std::bitset< TwoPowerD > & value)
Definition at line 68 of file GridTraversalEvent.h.
References _hasBeenRefined.
setHasBeenRefined() [2/2]
void peano4::grid::GridTraversalEvent::setHasBeenRefined (int index, bool value)
Definition at line 67 of file GridTraversalEvent.h.
References _hasBeenRefined.
Referenced by GridTraversalEvent().
setInvokingSpacetree()
void peano4::grid::GridTraversalEvent::setInvokingSpacetree (int value)
Definition at line 189 of file GridTraversalEvent.h.
References _invokingSpacetree.
Referenced by GridTraversalEvent().
setInvokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing()
void peano4::grid::GridTraversalEvent::setInvokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing (bool value)
Definition at line 193 of file GridTraversalEvent.h.
References _invokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing.
Referenced by GridTraversalEvent().
setIsAdjacentCellLocal() [1/2]
void peano4::grid::GridTraversalEvent::setIsAdjacentCellLocal (const std::bitset< ThreePowerD > & value)
Definition at line 153 of file GridTraversalEvent.h.
References _isAdjacentCellLocal.
Referenced by GridTraversalEvent().
setIsAdjacentCellLocal() [2/2]
void peano4::grid::GridTraversalEvent::setIsAdjacentCellLocal (int index, bool value)
Definition at line 155 of file GridTraversalEvent.h.
References _isAdjacentCellLocal.
setIsCellLocal()
void peano4::grid::GridTraversalEvent::setIsCellLocal (bool value)
Definition at line 104 of file GridTraversalEvent.h.
References _isCellLocal.
Referenced by peano4::grid::GridTraversalEventGenerator::createPrunedEnterCellTraversalEvent(), peano4::grid::GridTraversalEventGenerator::createPrunedLeaveCellTraversalEvent(), and GridTraversalEvent().
setIsFaceAdjacentToParallelDomainBoundary() [1/2]
void peano4::grid::GridTraversalEvent::setIsFaceAdjacentToParallelDomainBoundary (const std::bitset< TwoTimesD > & value)
Definition at line 128 of file GridTraversalEvent.h.
References _isFaceAdjacentToParallelDomainBoundary.
Referenced by GridTraversalEvent().
setIsFaceAdjacentToParallelDomainBoundary() [2/2]
void peano4::grid::GridTraversalEvent::setIsFaceAdjacentToParallelDomainBoundary (int index, bool value)
Definition at line 134 of file GridTraversalEvent.h.
References _isFaceAdjacentToParallelDomainBoundary.
setIsFaceLocal() [1/2]
void peano4::grid::GridTraversalEvent::setIsFaceLocal (const std::bitset< TwoTimesD > & value)
Definition at line 100 of file GridTraversalEvent.h.
References _isFaceLocal.
setIsFaceLocal() [2/2]
void peano4::grid::GridTraversalEvent::setIsFaceLocal (int index, bool value)
Definition at line 99 of file GridTraversalEvent.h.
References _isFaceLocal.
Referenced by peano4::grid::GridTraversalEventGenerator::createPrunedEnterCellTraversalEvent(), peano4::grid::GridTraversalEventGenerator::createPrunedLeaveCellTraversalEvent(), and GridTraversalEvent().
setIsParentCellLocal()
void peano4::grid::GridTraversalEvent::setIsParentCellLocal (bool value)
Definition at line 107 of file GridTraversalEvent.h.
References _isParentCellLocal.
Referenced by peano4::grid::GridTraversalEventGenerator::createPrunedEnterCellTraversalEvent(), peano4::grid::GridTraversalEventGenerator::createPrunedLeaveCellTraversalEvent(), and GridTraversalEvent().
setIsParentVertexLocal() [1/2]
void peano4::grid::GridTraversalEvent::setIsParentVertexLocal (const std::bitset< TwoPowerD > & value)
Definition at line 86 of file GridTraversalEvent.h.
References _isParentVertexLocal.
setIsParentVertexLocal() [2/2]
void peano4::grid::GridTraversalEvent::setIsParentVertexLocal (int index, bool value)
Definition at line 85 of file GridTraversalEvent.h.
References _isParentVertexLocal.
Referenced by GridTraversalEvent().
setIsVertexAdjacentToParallelDomainBoundary() [1/2]
void peano4::grid::GridTraversalEvent::setIsVertexAdjacentToParallelDomainBoundary (const std::bitset< TwoPowerD > & value)
Definition at line 118 of file GridTraversalEvent.h.
References _isVertexAdjacentToParallelDomainBoundary.
setIsVertexAdjacentToParallelDomainBoundary() [2/2]
void peano4::grid::GridTraversalEvent::setIsVertexAdjacentToParallelDomainBoundary (int index, bool value)
Definition at line 115 of file GridTraversalEvent.h.
References _isVertexAdjacentToParallelDomainBoundary.
Referenced by GridTraversalEvent().
setIsVertexLocal() [1/2]
void peano4::grid::GridTraversalEvent::setIsVertexLocal (const std::bitset< TwoPowerD > & value)
Definition at line 80 of file GridTraversalEvent.h.
References _isVertexLocal.
setIsVertexLocal() [2/2]
void peano4::grid::GridTraversalEvent::setIsVertexLocal (int index, bool value)
Definition at line 79 of file GridTraversalEvent.h.
References _isVertexLocal.
Referenced by peano4::grid::GridTraversalEventGenerator::createPrunedEnterCellTraversalEvent(), peano4::grid::GridTraversalEventGenerator::createPrunedLeaveCellTraversalEvent(), and GridTraversalEvent().
setIsVertexParentOfSubtree() [1/2]
void peano4::grid::GridTraversalEvent::setIsVertexParentOfSubtree (const std::bitset< TwoPowerD > & value)
Definition at line 92 of file GridTraversalEvent.h.
References _isVertexParentOfSubtree.
setIsVertexParentOfSubtree() [2/2]
void peano4::grid::GridTraversalEvent::setIsVertexParentOfSubtree (int index, bool value)
Definition at line 91 of file GridTraversalEvent.h.
References _isVertexParentOfSubtree.
Referenced by GridTraversalEvent().
setNumberOfAdjacentTreesPerVertex() [1/2]
void peano4::grid::GridTraversalEvent::setNumberOfAdjacentTreesPerVertex (const tarch::la::Vector< TwoPowerD, int > & value)
Definition at line 144 of file GridTraversalEvent.h.
References _numberOfAdjacentTreesPerVertex.
Referenced by GridTraversalEvent().
setNumberOfAdjacentTreesPerVertex() [2/2]
void peano4::grid::GridTraversalEvent::setNumberOfAdjacentTreesPerVertex (int index, int value)
Definition at line 148 of file GridTraversalEvent.h.
References _numberOfAdjacentTreesPerVertex.
setRelativePositionToFather() [1/2]
void peano4::grid::GridTraversalEvent::setRelativePositionToFather (const tarch::la::Vector< Dimensions, int > & value)
Definition at line 182 of file GridTraversalEvent.h.
References _relativePositionToFather.
Referenced by toolbox::blockstructured::tests::IandRSecondOrderTest::compareInterpolateLinearCaseToTensorProduct(), toolbox::blockstructured::tests::IandRThirdOrderTest::compareInterpolateLinearCaseToTensorProduct(), toolbox::blockstructured::tests::IandRInMatricesTest::compareInterpolateLinearCaseToTensorProductPatch(), toolbox::blockstructured::tests::IandRSecondOrderTest::compareRestrictLinearCaseToTensorProduct(), toolbox::blockstructured::tests::IandRThirdOrderTest::compareRestrictLinearCaseToTensorProduct(), toolbox::blockstructured::tests::IandRInMatricesTest::compareRestrictLinearCaseToTensorProductPatch(), GridTraversalEvent(), exahype2::fv::tests::InterpolationRestrictionTest::testAverageRestrictionWithTensorProduct(), exahype2::fv::tests::InterpolationRestrictionTest::testInjectionExtrapolationRestrictionWithTensorProduct(), exahype2::fv::tests::InterpolationRestrictionTest::testPiecewiseConstantInterpolationWithTensorProduct1(), exahype2::fv::tests::InterpolationRestrictionTest::testPiecewiseConstantInterpolationWithTensorProduct2(), and toolbox::blockstructured::tests::InterpolationTest::testRestrictHaloLayer_AoS_averaging().
setRelativePositionToFather() [2/2]
void peano4::grid::GridTraversalEvent::setRelativePositionToFather (int index, int value)
Definition at line 186 of file GridTraversalEvent.h.
References _relativePositionToFather.
setVertexDataFrom() [1/2]
void peano4::grid::GridTraversalEvent::setVertexDataFrom (const tarch::la::Vector< TwoPowerD, int > & value)
Definition at line 159 of file GridTraversalEvent.h.
References _vertexDataFrom.
Referenced by GridTraversalEvent().
setVertexDataFrom() [2/2]
void peano4::grid::GridTraversalEvent::setVertexDataFrom (int index, int value)
Definition at line 161 of file GridTraversalEvent.h.
References _vertexDataFrom.
setVertexDataTo() [1/2]
void peano4::grid::GridTraversalEvent::setVertexDataTo (const tarch::la::Vector< TwoPowerD, int > & value)
Definition at line 164 of file GridTraversalEvent.h.
References _vertexDataTo.
Referenced by GridTraversalEvent().
setVertexDataTo() [2/2]
void peano4::grid::GridTraversalEvent::setVertexDataTo (int index, int value)
Definition at line 166 of file GridTraversalEvent.h.
References _vertexDataTo.
setWillBeRefined() [1/2]
void peano4::grid::GridTraversalEvent::setWillBeRefined (const std::bitset< TwoPowerD > & value)
Definition at line 74 of file GridTraversalEvent.h.
References _willBeRefined.
setWillBeRefined() [2/2]
void peano4::grid::GridTraversalEvent::setWillBeRefined (int index, bool value)
Definition at line 73 of file GridTraversalEvent.h.
References _willBeRefined.
Referenced by GridTraversalEvent().
setX() [1/2]
void peano4::grid::GridTraversalEvent::setX (const tarch::la::Vector< Dimensions, double > & value)
Definition at line 58 of file GridTraversalEvent.h.
References _x.
setX() [2/2]
void peano4::grid::GridTraversalEvent::setX (int index, double value)
Definition at line 57 of file GridTraversalEvent.h.
References _x.
Referenced by peano4::grid::GridTraversalEventGenerator::createGenericCellTraversalEvent(), GridTraversalEvent(), exahype2::dg::tests::DGUtilsTest::testEvaluatePolynomialOrder1(), and exahype2::dg::tests::DGUtilsTest::testEvaluatePolynomialOrder2().
shutdownDatatype()
void peano4::grid::GridTraversalEvent::shutdownDatatype () static
Free the underlying MPI datatype.
Definition at line 363 of file GridTraversalEvent.cpp.
toString()
std::string peano4::grid::GridTraversalEvent::toString () const
Definition at line 83 of file GridTraversalEvent.cpp.
Referenced by peano4::grid::Spacetree::receiveAndMergeUserData().
Field Documentation
_cellData
int peano4::grid::GridTraversalEvent::_cellData private
Definition at line 309 of file GridTraversalEvent.h.
Referenced by getCellData(), and setCellData().
_faceDataFrom
tarch::la::Vector<TwoTimesD, int> peano4::grid::GridTraversalEvent::_faceDataFrom private
Definition at line 307 of file GridTraversalEvent.h.
Referenced by getFaceDataFrom(), getFaceDataFrom(), setFaceDataFrom(), and setFaceDataFrom().
_faceDataTo
tarch::la::Vector<TwoTimesD, int> peano4::grid::GridTraversalEvent::_faceDataTo private
Definition at line 308 of file GridTraversalEvent.h.
Referenced by getFaceDataTo(), getFaceDataTo(), setFaceDataTo(), and setFaceDataTo().
_h
tarch::la::Vector<Dimensions, double> peano4::grid::GridTraversalEvent::_h private
Definition at line 292 of file GridTraversalEvent.h.
Referenced by getH(), getH(), setH(), and setH().
_hasBeenRefined
std::bitset<TwoPowerD> peano4::grid::GridTraversalEvent::_hasBeenRefined private
Definition at line 293 of file GridTraversalEvent.h.
Referenced by flipHasBeenRefined(), getHasBeenRefined(), getHasBeenRefined(), setHasBeenRefined(), and setHasBeenRefined().
_invokingSpacetree
int peano4::grid::GridTraversalEvent::_invokingSpacetree private
Definition at line 311 of file GridTraversalEvent.h.
Referenced by getInvokingSpacetree(), and setInvokingSpacetree().
_invokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing
bool peano4::grid::GridTraversalEvent::_invokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing private
Definition at line 312 of file GridTraversalEvent.h.
Referenced by getInvokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing(), and setInvokingSpacetreeIsNotInvolvedInAnyDynamicLoadBalancing().
_isAdjacentCellLocal
std::bitset<ThreePowerD> peano4::grid::GridTraversalEvent::_isAdjacentCellLocal private
Definition at line 304 of file GridTraversalEvent.h.
Referenced by flipIsAdjacentCellLocal(), getIsAdjacentCellLocal(), getIsAdjacentCellLocal(), setIsAdjacentCellLocal(), and setIsAdjacentCellLocal().
_isCellLocal
bool peano4::grid::GridTraversalEvent::_isCellLocal private
Definition at line 299 of file GridTraversalEvent.h.
Referenced by getIsCellLocal(), and setIsCellLocal().
_isFaceAdjacentToParallelDomainBoundary
std::bitset<TwoTimesD> peano4::grid::GridTraversalEvent::_isFaceAdjacentToParallelDomainBoundary private
Definition at line 302 of file GridTraversalEvent.h.
Referenced by flipIsFaceAdjacentToParallelDomainBoundary(), getIsFaceAdjacentToParallelDomainBoundary(), getIsFaceAdjacentToParallelDomainBoundary(), setIsFaceAdjacentToParallelDomainBoundary(), and setIsFaceAdjacentToParallelDomainBoundary().
_isFaceLocal
std::bitset<TwoTimesD> peano4::grid::GridTraversalEvent::_isFaceLocal private
Definition at line 298 of file GridTraversalEvent.h.
Referenced by flipIsFaceLocal(), getIsFaceLocal(), getIsFaceLocal(), setIsFaceLocal(), and setIsFaceLocal().
_isParentCellLocal
bool peano4::grid::GridTraversalEvent::_isParentCellLocal private
Definition at line 300 of file GridTraversalEvent.h.
Referenced by getIsParentCellLocal(), and setIsParentCellLocal().
_isParentVertexLocal
std::bitset<TwoPowerD> peano4::grid::GridTraversalEvent::_isParentVertexLocal private
Definition at line 296 of file GridTraversalEvent.h.
Referenced by flipIsParentVertexLocal(), getIsParentVertexLocal(), getIsParentVertexLocal(), setIsParentVertexLocal(), and setIsParentVertexLocal().
_isVertexAdjacentToParallelDomainBoundary
std::bitset<TwoPowerD> peano4::grid::GridTraversalEvent::_isVertexAdjacentToParallelDomainBoundary private
Definition at line 301 of file GridTraversalEvent.h.
Referenced by flipIsVertexAdjacentToParallelDomainBoundary(), getIsVertexAdjacentToParallelDomainBoundary(), getIsVertexAdjacentToParallelDomainBoundary(), setIsVertexAdjacentToParallelDomainBoundary(), and setIsVertexAdjacentToParallelDomainBoundary().
_isVertexLocal
std::bitset<TwoPowerD> peano4::grid::GridTraversalEvent::_isVertexLocal private
Definition at line 295 of file GridTraversalEvent.h.
Referenced by flipIsVertexLocal(), getIsVertexLocal(), getIsVertexLocal(), setIsVertexLocal(), and setIsVertexLocal().
_isVertexParentOfSubtree
std::bitset<TwoPowerD> peano4::grid::GridTraversalEvent::_isVertexParentOfSubtree private
Definition at line 297 of file GridTraversalEvent.h.
Referenced by flipIsVertexParentOfSubtree(), getIsVertexParentOfSubtree(), getIsVertexParentOfSubtree(), setIsVertexParentOfSubtree(), and setIsVertexParentOfSubtree().
_numberOfAdjacentTreesPerVertex
tarch::la::Vector<TwoPowerD, int> peano4::grid::GridTraversalEvent::_numberOfAdjacentTreesPerVertex private
Definition at line 303 of file GridTraversalEvent.h.
Referenced by getNumberOfAdjacentTreesPerVertex(), getNumberOfAdjacentTreesPerVertex(), setNumberOfAdjacentTreesPerVertex(), and setNumberOfAdjacentTreesPerVertex().
_relativePositionToFather
tarch::la::Vector<Dimensions, int> peano4::grid::GridTraversalEvent::_relativePositionToFather private
Definition at line 310 of file GridTraversalEvent.h.
Referenced by getRelativePositionToFather(), getRelativePositionToFather(), setRelativePositionToFather(), and setRelativePositionToFather().
_senderDestinationRank
int peano4::grid::GridTraversalEvent::_senderDestinationRank private
Definition at line 316 of file GridTraversalEvent.h.
Referenced by receive(), and receive().
_vertexDataFrom
tarch::la::Vector<TwoPowerD, int> peano4::grid::GridTraversalEvent::_vertexDataFrom private
Definition at line 305 of file GridTraversalEvent.h.
Referenced by getVertexDataFrom(), getVertexDataFrom(), setVertexDataFrom(), and setVertexDataFrom().
_vertexDataTo
tarch::la::Vector<TwoPowerD, int> peano4::grid::GridTraversalEvent::_vertexDataTo private
Definition at line 306 of file GridTraversalEvent.h.
Referenced by getVertexDataTo(), getVertexDataTo(), setVertexDataTo(), and setVertexDataTo().
_willBeRefined
std::bitset<TwoPowerD> peano4::grid::GridTraversalEvent::_willBeRefined private
Definition at line 294 of file GridTraversalEvent.h.
Referenced by flipWillBeRefined(), getWillBeRefined(), getWillBeRefined(), setWillBeRefined(), and setWillBeRefined().
_x
tarch::la::Vector<Dimensions, double> peano4::grid::GridTraversalEvent::_x private
Definition at line 291 of file GridTraversalEvent.h.
Referenced by getX(), getX(), setX(), and setX().
Datatype
MPI_Datatype peano4::grid::GridTraversalEvent::Datatype = MPI_DATATYPE_NULL static private
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
However, Peano calls init explicitly in most cases. Without the LLVM extension which caches the MPI datatype once constructed, this field stores the type.
Definition at line 325 of file GridTraversalEvent.h.
The documentation for this struct was generated from the following files:
src/peano4/grid/GridTraversalEvent.h
src/peano4/grid/GridTraversalEvent.cpp