Peano
VtkPointBinaryWriter< FileWriter, fp > Class Template Reference
#include <point.h>
Public Member Functions
VtkPointBinaryWriter (FileWriter *writer)
VtkPointBinaryWriter ()=default
void add (fp x, fp y, fp z)
void addPointDataHeader ()
void addScalarPointDataHeader (const char *name)
void addScalar (fp value)
void finish ()
Additional Inherited Members
Protected Member Functions inherited from VtkPointWriterBase< FileWriter >
constexpr int particleCountPosition () const
template<typename T >
T byteswapped (T val)
void updatePointsCount ()
VtkPointWriterBase (FileWriter *writer)
VtkPointWriterBase ()=default
Protected Attributes inherited from VtkPointWriterBase< FileWriter >
FileWriter * writer = nullptr
unsigned long pointCount = 0
Detailed Description
template<typename FileWriter, typename fp = float>
requires IoWriter<FileWriter> and std::is_floating_point_v<fp>
class VtkPointBinaryWriter< FileWriter, fp >
Definition at line 100 of file point.h.
Constructor & Destructor Documentation
VtkPointBinaryWriter() [1/2]
template<typename FileWriter , typename fp = float> VtkPointBinaryWriter< FileWriter, fp >::VtkPointBinaryWriter (FileWriter * writer) explicit
Definition at line 102 of file point.h.
References assert.
VtkPointBinaryWriter() [2/2]
template<typename FileWriter , typename fp = float> VtkPointBinaryWriter< FileWriter, fp >::VtkPointBinaryWriter () explicit default
Member Function Documentation
add()
template<typename FileWriter , typename fp = float> void VtkPointBinaryWriter< FileWriter, fp >::add (fp x, fp y, fp z)
Definition at line 117 of file point.h.
References VtkPointWriterBase< FileWriter >::byteswapped(), VtkPointWriterBase< FileWriter >::pointCount, and VtkPointWriterBase< FileWriter >::writer.
Referenced by VtkPolylineBinaryWriter< FileWriter, fp >::add().
addPointDataHeader()
template<typename FileWriter , typename fp = float> void VtkPointBinaryWriter< FileWriter, fp >::addPointDataHeader ()
Definition at line 135 of file point.h.
References assert, VtkPointWriterBase< FileWriter >::pointCount, and VtkPointWriterBase< FileWriter >::writer.
addScalar()
template<typename FileWriter , typename fp = float> void VtkPointBinaryWriter< FileWriter, fp >::addScalar (fp value)
Definition at line 149 of file point.h.
References VtkPointWriterBase< FileWriter >::byteswapped(), and VtkPointWriterBase< FileWriter >::writer.
addScalarPointDataHeader()
template<typename FileWriter , typename fp = float> void VtkPointBinaryWriter< FileWriter, fp >::addScalarPointDataHeader (const char * name)
Definition at line 142 of file point.h.
References assert, and VtkPointWriterBase< FileWriter >::writer.
finish()
template<typename FileWriter , typename fp = float> void VtkPointBinaryWriter< FileWriter, fp >::finish ()
Definition at line 153 of file point.h.
References VtkPointWriterBase< FileWriter >::updatePointsCount(), and VtkPointWriterBase< FileWriter >::writer.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/vtk/writer/point.h