Peano
tl Namespace Reference
Namespaces
namespace cursor
namespace detail
namespace meta
namespace views
Data Structures
struct as_sentinel_t
class basic_iterator
class basic_mixin
class basic_sentinel
class cartesian_product_view
class cartesian_product_view< std::ranges::iota_view< W, B > >
class cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >
class cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >
struct compose_fn
struct pipeable_base
struct pipeable_fn
class stride_view
Concepts
concept simple_view
concept is_pipeable
Typedefs
template<class... V>
using common_iterator_category = decltype(detail::common_iterator_category<V...>())
template<bool Const, class T >
using maybe_const = std::conditional_t<Const, const T, T>
template<std::size_t N>
using index_constant = std::integral_constant<std::size_t, N>
template<class... Ts>
using tuple_or_pair = typename detail::tuple_or_pair_impl<Ts...>::type
Functions
template<class C >
requires cursor::random_access<C>
constexpr basic_iterator< C > operator+ (const basic_iterator< C > &i, cursor::difference_type_t< C > n) noexcept(std::is_nothrow_copy_constructible< basic_iterator< C > >::value &&std::is_nothrow_move_constructible< basic_iterator< C > >::value &&noexcept(std::declval< basic_iterator< C > & >()+=n))
template<class C >
requires cursor::random_access<C>
constexpr basic_iterator< C > operator+ (cursor::difference_type_t< C > n, const basic_iterator< C > &i) noexcept(noexcept(i+n))
template<class C >
requires cursor::random_access<C>
constexpr basic_iterator< C > operator- (const basic_iterator< C > &i, cursor::difference_type_t< C > n) noexcept(noexcept(i+(-n)))
template<class C1 , class C2 >
requires cursor::sized_sentinel_for<C1, C2>
constexpr cursor::difference_type_t< C2 > operator- (const basic_iterator< C1 > &lhs, const basic_iterator< C2 > &rhs) noexcept(noexcept(rhs.get().distance_to(lhs.get())))
template<class C , class S >
requires cursor::sized_sentinel_for<S, C>
constexpr cursor::difference_type_t< C > operator- (const S &lhs, const basic_iterator< C > &rhs) noexcept(noexcept(rhs.get().distance_to(lhs)))
template<class C , class S >
requires cursor::sized_sentinel_for<S, C>
constexpr cursor::difference_type_t< C > operator- (const basic_iterator< C > &lhs, const S &rhs) noexcept(noexcept(-(rhs - lhs)))
template<class C1 , class C2 >
requires cursor::sentinel_for<C2, C1>
constexpr bool operator== (const basic_iterator< C1 > &lhs, const basic_iterator< C2 > &rhs) noexcept(noexcept(lhs.get().equal(rhs.get())))
template<class C , class S >
requires cursor::sentinel_for<S, C>
constexpr bool operator== (const basic_iterator< C > &lhs, const S &rhs) noexcept(noexcept(lhs.get().equal(rhs)))
template<class C , class S >
requires cursor::sentinel_for<S, C>
constexpr bool operator== (const S &lhs, const basic_iterator< C > &rhs) noexcept(noexcept(rhs==lhs))
template<class C1 , class C2 >
requires cursor::sentinel_for<C2, C1>
constexpr bool operator!= (const basic_iterator< C1 > &lhs, const basic_iterator< C2 > &rhs) noexcept(noexcept(!(lhs==rhs)))
template<class C , class S >
requires cursor::sentinel_for<S, C>
constexpr bool operator!= (const basic_iterator< C > &lhs, const S &rhs) noexcept(noexcept(!lhs.get().equal(rhs)))
template<class C , class S >
requires cursor::sentinel_for<S, C>
constexpr bool operator!= (const S &lhs, const basic_iterator< C > &rhs) noexcept(noexcept(!rhs.get().equal(lhs)))
template<class C1 , class C2 >
requires cursor::sized_sentinel_for<C1, C2>
constexpr bool operator< (const basic_iterator< C1 > &lhs, const basic_iterator< C2 > &rhs) noexcept(noexcept(lhs - rhs< 0))
template<class C1 , class C2 >
requires cursor::sized_sentinel_for<C1, C2>
constexpr bool operator> (const basic_iterator< C1 > &lhs, const basic_iterator< C2 > &rhs) noexcept(noexcept((lhs - rhs) > 0))
template<class C1 , class C2 >
requires cursor::sized_sentinel_for<C1, C2>
constexpr bool operator<= (const basic_iterator< C1 > &lhs, const basic_iterator< C2 > &rhs) noexcept(noexcept((lhs - rhs)<=0))
template<class C1 , class C2 >
requires cursor::sized_sentinel_for<C1, C2>
constexpr bool operator>= (const basic_iterator< C1 > &lhs, const basic_iterator< C2 > &rhs) noexcept(noexcept((lhs - rhs) >=0))
template<class F , class G >
constexpr auto compose (F &&f, G &&g)
template<class F >
constexpr auto pipeable (F f)
template<class V , class Pipe >
requires (!is_pipeable<V> && is_pipeable<Pipe> && std::invocable<Pipe, V>)
constexpr auto operator| (V &&v, Pipe &&fn)
template<class Pipe1 , class Pipe2 >
requires (is_pipeable<Pipe1>&& is_pipeable<Pipe2>)
constexpr auto operator| (Pipe1 &&p1, Pipe2 &&p2)
template<class F , class... Args>
constexpr auto bind_back (F &&f, Args &&... args)
template<class Tuple >
constexpr auto min_tuple (Tuple &&tuple)
template<class Tuple >
constexpr auto max_tuple (Tuple &&tuple)
template<class F , class... Tuples>
constexpr auto tuple_transform (F &&f, Tuples &&... tuples)
template<class F , class Tuple >
constexpr auto tuple_for_each (F &&f, Tuple &&tuple)
template<class Tuple >
constexpr auto tuple_pop_front (Tuple &&tuple)
template<class F , class T , class Tuple >
constexpr auto tuple_fold (Tuple tuple, T t, F f)
template<class... Tuples>
constexpr auto tuple_zip (Tuples &&... tuples)
template<class... Rs>
cartesian_product_view (Rs &&...) -> cartesian_product_view< std::views::all_t< Rs >... >
template<class R , class N >
stride_view (R &&, N n) -> stride_view< std::views::all_t< R > >
Variables
constexpr as_sentinel_t as_sentinel
template<class Tuple >
constexpr std::size_t tuple_size = std::tuple_size_v<std::remove_cvref_t<Tuple>>
Typedef Documentation
common_iterator_category
template<class... V> using tl::common_iterator_category = decltype(detail::common_iterator_category<V...>())
Definition at line 188 of file cartesian_product.h.
index_constant
template<std::size_t N> using tl::index_constant = std::integral_constant<std::size_t, N>
Definition at line 1009 of file cartesian_product.h.
maybe_const
template<bool Const, class T > using tl::maybe_const = std::conditional_t<Const, const T, T>
Definition at line 200 of file cartesian_product.h.
tuple_or_pair
template<class... Ts> using tl::tuple_or_pair = typename detail::tuple_or_pair_impl<Ts...>::type
Definition at line 1040 of file cartesian_product.h.
Function Documentation
bind_back()
template<class F , class... Args> constexpr auto tl::bind_back (F && f, Args &&... args) constexpr
Definition at line 989 of file cartesian_product.h.
Referenced by tl::views::detail::stride_fn::operator()().
cartesian_product_view()
template<class... Rs> tl::cartesian_product_view (Rs && ...) -> cartesian_product_view< std::views::all_t< Rs >... >
compose()
template<class F , class G > constexpr auto tl::compose (F && f, G && g) constexpr
Definition at line 947 of file cartesian_product.h.
Referenced by operator|().
max_tuple()
template<class Tuple > constexpr auto tl::max_tuple (Tuple && tuple) constexpr
Definition at line 1052 of file cartesian_product.h.
min_tuple()
template<class Tuple > constexpr auto tl::min_tuple (Tuple && tuple) constexpr
Definition at line 1043 of file cartesian_product.h.
Referenced by tuple_transform(), and tuple_zip().
operator!=() [1/3]
template<class C , class S > requires cursor::sentinel_for<S, C> constexpr bool tl::operator!= (const basic_iterator< C > & lhs, const S & rhs) constexpr noexcept
Definition at line 838 of file cartesian_product.h.
operator!=() [2/3]
template<class C1 , class C2 > requires cursor::sentinel_for<C2, C1> constexpr bool tl::operator!= (const basic_iterator< C1 > & lhs, const basic_iterator< C2 > & rhs) constexpr noexcept
Definition at line 831 of file cartesian_product.h.
operator!=() [3/3]
template<class C , class S > requires cursor::sentinel_for<S, C> constexpr bool tl::operator!= (const S & lhs, const basic_iterator< C > & rhs) constexpr noexcept
Definition at line 845 of file cartesian_product.h.
operator+() [1/2]
template<class C > requires cursor::random_access<C> constexpr basic_iterator< C > tl::operator+ (const basic_iterator< C > & i, cursor::difference_type_t< C > n) constexpr noexcept
Definition at line 759 of file cartesian_product.h.
operator+() [2/2]
template<class C > requires cursor::random_access<C> constexpr basic_iterator< C > tl::operator+ (cursor::difference_type_t< C > n, const basic_iterator< C > & i) constexpr noexcept
Definition at line 770 of file cartesian_product.h.
operator-() [1/4]
template<class C > requires cursor::random_access<C> constexpr basic_iterator< C > tl::operator- (const basic_iterator< C > & i, cursor::difference_type_t< C > n) constexpr noexcept
Definition at line 778 of file cartesian_product.h.
operator-() [2/4]
template<class C , class S > requires cursor::sized_sentinel_for<S, C> constexpr cursor::difference_type_t< C > tl::operator- (const basic_iterator< C > & lhs, const S & rhs) constexpr noexcept
Definition at line 801 of file cartesian_product.h.
operator-() [3/4]
template<class C1 , class C2 > requires cursor::sized_sentinel_for<C1, C2> constexpr cursor::difference_type_t< C2 > tl::operator- (const basic_iterator< C1 > & lhs, const basic_iterator< C2 > & rhs) constexpr noexcept
Definition at line 786 of file cartesian_product.h.
operator-() [4/4]
template<class C , class S > requires cursor::sized_sentinel_for<S, C> constexpr cursor::difference_type_t< C > tl::operator- (const S & lhs, const basic_iterator< C > & rhs) constexpr noexcept
Definition at line 794 of file cartesian_product.h.
operator<()
template<class C1 , class C2 > requires cursor::sized_sentinel_for<C1, C2> constexpr bool tl::operator< (const basic_iterator< C1 > & lhs, const basic_iterator< C2 > & rhs) constexpr noexcept
Definition at line 853 of file cartesian_product.h.
operator<=()
template<class C1 , class C2 > requires cursor::sized_sentinel_for<C1, C2> constexpr bool tl::operator<= (const basic_iterator< C1 > & lhs, const basic_iterator< C2 > & rhs) constexpr noexcept
Definition at line 869 of file cartesian_product.h.
operator==() [1/3]
template<class C , class S > requires cursor::sentinel_for<S, C> constexpr bool tl::operator== (const basic_iterator< C > & lhs, const S & rhs) constexpr noexcept
Definition at line 816 of file cartesian_product.h.
operator==() [2/3]
template<class C1 , class C2 > requires cursor::sentinel_for<C2, C1> constexpr bool tl::operator== (const basic_iterator< C1 > & lhs, const basic_iterator< C2 > & rhs) constexpr noexcept
Definition at line 809 of file cartesian_product.h.
operator==() [3/3]
template<class C , class S > requires cursor::sentinel_for<S, C> constexpr bool tl::operator== (const S & lhs, const basic_iterator< C > & rhs) constexpr noexcept
Definition at line 823 of file cartesian_product.h.
operator>()
template<class C1 , class C2 > requires cursor::sized_sentinel_for<C1, C2> constexpr bool tl::operator> (const basic_iterator< C1 > & lhs, const basic_iterator< C2 > & rhs) constexpr noexcept
Definition at line 861 of file cartesian_product.h.
operator>=()
template<class C1 , class C2 > requires cursor::sized_sentinel_for<C1, C2> constexpr bool tl::operator>= (const basic_iterator< C1 > & lhs, const basic_iterator< C2 > & rhs) constexpr noexcept
Definition at line 877 of file cartesian_product.h.
operator|() [1/2]
template<class Pipe1 , class Pipe2 > requires (is_pipeable<Pipe1>&& is_pipeable<Pipe2>) constexpr auto tl::operator| (Pipe1 && p1, Pipe2 && p2) constexpr
Definition at line 982 of file cartesian_product.h.
References compose(), and pipeable().
operator|() [2/2]
template<class V , class Pipe > requires (!is_pipeable<V> && is_pipeable<Pipe> && std::invocable<Pipe, V>) constexpr auto tl::operator| (V && v, Pipe && fn) constexpr
Definition at line 976 of file cartesian_product.h.
pipeable()
template<class F > constexpr auto tl::pipeable (F f) constexpr
Definition at line 971 of file cartesian_product.h.
Referenced by tl::views::detail::stride_fn::operator()(), and operator|().
stride_view()
template<class R , class N > tl::stride_view (R && , N n) -> stride_view< std::views::all_t< R > >
Referenced by tl::views::detail::stride_fn_base::operator()().
tuple_fold()
template<class F , class T , class Tuple > constexpr auto tl::tuple_fold (Tuple tuple, T t, F f) constexpr
Definition at line 1119 of file cartesian_product.h.
References tl::detail::tuple_fold_impl().
tuple_for_each()
template<class F , class Tuple > constexpr auto tl::tuple_for_each (F && f, Tuple && tuple) constexpr
Definition at line 1091 of file cartesian_product.h.
tuple_pop_front()
template<class Tuple > constexpr auto tl::tuple_pop_front (Tuple && tuple) constexpr
Definition at line 1099 of file cartesian_product.h.
tuple_transform()
template<class F , class... Tuples> constexpr auto tl::tuple_transform (F && f, Tuples &&... tuples) constexpr
Definition at line 1062 of file cartesian_product.h.
References min_tuple().
Referenced by tl::cartesian_product_view< Vs >::cursor< Const >::read().
tuple_zip()
template<class... Tuples> constexpr auto tl::tuple_zip (Tuples &&... tuples) constexpr
Definition at line 1126 of file cartesian_product.h.
References min_tuple().
Variable Documentation
as_sentinel
constexpr as_sentinel_t tl::as_sentinel constexpr
Definition at line 197 of file cartesian_product.h.
Referenced by tl::cartesian_product_view< Vs >::end(), and tl::cartesian_product_view< Vs >::end().
tuple_size
template<class Tuple > constexpr std::size_t tl::tuple_size = std::tuple_size_v<std::remove_cvref_t<Tuple>> constexpr
Definition at line 1006 of file cartesian_product.h.