Peano
tarch::reader::CheckpointFilesManager Class Reference
A reader class allowing code to load checkpoint subfile if it hasn't be loaded in memory and search in loaded subfiles to find the correct patch data for restarting.
#include <PeanoTextPatchFileReader.h>
Public Member Functions
CheckpointFilesManager (size_t limit)
const std::vector< std::string > & getCheckpointFileData (const std::string &filename)
Private Member Functions
size_t calculateMemoryUsage (const std::vector< std::string > &data)
void freeOldestFile ()
void loadNewFile (const std::string &filename)
Private Attributes
size_t memoryLimit
size_t currentMemoryUsage = 0
std::unordered_map< std::string, std::vector< std::string > > CheckpointFileDataset
std::queue< std::string > loadedCheckpointFileNames
Detailed Description
A reader class allowing code to load checkpoint subfile if it hasn't be loaded in memory and search in loaded subfiles to find the correct patch data for restarting.
Designed for memory-wise option of restarting, ideally this option will be faster than pure loaded approach and also avold momoery fault in for huge domain.
Definition at line 123 of file PeanoTextPatchFileReader.h.
Constructor & Destructor Documentation
CheckpointFilesManager()
tarch::reader::CheckpointFilesManager::CheckpointFilesManager (size_t limit)
Definition at line 171 of file PeanoTextPatchFileReader.h.
Member Function Documentation
calculateMemoryUsage()
size_t tarch::reader::CheckpointFilesManager::calculateMemoryUsage (const std::vector< std::string > & data) private
Definition at line 130 of file PeanoTextPatchFileReader.h.
Referenced by freeOldestFile(), and loadNewFile().
freeOldestFile()
void tarch::reader::CheckpointFilesManager::freeOldestFile () private
Definition at line 138 of file PeanoTextPatchFileReader.h.
References calculateMemoryUsage(), CheckpointFileDataset, currentMemoryUsage, and loadedCheckpointFileNames.
Referenced by loadNewFile().
getCheckpointFileData()
const std::vector< std::string > & tarch::reader::CheckpointFilesManager::getCheckpointFileData (const std::string & filename)
Definition at line 175 of file PeanoTextPatchFileReader.h.
References CheckpointFileDataset, and loadNewFile().
loadNewFile()
void tarch::reader::CheckpointFilesManager::loadNewFile (const std::string & filename) private
Definition at line 147 of file PeanoTextPatchFileReader.h.
References calculateMemoryUsage(), CheckpointFileDataset, currentMemoryUsage, freeOldestFile(), loadedCheckpointFileNames, and memoryLimit.
Referenced by getCheckpointFileData().
Field Documentation
CheckpointFileDataset
std::unordered_map<std::string, std::vector<std::string> > tarch::reader::CheckpointFilesManager::CheckpointFileDataset private
Definition at line 127 of file PeanoTextPatchFileReader.h.
Referenced by freeOldestFile(), getCheckpointFileData(), and loadNewFile().
currentMemoryUsage
size_t tarch::reader::CheckpointFilesManager::currentMemoryUsage = 0 private
Definition at line 126 of file PeanoTextPatchFileReader.h.
Referenced by freeOldestFile(), and loadNewFile().
loadedCheckpointFileNames
std::queue<std::string> tarch::reader::CheckpointFilesManager::loadedCheckpointFileNames private
Definition at line 128 of file PeanoTextPatchFileReader.h.
Referenced by freeOldestFile(), and loadNewFile().
memoryLimit
size_t tarch::reader::CheckpointFilesManager::memoryLimit private
Definition at line 125 of file PeanoTextPatchFileReader.h.
Referenced by loadNewFile().
The documentation for this class was generated from the following file:
src/tarch/reader/PeanoTextPatchFileReader.h