Peano
tarch::plotter::pointdata::vtk::VTKWriter Class Reference
Implementation of the point data writer that basically maps the points onto a vtk text file, i.e.
#include <VTKWriter.h>
Data Structures
class PointDataWriter
A writer to assign points a value.
Public Member Functions
VTKWriter (bool binaryFile, const std::string &fileName, const std::string &indexFileName, tarch::plotter::PVDTimeSeriesWriter::IndexFileMode modeFile, double timeStamp)
virtual ~VTKWriter ()
virtual bool writeToFile () override
Before we write to a file, we have to close the.
virtual bool isOpen () override
virtual void clear () override
Clear the writer, i.e.
virtual int plotPoint (const tarch::la::Vector< 2, double > &position) override
virtual int plotPoint (const tarch::la::Vector< 3, double > &position) override
virtual PointWriter::PointDataWriter * createPointDataWriter (const std::string &identifier, int recordsPerPoint) override
Caller has to destroy this instance manually.
Public Member Functions inherited from tarch::plotter::pointdata::PointWriter
virtual ~PointWriter ()=default
Private Member Functions
VTKWriter (const VTKWriter &writer)=delete
Copy constructor.
VTKWriter & operator= (const VTKWriter &writer)=delete
Assignment operator.
Private Attributes
tarch::plotter::griddata::unstructured::UnstructuredGridWriter * _vtkWriter
tarch::plotter::griddata::unstructured::UnstructuredGridWriter::VertexWriter * _vertexWriter
tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellWriter * _cellWriter
Static Private Attributes
static tarch::mpi::BooleanSemaphore _sempahore
This is a global (mpi) semaphore that I use to update/modify the index file over all files.
Detailed Description
Implementation of the point data writer that basically maps the points onto a vtk text file, i.e.
it uses the unstructured grid writer.
Implementation
Author
Tobias Weinzierl
Definition at line 35 of file VTKWriter.h.
Constructor & Destructor Documentation
VTKWriter() [1/2]
tarch::plotter::pointdata::vtk::VTKWriter::VTKWriter (const VTKWriter & writer) private delete
Copy constructor.
A writer never should be copied. However, we have to make this operation protected to allow implementations to hide their copy constructor as well.
VTKWriter() [2/2]
tarch::plotter::pointdata::vtk::VTKWriter::VTKWriter (bool binaryFile, const std::string & fileName, const std::string & indexFileName, tarch::plotter::PVDTimeSeriesWriter::IndexFileMode modeFile, double timeStamp)
Parameters
fileName Name of the file to write. Has to be unique per dump.
indexFileName Name of the index file. Can we empty if you select NoIndexFile.
Definition at line 10 of file VTKWriter.cpp.
References _cellWriter, _vertexWriter, _vtkWriter, tarch::plotter::griddata::unstructured::UnstructuredGridWriter::createCellWriter(), tarch::plotter::griddata::unstructured::UnstructuredGridWriter::createVertexWriter(), and timeStamp.
~VTKWriter()
tarch::plotter::pointdata::vtk::VTKWriter::~VTKWriter () virtual
Definition at line 25 of file VTKWriter.cpp.
References assertionMsg.
Member Function Documentation
clear()
void tarch::plotter::pointdata::vtk::VTKWriter::clear () override virtual
Clear the writer, i.e.
erase all the data. However, as the writer does not track how many vertex and cell writers you've created, it's up to you to ensure that none of these instances is left.
Implements tarch::plotter::pointdata::PointWriter.
Definition at line 59 of file VTKWriter.cpp.
Referenced by peano4.output.Makefile.Makefile::__init__().
createPointDataWriter()
tarch::plotter::pointdata::PointWriter::PointDataWriter * tarch::plotter::pointdata::vtk::VTKWriter::createPointDataWriter (const std::string & identifier, int recordsPerPoint) override virtual
Caller has to destroy this instance manually.
Implements tarch::plotter::pointdata::PointWriter.
Definition at line 33 of file VTKWriter.cpp.
isOpen()
bool tarch::plotter::pointdata::vtk::VTKWriter::isOpen () override virtual
Returns
Whether writer is ready to accept data.
Implements tarch::plotter::pointdata::PointWriter.
Definition at line 54 of file VTKWriter.cpp.
operator=()
VTKWriter & tarch::plotter::pointdata::vtk::VTKWriter::operator= (const VTKWriter & writer) private delete
Assignment operator.
A writer never should be copied. However, we have to make this operation protected to allow implementations to hide their copy constructor as well.
plotPoint() [1/2]
int tarch::plotter::pointdata::vtk::VTKWriter::plotPoint (const tarch::la::Vector< 2, double > & position) override virtual
Implements tarch::plotter::pointdata::PointWriter.
Definition at line 64 of file VTKWriter.cpp.
plotPoint() [2/2]
int tarch::plotter::pointdata::vtk::VTKWriter::plotPoint (const tarch::la::Vector< 3, double > & position) override virtual
Implements tarch::plotter::pointdata::PointWriter.
Definition at line 71 of file VTKWriter.cpp.
writeToFile()
bool tarch::plotter::pointdata::vtk::VTKWriter::writeToFile () override virtual
Before we write to a file, we have to close the.
vertex writer
call writer
However, we might have closed the point data plotters already and thus they might be down already. So we close them only if they are still up.
See also
PointDataWriter::close()
Implements tarch::plotter::pointdata::PointWriter.
Definition at line 38 of file VTKWriter.cpp.
Field Documentation
_cellWriter
tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellWriter* tarch::plotter::pointdata::vtk::VTKWriter::_cellWriter private
Definition at line 46 of file VTKWriter.h.
Referenced by VTKWriter().
_sempahore
tarch::mpi::BooleanSemaphore tarch::plotter::pointdata::vtk::VTKWriter::_sempahore static private
This is a global (mpi) semaphore that I use to update/modify the index file over all files.
The individual data writes are totally concurrent.
Definition at line 42 of file VTKWriter.h.
_vertexWriter
tarch::plotter::griddata::unstructured::UnstructuredGridWriter::VertexWriter* tarch::plotter::pointdata::vtk::VTKWriter::_vertexWriter private
Definition at line 45 of file VTKWriter.h.
Referenced by VTKWriter().
_vtkWriter
tarch::plotter::griddata::unstructured::UnstructuredGridWriter* tarch::plotter::pointdata::vtk::VTKWriter::_vtkWriter private
Definition at line 44 of file VTKWriter.h.
Referenced by VTKWriter().
The documentation for this class was generated from the following files:
src/tarch/plotter/pointdata/vtk/VTKWriter.h
src/tarch/plotter/pointdata/vtk/VTKWriter.cpp