Peano
DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK > Class Template Reference
#include <dma.h>
Data Structures
struct BUF
Public Member Functions
DmaWriter (i32 fd) noexcept
DmaWriter ()=default
DmaWriter (const DmaWriter &)=delete
DmaWriter & operator= (DmaWriter &&other) noexcept
template<typename T >
requires (!std::is_pointer_v<T>)
void write (T val)
void write (std::string_view s)
void write (const void *ptr, u64 n)
void seek (u64 pos)
void * buffer (u64 n)
void sync ()
u64 getPos ()
~DmaWriter ()
Private Member Functions
aiocb * getCb ()
aiocb * pickNextCb ()
void syncCb (aiocb *cb)
void flushCb (aiocb *cb)
void flushCbAsync ()
char * getBuf ()
Static Private Member Functions
static constexpr u64 BUFF_SIZE ()
Private Attributes
aiocb * cbs = nullptr
u64 len = 0
u64 offset = 0
u64 max_len = 0
u32 prefill = 0
i32 fd = -1
u8 idx = 0
Detailed Description
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512>
class DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >
Definition at line 17 of file dma.h.
Constructor & Destructor Documentation
DmaWriter() [1/3]
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::DmaWriter (i32 fd) explicit noexcept
Definition at line 162 of file dma.h.
References assert.
DmaWriter() [2/3]
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::DmaWriter () explicit default
DmaWriter() [3/3]
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::DmaWriter (const DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK > &) delete
~DmaWriter()
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::~DmaWriter ()
Definition at line 264 of file dma.h.
Member Function Documentation
BUFF_SIZE()
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> static constexpr u64 DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::BUFF_SIZE () static constexpr private
Definition at line 18 of file dma.h.
buffer()
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> void * DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::buffer (u64 n)
Definition at line 240 of file dma.h.
flushCb()
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> void DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::flushCb (aiocb * cb) private
Definition at line 86 of file dma.h.
References assert, DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::fd, DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::len, DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::offset, and DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::prefill.
Referenced by DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::flushCbAsync().
flushCbAsync()
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> void DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::flushCbAsync () private
Definition at line 145 of file dma.h.
References DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::flushCb(), DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::getCb(), and DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::pickNextCb().
getBuf()
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> char * DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::getBuf () private
Definition at line 153 of file dma.h.
References DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::getCb(), and DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::len.
getCb()
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> aiocb * DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::getCb () private
Definition at line 36 of file dma.h.
References DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::idx.
Referenced by DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::flushCbAsync(), and DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::getBuf().
getPos()
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> u64 DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::getPos ()
Definition at line 259 of file dma.h.
operator=()
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> DmaWriter & DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::operator= (DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK > && other) noexcept
Definition at line 176 of file dma.h.
References DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::cbs.
pickNextCb()
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> aiocb * DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::pickNextCb () private
Definition at line 40 of file dma.h.
References assert.
Referenced by DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::flushCbAsync().
seek()
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> void DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::seek (u64 pos)
Definition at line 231 of file dma.h.
References assert.
sync()
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> void DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::sync ()
Definition at line 247 of file dma.h.
References assert.
syncCb()
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> void DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::syncCb (aiocb * cb) private
Definition at line 69 of file dma.h.
References assert.
write() [1/3]
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> void DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::write (const void * ptr, u64 n)
Definition at line 214 of file dma.h.
write() [2/3]
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> void DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::write (std::string_view s)
Definition at line 210 of file dma.h.
write() [3/3]
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> template<typename T > requires (!std::is_pointer_v<T>) void DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::write (T val)
Definition at line 198 of file dma.h.
Field Documentation
cbs
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> aiocb* DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::cbs = nullptr private
Definition at line 27 of file dma.h.
Referenced by DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::operator=().
fd
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> i32 DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::fd = -1 private
Definition at line 33 of file dma.h.
Referenced by DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::flushCb().
idx
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> u8 DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::idx = 0 private
Definition at line 34 of file dma.h.
Referenced by DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::getCb().
len
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> u64 DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::len = 0 private
Definition at line 29 of file dma.h.
Referenced by DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::flushCb(), and DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::getBuf().
max_len
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> u64 DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::max_len = 0 private
Definition at line 31 of file dma.h.
offset
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> u64 DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::offset = 0 private
Definition at line 30 of file dma.h.
Referenced by peano4.visualisation.input.Patch.Patch::__repr__(), and DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::flushCb().
prefill
template<u64 T_BUFF_SIZE = 1024 * 1024 * 1, u8 WIDTH = 4, i32 BLOCK = 512> u32 DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::prefill = 0 private
Definition at line 32 of file dma.h.
Referenced by DmaWriter< T_BUFF_SIZE, WIDTH, BLOCK >::flushCb().
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/io/writer/dma.h