Peano
Scenario.Scenario.Scenario Class Reference
Public Member Functions
initial_conditions (self)
generate_required_files (self, order)
generate_file_from_template (self, template_file, full_qualified_filename, dictionary)
copy_file_to_current_folder (self, current_filename, full_qualified_filename)
Static Public Attributes
list domain_offset = [1., 1., 1.]
list domain_size = [1., 1., 1.]
float end_time = 0.0
list tracer_coordinates = []
Detailed Description
Definition at line 7 of file Scenario.py.
Member Function Documentation
copy_file_to_current_folder()
Scenario.Scenario.Scenario.copy_file_to_current_folder (self, current_filename, full_qualified_filename)
Definition at line 32 of file Scenario.py.
Referenced by Scenario.TPV26.TPV26.generate_required_files(), Scenario.TPV28.TPV28.generate_required_files(), Scenario.TPV29.TPV29.generate_required_files(), and Scenario.TPV5.TPV5.generate_required_files().
generate_file_from_template()
Scenario.Scenario.Scenario.generate_file_from_template (self, template_file, full_qualified_filename, dictionary)
Definition at line 21 of file Scenario.py.
Referenced by Scenario.HHS1.HHS1.generate_required_files(), Scenario.LOH1.LOH1.generate_required_files(), Scenario.TPV26.TPV26.generate_required_files(), Scenario.TPV28.TPV28.generate_required_files(), Scenario.TPV29.TPV29.generate_required_files(), Scenario.TPV5.TPV5.generate_required_files(), and Scenario.Zugspitze.Zugspitze.generate_required_files().
generate_required_files()
Scenario.Scenario.Scenario.generate_required_files (self, order)
Reimplemented in Scenario.HHS1.HHS1, Scenario.LOH1.LOH1, Scenario.TPV26.TPV26, Scenario.TPV28.TPV28, Scenario.TPV29.TPV29, Scenario.TPV5.TPV5, and Scenario.Zugspitze.Zugspitze.
Definition at line 18 of file Scenario.py.
initial_conditions()
Scenario.Scenario.Scenario.initial_conditions (self)
Reimplemented in Scenario.HHS1.HHS1, Scenario.LOH1.LOH1, Scenario.TPV26.TPV26, Scenario.TPV28.TPV28, Scenario.TPV29.TPV29, Scenario.TPV5.TPV5, and Scenario.Zugspitze.Zugspitze.
Definition at line 15 of file Scenario.py.
Field Documentation
domain_offset
list Scenario.Scenario.Scenario.domain_offset = [1., 1., 1.] static
Definition at line 8 of file Scenario.py.
domain_size
list Scenario.Scenario.Scenario.domain_size = [1., 1., 1.] static
Definition at line 9 of file Scenario.py.
end_time
float Scenario.Scenario.Scenario.end_time = 0.0 static
Definition at line 11 of file Scenario.py.
tracer_coordinates
list Scenario.Scenario.Scenario.tracer_coordinates = [] static
Definition at line 13 of file Scenario.py.
The documentation for this class was generated from the following file:
applications/exahype2/exaseis/ExaSeis_core/Scenario/Scenario.py