var namespacesolvers_1_1api_1_1CollocatedDLinearDiscretisationWithPointJacobi =
[
    [ "CollocatedDLinearDiscretisationWithPointJacobi", "d6/d20/classsolvers_1_1api_1_1CollocatedDLinearDiscretisationWithPointJacobi_1_1CollocatedDLinearDiscretisationWithPointJacobi.html", "d6/d20/classsolvers_1_1api_1_1CollocatedDLinearDiscretisationWithPointJacobi_1_1CollocatedDLinearDiscretisationWithPointJacobi" ]
];