Peano
BlockBoundary Class Reference
#include <blockBoundary.h>
Public Types
enum BlockFace {
LEFT = 0 , RIGHT = 1 , BOTTOM = 2 , TOP = 3 ,
FRONT = 4 , BACK = 5
}
Public Member Functions
BlockBoundary (Coordinate a_coords[3])
BlockBoundary (Coordinate c0, Coordinate c1, Coordinate c2)
BlockBoundary (Face topography, bool top, int n_depth, double depth)
double & operator() (BlockFace face, Coordinate coord, int j, int i)
const Face & getFace (BlockFace face)
const Face & getFace (Coordinate coord, bool upper)
void setFace (BlockFace face, const Face &other)
void setFace (Coordinate coord, bool upper, Face other)
void getIndexSize (int a_index_size[3])
void split (Face &face, BlockBoundary &left, BlockBoundary &right)
void setCoord (Coordinate a_coords[3])
void getCoord (Coordinate a_coords[3])
Coordinate getCoord (int i)
void setIndexOffset (int a_index_offset[3])
void setIndexSize (int a_index_size[3])
void getIndexOffset (int a_index_offset[3]) const
int getIndexOffset (Coordinate coord) const
void getIndexSize (int a_index_size[3]) const
int getIndexSize (Coordinate coord) const
void getBoundingBox (double offset[3], double size[3])
void toNetCDF (std::string prefix)
FaceBoundary setupSplittingFace (Coordinate cycx[2], int fault_index, double fault_position, int indexOffset_fault[3])
std::string toString (int depth=0) const
std::string printFaces ()
void checkConformity ()
Private Attributes
Face left_face
Face right_face
Face bottom_face
Face top_face
Face front_face
Face back_face
int index_offset [3]
int index_size [3]
Coordinate coords [3]
Detailed Description
Definition at line 16 of file blockBoundary.h.
Member Enumeration Documentation
BlockFace
enum BlockBoundary::BlockFace
Enumerator
LEFT
RIGHT
BOTTOM
TOP
FRONT
BACK
Definition at line 19 of file blockBoundary.h.
Constructor & Destructor Documentation
BlockBoundary() [1/3]
BlockBoundary::BlockBoundary (Coordinate a_coords[3])
Definition at line 27 of file blockBoundary.h.
References coords.
BlockBoundary() [2/3]
BlockBoundary::BlockBoundary (Coordinate c0, Coordinate c1, Coordinate c2)
Definition at line 31 of file blockBoundary.h.
References coords.
BlockBoundary() [3/3]
BlockBoundary::BlockBoundary (Face topography, bool top, int n_depth, double depth)
Definition at line 37 of file blockBoundary.h.
References checkConformity(), coords, Face::getCoord(), FaceBoundary::getEdge(), getFace(), Face::getIndexOffset(), Face::getIndexRange(), Face::getIndexSize(), getNormal(), Face::getPosition(), index_offset, index_size, and setFace().
Member Function Documentation
checkConformity()
void BlockBoundary::checkConformity ()
Definition at line 630 of file blockBoundary.h.
References coords, Face::getCoord(), getFace(), Face::getIndexOffset(), Face::getIndexSize(), getNormal(), index_offset, index_size, and toString().
Referenced by BlockBoundary().
getBoundingBox()
void BlockBoundary::getBoundingBox (double offset[3], double size[3])
Definition at line 492 of file blockBoundary.h.
References Face::getCoord(), getFace(), and Face::getIndexRange().
Referenced by setupSplittingFace().
getCoord() [1/2]
void BlockBoundary::getCoord (Coordinate a_coords[3])
Definition at line 458 of file blockBoundary.h.
References coords.
getCoord() [2/2]
Coordinate BlockBoundary::getCoord (int i)
Definition at line 462 of file blockBoundary.h.
References coords.
getFace() [1/2]
const Face & BlockBoundary::getFace (BlockFace face)
Definition at line 245 of file blockBoundary.h.
References BACK, back_face, BOTTOM, bottom_face, FRONT, front_face, LEFT, left_face, RIGHT, right_face, TOP, and top_face.
Referenced by BlockBoundary(), checkConformity(), getBoundingBox(), printFaces(), split(), and toNetCDF().
getFace() [2/2]
const Face & BlockBoundary::getFace (Coordinate coord, bool upper)
Definition at line 266 of file blockBoundary.h.
References back_face, bottom_face, coords, front_face, left_face, right_face, and top_face.
getIndexOffset() [1/2]
int BlockBoundary::getIndexOffset (Coordinate coord) const
Definition at line 479 of file blockBoundary.h.
References index_offset.
getIndexOffset() [2/2]
void BlockBoundary::getIndexOffset (int a_index_offset[3]) const
Definition at line 475 of file blockBoundary.h.
References index_offset.
getIndexSize() [1/3]
int BlockBoundary::getIndexSize (Coordinate coord) const
Definition at line 488 of file blockBoundary.h.
References index_size.
getIndexSize() [2/3]
void BlockBoundary::getIndexSize (int a_index_size[3])
Definition at line 339 of file blockBoundary.h.
References index_size.
getIndexSize() [3/3]
void BlockBoundary::getIndexSize (int a_index_size[3]) const
Definition at line 484 of file blockBoundary.h.
References index_size.
operator()()
double & BlockBoundary::operator() (BlockFace face, Coordinate coord, int j, int i)
Definition at line 218 of file blockBoundary.h.
References BACK, back_face, BOTTOM, bottom_face, FRONT, front_face, index_size, LEFT, left_face, NCOORDS, RIGHT, right_face, TOP, and top_face.
printFaces()
std::string BlockBoundary::printFaces ()
Definition at line 612 of file blockBoundary.h.
References coords, and getFace().
setCoord()
void BlockBoundary::setCoord (Coordinate a_coords[3])
Definition at line 454 of file blockBoundary.h.
References coords.
setFace() [1/2]
void BlockBoundary::setFace (BlockFace face, const Face & other)
Definition at line 292 of file blockBoundary.h.
References BACK, back_face, BOTTOM, bottom_face, FRONT, front_face, LEFT, left_face, RIGHT, right_face, TOP, and top_face.
Referenced by BlockBoundary().
setFace() [2/2]
void BlockBoundary::setFace (Coordinate coord, bool upper, Face other)
Definition at line 314 of file blockBoundary.h.
References back_face, bottom_face, coords, front_face, left_face, right_face, and top_face.
setIndexOffset()
void BlockBoundary::setIndexOffset (int a_index_offset[3])
Definition at line 467 of file blockBoundary.h.
References index_offset.
setIndexSize()
void BlockBoundary::setIndexSize (int a_index_size[3])
Definition at line 471 of file blockBoundary.h.
References index_size.
setupSplittingFace()
FaceBoundary BlockBoundary::setupSplittingFace (Coordinate cycx[2], int fault_index, double fault_position, int indexOffset_fault[3])
Definition at line 535 of file blockBoundary.h.
References getBoundingBox(), getNormal(), index_offset, and index_size.
split()
void BlockBoundary::split (Face & face, BlockBoundary & left, BlockBoundary & right)
Definition at line 343 of file blockBoundary.h.
References coordToString(), Face::getCoord(), getFace(), Face::getIndexOffset(), Face::getIndexSize(), getNormal(), Face::getPerturbation(), Face::getPosition(), index_offset, index_size, Face::split(), Face::toNetCDF(), toString(), X, Y, and Z.
toNetCDF()
void BlockBoundary::toNetCDF (std::string prefix)
Definition at line 524 of file blockBoundary.h.
References coordToString(), getFace(), and Face::toNetCDF().
toString()
std::string BlockBoundary::toString (int depth = 0) const
Definition at line 578 of file blockBoundary.h.
References coords, coordToString(), index_offset, and index_size.
Referenced by checkConformity(), split(), and Leaf::toString().
Field Documentation
back_face
Face BlockBoundary::back_face private
Definition at line 671 of file blockBoundary.h.
Referenced by getFace(), getFace(), operator()(), setFace(), and setFace().
bottom_face
Face BlockBoundary::bottom_face private
Definition at line 668 of file blockBoundary.h.
Referenced by getFace(), getFace(), operator()(), setFace(), and setFace().
coords
Coordinate BlockBoundary::coords[3] private
Definition at line 675 of file blockBoundary.h.
Referenced by BlockBoundary(), BlockBoundary(), BlockBoundary(), checkConformity(), getCoord(), getCoord(), getFace(), printFaces(), setCoord(), setFace(), and toString().
front_face
Face BlockBoundary::front_face private
Definition at line 670 of file blockBoundary.h.
Referenced by getFace(), getFace(), operator()(), setFace(), and setFace().
index_offset
int BlockBoundary::index_offset[3] private
Definition at line 673 of file blockBoundary.h.
Referenced by BlockBoundary(), checkConformity(), getIndexOffset(), getIndexOffset(), setIndexOffset(), setupSplittingFace(), split(), and toString().
index_size
int BlockBoundary::index_size[3] private
Definition at line 674 of file blockBoundary.h.
Referenced by BlockBoundary(), checkConformity(), getIndexSize(), getIndexSize(), getIndexSize(), operator()(), setIndexSize(), setupSplittingFace(), split(), and toString().
left_face
Face BlockBoundary::left_face private
Definition at line 666 of file blockBoundary.h.
Referenced by getFace(), getFace(), operator()(), setFace(), and setFace().
right_face
Face BlockBoundary::right_face private
Definition at line 667 of file blockBoundary.h.
Referenced by getFace(), getFace(), operator()(), setFace(), and setFace().
top_face
Face BlockBoundary::top_face private
Definition at line 669 of file blockBoundary.h.
Referenced by getFace(), getFace(), operator()(), setFace(), and setFace().
The documentation for this class was generated from the following file:
src/toolbox/curvi/geometry/blockBoundary.h