var rkdg_2actionsets_2PostprocessSolution_8py =
[
    [ "exahype2.solvers.rkdg.actionsets.PostprocessSolution.EmptyPostprocessSolution", "d1/d9d/classexahype2_1_1solvers_1_1rkdg_1_1actionsets_1_1PostprocessSolution_1_1EmptyPostprocessSolution.html", "d1/d9d/classexahype2_1_1solvers_1_1rkdg_1_1actionsets_1_1PostprocessSolution_1_1EmptyPostprocessSolution" ],
    [ "exahype2.solvers.rkdg.actionsets.PostprocessSolution.DoFWisePostprocessSolution", "d0/d3f/classexahype2_1_1solvers_1_1rkdg_1_1actionsets_1_1PostprocessSolution_1_1DoFWisePostprocessSolution.html", "d0/d3f/classexahype2_1_1solvers_1_1rkdg_1_1actionsets_1_1PostprocessSolution_1_1DoFWisePostprocessSolution" ],
    [ "exahype2.solvers.rkdg.actionsets.PostprocessSolution.CellWisePostprocessSolution", "db/d55/classexahype2_1_1solvers_1_1rkdg_1_1actionsets_1_1PostprocessSolution_1_1CellWisePostprocessSolution.html", "db/d55/classexahype2_1_1solvers_1_1rkdg_1_1actionsets_1_1PostprocessSolution_1_1CellWisePostprocessSolution" ]
];