Peano
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter Class Reference
#include <PeanoTextPatchFileWriter.h>
Public Member Functions
CellDataWriter (const std::string &identifier, int unknownsPerAxis, int numberOfUnknowns, const std::string &description, const std::string &metaData, double *mapping, tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter &writer)
virtual ~CellDataWriter ()
void setPrecision (int precision)
int getCellsPerPatch () const
void plotCell (int index, double value)
Write data for one cell.
void plotCell (int index, double *values)
template<typename T >
void plotCell (int index, T value)
template<typename T >
void plotCell (int index, T *values)
virtual void close () override
If you close your writer, each cell/vertex has to be assigned a value, i.e.
virtual void assignRemainingCellsDefaultValues () override
virtual int getFirstCellWithinPatch (int index) const override
Protected Member Functions
void flushIfPatchIsComplete ()
Protected Attributes
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter & _writer
const std::string _identifier
const int _numberOfCellsPerAxis
const int _numberOfUnknowns
int _entryCounter
std::stringstream _out
Detailed Description
Definition at line 113 of file PeanoTextPatchFileWriter.h.
Constructor & Destructor Documentation
CellDataWriter()
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::CellDataWriter (const std::string & identifier, int unknownsPerAxis, int numberOfUnknowns, const std::string & description, const std::string & metaData, double * mapping, tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter & writer)
Definition at line 7 of file PeanoTextPatchFileWriter_CellDataWriter.cpp.
References _numberOfCellsPerAxis, _numberOfUnknowns, _out, tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::_snapshotFileOut, _writer, getCellsPerPatch(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::writeMapping(), and tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::writeMetaData().
~CellDataWriter()
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::~CellDataWriter () virtual
Reimplemented from tarch::plotter::griddata::blockstructured::PatchWriter::CellDataWriter.
Definition at line 33 of file PeanoTextPatchFileWriter_CellDataWriter.cpp.
Member Function Documentation
assignRemainingCellsDefaultValues()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::assignRemainingCellsDefaultValues () override virtual
See also
close()
Implements tarch::plotter::griddata::blockstructured::PatchWriter::CellDataWriter.
Definition at line 99 of file PeanoTextPatchFileWriter_CellDataWriter.cpp.
References assertionMsg.
close()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::close () override virtual
If you close your writer, each cell/vertex has to be assigned a value, i.e.
you may not add less data than you have cells. See
Implements tarch::plotter::griddata::blockstructured::PatchWriter::CellDataWriter.
Definition at line 84 of file PeanoTextPatchFileWriter_CellDataWriter.cpp.
flushIfPatchIsComplete()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::flushIfPatchIsComplete () protected
Definition at line 87 of file PeanoTextPatchFileWriter_CellDataWriter.cpp.
Referenced by plotCell().
getCellsPerPatch()
int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::getCellsPerPatch () const
Definition at line 36 of file PeanoTextPatchFileWriter_CellDataWriter.cpp.
References tarch::la::aPowI().
Referenced by CellDataWriter().
getFirstCellWithinPatch()
int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::getFirstCellWithinPatch (int patchIndex) const override virtual
See also
plotCell()
Implements tarch::plotter::griddata::blockstructured::PatchWriter::CellDataWriter.
Definition at line 104 of file PeanoTextPatchFileWriter_CellDataWriter.cpp.
plotCell() [1/4]
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::plotCell (int index, double * values) virtual
Implements tarch::plotter::griddata::blockstructured::PatchWriter::CellDataWriter.
Definition at line 66 of file PeanoTextPatchFileWriter_CellDataWriter.cpp.
References std::abs(), and tarch::la::equals().
plotCell() [2/4]
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::plotCell (int index, double value) virtual
Write data for one cell.
Parameters
index Index of the cell. This index has to equal the index used for the cell within the VTKWriter class interface.
value Value for the cell.
Implements tarch::plotter::griddata::blockstructured::PatchWriter::CellDataWriter.
Definition at line 48 of file PeanoTextPatchFileWriter_CellDataWriter.cpp.
References std::abs(), and tarch::la::equals().
plotCell() [3/4]
template<typename T > void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::plotCell (int index, T * values)
Definition at line 21 of file PeanoTextPatchFileWriter_CellDataWriter.cpph.
References std::abs(), and tarch::la::equals().
plotCell() [4/4]
template<typename T > void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::plotCell (int index, T value)
Definition at line 2 of file PeanoTextPatchFileWriter_CellDataWriter.cpph.
References _entryCounter, _numberOfUnknowns, _out, std::abs(), tarch::la::equals(), and flushIfPatchIsComplete().
setPrecision()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::setPrecision (int precision)
See also
https://www.cplusplus.com/reference/iomanip/setprecision/
Definition at line 41 of file PeanoTextPatchFileWriter_CellDataWriter.cpp.
Field Documentation
_entryCounter
int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::_entryCounter protected
Definition at line 120 of file PeanoTextPatchFileWriter.h.
Referenced by plotCell().
_identifier
const std::string tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::_identifier protected
Definition at line 117 of file PeanoTextPatchFileWriter.h.
_numberOfCellsPerAxis
const int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::_numberOfCellsPerAxis protected
Definition at line 118 of file PeanoTextPatchFileWriter.h.
Referenced by CellDataWriter().
_numberOfUnknowns
const int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::_numberOfUnknowns protected
Definition at line 119 of file PeanoTextPatchFileWriter.h.
Referenced by CellDataWriter(), and plotCell().
_out
std::stringstream tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::_out protected
Definition at line 121 of file PeanoTextPatchFileWriter.h.
Referenced by CellDataWriter(), and plotCell().
_writer
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter& tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::_writer protected
Definition at line 115 of file PeanoTextPatchFileWriter.h.
Referenced by CellDataWriter().
The documentation for this class was generated from the following files:
src/tarch/plotter/griddata/blockstructured/PeanoTextPatchFileWriter.h
src/tarch/plotter/griddata/blockstructured/PeanoTextPatchFileWriter_CellDataWriter.cpp
src/tarch/plotter/griddata/blockstructured/PeanoTextPatchFileWriter_CellDataWriter.cpph