Peano
tl::cartesian_product_view< Vs >::cursor< Const > Class Template Reference
Public Types
using reference
using value_type
using difference_type = std::ptrdiff_t
Public Member Functions
cursor ()=default
constexpr cursor (constify< std::tuple< Vs... > > *bases)
constexpr cursor (as_sentinel_t, constify< std::tuple< Vs... > > *bases)
constexpr cursor (as_sentinel_t, constify< std::tuple< Vs... > > *bases)
constexpr cursor (cursor<!Const > i) &&(std
constexpr decltype(auto) read () const
template<std::size_t N = (sizeof...(Vs) - 1)>
void update (int idx)
void next ()
void prev ()
void advance (difference_type n)
constexpr bool equal (const cursor &rhs) const
constexpr bool equal (const sentinel< Const > &s) const
template<std::size_t N = (sizeof...(Vs) - 1)>
requires (am_distanceable<constify<Vs>...>)
constexpr auto distance_to (cursor const &other) const
Private Types
template<class T >
using constify = std::conditional_t<Const, const T, T>
template<class T >
using intify = std::conditional_t<true, std::int64_t, T>
Private Attributes
std::tuple< std::ranges::iterator_t< constify< Vs > >... > currents_ {}
std::tuple< std::ranges::iterator_t< constify< Vs > >... > begins_ {}
std::tuple< std::ranges::sentinel_t< constify< Vs > >... > ends_ {}
std::tuple< intify< Vs >... > counts_ {}
std::int64_t idx_
Friends
class cursor<!Const >
Detailed Description
template<std::ranges::forward_range... Vs>
template<bool Const>
class tl::cartesian_product_view< Vs >::cursor< Const >
Definition at line 1197 of file cartesian_product.h.
Member Typedef Documentation
constify
template<std::ranges::forward_range... Vs> template<bool Const> template<class T > using tl::cartesian_product_view< Vs >::cursor< Const >::constify = std::conditional_t<Const, const T, T> private
Definition at line 1199 of file cartesian_product.h.
difference_type
template<std::ranges::forward_range... Vs> template<bool Const> using tl::cartesian_product_view< Vs >::cursor< Const >::difference_type = std::ptrdiff_t
Definition at line 1217 of file cartesian_product.h.
intify
template<std::ranges::forward_range... Vs> template<bool Const> template<class T > using tl::cartesian_product_view< Vs >::cursor< Const >::intify = std::conditional_t<true, std::int64_t, T> private
Definition at line 1202 of file cartesian_product.h.
reference
template<std::ranges::forward_range... Vs> template<bool Const> using tl::cartesian_product_view< Vs >::cursor< Const >::reference
Initial value:
            std::tuple<std::ranges::range_reference_t<constify<Vs>>...>
Definition at line 1212 of file cartesian_product.h.
value_type
template<std::ranges::forward_range... Vs> template<bool Const> using tl::cartesian_product_view< Vs >::cursor< Const >::value_type
Initial value:
            std::tuple<std::ranges::range_value_t<constify<Vs>>...>
Definition at line 1214 of file cartesian_product.h.
Constructor & Destructor Documentation
cursor() [1/5]
template<std::ranges::forward_range... Vs> template<bool Const> tl::cartesian_product_view< Vs >::cursor< Const >::cursor () default
cursor() [2/5]
template<std::ranges::forward_range... Vs> template<bool Const> constexpr tl::cartesian_product_view< Vs >::cursor< Const >::cursor (constify< std::tuple< Vs... > > * bases) explicit constexpr
Definition at line 1220 of file cartesian_product.h.
cursor() [3/5]
template<std::ranges::forward_range... Vs> template<bool Const> constexpr tl::cartesian_product_view< Vs >::cursor< Const >::cursor (as_sentinel_t , constify< std::tuple< Vs... > > * bases) explicit constexpr
Definition at line 1229 of file cartesian_product.h.
cursor() [4/5]
template<std::ranges::forward_range... Vs> template<bool Const> constexpr tl::cartesian_product_view< Vs >::cursor< Const >::cursor (as_sentinel_t , constify< std::tuple< Vs... > > * bases) explicit constexpr
Definition at line 1237 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::cursor< Const >::begins_, tl::cartesian_product_view< Vs >::cursor< Const >::currents_, and tl::cartesian_product_view< Vs >::cursor< Const >::ends_.
cursor() [5/5]
template<std::ranges::forward_range... Vs> template<bool Const> constexpr tl::cartesian_product_view< Vs >::cursor< Const >::cursor (cursor<!Const > i) && constexpr
Definition at line 1245 of file cartesian_product.h.
Member Function Documentation
advance()
template<std::ranges::forward_range... Vs> template<bool Const> void tl::cartesian_product_view< Vs >::cursor< Const >::advance (difference_type n)
Definition at line 1279 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::cursor< Const >::idx_, and tl::cartesian_product_view< Vs >::cursor< Const >::update().
Referenced by tl::cartesian_product_view< Vs >::cursor< Const >::next(), tl::cartesian_product_view< std::ranges::iota_view< W, B > >::cursor< Const >::next(), tl::cartesian_product_view< Vs >::cursor< Const >::prev(), tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::cursor< Const >::prev(), tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::cursor< Const >::prev(), and tl::cartesian_product_view< std::ranges::iota_view< W, B > >::cursor< Const >::prev().
distance_to()
template<std::ranges::forward_range... Vs> template<bool Const> template<std::size_t N = (sizeof...(Vs) - 1)> requires (am_distanceable<constify<Vs>...>) constexpr auto tl::cartesian_product_view< Vs >::cursor< Const >::distance_to (cursor< Const > const & other) const constexpr
Definition at line 1297 of file cartesian_product.h.
Referenced by tl::cartesian_product_view< Vs >::cursor< Const >::cursor<!Const >.
equal() [1/2]
template<std::ranges::forward_range... Vs> template<bool Const> constexpr bool tl::cartesian_product_view< Vs >::cursor< Const >::equal (const cursor< Const > & rhs) const constexpr
Definition at line 1284 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::cursor< Const >::currents_.
equal() [2/2]
template<std::ranges::forward_range... Vs> template<bool Const> constexpr bool tl::cartesian_product_view< Vs >::cursor< Const >::equal (const sentinel< Const > & s) const constexpr
Definition at line 1292 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::cursor< Const >::currents_.
next()
template<std::ranges::forward_range... Vs> template<bool Const> void tl::cartesian_product_view< Vs >::cursor< Const >::next ()
Definition at line 1269 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::cursor< Const >::advance().
prev()
template<std::ranges::forward_range... Vs> template<bool Const> void tl::cartesian_product_view< Vs >::cursor< Const >::prev ()
Definition at line 1275 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::cursor< Const >::advance().
read()
template<std::ranges::forward_range... Vs> template<bool Const> constexpr decltype(auto) tl::cartesian_product_view< Vs >::cursor< Const >::read () const constexpr
Definition at line 1251 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::cursor< Const >::currents_, and tl::tuple_transform().
update()
template<std::ranges::forward_range... Vs> template<bool Const> template<std::size_t N = (sizeof...(Vs) - 1)> void tl::cartesian_product_view< Vs >::cursor< Const >::update (int idx)
Definition at line 1256 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::cursor< Const >::begins_, tl::cartesian_product_view< Vs >::cursor< Const >::counts_, tl::cartesian_product_view< Vs >::cursor< Const >::currents_, and tl::cartesian_product_view< Vs >::cursor< Const >::update().
Referenced by tl::cartesian_product_view< Vs >::cursor< Const >::advance(), and tl::cartesian_product_view< Vs >::cursor< Const >::update().
Friends And Related Symbol Documentation
cursor<!Const >
template<std::ranges::forward_range... Vs> template<bool Const> friend class cursor<!Const > friend
Definition at line 1297 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::cursor< Const >::begins_, tl::cartesian_product_view< Vs >::cursor< Const >::currents_, tl::cartesian_product_view< Vs >::cursor< Const >::distance_to(), and tl::cartesian_product_view< Vs >::cursor< Const >::ends_.
Field Documentation
begins_
template<std::ranges::forward_range... Vs> template<bool Const> std::tuple<std::ranges::iterator_t<constify<Vs> >...> tl::cartesian_product_view< Vs >::cursor< Const >::begins_ {} private
Definition at line 1206 of file cartesian_product.h.
Referenced by tl::cartesian_product_view< Vs >::cursor< Const >::cursor(), tl::cartesian_product_view< Vs >::cursor< Const >::cursor<!Const >, and tl::cartesian_product_view< Vs >::cursor< Const >::update().
counts_
template<std::ranges::forward_range... Vs> template<bool Const> std::tuple<intify<Vs>...> tl::cartesian_product_view< Vs >::cursor< Const >::counts_ {} private
Definition at line 1208 of file cartesian_product.h.
Referenced by tl::cartesian_product_view< Vs >::cursor< Const >::update().
currents_
template<std::ranges::forward_range... Vs> template<bool Const> std::tuple<std::ranges::iterator_t<constify<Vs> >...> tl::cartesian_product_view< Vs >::cursor< Const >::currents_ {} private
Definition at line 1205 of file cartesian_product.h.
Referenced by tl::cartesian_product_view< Vs >::cursor< Const >::cursor(), tl::cartesian_product_view< Vs >::cursor< Const >::cursor<!Const >, tl::cartesian_product_view< Vs >::cursor< Const >::equal(), tl::cartesian_product_view< Vs >::cursor< Const >::equal(), tl::cartesian_product_view< Vs >::cursor< Const >::read(), and tl::cartesian_product_view< Vs >::cursor< Const >::update().
ends_
template<std::ranges::forward_range... Vs> template<bool Const> std::tuple<std::ranges::sentinel_t<constify<Vs> >...> tl::cartesian_product_view< Vs >::cursor< Const >::ends_ {} private
Definition at line 1207 of file cartesian_product.h.
Referenced by tl::cartesian_product_view< Vs >::cursor< Const >::cursor(), and tl::cartesian_product_view< Vs >::cursor< Const >::cursor<!Const >.
idx_
template<std::ranges::forward_range... Vs> template<bool Const> std::int64_t tl::cartesian_product_view< Vs >::cursor< Const >::idx_ private
Definition at line 1209 of file cartesian_product.h.
Referenced by tl::cartesian_product_view< Vs >::cursor< Const >::advance().
The documentation for this class was generated from the following file:
src/tarch/accelerator/cpp/cartesian_product.h