Peano
peano4::grid::GridVertex Struct Reference
#include <GridVertex.h>
Public Types
enum class State : int {
HangingVertex = 0 , New = 1 , Unrefined = 2 , Refined = 3 ,
RefinementTriggered = 4 , Refining = 5 , EraseTriggered = 6 , Erasing = 7 ,
Delete = 8
}
enum ObjectConstruction { NoData }
Public Member Functions
GridVertex ()=default
GridVertex (const State __state, const tarch::la::Vector< TwoPowerD, int > &__adjacentRanks, const tarch::la::Vector< TwoPowerD, int > &__backupOfAdjacentRanks, const bool __hasBeenAntecessorOfRefinedVertexInPreviousTreeSweep, const bool __isAntecessorOfRefinedVertexInCurrentTreeSweep, const bool __hasBeenParentOfSubtreeVertexInPreviousTreeSweep, const bool __isParentOfSubtreeVertexInCurrentTreeSweep, const int __numberOfAdjacentRefinedLocalCells, const tarch::la::Vector< Dimensions, double > &__x, const int __level)
GridVertex (const GridVertex &copy)
GridVertex & operator= (const GridVertex &other)
peano4::grid::GridVertex::State getState () const
void setState (State value)
tarch::la::Vector< TwoPowerD, int > getAdjacentRanks () const
void setAdjacentRanks (const tarch::la::Vector< TwoPowerD, int > &value)
int getAdjacentRanks (int index) const
void setAdjacentRanks (int index, int value)
tarch::la::Vector< TwoPowerD, int > getBackupOfAdjacentRanks () const
void setBackupOfAdjacentRanks (const tarch::la::Vector< TwoPowerD, int > &value)
int getBackupOfAdjacentRanks (int index) const
void setBackupOfAdjacentRanks (int index, int value)
bool getHasBeenAntecessorOfRefinedVertexInPreviousTreeSweep () const
void setHasBeenAntecessorOfRefinedVertexInPreviousTreeSweep (bool value)
bool getIsAntecessorOfRefinedVertexInCurrentTreeSweep () const
void setIsAntecessorOfRefinedVertexInCurrentTreeSweep (bool value)
bool getHasBeenParentOfSubtreeVertexInPreviousTreeSweep () const
void setHasBeenParentOfSubtreeVertexInPreviousTreeSweep (bool value)
bool getIsParentOfSubtreeVertexInCurrentTreeSweep () const
void setIsParentOfSubtreeVertexInCurrentTreeSweep (bool value)
int getNumberOfAdjacentRefinedLocalCells () const
void setNumberOfAdjacentRefinedLocalCells (int value)
int getLevel () const
void setLevel (int value)
int getSenderRank () const
GridVertex (ObjectConstruction)
std::string toString () const
Static Public Member Functions
static MPI_Datatype getForkDatatype ()
Hands out MPI datatype if we work without the LLVM MPI extension.
static MPI_Datatype getJoinDatatype ()
static MPI_Datatype getBoundaryExchangeDatatype ()
static MPI_Datatype getMultiscaleDataExchangeDatatype ()
static MPI_Datatype getGlobalCommunciationDatatype ()
static void freeForkDatatype ()
static void freeJoinDatatype ()
static void freeBoundaryExchangeDatatype ()
static void freeMultiscaleDataExchangeDatatype ()
static void freeGlobalCommunciationDatatype ()
static void initDatatype ()
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
static void shutdownDatatype ()
Free the underlying MPI datatype.
static void send (const peano4::grid::GridVertex &buffer, int destination, int tag, MPI_Comm communicator)
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
static void receive (peano4::grid::GridVertex &buffer, int source, int tag, MPI_Comm communicator)
static void send (const peano4::grid::GridVertex &buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
static void receive (peano4::grid::GridVertex &buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
static void sendAndPollDanglingMessages (const peano4::grid::GridVertex &message, int destination, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
static void receiveAndPollDanglingMessages (peano4::grid::GridVertex &message, int source, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
Private Attributes
State _state
tarch::la::Vector< TwoPowerD, int > _adjacentRanks
tarch::la::Vector< TwoPowerD, int > _backupOfAdjacentRanks
bool _hasBeenAntecessorOfRefinedVertexInPreviousTreeSweep
bool _isAntecessorOfRefinedVertexInCurrentTreeSweep
bool _hasBeenParentOfSubtreeVertexInPreviousTreeSweep
bool _isParentOfSubtreeVertexInCurrentTreeSweep
int _numberOfAdjacentRefinedLocalCells
int _level
int _senderDestinationRank
Static Private Attributes
static MPI_Datatype Datatype = MPI_DATATYPE_NULL
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
Detailed Description
Definition at line 25 of file GridVertex.h.
Member Enumeration Documentation
ObjectConstruction
enum peano4::grid::GridVertex::ObjectConstruction
Enumerator
NoData
Definition at line 181 of file GridVertex.h.
State
enum class peano4::grid::GridVertex::State : int strong
Enumerator
HangingVertex
New
Unrefined
Refined
RefinementTriggered
Refining
EraseTriggered
Erasing
Delete
Definition at line 27 of file GridVertex.h.
Constructor & Destructor Documentation
GridVertex() [1/4]
peano4::grid::GridVertex::GridVertex () default
GridVertex() [2/4]
peano4::grid::GridVertex::GridVertex (const State __state, const tarch::la::Vector< TwoPowerD, int > & __adjacentRanks, const tarch::la::Vector< TwoPowerD, int > & __backupOfAdjacentRanks, const bool __hasBeenAntecessorOfRefinedVertexInPreviousTreeSweep, const bool __isAntecessorOfRefinedVertexInCurrentTreeSweep, const bool __hasBeenParentOfSubtreeVertexInPreviousTreeSweep, const bool __isParentOfSubtreeVertexInCurrentTreeSweep, const int __numberOfAdjacentRefinedLocalCells, const tarch::la::Vector< Dimensions, double > & __x, const int __level)
Definition at line 8 of file GridVertex.cpp.
References setAdjacentRanks(), setBackupOfAdjacentRanks(), setHasBeenAntecessorOfRefinedVertexInPreviousTreeSweep(), setHasBeenParentOfSubtreeVertexInPreviousTreeSweep(), setIsAntecessorOfRefinedVertexInCurrentTreeSweep(), setIsParentOfSubtreeVertexInCurrentTreeSweep(), setLevel(), setNumberOfAdjacentRefinedLocalCells(), setState(), and setX().
GridVertex() [3/4]
peano4::grid::GridVertex::GridVertex (const GridVertex & copy)
Definition at line 34 of file GridVertex.cpp.
References setLevel(), and setX().
GridVertex() [4/4]
peano4::grid::GridVertex::GridVertex (ObjectConstruction)
Definition at line 183 of file GridVertex.h.
Member Function Documentation
freeBoundaryExchangeDatatype()
void peano4::grid::GridVertex::freeBoundaryExchangeDatatype () static
Definition at line 137 of file GridVertex.cpp.
freeForkDatatype()
void peano4::grid::GridVertex::freeForkDatatype () static
Definition at line 116 of file GridVertex.cpp.
freeGlobalCommunciationDatatype()
void peano4::grid::GridVertex::freeGlobalCommunciationDatatype () static
Definition at line 123 of file GridVertex.cpp.
freeJoinDatatype()
void peano4::grid::GridVertex::freeJoinDatatype () static
Definition at line 130 of file GridVertex.cpp.
freeMultiscaleDataExchangeDatatype()
void peano4::grid::GridVertex::freeMultiscaleDataExchangeDatatype () static
Definition at line 144 of file GridVertex.cpp.
getAdjacentRanks() [1/2]
tarch::la::Vector< TwoPowerD, int > peano4::grid::GridVertex::getAdjacentRanks () const
Definition at line 58 of file GridVertex.h.
References _adjacentRanks.
Referenced by peano4::grid::GridTraversalEventGenerator::areFacesLocal(), peano4::grid::GridTraversalEventGenerator::getAdjacentRanksOfFace(), peano4::grid::Spacetree::getNeighbourTrees(), peano4::grid::GridTraversalEventGenerator::isVertexAdjacentToLocalSpacetree(), peano4::grid::Spacetree::mergeGridVertexAdjacencyListsAtHorizontalDomainBoundary(), operator=(), peano4::grid::Spacetree::receiveAndMergeGridVertexAtHorizontalBoundary(), peano4::grid::Spacetree::receiveAndMergeGridVertexAtVerticalBoundary(), and peano4::grid::Spacetree::sendGridVertex().
getAdjacentRanks() [2/2]
int peano4::grid::GridVertex::getAdjacentRanks (int index) const
Definition at line 60 of file GridVertex.h.
References _adjacentRanks.
getBackupOfAdjacentRanks() [1/2]
tarch::la::Vector< TwoPowerD, int > peano4::grid::GridVertex::getBackupOfAdjacentRanks () const
Definition at line 63 of file GridVertex.h.
References _backupOfAdjacentRanks.
Referenced by peano4::grid::GridTraversalEventGenerator::getAdjacentRanksOfFace(), peano4::grid::Spacetree::getNeighbourTrees(), and operator=().
getBackupOfAdjacentRanks() [2/2]
int peano4::grid::GridVertex::getBackupOfAdjacentRanks (int index) const
Definition at line 67 of file GridVertex.h.
References _backupOfAdjacentRanks.
getBoundaryExchangeDatatype()
MPI_Datatype peano4::grid::GridVertex::getBoundaryExchangeDatatype () static
Definition at line 113 of file GridVertex.cpp.
getForkDatatype()
MPI_Datatype peano4::grid::GridVertex::getForkDatatype () static
Hands out MPI datatype if we work without the LLVM MPI extension.
If we work with this additional feature, this is the routine where the lazy initialisation is done and the datatype is also cached.
Definition at line 110 of file GridVertex.cpp.
getGlobalCommunciationDatatype()
MPI_Datatype peano4::grid::GridVertex::getGlobalCommunciationDatatype () static
Definition at line 111 of file GridVertex.cpp.
getHasBeenAntecessorOfRefinedVertexInPreviousTreeSweep()
bool peano4::grid::GridVertex::getHasBeenAntecessorOfRefinedVertexInPreviousTreeSweep () const
Definition at line 70 of file GridVertex.h.
References _hasBeenAntecessorOfRefinedVertexInPreviousTreeSweep.
Referenced by operator=().
getHasBeenParentOfSubtreeVertexInPreviousTreeSweep()
bool peano4::grid::GridVertex::getHasBeenParentOfSubtreeVertexInPreviousTreeSweep () const
Definition at line 84 of file GridVertex.h.
References _hasBeenParentOfSubtreeVertexInPreviousTreeSweep.
Referenced by operator=().
getIsAntecessorOfRefinedVertexInCurrentTreeSweep()
bool peano4::grid::GridVertex::getIsAntecessorOfRefinedVertexInCurrentTreeSweep () const
Definition at line 77 of file GridVertex.h.
References _isAntecessorOfRefinedVertexInCurrentTreeSweep.
Referenced by operator=(), and peano4::grid::Spacetree::updateVertexBeforeStore().
getIsParentOfSubtreeVertexInCurrentTreeSweep()
bool peano4::grid::GridVertex::getIsParentOfSubtreeVertexInCurrentTreeSweep () const
Definition at line 91 of file GridVertex.h.
References _isParentOfSubtreeVertexInCurrentTreeSweep.
Referenced by operator=(), and peano4::grid::Spacetree::updateVertexBeforeStore().
getJoinDatatype()
MPI_Datatype peano4::grid::GridVertex::getJoinDatatype () static
Definition at line 112 of file GridVertex.cpp.
getLevel()
int peano4::grid::GridVertex::getLevel () const
Definition at line 108 of file GridVertex.h.
References _level.
Referenced by operator=().
getMultiscaleDataExchangeDatatype()
MPI_Datatype peano4::grid::GridVertex::getMultiscaleDataExchangeDatatype () static
Definition at line 114 of file GridVertex.cpp.
getNumberOfAdjacentRefinedLocalCells()
int peano4::grid::GridVertex::getNumberOfAdjacentRefinedLocalCells () const
Definition at line 98 of file GridVertex.h.
References _numberOfAdjacentRefinedLocalCells.
Referenced by operator=(), and peano4::grid::Spacetree::updateVertexBeforeStore().
getSenderRank()
int peano4::grid::GridVertex::getSenderRank () const
Returns
The rank of the sender of an object. It only make ssense to call this routine after you've invoked receive with MPI_ANY_SOURCE.
Definition at line 151 of file GridVertex.cpp.
getState()
peano4::grid::GridVertex::State peano4::grid::GridVertex::getState () const
Definition at line 55 of file GridVertex.h.
References _state.
Referenced by peano4::grid::GridTraversalEventGenerator::areFacesLocal(), peano4::grid::GridTraversalEventGenerator::getAdjacentRanksOfFace(), peano4::grid::hasVertexBeenRefined(), peano4::grid::Spacetree::isVertexAdjacentToLocalSpacetree(), operator=(), peano4::grid::Spacetree::shouldEraseAdjacencyInformation(), peano4::grid::Spacetree::updateVertexBeforeStore(), and peano4::grid::willVertexBeRefined().
initDatatype()
void peano4::grid::GridVertex::initDatatype () static
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
Definition at line 153 of file GridVertex.cpp.
References _state, and TwoPowerD.
Referenced by peano4::parallel::Node::initMPIDatatypes().
operator=()
peano4::grid::GridVertex & peano4::grid::GridVertex::operator= (const GridVertex & other)
Definition at line 49 of file GridVertex.cpp.
References getAdjacentRanks(), getBackupOfAdjacentRanks(), getHasBeenAntecessorOfRefinedVertexInPreviousTreeSweep(), getHasBeenParentOfSubtreeVertexInPreviousTreeSweep(), getIsAntecessorOfRefinedVertexInCurrentTreeSweep(), getIsParentOfSubtreeVertexInCurrentTreeSweep(), getLevel(), getNumberOfAdjacentRefinedLocalCells(), getState(), setLevel(), and setX().
receive() [1/2]
void peano4::grid::GridVertex::receive (peano4::grid::GridVertex & buffer, int source, int tag, MPI_Comm communicator) static
Definition at line 286 of file GridVertex.cpp.
References _senderDestinationRank.
Referenced by receiveAndPollDanglingMessages().
receive() [2/2]
void peano4::grid::GridVertex::receive (peano4::grid::GridVertex & buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Definition at line 311 of file GridVertex.cpp.
References _senderDestinationRank.
receiveAndPollDanglingMessages()
void peano4::grid::GridVertex::receiveAndPollDanglingMessages (peano4::grid::GridVertex & message, int source, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 359 of file GridVertex.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), receive(), tarch::services::ServiceRepository::receiveDanglingMessages(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
send() [1/2]
void peano4::grid::GridVertex::send (const peano4::grid::GridVertex & buffer, int destination, int tag, MPI_Comm communicator) static
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
However, this did not work with newer C++11 versions, as a member function using this as pointer usually doesn't see the vtable while the init sees the object from outside, i.e. including a vtable. So this routine now is basically an alias for a blocking MPI_Send.
Definition at line 281 of file GridVertex.cpp.
Referenced by sendAndPollDanglingMessages().
send() [2/2]
void peano4::grid::GridVertex::send (const peano4::grid::GridVertex & buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
In systems with heavy MPI usage, this can help to avoid deadlocks.
Definition at line 292 of file GridVertex.cpp.
sendAndPollDanglingMessages()
void peano4::grid::GridVertex::sendAndPollDanglingMessages (const peano4::grid::GridVertex & message, int destination, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 334 of file GridVertex.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), tarch::services::ServiceRepository::receiveDanglingMessages(), send(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
setAdjacentRanks() [1/2]
void peano4::grid::GridVertex::setAdjacentRanks (const tarch::la::Vector< TwoPowerD, int > & value)
Definition at line 59 of file GridVertex.h.
References _adjacentRanks.
Referenced by peano4::grid::createVertex(), GridVertex(), peano4::grid::Spacetree::mergeGridVertexAdjacencyListsAtHorizontalDomainBoundary(), peano4::grid::Spacetree::receiveAndMergeGridVertexAtVerticalBoundary(), peano4::grid::Spacetree::sendGridVertex(), peano4::grid::tests::GridTraversalEventGeneratorTest::testAreFacesLocal1(), peano4::grid::tests::GridTraversalEventGeneratorTest::testAreFacesLocal2(), peano4::grid::tests::GridTraversalEventGeneratorTest::testCreateGenericCellTraversalEvent1(), peano4::grid::tests::GridTraversalEventGeneratorTest::testCreateLeaveCellTraversalEvent1(), peano4::grid::tests::SpacetreeTest::testGetAdjacentDomainIds(), peano4::grid::Spacetree::traverse(), and peano4::grid::Spacetree::updateVertexBeforeStore().
setAdjacentRanks() [2/2]
void peano4::grid::GridVertex::setAdjacentRanks (int index, int value)
Definition at line 61 of file GridVertex.h.
References _adjacentRanks.
setBackupOfAdjacentRanks() [1/2]
void peano4::grid::GridVertex::setBackupOfAdjacentRanks (const tarch::la::Vector< TwoPowerD, int > & value)
Definition at line 64 of file GridVertex.h.
References _backupOfAdjacentRanks.
Referenced by peano4::grid::createVertex(), GridVertex(), peano4::grid::Spacetree::receiveAndMergeGridVertexAtHorizontalBoundary(), peano4::grid::tests::GridTraversalEventGeneratorTest::testAreFacesLocal1(), peano4::grid::tests::GridTraversalEventGeneratorTest::testAreFacesLocal2(), peano4::grid::tests::GridTraversalEventGeneratorTest::testCreateGenericCellTraversalEvent1(), and peano4::grid::tests::SpacetreeTest::testGetAdjacentDomainIds().
setBackupOfAdjacentRanks() [2/2]
void peano4::grid::GridVertex::setBackupOfAdjacentRanks (int index, int value)
Definition at line 68 of file GridVertex.h.
References _backupOfAdjacentRanks.
setHasBeenAntecessorOfRefinedVertexInPreviousTreeSweep()
void peano4::grid::GridVertex::setHasBeenAntecessorOfRefinedVertexInPreviousTreeSweep (bool value)
Definition at line 73 of file GridVertex.h.
References _hasBeenAntecessorOfRefinedVertexInPreviousTreeSweep.
Referenced by peano4::grid::createVertex(), GridVertex(), and peano4::grid::tests::GridTraversalEventGeneratorTest::testCreateLeaveCellTraversalEvent1().
setHasBeenParentOfSubtreeVertexInPreviousTreeSweep()
void peano4::grid::GridVertex::setHasBeenParentOfSubtreeVertexInPreviousTreeSweep (bool value)
Definition at line 87 of file GridVertex.h.
References _hasBeenParentOfSubtreeVertexInPreviousTreeSweep.
Referenced by peano4::grid::createVertex(), GridVertex(), and peano4::grid::Spacetree::traverse().
setIsAntecessorOfRefinedVertexInCurrentTreeSweep()
void peano4::grid::GridVertex::setIsAntecessorOfRefinedVertexInCurrentTreeSweep (bool value)
Definition at line 80 of file GridVertex.h.
References _isAntecessorOfRefinedVertexInCurrentTreeSweep.
Referenced by peano4::grid::createVertex(), GridVertex(), and peano4::grid::tests::GridTraversalEventGeneratorTest::testCreateLeaveCellTraversalEvent1().
setIsParentOfSubtreeVertexInCurrentTreeSweep()
void peano4::grid::GridVertex::setIsParentOfSubtreeVertexInCurrentTreeSweep (bool value)
Definition at line 94 of file GridVertex.h.
References _isParentOfSubtreeVertexInCurrentTreeSweep.
Referenced by peano4::grid::createVertex(), and GridVertex().
setLevel()
void peano4::grid::GridVertex::setLevel (int value)
Definition at line 109 of file GridVertex.h.
References _level.
Referenced by peano4::grid::createVertex(), GridVertex(), and peano4::grid::tests::GridTraversalEventGeneratorTest::testCreateLeaveCellTraversalEvent1().
setNumberOfAdjacentRefinedLocalCells()
void peano4::grid::GridVertex::setNumberOfAdjacentRefinedLocalCells (int value)
Definition at line 99 of file GridVertex.h.
References _numberOfAdjacentRefinedLocalCells.
Referenced by peano4::grid::createVertex(), and GridVertex().
setState()
void peano4::grid::GridVertex::setState (State value)
Definition at line 56 of file GridVertex.h.
References _state.
Referenced by peano4::grid::createVertex(), GridVertex(), peano4::grid::tests::GridTraversalEventGeneratorTest::testAreFacesLocal1(), peano4::grid::tests::GridTraversalEventGeneratorTest::testAreFacesLocal2(), peano4::grid::tests::GridTraversalEventGeneratorTest::testCreateGenericCellTraversalEvent1(), peano4::grid::tests::GridTraversalEventGeneratorTest::testCreateLeaveCellTraversalEvent1(), peano4::grid::tests::SpacetreeTest::testGetAdjacentDomainIds(), peano4::grid::tests::GridTraversalEventGeneratorTest::testGetFaceType(), and peano4::grid::Spacetree::updateVertexBeforeStore().
shutdownDatatype()
void peano4::grid::GridVertex::shutdownDatatype () static
Free the underlying MPI datatype.
Definition at line 268 of file GridVertex.cpp.
Referenced by peano4::parallel::Node::shutdownMPIDatatypes().
toString()
std::string peano4::grid::GridVertex::toString () const
Definition at line 71 of file GridVertex.cpp.
References _state.
Referenced by peano4::grid::Spacetree::mergeGridVertexAdjacencyListsAtHorizontalDomainBoundary(), peano4::grid::Spacetree::receiveAndMergeGridVertexAtHorizontalBoundary(), peano4::grid::Spacetree::receiveAndMergeGridVertexAtVerticalBoundary(), peano4::grid::Spacetree::sendGridVertex(), peano4::grid::Spacetree::shouldEraseAdjacencyInformation(), and peano4::grid::Spacetree::updateVertexBeforeStore().
Field Documentation
_adjacentRanks
tarch::la::Vector<TwoPowerD, int> peano4::grid::GridVertex::_adjacentRanks private
Definition at line 205 of file GridVertex.h.
Referenced by getAdjacentRanks(), getAdjacentRanks(), setAdjacentRanks(), and setAdjacentRanks().
_backupOfAdjacentRanks
tarch::la::Vector<TwoPowerD, int> peano4::grid::GridVertex::_backupOfAdjacentRanks private
Definition at line 206 of file GridVertex.h.
Referenced by getBackupOfAdjacentRanks(), getBackupOfAdjacentRanks(), setBackupOfAdjacentRanks(), and setBackupOfAdjacentRanks().
_hasBeenAntecessorOfRefinedVertexInPreviousTreeSweep
bool peano4::grid::GridVertex::_hasBeenAntecessorOfRefinedVertexInPreviousTreeSweep private
Definition at line 207 of file GridVertex.h.
Referenced by getHasBeenAntecessorOfRefinedVertexInPreviousTreeSweep(), and setHasBeenAntecessorOfRefinedVertexInPreviousTreeSweep().
_hasBeenParentOfSubtreeVertexInPreviousTreeSweep
bool peano4::grid::GridVertex::_hasBeenParentOfSubtreeVertexInPreviousTreeSweep private
Definition at line 209 of file GridVertex.h.
Referenced by getHasBeenParentOfSubtreeVertexInPreviousTreeSweep(), and setHasBeenParentOfSubtreeVertexInPreviousTreeSweep().
_isAntecessorOfRefinedVertexInCurrentTreeSweep
bool peano4::grid::GridVertex::_isAntecessorOfRefinedVertexInCurrentTreeSweep private
Definition at line 208 of file GridVertex.h.
Referenced by getIsAntecessorOfRefinedVertexInCurrentTreeSweep(), and setIsAntecessorOfRefinedVertexInCurrentTreeSweep().
_isParentOfSubtreeVertexInCurrentTreeSweep
bool peano4::grid::GridVertex::_isParentOfSubtreeVertexInCurrentTreeSweep private
Definition at line 210 of file GridVertex.h.
Referenced by getIsParentOfSubtreeVertexInCurrentTreeSweep(), and setIsParentOfSubtreeVertexInCurrentTreeSweep().
_level
int peano4::grid::GridVertex::_level private
Definition at line 217 of file GridVertex.h.
Referenced by getLevel(), and setLevel().
_numberOfAdjacentRefinedLocalCells
int peano4::grid::GridVertex::_numberOfAdjacentRefinedLocalCells private
Definition at line 211 of file GridVertex.h.
Referenced by getNumberOfAdjacentRefinedLocalCells(), and setNumberOfAdjacentRefinedLocalCells().
_senderDestinationRank
int peano4::grid::GridVertex::_senderDestinationRank private
Definition at line 221 of file GridVertex.h.
Referenced by receive(), and receive().
_state
State peano4::grid::GridVertex::_state private
Definition at line 204 of file GridVertex.h.
Referenced by getState(), and setState().
Datatype
MPI_Datatype peano4::grid::GridVertex::Datatype = MPI_DATATYPE_NULL static private
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
However, Peano calls init explicitly in most cases. Without the LLVM extension which caches the MPI datatype once constructed, this field stores the type.
Definition at line 230 of file GridVertex.h.
The documentation for this struct was generated from the following files:
src/peano4/grid/GridVertex.h
src/peano4/grid/GridVertex.cpp