Peano
ThreadPool Class Reference
#include <thread_pool.h>
Data Structures
struct PooledThread
Public Member Functions
ThreadPool (const ThreadPool &copy)=delete
ThreadPool (ThreadPool &&move)=default
ThreadPool & operator= (ThreadPool &&move)=default
ThreadPool (u32 poolSize=0)
void dispatch (const std::function< void()> &work, u32 numThreads=0)
void wait ()
void shutdown ()
u32 size () const
~ThreadPool ()
Private Member Functions
void setThreadAffinity (auto nativeHandle, u32 coreId)
Static Private Member Functions
static std::vector< u32 > getThreadConfigBindings ()
static std::vector< u32 > getThreadBindingsFromSize (u32 threadingLevel=1)
Private Attributes
std::unique_ptr< PooledThread[]> threadPool
u32 poolSize = 0
u32 freeThreadIdx = 0
Detailed Description
Definition at line 11 of file thread_pool.h.
Constructor & Destructor Documentation
ThreadPool() [1/3]
ThreadPool::ThreadPool (const ThreadPool & copy) delete
ThreadPool() [2/3]
ThreadPool::ThreadPool (ThreadPool && move) default
ThreadPool() [3/3]
ThreadPool::ThreadPool (u32 poolSize = 0) explicit
Definition at line 135 of file thread_pool.h.
References getThreadBindingsFromSize(), getThreadConfigBindings(), poolSize, setThreadAffinity(), and ThreadPool::PooledThread::threadLoop().
~ThreadPool()
ThreadPool::~ThreadPool ()
Definition at line 217 of file thread_pool.h.
References shutdown().
Member Function Documentation
dispatch()
void ThreadPool::dispatch (const std::function< void()> & work, u32 numThreads = 0)
Definition at line 162 of file thread_pool.h.
References assert, and poolSize.
Referenced by ThreadPoolTaskBackend::runParallelGeneratorParallel(), and ThreadPoolTaskBackend::runSerialGeneratorParallel().
getThreadBindingsFromSize()
static std::vector< u32 > ThreadPool::getThreadBindingsFromSize (u32 threadingLevel = 1) static private
Definition at line 106 of file thread_pool.h.
Referenced by ThreadPool().
getThreadConfigBindings()
static std::vector< u32 > ThreadPool::getThreadConfigBindings () static private
Definition at line 75 of file thread_pool.h.
References assert.
Referenced by ThreadPool().
operator=()
ThreadPool & ThreadPool::operator= (ThreadPool && move) default
setThreadAffinity()
void ThreadPool::setThreadAffinity (auto nativeHandle, u32 coreId) private
Definition at line 67 of file thread_pool.h.
References assert.
Referenced by ThreadPool().
shutdown()
void ThreadPool::shutdown ()
Definition at line 190 of file thread_pool.h.
References poolSize.
Referenced by ~ThreadPool().
size()
u32 ThreadPool::size () const
Definition at line 213 of file thread_pool.h.
References poolSize.
Referenced by peano4.visualisation.input.Patch.Patch::__repr__(), and ThreadPoolTaskBackend::MAX_THREADS().
wait()
void ThreadPool::wait ()
Definition at line 173 of file thread_pool.h.
References freeThreadIdx.
Referenced by ThreadPoolTaskBackend::runParallelGeneratorParallel(), and ThreadPoolTaskBackend::runSerialGeneratorParallel().
Field Documentation
freeThreadIdx
u32 ThreadPool::freeThreadIdx = 0 private
Definition at line 65 of file thread_pool.h.
Referenced by wait().
poolSize
u32 ThreadPool::poolSize = 0 private
Definition at line 64 of file thread_pool.h.
Referenced by dispatch(), shutdown(), size(), and ThreadPool().
threadPool
std::unique_ptr<PooledThread[]> ThreadPool::threadPool private
Definition at line 63 of file thread_pool.h.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/lang/thread_pool.h