Peano
runner_do_ghost.h File Reference
Functions
void runner_do_ghost (Tree *leaf, const hydro_props *hydro_properties, HYDRO_STATS_T *hydro_stats)
void do_density (Tree *leaf)
void do_density (Tree *leaf, int *pids, int pidCount)
Function Documentation
do_density() [1/2]
void do_density (Tree * leaf)
Definition at line 5 of file runner_do_ghost.h.
References part::_x, a, dx, Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::getRegionParent(), H, part::h, hi, hj, Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::items, pi, pj, and LinkedGrid< _Geo, SPLIT_FACTOR, Derived >::range.
Referenced by runner_do_ghost().
do_density() [2/2]
void do_density (Tree * leaf, int * pids, int pidCount)
Definition at line 50 of file runner_do_ghost.h.
References part::_x, a, dx, Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::getRegionParent(), H, part::h, hi, hj, Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::items, pi, pj, and LinkedGrid< _Geo, SPLIT_FACTOR, Derived >::range.
runner_do_ghost()
void runner_do_ghost (Tree * leaf, const hydro_props * hydro_properties, HYDRO_STATS_T * hydro_stats)
Definition at line 95 of file runner_do_ghost.h.
References assert, cosmo, COSMO, do_density(), hydro_props::eta_neighbours, part::h, hydro_props::h_max, HYDRO_STATS_T::h_max, HYDRO_STATS_T::h_max_active, hydro_props::h_min, hydro_props::h_tolerance, HYDRO_PROPS, Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::items, kernel_root, MAX, hydro_props::max_smoothing_iterations, MIN, pressure_floor, hydro_props::use_mass_weighted_num_ngb, and xp.