Peano
DynamicMatrix.h File Reference
#include <string>
#include "ScalarOperations.h"
#include "tarch/Assertions.h"
#include "DynamicMatrix.cpph"
Data Structures
class tarch::la::DynamicMatrix
My standard matrix is a matrix where the size is fixed at compile time.
Namespaces
namespace tarch
tarch denotes the Technical Architectures.
namespace tarch::la
My collection of tiny vector operations.
Functions
tarch::la::DynamicMatrix kroneckerProduct (const tarch::la::DynamicMatrix &lhs, const tarch::la::DynamicMatrix &rhs)
Wrapper around static routine, so I don't have to use full-qualified name.
tarch::la::DynamicMatrix operator* (const tarch::la::DynamicMatrix &A, const tarch::la::DynamicMatrix &B)
Function Documentation
kroneckerProduct()
tarch::la::DynamicMatrix kroneckerProduct (const tarch::la::DynamicMatrix & lhs, const tarch::la::DynamicMatrix & rhs)
Wrapper around static routine, so I don't have to use full-qualified name.
Definition at line 13 of file DynamicMatrix.cpp.
operator*()
tarch::la::DynamicMatrix operator* (const tarch::la::DynamicMatrix & A, const tarch::la::DynamicMatrix & B)
Definition at line 569 of file DynamicMatrix.cpp.
References assertionEquals, tarch::la::col(), tarch::la::max(), and tarch::la::row().