Peano
VtkGridAsciiWriter< FileWriter, fp > Class Template Reference
#include <grid.h>
Public Member Functions
VtkGridAsciiWriter (FileWriter *writer)
void add (fp xmin, fp ymin, fp zmin, fp xmax, fp ymax, fp zmax)
void finish ()
Private Member Functions
void addPoint (fp x, fp y, fp z)
void addCell (unsigned long idx)
void addCells ()
void addCellTypes ()
Additional Inherited Members
Protected Member Functions inherited from VtkGridWriterBase< FileWriter >
constexpr int particleCountPosition () const
template<typename T >
T byteswapped (T val)
void updatePointsCount ()
VtkGridWriterBase (FileWriter *writer)
VtkGridWriterBase ()=default
Protected Attributes inherited from VtkGridWriterBase< FileWriter >
FileWriter * writer = nullptr
unsigned long cellCount = 0
Detailed Description
template<typename FileWriter, typename fp = float>
requires IoWriter<FileWriter> and std::is_floating_point_v<fp>
class VtkGridAsciiWriter< FileWriter, fp >
Definition at line 49 of file grid.h.
Constructor & Destructor Documentation
VtkGridAsciiWriter()
template<typename FileWriter , typename fp = float> VtkGridAsciiWriter< FileWriter, fp >::VtkGridAsciiWriter (FileWriter * writer) explicit
Definition at line 101 of file grid.h.
References assert.
Member Function Documentation
add()
template<typename FileWriter , typename fp = float> void VtkGridAsciiWriter< FileWriter, fp >::add (fp xmin, fp ymin, fp zmin, fp xmax, fp ymax, fp zmax)
Definition at line 115 of file grid.h.
References VtkGridAsciiWriter< FileWriter, fp >::addPoint(), and VtkGridWriterBase< FileWriter >::cellCount.
addCell()
template<typename FileWriter , typename fp = float> void VtkGridAsciiWriter< FileWriter, fp >::addCell (unsigned long idx) private
Definition at line 56 of file grid.h.
References assert, and VtkGridWriterBase< FileWriter >::writer.
Referenced by VtkGridAsciiWriter< FileWriter, fp >::addCells().
addCells()
template<typename FileWriter , typename fp = float> void VtkGridAsciiWriter< FileWriter, fp >::addCells () private
Definition at line 73 of file grid.h.
References VtkGridAsciiWriter< FileWriter, fp >::addCell(), assert, VtkGridWriterBase< FileWriter >::cellCount, and VtkGridWriterBase< FileWriter >::writer.
Referenced by VtkGridAsciiWriter< FileWriter, fp >::finish().
addCellTypes()
template<typename FileWriter , typename fp = float> void VtkGridAsciiWriter< FileWriter, fp >::addCellTypes () private
Definition at line 85 of file grid.h.
References assert, VtkGridWriterBase< FileWriter >::cellCount, and VtkGridWriterBase< FileWriter >::writer.
Referenced by VtkGridAsciiWriter< FileWriter, fp >::finish().
addPoint()
template<typename FileWriter , typename fp = float> void VtkGridAsciiWriter< FileWriter, fp >::addPoint (fp x, fp y, fp z) private
Definition at line 50 of file grid.h.
References VtkGridWriterBase< FileWriter >::writer.
Referenced by VtkGridAsciiWriter< FileWriter, fp >::add().
finish()
template<typename FileWriter , typename fp = float> void VtkGridAsciiWriter< FileWriter, fp >::finish ()
Definition at line 131 of file grid.h.
References VtkGridAsciiWriter< FileWriter, fp >::addCells(), VtkGridAsciiWriter< FileWriter, fp >::addCellTypes(), VtkGridWriterBase< FileWriter >::updatePointsCount(), and VtkGridWriterBase< FileWriter >::writer.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/vtk/writer/grid.h