Peano
DomainDecomposition< Geo > Class Template Reference
#include <decomposition.h>
Data Structures
class Grid
Public Member Functions
DomainDecomposition (Geo::Region range, u64 localRankId, u32 rankCount, Geo::P haloThickness)
Geo::Region getLocalArea ()
Geo::Region getLocalHaloArea ()
std::vector< u64 > getNeighbourRankIds ()
Geo::Region getLocalHaloForNeighbour (u64 neighbourRankId)
Geo::Region getRemoteHaloForNeighbour (u64 neighbourRankId)
Private Types
using LeafsIter = LeafsIterator<Grid>
using InsideRegionIter = InsideRegionLeafsIterator<Grid>
using Morton = mortonnd::MortonNDBmi<Geo::D::N, u64>
Private Member Functions
u64 getLeafRankId (Grid *leaf)
Geo::Region getLocalAreaForRankId (u64 rankId)
Private Attributes
Geo::Region range
u32 localRankId
u32 rankCount
Geo::P haloThickness
Grid grid
Detailed Description
template<typename Geo>
class DomainDecomposition< Geo >
Definition at line 13 of file decomposition.h.
Member Typedef Documentation
InsideRegionIter
template<typename Geo > using DomainDecomposition< Geo >::InsideRegionIter = InsideRegionLeafsIterator<Grid> private
Definition at line 25 of file decomposition.h.
LeafsIter
template<typename Geo > using DomainDecomposition< Geo >::LeafsIter = LeafsIterator<Grid> private
Definition at line 24 of file decomposition.h.
Morton
template<typename Geo > using DomainDecomposition< Geo >::Morton = mortonnd::MortonNDBmi<Geo::D::N, u64> private
Definition at line 27 of file decomposition.h.
Constructor & Destructor Documentation
DomainDecomposition()
template<typename Geo > DomainDecomposition< Geo >::DomainDecomposition (Geo::Region range, u64 localRankId, u32 rankCount, Geo::P haloThickness)
Definition at line 54 of file decomposition.h.
References assert, LinkedGrid< Geo, 2, Grid >::getMaxChildren(), DomainDecomposition< Geo >::range, DomainDecomposition< Geo >::rankCount, and LinkedGrid< _Geo, SPLIT_FACTOR, Derived >::split().
Member Function Documentation
getLeafRankId()
template<typename Geo > u64 DomainDecomposition< Geo >::getLeafRankId (Grid * leaf) private
Definition at line 31 of file decomposition.h.
References assert, LinkedGrid< _Geo, SPLIT_FACTOR, Derived >::idx, and LinkedGrid< _Geo, SPLIT_FACTOR, Derived >::subtrees.
Referenced by DomainDecomposition< Geo >::getLocalAreaForRankId(), and DomainDecomposition< Geo >::getNeighbourRankIds().
getLocalArea()
template<typename Geo > Geo::Region DomainDecomposition< Geo >::getLocalArea ()
Definition at line 70 of file decomposition.h.
References DomainDecomposition< Geo >::getLocalAreaForRankId().
Referenced by DomainDecomposition< Geo >::getLocalHaloArea(), and DomainDecomposition< Geo >::getLocalHaloForNeighbour().
getLocalAreaForRankId()
template<typename Geo > Geo::Region DomainDecomposition< Geo >::getLocalAreaForRankId (u64 rankId) private
Definition at line 38 of file decomposition.h.
References assert, and DomainDecomposition< Geo >::getLeafRankId().
Referenced by DomainDecomposition< Geo >::getLocalArea(), DomainDecomposition< Geo >::getLocalHaloForNeighbour(), and DomainDecomposition< Geo >::getRemoteHaloForNeighbour().
getLocalHaloArea()
template<typename Geo > Geo::Region DomainDecomposition< Geo >::getLocalHaloArea ()
Definition at line 75 of file decomposition.h.
References DomainDecomposition< Geo >::getLocalArea().
Referenced by DomainDecomposition< Geo >::getNeighbourRankIds(), and DomainDecomposition< Geo >::getRemoteHaloForNeighbour().
getLocalHaloForNeighbour()
template<typename Geo > Geo::Region DomainDecomposition< Geo >::getLocalHaloForNeighbour (u64 neighbourRankId)
Definition at line 99 of file decomposition.h.
References assert, DomainDecomposition< Geo >::getLocalArea(), and DomainDecomposition< Geo >::getLocalAreaForRankId().
getNeighbourRankIds()
template<typename Geo > std::vector< u64 > DomainDecomposition< Geo >::getNeighbourRankIds ()
Definition at line 82 of file decomposition.h.
References DomainDecomposition< Geo >::getLeafRankId(), and DomainDecomposition< Geo >::getLocalHaloArea().
getRemoteHaloForNeighbour()
template<typename Geo > Geo::Region DomainDecomposition< Geo >::getRemoteHaloForNeighbour (u64 neighbourRankId)
Definition at line 109 of file decomposition.h.
References assert, DomainDecomposition< Geo >::getLocalAreaForRankId(), and DomainDecomposition< Geo >::getLocalHaloArea().
Field Documentation
grid
template<typename Geo > Grid DomainDecomposition< Geo >::grid private
Definition at line 29 of file decomposition.h.
haloThickness
template<typename Geo > Geo::P DomainDecomposition< Geo >::haloThickness private
Definition at line 17 of file decomposition.h.
localRankId
template<typename Geo > u32 DomainDecomposition< Geo >::localRankId private
Definition at line 15 of file decomposition.h.
range
template<typename Geo > Geo::Region DomainDecomposition< Geo >::range private
Definition at line 14 of file decomposition.h.
Referenced by DomainDecomposition< Geo >::DomainDecomposition().
rankCount
template<typename Geo > u32 DomainDecomposition< Geo >::rankCount private
Definition at line 16 of file decomposition.h.
Referenced by DomainDecomposition< Geo >::DomainDecomposition().
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/mpi/decomposition.h