Peano
SpacetreeSorter< Spacetree, PreSortCallback > Class Template Reference
#include <sort.h>
Data Structures
struct SortWorkerState
Public Member Functions
SpacetreeSorter (Spacetree *spacetree)
std::vector< typename Spacetree::Item > run (u32 numThreads=0)
Private Attributes
Spacetree * spacetree = nullptr
Detailed Description
template<typename Spacetree, auto PreSortCallback = EmptySortCallback<Spacetree>>
class SpacetreeSorter< Spacetree, PreSortCallback >
Definition at line 11 of file sort.h.
Constructor & Destructor Documentation
SpacetreeSorter()
template<typename Spacetree , auto PreSortCallback = EmptySortCallback<Spacetree>> SpacetreeSorter< Spacetree, PreSortCallback >::SpacetreeSorter (Spacetree * spacetree) explicit
Definition at line 20 of file sort.h.
Member Function Documentation
run()
template<typename Spacetree , auto PreSortCallback = EmptySortCallback<Spacetree>> std::vector< typename Spacetree::Item > SpacetreeSorter< Spacetree, PreSortCallback >::run (u32 numThreads = 0)
Definition at line 22 of file sort.h.
References Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::insert(), InsideRegionLeafsIterator(), Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::items, SpacetreeSorter< Spacetree, PreSortCallback >::SortWorkerState::localTree, Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::onNode(), LinkedGrid< _Geo, SPLIT_FACTOR, Derived >::range, state, and Vector< Tp, Alloc >::unstableTake().
Field Documentation
spacetree
template<typename Spacetree , auto PreSortCallback = EmptySortCallback<Spacetree>> Spacetree* SpacetreeSorter< Spacetree, PreSortCallback >::spacetree = nullptr private
Definition at line 12 of file sort.h.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/spacetree/sort.h