Peano
coordinate.h File Reference
#include <string>
Macros
#define NCOORDS 3
Enumerations
enum Coordinate { Z =0 , Y =1 , X =2 }
Functions
std::string coordToString (Coordinate c)
std::string coordToLowercaseString (Coordinate c)
Coordinate stringToCoord (std::string c)
Coordinate getNormal (Coordinate c1, Coordinate c2)
void getPlane (Coordinate c1, Coordinate &c2, Coordinate &c3)
Macro Definition Documentation
NCOORDS
#define NCOORDS 3
Definition at line 9 of file coordinate.h.
Referenced by Block::Block(), Block::Block(), Edge::Edge(), Face::Face(), Face::Face(), FaceBoundary::FaceBoundary(), FaceBoundary::FaceBoundary(), Curvi::Interface::getElement(), Edge::interpolate(), Interpolation::Lagrange::interpolate1D(), Interpolation::Transfinite::interpolate2D(), Interpolation::Transfinite::interpolate3D(), Interpolation::Lagrange::interpolate3D(), Transformation::metricDerivativesAndJacobian3D(), Edge::numNodes(), BlockBoundary::operator()(), Edge::operator()(), Edge::operator()(), Face::operator()(), Face::operator()(), Block::operator()(), Block::operator()(), Edge::printEdge(), Block::resample(), FaceBoundary::split(), Edge::split(), Face::split(), and Edge::subedge().
Enumeration Type Documentation
Coordinate
enum Coordinate
Enumerator
Z
Y
X
Definition at line 7 of file coordinate.h.
Function Documentation
coordToLowercaseString()
std::string coordToLowercaseString (Coordinate c)
Definition at line 17 of file coordinate.cpp.
References X, Y, and Z.
Referenced by InnerNode::InnerNode(), and Root::Root().
coordToString()
std::string coordToString (Coordinate c)
Definition at line 5 of file coordinate.cpp.
References X, Y, and Z.
Referenced by FaceBoundary::FaceBoundary(), Edge::printEdge(), FaceBoundary::split(), Edge::split(), BlockBoundary::split(), Face::split(), stringToCoord(), Face::subface(), BlockBoundary::toNetCDF(), Block::toString(), InnerNode::toString(), Root::toString(), and BlockBoundary::toString().
getNormal()
Coordinate getNormal (Coordinate c1, Coordinate c2)
Definition at line 41 of file coordinate.cpp.
Referenced by BlockBoundary::BlockBoundary(), BlockBoundary::checkConformity(), Face::Face(), FaceBoundary::FaceBoundary(), FaceBoundary::FaceBoundary(), InnerNode::getFaceNormal(), InnerNode::init(), Root::init(), InnerNode::InnerNode(), Root::Root(), BlockBoundary::setupSplittingFace(), BlockBoundary::split(), Face::split(), InnerNode::traverse(), and InnerNode::traverseProjection().
getPlane()
void getPlane (Coordinate c1, Coordinate & c2, Coordinate & c3)
Definition at line 45 of file coordinate.cpp.
Referenced by Curvi::Interface::invertProjection().
stringToCoord()
Coordinate stringToCoord (std::string c)
Definition at line 29 of file coordinate.cpp.
References coordToString(), X, Y, and Z.
Referenced by InnerNode::InnerNode(), and Root::Root().