Peano
TP::LoggingAdapter Struct Reference
The LoggingAdapter: Logging in Cactus/printf style without macros.
#include <TP_Logging.h>
Public Member Functions
void TP_LOG (const char *fmt,...)
void TP_ERROR (const char *fmt,...)
void TP_INFO (const char *fmt,...)
void TP_WARN (const char *fmt,...)
LoggingAdapter ()
Data Fields
logger * log
Detailed Description
The LoggingAdapter: Logging in Cactus/printf style without macros.
Just inherit from this class to use the facilities.
Definition at line 44 of file TP_Logging.h.
Constructor & Destructor Documentation
LoggingAdapter()
TP::LoggingAdapter::LoggingAdapter ()
Definition at line 53 of file TP_Logging.h.
Member Function Documentation
TP_ERROR()
void LoggingAdapter::TP_ERROR (const char * fmt, ...)
Definition at line 52 of file TP_Logging.cpp.
References vformat().
Referenced by TP::TwoPunctures::Interpolate(), and TP::TwoPunctures::Run().
TP_INFO()
void LoggingAdapter::TP_INFO (const char * fmt, ...)
Definition at line 60 of file TP_Logging.cpp.
References vformat().
Referenced by TP::Parameters::PrintParameters(), and TP::TwoPunctures::Run().
TP_LOG()
void LoggingAdapter::TP_LOG (const char * fmt, ...)
Definition at line 44 of file TP_Logging.cpp.
References vformat().
TP_WARN()
void LoggingAdapter::TP_WARN (const char * fmt, ...)
Definition at line 68 of file TP_Logging.cpp.
References vformat().
Referenced by TP::TwoPunctures::Interpolate().
Field Documentation
log
logger* TP::LoggingAdapter::log
Definition at line 51 of file TP_Logging.h.
The documentation for this struct was generated from the following files:
applications/exahype2/ccz4/libtwopunctures/TP_Logging.h
applications/exahype2/ccz4/libtwopunctures/TP_Logging.cpp