Peano
LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder > Class Template Reference
#include <linked_grid_iterator.h>
Public Types
using Grid = Base::Grid
using Item = Spacetree*
Public Types inherited from DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >
using Grid = TGrid
using Item = Item<TGrid>
Public Member Functions
std::optional< Item > next ()
Public Member Functions inherited from DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >
DefaultIteratorCRTP ()=default
DefaultIteratorCRTP (TIterationOrder order)
DefaultIteratorCRTP (Grid *top)
std::optional< Item > next ()
Protected Member Functions
constexpr EventEmitFlag emitFlags ()
bool enter (Spacetree *spacetree)
bool exit (Spacetree *spacetree)
Protected Member Functions inherited from DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >
constexpr EventEmitFlag emitFlags ()
bool enter (TGrid *)
bool exit (TGrid *)
bool hasNext ()
Private Types
using Base = DefaultIteratorCRTP<Spacetree, LeafOrLevelIterator<Spacetree, LEVEL, TIterationOrder>, TIterationOrder>
Private Attributes
friend Base
int level = -1
Additional Inherited Members
Protected Attributes inherited from DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >
TIterationOrder iterationOrder
TGrid * cell = nullptr
Direction state = Direction::Enter
bool hasEmittedLast = false
Detailed Description
template<typename Spacetree, int LEVEL = 4, typename TIterationOrder = NaturalOrder<Spacetree>>
class LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >
Definition at line 327 of file linked_grid_iterator.h.
Member Typedef Documentation
Base
template<typename Spacetree , int LEVEL = 4, typename TIterationOrder = NaturalOrder<Spacetree>> using LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >::Base = DefaultIteratorCRTP<Spacetree, LeafOrLevelIterator<Spacetree, LEVEL, TIterationOrder>, TIterationOrder> private
Definition at line 328 of file linked_grid_iterator.h.
Grid
template<typename Spacetree , int LEVEL = 4, typename TIterationOrder = NaturalOrder<Spacetree>> using LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >::Grid = Base::Grid
Definition at line 351 of file linked_grid_iterator.h.
Item
template<typename Spacetree , int LEVEL = 4, typename TIterationOrder = NaturalOrder<Spacetree>> using LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >::Item = Spacetree*
Definition at line 352 of file linked_grid_iterator.h.
Member Function Documentation
emitFlags()
template<typename Spacetree , int LEVEL = 4, typename TIterationOrder = NaturalOrder<Spacetree>> constexpr EventEmitFlag LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >::emitFlags () constexpr protected
Definition at line 333 of file linked_grid_iterator.h.
References EmitEnter.
enter()
template<typename Spacetree , int LEVEL = 4, typename TIterationOrder = NaturalOrder<Spacetree>> bool LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >::enter (Spacetree * spacetree) protected
Definition at line 337 of file linked_grid_iterator.h.
References LEVEL.
exit()
template<typename Spacetree , int LEVEL = 4, typename TIterationOrder = NaturalOrder<Spacetree>> bool LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >::exit (Spacetree * spacetree) protected
Definition at line 345 of file linked_grid_iterator.h.
next()
template<typename Spacetree , int LEVEL = 4, typename TIterationOrder = NaturalOrder<Spacetree>> std::optional< Item > LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >::next ()
Definition at line 356 of file linked_grid_iterator.h.
References LEVEL, DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::next(), and LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >::next().
Referenced by LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >::next().
Field Documentation
Base
template<typename Spacetree , int LEVEL = 4, typename TIterationOrder = NaturalOrder<Spacetree>> friend LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >::Base private
Definition at line 329 of file linked_grid_iterator.h.
level
template<typename Spacetree , int LEVEL = 4, typename TIterationOrder = NaturalOrder<Spacetree>> int LeafOrLevelIterator< Spacetree, LEVEL, TIterationOrder >::level = -1 private
Definition at line 331 of file linked_grid_iterator.h.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/grid/linked_grid_iterator.h