Peano
SpacetreePruner< Spacetree, SPLIT > Class Template Reference
#include <prune.h>
Public Member Functions
SpacetreePruner (Spacetree *spacetree)
void run (u32 numThreads=0)
Static Private Member Functions
static u64 countChildrenItems (Spacetree *globalLevelBottomUpNode, Spacetree **leafWithMostItems)
static void mergeChildren (Spacetree *globalLevelBottomUpNode, Spacetree *leafWithMostItems, u64 totalItemsCount)
Private Attributes
Spacetree * spacetree = nullptr
Detailed Description
template<typename Spacetree, u32 SPLIT = 4>
class SpacetreePruner< Spacetree, SPLIT >
Definition at line 6 of file prune.h.
Constructor & Destructor Documentation
SpacetreePruner()
template<typename Spacetree , u32 SPLIT = 4> SpacetreePruner< Spacetree, SPLIT >::SpacetreePruner (Spacetree * spacetree) explicit
Definition at line 43 of file prune.h.
Member Function Documentation
countChildrenItems()
template<typename Spacetree , u32 SPLIT = 4> static u64 SpacetreePruner< Spacetree, SPLIT >::countChildrenItems (Spacetree * globalLevelBottomUpNode, Spacetree ** leafWithMostItems) static private
Definition at line 9 of file prune.h.
References Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::CAPACITY, Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::getMaxChildren(), and LinkedGrid< _Geo, SPLIT_FACTOR, Derived >::subtrees.
Referenced by SpacetreePruner< Spacetree, SPLIT >::run().
mergeChildren()
template<typename Spacetree , u32 SPLIT = 4> static void SpacetreePruner< Spacetree, SPLIT >::mergeChildren (Spacetree * globalLevelBottomUpNode, Spacetree * leafWithMostItems, u64 totalItemsCount) static private
Definition at line 31 of file prune.h.
References Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::destroySubtrees(), Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::getMaxChildren(), Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::items, and LinkedGrid< _Geo, SPLIT_FACTOR, Derived >::subtrees.
Referenced by SpacetreePruner< Spacetree, SPLIT >::run().
run()
template<typename Spacetree , u32 SPLIT = 4> void SpacetreePruner< Spacetree, SPLIT >::run (u32 numThreads = 0)
Definition at line 45 of file prune.h.
References BottomUpIterator(), Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::CAPACITY, SpacetreePruner< Spacetree, SPLIT >::countChildrenItems(), Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::getMaxChildren(), SpacetreePruner< Spacetree, SPLIT >::mergeChildren(), and Spacetree< _Geometry, _Item, THRESHOLD, SPLIT_FACTOR, _TaskBackend >::onNode().
Field Documentation
spacetree
template<typename Spacetree , u32 SPLIT = 4> Spacetree* SpacetreePruner< Spacetree, SPLIT >::spacetree = nullptr private
Definition at line 7 of file prune.h.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/spacetree/prune.h