Peano
toolbox::particles::internal Namespace Reference
Functions
double relativeReleaseOwnershipSpatialSortingTolerance (const ::peano4::datamanagement::VertexMarker &marker)
double relativeReleaseOwnershipSpatialSortingTolerance (const ::peano4::datamanagement::CellMarker &marker)
double relativeReleaseOwnershipSpatialSortingTolerance (const tarch::la::Vector< Dimensions, double > &h)
double relativeGrabOwnershipSpatialSortingTolerance (const ::peano4::datamanagement::VertexMarker &marker)
double relativeGrabOwnershipSpatialSortingTolerance (const ::peano4::datamanagement::CellMarker &marker)
double relativeGrabOwnershipSpatialSortingTolerance (const tarch::la::Vector< Dimensions, double > &h)
bool fitsIntoLevel (double searchRadius, const ::peano4::datamanagement::CellMarker &marker)
bool fitsIntoLevel (double searchRadius, const ::peano4::datamanagement::VertexMarker &marker)
std::bitset< Dimensions > getParticleAssociationWithinCell (const tarch::la::Vector< Dimensions, double > &x, const tarch::la::Vector< Dimensions, double > &cellCentre)
Find out which vertex should hold a particle.
Function Documentation
fitsIntoLevel() [1/2]
bool toolbox::particles::internal::fitsIntoLevel (double searchRadius, const ::peano4::datamanagement::CellMarker & marker)
Definition at line 38 of file internal.cpp.
References tarch::la::greaterEquals(), and tarch::la::min().
Referenced by toolbox::particles::tests::MultiscaleTransitionsTest::testLiftDropOfParticleAssociatedWithVertex03(), and toolbox::particles::tests::MultiscaleTransitionsTest::testLiftDropOfParticleAssociatedWithVertex04().
fitsIntoLevel() [2/2]
bool toolbox::particles::internal::fitsIntoLevel (double searchRadius, const ::peano4::datamanagement::VertexMarker & marker)
Definition at line 43 of file internal.cpp.
References tarch::la::greaterEquals(), and tarch::la::min().
getParticleAssociationWithinCell()
std::bitset< Dimensions > toolbox::particles::internal::getParticleAssociationWithinCell (const tarch::la::Vector< Dimensions, double > & x, const tarch::la::Vector< Dimensions, double > & cellCentre)
Find out which vertex should hold a particle.
Parameters
particle The particle of interest to be studied.
cellCentre Results from CellMarker::x().
Returns
The number of the vertex within the cell identified by marker to which you should assign particle. Use to_ulong() to convert the result, as the result identifies the vertex in z-order, i.e. if it returns 00 it is the left bottom vertex, 10 is the right bottom one, and so forth.
Definition at line 48 of file internal.cpp.
References tarch::la::greaterEquals().
relativeGrabOwnershipSpatialSortingTolerance() [1/3]
double toolbox::particles::internal::relativeGrabOwnershipSpatialSortingTolerance (const ::peano4::datamanagement::CellMarker & marker)
Definition at line 28 of file internal.cpp.
References relativeGrabOwnershipSpatialSortingTolerance().
relativeGrabOwnershipSpatialSortingTolerance() [2/3]
double toolbox::particles::internal::relativeGrabOwnershipSpatialSortingTolerance (const ::peano4::datamanagement::VertexMarker & marker)
Definition at line 23 of file internal.cpp.
References relativeGrabOwnershipSpatialSortingTolerance().
Referenced by swift2::kernels::legacy::forceKernelEvaluatePairInteractionPredicate(), swift2::kernels::localParticleCanBeUpdatedInCellKernel(), swift2::kernels::localParticleCanBeUpdatedInCellKernelFromAnyOtherParticle(), swift2::kernels::localParticleCanBeUpdatedInCellKernelFromAnyOtherParticleWithinIterationRange(), swift2::markAllParticlesAsUpdatedWithinCell(), relativeGrabOwnershipSpatialSortingTolerance(), relativeGrabOwnershipSpatialSortingTolerance(), toolbox::particles::tests::MultiscaleTransitionsTest::testLiftDropOfParticleAssociatedWithVertex03(), and toolbox::particles::updateContainedInAdjacentCellProperty().
relativeGrabOwnershipSpatialSortingTolerance() [3/3]
double toolbox::particles::internal::relativeGrabOwnershipSpatialSortingTolerance (const tarch::la::Vector< Dimensions, double > & h)
Definition at line 33 of file internal.cpp.
References toolbox::particles::GrabOwnershipSpatialSortingTolerance, and tarch::la::max().
relativeReleaseOwnershipSpatialSortingTolerance() [1/3]
double toolbox::particles::internal::relativeReleaseOwnershipSpatialSortingTolerance (const ::peano4::datamanagement::CellMarker & marker)
Definition at line 13 of file internal.cpp.
References relativeReleaseOwnershipSpatialSortingTolerance().
relativeReleaseOwnershipSpatialSortingTolerance() [2/3]
double toolbox::particles::internal::relativeReleaseOwnershipSpatialSortingTolerance (const ::peano4::datamanagement::VertexMarker & marker)
Definition at line 8 of file internal.cpp.
References relativeReleaseOwnershipSpatialSortingTolerance().
Referenced by relativeReleaseOwnershipSpatialSortingTolerance(), relativeReleaseOwnershipSpatialSortingTolerance(), toolbox::particles::tests::MultiscaleTransitionsTest::testLiftDropOfParticleAssociatedWithVertex03(), and toolbox::particles::tests::MultiscaleTransitionsTest::testLiftDropOfParticleAssociatedWithVertex04().
relativeReleaseOwnershipSpatialSortingTolerance() [3/3]
double toolbox::particles::internal::relativeReleaseOwnershipSpatialSortingTolerance (const tarch::la::Vector< Dimensions, double > & h)
Definition at line 18 of file internal.cpp.
References tarch::la::max(), and toolbox::particles::ReleaseOwnershipSpatialSortingTolerance.