Peano
TP_PunctureTracker.h File Reference
#include <iostream>
#include <fstream>
#include <limits>
#include <string>
#include <cstring>
#include "tarch/la/Vector.h"
Functions
std::istream & ignoreline (std::fstream &in, std::ifstream::pos_type &pos)
std::string getLastLine (std::fstream &in)
double linearInter (double x1, double f1, double x2, double f2, double target)
void CoorReadIn (double *coor, std::string line)
void ConsReadIn (double *cons, std::string line)
tarch::la::Vector< Dimensions *2, int > FindCellIndex (const double *coor, tarch::la::Vector< Dimensions, double > Offset, double volumeH, int patchSize)
void FindInterIndex (tarch::la::Vector< Dimensions, int > *InterIndex, tarch::la::Vector< Dimensions *2, int > IndexOfCell)
void Interpolation (double *result, tarch::la::Vector< Dimensions, int > *IndexForInter, double *raw, const double *coor, tarch::la::Vector< Dimensions, double > Offset, double volumeH, int patchSize)
Function Documentation
ConsReadIn()
void ConsReadIn (double * cons, std::string line)
Definition at line 58 of file TP_PunctureTracker.h.
CoorReadIn()
void CoorReadIn (double * coor, std::string line)
Definition at line 43 of file TP_PunctureTracker.h.
FindCellIndex()
tarch::la::Vector< Dimensions *2, int > FindCellIndex (const double * coor, tarch::la::Vector< Dimensions, double > Offset, double volumeH, int patchSize)
Definition at line 74 of file TP_PunctureTracker.h.
FindInterIndex()
void FindInterIndex (tarch::la::Vector< Dimensions, int > * InterIndex, tarch::la::Vector< Dimensions *2, int > IndexOfCell)
Definition at line 118 of file TP_PunctureTracker.h.
getLastLine()
std::string getLastLine (std::fstream & in)
Definition at line 18 of file TP_PunctureTracker.h.
References ignoreline().
ignoreline()
std::istream & ignoreline (std::fstream & in, std::ifstream::pos_type & pos)
Definition at line 12 of file TP_PunctureTracker.h.
Referenced by getLastLine().
Interpolation()
void Interpolation (double * result, tarch::la::Vector< Dimensions, int > * IndexForInter, double * raw, const double * coor, tarch::la::Vector< Dimensions, double > Offset, double volumeH, int patchSize)
Definition at line 153 of file TP_PunctureTracker.h.
References linearInter(), and m.
linearInter()
double linearInter (double x1, double f1, double x2, double f2, double target)
Definition at line 34 of file TP_PunctureTracker.h.
Referenced by Interpolation().