Peano
exahype2.solvers.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets Class Reference
Code snippet generator for all adaptive time stepping solvers.
Public Member Functions
create_abstract_solver_user_declarations (self)
create_abstract_solver_user_definitions (self)
create_abstract_solver_constructor_statements (self)
create_compute_time_step_size (self)
Within the actual compute kernels, the kernels ask the solver variant how to determine a new field.
create_compute_new_time_step_size (self)
This is global, fixed time stepping, i.e.
create_finish_time_step_implementation (self)
This routine is inserted after we have reduced all global quantities.
Public Member Functions inherited from exahype2.solvers.SolverCodeSnippets.SolverCodeSnippets
create_start_time_step_implementation (self)
Detailed Description
Code snippet generator for all adaptive time stepping solvers.
Definition at line 6 of file AdaptiveTimeSteppingCodeSnippets.py.
Member Function Documentation
create_abstract_solver_constructor_statements()
exahype2.solvers.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets.create_abstract_solver_constructor_statements (self)
Reimplemented from exahype2.solvers.SolverCodeSnippets.SolverCodeSnippets.
Definition at line 52 of file AdaptiveTimeSteppingCodeSnippets.py.
create_abstract_solver_user_declarations()
exahype2.solvers.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets.create_abstract_solver_user_declarations (self)
Reimplemented from exahype2.solvers.SolverCodeSnippets.SolverCodeSnippets.
Definition at line 11 of file AdaptiveTimeSteppingCodeSnippets.py.
create_abstract_solver_user_definitions()
exahype2.solvers.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets.create_abstract_solver_user_definitions (self)
Reimplemented from exahype2.solvers.SolverCodeSnippets.SolverCodeSnippets.
Definition at line 34 of file AdaptiveTimeSteppingCodeSnippets.py.
create_compute_new_time_step_size()
exahype2.solvers.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets.create_compute_new_time_step_size (self)
This is global, fixed time stepping, i.e.
the new time step size will likely be the same as the previous one, unless the mesh changes, as we work with normalised time step sizes, i.e. in this case the time step size might change. Anyway, the new time step size is only for stats anyway, as we'll pick a global one when we determine timeStepSize the next time step.
Reimplemented from exahype2.solvers.SolverCodeSnippets.SolverCodeSnippets.
Reimplemented in exahype2.solvers.aderdg.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets.
Definition at line 63 of file AdaptiveTimeSteppingCodeSnippets.py.
create_compute_time_step_size()
exahype2.solvers.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets.create_compute_time_step_size (self)
Within the actual compute kernels, the kernels ask the solver variant how to determine a new field.
const double timeStepSize = ...;
You can remove the const if you want. Anyway, this routine has to build up the right time step size choice.
Reimplemented from exahype2.solvers.SolverCodeSnippets.SolverCodeSnippets.
Definition at line 58 of file AdaptiveTimeSteppingCodeSnippets.py.
create_finish_time_step_implementation()
exahype2.solvers.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets.create_finish_time_step_implementation (self)
This routine is inserted after we have reduced all global quantities.
These are the quantities with the postfix ThisTimeStep.
Reimplemented from exahype2.solvers.SolverCodeSnippets.SolverCodeSnippets.
Reimplemented in exahype2.solvers.aderdg.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets, exahype2.solvers.fv.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets, exahype2.solvers.rkdg.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets, and exahype2.solvers.rkfd.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets.
Definition at line 76 of file AdaptiveTimeSteppingCodeSnippets.py.
Referenced by exahype2.solvers.aderdg.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets.create_finish_time_step_implementation(), exahype2.solvers.fv.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets.create_finish_time_step_implementation(), exahype2.solvers.rkdg.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets.create_finish_time_step_implementation(), and exahype2.solvers.rkfd.AdaptiveTimeSteppingCodeSnippets.AdaptiveTimeSteppingCodeSnippets.create_finish_time_step_implementation().
The documentation for this class was generated from the following file:
python/exahype2/solvers/AdaptiveTimeSteppingCodeSnippets.py