Peano
SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader Class Reference
#include <channel.h>
Public Member Functions
Reader (SPMCChannel *channel, u32 consumerIdHint=0)
std::optional< Item > get ()
std::optional< Item > getFast ()
std::optional< Item > getOther ()
Private Attributes
SPMCChannel * channel
const u32 firstItemHint
u32 nextItemHint
Detailed Description
template<typename Item, u32 CELLS_PER_CONSUMER = 16>
class SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader
Definition at line 48 of file channel.h.
Constructor & Destructor Documentation
Reader()
template<typename Item , u32 CELLS_PER_CONSUMER = 16> SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::Reader (SPMCChannel * channel, u32 consumerIdHint = 0) explicit
Definition at line 54 of file channel.h.
Member Function Documentation
get()
template<typename Item , u32 CELLS_PER_CONSUMER = 16> std::optional< Item > SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::get ()
Definition at line 56 of file channel.h.
References SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::getFast(), and SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::getOther().
getFast()
template<typename Item , u32 CELLS_PER_CONSUMER = 16> std::optional< Item > SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::getFast ()
Definition at line 65 of file channel.h.
References SPMCChannel< Item, CELLS_PER_CONSUMER >::buf, SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::firstItemHint, and SPMCChannel< Item, CELLS_PER_CONSUMER >::tryGet().
Referenced by SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::get().
getOther()
template<typename Item , u32 CELLS_PER_CONSUMER = 16> std::optional< Item > SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::getOther ()
Definition at line 84 of file channel.h.
References SPMCChannel< Item, CELLS_PER_CONSUMER >::buf, SPMCChannel< Item, CELLS_PER_CONSUMER >::bufSize, SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::firstItemHint, and SPMCChannel< Item, CELLS_PER_CONSUMER >::tryGet().
Referenced by SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::get().
Field Documentation
channel
template<typename Item , u32 CELLS_PER_CONSUMER = 16> SPMCChannel* SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::channel private
Definition at line 49 of file channel.h.
firstItemHint
template<typename Item , u32 CELLS_PER_CONSUMER = 16> const u32 SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::firstItemHint private
Definition at line 50 of file channel.h.
Referenced by SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::getFast(), and SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::getOther().
nextItemHint
template<typename Item , u32 CELLS_PER_CONSUMER = 16> u32 SPMCChannel< Item, CELLS_PER_CONSUMER >::Reader::nextItemHint private
Definition at line 51 of file channel.h.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/lang/channel.h