Peano
toolbox::particles::assignmentchecks::tests::internal Namespace Reference
Functions
bool liftParticle (const tarch::la::Vector< Dimensions, double > particleX, const tarch::la::Vector< Dimensions, double > vertexX, const tarch::la::Vector< Dimensions, double > vertexH, const int depth)
Does this particle need to be lifted? Yes if particleX is not located in the square with size 2 vertexH around the closest vertex with size vertexH, and if we're not at shallowest point in tree (= depth == 0)
bool dropParticle (const tarch::la::Vector< Dimensions, double > particleX, const tarch::la::Vector< Dimensions, double > vertexH, const int depth, const int maxVertexDepth)
Does this particle need to be dropped? Yes if particleX is located in the square with size 2 vertexH around the closest vertex with size vertexH and while depth doesn't exceed maxVertexDepth.
int findVertexInd (double x, double vertexH)
Find "index" of vertex with size vertexH covering position x assuming all vertices start at (0, 0, 0).
tarch::la::Vector< Dimensions, double > findVertexX (const tarch::la::Vector< Dimensions, double > x, const tarch::la::Vector< Dimensions, double > vertexH)
Find position of vertex with size vertexH covering position x assuming all vertices start at (0, 0, 0).
TestParticle * mirrorParticleAlongPeriodicBoundary (TestParticle *original, bool bx, bool by, bool bz, tarch::la::Vector< Dimensions, double > boundary)
Create a particle mirrored along periodic boundaries.
Function Documentation
dropParticle()
bool toolbox::particles::assignmentchecks::tests::internal::dropParticle (const tarch::la::Vector< Dimensions, double > particleX, const tarch::la::Vector< Dimensions, double > vertexH, const int depth, const int maxVertexDepth)
Does this particle need to be dropped? Yes if particleX is located in the square with size 2 vertexH around the closest vertex with size vertexH and while depth doesn't exceed maxVertexDepth.
Definition at line 45 of file TestHelpers.cpp.
References tarch::la::allGreater(), tarch::la::allSmaller(), dv, and findVertexX().
Referenced by toolbox::particles::assignmentchecks::tests::TestHelpers::testParticleLiftDrop(), toolbox::particles::assignmentchecks::tests::TestHelpers::testParticleWalk(), toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditions(), and toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditionsCorner().
findVertexInd()
int toolbox::particles::assignmentchecks::tests::internal::findVertexInd (double x, double vertexH)
Find "index" of vertex with size vertexH covering position x assuming all vertices start at (0, 0, 0).
Definition at line 68 of file TestHelpers.cpp.
Referenced by findVertexX(), toolbox::particles::assignmentchecks::tests::TestHelpers::testParticleWalkSameTreeLevel(), toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditions(), and toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditionsCorner().
findVertexX()
tarch::la::Vector< Dimensions, double > toolbox::particles::assignmentchecks::tests::internal::findVertexX (const tarch::la::Vector< Dimensions, double > x, const tarch::la::Vector< Dimensions, double > vertexH)
Find position of vertex with size vertexH covering position x assuming all vertices start at (0, 0, 0).
Definition at line 80 of file TestHelpers.cpp.
References findVertexInd().
Referenced by dropParticle(), toolbox::particles::assignmentchecks::tests::TestHelpers::testParticleLiftDrop(), toolbox::particles::assignmentchecks::tests::TestHelpers::testParticleWalk(), toolbox::particles::assignmentchecks::tests::TestHelpers::testParticleWalkSameTreeLevel(), toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditions(), toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditionsCorner(), and toolbox::particles::assignmentchecks::tests::TestHelpers::testSieveSet().
liftParticle()
bool toolbox::particles::assignmentchecks::tests::internal::liftParticle (const tarch::la::Vector< Dimensions, double > particleX, const tarch::la::Vector< Dimensions, double > vertexX, const tarch::la::Vector< Dimensions, double > vertexH, const int depth)
Does this particle need to be lifted? Yes if particleX is not located in the square with size 2 vertexH around the closest vertex with size vertexH, and if we're not at shallowest point in tree (= depth == 0)
Definition at line 22 of file TestHelpers.cpp.
References dv, tarch::la::oneGreater(), and tarch::la::oneSmaller().
Referenced by toolbox::particles::assignmentchecks::tests::TestHelpers::testParticleLiftDrop(), toolbox::particles::assignmentchecks::tests::TestHelpers::testParticleWalk(), toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditions(), and toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditionsCorner().
mirrorParticleAlongPeriodicBoundary()
toolbox::particles::assignmentchecks::tests::TestParticle * toolbox::particles::assignmentchecks::tests::internal::mirrorParticleAlongPeriodicBoundary (TestParticle * original, bool bx, bool by, bool bz, tarch::la::Vector< Dimensions, double > boundary)
Create a particle mirrored along periodic boundaries.
Assumes we're at the lower left (0, 0, 0) corner of the simulation box, and applies +boundary correction.
Parameters
original The original particle to be mirrored.
bx if true, mirror along x axis
by if true, mirror along y axis
bz if true, mirror along z axis
boundary position of the boundary. Essentially equivalent to DomainSize here.
Definition at line 96 of file TestHelpers.cpp.
References toolbox::particles::assignmentchecks::tests::TestParticle::getDepth(), toolbox::particles::assignmentchecks::tests::TestParticle::getPartid(), toolbox::particles::assignmentchecks::tests::TestParticle::getVertexH(), toolbox::particles::assignmentchecks::tests::TestParticle::getX(), toolbox::particles::assignmentchecks::tests::TestParticle::setDepth(), and toolbox::particles::assignmentchecks::tests::TestParticle::setVertexH().
Referenced by toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditionsCorner().