Peano
tl::basic_iterator< C > Class Template Reference
#include <cartesian_product.h>
Public Types
using value_type = cursor::value_type_t<C>
using difference_type = cursor::difference_type_t<C>
using reference = cursor::reference_t<C>
Public Member Functions
basic_iterator ()=default
constexpr basic_iterator (C &&c) noexcept(std::is_nothrow_constructible_v< mixin, C && >)
constexpr basic_iterator (C const &c) noexcept(std::is_nothrow_constructible_v< mixin, C const & >)
template<std::convertible_to< C > O>
constexpr basic_iterator (basic_iterator< O > &&that) noexcept(std::is_nothrow_constructible< mixin, O && >::value)
template<std::convertible_to< C > O>
constexpr basic_iterator (const basic_iterator< O > &that) noexcept(std::is_nothrow_constructible< mixin, const O & >::value)
template<std::convertible_to< C > O>
constexpr basic_iterator & operator= (basic_iterator< O > &&that) &noexcept(std::is_nothrow_assignable< C &, O && >::value)
template<std::convertible_to< C > O>
constexpr basic_iterator & operator= (const basic_iterator< O > &that) &noexcept(std::is_nothrow_assignable< C &, const O & >::value)
template<class T >
requires (!std::same_as<std::decay_t<T>, basic_iterator> && !cursor::next<C>&& cursor::writable<C, T>)
constexpr basic_iterator & operator= (T &&t) &noexcept(noexcept(std::declval< C & >().write(static_cast< T && >(t))))
constexpr decltype(auto) operator* () const noexcept(noexcept(std::declval< const C & >().read()))
constexpr decltype(auto) operator* () noexcept(noexcept(reference_t{ cursor() }))
constexpr decltype(auto) operator* () const noexcept(noexcept(const_reference_t{ cursor() }))
constexpr basic_iterator & operator* () noexcept
constexpr decltype(auto) operator-> () const noexcept(noexcept(cursor().arrow()))
constexpr decltype(auto) operator-> () const noexcept(noexcept(*std::declval< const basic_iterator & >()))
constexpr basic_iterator & operator++ () &noexcept
constexpr basic_iterator & operator++ () &noexcept(noexcept(std::declval< basic_iterator >().cursor().next()))
constexpr auto operator++ (int) &noexcept(noexcept(++std::declval< basic_iterator & >()) &&std::is_nothrow_move_constructible_v< value_type > &&std::is_nothrow_constructible_v< value_type, reference >)
constexpr void operator++ (int) &noexcept(noexcept(++std::declval< basic_iterator & >()))
constexpr basic_iterator operator++ (int) &noexcept(std::is_nothrow_copy_constructible_v< C > &&std::is_nothrow_move_constructible_v< C > &&noexcept(++std::declval< basic_iterator & >()))
constexpr basic_iterator & operator-- () &noexcept(noexcept(cursor().prev()))
constexpr basic_iterator operator-- (int) &noexcept(std::is_nothrow_copy_constructible< basic_iterator >::value &&std::is_nothrow_move_constructible< basic_iterator >::value &&noexcept(--std::declval< basic_iterator & >()))
constexpr basic_iterator & operator+= (difference_type n) &noexcept(noexcept(cursor().advance(n)))
constexpr basic_iterator & operator-= (difference_type n) &noexcept(noexcept(cursor().advance(-n)))
constexpr decltype(auto) operator[] (difference_type n) const noexcept(noexcept(*(std::declval< basic_iterator & >()+n)))
Private Types
using mixin = cursor::mixin_t<C>
using reference_t = decltype(std::declval<C>().read())
using const_reference_t = reference_t
Private Member Functions
constexpr auto & cursor () noexcept
constexpr auto const & cursor () const noexcept
Friends
template<cursor::input >
class basic_iterator
constexpr decltype(auto) iter_move (const basic_iterator &i) noexcept(noexcept(i.cursor().indirect_move()))
template<class O >
requires cursor::indirect_swap<C, O>
constexpr void iter_swap (const basic_iterator &x, const basic_iterator< O > &y) noexcept(noexcept((void) x.indirect_swap(y)))
constexpr difference_type operator- (const basic_iterator &x, const basic_iterator &y) noexcept(noexcept(y.cursor().distance_to(x.cursor())))
constexpr bool operator== (const basic_iterator &x, const basic_iterator &y) noexcept(noexcept(x.cursor().equal(y.cursor())))
constexpr bool operator!= (const basic_iterator &x, const basic_iterator &y) noexcept(noexcept(!(x==y)))
constexpr bool operator< (const basic_iterator &x, const basic_iterator &y) noexcept(noexcept(y - x))
constexpr bool operator> (const basic_iterator &x, const basic_iterator &y) noexcept(noexcept(y - x))
constexpr bool operator<= (const basic_iterator &x, const basic_iterator &y) noexcept(noexcept(y - x))
constexpr bool operator>= (const basic_iterator &x, const basic_iterator &y) noexcept(noexcept(y - x))
Detailed Description
template<cursor::input C>
class tl::basic_iterator< C >
Definition at line 472 of file cartesian_product.h.
Member Typedef Documentation
const_reference_t
template<cursor::input C> using tl::basic_iterator< C >::const_reference_t = reference_t private
Definition at line 486 of file cartesian_product.h.
difference_type
template<cursor::input C> using tl::basic_iterator< C >::difference_type = cursor::difference_type_t<C>
Definition at line 492 of file cartesian_product.h.
mixin
template<cursor::input C> using tl::basic_iterator< C >::mixin = cursor::mixin_t<C> private
Definition at line 476 of file cartesian_product.h.
reference
template<cursor::input C> using tl::basic_iterator< C >::reference = cursor::reference_t<C>
Definition at line 493 of file cartesian_product.h.
reference_t
template<cursor::input C> using tl::basic_iterator< C >::reference_t = decltype(std::declval<C>().read()) private
Definition at line 485 of file cartesian_product.h.
value_type
template<cursor::input C> using tl::basic_iterator< C >::value_type = cursor::value_type_t<C>
Definition at line 491 of file cartesian_product.h.
Constructor & Destructor Documentation
basic_iterator() [1/5]
template<cursor::input C> tl::basic_iterator< C >::basic_iterator () default
basic_iterator() [2/5]
template<cursor::input C> constexpr tl::basic_iterator< C >::basic_iterator (C && c) explicit constexpr noexcept
Definition at line 499 of file cartesian_product.h.
basic_iterator() [3/5]
template<cursor::input C> constexpr tl::basic_iterator< C >::basic_iterator (C const & c) explicit constexpr noexcept
Definition at line 504 of file cartesian_product.h.
basic_iterator() [4/5]
template<cursor::input C> template<std::convertible_to< C > O> constexpr tl::basic_iterator< C >::basic_iterator (basic_iterator< O > && that) constexpr noexcept
Definition at line 509 of file cartesian_product.h.
basic_iterator() [5/5]
template<cursor::input C> template<std::convertible_to< C > O> constexpr tl::basic_iterator< C >::basic_iterator (const basic_iterator< O > & that) constexpr noexcept
Definition at line 514 of file cartesian_product.h.
Member Function Documentation
cursor() [1/2]
template<cursor::input C> constexpr auto const & tl::basic_iterator< C >::cursor () const constexpr private noexcept
Definition at line 479 of file cartesian_product.h.
cursor() [2/2]
template<cursor::input C> constexpr auto & tl::basic_iterator< C >::cursor () constexpr private noexcept
Definition at line 478 of file cartesian_product.h.
Referenced by tl::basic_iterator< C >::operator*(), tl::basic_iterator< C >::operator*(), tl::basic_iterator< C >::operator*(), tl::basic_iterator< C >::operator++(), tl::basic_iterator< C >::operator+=(), tl::basic_iterator< C >::operator--(), tl::basic_iterator< C >::operator-=(), tl::basic_iterator< C >::operator->(), tl::basic_iterator< C >::operator=(), tl::basic_iterator< C >::operator=(), and tl::basic_iterator< C >::operator=().
operator*() [1/4]
template<cursor::input C> constexpr decltype(auto) tl::basic_iterator< C >::operator* () const constexpr noexcept
Definition at line 577 of file cartesian_product.h.
References tl::basic_iterator< C >::cursor().
operator*() [2/4]
template<cursor::input C> constexpr decltype(auto) tl::basic_iterator< C >::operator* () const constexpr noexcept
Definition at line 563 of file cartesian_product.h.
References tl::basic_iterator< C >::cursor().
operator*() [3/4]
template<cursor::input C> constexpr basic_iterator & tl::basic_iterator< C >::operator* () constexpr noexcept
Definition at line 584 of file cartesian_product.h.
operator*() [4/4]
template<cursor::input C> constexpr decltype(auto) tl::basic_iterator< C >::operator* () constexpr noexcept
Definition at line 570 of file cartesian_product.h.
References tl::basic_iterator< C >::cursor().
operator++() [1/5]
template<cursor::input C> constexpr basic_iterator & tl::basic_iterator< C >::operator++ () & constexpr noexcept
Definition at line 604 of file cartesian_product.h.
operator++() [2/5]
template<cursor::input C> constexpr basic_iterator & tl::basic_iterator< C >::operator++ () & constexpr noexcept
Definition at line 607 of file cartesian_product.h.
References tl::basic_iterator< C >::cursor().
operator++() [3/5]
template<cursor::input C> constexpr auto tl::basic_iterator< C >::operator++ (int) & constexpr noexcept
Definition at line 616 of file cartesian_product.h.
operator++() [4/5]
template<cursor::input C> constexpr void tl::basic_iterator< C >::operator++ (int) & constexpr noexcept
Definition at line 629 of file cartesian_product.h.
References void.
operator++() [5/5]
template<cursor::input C> constexpr basic_iterator tl::basic_iterator< C >::operator++ (int) & constexpr noexcept
Definition at line 637 of file cartesian_product.h.
References temp.
operator+=()
template<cursor::input C> constexpr basic_iterator & tl::basic_iterator< C >::operator+= (difference_type n) & constexpr noexcept
Definition at line 667 of file cartesian_product.h.
References tl::basic_iterator< C >::cursor().
operator--() [1/2]
template<cursor::input C> constexpr basic_iterator & tl::basic_iterator< C >::operator-- () & constexpr noexcept
Definition at line 647 of file cartesian_product.h.
References tl::basic_iterator< C >::cursor().
operator--() [2/2]
template<cursor::input C> constexpr basic_iterator tl::basic_iterator< C >::operator-- (int) & constexpr noexcept
Definition at line 657 of file cartesian_product.h.
operator-=()
template<cursor::input C> constexpr basic_iterator & tl::basic_iterator< C >::operator-= (difference_type n) & constexpr noexcept
Definition at line 674 of file cartesian_product.h.
References tl::basic_iterator< C >::cursor().
operator->() [1/2]
template<cursor::input C> constexpr decltype(auto) tl::basic_iterator< C >::operator-> () const constexpr noexcept
Definition at line 596 of file cartesian_product.h.
operator->() [2/2]
template<cursor::input C> constexpr decltype(auto) tl::basic_iterator< C >::operator-> () const constexpr noexcept
Definition at line 590 of file cartesian_product.h.
References tl::basic_iterator< C >::cursor().
operator=() [1/3]
template<cursor::input C> template<std::convertible_to< C > O> constexpr basic_iterator & tl::basic_iterator< C >::operator= (basic_iterator< O > && that) & constexpr noexcept
Definition at line 519 of file cartesian_product.h.
References tl::basic_iterator< C >::cursor().
operator=() [2/3]
template<cursor::input C> template<std::convertible_to< C > O> constexpr basic_iterator & tl::basic_iterator< C >::operator= (const basic_iterator< O > & that) & constexpr noexcept
Definition at line 526 of file cartesian_product.h.
References tl::basic_iterator< C >::cursor().
operator=() [3/3]
template<cursor::input C> template<class T > requires (!std::same_as<std::decay_t<T>, basic_iterator> && !cursor::next<C>&& cursor::writable<C, T>) constexpr basic_iterator & tl::basic_iterator< C >::operator= (T && t) & constexpr noexcept
Definition at line 537 of file cartesian_product.h.
References tl::basic_iterator< C >::cursor().
operator[]()
template<cursor::input C> constexpr decltype(auto) tl::basic_iterator< C >::operator[] (difference_type n) const constexpr noexcept
Definition at line 681 of file cartesian_product.h.
Friends And Related Symbol Documentation
basic_iterator
template<cursor::input C> template<cursor::input > friend class basic_iterator friend
Definition at line 482 of file cartesian_product.h.
iter_move
template<cursor::input C> constexpr decltype(auto) iter_move (const basic_iterator< C > & i) friend
Definition at line 543 of file cartesian_product.h.
iter_swap
template<cursor::input C> template<class O > requires cursor::indirect_swap<C, O> constexpr void iter_swap (const basic_iterator< C > & x, const basic_iterator< O > & y) friend
Definition at line 553 of file cartesian_product.h.
operator!=
template<cursor::input C> constexpr bool operator!= (const basic_iterator< C > & x, const basic_iterator< C > & y) friend
Definition at line 703 of file cartesian_product.h.
operator-
template<cursor::input C> constexpr difference_type operator- (const basic_iterator< C > & x, const basic_iterator< C > & y) friend
Definition at line 688 of file cartesian_product.h.
operator<
template<cursor::input C> constexpr bool operator< (const basic_iterator< C > & x, const basic_iterator< C > & y) friend
Definition at line 712 of file cartesian_product.h.
operator<=
template<cursor::input C> constexpr bool operator<= (const basic_iterator< C > & x, const basic_iterator< C > & y) friend
Definition at line 728 of file cartesian_product.h.
operator==
template<cursor::input C> constexpr bool operator== (const basic_iterator< C > & x, const basic_iterator< C > & y) friend
Definition at line 694 of file cartesian_product.h.
operator>
template<cursor::input C> constexpr bool operator> (const basic_iterator< C > & x, const basic_iterator< C > & y) friend
Definition at line 720 of file cartesian_product.h.
operator>=
template<cursor::input C> constexpr bool operator>= (const basic_iterator< C > & x, const basic_iterator< C > & y) friend
Definition at line 736 of file cartesian_product.h.
The documentation for this class was generated from the following file:
src/tarch/accelerator/cpp/cartesian_product.h