Peano
BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder > Class Template Reference
#include <linked_grid_iterator.h>
Public Types
using Grid = Base::Grid
using Item = Spacetree*
Public Types inherited from LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >
using Grid = Base::Grid
using Item = Spacetree*
Public Types inherited from DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >
using Grid = TGrid
using Item = Item<TGrid>
Public Member Functions
BoundaryLeafsIteratorCRTP (TIterationOrder order)
BoundaryLeafsIteratorCRTP (TIterationOrder order, Spacetree::Geo::Region boundary)
BoundaryLeafsIteratorCRTP (Spacetree *top)
BoundaryLeafsIteratorCRTP (Spacetree *top, Spacetree::Geo::Region boundary)
std::optional< Item > next ()
Public Member Functions inherited from LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >
std::optional< Item > next ()
Public Member Functions inherited from DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >
DefaultIteratorCRTP ()=default
DefaultIteratorCRTP (TIterationOrder order)
DefaultIteratorCRTP (Grid *top)
std::optional< Item > next ()
Protected Types
using Base = LeafsIteratorCRTP<Spacetree, Derived, TIterationOrder>
Protected Types inherited from LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >
using Base = DefaultIteratorCRTP<Spacetree, Derived, TIterationOrder>
Protected Member Functions
bool enter (Spacetree *spacetree)
Protected Member Functions inherited from LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >
constexpr EventEmitFlag emitFlags ()
bool enter (Spacetree *spacetree)
bool exit (Spacetree *spacetree)
Protected Member Functions inherited from DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >
constexpr EventEmitFlag emitFlags ()
bool enter (TGrid *)
bool exit (TGrid *)
bool hasNext ()
Protected Attributes
friend Base
Spacetree::Geo::Region boundary
Protected Attributes inherited from LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >
friend Base
Protected Attributes inherited from DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >
TIterationOrder iterationOrder
TGrid * cell = nullptr
Direction state = Direction::Enter
bool hasEmittedLast = false
Detailed Description
template<typename Spacetree, typename Derived, typename TIterationOrder = NaturalOrder<Spacetree>>
class BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >
Definition at line 186 of file linked_grid_iterator.h.
Member Typedef Documentation
Base
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> using BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::Base = LeafsIteratorCRTP<Spacetree, Derived, TIterationOrder> protected
Definition at line 188 of file linked_grid_iterator.h.
Grid
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> using BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::Grid = Base::Grid
Definition at line 201 of file linked_grid_iterator.h.
Item
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> using BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::Item = Spacetree*
Definition at line 202 of file linked_grid_iterator.h.
Constructor & Destructor Documentation
BoundaryLeafsIteratorCRTP() [1/4]
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::BoundaryLeafsIteratorCRTP (TIterationOrder order) explicit
Definition at line 204 of file linked_grid_iterator.h.
BoundaryLeafsIteratorCRTP() [2/4]
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::BoundaryLeafsIteratorCRTP (TIterationOrder order, Spacetree::Geo::Region boundary)
Definition at line 206 of file linked_grid_iterator.h.
BoundaryLeafsIteratorCRTP() [3/4]
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::BoundaryLeafsIteratorCRTP (Spacetree * top) explicit
Definition at line 208 of file linked_grid_iterator.h.
BoundaryLeafsIteratorCRTP() [4/4]
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::BoundaryLeafsIteratorCRTP (Spacetree * top, Spacetree::Geo::Region boundary)
Definition at line 210 of file linked_grid_iterator.h.
Member Function Documentation
enter()
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> bool BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::enter (Spacetree * spacetree) protected
Definition at line 194 of file linked_grid_iterator.h.
References LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::enter(), and LinkedGrid< _Geo, SPLIT_FACTOR, Derived >::range.
next()
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> std::optional< Item > BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::next ()
Definition at line 212 of file linked_grid_iterator.h.
References LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::next(), and BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::next().
Referenced by BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::next().
Field Documentation
Base
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> friend BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::Base protected
Definition at line 189 of file linked_grid_iterator.h.
boundary
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> Spacetree::Geo::Region BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::boundary protected
Definition at line 192 of file linked_grid_iterator.h.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/grid/linked_grid_iterator.h