Peano
peano4::grid::GridStatistics Struct Reference
#include <GridStatistics.h>
Public Types
enum ObjectConstruction { NoData }
Public Member Functions
GridStatistics ()
GridStatistics (int __numberOfLocalUnrefinedCells, int __numberOfRemoteUnrefinedCells, int __numberOfLocalRefinedCells, int __numberOfRemoteRefinedCells, int __stationarySweeps, bool __coarseningHasBeenVetoed, bool __removedEmptySubtree, tarch::la::Vector< Dimensions, double > __minH)
int getNumberOfLocalUnrefinedCells () const
void setNumberOfLocalUnrefinedCells (int value)
int getNumberOfRemoteUnrefinedCells () const
void setNumberOfRemoteUnrefinedCells (int value)
int getNumberOfLocalRefinedCells () const
void setNumberOfLocalRefinedCells (int value)
int getNumberOfRemoteRefinedCells () const
void setNumberOfRemoteRefinedCells (int value)
int getStationarySweeps () const
void setStationarySweeps (int value)
bool getCoarseningHasBeenVetoed () const
void setCoarseningHasBeenVetoed (bool value)
bool getRemovedEmptySubtree () const
void setRemovedEmptySubtree (bool value)
tarch::la::Vector< Dimensions, double > getMinH () const
void setMinH (const tarch::la::Vector< Dimensions, double > &value)
double getMinH (int index) const
void setMinH (int index, double value)
GridStatistics (const GridStatistics &copy)=default
int getSenderRank () const
GridStatistics (ObjectConstruction)
std::string toString () const
Static Public Member Functions
static MPI_Datatype getForkDatatype ()
Hands out MPI datatype if we work without the LLVM MPI extension.
static MPI_Datatype getJoinDatatype ()
static MPI_Datatype getBoundaryExchangeDatatype ()
static MPI_Datatype getMultiscaleDataExchangeDatatype ()
static MPI_Datatype getGlobalCommunciationDatatype ()
static void freeForkDatatype ()
static void freeJoinDatatype ()
static void freeBoundaryExchangeDatatype ()
static void freeMultiscaleDataExchangeDatatype ()
static void freeGlobalCommunciationDatatype ()
static void initDatatype ()
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
static void shutdownDatatype ()
Free the underlying MPI datatype.
static void send (const peano4::grid::GridStatistics &buffer, int destination, int tag, MPI_Comm communicator)
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
static void receive (peano4::grid::GridStatistics &buffer, int source, int tag, MPI_Comm communicator)
static void send (const peano4::grid::GridStatistics &buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
static void receive (peano4::grid::GridStatistics &buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
static void sendAndPollDanglingMessages (const peano4::grid::GridStatistics &message, int destination, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
static void receiveAndPollDanglingMessages (peano4::grid::GridStatistics &message, int source, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
Private Attributes
int _numberOfLocalUnrefinedCells
int _numberOfRemoteUnrefinedCells
int _numberOfLocalRefinedCells
int _numberOfRemoteRefinedCells
int _stationarySweeps
bool _coarseningHasBeenVetoed
bool _removedEmptySubtree
tarch::la::Vector< Dimensions, double > _minH
int _senderDestinationRank
Static Private Attributes
static MPI_Datatype Datatype = MPI_DATATYPE_NULL
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
Detailed Description
Definition at line 33 of file GridStatistics.h.
Member Enumeration Documentation
ObjectConstruction
enum peano4::grid::GridStatistics::ObjectConstruction
Enumerator
NoData
Definition at line 134 of file GridStatistics.h.
Constructor & Destructor Documentation
GridStatistics() [1/4]
peano4::grid::GridStatistics::GridStatistics ()
Definition at line 35 of file GridStatistics.h.
GridStatistics() [2/4]
peano4::grid::GridStatistics::GridStatistics (int __numberOfLocalUnrefinedCells, int __numberOfRemoteUnrefinedCells, int __numberOfLocalRefinedCells, int __numberOfRemoteRefinedCells, int __stationarySweeps, bool __coarseningHasBeenVetoed, bool __removedEmptySubtree, tarch::la::Vector< Dimensions, double > __minH)
Definition at line 6 of file GridStatistics.cpp.
References setCoarseningHasBeenVetoed(), setMinH(), setNumberOfLocalRefinedCells(), setNumberOfLocalUnrefinedCells(), setNumberOfRemoteRefinedCells(), setNumberOfRemoteUnrefinedCells(), setRemovedEmptySubtree(), and setStationarySweeps().
GridStatistics() [3/4]
peano4::grid::GridStatistics::GridStatistics (const GridStatistics & copy) default
GridStatistics() [4/4]
peano4::grid::GridStatistics::GridStatistics (ObjectConstruction)
Definition at line 138 of file GridStatistics.h.
Member Function Documentation
freeBoundaryExchangeDatatype()
void peano4::grid::GridStatistics::freeBoundaryExchangeDatatype () static
Definition at line 177 of file GridStatistics.cpp.
freeForkDatatype()
void peano4::grid::GridStatistics::freeForkDatatype () static
Definition at line 150 of file GridStatistics.cpp.
freeGlobalCommunciationDatatype()
void peano4::grid::GridStatistics::freeGlobalCommunciationDatatype () static
Definition at line 159 of file GridStatistics.cpp.
freeJoinDatatype()
void peano4::grid::GridStatistics::freeJoinDatatype () static
Definition at line 168 of file GridStatistics.cpp.
freeMultiscaleDataExchangeDatatype()
void peano4::grid::GridStatistics::freeMultiscaleDataExchangeDatatype () static
Definition at line 186 of file GridStatistics.cpp.
getBoundaryExchangeDatatype()
MPI_Datatype peano4::grid::GridStatistics::getBoundaryExchangeDatatype () static
Definition at line 139 of file GridStatistics.cpp.
getCoarseningHasBeenVetoed()
bool peano4::grid::GridStatistics::getCoarseningHasBeenVetoed () const
Definition at line 79 of file GridStatistics.cpp.
Referenced by peano4::parallel::SpacetreeSet::cleanUpTrees(), and operator+().
getForkDatatype()
MPI_Datatype peano4::grid::GridStatistics::getForkDatatype () static
Hands out MPI datatype if we work without the LLVM MPI extension.
If we work with this additional feature, this is the routine where the lazy initialisation is done and the datatype is also cached.
Definition at line 124 of file GridStatistics.cpp.
getGlobalCommunciationDatatype()
MPI_Datatype peano4::grid::GridStatistics::getGlobalCommunciationDatatype () static
Definition at line 129 of file GridStatistics.cpp.
getJoinDatatype()
MPI_Datatype peano4::grid::GridStatistics::getJoinDatatype () static
Definition at line 134 of file GridStatistics.cpp.
getMinH() [1/2]
tarch::la::Vector< Dimensions, double > peano4::grid::GridStatistics::getMinH () const
Definition at line 95 of file GridStatistics.cpp.
Referenced by swift2::timestepping::computeAdmissibleTimeStepSizeFromGlobalMeshSizeAndMaximumVelocity(), operator+(), and selectNextAlgorithmicStep().
getMinH() [2/2]
double peano4::grid::GridStatistics::getMinH (int index) const
Definition at line 103 of file GridStatistics.cpp.
getMultiscaleDataExchangeDatatype()
MPI_Datatype peano4::grid::GridStatistics::getMultiscaleDataExchangeDatatype () static
Definition at line 144 of file GridStatistics.cpp.
getNumberOfLocalRefinedCells()
int peano4::grid::GridStatistics::getNumberOfLocalRefinedCells () const
Definition at line 55 of file GridStatistics.cpp.
Referenced by operator+().
getNumberOfLocalUnrefinedCells()
int peano4::grid::GridStatistics::getNumberOfLocalUnrefinedCells () const
Definition at line 39 of file GridStatistics.cpp.
Referenced by toolbox::loadbalancing::LoadBalancer::getStatistics(), operator+(), runParallel(), toolbox::loadbalancing::Blacklist::update(), updateDomainDecomposition(), and toolbox::loadbalancing::Statistics::updateGlobalView().
getNumberOfRemoteRefinedCells()
int peano4::grid::GridStatistics::getNumberOfRemoteRefinedCells () const
Definition at line 63 of file GridStatistics.cpp.
Referenced by operator+().
getNumberOfRemoteUnrefinedCells()
int peano4::grid::GridStatistics::getNumberOfRemoteUnrefinedCells () const
Definition at line 47 of file GridStatistics.cpp.
Referenced by toolbox::loadbalancing::LoadBalancer::getStatistics(), and operator+().
getRemovedEmptySubtree()
bool peano4::grid::GridStatistics::getRemovedEmptySubtree () const
Definition at line 87 of file GridStatistics.cpp.
Referenced by operator+(), and toolbox::loadbalancing::Blacklist::update().
getSenderRank()
int peano4::grid::GridStatistics::getSenderRank () const
Returns
The rank of the sender of an object. It only make ssense to call this routine after you've invoked receive with MPI_ANY_SOURCE.
Definition at line 194 of file GridStatistics.cpp.
getStationarySweeps()
int peano4::grid::GridStatistics::getStationarySweeps () const
Definition at line 71 of file GridStatistics.cpp.
Referenced by peano4::grid::clear(), operator+(), and selectNextAlgorithmicStep().
initDatatype()
void peano4::grid::GridStatistics::initDatatype () static
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
Definition at line 198 of file GridStatistics.cpp.
Referenced by peano4::parallel::Node::initMPIDatatypes().
receive() [1/2]
void peano4::grid::GridStatistics::receive (peano4::grid::GridStatistics & buffer, int source, int tag, MPI_Comm communicator) static
Definition at line 311 of file GridStatistics.cpp.
References _senderDestinationRank.
Referenced by receiveAndPollDanglingMessages().
receive() [2/2]
void peano4::grid::GridStatistics::receive (peano4::grid::GridStatistics & buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Definition at line 336 of file GridStatistics.cpp.
References _senderDestinationRank.
receiveAndPollDanglingMessages()
void peano4::grid::GridStatistics::receiveAndPollDanglingMessages (peano4::grid::GridStatistics & message, int source, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 376 of file GridStatistics.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), receive(), tarch::services::ServiceRepository::receiveDanglingMessages(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
send() [1/2]
void peano4::grid::GridStatistics::send (const peano4::grid::GridStatistics & buffer, int destination, int tag, MPI_Comm communicator) static
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
However, this did not work with newer C++11 versions, as a member function using this as pointer usually doesn't see the vtable while the init sees the object from outside, i.e. including a vtable. So this routine now is basically an alias for a blocking MPI_Send.
Definition at line 307 of file GridStatistics.cpp.
Referenced by sendAndPollDanglingMessages().
send() [2/2]
void peano4::grid::GridStatistics::send (const peano4::grid::GridStatistics & buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
In systems with heavy MPI usage, this can help to avoid deadlocks.
Definition at line 317 of file GridStatistics.cpp.
sendAndPollDanglingMessages()
void peano4::grid::GridStatistics::sendAndPollDanglingMessages (const peano4::grid::GridStatistics & message, int destination, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 359 of file GridStatistics.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), tarch::services::ServiceRepository::receiveDanglingMessages(), send(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
setCoarseningHasBeenVetoed()
void peano4::grid::GridStatistics::setCoarseningHasBeenVetoed (bool value)
Definition at line 83 of file GridStatistics.cpp.
Referenced by peano4::grid::clear(), and GridStatistics().
setMinH() [1/2]
void peano4::grid::GridStatistics::setMinH (const tarch::la::Vector< Dimensions, double > & value)
Definition at line 99 of file GridStatistics.cpp.
Referenced by peano4::grid::clear(), and GridStatistics().
setMinH() [2/2]
void peano4::grid::GridStatistics::setMinH (int index, double value)
Definition at line 107 of file GridStatistics.cpp.
setNumberOfLocalRefinedCells()
void peano4::grid::GridStatistics::setNumberOfLocalRefinedCells (int value)
Definition at line 59 of file GridStatistics.cpp.
Referenced by peano4::grid::clear(), and GridStatistics().
setNumberOfLocalUnrefinedCells()
void peano4::grid::GridStatistics::setNumberOfLocalUnrefinedCells (int value)
Definition at line 43 of file GridStatistics.cpp.
Referenced by peano4::grid::clear(), and GridStatistics().
setNumberOfRemoteRefinedCells()
void peano4::grid::GridStatistics::setNumberOfRemoteRefinedCells (int value)
Definition at line 67 of file GridStatistics.cpp.
Referenced by peano4::grid::clear(), and GridStatistics().
setNumberOfRemoteUnrefinedCells()
void peano4::grid::GridStatistics::setNumberOfRemoteUnrefinedCells (int value)
Definition at line 51 of file GridStatistics.cpp.
Referenced by peano4::grid::clear(), and GridStatistics().
setRemovedEmptySubtree()
void peano4::grid::GridStatistics::setRemovedEmptySubtree (bool value)
Definition at line 91 of file GridStatistics.cpp.
Referenced by peano4::parallel::SpacetreeSet::cleanUpTrees(), peano4::grid::clear(), and GridStatistics().
setStationarySweeps()
void peano4::grid::GridStatistics::setStationarySweeps (int value)
Definition at line 75 of file GridStatistics.cpp.
Referenced by peano4::grid::clear(), GridStatistics(), peano4::grid::Spacetree::Spacetree(), and peano4::grid::Spacetree::Spacetree().
shutdownDatatype()
void peano4::grid::GridStatistics::shutdownDatatype () static
Free the underlying MPI datatype.
Definition at line 294 of file GridStatistics.cpp.
Referenced by peano4::parallel::Node::shutdownMPIDatatypes().
toString()
std::string peano4::grid::GridStatistics::toString () const
Definition at line 17 of file GridStatistics.cpp.
Referenced by peano4::parallel::SpacetreeSet::getGridStatistics().
Field Documentation
_coarseningHasBeenVetoed
bool peano4::grid::GridStatistics::_coarseningHasBeenVetoed private
Definition at line 155 of file GridStatistics.h.
_minH
tarch::la::Vector<Dimensions,double> peano4::grid::GridStatistics::_minH private
Definition at line 157 of file GridStatistics.h.
_numberOfLocalRefinedCells
int peano4::grid::GridStatistics::_numberOfLocalRefinedCells private
Definition at line 152 of file GridStatistics.h.
_numberOfLocalUnrefinedCells
int peano4::grid::GridStatistics::_numberOfLocalUnrefinedCells private
Definition at line 150 of file GridStatistics.h.
_numberOfRemoteRefinedCells
int peano4::grid::GridStatistics::_numberOfRemoteRefinedCells private
Definition at line 153 of file GridStatistics.h.
_numberOfRemoteUnrefinedCells
int peano4::grid::GridStatistics::_numberOfRemoteUnrefinedCells private
Definition at line 151 of file GridStatistics.h.
_removedEmptySubtree
bool peano4::grid::GridStatistics::_removedEmptySubtree private
Definition at line 156 of file GridStatistics.h.
_senderDestinationRank
int peano4::grid::GridStatistics::_senderDestinationRank private
Definition at line 161 of file GridStatistics.h.
Referenced by receive(), and receive().
_stationarySweeps
int peano4::grid::GridStatistics::_stationarySweeps private
Definition at line 154 of file GridStatistics.h.
Datatype
MPI_Datatype peano4::grid::GridStatistics::Datatype = MPI_DATATYPE_NULL static private
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
However, Peano calls init explicitly in most cases. Without the LLVM extension which caches the MPI datatype once constructed, this field stores the type.
Definition at line 170 of file GridStatistics.h.
The documentation for this struct was generated from the following files:
src/peano4/grid/GridStatistics.h
src/peano4/grid/GridStatistics.cpp