Peano
InnerNode Class Reference
#include <innerNode.h>
Public Member Functions
InnerNode (YAML::Node const &node)
~InnerNode ()
std::string toString (int depth=0)
void init (BlockBoundary &boundary, uint modes[3])
BlockBoundary traverse (int a_index[3])
BlockBoundary traverseProjection (double coordinate[3])
Block traverse ()
void setPosition (double a_position)
double getPosition ()
void getCoordinates (Coordinate a_coords[2])
Coordinate getFaceNormal ()
double evalPerturbation (double y, double x)
void checkInit ()
bool isLeaf () const
Private Attributes
bool isInit
Coordinate coords [2]
double position
int index
easi::Component * model
std::function< double(double, double)> perturbation
Node * left
Node * right
Detailed Description
Definition at line 7 of file innerNode.h.
Constructor & Destructor Documentation
InnerNode()
InnerNode::InnerNode (YAML::Node const & node)
Definition at line 9 of file innerNode.h.
References coords, coordToLowercaseString(), getNormal(), index, InnerNode(), isInit, left, model, perturbation, position, right, and stringToCoord().
Referenced by InnerNode().
~InnerNode()
InnerNode::~InnerNode ()
Definition at line 82 of file innerNode.h.
References left, model, and right.
Member Function Documentation
checkInit()
void InnerNode::checkInit ()
Definition at line 181 of file innerNode.h.
References isInit.
Referenced by traverse(), traverse(), and traverseProjection().
evalPerturbation()
double InnerNode::evalPerturbation (double y, double x)
Definition at line 177 of file innerNode.h.
References perturbation.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::riemannSolver().
getCoordinates()
void InnerNode::getCoordinates (Coordinate a_coords[2])
Definition at line 168 of file innerNode.h.
References coords.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::riemannSolver().
getFaceNormal()
Coordinate InnerNode::getFaceNormal ()
Definition at line 173 of file innerNode.h.
References coords, and getNormal().
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::riemannSolver().
getPosition()
double InnerNode::getPosition ()
Definition at line 164 of file innerNode.h.
References position.
Referenced by ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::riemannSolver().
init()
void InnerNode::init (BlockBoundary & boundary, uint modes[3]) virtual
Implements Node.
Definition at line 99 of file innerNode.h.
References coords, getNormal(), index, Node::init(), int, isInit, left, perturbation, position, and right.
isLeaf()
bool InnerNode::isLeaf () const
Definition at line 187 of file innerNode.h.
setPosition()
void InnerNode::setPosition (double a_position)
Definition at line 160 of file innerNode.h.
References position.
toString()
std::string InnerNode::toString (int depth = 0) virtual
Implements Node.
Definition at line 88 of file innerNode.h.
References coords, coordToString(), index, left, position, right, and Node::toString().
traverse() [1/2]
Block InnerNode::traverse () virtual
Implements Node.
Definition at line 154 of file innerNode.h.
References checkInit(), left, right, and Node::traverse().
traverse() [2/2]
BlockBoundary InnerNode::traverse (int a_index[3]) virtual
Implements Node.
Definition at line 130 of file innerNode.h.
References checkInit(), coords, getNormal(), index, left, right, and Node::traverse().
traverseProjection()
BlockBoundary InnerNode::traverseProjection (double coordinate[3]) virtual
Implements Node.
Definition at line 142 of file innerNode.h.
References checkInit(), coords, getNormal(), left, position, right, and Node::traverseProjection().
Field Documentation
coords
Coordinate InnerNode::coords[2] private
Definition at line 195 of file innerNode.h.
Referenced by getCoordinates(), getFaceNormal(), init(), InnerNode(), toString(), traverse(), and traverseProjection().
index
int InnerNode::index private
Definition at line 197 of file innerNode.h.
Referenced by init(), InnerNode(), toString(), and traverse().
isInit
bool InnerNode::isInit private
Definition at line 193 of file innerNode.h.
Referenced by checkInit(), init(), and InnerNode().
left
Node* InnerNode::left private
Definition at line 202 of file innerNode.h.
Referenced by init(), InnerNode(), toString(), traverse(), traverse(), traverseProjection(), and ~InnerNode().
model
easi::Component* InnerNode::model private
Definition at line 198 of file innerNode.h.
Referenced by peano4.datamodel.ModelToDataRepository.ModelToDataRepository::__get_full_namespace(), peano4.datamodel.ModelToDataRepository.ModelToDataRepository::__parse_data_declarations_in_model(), peano4.datamodel.ModelToDataRepository.ModelToDataRepository::construct_output(), InnerNode(), and ~InnerNode().
perturbation
std::function<double(double,double)> InnerNode::perturbation private
Definition at line 199 of file innerNode.h.
Referenced by evalPerturbation(), init(), and InnerNode().
position
double InnerNode::position private
Definition at line 196 of file innerNode.h.
Referenced by getPosition(), init(), InnerNode(), setPosition(), toString(), and traverseProjection().
right
Node* InnerNode::right private
Definition at line 203 of file innerNode.h.
Referenced by init(), InnerNode(), toString(), traverse(), traverse(), traverseProjection(), and ~InnerNode().
The documentation for this class was generated from the following file:
src/toolbox/curvi/kdTree/innerNode.h