Peano
std Namespace Reference
STL namespace.
Namespaces
namespace ranges
Data Structures
class allocator
STL class.
class array
STL class.
class atomic
STL class.
class atomic_ref
STL class.
class auto_ptr
STL class.
class bad_alloc
STL class.
class bad_cast
STL class.
class bad_exception
STL class.
class bad_typeid
STL class.
class basic_fstream
STL class.
class basic_ifstream
STL class.
class basic_ios
STL class.
class basic_iostream
STL class.
class basic_istream
STL class.
class basic_istringstream
STL class.
class basic_ofstream
STL class.
class basic_ostream
STL class.
class basic_ostringstream
STL class.
class basic_string
STL class.
class basic_string_view
STL class.
class basic_stringstream
STL class.
class bitset
STL class.
class complex
STL class.
class deque
STL class.
class domain_error
STL class.
class error_category
STL class.
class error_code
STL class.
class error_condition
STL class.
class exception
STL class.
class forward_list
STL class.
class fstream
STL class.
class ifstream
STL class.
class invalid_argument
STL class.
class ios
STL class.
class ios_base
STL class.
class istream
STL class.
class istringstream
STL class.
struct iterator_traits< tl::basic_iterator< C > >
class jthread
STL class.
class length_error
STL class.
class list
STL class.
class lock_guard
STL class.
class logic_error
STL class.
class map
STL class.
class multimap
STL class.
class multiset
STL class.
class mutex
STL class.
class ofstream
STL class.
class ostream
STL class.
class ostringstream
STL class.
class out_of_range
STL class.
class overflow_error
STL class.
class pair
STL class.
class priority_queue
STL class.
class queue
STL class.
class range_error
STL class.
class recursive_mutex
STL class.
class recursive_timed_mutex
STL class.
class runtime_error
STL class.
class set
STL class.
class shared_lock
STL class.
class shared_mutex
STL class.
class shared_ptr
STL class.
class shared_timed_mutex
STL class.
class smart_ptr
STL class.
class span
STL class.
class stack
STL class.
class string
STL class.
class string_view
STL class.
class stringstream
STL class.
class system_error
STL class.
class thread
STL class.
class timed_mutex
STL class.
class u16string
STL class.
class u16string_view
STL class.
class u32string
STL class.
class u32string_view
STL class.
class u8string
STL class.
class u8string_view
STL class.
class underflow_error
STL class.
class unique_lock
STL class.
class unique_ptr
STL class.
class unordered_map
STL class.
class unordered_multimap
STL class.
class unordered_multiset
STL class.
class unordered_set
STL class.
class valarray
STL class.
class vector
STL class.
class weak_ptr
STL class.
class wfstream
STL class.
class wifstream
STL class.
class wios
STL class.
class wistream
STL class.
class wistringstream
STL class.
class wofstream
STL class.
class wostream
STL class.
class wostringstream
STL class.
class wstring
STL class.
class wstring_view
STL class.
class wstringstream
STL class.
Functions
template<typename CF >
CF abs (const CF &cf)
Detailed Description
STL namespace.
Function Documentation
abs()
template<typename CF > CF std::abs (const CF & cf)
Definition at line 15 of file CompressedFloat.h.
Referenced by __attribute__(), NumVec< T, LENGTH >::abs(), tarch::la::abs(), riemannSolver::boxcar(), ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::boxcar(), toolbox::blockstructured::computeGradientAndReturnMaxDifference(), tarch::la::convertAbsoluteIntoRelativeValue(), toolbox::blockstructured::copyUnknownAndComputeMaxDifference(), toolbox::multiprecision::decomposeIntoFourVariants(), exahype2::dg::tests::elasticEigenvalue(), examples::regulargridupscaling::MyObserver::enterCell(), tarch::la::equals(), tarch::la::equals(), tarch::la::equalsReturnIndex(), tarch::la::equalsReturnIndex(), exahype2::dg::tests::eulerEigenvalue(), toolbox::particles::TrajectoryDatabase::getAction(), toolbox::blockstructured::GlobalDatabase::getAction(), toolbox::particles::getParticleReassociationInstructionWithinCellWithIntraCellReassignment(), tarch::timing::Measurement::getStandardDeviation(), swift2::kernels::legacy::hydro_update_smoothing_length_and_rerun_if_required(), Edge::interpolate(), toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_linear(), tarch::timing::GlidingAverageMeasurement::isAccurateValue(), peano4::datamanagement::VertexMarker::isContainedInAdjacentCells(), peano4::datamanagement::VertexMarker::isContainedInAdjacentCellsByDimension(), tarch::la::lu(), tarch::la::maxAbs(), applications::exahype2::ccz4::CCZ4::maxEigenvalue(), benchmarks::exahype2::ccz4::CCZ4::maxEigenvalue(), examples::exahype2::mgccz4::FiniteVolumeMGCCZ4::maxEigenvalue(), examples::exahype2::mgccz4::ADERDGMGCCZ4::maxEigenvalue(), tarch::la::normMax(), tarch::la::normMax(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::plotCell(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::plotCell(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::plotCell(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::plotCell(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::plotVertex(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::plotVertex(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::plotVertex(), exahype2::fv::internal::projectValueOntoParticle_piecewiseLinear(), tarch::la::relativeEps(), tarch::la::relativeEpsNormaledAgainstValueGreaterOne(), ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::riemannSolver(), tarch::timing::Measurement::setValue(), riemannSolver::slip_weakening(), toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testBatchDecomposition(), toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testBatchDecompositionWithArrayOfFour(), toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testDecompose(), toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testDecomposeWithChar(), toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testDecomposeWithInt(), toolbox::multiprecision::tests::CompressedFloatingPointNumbersTest::testErrorComputation(), mghype::matrixfree::solvers::SolverStatistics::updateGlobalPrecondResidual(), mghype::matrixfree::solvers::SolverStatistics::updateGlobalResidual(), mghype::matrixfree::solvers::SolverStatistics::updateGlobalSolutionUpdates(), and validateOutcome().