Peano
ExaHyPEMain.template.cpp File Reference
#include "{{MAIN_NAME}}.h"
#include "{{SUBDIRECTORY}}Constants.h"
#include "{{SUBDIRECTORY}}observers/CreateGridWithRefinement.h"
#include "{{SUBDIRECTORY}}observers/CreateGridWithoutRefinement.h"
#include "{{SUBDIRECTORY}}observers/InitGrid.h"
#include "{{SUBDIRECTORY}}observers/PlotSolution.h"
#include "{{SUBDIRECTORY}}observers/CheckpointSolution.h"
#include "{{SUBDIRECTORY}}observers/TimeStep.h"
#include "{{subdirectory}}repositories/DataRepository.h"
#include "{{subdirectory}}repositories/SolverRepository.h"
#include "{{subdirectory}}repositories/StepRepository.h"
#include "repositories/DataRepository.h"
#include "repositories/SolverRepository.h"
#include "repositories/StepRepository.h"
#include "tarch/NonCriticalAssertions.h"
#include "tarch/accelerator/MemoryManager.h"
#include "tarch/logging/Log.h"
#include "tarch/logging/LogFilter.h"
#include "tarch/logging/Statistics.h"
#include "tarch/multicore/Core.h"
#include "tarch/multicore/multicore.h"
#include "tarch/timing/Measurement.h"
#include "tarch/timing/Watch.h"
#include "peano4/peano4.h"
#include "peano4/grid/Spacetree.h"
#include "peano4/parallel/SpacetreeSet.h"
#include <iomanip>
#include <fenv.h>
Macros
#define SCOREP_USER_REGION_DEFINE(handle)
#define SCOREP_USER_REGION_BEGIN(handle, name, type)
#define SCOREP_USER_REGION_END(handle)
Functions
bool selectNextAlgorithmicStep ()
Decide which step to run next.
void printNextAlgorithmicStep (const {{SUBNAMESPACE}}repositories::StepRepository::Steps &stepName)
void step ()
int main (int argc, char **argv)
Main routine of the SPH code.
Variables
tarch::logging::Log _log ("")
tarch::timing::Measurement gridConstructionMeasurement
tarch::timing::Measurement timeStepMeasurement
tarch::timing::Measurement plotMeasurement
static double printNextTimeStep = 0.0
static bool haveReceivedNonCriticalAssertion = false
Macro Definition Documentation
SCOREP_USER_REGION_BEGIN
#define SCOREP_USER_REGION_BEGIN (handle, name, type)
SCOREP_USER_REGION_DEFINE
#define SCOREP_USER_REGION_DEFINE (handle)
SCOREP_USER_REGION_END
#define SCOREP_USER_REGION_END (handle)
Function Documentation
main()
int main (int argc, char ** argv)
Main routine of the SPH code.
Definition at line 490 of file ExaHyPEMain.template.cpp.
References tarch::logging::Statistics::clear(), tarch::timing::Measurement::getAccumulatedValue(), peano4::parallel::Node::getInstance(), tarch::logging::Statistics::getInstance(), tarch::mpi::Rank::getInstance(), tarch::timing::Measurement::getNumberOfMeasurements(), tarch::timing::Measurement::getValue(), gridConstructionMeasurement, haveReceivedNonCriticalAssertion, peano4::init(), logInfo, main(), plotMeasurement, selectNextAlgorithmicStep(), peano4::shutdown(), step(), timeStepMeasurement, tarch::timing::Measurement::toString(), and tarch::logging::Statistics::writeToCSV().
printNextAlgorithmicStep()
void printNextAlgorithmicStep (const {{SUBNAMESPACE}}repositories::StepRepository::Steps & stepName)
Definition at line 237 of file ExaHyPEMain.template.cpp.
Referenced by step().
selectNextAlgorithmicStep()
bool selectNextAlgorithmicStep ()
Decide which step to run next.
Control of the parallel grid construction
Returns
continues to run
Definition at line 73 of file ExaHyPEMain.template.cpp.
References peano4::parallel::SpacetreeSet::getGridStatistics(), peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), peano4::grid::GridStatistics::getMinH(), peano4::grid::GridStatistics::getStationarySweeps(), tarch::hasNonCriticalAssertionBeenViolated(), haveReceivedNonCriticalAssertion, logDebug, logError, logWarning, tarch::la::max(), and peano4::parallel::Node::setNextProgramStep().
Referenced by main().
step()
void step ()
Definition at line 251 of file ExaHyPEMain.template.cpp.
References assertion, tarch::timing::Measurement::getAccumulatedValue(), tarch::timing::Watch::getCalendarTime(), peano4::parallel::Node::getCurrentProgramStep(), peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), tarch::logging::LogFilter::getInstance(), tarch::logging::Statistics::getInstance(), tarch::mpi::Rank::getInstance(), tarch::timing::Measurement::getNumberOfMeasurements(), tarch::accelerator::MemoryManager::getStatistics(), toolbox::loadbalancing::LoadBalancer::getStatistics(), tarch::timing::Measurement::getValue(), gridConstructionMeasurement, tarch::logging::Statistics::log(), logInfo, plotMeasurement, printNextAlgorithmicStep(), printNextTimeStep, SCOREP_USER_REGION_BEGIN, SCOREP_USER_REGION_DEFINE, SCOREP_USER_REGION_END, tarch::timing::Measurement::setValue(), tarch::timing::Watch::start(), tarch::timing::Watch::stop(), tarch::logging::LogFilter::switchProgramPhase(), timeStepMeasurement, and peano4::parallel::SpacetreeSet::traverse().
Referenced by main().
Variable Documentation
_log
tarch::logging::Log _log("") ("")
gridConstructionMeasurement
tarch::timing::Measurement gridConstructionMeasurement
Definition at line 58 of file ExaHyPEMain.template.cpp.
Referenced by main(), and step().
haveReceivedNonCriticalAssertion
bool haveReceivedNonCriticalAssertion = false static
Definition at line 63 of file ExaHyPEMain.template.cpp.
Referenced by main(), and selectNextAlgorithmicStep().
plotMeasurement
tarch::timing::Measurement plotMeasurement
Definition at line 60 of file ExaHyPEMain.template.cpp.
Referenced by main(), and step().
printNextTimeStep
double printNextTimeStep = 0.0 static
Definition at line 62 of file ExaHyPEMain.template.cpp.
Referenced by step().
timeStepMeasurement
tarch::timing::Measurement timeStepMeasurement
Definition at line 59 of file ExaHyPEMain.template.cpp.
Referenced by main(), and step().