Peano
tarch::plotter::griddata::unstructured::vtk::tests::VTKBinaryFileTestCase Class Reference
This is just a default test case that demonstrated how to write unit tests in Peano.
#include <VTKBinaryFileTestCase.h>
Public Member Functions
VTKBinaryFileTestCase ()
virtual ~VTKBinaryFileTestCase ()
virtual void run ()
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testHexahedron ()
These operation usually implement the real tests.
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
This is just a default test case that demonstrated how to write unit tests in Peano.
Feel free to rename, remove, or duplicate it.
Definition at line 29 of file VTKBinaryFileTestCase.h.
Constructor & Destructor Documentation
VTKBinaryFileTestCase()
tarch::plotter::griddata::unstructured::vtk::tests::VTKBinaryFileTestCase::VTKBinaryFileTestCase ()
Definition at line 15 of file VTKBinaryFileTestCase.cpp.
~VTKBinaryFileTestCase()
tarch::plotter::griddata::unstructured::vtk::tests::VTKBinaryFileTestCase::~VTKBinaryFileTestCase () virtual
Definition at line 20 of file VTKBinaryFileTestCase.cpp.
Member Function Documentation
run()
void tarch::plotter::griddata::unstructured::vtk::tests::VTKBinaryFileTestCase::run () virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 24 of file VTKBinaryFileTestCase.cpp.
References testMethod.
testHexahedron()
void tarch::plotter::griddata::unstructured::vtk::tests::VTKBinaryFileTestCase::testHexahedron () private
These operation usually implement the real tests.
Definition at line 29 of file VTKBinaryFileTestCase.cpp.
References tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellDataWriter::close(), tarch::plotter::griddata::unstructured::UnstructuredGridWriter::VertexDataWriter::close(), tarch::plotter::griddata::unstructured::UnstructuredGridWriter::VertexWriter::close(), tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellWriter::close(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::createCellDataWriter(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::createCellWriter(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::createVertexDataWriter(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::createVertexWriter(), tarch::plotter::PVDTimeSeriesWriter::NoIndexFile, tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellDataWriter::plotCell(), tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellWriter::plotHexahedron(), tarch::plotter::griddata::unstructured::UnstructuredGridWriter::VertexWriter::plotVertex(), tarch::plotter::griddata::unstructured::UnstructuredGridWriter::VertexDataWriter::plotVertex(), and tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::writeToFile().
The documentation for this class was generated from the following files:
src/tarch/plotter/griddata/unstructured/vtk/tests/VTKBinaryFileTestCase.h
src/tarch/plotter/griddata/unstructured/vtk/tests/VTKBinaryFileTestCase.cpp