Peano
examples::exahype2::mgccz4::ADERDGMGCCZ4 Class Reference
#include <ADERDGMGCCZ4.h>
Public Member Functions
ADERDGMGCCZ4 ()
void adjustSolution (double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &x, double t) override
virtual void boundaryConditions (const double *__restrict__ Qinside, double *__restrict__ Qoutside, const tarch::la::Vector< Dimensions, double > &x, double t, int normal) override
double maxEigenvalue (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &x, double t, int normal) override
void nonconservativeProduct (const double *__restrict__ Q, const double *__restrict__ deltaQ, const tarch::la::Vector< Dimensions, double > &x, double t, int normal, double *__restrict__ BgradQ) override
virtual void algebraicSource (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &x, const tarch::la::Vector< Dimensions, double > &h, double t, double dt, double *__restrict__ S) override
Static Private Attributes
static tarch::logging::Log _log
Detailed Description
Definition at line 23 of file ADERDGMGCCZ4.h.
Constructor & Destructor Documentation
ADERDGMGCCZ4()
examples::exahype2::mgccz4::ADERDGMGCCZ4::ADERDGMGCCZ4 ()
Definition at line 18 of file ADERDGMGCCZ4.cpp.
Member Function Documentation
adjustSolution()
void examples::exahype2::mgccz4::ADERDGMGCCZ4::adjustSolution (double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & x, double t) override
Definition at line 29 of file ADERDGMGCCZ4.cpp.
References assertion3, examples::exahype2::mgccz4::enforceMGCCZ4constraints(), tarch::la::equals(), examples::exahype2::mgccz4::gaugeWave(), examples::exahype2::mgccz4::linearWave(), logError, logTraceInWith2Arguments, and logTraceOut.
algebraicSource()
void examples::exahype2::mgccz4::ADERDGMGCCZ4::algebraicSource (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & x, const tarch::la::Vector< Dimensions, double > & h, double t, double dt, double *__restrict__ S) override virtual
Definition at line 60 of file ADERDGMGCCZ4.cpp.
References assertion3, nonCriticalAssertion3, and examples::exahype2::mgccz4::source().
boundaryConditions()
void examples::exahype2::mgccz4::ADERDGMGCCZ4::boundaryConditions (const double *__restrict__ Qinside, double *__restrict__ Qoutside, const tarch::la::Vector< Dimensions, double > & x, double t, int normal) override virtual
Definition at line 164 of file ADERDGMGCCZ4.cpp.
References assertion4, logTraceInWith3Arguments, and logTraceOut.
maxEigenvalue()
double examples::exahype2::mgccz4::ADERDGMGCCZ4::maxEigenvalue (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & x, double t, int normal) override
Definition at line 80 of file ADERDGMGCCZ4.cpp.
References std::abs().
nonconservativeProduct()
void examples::exahype2::mgccz4::ADERDGMGCCZ4::nonconservativeProduct (const double *__restrict__ Q, const double *__restrict__ deltaQ, const tarch::la::Vector< Dimensions, double > & x, double t, int normal, double *__restrict__ BgradQ) override
Definition at line 133 of file ADERDGMGCCZ4.cpp.
References assertion, logTraceInWith3Arguments, logTraceOut, examples::exahype2::mgccz4::ncp(), and nonCriticalAssertion4.
Field Documentation
_log
tarch::logging::Log examples::exahype2::mgccz4::ADERDGMGCCZ4::_log static private
Definition at line 25 of file ADERDGMGCCZ4.h.
The documentation for this class was generated from the following files:
applications/exahype2/mgccz4/ADERDGMGCCZ4.h
applications/exahype2/mgccz4/ADERDGMGCCZ4.cpp