var ProjectIntoCellAndUpdateCellSolution_8py =
[
    [ "solvers.api.actionsets.DGSolver.ProjectIntoCellAndUpdateCellSolution.ProjectIntoCellAndUpdateCellSolution", "d8/d8c/classsolvers_1_1api_1_1actionsets_1_1DGSolver_1_1ProjectIntoCellAndUpdateCellSolution_1_1ProjectIntoCellAndUpdateCellSolution.html", "d8/d8c/classsolvers_1_1api_1_1actionsets_1_1DGSolver_1_1ProjectIntoCellAndUpdateCellSolution_1_1ProjectIntoCellAndUpdateCellSolution" ]
];