Peano
exahype2::EnclaveBookkeeping Class Reference
#include <EnclaveBookkeeping.h>
Public Member Functions
EnclaveBookkeeping (const EnclaveBookkeeping &)=delete
EnclaveBookkeeping & operator= (const EnclaveBookkeeping &)=delete
EnclaveBookkeeping (EnclaveBookkeeping &&)=delete
EnclaveBookkeeping & operator= (EnclaveBookkeeping &&)=delete
~EnclaveBookkeeping ()
void bookmarkTask (tarch::multicore::Task *task)
void clear ()
void fusePendingTasks ()
std::map< int, std::size_t > getNumberOfTasksPerType () const
std::size_t getTotalNumberOfTasks () const
Static Public Member Functions
static EnclaveBookkeeping & getInstance ()
Private Member Functions
EnclaveBookkeeping ()=default
Private Attributes
std::map< int, std::list< tarch::multicore::Task * > > pendingTasks
tarch::multicore::BooleanSemaphore pendingTasksSemaphore
Static Private Attributes
static tarch::logging::Log _log
Detailed Description
Definition at line 20 of file EnclaveBookkeeping.h.
Constructor & Destructor Documentation
EnclaveBookkeeping() [1/3]
exahype2::EnclaveBookkeeping::EnclaveBookkeeping () private default
EnclaveBookkeeping() [2/3]
exahype2::EnclaveBookkeeping::EnclaveBookkeeping (const EnclaveBookkeeping &) delete
EnclaveBookkeeping() [3/3]
exahype2::EnclaveBookkeeping::EnclaveBookkeeping (EnclaveBookkeeping &&) delete
~EnclaveBookkeeping()
exahype2::EnclaveBookkeeping::~EnclaveBookkeeping ()
Definition at line 7 of file EnclaveBookkeeping.cpp.
Member Function Documentation
bookmarkTask()
void exahype2::EnclaveBookkeeping::bookmarkTask (tarch::multicore::Task * task)
Definition at line 11 of file EnclaveBookkeeping.cpp.
References assertion, assertion1, tarch::multicore::Task::getTaskType(), and logInfo.
Referenced by exahype2::tests::EnclaveBookkeepingTest::testFusePendingTasks().
clear()
void exahype2::EnclaveBookkeeping::clear ()
Definition at line 28 of file EnclaveBookkeeping.cpp.
Referenced by peano4.output.Makefile.Makefile::__init__().
fusePendingTasks()
void exahype2::EnclaveBookkeeping::fusePendingTasks ()
Definition at line 38 of file EnclaveBookkeeping.cpp.
References firstTask(), and tarch::multicore::Task::fuse().
Referenced by exahype2::tests::EnclaveBookkeepingTest::testFusePendingTasks().
getInstance()
static EnclaveBookkeeping & exahype2::EnclaveBookkeeping::getInstance () static
Definition at line 37 of file EnclaveBookkeeping.h.
Referenced by exahype2::tests::EnclaveBookkeepingTest::testFusePendingTasks().
getNumberOfTasksPerType()
std::map< int, std::size_t > exahype2::EnclaveBookkeeping::getNumberOfTasksPerType () const
Definition at line 57 of file EnclaveBookkeeping.cpp.
getTotalNumberOfTasks()
std::size_t exahype2::EnclaveBookkeeping::getTotalNumberOfTasks () const
Definition at line 65 of file EnclaveBookkeeping.cpp.
operator=() [1/2]
EnclaveBookkeeping & exahype2::EnclaveBookkeeping::operator= (const EnclaveBookkeeping &) delete
operator=() [2/2]
EnclaveBookkeeping & exahype2::EnclaveBookkeeping::operator= (EnclaveBookkeeping &&) delete
Field Documentation
_log
tarch::logging::Log exahype2::EnclaveBookkeeping::_log static private
Definition at line 22 of file EnclaveBookkeeping.h.
pendingTasks
std::map<int, std::list<tarch::multicore::Task*> > exahype2::EnclaveBookkeeping::pendingTasks private
Definition at line 24 of file EnclaveBookkeeping.h.
pendingTasksSemaphore
tarch::multicore::BooleanSemaphore exahype2::EnclaveBookkeeping::pendingTasksSemaphore private
Definition at line 25 of file EnclaveBookkeeping.h.
The documentation for this class was generated from the following files:
src/exahype2/EnclaveBookkeeping.h
src/exahype2/EnclaveBookkeeping.cpp