Peano
tarch::la::tests::ScalarTest Class Reference
#include <ScalarTest.h>
Public Member Functions
ScalarTest ()
Constructor.
virtual ~ScalarTest ()
Destructor, empty.
virtual void run ()
Runs all tests.
virtual void setUp ()
Sets up test environment.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testComparison ()
void testAbs ()
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Definition at line 15 of file ScalarTest.h.
Constructor & Destructor Documentation
ScalarTest()
tarch::la::tests::ScalarTest::ScalarTest ()
Constructor.
Definition at line 9 of file ScalarTest.cpp.
~ScalarTest()
virtual tarch::la::tests::ScalarTest::~ScalarTest () virtual
Destructor, empty.
Definition at line 33 of file ScalarTest.h.
Member Function Documentation
run()
void tarch::la::tests::ScalarTest::run () virtual
Runs all tests.
Implements tarch::tests::TestCase.
Definition at line 14 of file ScalarTest.cpp.
References testMethod.
setUp()
virtual void tarch::la::tests::ScalarTest::setUp () virtual
Sets up test environment.
Definition at line 43 of file ScalarTest.h.
testAbs()
void tarch::la::tests::ScalarTest::testAbs () private
Definition at line 51 of file ScalarTest.cpp.
References a, tarch::la::abs(), and validateEquals.
testComparison()
void tarch::la::tests::ScalarTest::testComparison () private
Definition at line 19 of file ScalarTest.cpp.
References a, tarch::la::equals(), tarch::la::greater(), tarch::la::greaterEquals(), tarch::la::max(), tarch::la::smaller(), tarch::la::smallerEquals(), and validate.
The documentation for this class was generated from the following files:
src/tarch/la/tests/ScalarTest.h
src/tarch/la/tests/ScalarTest.cpp