Peano
ContextCurvilinear< Shortcuts, basisSize, numberOfData, T > Class Template Reference
#include <ContextCurvilinear.h>
Public Member Functions
ContextCurvilinear (std::string &topography_string, int coarsestMeshLevel, double coarsestMeshSize, double maxAdaptiveDepth, tarch::la::Vector< Dimensions, double > _domainOffset, tarch::la::Vector< Dimensions, double > _domainSize, T *_nodes, T *_dudx)
Root * getRoot ()
~ContextCurvilinear ()
void initUnknownsPatch (T *luh, const tarch::la::Vector< Dimensions, double > &center, const tarch::la::Vector< Dimensions, double > &dx, double t, double dt, std::function< void(const T *const x, const tarch::la::Vector< Dimensions, double > &center, const double t, const double dt, T *Q)> initUnknownsPointwise)
void correctPointSourceLocation (double pointSourceLocation[][3])
void getElementSize (const T *const luh, tarch::la::Vector< Dimensions, double > &dx)
void getElementCenter (const T *const luh, tarch::la::Vector< Dimensions, double > &center)
Data Fields
double max_dx
Protected Attributes
Curvi::Interface * interface
double nodes [basisSize]
double dudx [basisSize][basisSize]
double domainOffset [3]
const int meshLevel
Detailed Description
template<class Shortcuts, int basisSize, int numberOfData, typename T>
class ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >
Definition at line 12 of file ContextCurvilinear.h.
Constructor & Destructor Documentation
ContextCurvilinear()
template<class Shortcuts , int basisSize, int numberOfData, typename T > ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::ContextCurvilinear (std::string & topography_string, int coarsestMeshLevel, double coarsestMeshSize, double maxAdaptiveDepth, tarch::la::Vector< Dimensions, double > _domainOffset, tarch::la::Vector< Dimensions, double > _domainSize, T * _nodes, T * _dudx)
Definition at line 15 of file ContextCurvilinear.h.
References ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::domainOffset, ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::dudx, ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::interface, ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::max_dx, ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::nodes, X, Y, and Z.
~ContextCurvilinear()
template<class Shortcuts , int basisSize, int numberOfData, typename T > ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::~ContextCurvilinear ()
Definition at line 62 of file ContextCurvilinear.h.
References ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::interface.
Member Function Documentation
correctPointSourceLocation()
template<class Shortcuts , int basisSize, int numberOfData, typename T > void ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::correctPointSourceLocation (double pointSourceLocation[][3])
Definition at line 187 of file ContextCurvilinear.h.
References ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::interface, Curvi::Interface::invertProjection(), X, Y, and Z.
getElementCenter()
template<class Shortcuts , int basisSize, int numberOfData, typename T > void ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::getElementCenter (const T *const luh, tarch::la::Vector< Dimensions, double > & center)
Definition at line 225 of file ContextCurvilinear.h.
References int.
Referenced by ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::initUnknownsPatch().
getElementSize()
template<class Shortcuts , int basisSize, int numberOfData, typename T > void ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::getElementSize (const T *const luh, tarch::la::Vector< Dimensions, double > & dx)
Definition at line 201 of file ContextCurvilinear.h.
References dx.
getRoot()
template<class Shortcuts , int basisSize, int numberOfData, typename T > Root * ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::getRoot ()
Definition at line 60 of file ContextCurvilinear.h.
initUnknownsPatch()
template<class Shortcuts , int basisSize, int numberOfData, typename T > void ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::initUnknownsPatch (T * luh, const tarch::la::Vector< Dimensions, double > & center, const tarch::la::Vector< Dimensions, double > & dx, double t, double dt, std::function< void(const T *const x, const tarch::la::Vector< Dimensions, double > &center, const double t, const double dt, T *Q)> initUnknownsPointwise)
Definition at line 66 of file ContextCurvilinear.h.
References assertion5, ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::domainOffset, ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::dudx, dx, tarch::la::equals(), Curvi::Interface::getElement(), ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::getElementCenter(), Block::getIndexOffset(), ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::interface, m, ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::meshLevel, ExaSeis::Derivatives< Shortcuts, T, num_nodes, numberOfData >::metricDerivatives(), ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::nodes, X, Y, and Z.
Field Documentation
domainOffset
template<class Shortcuts , int basisSize, int numberOfData, typename T > double ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::domainOffset[3] protected
Definition at line 252 of file ContextCurvilinear.h.
Referenced by ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::ContextCurvilinear(), and ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::initUnknownsPatch().
dudx
template<class Shortcuts , int basisSize, int numberOfData, typename T > double ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::dudx[basisSize][basisSize] protected
Definition at line 250 of file ContextCurvilinear.h.
Referenced by ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::ContextCurvilinear(), and ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::initUnknownsPatch().
interface
template<class Shortcuts , int basisSize, int numberOfData, typename T > Curvi::Interface* ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::interface protected
Definition at line 247 of file ContextCurvilinear.h.
Referenced by ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::ContextCurvilinear(), ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::correctPointSourceLocation(), ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::initUnknownsPatch(), and ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::~ContextCurvilinear().
max_dx
template<class Shortcuts , int basisSize, int numberOfData, typename T > double ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::max_dx
Definition at line 244 of file ContextCurvilinear.h.
Referenced by ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::ContextCurvilinear().
meshLevel
template<class Shortcuts , int basisSize, int numberOfData, typename T > const int ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::meshLevel protected
Definition at line 253 of file ContextCurvilinear.h.
Referenced by ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::initUnknownsPatch().
nodes
template<class Shortcuts , int basisSize, int numberOfData, typename T > double ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::nodes[basisSize] protected
Definition at line 249 of file ContextCurvilinear.h.
Referenced by ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::ContextCurvilinear(), and ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::initUnknownsPatch().
The documentation for this class was generated from the following file:
applications/exahype2/exaseis/ExaSeis_core/Curvilinear/ContextCurvilinear.h