Peano
riemannSolver Namespace Reference
Functions
void extract_tractions_and_particle_velocity (double *n, const double *Q, double &Tx, double &Ty, double &vx, double &vy)
void rotate_into_orthogonal_basis (double *n, double *m, double Tx, double Ty, double &Tn, double &Tm)
void rotate_into_physical_basis (double *n, double *m, double Fn, double Fm, double &Fx, double &Fy)
void generate_fluctuations_left (double z, double T, double T_hat, double v, double v_hat, double &F)
void generate_fluctuations_right (double z, double T, double T_hat, double v, double v_hat, double &F)
void riemannSolver_BC0 (double v, double sigma, double z, double r, double &v_hat, double &sigma_hat)
void riemannSolver_BCn (double v, double sigma, double z, double r, double &v_hat, double &sigma_hat)
void riemannSolver_boundary (int faceIndex, double r, double vn, double vm, double Tn, double Tm, double zp, double zs, double &vn_hat, double &vm_hat, double &Tn_hat, double &Tm_hat)
void riemannSolver_Nodal (double v_p, double v_m, double sigma_p, double sigma_m, double z_p, double z_m, double &v_hat_p, double &v_hat_m, double &sigma_hat_p, double &sigma_hat_m)
void localBasis (double *n, double *m)
void extractTransformation (const double *const Q, double &q_x, double &q_y, double &r_x, double &r_y)
void get_normals (int normalNonZeroIndex, double &norm, double *n, const double *Q)
void slip_weakening (double &v1, double &Vel, double &tau1, double phi_1, double eta, double tau_str, double sigma_n)
double boxcar (double &f, double x, double w)
void TauStrength (double &tau_str, double sigma_n, double S, double *x, double t)
void extract_tractions (double sxx, double syy, double sxy, double *n, double &Tx, double &Ty)
void initialstresstensor (double &sxx, double &syy, double &sxy, double *x)
void prestress (double &T0_n, double &T0_m, double *x, double t, double *m, double *n)
void SlipWeakeningFriction (double vn_p, double vn_m, double Tn_p, double Tn_m, double zn_p, double zn_m, double &vn_hat_p, double &vn_hat_m, double &Tn_hat_p, double &Tn_hat_m, double vm_p, double vm_m, double Tm_p, double Tm_m, double zm_p, double zm_m, double &vm_hat_p, double &vm_hat_m, double &Tm_hat_p, double &Tm_hat_m, double *m, double *n, double *x, double S)
Function Documentation
boxcar()
double riemannSolver::boxcar (double & f, double x, double w)
Definition at line 164 of file riemannSolver.h.
References std::abs(), and w.
Referenced by prestress(), and TauStrength().
extract_tractions()
void riemannSolver::extract_tractions (double sxx, double syy, double sxy, double * n, double & Tx, double & Ty)
Definition at line 219 of file riemannSolver.h.
Referenced by prestress().
extract_tractions_and_particle_velocity()
void riemannSolver::extract_tractions_and_particle_velocity (double * n, const double * Q, double & Tx, double & Ty, double & vx, double & vy)
Definition at line 3 of file riemannSolver.h.
extractTransformation()
void riemannSolver::extractTransformation (const double *const Q, double & q_x, double & q_y, double & r_x, double & r_y)
Definition at line 118 of file riemannSolver.h.
Referenced by get_normals().
generate_fluctuations_left()
void riemannSolver::generate_fluctuations_left (double z, double T, double T_hat, double v, double v_hat, double & F)
Definition at line 29 of file riemannSolver.h.
generate_fluctuations_right()
void riemannSolver::generate_fluctuations_right (double z, double T, double T_hat, double v, double v_hat, double & F)
Definition at line 33 of file riemannSolver.h.
get_normals()
void riemannSolver::get_normals (int normalNonZeroIndex, double & norm, double * n, const double * Q)
Definition at line 128 of file riemannSolver.h.
References extractTransformation().
initialstresstensor()
void riemannSolver::initialstresstensor (double & sxx, double & syy, double & sxy, double * x)
Definition at line 225 of file riemannSolver.h.
Referenced by prestress().
localBasis()
void riemannSolver::localBasis (double * n, double * m)
Definition at line 113 of file riemannSolver.h.
References m.
prestress()
void riemannSolver::prestress (double & T0_n, double & T0_m, double * x, double t, double * m, double * n)
Definition at line 245 of file riemannSolver.h.
References boxcar(), extract_tractions(), initialstresstensor(), m, and rotate_into_orthogonal_basis().
Referenced by SlipWeakeningFriction().
riemannSolver_BC0()
void riemannSolver::riemannSolver_BC0 (double v, double sigma, double z, double r, double & v_hat, double & sigma_hat)
Definition at line 37 of file riemannSolver.h.
References r.
Referenced by riemannSolver_boundary().
riemannSolver_BCn()
void riemannSolver::riemannSolver_BCn (double v, double sigma, double z, double r, double & v_hat, double & sigma_hat)
Definition at line 44 of file riemannSolver.h.
References r.
Referenced by riemannSolver_boundary().
riemannSolver_boundary()
void riemannSolver::riemannSolver_boundary (int faceIndex, double r, double vn, double vm, double Tn, double Tm, double zp, double zs, double & vn_hat, double & vm_hat, double & Tn_hat, double & Tm_hat)
Definition at line 51 of file riemannSolver.h.
References r, riemannSolver_BC0(), and riemannSolver_BCn().
riemannSolver_Nodal()
void riemannSolver::riemannSolver_Nodal (double v_p, double v_m, double sigma_p, double sigma_m, double z_p, double z_m, double & v_hat_p, double & v_hat_m, double & sigma_hat_p, double & sigma_hat_m)
Definition at line 70 of file riemannSolver.h.
rotate_into_orthogonal_basis()
void riemannSolver::rotate_into_orthogonal_basis (double * n, double * m, double Tx, double Ty, double & Tn, double & Tm)
Definition at line 17 of file riemannSolver.h.
References m.
Referenced by prestress().
rotate_into_physical_basis()
void riemannSolver::rotate_into_physical_basis (double * n, double * m, double Fn, double Fm, double & Fx, double & Fy)
Definition at line 22 of file riemannSolver.h.
References m.
slip_weakening()
void riemannSolver::slip_weakening (double & v1, double & Vel, double & tau1, double phi_1, double eta, double tau_str, double sigma_n)
Definition at line 148 of file riemannSolver.h.
References std::abs().
Referenced by SlipWeakeningFriction().
SlipWeakeningFriction()
void riemannSolver::SlipWeakeningFriction (double vn_p, double vn_m, double Tn_p, double Tn_m, double zn_p, double zn_m, double & vn_hat_p, double & vn_hat_m, double & Tn_hat_p, double & Tn_hat_m, double vm_p, double vm_m, double Tm_p, double Tm_m, double zm_p, double zm_m, double & vm_hat_p, double & vm_hat_m, double & Tm_hat_p, double & Tm_hat_m, double * m, double * n, double * x, double S)
continuity of normal velocity
continuity of normal stress
continuity of normal velocity
Definition at line 306 of file riemannSolver.h.
References m, prestress(), r, slip_weakening(), and TauStrength().
TauStrength()
void riemannSolver::TauStrength (double & tau_str, double sigma_n, double S, double * x, double t)
Definition at line 182 of file riemannSolver.h.
References boxcar().
Referenced by SlipWeakeningFriction().