var exahype2_2solvers_2rkfd_2actionsets_2ProjectPatchOntoFaces_8py =
[
    [ "exahype2.solvers.rkfd.actionsets.ProjectPatchOntoFaces.ProjectPatchOntoFaces", "dc/d9b/classexahype2_1_1solvers_1_1rkfd_1_1actionsets_1_1ProjectPatchOntoFaces_1_1ProjectPatchOntoFaces.html", "dc/d9b/classexahype2_1_1solvers_1_1rkfd_1_1actionsets_1_1ProjectPatchOntoFaces_1_1ProjectPatchOntoFaces" ]
];