Peano
exahype2::CellFaceData< inType, outType > Struct Template Reference
Represents the faces of one cell, with a total of 2*Dim faces per cell For ADER QIn will contain the values, QOut would contain the fluxes The faces can still each be made to contain either only the values for the given cell, or those and the neighbours' values.
#include <CellFaceData.h>
Public Member Functions
CellFaceData (inType *QIn_[2 *Dimensions], const tarch::la::Vector< Dimensions, double > &cellCentre_, const tarch::la::Vector< Dimensions, double > &cellSize_, double t_, double dt_, outType *QOut_[2 *Dimensions], tarch::MemoryLocation memoryLocation_=tarch::MemoryLocation::Heap, int targetDevice_=tarch::accelerator::Device::DefaultDevice)
Construct patch data object for one single cell.
CellFaceData (int numberOfCells_, tarch::MemoryLocation memoryLocation_=tarch::MemoryLocation::Heap, int targetDevice_=tarch::accelerator::Device::DefaultDevice)
CellFaceData (const CellFaceData &copy)=delete
CellFaceData & operator= (const CellFaceData &)=delete
~CellFaceData ()
std::string toString () const
Data Fields
inType *(* QIn)[2 *Dimensions]
QIn may not be const, as some kernels delete it straightaway once the input data has been handled.
tarch::la::Vector< Dimensions, double > * cellCentre
tarch::la::Vector< Dimensions, double > * cellSize
double * t
double * dt
int * id
Id of underlying task.
const int numberOfCells
As we store data as SoA, we have to know how big the actual arrays are.
const tarch::MemoryLocation memoryLocation
We might want to allocate data on the heap or an accelerator, therefore we save the target device id.
const int targetDevice
We might want to allocate data on an accelerator, therefore we save the target device id.
outType *(* QOut)[2 *Dimensions]
Out values.
Detailed Description
template<typename inType = double, typename outType = double>
struct exahype2::CellFaceData< inType, outType >
Represents the faces of one cell, with a total of 2*Dim faces per cell For ADER QIn will contain the values, QOut would contain the fluxes The faces can still each be made to contain either only the values for the given cell, or those and the neighbours' values.
Definition at line 21 of file CellFaceData.h.
Constructor & Destructor Documentation
CellFaceData() [1/3]
template<typename inType , typename outType > exahype2::CellFaceData< inType, outType >::CellFaceData (inType * QIn_[2 *Dimensions], const tarch::la::Vector< Dimensions, double > & cellCentre_, const tarch::la::Vector< Dimensions, double > & cellSize_, double t_, double dt_, outType * QOut_[2 *Dimensions], tarch::MemoryLocation memoryLocation_ = tarch::MemoryLocation::Heap, int targetDevice_ = tarch::accelerator::Device::DefaultDevice)
Construct patch data object for one single cell.
Usually, I do so only to be able to use the same kernels everywhere: Kernels accept CellFaceData, i.e. multiple patches. Even if we have only one cell, we thus wrap this cell's data into an instance of CellFaceData and pass it in. The id can be set to any dummy in this case, as we know which task has wrapped this single cell, i.e. we usually do not read it later.
Definition at line 100 of file CellFaceData.h.
References exahype2::CellFaceData< inType, outType >::cellCentre, exahype2::CellFaceData< inType, outType >::cellSize, exahype2::CellFaceData< inType, outType >::dt, exahype2::CellFaceData< inType, outType >::QIn, exahype2::CellFaceData< inType, outType >::QOut, and exahype2::CellFaceData< inType, outType >::t.
CellFaceData() [2/3]
template<typename inType , typename outType > exahype2::CellFaceData< inType, outType >::CellFaceData (int numberOfCells_, tarch::MemoryLocation memoryLocation_ = tarch::MemoryLocation::Heap, int targetDevice_ = tarch::accelerator::Device::DefaultDevice)
Definition at line 121 of file CellFaceData.h.
References tarch::accelerator::MemoryManager::allocate(), exahype2::CellFaceData< inType, outType >::cellCentre, exahype2::CellFaceData< inType, outType >::cellSize, exahype2::CellFaceData< inType, outType >::dt, tarch::accelerator::MemoryManager::getInstance(), exahype2::CellFaceData< inType, outType >::QIn, exahype2::CellFaceData< inType, outType >::QOut, and exahype2::CellFaceData< inType, outType >::t.
CellFaceData() [3/3]
template<typename inType = double, typename outType = double> exahype2::CellFaceData< inType, outType >::CellFaceData (const CellFaceData< inType, outType > & copy) delete
~CellFaceData()
template<typename inType , typename outType > exahype2::CellFaceData< inType, outType >::~CellFaceData ()
Definition at line 156 of file CellFaceData.h.
References cellSize, tarch::accelerator::MemoryManager::free(), tarch::accelerator::MemoryManager::getInstance(), and targetDevice.
Member Function Documentation
operator=()
template<typename inType = double, typename outType = double> CellFaceData & exahype2::CellFaceData< inType, outType >::operator= (const CellFaceData< inType, outType > &) delete
toString()
template<typename inType , typename outType > std::string exahype2::CellFaceData< inType, outType >::toString () const
Definition at line 174 of file CellFaceData.h.
References cellSize.
Field Documentation
cellCentre
template<typename inType = double, typename outType = double> tarch::la::Vector<Dimensions, double>* exahype2::CellFaceData< inType, outType >::cellCentre
Definition at line 27 of file CellFaceData.h.
Referenced by exahype2::CellFaceData< inType, outType >::CellFaceData(), exahype2::CellFaceData< inType, outType >::CellFaceData(), firstTask(), firstTask(), variant1::runBenchmarks(), variant2::runBenchmarks(), variant3::runBenchmarks(), and runKernels().
cellSize
template<typename inType = double, typename outType = double> tarch::la::Vector<Dimensions, double>* exahype2::CellFaceData< inType, outType >::cellSize
Definition at line 28 of file CellFaceData.h.
Referenced by exahype2::CellFaceData< inType, outType >::CellFaceData(), exahype2::CellFaceData< inType, outType >::CellFaceData(), firstTask(), firstTask(), variant1::runBenchmarks(), variant2::runBenchmarks(), variant3::runBenchmarks(), and runKernels().
dt
template<typename inType = double, typename outType = double> double* exahype2::CellFaceData< inType, outType >::dt
Definition at line 31 of file CellFaceData.h.
Referenced by exahype2::CellFaceData< inType, outType >::CellFaceData(), exahype2::CellFaceData< inType, outType >::CellFaceData(), firstTask(), firstTask(), variant1::runBenchmarks(), variant2::runBenchmarks(), variant3::runBenchmarks(), and runKernels().
id
template<typename inType = double, typename outType = double> int* exahype2::CellFaceData< inType, outType >::id
Id of underlying task.
Required when we fuse many enclave tasks and load them off to the GPU, as we have to know afterwards which outcome corresponds to which task.
Definition at line 38 of file CellFaceData.h.
memoryLocation
template<typename inType = double, typename outType = double> const tarch::MemoryLocation exahype2::CellFaceData< inType, outType >::memoryLocation
We might want to allocate data on the heap or an accelerator, therefore we save the target device id.
Definition at line 50 of file CellFaceData.h.
numberOfCells
template<typename inType = double, typename outType = double> const int exahype2::CellFaceData< inType, outType >::numberOfCells
As we store data as SoA, we have to know how big the actual arrays are.
Definition at line 44 of file CellFaceData.h.
QIn
template<typename inType = double, typename outType = double> inType*(* exahype2::CellFaceData< inType, outType >::QIn)[2 *Dimensions]
QIn may not be const, as some kernels delete it straightaway once the input data has been handled.
Definition at line 26 of file CellFaceData.h.
Referenced by exahype2::CellFaceData< inType, outType >::CellFaceData(), exahype2::CellFaceData< inType, outType >::CellFaceData(), firstTask(), firstTask(), initialTask(), variant1::runBenchmarks(), variant2::runBenchmarks(), variant3::runBenchmarks(), runKernels(), and secondTask().
QOut
template<typename inType = double, typename outType = double> outType*(* exahype2::CellFaceData< inType, outType >::QOut)[2 *Dimensions]
Out values.
Definition at line 61 of file CellFaceData.h.
Referenced by exahype2::CellFaceData< inType, outType >::CellFaceData(), exahype2::CellFaceData< inType, outType >::CellFaceData(), firstTask(), firstTask(), initialTask(), variant1::runBenchmarks(), variant2::runBenchmarks(), variant3::runBenchmarks(), runKernels(), and secondTask().
t
template<typename inType = double, typename outType = double> double* exahype2::CellFaceData< inType, outType >::t
Definition at line 30 of file CellFaceData.h.
Referenced by exahype2::CellFaceData< inType, outType >::CellFaceData(), exahype2::CellFaceData< inType, outType >::CellFaceData(), firstTask(), firstTask(), variant1::runBenchmarks(), variant2::runBenchmarks(), variant3::runBenchmarks(), and runKernels().
targetDevice
template<typename inType = double, typename outType = double> const int exahype2::CellFaceData< inType, outType >::targetDevice
We might want to allocate data on an accelerator, therefore we save the target device id.
Definition at line 56 of file CellFaceData.h.
The documentation for this struct was generated from the following file:
benchmarks/exahype2/kernel-benchmarks/aderdg-fused/CellFaceData.h