Peano
peano4::utils Namespace Reference
Namespaces
namespace tests
Typedefs
typedef std::bitset< Dimensions > LoopDirection
Is used by the z-loop.
Functions
GPUCallableMethod int dCmp (const tarch::la::Vector< Dimensions, int > &counter, int max)
Element-wise comparison for the for d-dimensional for loops.
GPUCallableMethod int dCmp (const tarch::la::Vector< Dimensions, int > &counter, const tarch::la::Vector< Dimensions, int > &max)
Element-wise comparison for the for d-dimensional for loops.
GPUCallableMethod bool dCmpLinearOrder (const tarch::la::Vector< Dimensions, int > &counter, const tarch::la::Vector< Dimensions, int > &max)
Compares two vectors with regards to their linearised value.
GPUCallableMethod void dDec (tarch::la::Vector< Dimensions, int > &counter, int max)
d-dimensional counterpart of decrement operator
GPUCallableMethod void dInc (tarch::la::Vector< Dimensions, int > &counter, int max)
d-dimensional counterpart of increment operator
GPUCallableMethod void dInc (tarch::la::Vector< Dimensions, int > &counter, const tarch::la::Vector< Dimensions, int > &max)
d-dimensional counterpart of increment, where individual vector components have different max values
GPUCallableMethod void dIncByVector (tarch::la::Vector< Dimensions, int > &counter, int max, int increment)
Perform a d-dimensional increment by value increment: The first component of the counter is incremented by increment.
GPUCallableMethod void dInc (tarch::la::Vector< Dimensions, int > &counter, int max, int doNotExamine)
Same operation as dInc(tarch::la::Vector<Dimensions,int>,int), but now one dimension is not taken into consideration.
GPUCallableMethod void dInc (tarch::la::Vector< Dimensions, int > &counter, int max, LoopDirection &direction)
Operation similar to dInc, but is given a direction bitset that identifies whether the counters has to be incremented or decremented.
GPUCallableMethod void dIncByScalar (tarch::la::Vector< Dimensions, int > &counter, int max, int increment)
Perform a scalar increment of a vector: The operation equals a sequence of increment calls to dInc().
GPUCallableMethod int getKeyForDLinearisedLookup (const tarch::la::Vector< Dimensions, int > &counter, int max)
GPUCallableMethod int getKeyForDDeLinearisedLookup (int value, int max)
GPUCallableMethod int dLinearised (const std::bitset< Dimensions > &counter)
Map d-dimensional vector onto integer index.
GPUCallableMethod int dLinearised (const tarch::la::Vector< Dimensions, int > &counter, int max)
GPUCallableMethod int dLinearisedWithoutLookup (const tarch::la::Vector< Dimensions, int > &counter, int max)
GPUCallableMethod int d2Linearised (const tarch::la::Vector< 2, int > &counter, int max)
Special 2d variant of dLinearised that works also if you compile with other dimensions.
GPUCallableMethod int d3Linearised (const tarch::la::Vector< 3, int > &counter, int max)
Special 3d variant of dLinearised that works also if you compile with other dimensions.
GPUCallableMethod tarch::la::Vector< Dimensions, int > dDelinearised (int value, int max)
Counterpart of dLinearised().
GPUCallableMethod tarch::la::Vector< Dimensions, int > dDelinearisedWithoutLookup (int value, int max)
void setupLookupTableForDLinearised ()
void setupLookupTableForDDelinearised ()
GPUCallableMethod tarch::la::Vector< Dimensions, int > dStartVector ()
Construct start vector (0,0,....) for d-dimensional loop.
GPUCallableMethod tarch::la::Vector< Dimensions, int > dStartVector (int dim, int value)
GPUCallableMethod tarch::la::Vector< Dimensions, int > dStartVector (int max, const LoopDirection &direction)
Creates a start vector.
Variables
constexpr int MaxIndexOfLinearisation = BasePowerExponent<MaxTable, Dimensions>::value
int lookupTableDLinearised [MaxIndexOfLinearisation *(MaxTable - 1)]
tarch::la::Vector< Dimensions, int > lookupTableDDeLinearised [MaxIndexOfLinearisation *(MaxTable - 1)]
Typedef Documentation
LoopDirection
typedef std::bitset<Dimensions> peano4::utils::LoopDirection
Is used by the z-loop.
See macro dforz.
Definition at line 12 of file LoopDirection.h.
Function Documentation
d2Linearised()
GPUCallableMethod int peano4::utils::d2Linearised (const tarch::la::Vector< 2, int > & counter, int max)
Special 2d variant of dLinearised that works also if you compile with other dimensions.
Definition at line 84 of file Linearised.cpph.
References assertion2, and assertion3.
Referenced by toolbox::finiteelements::BSplinesStencilFactory::getElementWiseAssemblyMatrix().
d3Linearised()
GPUCallableMethod int peano4::utils::d3Linearised (const tarch::la::Vector< 3, int > & counter, int max)
Special 3d variant of dLinearised that works also if you compile with other dimensions.
Definition at line 100 of file Linearised.cpph.
References assertion2.
Referenced by toolbox::finiteelements::BSplinesStencilFactory::getElementWiseAssemblyMatrix().
dCmp() [1/2]
GPUCallableMethod int peano4::utils::dCmp (const tarch::la::Vector< Dimensions, int > & counter, const tarch::la::Vector< Dimensions, int > & max)
Element-wise comparison for the for d-dimensional for loops.
Element-wise comparison for the loops. Different to the other dCmp() operation, this one works fine even if the max range per vector entry is different.
Returns
true if all entries of counter are smaller than their corresponding entries in max
Definition at line 4 of file Compare.cpph.
References assertion2.
dCmp() [2/2]
GPUCallableMethod int peano4::utils::dCmp (const tarch::la::Vector< Dimensions, int > & counter, int max)
Element-wise comparison for the for d-dimensional for loops.
Returns
true if all entries of counter are smaller max
Definition at line 19 of file Compare.cpph.
References assertion2.
dCmpLinearOrder()
GPUCallableMethod bool peano4::utils::dCmpLinearOrder (const tarch::la::Vector< Dimensions, int > & counter, const tarch::la::Vector< Dimensions, int > & max)
Compares two vectors with regards to their linearised value.
Returns
true, if dLinearised(counter, XXX) < dLinearised(max, XXX)
Definition at line 31 of file Compare.cpph.
dDec()
GPUCallableMethod void peano4::utils::dDec (tarch::la::Vector< Dimensions, int > & counter, int max)
d-dimensional counterpart of decrement operator
This operation performs a d-dimensional decrement on a given integer vector: The first component of the vector is decremented. If the first component is smaller than 0, the component is set to max and the next component is decremented by one.
Definition at line 4 of file Decrement.cpph.
References assertion.
dDelinearised()
GPUCallableMethod tarch::la::Vector< Dimensions, int > peano4::utils::dDelinearised (int value, int max)
Counterpart of dLinearised().
Definition at line 116 of file Linearised.cpph.
References assertionEquals2, dDelinearisedWithoutLookup(), getKeyForDDeLinearisedLookup(), lookupTableDDeLinearised, and MaxTable.
Referenced by toolbox::finiteelements::mapElementMatrixEntryOntoStencilEntry().
dDelinearisedWithoutLookup()
GPUCallableMethod tarch::la::Vector< Dimensions, int > peano4::utils::dDelinearisedWithoutLookup (int value, int max)
Definition at line 138 of file Linearised.cpph.
References tarch::la::aPowI(), and assertion2.
Referenced by dDelinearised(), setupLookupTableForDDelinearised(), peano4::utils::tests::LinearisedTest::testDelinearisedVector(), peano4::utils::tests::LinearisedTest::testDelinearisedWithoutLookup(), peano4::utils::tests::LinearisedTest::testLinearisedVectorRoundTripWithoutLookup(), and peano4::utils::tests::LinearisedTest::testLookupTableDelinearised().
dInc() [1/4]
GPUCallableMethod void peano4::utils::dInc (tarch::la::Vector< Dimensions, int > & counter, const tarch::la::Vector< Dimensions, int > & max)
d-dimensional counterpart of increment, where individual vector components have different max values
This operation performs a d-dimensional increment on a given integer vector: The first component of the vector is incremented. If the first component is greater than max(0)-1, the component is set zero and the next component is incremented by one. This operation is used often by d-dimensional for-loops.
Definition at line 14 of file Increment.cpph.
dInc() [2/4]
GPUCallableMethod void peano4::utils::dInc (tarch::la::Vector< Dimensions, int > & counter, int max)
d-dimensional counterpart of increment operator
This operation performs a d-dimensional increment on a given integer vector: The first component of the vector is incremented. If the first component is greater than max-1, the component is set zero and the next component is incremented by one. This operation is used often by d-dimensional for-loops.
Definition at line 4 of file Increment.cpph.
dInc() [3/4]
GPUCallableMethod void peano4::utils::dInc (tarch::la::Vector< Dimensions, int > & counter, int max, int doNotExamine)
Same operation as dInc(tarch::la::Vector<Dimensions,int>,int), but now one dimension is not taken into consideration.
Definition at line 29 of file Increment.cpph.
References assertion.
dInc() [4/4]
GPUCallableMethod void peano4::utils::dInc (tarch::la::Vector< Dimensions, int > & counter, int max, LoopDirection & direction)
Operation similar to dInc, but is given a direction bitset that identifies whether the counters has to be incremented or decremented.
See the dforz macro for an example how to use dInc.
Definition at line 57 of file Increment.cpph.
dIncByScalar()
GPUCallableMethod void peano4::utils::dIncByScalar (tarch::la::Vector< Dimensions, int > & counter, int max, int increment)
Perform a scalar increment of a vector: The operation equals a sequence of increment calls to dInc().
Definition at line 99 of file Increment.cpph.
dIncByVector()
GPUCallableMethod void peano4::utils::dIncByVector (tarch::la::Vector< Dimensions, int > & counter, int max, int increment)
Perform a d-dimensional increment by value increment: The first component of the counter is incremented by increment.
Afterwards, the operation checks the first entry: If it exceeds max, its module value is set, the next component is incremented by increment, and the check continues.
Definition at line 86 of file Increment.cpph.
dLinearised() [1/2]
GPUCallableMethod int peano4::utils::dLinearised (const std::bitset< Dimensions > & counter)
Map d-dimensional vector onto integer index.
This operation is called pretty often and, thus, might cause a significant slowdown in the overall performance. Therefore, I introduced a aggressive optimisation based on lookup tables. This optimisation is switched on if DLINEAR_USE_LOOKUP is defined.
Returns
the linearisation of the counter, i.e. the k-th component is multiplied by max^k and the results are accumulated.
Definition at line 34 of file Linearised.cpph.
Referenced by exahype2::fd::tests::CCZ4KernelTest::AppleWithAppleTest(), peano4::datamanagement::VertexMarker::areAdjacentCellsLocal(), toolbox::blockstructured::computeGradient(), toolbox::blockstructured::computeGradientAndReturnMaxDifference(), exahype2::dg::internal::copySolution(), peano4::grid::GridTraversalEventGenerator::createGenericCellTraversalEvent(), toolbox::blockstructured::internal::createPiecewiseConstantInterpolationMatrix(), peano4::grid::Spacetree::descend(), exahype2::dg::evaluatePolynomial(), toolbox::finiteelements::extractElementStencil(), toolbox::blockstructured::extrapolatePatchSolutionAndProjectExtrapolatedHaloOntoFaces(), peano4::grid::GridTraversalEventGenerator::getAdjacentRanksOfFace(), toolbox::finiteelements::getElementWiseAssemblyMatrix(), toolbox::finiteelements::getElementWiseAssemblyMatrix(), toolbox::finiteelements::getElementWiseAssemblyMatrix(), toolbox::finiteelements::getElementWiseAssemblyMatrix(), peano4::parallel::Node::getOutputStackForPeriodicBoundaryExchange(), peano4::parallel::Node::getPeriodicBoundaryNumber(), swift2::getVertexNumbersOfParentVertices(), peano4::grid::GridTraversalEventGenerator::getVertexType(), toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_fourthOrder(), toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_linear(), toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_secondOrder(), peano4::grid::Spacetree::loadVertices(), exahype2::fv::plotPatch(), toolbox::finiteelements::preprocessBoundaryStencil(), toolbox::blockstructured::internal::projectInterpolatedFineCellsOnHaloLayer_AoS(), toolbox::blockstructured::projectPatchHaloOntoFaces(), toolbox::blockstructured::projectPatchSolutionOntoFaces(), exahype2::fv::internal::projectValueOntoParticle_piecewiseConstant(), exahype2::fv::internal::projectValueOntoParticle_piecewiseLinear(), mghype::matrixfree::solvers::cgmultigrid::prolongate(), peano4::grid::Spacetree::refineState(), toolbox::blockstructured::restrictCell_AoS_averaging(), toolbox::blockstructured::restrictCell_AoS_inject(), toolbox::blockstructured::restrictCellIntoOverlappingCell_inject(), toolbox::blockstructured::restrictCellIntoOverlappingCell_inject_and_average(), mghype::matrixfree::solvers::cgmultigrid::restrictToNextLevel(), exahype2::dg::tests::CellIntegralTest::runEulerOrder2OnStationarySetup(), peano4::grid::Spacetree::shouldEraseAdjacencyInformation(), peano4::grid::Spacetree::storeVertices(), exahype2::fv::tests::CopyPatchTest::testCopyPatch(), peano4::utils::tests::LinearisedTest::testLinearisedBitset(), peano4::utils::tests::LinearisedTest::testLinearisedVector(), peano4::grid::Spacetree::traverse(), and exahype2::fv::validatePatch().
dLinearised() [2/2]
GPUCallableMethod int peano4::utils::dLinearised (const tarch::la::Vector< Dimensions, int > & counter, int max)
Definition at line 44 of file Linearised.cpph.
References assertionEquals3, dLinearisedWithoutLookup(), getKeyForDLinearisedLookup(), lookupTableDLinearised, and MaxTable.
dLinearisedWithoutLookup()
GPUCallableMethod int peano4::utils::dLinearisedWithoutLookup (const tarch::la::Vector< Dimensions, int > & counter, int max)
Definition at line 65 of file Linearised.cpph.
References assertion2.
Referenced by dLinearised(), setupLookupTableForDLinearised(), peano4::utils::tests::LinearisedTest::testDelinearisedWithoutLookup(), peano4::utils::tests::LinearisedTest::testLinearisedVectorRoundTripWithoutLookup(), peano4::utils::tests::LinearisedTest::testLinearisedVectorWithoutLookup(), and peano4::utils::tests::LinearisedTest::testLookupTableLinearised().
dStartVector() [1/3]
GPUCallableMethod tarch::la::Vector< Dimensions, int > peano4::utils::dStartVector ()
Construct start vector (0,0,....) for d-dimensional loop.
Returns
a vector containing zero values only.
Definition at line 4 of file Loop.cpph.
dStartVector() [2/3]
GPUCallableMethod tarch::la::Vector< Dimensions, int > peano4::utils::dStartVector (int dim, int value)
Returns
a vector containing only zero values besides the dim-th entry. This entry is set value.
Definition at line 9 of file Loop.cpph.
References assertion2.
dStartVector() [3/3]
GPUCallableMethod tarch::la::Vector< Dimensions, int > peano4::utils::dStartVector (int max, const LoopDirection & direction)
Creates a start vector.
Each component is set either 0 or max-1 depending on direction: If direction is true, then the value 0 is zero.
Returns
a start vector for an oscillating loop.
Definition at line 20 of file Loop.cpph.
References assertion2.
getKeyForDDeLinearisedLookup()
GPUCallableMethod int peano4::utils::getKeyForDDeLinearisedLookup (int value, int max)
Definition at line 25 of file Linearised.cpph.
References tarch::la::aPowI(), assertion1, assertion2, MaxIndexOfLinearisation, and MaxTable.
Referenced by dDelinearised(), setupLookupTableForDDelinearised(), and peano4::utils::tests::LinearisedTest::testLookupTableDelinearised().
getKeyForDLinearisedLookup()
GPUCallableMethod int peano4::utils::getKeyForDLinearisedLookup (const tarch::la::Vector< Dimensions, int > & counter, int max)
Definition at line 4 of file Linearised.cpph.
References assertion2, assertionEquals, MaxIndexOfLinearisation, and MaxTable.
Referenced by dLinearised(), setupLookupTableForDLinearised(), peano4::utils::tests::LinearisedTest::testKeyComputationForLinearisedLookup(), and peano4::utils::tests::LinearisedTest::testLookupTableLinearised().
setupLookupTableForDDelinearised()
void peano4::utils::setupLookupTableForDDelinearised ()
Definition at line 16 of file Linearised.cpp.
References tarch::la::aPowI(), assertion3, dDelinearisedWithoutLookup(), getKeyForDDeLinearisedLookup(), lookupTableDDeLinearised, MaxIndexOfLinearisation, and MaxTable.
Referenced by peano4::init().
setupLookupTableForDLinearised()
void peano4::utils::setupLookupTableForDLinearised ()
Definition at line 10 of file Linearised.cpp.
References dfor, dLinearisedWithoutLookup(), getKeyForDLinearisedLookup(), lookupTableDLinearised, and MaxTable.
Referenced by peano4::init().
Variable Documentation
lookupTableDDeLinearised
tarch::la::Vector< Dimensions, int > peano4::utils::lookupTableDDeLinearised extern
Definition at line 8 of file Linearised.cpp.
Referenced by dDelinearised(), setupLookupTableForDDelinearised(), and peano4::utils::tests::LinearisedTest::testLookupTableDelinearised().
lookupTableDLinearised
int peano4::utils::lookupTableDLinearised extern
Definition at line 7 of file Linearised.cpp.
Referenced by dLinearised(), setupLookupTableForDLinearised(), and peano4::utils::tests::LinearisedTest::testLookupTableLinearised().
MaxIndexOfLinearisation
constexpr int peano4::utils::MaxIndexOfLinearisation = BasePowerExponent<MaxTable, Dimensions>::value constexpr
Definition at line 22 of file Linearised.h.
Referenced by getKeyForDDeLinearisedLookup(), getKeyForDLinearisedLookup(), setupLookupTableForDDelinearised(), and peano4::utils::tests::LinearisedTest::testKeyComputationForLinearisedLookup().