Peano
DefaultSequence.template.cpp File Reference
#include "{{MAIN_NAME}}.h"
#include "tarch/logging/Log.h"
#include "tarch/logging/LogFilter.h"
#include "tarch/multicore/multicore.h"
#include "peano4/peano4.h"
#include "peano4/grid/Spacetree.h"
#include "peano4/parallel/SpacetreeSet.h"
#include "{{subdirectory}}Constants.h"
#include "{{subdirectory}}repositories/DataRepository.h"
#include "{{subdirectory}}repositories/StepRepository.h"
#include "Constants.h"
#include "repositories/DataRepository.h"
#include "repositories/StepRepository.h"
#include <fenv.h>
Functions
int main (int argc, char **argv)
Main routine of the SPH code.
Function Documentation
main()
int main (int argc, char ** argv)
Main routine of the SPH code.
Definition at line 33 of file DefaultSequence.template.cpp.
References tarch::logging::LogFilter::addFilterListEntry(), tarch::logging::LogFilter::FilterListEntry::AlwaysOn, tarch::logging::LogFilter::FilterListEntry::AnyRank, tarch::logging::LogFilter::FilterListEntry::BlackListEntry, peano4::parallel::Node::getInstance(), tarch::logging::LogFilter::getInstance(), tarch::mpi::Rank::getInstance(), peano4::init(), logDebug, peano4::shutdown(), tarch::logging::LogFilter::FilterListEntry::TargetDebug, tarch::logging::LogFilter::FilterListEntry::TargetInfo, tarch::logging::LogFilter::FilterListEntry::TargetTrace, and tarch::logging::LogFilter::FilterListEntry::WhiteListEntry.