Peano
tarch::multicore::RecursiveLock Class Reference
Create a lock around a boolean semaphore region.
#include <RecursiveLock.h>
Public Member Functions
RecursiveLock (tarch::multicore::RecursiveSemaphore &semaphore, bool aquireLockImmediately=true)
~RecursiveLock ()
bool tryLock ()
bool isLocked () const
void lock ()
void free ()
Private Attributes
RecursiveSemaphore & _semaphore
bool _lockIsAquired
Detailed Description
Create a lock around a boolean semaphore region.
See also
tarch::multicore::BooleanSemaphore
Definition at line 17 of file RecursiveLock.h.
Constructor & Destructor Documentation
RecursiveLock()
tarch::multicore::RecursiveLock::RecursiveLock (tarch::multicore::RecursiveSemaphore & semaphore, bool aquireLockImmediately = true)
Definition at line 6 of file RecursiveLock.cpp.
References lock().
~RecursiveLock()
tarch::multicore::RecursiveLock::~RecursiveLock ()
Definition at line 15 of file RecursiveLock.cpp.
Member Function Documentation
free()
void tarch::multicore::RecursiveLock::free ()
Definition at line 44 of file RecursiveLock.cpp.
References assertion.
isLocked()
bool tarch::multicore::RecursiveLock::isLocked () const
Definition at line 32 of file RecursiveLock.cpp.
lock()
void tarch::multicore::RecursiveLock::lock ()
Definition at line 37 of file RecursiveLock.cpp.
References assertion.
Referenced by RecursiveLock().
tryLock()
bool tarch::multicore::RecursiveLock::tryLock ()
Definition at line 22 of file RecursiveLock.cpp.
References assertion.
Referenced by tarch::services::ServiceRepository::receiveDanglingMessages().
Field Documentation
_lockIsAquired
bool tarch::multicore::RecursiveLock::_lockIsAquired private
Definition at line 20 of file RecursiveLock.h.
_semaphore
RecursiveSemaphore& tarch::multicore::RecursiveLock::_semaphore private
Definition at line 19 of file RecursiveLock.h.
The documentation for this class was generated from the following files:
src/tarch/multicore/RecursiveLock.h
src/tarch/multicore/RecursiveLock.cpp