Peano
exahype2::tests::EnclaveBookkeepingTest Class Reference final
#include <EnclaveBookkeepingTest.h>
Public Member Functions
EnclaveBookkeepingTest ()
~EnclaveBookkeepingTest () override final=default
void run () override final
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testFusePendingTasks ()
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Definition at line 11 of file EnclaveBookkeepingTest.h.
Constructor & Destructor Documentation
EnclaveBookkeepingTest()
exahype2::tests::EnclaveBookkeepingTest::EnclaveBookkeepingTest ()
Definition at line 33 of file EnclaveBookkeepingTest.cpp.
~EnclaveBookkeepingTest()
exahype2::tests::EnclaveBookkeepingTest::~EnclaveBookkeepingTest () final override default
Member Function Documentation
run()
void exahype2::tests::EnclaveBookkeepingTest::run () final override virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 36 of file EnclaveBookkeepingTest.cpp.
References testMethod.
testFusePendingTasks()
void exahype2::tests::EnclaveBookkeepingTest::testFusePendingTasks () private
Definition at line 50 of file EnclaveBookkeepingTest.cpp.
References exahype2::EnclaveBookkeeping::bookmarkTask(), exahype2::EnclaveBookkeeping::fusePendingTasks(), exahype2::EnclaveBookkeeping::getInstance(), numberOfTasksThatHaveBeenExecuted, NumberOfTasksToExecute, and validateEquals.
The documentation for this class was generated from the following files:
src/exahype2/tests/EnclaveBookkeepingTest.h
src/exahype2/tests/EnclaveBookkeepingTest.cpp