Peano
peano4::grid::AutomatonState Struct Reference
#include <AutomatonState.h>
Public Types
enum ObjectConstruction { NoData }
Public Member Functions
AutomatonState ()=default
AutomatonState (const int __level, const tarch::la::Vector< Dimensions, double > &__x, const tarch::la::Vector< Dimensions, double > &__h, const bool __inverted, const std::bitset< Dimensions > &__evenFlags, const tarch::la::Vector< DimensionsTimesTwo, int > &__accessNumber)
AutomatonState (const AutomatonState &copy)
AutomatonState & operator= (const AutomatonState &other)
~AutomatonState ()=default
AutomatonState (ObjectConstruction)
int getLevel () const
void setLevel (int value)
tarch::la::Vector< Dimensions, double > getX () const
void setX (const tarch::la::Vector< Dimensions, double > &value)
double getX (int index) const
void setX (int index, double value)
tarch::la::Vector< Dimensions, double > getH () const
void setH (const tarch::la::Vector< Dimensions, double > &value)
double getH (int index) const
void setH (int index, double value)
bool getInverted () const
void setInverted (bool value)
std::bitset< Dimensions > getEvenFlags () const
void setEvenFlags (const std::bitset< Dimensions > &value)
bool getEvenFlags (int index) const
void setEvenFlags (int index, bool value)
void flipEvenFlags (int index)
tarch::la::Vector< DimensionsTimesTwo, int > getAccessNumber () const
void setAccessNumber (const tarch::la::Vector< DimensionsTimesTwo, int > &value)
int getAccessNumber (int index) const
void setAccessNumber (int index, int value)
int getSenderRank () const
std::string toString () const
Static Public Member Functions
static MPI_Datatype getForkDatatype ()
Hands out MPI datatype if we work without the LLVM MPI extension.
static MPI_Datatype getJoinDatatype ()
static MPI_Datatype getBoundaryExchangeDatatype ()
static MPI_Datatype getMultiscaleDataExchangeDatatype ()
static MPI_Datatype getGlobalCommunciationDatatype ()
static void freeForkDatatype ()
static void freeJoinDatatype ()
static void freeBoundaryExchangeDatatype ()
static void freeMultiscaleDataExchangeDatatype ()
static void freeGlobalCommunciationDatatype ()
static void initDatatype ()
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
static void shutdownDatatype ()
Free the underlying MPI datatype.
static void send (const peano4::grid::AutomatonState &buffer, int destination, int tag, MPI_Comm communicator)
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
static void receive (peano4::grid::AutomatonState &buffer, int source, int tag, MPI_Comm communicator)
static void send (const peano4::grid::AutomatonState &buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
static void receive (peano4::grid::AutomatonState &buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
static void sendAndPollDanglingMessages (const peano4::grid::AutomatonState &message, int destination, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
static void receiveAndPollDanglingMessages (peano4::grid::AutomatonState &message, int source, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
Private Attributes
int _level
tarch::la::Vector< Dimensions, double > _x
tarch::la::Vector< Dimensions, double > _h
bool _inverted
std::bitset< Dimensions > _evenFlags
tarch::la::Vector< DimensionsTimesTwo, int > _accessNumber
int _senderDestinationRank
Static Private Attributes
static MPI_Datatype Datatype = MPI_DATATYPE_NULL
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
Detailed Description
Definition at line 25 of file AutomatonState.h.
Member Enumeration Documentation
ObjectConstruction
enum peano4::grid::AutomatonState::ObjectConstruction
Enumerator
NoData
Definition at line 42 of file AutomatonState.h.
Constructor & Destructor Documentation
AutomatonState() [1/4]
peano4::grid::AutomatonState::AutomatonState () default
AutomatonState() [2/4]
peano4::grid::AutomatonState::AutomatonState (const int __level, const tarch::la::Vector< Dimensions, double > & __x, const tarch::la::Vector< Dimensions, double > & __h, const bool __inverted, const std::bitset< Dimensions > & __evenFlags, const tarch::la::Vector< DimensionsTimesTwo, int > & __accessNumber)
Definition at line 8 of file AutomatonState.cpp.
References setAccessNumber(), setEvenFlags(), setH(), setInverted(), setLevel(), and setX().
AutomatonState() [3/4]
peano4::grid::AutomatonState::AutomatonState (const AutomatonState & copy)
Definition at line 24 of file AutomatonState.cpp.
References setEvenFlags(), setH(), setInverted(), setLevel(), and setX().
~AutomatonState()
peano4::grid::AutomatonState::~AutomatonState () default
AutomatonState() [4/4]
peano4::grid::AutomatonState::AutomatonState (ObjectConstruction)
Definition at line 44 of file AutomatonState.h.
Member Function Documentation
flipEvenFlags()
void peano4::grid::AutomatonState::flipEvenFlags (int index)
Definition at line 67 of file AutomatonState.h.
References _evenFlags.
Referenced by peano4::grid::PeanoCurve::invertEvenFlag().
freeBoundaryExchangeDatatype()
void peano4::grid::AutomatonState::freeBoundaryExchangeDatatype () static
Definition at line 99 of file AutomatonState.cpp.
freeForkDatatype()
void peano4::grid::AutomatonState::freeForkDatatype () static
Definition at line 78 of file AutomatonState.cpp.
freeGlobalCommunciationDatatype()
void peano4::grid::AutomatonState::freeGlobalCommunciationDatatype () static
Definition at line 85 of file AutomatonState.cpp.
freeJoinDatatype()
void peano4::grid::AutomatonState::freeJoinDatatype () static
Definition at line 92 of file AutomatonState.cpp.
freeMultiscaleDataExchangeDatatype()
void peano4::grid::AutomatonState::freeMultiscaleDataExchangeDatatype () static
Definition at line 106 of file AutomatonState.cpp.
getAccessNumber() [1/2]
tarch::la::Vector< DimensionsTimesTwo, int > peano4::grid::AutomatonState::getAccessNumber () const
Definition at line 69 of file AutomatonState.h.
References _accessNumber.
Referenced by peano4::grid::PeanoCurve::getFaceReadStackNumber(), peano4::grid::PeanoCurve::getFaceWriteStackNumber(), peano4::grid::PeanoCurve::getVertexReadStackNumber(), peano4::grid::PeanoCurve::getVertexWriteStackNumber(), operator=(), peano4::grid::PeanoCurve::removeFaceAccessNumber(), and peano4::grid::PeanoCurve::setFaceAccessNumber().
getAccessNumber() [2/2]
int peano4::grid::AutomatonState::getAccessNumber (int index) const
Definition at line 71 of file AutomatonState.h.
References _accessNumber.
getBoundaryExchangeDatatype()
MPI_Datatype peano4::grid::AutomatonState::getBoundaryExchangeDatatype () static
Definition at line 75 of file AutomatonState.cpp.
getEvenFlags() [1/2]
std::bitset< Dimensions > peano4::grid::AutomatonState::getEvenFlags () const
Definition at line 63 of file AutomatonState.h.
References _evenFlags.
Referenced by peano4::grid::PeanoCurve::getFaceNumberAlongCurve(), peano4::grid::PeanoCurve::getFaceReadStackNumber(), peano4::grid::PeanoCurve::getFaceWriteStackNumber(), peano4::grid::PeanoCurve::getFirstVertexIndex(), peano4::grid::PeanoCurve::getVertexReadStackNumber(), peano4::grid::PeanoCurve::getVertexWriteStackNumber(), and operator=().
getEvenFlags() [2/2]
bool peano4::grid::AutomatonState::getEvenFlags (int index) const
Definition at line 65 of file AutomatonState.h.
References _evenFlags.
getForkDatatype()
MPI_Datatype peano4::grid::AutomatonState::getForkDatatype () static
Hands out MPI datatype if we work without the LLVM MPI extension.
If we work with this additional feature, this is the routine where the lazy initialisation is done and the datatype is also cached.
Definition at line 72 of file AutomatonState.cpp.
getGlobalCommunciationDatatype()
MPI_Datatype peano4::grid::AutomatonState::getGlobalCommunciationDatatype () static
Definition at line 73 of file AutomatonState.cpp.
getH() [1/2]
tarch::la::Vector< Dimensions, double > peano4::grid::AutomatonState::getH () const
Definition at line 55 of file AutomatonState.h.
References _h.
Referenced by peano4::grid::GridTraversalEventGenerator::createGenericCellTraversalEvent(), peano4::grid::Spacetree::descend(), peano4::grid::Spacetree::evaluateGridControlEvents(), peano4::grid::Spacetree::loadVertices(), operator=(), and peano4::grid::Spacetree::refineState().
getH() [2/2]
double peano4::grid::AutomatonState::getH (int index) const
Definition at line 57 of file AutomatonState.h.
References _h.
getInverted()
bool peano4::grid::AutomatonState::getInverted () const
Definition at line 60 of file AutomatonState.h.
References _inverted.
Referenced by peano4::grid::PeanoCurve::getFaceNumberAlongCurve(), peano4::grid::PeanoCurve::getFaceReadStackNumber(), peano4::grid::PeanoCurve::getFaceWriteStackNumber(), peano4::grid::PeanoCurve::getFirstVertexIndex(), peano4::grid::PeanoCurve::getInputStackNumber(), peano4::grid::PeanoCurve::getOutputStackNumber(), and operator=().
getJoinDatatype()
MPI_Datatype peano4::grid::AutomatonState::getJoinDatatype () static
Definition at line 74 of file AutomatonState.cpp.
getLevel()
int peano4::grid::AutomatonState::getLevel () const
Definition at line 47 of file AutomatonState.h.
References _level.
Referenced by peano4::grid::GridTraversalEventGenerator::createGenericCellTraversalEvent(), peano4::grid::Spacetree::loadVertices(), operator=(), and peano4::grid::Spacetree::refineState().
getMultiscaleDataExchangeDatatype()
MPI_Datatype peano4::grid::AutomatonState::getMultiscaleDataExchangeDatatype () static
Definition at line 76 of file AutomatonState.cpp.
getSenderRank()
int peano4::grid::AutomatonState::getSenderRank () const
Returns
The rank of the sender of an object. It only make ssense to call this routine after you've invoked receive with MPI_ANY_SOURCE.
Definition at line 113 of file AutomatonState.cpp.
getX() [1/2]
tarch::la::Vector< Dimensions, double > peano4::grid::AutomatonState::getX () const
Definition at line 50 of file AutomatonState.h.
References _x.
Referenced by peano4::grid::GridTraversalEventGenerator::createGenericCellTraversalEvent(), peano4::grid::Spacetree::loadVertices(), operator=(), and peano4::grid::Spacetree::refineState().
getX() [2/2]
double peano4::grid::AutomatonState::getX (int index) const
Definition at line 52 of file AutomatonState.h.
References _x.
initDatatype()
void peano4::grid::AutomatonState::initDatatype () static
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
Definition at line 115 of file AutomatonState.cpp.
References DimensionsTimesTwo.
Referenced by peano4::parallel::Node::initMPIDatatypes().
operator=()
peano4::grid::AutomatonState & peano4::grid::AutomatonState::operator= (const AutomatonState & other)
Definition at line 33 of file AutomatonState.cpp.
References getAccessNumber(), getEvenFlags(), getH(), getInverted(), getLevel(), getX(), setEvenFlags(), setH(), setInverted(), setLevel(), and setX().
receive() [1/2]
void peano4::grid::AutomatonState::receive (peano4::grid::AutomatonState & buffer, int source, int tag, MPI_Comm communicator) static
Definition at line 217 of file AutomatonState.cpp.
References _senderDestinationRank.
Referenced by peano4::parallel::SpacetreeSet::answerQuestions(), and receiveAndPollDanglingMessages().
receive() [2/2]
void peano4::grid::AutomatonState::receive (peano4::grid::AutomatonState & buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Definition at line 243 of file AutomatonState.cpp.
References _senderDestinationRank.
receiveAndPollDanglingMessages()
void peano4::grid::AutomatonState::receiveAndPollDanglingMessages (peano4::grid::AutomatonState & message, int source, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 291 of file AutomatonState.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), receive(), tarch::services::ServiceRepository::receiveDanglingMessages(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
send() [1/2]
void peano4::grid::AutomatonState::send (const peano4::grid::AutomatonState & buffer, int destination, int tag, MPI_Comm communicator) static
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
However, this did not work with newer C++11 versions, as a member function using this as pointer usually doesn't see the vtable while the init sees the object from outside, i.e. including a vtable. So this routine now is basically an alias for a blocking MPI_Send.
Definition at line 212 of file AutomatonState.cpp.
Referenced by peano4::parallel::SpacetreeSet::addSpacetree(), and sendAndPollDanglingMessages().
send() [2/2]
void peano4::grid::AutomatonState::send (const peano4::grid::AutomatonState & buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
In systems with heavy MPI usage, this can help to avoid deadlocks.
Definition at line 224 of file AutomatonState.cpp.
sendAndPollDanglingMessages()
void peano4::grid::AutomatonState::sendAndPollDanglingMessages (const peano4::grid::AutomatonState & message, int destination, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 266 of file AutomatonState.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), tarch::services::ServiceRepository::receiveDanglingMessages(), send(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
setAccessNumber() [1/2]
void peano4::grid::AutomatonState::setAccessNumber (const tarch::la::Vector< DimensionsTimesTwo, int > & value)
Definition at line 70 of file AutomatonState.h.
References _accessNumber.
Referenced by AutomatonState(), peano4::grid::PeanoCurve::removeFaceAccessNumber(), peano4::grid::PeanoCurve::setFaceAccessNumber(), peano4::grid::Spacetree::Spacetree(), and peano4::grid::Spacetree::Spacetree().
setAccessNumber() [2/2]
void peano4::grid::AutomatonState::setAccessNumber (int index, int value)
Definition at line 72 of file AutomatonState.h.
References _accessNumber.
setEvenFlags() [1/2]
void peano4::grid::AutomatonState::setEvenFlags (const std::bitset< Dimensions > & value)
Definition at line 64 of file AutomatonState.h.
References _evenFlags.
Referenced by AutomatonState(), peano4::grid::Spacetree::Spacetree(), and peano4::grid::Spacetree::Spacetree().
setEvenFlags() [2/2]
void peano4::grid::AutomatonState::setEvenFlags (int index, bool value)
Definition at line 66 of file AutomatonState.h.
References _evenFlags.
setH() [1/2]
void peano4::grid::AutomatonState::setH (const tarch::la::Vector< Dimensions, double > & value)
Definition at line 56 of file AutomatonState.h.
References _h.
Referenced by AutomatonState(), peano4::grid::Spacetree::refineState(), peano4::grid::Spacetree::Spacetree(), and peano4::grid::Spacetree::Spacetree().
setH() [2/2]
void peano4::grid::AutomatonState::setH (int index, double value)
Definition at line 58 of file AutomatonState.h.
References _h.
setInverted()
void peano4::grid::AutomatonState::setInverted (bool value)
Definition at line 61 of file AutomatonState.h.
References _inverted.
Referenced by AutomatonState(), peano4::grid::Spacetree::Spacetree(), and peano4::grid::Spacetree::Spacetree().
setLevel()
void peano4::grid::AutomatonState::setLevel (int value)
Definition at line 48 of file AutomatonState.h.
References _level.
Referenced by AutomatonState(), peano4::grid::Spacetree::refineState(), peano4::grid::Spacetree::Spacetree(), and peano4::grid::Spacetree::Spacetree().
setX() [1/2]
void peano4::grid::AutomatonState::setX (const tarch::la::Vector< Dimensions, double > & value)
Definition at line 51 of file AutomatonState.h.
References _x.
Referenced by AutomatonState(), peano4::grid::Spacetree::refineState(), peano4::grid::Spacetree::Spacetree(), and peano4::grid::Spacetree::Spacetree().
setX() [2/2]
void peano4::grid::AutomatonState::setX (int index, double value)
Definition at line 53 of file AutomatonState.h.
References _x.
shutdownDatatype()
void peano4::grid::AutomatonState::shutdownDatatype () static
Free the underlying MPI datatype.
Definition at line 199 of file AutomatonState.cpp.
Referenced by peano4::parallel::Node::shutdownMPIDatatypes().
toString()
std::string peano4::grid::AutomatonState::toString () const
Definition at line 48 of file AutomatonState.cpp.
Referenced by peano4::grid::Spacetree::descend(), peano4::grid::Spacetree::evaluateGridControlEvents(), peano4::grid::Spacetree::loadVertices(), peano4::grid::Spacetree::receiveAndMergeUserData(), peano4::grid::Spacetree::refineState(), peano4::grid::Spacetree::sendUserData(), and peano4::grid::Spacetree::Spacetree().
Field Documentation
_accessNumber
tarch::la::Vector<DimensionsTimesTwo, int> peano4::grid::AutomatonState::_accessNumber private
Definition at line 167 of file AutomatonState.h.
Referenced by getAccessNumber(), getAccessNumber(), setAccessNumber(), and setAccessNumber().
_evenFlags
std::bitset<Dimensions> peano4::grid::AutomatonState::_evenFlags private
Definition at line 166 of file AutomatonState.h.
Referenced by flipEvenFlags(), getEvenFlags(), getEvenFlags(), setEvenFlags(), and setEvenFlags().
_h
tarch::la::Vector<Dimensions, double> peano4::grid::AutomatonState::_h private
Definition at line 164 of file AutomatonState.h.
Referenced by getH(), getH(), setH(), and setH().
_inverted
bool peano4::grid::AutomatonState::_inverted private
Definition at line 165 of file AutomatonState.h.
Referenced by getInverted(), and setInverted().
_level
int peano4::grid::AutomatonState::_level private
Definition at line 162 of file AutomatonState.h.
Referenced by getLevel(), and setLevel().
_senderDestinationRank
int peano4::grid::AutomatonState::_senderDestinationRank private
Definition at line 171 of file AutomatonState.h.
Referenced by receive(), and receive().
_x
tarch::la::Vector<Dimensions, double> peano4::grid::AutomatonState::_x private
Definition at line 163 of file AutomatonState.h.
Referenced by getX(), getX(), setX(), and setX().
Datatype
MPI_Datatype peano4::grid::AutomatonState::Datatype = MPI_DATATYPE_NULL static private
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
However, Peano calls init explicitly in most cases. Without the LLVM extension which caches the MPI datatype once constructed, this field stores the type.
Definition at line 180 of file AutomatonState.h.
The documentation for this struct was generated from the following files:
src/peano4/grid/AutomatonState.h
src/peano4/grid/AutomatonState.cpp