Peano
peano4::utils::tests::LinearisedTest Class Reference final
#include <LinearisedTest.h>
Public Member Functions
LinearisedTest ()
~LinearisedTest () override final=default
void run () override final
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testLinearisedBitset ()
void testLinearisedVectorWithoutLookup ()
void testLinearisedVectorRoundTripWithoutLookup ()
void testDelinearisedWithoutLookup ()
void testKeyComputationForLinearisedLookup ()
void testLookupTableLinearised ()
void testLookupTableDelinearised ()
void testLinearisedVector ()
void testDelinearisedVector ()
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Definition at line 11 of file LinearisedTest.h.
Constructor & Destructor Documentation
LinearisedTest()
peano4::utils::tests::LinearisedTest::LinearisedTest ()
Definition at line 7 of file LinearisedTest.cpp.
~LinearisedTest()
peano4::utils::tests::LinearisedTest::~LinearisedTest () final override default
Member Function Documentation
run()
void peano4::utils::tests::LinearisedTest::run () final override virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 10 of file LinearisedTest.cpp.
References testMethod.
testDelinearisedVector()
void peano4::utils::tests::LinearisedTest::testDelinearisedVector () private
Definition at line 200 of file LinearisedTest.cpp.
References tarch::la::aPowI(), peano4::utils::dDelinearisedWithoutLookup(), MaxTable, and validateEqualsWithParams1.
testDelinearisedWithoutLookup()
void peano4::utils::tests::LinearisedTest::testDelinearisedWithoutLookup () private
Definition at line 87 of file LinearisedTest.cpp.
References peano4::utils::dDelinearisedWithoutLookup(), peano4::utils::dLinearisedWithoutLookup(), and validateEqualsWithParams1.
testKeyComputationForLinearisedLookup()
void peano4::utils::tests::LinearisedTest::testKeyComputationForLinearisedLookup () private
Definition at line 99 of file LinearisedTest.cpp.
References peano4::utils::getKeyForDLinearisedLookup(), peano4::utils::MaxIndexOfLinearisation, MaxTable, and validateWithParams1.
testLinearisedBitset()
void peano4::utils::tests::LinearisedTest::testLinearisedBitset () private
Definition at line 22 of file LinearisedTest.cpp.
References peano4::utils::dLinearised(), and validateEqualsWithParams1.
testLinearisedVector()
void peano4::utils::tests::LinearisedTest::testLinearisedVector () private
Definition at line 170 of file LinearisedTest.cpp.
References peano4::utils::dLinearised(), MaxTable, and validateEqualsWithParams1.
testLinearisedVectorRoundTripWithoutLookup()
void peano4::utils::tests::LinearisedTest::testLinearisedVectorRoundTripWithoutLookup () private
Definition at line 64 of file LinearisedTest.cpp.
References peano4::utils::dDelinearisedWithoutLookup(), peano4::utils::dLinearisedWithoutLookup(), and validateEqualsWithParams1.
testLinearisedVectorWithoutLookup()
void peano4::utils::tests::LinearisedTest::testLinearisedVectorWithoutLookup () private
Definition at line 33 of file LinearisedTest.cpp.
References peano4::utils::dLinearisedWithoutLookup(), and validateEqualsWithParams1.
testLookupTableDelinearised()
void peano4::utils::tests::LinearisedTest::testLookupTableDelinearised () private
Definition at line 157 of file LinearisedTest.cpp.
References tarch::la::aPowI(), peano4::utils::dDelinearisedWithoutLookup(), peano4::utils::getKeyForDDeLinearisedLookup(), peano4::utils::lookupTableDDeLinearised, MaxTable, and validateEqualsWithParams1.
testLookupTableLinearised()
void peano4::utils::tests::LinearisedTest::testLookupTableLinearised () private
Definition at line 125 of file LinearisedTest.cpp.
References peano4::utils::dLinearisedWithoutLookup(), peano4::utils::getKeyForDLinearisedLookup(), peano4::utils::lookupTableDLinearised, MaxTable, and validateEqualsWithParams3.
The documentation for this class was generated from the following files:
src/peano4/utils/tests/LinearisedTest.h
src/peano4/utils/tests/LinearisedTest.cpp