Peano
fuseADERSolvers Namespace Reference
Functions
compute_projector_to_point_set (quad_points_from, quad_points_to)
Transforms the degrees of freedom located at Lagrange quadrature_points to degrees of freedom located at a set of points as defined by the parameter points.
flatten (xss)
postprocessing_kernel (condition, order, proj, solver_name)
dg2dgFace ()
fuseADERSolvers (solver1, solver2, condition)
Function Documentation
compute_projector_to_point_set()
fuseADERSolvers.compute_projector_to_point_set (quad_points_from, quad_points_to)
Transforms the degrees of freedom located at Lagrange quadrature_points to degrees of freedom located at a set of points as defined by the parameter points.
Let us denote by P the projection operator. The DoF are computed according to:
u@x = sum_{m} P_m u^DG_m
Returns: Projector: The corresponding degrees of freedom located at the set of points defined by the parameter x.
Definition at line 4 of file fuseADERSolvers.py.
Referenced by fuseADERSolvers().
dg2dgFace()
fuseADERSolvers.dg2dgFace ()
Definition at line 89 of file fuseADERSolvers.py.
Referenced by fuseADERSolvers().
flatten()
fuseADERSolvers.flatten (xss)
Definition at line 34 of file fuseADERSolvers.py.
Referenced by fuseADERSolvers().
fuseADERSolvers()
fuseADERSolvers.fuseADERSolvers (solver1, solver2, condition)
Definition at line 133 of file fuseADERSolvers.py.
References compute_projector_to_point_set(), dg2dgFace(), flatten(), and postprocessing_kernel().
postprocessing_kernel()
fuseADERSolvers.postprocessing_kernel (condition, order, proj, solver_name)
Definition at line 37 of file fuseADERSolvers.py.
Referenced by fuseADERSolvers().