Peano
api.MatrixFreeMain.MatrixFreeMain Class Reference
Public Member Functions
__init__ (self, project, domain_offset, domain_size, plot_each_timestep, max_iterations)
Public Member Functions inherited from peano4.runner.DefaultSequence.DefaultSequence
construct_output (self, output, main_name)
Pass in a version of output.
merge (self, main)
Make subproject's data a part of the project (will be extended)
Data Fields
overwrite
Data Fields inherited from peano4.runner.DefaultSequence.DefaultSequence
project
overwrite
d
is_extended
Protected Member Functions
_get_header_file_template (self)
_get_implementation_file_template (self)
Detailed Description
Definition at line 4 of file MatrixFreeMain.py.
Constructor & Destructor Documentation
__init__()
api.MatrixFreeMain.MatrixFreeMain.__init__ (self, project, domain_offset, domain_size, plot_each_timestep, max_iterations)
Reimplemented from peano4.runner.DefaultSequence.DefaultSequence.
Definition at line 5 of file MatrixFreeMain.py.
References api.MatrixFreeMain.MatrixFreeMain.__init__().
Referenced by api.MatrixFreeMain.MatrixFreeMain.__init__().
Member Function Documentation
_get_header_file_template()
api.MatrixFreeMain.MatrixFreeMain._get_header_file_template (self) protected
Reimplemented from peano4.runner.DefaultSequence.DefaultSequence.
Definition at line 30 of file MatrixFreeMain.py.
Referenced by peano4.runner.DefaultSequence.DefaultSequence.construct_output().
_get_implementation_file_template()
api.MatrixFreeMain.MatrixFreeMain._get_implementation_file_template (self) protected
Reimplemented from peano4.runner.DefaultSequence.DefaultSequence.
Definition at line 34 of file MatrixFreeMain.py.
Referenced by peano4.runner.DefaultSequence.DefaultSequence.construct_output().
Field Documentation
overwrite
api.MatrixFreeMain.MatrixFreeMain.overwrite
Definition at line 13 of file MatrixFreeMain.py.
Referenced by peano4.runner.DefaultSequence.DefaultSequence.construct_output().
The documentation for this class was generated from the following file:
src/mghype/matrixfree/api/MatrixFreeMain.py