Peano
tarch::mpi::DoubleMessage Struct Reference
#include <DoubleMessage.h>
Public Types
enum ObjectConstruction { NoData }
Public Member Functions
DoubleMessage ()
DoubleMessage (double __value)
double getValue () const
void setValue (double value)
DoubleMessage (const DoubleMessage &copy)=default
int getSenderRank () const
DoubleMessage (ObjectConstruction)
std::string toString () const
Static Public Member Functions
static MPI_Datatype getForkDatatype ()
Hands out MPI datatype if we work without the LLVM MPI extension.
static MPI_Datatype getJoinDatatype ()
static MPI_Datatype getBoundaryExchangeDatatype ()
static MPI_Datatype getMultiscaleDataExchangeDatatype ()
static MPI_Datatype getGlobalCommunciationDatatype ()
static void freeForkDatatype ()
static void freeJoinDatatype ()
static void freeBoundaryExchangeDatatype ()
static void freeMultiscaleDataExchangeDatatype ()
static void freeGlobalCommunciationDatatype ()
static void initDatatype ()
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
static void shutdownDatatype ()
Free the underlying MPI datatype.
static void send (const tarch::mpi::DoubleMessage &buffer, int destination, int tag, MPI_Comm communicator)
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
static void receive (tarch::mpi::DoubleMessage &buffer, int source, int tag, MPI_Comm communicator)
static void send (const tarch::mpi::DoubleMessage &buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
static void receive (tarch::mpi::DoubleMessage &buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
static void sendAndPollDanglingMessages (const tarch::mpi::DoubleMessage &message, int destination, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
static void receiveAndPollDanglingMessages (tarch::mpi::DoubleMessage &message, int source, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
Private Attributes
double _value
int _senderDestinationRank
Static Private Attributes
static MPI_Datatype Datatype = MPI_DATATYPE_NULL
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
Detailed Description
Definition at line 33 of file DoubleMessage.h.
Member Enumeration Documentation
ObjectConstruction
enum tarch::mpi::DoubleMessage::ObjectConstruction
Enumerator
NoData
Definition at line 121 of file DoubleMessage.h.
Constructor & Destructor Documentation
DoubleMessage() [1/4]
tarch::mpi::DoubleMessage::DoubleMessage ()
Definition at line 37 of file DoubleMessage.h.
DoubleMessage() [2/4]
tarch::mpi::DoubleMessage::DoubleMessage (double __value)
Definition at line 10 of file DoubleMessage.cpp.
References setValue().
DoubleMessage() [3/4]
tarch::mpi::DoubleMessage::DoubleMessage (const DoubleMessage & copy) default
DoubleMessage() [4/4]
tarch::mpi::DoubleMessage::DoubleMessage (ObjectConstruction)
Definition at line 125 of file DoubleMessage.h.
Member Function Documentation
freeBoundaryExchangeDatatype()
void tarch::mpi::DoubleMessage::freeBoundaryExchangeDatatype () static
Definition at line 107 of file DoubleMessage.cpp.
freeForkDatatype()
void tarch::mpi::DoubleMessage::freeForkDatatype () static
Definition at line 80 of file DoubleMessage.cpp.
freeGlobalCommunciationDatatype()
void tarch::mpi::DoubleMessage::freeGlobalCommunciationDatatype () static
Definition at line 89 of file DoubleMessage.cpp.
freeJoinDatatype()
void tarch::mpi::DoubleMessage::freeJoinDatatype () static
Definition at line 98 of file DoubleMessage.cpp.
freeMultiscaleDataExchangeDatatype()
void tarch::mpi::DoubleMessage::freeMultiscaleDataExchangeDatatype () static
Definition at line 116 of file DoubleMessage.cpp.
getBoundaryExchangeDatatype()
MPI_Datatype tarch::mpi::DoubleMessage::getBoundaryExchangeDatatype () static
Definition at line 68 of file DoubleMessage.cpp.
getForkDatatype()
MPI_Datatype tarch::mpi::DoubleMessage::getForkDatatype () static
Hands out MPI datatype if we work without the LLVM MPI extension.
If we work with this additional feature, this is the routine where the lazy initialisation is done and the datatype is also cached.
Definition at line 50 of file DoubleMessage.cpp.
getGlobalCommunciationDatatype()
MPI_Datatype tarch::mpi::DoubleMessage::getGlobalCommunciationDatatype () static
Definition at line 56 of file DoubleMessage.cpp.
getJoinDatatype()
MPI_Datatype tarch::mpi::DoubleMessage::getJoinDatatype () static
Definition at line 62 of file DoubleMessage.cpp.
getMultiscaleDataExchangeDatatype()
MPI_Datatype tarch::mpi::DoubleMessage::getMultiscaleDataExchangeDatatype () static
Definition at line 74 of file DoubleMessage.cpp.
getSenderRank()
int tarch::mpi::DoubleMessage::getSenderRank () const
Returns
The rank of the sender of an object. It only make ssense to call this routine after you've invoked receive with MPI_ANY_SOURCE.
Definition at line 124 of file DoubleMessage.cpp.
getValue()
double tarch::mpi::DoubleMessage::getValue () const
Definition at line 28 of file DoubleMessage.cpp.
initDatatype()
void tarch::mpi::DoubleMessage::initDatatype () static
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
Definition at line 129 of file DoubleMessage.cpp.
Referenced by tarch::mpi::Rank::init().
receive() [1/2]
void tarch::mpi::DoubleMessage::receive (tarch::mpi::DoubleMessage & buffer, int source, int tag, MPI_Comm communicator) static
Definition at line 202 of file DoubleMessage.cpp.
References _senderDestinationRank.
Referenced by receiveAndPollDanglingMessages().
receive() [2/2]
void tarch::mpi::DoubleMessage::receive (tarch::mpi::DoubleMessage & buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Definition at line 229 of file DoubleMessage.cpp.
References _senderDestinationRank.
receiveAndPollDanglingMessages()
void tarch::mpi::DoubleMessage::receiveAndPollDanglingMessages (tarch::mpi::DoubleMessage & message, int source, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 269 of file DoubleMessage.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), receive(), tarch::services::ServiceRepository::receiveDanglingMessages(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
send() [1/2]
void tarch::mpi::DoubleMessage::send (const tarch::mpi::DoubleMessage & buffer, int destination, int tag, MPI_Comm communicator) static
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
However, this did not work with newer C++11 versions, as a member function using this as pointer usually doesn't see the vtable while the init sees the object from outside, i.e. including a vtable. So this routine now is basically an alias for a blocking MPI_Send.
Definition at line 197 of file DoubleMessage.cpp.
Referenced by sendAndPollDanglingMessages().
send() [2/2]
void tarch::mpi::DoubleMessage::send (const tarch::mpi::DoubleMessage & buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
In systems with heavy MPI usage, this can help to avoid deadlocks.
Definition at line 209 of file DoubleMessage.cpp.
sendAndPollDanglingMessages()
void tarch::mpi::DoubleMessage::sendAndPollDanglingMessages (const tarch::mpi::DoubleMessage & message, int destination, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 252 of file DoubleMessage.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), tarch::services::ServiceRepository::receiveDanglingMessages(), send(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
setValue()
void tarch::mpi::DoubleMessage::setValue (double value)
Definition at line 33 of file DoubleMessage.cpp.
Referenced by DoubleMessage().
shutdownDatatype()
void tarch::mpi::DoubleMessage::shutdownDatatype () static
Free the underlying MPI datatype.
Definition at line 183 of file DoubleMessage.cpp.
toString()
std::string tarch::mpi::DoubleMessage::toString () const
Definition at line 16 of file DoubleMessage.cpp.
Field Documentation
_senderDestinationRank
int tarch::mpi::DoubleMessage::_senderDestinationRank private
Definition at line 143 of file DoubleMessage.h.
Referenced by receive(), and receive().
_value
double tarch::mpi::DoubleMessage::_value private
Definition at line 137 of file DoubleMessage.h.
Datatype
MPI_Datatype tarch::mpi::DoubleMessage::Datatype = MPI_DATATYPE_NULL static private
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
However, Peano calls init explicitly in most cases. Without the LLVM extension which caches the MPI datatype once constructed, this field stores the type.
Definition at line 152 of file DoubleMessage.h.
The documentation for this struct was generated from the following files:
src/tarch/mpi/DoubleMessage.h
src/tarch/mpi/DoubleMessage.cpp