var rkfd_2fd4_2GlobalAdaptiveTimeStepWithEnclaveTasking_8py =
[
    [ "exahype2.solvers.rkfd.fd4.GlobalAdaptiveTimeStepWithEnclaveTasking.GlobalAdaptiveTimeStepWithEnclaveTasking", "d7/d49/classexahype2_1_1solvers_1_1rkfd_1_1fd4_1_1GlobalAdaptiveTimeStepWithEnclaveTasking_1_1GlobalAdaptiveTimeStepWithEnclaveTasking.html", "d7/d49/classexahype2_1_1solvers_1_1rkfd_1_1fd4_1_1GlobalAdaptiveTimeStepWithEnclaveTasking_1_1GlobalAdaptiveTimeStepWithEnclaveTasking" ]
];