Peano
tl::compose_fn< F, G > Struct Template Reference
#include <cartesian_product.h>
Public Member Functions
template<class A , class B >
compose_fn (A &&a, B &&b)
template<class... Args>
constexpr auto operator() (Args &&... args) &
template<class... Args>
constexpr auto operator() (Args &&... args) const &
template<class... Args>
constexpr auto operator() (Args &&... args) &&
template<class... Args>
constexpr auto operator() (Args &&... args) const &&
Static Public Member Functions
template<class A , class B , class ... Args>
static constexpr auto call (A &&a, B &&b, Args &&... args)
Data Fields
F f
G g
Detailed Description
template<class F, class G>
struct tl::compose_fn< F, G >
Definition at line 907 of file cartesian_product.h.
Constructor & Destructor Documentation
compose_fn()
template<class F , class G > template<class A , class B > tl::compose_fn< F, G >::compose_fn (A && a, B && b)
Definition at line 912 of file cartesian_product.h.
Member Function Documentation
call()
template<class F , class G > template<class A , class B , class ... Args> static constexpr auto tl::compose_fn< F, G >::call (A && a, B && b, Args &&... args) static constexpr
Definition at line 915 of file cartesian_product.h.
References a.
Referenced by tl::compose_fn< F, G >::operator()(), tl::compose_fn< F, G >::operator()(), tl::compose_fn< F, G >::operator()(), and tl::compose_fn< F, G >::operator()().
operator()() [1/4]
template<class F , class G > template<class... Args> constexpr auto tl::compose_fn< F, G >::operator() (Args &&... args) & constexpr
Definition at line 926 of file cartesian_product.h.
References tl::compose_fn< F, G >::call(), tl::compose_fn< F, G >::f, and tl::compose_fn< F, G >::g.
operator()() [2/4]
template<class F , class G > template<class... Args> constexpr auto tl::compose_fn< F, G >::operator() (Args &&... args) && constexpr
Definition at line 936 of file cartesian_product.h.
References tl::compose_fn< F, G >::call(), tl::compose_fn< F, G >::f, and tl::compose_fn< F, G >::g.
operator()() [3/4]
template<class F , class G > template<class... Args> constexpr auto tl::compose_fn< F, G >::operator() (Args &&... args) const & constexpr
Definition at line 931 of file cartesian_product.h.
References tl::compose_fn< F, G >::call(), tl::compose_fn< F, G >::f, and tl::compose_fn< F, G >::g.
operator()() [4/4]
template<class F , class G > template<class... Args> constexpr auto tl::compose_fn< F, G >::operator() (Args &&... args) const && constexpr
Definition at line 941 of file cartesian_product.h.
References tl::compose_fn< F, G >::call(), tl::compose_fn< F, G >::f, and tl::compose_fn< F, G >::g.
Field Documentation
f
template<class F , class G > F tl::compose_fn< F, G >::f
Definition at line 908 of file cartesian_product.h.
Referenced by tl::compose_fn< F, G >::operator()(), tl::compose_fn< F, G >::operator()(), tl::compose_fn< F, G >::operator()(), tl::compose_fn< F, G >::operator()(), swift2.sphtools.riemann.RiemannSolver::solve(), swift2.sphtools.riemann.RiemannSolver::solve_brent(), and swift2.sphtools.riemann.RiemannSolver::solve_middle_state().
g
template<class F , class G > G tl::compose_fn< F, G >::g
Definition at line 909 of file cartesian_product.h.
Referenced by tl::compose_fn< F, G >::operator()(), tl::compose_fn< F, G >::operator()(), tl::compose_fn< F, G >::operator()(), and tl::compose_fn< F, G >::operator()().
The documentation for this struct was generated from the following file:
src/tarch/accelerator/cpp/cartesian_product.h