Peano
TP_bindding Namespace Reference
Functions
void SOCCZ4Cal (double *__restrict__ Q)
void GradientCal (const double *X, double *__restrict__ Q, double *LgradQ, int nVars, TP::TwoPunctures *tp, bool low_res=false)
void AuxiliaryCal (double *__restrict__ Q, double *LgradQ, int nVars)
Function Documentation
AuxiliaryCal()
void TP_bindding::AuxiliaryCal (double *__restrict__ Q, double * LgradQ, int nVars)
Definition at line 65 of file TP_bindding.h.
GradientCal()
void TP_bindding::GradientCal (const double * X, double *__restrict__ Q, double * LgradQ, int nVars, TP::TwoPunctures * tp, bool low_res = false)
Definition at line 42 of file TP_bindding.h.
References TP::TwoPunctures::Interpolate(), SOCCZ4Cal(), and X.
SOCCZ4Cal()
void TP_bindding::SOCCZ4Cal (double *__restrict__ Q)
Definition at line 10 of file TP_bindding.h.
Referenced by GradientCal().