Peano
peano4::parallel::TreeEntry Struct Reference
#include <TreeEntry.h>
Public Types
enum ObjectConstruction { NoData }
Public Member Functions
TreeEntry ()
TreeEntry (int __id, int __master)
int getId () const
void setId (int value)
int getMaster () const
void setMaster (int value)
TreeEntry (const TreeEntry &copy)=default
int getSenderRank () const
TreeEntry (ObjectConstruction)
std::string toString () const
Static Public Member Functions
static MPI_Datatype getForkDatatype ()
Hands out MPI datatype if we work without the LLVM MPI extension.
static MPI_Datatype getJoinDatatype ()
static MPI_Datatype getBoundaryExchangeDatatype ()
static MPI_Datatype getMultiscaleDataExchangeDatatype ()
static MPI_Datatype getGlobalCommunciationDatatype ()
static void freeForkDatatype ()
static void freeJoinDatatype ()
static void freeBoundaryExchangeDatatype ()
static void freeMultiscaleDataExchangeDatatype ()
static void freeGlobalCommunciationDatatype ()
static void initDatatype ()
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
static void shutdownDatatype ()
Free the underlying MPI datatype.
static void send (const peano4::parallel::TreeEntry &buffer, int destination, int tag, MPI_Comm communicator)
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
static void receive (peano4::parallel::TreeEntry &buffer, int source, int tag, MPI_Comm communicator)
static void send (const peano4::parallel::TreeEntry &buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
static void receive (peano4::parallel::TreeEntry &buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
static void sendAndPollDanglingMessages (const peano4::parallel::TreeEntry &message, int destination, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
static void receiveAndPollDanglingMessages (peano4::parallel::TreeEntry &message, int source, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
Private Attributes
int _id
int _master
int _senderDestinationRank
Static Private Attributes
static MPI_Datatype Datatype = MPI_DATATYPE_NULL
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
Detailed Description
Definition at line 27 of file TreeEntry.h.
Member Enumeration Documentation
ObjectConstruction
enum peano4::parallel::TreeEntry::ObjectConstruction
Enumerator
NoData
Definition at line 114 of file TreeEntry.h.
Constructor & Destructor Documentation
TreeEntry() [1/4]
peano4::parallel::TreeEntry::TreeEntry ()
Definition at line 29 of file TreeEntry.h.
TreeEntry() [2/4]
peano4::parallel::TreeEntry::TreeEntry (int __id, int __master)
Definition at line 10 of file TreeEntry.cpp.
References setId(), and setMaster().
TreeEntry() [3/4]
peano4::parallel::TreeEntry::TreeEntry (const TreeEntry & copy) default
TreeEntry() [4/4]
peano4::parallel::TreeEntry::TreeEntry (ObjectConstruction)
Definition at line 118 of file TreeEntry.h.
Member Function Documentation
freeBoundaryExchangeDatatype()
void peano4::parallel::TreeEntry::freeBoundaryExchangeDatatype () static
Definition at line 120 of file TreeEntry.cpp.
freeForkDatatype()
void peano4::parallel::TreeEntry::freeForkDatatype () static
Definition at line 93 of file TreeEntry.cpp.
freeGlobalCommunciationDatatype()
void peano4::parallel::TreeEntry::freeGlobalCommunciationDatatype () static
Definition at line 102 of file TreeEntry.cpp.
freeJoinDatatype()
void peano4::parallel::TreeEntry::freeJoinDatatype () static
Definition at line 111 of file TreeEntry.cpp.
freeMultiscaleDataExchangeDatatype()
void peano4::parallel::TreeEntry::freeMultiscaleDataExchangeDatatype () static
Definition at line 129 of file TreeEntry.cpp.
getBoundaryExchangeDatatype()
MPI_Datatype peano4::parallel::TreeEntry::getBoundaryExchangeDatatype () static
Definition at line 81 of file TreeEntry.cpp.
getForkDatatype()
MPI_Datatype peano4::parallel::TreeEntry::getForkDatatype () static
Hands out MPI datatype if we work without the LLVM MPI extension.
If we work with this additional feature, this is the routine where the lazy initialisation is done and the datatype is also cached.
Definition at line 63 of file TreeEntry.cpp.
getGlobalCommunciationDatatype()
MPI_Datatype peano4::parallel::TreeEntry::getGlobalCommunciationDatatype () static
Definition at line 69 of file TreeEntry.cpp.
getId()
int peano4::parallel::TreeEntry::getId () const
Definition at line 31 of file TreeEntry.cpp.
getJoinDatatype()
MPI_Datatype peano4::parallel::TreeEntry::getJoinDatatype () static
Definition at line 75 of file TreeEntry.cpp.
getMaster()
int peano4::parallel::TreeEntry::getMaster () const
Definition at line 41 of file TreeEntry.cpp.
getMultiscaleDataExchangeDatatype()
MPI_Datatype peano4::parallel::TreeEntry::getMultiscaleDataExchangeDatatype () static
Definition at line 87 of file TreeEntry.cpp.
getSenderRank()
int peano4::parallel::TreeEntry::getSenderRank () const
Returns
The rank of the sender of an object. It only make ssense to call this routine after you've invoked receive with MPI_ANY_SOURCE.
Definition at line 137 of file TreeEntry.cpp.
initDatatype()
void peano4::parallel::TreeEntry::initDatatype () static
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
Definition at line 142 of file TreeEntry.cpp.
receive() [1/2]
void peano4::parallel::TreeEntry::receive (peano4::parallel::TreeEntry & buffer, int source, int tag, MPI_Comm communicator) static
Definition at line 221 of file TreeEntry.cpp.
References _senderDestinationRank.
Referenced by receiveAndPollDanglingMessages().
receive() [2/2]
void peano4::parallel::TreeEntry::receive (peano4::parallel::TreeEntry & buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Definition at line 248 of file TreeEntry.cpp.
References _senderDestinationRank.
receiveAndPollDanglingMessages()
void peano4::parallel::TreeEntry::receiveAndPollDanglingMessages (peano4::parallel::TreeEntry & message, int source, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 288 of file TreeEntry.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), receive(), tarch::services::ServiceRepository::receiveDanglingMessages(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
send() [1/2]
void peano4::parallel::TreeEntry::send (const peano4::parallel::TreeEntry & buffer, int destination, int tag, MPI_Comm communicator) static
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
However, this did not work with newer C++11 versions, as a member function using this as pointer usually doesn't see the vtable while the init sees the object from outside, i.e. including a vtable. So this routine now is basically an alias for a blocking MPI_Send.
Definition at line 216 of file TreeEntry.cpp.
Referenced by sendAndPollDanglingMessages().
send() [2/2]
void peano4::parallel::TreeEntry::send (const peano4::parallel::TreeEntry & buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
In systems with heavy MPI usage, this can help to avoid deadlocks.
Definition at line 228 of file TreeEntry.cpp.
sendAndPollDanglingMessages()
void peano4::parallel::TreeEntry::sendAndPollDanglingMessages (const peano4::parallel::TreeEntry & message, int destination, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 271 of file TreeEntry.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), tarch::services::ServiceRepository::receiveDanglingMessages(), send(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
setId()
void peano4::parallel::TreeEntry::setId (int value)
Definition at line 36 of file TreeEntry.cpp.
Referenced by peano4::parallel::Node::registerId(), and TreeEntry().
setMaster()
void peano4::parallel::TreeEntry::setMaster (int value)
Definition at line 46 of file TreeEntry.cpp.
Referenced by peano4::parallel::Node::registerId(), and TreeEntry().
shutdownDatatype()
void peano4::parallel::TreeEntry::shutdownDatatype () static
Free the underlying MPI datatype.
Definition at line 202 of file TreeEntry.cpp.
toString()
std::string peano4::parallel::TreeEntry::toString () const
Definition at line 17 of file TreeEntry.cpp.
Field Documentation
_id
int peano4::parallel::TreeEntry::_id private
Definition at line 130 of file TreeEntry.h.
_master
int peano4::parallel::TreeEntry::_master private
Definition at line 131 of file TreeEntry.h.
_senderDestinationRank
int peano4::parallel::TreeEntry::_senderDestinationRank private
Definition at line 135 of file TreeEntry.h.
Referenced by receive(), and receive().
Datatype
MPI_Datatype peano4::parallel::TreeEntry::Datatype = MPI_DATATYPE_NULL static private
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
However, Peano calls init explicitly in most cases. Without the LLVM extension which caches the MPI datatype once constructed, this field stores the type.
Definition at line 144 of file TreeEntry.h.
The documentation for this struct was generated from the following files:
src/peano4/parallel/TreeEntry.h
src/peano4/parallel/TreeEntry.cpp