Peano
swift2::kernels::legacy Namespace Reference
Legacy SPH implementation.
Namespaces
namespace adiabaticIndex
namespace eos
namespace hydroDimensions
namespace kernelHydro
Functions
template<typename Particle >
bool prepareDensityUpdateParticlePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &localParticle)
Prepares a particle for the density calculation.
template<typename Particle >
void prepareDensity (const peano4::datamanagement::VertexMarker &marker, Particle &localParticle)
template<typename Particle >
void hydro_end_density (Particle *localParticle)
Finishes the density calculation.
template<typename Particle >
bool endDensityCalculationUpdateParticlePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &localParticle)
template<typename Particle >
void endDensityCalculation (const peano4::datamanagement::VertexMarker &marker, Particle &localParticle)
template<typename Particle >
void density_kernel (Particle *localParticle, const Particle *activeParticle)
The actual density kernel, which interacts a local particle and an active particle, and updates the local particle.
template<typename Particle >
bool densityKernelUpdateParticlePredicate (const peano4::datamanagement::CellMarker &marker, const bool &localParticleIsContainedInCell, const Particle &localParticle)
Predicate to decide if to update a particle according to density kernel.
template<typename Particle >
bool densityKernelEvaluatePairInteractionPredicate (const peano4::datamanagement::CellMarker &marker, const Particle &localParticle, const Particle &activeParticle)
Predicate if two particles contribute towards the density checks.
template<typename Particle >
void densityKernel (const peano4::datamanagement::CellMarker &marker, Particle &localParticle, const Particle &activeParticle)
Density kernel.
template<typename Particle >
void hydro_prepare_force (Particle *localParticle)
Prepare a particle for the force calculation.
template<typename Particle >
bool prepareHydroForceUpdateParticlePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &localParticle)
template<typename Particle >
void prepareHydroForce (const peano4::datamanagement::VertexMarker &marker, Particle &localParticle)
template<typename Particle >
void hydro_reset_acceleration (Particle *localParticle)
Reset acceleration fields of a particle.
template<typename Particle >
bool resetAccelerationUpdateParticlePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &localParticle)
template<typename Particle >
void resetAcceleration (const peano4::datamanagement::VertexMarker &marker, Particle &localParticle)
template<typename Particle >
void hydro_end_force (Particle *localParticle)
Finishes the force calculation.
template<typename Particle >
bool endHydroForceCalculationUpdateParticlePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &localParticle)
template<typename Particle >
void endHydroForceCalculation (const peano4::datamanagement::VertexMarker &marker, Particle &localParticle)
template<typename Particle >
void force_kernel (Particle *localParticle, const Particle *activeParticle)
The actual force kernel, which interacts a local particle and an active particle, and updates the local particle.
template<typename Particle >
bool forceKernelUpdateParticlePredicate (const peano4::datamanagement::CellMarker &marker, const bool &localParticleIsContainedInCell, const Particle &localParticle)
template<typename Particle >
bool forceKernelEvaluatePairInteractionPredicate (const peano4::datamanagement::CellMarker &marker, const Particle &localParticle, const Particle &activeParticle)
template<typename Particle >
void forceKernel (const peano4::datamanagement::CellMarker &marker, Particle &localParticle, const Particle &activeParticle)
Generic force kernel implementation.
template<typename Particle >
void predict_hyrdro (Particle *particle)
Predict hydro terms (SWIFT) Relevant for inactive particles when using local-timestepping, but always used.
template<typename Particle >
bool predictHydroUpdateParticlePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &localParticle)
template<typename Particle >
void predictHydro (const peano4::datamanagement::VertexMarker &marker, Particle &localParticle)
template<typename Particle >
bool forceKernelDistanceCheck (Particle *__restrict__ localParticle, const Particle *__restrict__ activeParticle)
Check distance between two particles.
template<typename Particle >
void leapfrog_drift_global_time_step_size (Particle *particle)
Update a particle with the leapfrog KDK integrator.
template<typename Particle >
bool leapfrogDriftWithGlobalTimeStepSizeParticleUpdatePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &localParticle)
template<typename Particle >
void leapfrogDriftWithGlobalTimeStepSize (const peano4::datamanagement::VertexMarker &marker, Particle &localParticle)
template<typename Particle >
void hydro_predict_extra (Particle *localParticle)
Predict additional particle fields forward in time when drifting.
template<typename Particle >
bool hydroPredictExtraUpdateParticlePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &localParticle)
template<typename Particle >
void hydroPredictExtra (const peano4::datamanagement::VertexMarker &marker, Particle &localParticle)
template<typename Particle >
void leapfrog_kick_global_time_step_size (Particle *particle)
Kick steps.
template<typename Particle >
bool leapfrogKickWithGlobalTimeStepSizeUpdateParticlePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &localParticle)
template<typename Particle >
void leapfrogKickWithGlobalTimeStepSize (const peano4::datamanagement::VertexMarker &marker, Particle &localParticle)
template<typename Particle >
void hydro_kick_extra_global_time_step_size (Particle *localParticle)
Kick the additional variables.
template<typename Particle >
bool leapfrogKickExtraWithGlobalTimeStepSizeUpdateParticlePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &localParticle)
template<typename Particle >
void leapfrogKickExtraWithGlobalTimeStepSize (const peano4::datamanagement::VertexMarker &marker, Particle &localParticle)
template<typename Particle >
void hydro_reset_predicted_values (Particle *localParticle)
Sets the values to be predicted in the drifts to their values at a kick time.
template<typename Particle >
bool resetPredictedValuesUpdateParticlePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &localParticle)
template<typename Particle >
void resetPredictedValues (const peano4::datamanagement::VertexMarker &marker, Particle &localParticle)
template<typename Particle >
void hydro_update_smoothing_length_and_rerun_if_required (Particle *localParticle)
Derive smoothing length from density.
template<typename Particle >
bool updateSmoothingLengthAndRerunIfRequiredUpdateParticlePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &localParticle)
template<typename Particle >
void updateSmoothingLengthAndRerunIfRequired (const peano4::datamanagement::VertexMarker &marker, Particle &localParticle)
Wrapper around hydro_update_smoothing_length_and_rerun_if_required() with only one argument.
template<typename Particle >
bool resetSmoothingLengthIterationCounterUpdateParticlePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &particle)
Reset smoothing length iteration related flags on a particle.
template<typename Particle >
void resetSmoothingLengthIterationCounter (const peano4::datamanagement::VertexMarker &marker, Particle &particle)
template<typename Particle >
void first_init_particle (Particle *particle)
Initialise particles for the first time.
template<typename Particle >
bool firstInitParticleParticleUpdatePredicate (const peano4::datamanagement::VertexMarker &marker, const Particle &particle)
In principle, we don't need to check for anything here, just overwrite particle data.
template<typename Particle >
void firstInitParticle (const peano4::datamanagement::VertexMarker &marker, Particle &particle)
template<typename Particle >
void hydro_init_particle (Particle *particle)
Prepares a particle for the density calculation.
template<typename Particle >
double hydro_compute_timestep (Particle *particle)
Computes the SPH time step size.
template<typename ParticleContainer >
void computeNextTimestep (const peano4::datamanagement::VertexMarker &marker, ParticleContainer &assignedParticles)
computes the next time step size for all particles associated to this vertex, and writes it into the particle species.
Detailed Description
Legacy SPH implementation.
This implementation is very very close to the original Swift kernels. This can immediately be seen from the signature of the routines: The core routines all work solely with pointers.
For Swift 2 however, we need signatures which work with references and also evaluate predicates. So each routine actually comes along as pair: The core science with a pointer and then a wrapper around it.
The wrapper vs implementation distinction also is reflected in the naming conventions: The actual physics remain written in C/Swift style, whereas the wrappers follow the Peano's C++ convention.
This file contains only the functions that we actually want to use from the original swift codebase, and maintains their original name. The idea is to eventually use the SWIFT implementation of these functions. But for now, we keep a (modified) version of them here.
A second point to keep these functions separate is the fact that they do different things for each SPH flavour. So they are intended to be replaceable anyway.
There are some notable exceptions which are missing from this collection of functions. Firstly, we keep the particle-particle interactions separately. We are tinkering with them in Peano and optimizing them in a different way. They are defined in ParticleParticleInteraction.h. Secondly, anything related to the computation of the smoothing lengths is defined in SmoothingLengthComputation.h. The smoothing length computation is intimately tied to the neighbour search algorithms, and cannot be separated trivially from the underlying codebase and infrastructure. As such, we can't simply re-use what original SWIFT does, but need to provide our own algorithms. In particular, we differentiate between the search radius and the interaction radius/ compact support radius of particles, which original swift doesn't. We provide smoothing length computation algorithms for both a constant search radius as well as a varying search radius.
Function Documentation
computeNextTimestep()
template<typename ParticleContainer > void swift2::kernels::legacy::computeNextTimestep (const peano4::datamanagement::VertexMarker & marker, ParticleContainer & assignedParticles)
computes the next time step size for all particles associated to this vertex, and writes it into the particle species.
@TODO: this needs to be made threadsafe. @TODO: this needs to make use of the other forAll particleSetIterators. But for that, we need a new particleSetIterator that accepts a return value and a function to reduce the return value.
Definition at line 46 of file Timestep.cpph.
References hydro_compute_timestep(), and swift2::kernels::localParticleCanBeUpdatedInVertexKernel().
density_kernel()
template<typename Particle > void swift2::kernels::legacy::density_kernel (Particle * localParticle, const Particle * activeParticle)
The actual density kernel, which interacts a local particle and an active particle, and updates the local particle.
In this particle-particle interaction loop, we accumulate several quantities. For the subsequent force computation, we need to collect the density
\(\rho_i = \rho(\mathbf{x}_i) = \sum_j m_j W(r_{ij}, h_i)\)
and its derivative w.r.t. \(h \) :
\(\frac{\partial \rho_i}{\partial h} = \sum_j m_j \frac{\partial W(r_{ij}, h_i)}{\partial h} \)
(see the \(f_i\) in swift2::kernels::legacy::force_kernel to see where and how it is used) where \(m_j \) is the particle mass, \(r_{ij} \) is the distance between particle \(i \) and \(j \), \(h_i \) is the smoothing length of \(i \) and \(W(r, h) \) is the SPH kernel function we use.
Let
\(W = \frac{1}{h^\nu} f\left(\frac{r}{h}\right) \equiv \frac{1}{h^\nu} f(q) \)
for \(\nu \) dimensions. Then
\(\frac{\partial W(r_{ij}, h_i)}{\partial h} = - \nu \frac{1}{h ^ {\nu + 1}} f(r/h) + \frac{1}{h^\nu} \frac{\partial f(q)}{\partial h} = - \nu \frac{1}{h ^ {\nu + 1}} f(q) + \frac{1}{h^\nu} \frac{\partial f(q)}{\partial q} \frac{\partial q}{\partial h} = - \frac{1}{h} \left(\nu W(q) + q \frac{\partial W(q)}{\partial q} \right) \)
which is a quantity we accumulate in the density interaction kernel for the estimate of \(\frac{\partial \rho_i}{\partial h} \).
Similarly, for the computation of the smoothing length, we require to accumulate the analgue number densities (and its derivative w.r.t. h):
\(n_i = \sum_j W(r_{ij}, h_i)\)
\(\frac{\partial n_i}{\partial h} = \sum_j \frac{\partial W(r_{ij}, h_i)}{\partial h} \)
Definition at line 129 of file Density.cpph.
References curlvr, tarch::la::dot(), dv, dvdr, dx, hi, hi_inv, kernel_deval(), mj, tarch::la::norm2(), r, and r_inv.
Referenced by densityKernel().
densityKernel()
template<typename Particle > void swift2::kernels::legacy::densityKernel (const peano4::datamanagement::CellMarker & marker, Particle & localParticle, const Particle & activeParticle)
Density kernel.
This routine forwards the function call to density_kernel(). Please consult this routine for additional information.
Predicates and preconditions
This kernel is to be used with
densityKernelUpdateParticlePredicate() and
densityKernelEvaluatePairInteractionPredicate()
Definition at line 8 of file Density.cpph.
References assertion2, density_kernel(), and densityKernelEvaluatePairInteractionPredicate().
densityKernelEvaluatePairInteractionPredicate()
template<typename Particle > bool swift2::kernels::legacy::densityKernelEvaluatePairInteractionPredicate (const peano4::datamanagement::CellMarker & marker, const Particle & localParticle, const Particle & activeParticle)
Predicate if two particles contribute towards the density checks.
This predicate assumes that swift2::kernels::localParticleCanBeUpdatedInCellKernel() holds. It then evaluates if activeParticle contributes towards localParticle. Is used by the densityKernel() to find out if the actual density calculation is to be invoked, but can also be used as explicit check in combination with densityKernelWithoutChecks().
Optimisation
The comparison of radii has to be done by comaring the squares, as we otherwise would need a square root.
swift2::kernels::localParticleCanBeUpdatedInCellKernel<globaldata::HydroPart>
Definition at line 29 of file Density.cpph.
References assertion1, densityKernelUpdateParticlePredicate(), dx, tarch::la::greater(), hi, tarch::la::norm2Squared(), and tarch::la::smaller().
Referenced by densityKernel().
densityKernelUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::densityKernelUpdateParticlePredicate (const peano4::datamanagement::CellMarker & marker, const bool & localParticleIsContainedInCell, const Particle & localParticle)
Predicate to decide if to update a particle according to density kernel.
This is an implementation of the concept UpdateParticleAssignedToCellPredicate() for densityKernel(), i.e. should be used in combination with the latter.
The function delegates to swift2::kernels::localParticleCanBeUpdatedInCellKernel() and combines it with localParticle.getSmoothingLengthConverged(): We only consider updating a particles if its smoothing length computation has not yet converged.
Definition at line 19 of file Density.cpph.
Referenced by densityKernelEvaluatePairInteractionPredicate().
endDensityCalculation()
template<typename Particle > void swift2::kernels::legacy::endDensityCalculation (const peano4::datamanagement::VertexMarker & marker, Particle & localParticle)
Definition at line 58 of file Density.h.
References assertion, endDensityCalculationUpdateParticlePredicate(), and hydro_end_density().
endDensityCalculationUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::endDensityCalculationUpdateParticlePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & localParticle)
Definition at line 50 of file Density.h.
Referenced by endDensityCalculation().
endHydroForceCalculation()
template<typename Particle > void swift2::kernels::legacy::endHydroForceCalculation (const peano4::datamanagement::VertexMarker & marker, Particle & localParticle)
Definition at line 93 of file HydroForce.h.
References assertion, endHydroForceCalculationUpdateParticlePredicate(), and hydro_end_force().
endHydroForceCalculationUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::endHydroForceCalculationUpdateParticlePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & localParticle)
Definition at line 85 of file HydroForce.h.
Referenced by endHydroForceCalculation().
first_init_particle()
template<typename Particle > void swift2::kernels::legacy::first_init_particle (Particle * particle)
Initialise particles for the first time.
This method is intended to be called during startup only, not every simulation step.
Definition at line 5 of file Swift.cpph.
References hydro_init_particle(), and kernel_gamma_inv.
Referenced by firstInitParticle().
firstInitParticle()
template<typename Particle > void swift2::kernels::legacy::firstInitParticle (const peano4::datamanagement::VertexMarker & marker, Particle & particle)
Definition at line 75 of file Swift.h.
References assertion, first_init_particle(), and firstInitParticleParticleUpdatePredicate().
firstInitParticleParticleUpdatePredicate()
template<typename Particle > bool swift2::kernels::legacy::firstInitParticleParticleUpdatePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & particle)
In principle, we don't need to check for anything here, just overwrite particle data.
In practice, this messes with the dependency checks.
Definition at line 67 of file Swift.h.
References swift2::kernels::localParticleCanBeUpdatedInVertexKernel().
Referenced by firstInitParticle().
force_kernel()
template<typename Particle > void swift2::kernels::legacy::force_kernel (Particle * localParticle, const Particle * activeParticle)
The actual force kernel, which interacts a local particle and an active particle, and updates the local particle.
In this kernel, we accumulate the sums necessary for the force interactions between particles. In the "Minimal" SPH, by the end of it we're updating the velocity and the internal energy via
\(\frac{d\mathbf{v}_i}{dt} = - \sum_j m_j \left[ \frac{f_i P_i}{\rho_i^2} \nabla_x W(\mathbf{x}_{ij}, h_i) + \frac{f_j P_j}{\rho_j^2} \nabla_x W(\mathbf{x}_{ij}, h_j) + \nu_{ij} \overline{\nabla_x W_{ij}} \right] \)
and
\(\frac{du_i}{dt} = \sum_j m_j \left[ \frac{f_i P_i}{\rho_i^2} \mathbf{v}_{ij} \cdot \nabla_x W(\mathbf{x}_{ij}, h_i) + \frac{1}{2} \nu_{ij} \mathbf{v}_{ij} \cdot \overline{\nabla_x W_{ij}} \right] \)
where
\(\nu_{ij} = -\frac{1}{2} \frac{\alpha \mu_{ij} v_{sig,ij}}{\overline{\rho}_{ij}}\)
\(v_{sig,ij} = c_i + c_j - \beta \mu_{ij}\)
\(\mu_{ij} = \frac{\mathbf{v}_{ij} \cdot \mathbf{x}_{ij}}{|\mathbf{x}_{ij}|}\) if \(\mathbf{v}_{ij} \cdot \mathbf{x}_{ij} < 0\), or 0 otherwise
\(f_i = \left(1 + \frac{h_i}{3 \rho_i} \frac{\partial \rho_i}{\partial h_i} \right)^{-1} \)
\(c_i\): soundspeed of particle i
\(P_i\): pressure of particle i
\(\mathbf{x}_{ij} = \mathbf{x}_{i} - \mathbf{x}_{j} \)
\(\mathbf{v}_{ij} = \mathbf{v}_{i} - \mathbf{v}_{j} \)
\(\alpha, \beta \): user set viscosity coefficient. Usually 0 and 3, respectively.
\(\overline{\rho}_{ij} = \frac{1}{2} (\rho_i + \rho_j) \)
\(\overline{\nabla_x W}_{ij} = \frac{1}{2} (\nabla_x W_i + \nabla_x W_j) \)
For a kernel
\(W(\mathbf{x}_{ij}, h) = \frac{1}{h^d} f \left(\frac{\mathbf{x}_{ij}}{h} \right) = \frac{1}{h^d} f \left(q \right) \)
in \(d \) dimensions, we have
\(\nabla_x W(\mathbf{x}_{ij}, h) = \frac{1}{h^{d+1}} \frac{\partial f(q)}{\partial q} \frac{\mathbf{x}_{ij}}{|\mathbf{x}_{ij}|} \)
Vectorisation
This operation struggles to vectorise, as we have the statement
  if ((tarch::la::smaller(r, iactRi) or tarch::la::smaller(r, iactRj))
and tarch::la::greater(r, 0.0))
{
in there. This if statement encapsulates quite a lot of operations. The Intel compiler therefore cannot vectorise this routine anymore.
See also
forceKernelVectorised()
Definition at line 236 of file HydroForce.cpph.
References assertion3, assertion6, assertion9, tarch::la::dot(), dvdr, dx, tarch::la::greater(), tarch::la::isEntryNan(), kernel_deval(), mu_ij, tarch::la::norm2(), swift2::kernels::legacy::hydroDimensions::pow_dimension_plus_one(), r, r_inv, tarch::la::smaller(), and v_sig.
Referenced by forceKernel().
forceKernel()
template<typename Particle > void swift2::kernels::legacy::forceKernel (const peano4::datamanagement::CellMarker & marker, Particle & localParticle, const Particle & activeParticle)
Generic force kernel implementation.
Is to be used in combination with
forceKernelUpdateParticlePredicate() and
forceKernelEvaluatePairInteractionPredicate()
Definition at line 29 of file HydroForce.cpph.
References assertion2, force_kernel(), and swift2::kernels::localParticleCanBeUpdatedInCellKernelFromAnyOtherParticle().
forceKernelDistanceCheck()
template<typename Particle > bool swift2::kernels::legacy::forceKernelDistanceCheck (Particle *__restrict__ localParticle, const Particle *__restrict__ activeParticle)
Check distance between two particles.
First part of force kernel routine, where we check if two particles are close enough to actually interact. This routine also returns true if localParticle and activeParticle are the same. That is, it does not check for equality. Therefore, the routine has to be used with forceKernelVectorised() which in turn checks the distance interally but masks out zero distances.
forceKernelEvaluatePairInteractionPredicate()
template<typename Particle > bool swift2::kernels::legacy::forceKernelEvaluatePairInteractionPredicate (const peano4::datamanagement::CellMarker & marker, const Particle & localParticle, const Particle & activeParticle)
Definition at line 15 of file HydroForce.cpph.
References assertion3, tarch::la::NUMERICAL_ZERO_DIFFERENCE, and toolbox::particles::internal::relativeGrabOwnershipSpatialSortingTolerance().
forceKernelUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::forceKernelUpdateParticlePredicate (const peano4::datamanagement::CellMarker & marker, const bool & localParticleIsContainedInCell, const Particle & localParticle)
Definition at line 7 of file HydroForce.cpph.
hydro_compute_timestep()
template<typename Particle > double swift2::kernels::legacy::hydro_compute_timestep (Particle * particle)
Computes the SPH time step size.
May depend on SPH flavour.
@TODO: add cosmological factors.
Definition at line 9 of file Timestep.cpph.
References assertion1, assertion3, and v_sig.
Referenced by computeNextTimestep().
hydro_end_density()
template<typename Particle > void swift2::kernels::legacy::hydro_end_density (Particle * localParticle)
Finishes the density calculation.
Multiplies the density and number of neighbours by the appropiate constants and add the self-contribution term. Additional quantities such as velocity gradients will also get the final terms added to them here.
Also adds/multiplies the cosmological terms if need be. (Not implemented yet)
Definition at line 52 of file Density.cpph.
References assertion1, h_inv, kernel_root, and swift2::kernels::legacy::hydroDimensions::pow_dimension().
Referenced by endDensityCalculation().
hydro_end_force()
template<typename Particle > void swift2::kernels::legacy::hydro_end_force (Particle * localParticle)
Finishes the force calculation.
Multiplies the force and accelerations by the appropiate constants and add the self-contribution term. In most cases, there is little to do here.
Cosmological terms are also added/multiplied here.
Parameters
localParticle The particle to act upon
Definition at line 184 of file HydroForce.cpph.
References _log, assertion2, double, and logWarning.
Referenced by endHydroForceCalculation().
hydro_init_particle()
template<typename Particle > void swift2::kernels::legacy::hydro_init_particle (Particle * particle)
Prepares a particle for the density calculation.
Zeroes all the relevant arrays in preparation for the sums taking place in the various density loop over neighbours. Typically, all fields of the density sub-structure of a particle get zeroed in here.
Definition at line 59 of file Swift.cpph.
Referenced by first_init_particle(), and prepareDensity().
hydro_kick_extra_global_time_step_size()
template<typename Particle > void swift2::kernels::legacy::hydro_kick_extra_global_time_step_size (Particle * localParticle)
Kick the additional variables.
Additional hydrodynamic quantites are kicked forward in time here. These include thermal quantities (thermal energy or total energy or entropy, ...). The additional quantities being updated here depend on the exact SPH flavour being used.
Kick extra step, i.e. update some thermodynamic quantities forward in time. In particular, U is integrated forward in time treating it as the velocity.
Definition at line 137 of file Leapfrog.cpph.
References dt_kick_therm.
Referenced by leapfrog_kick_global_time_step_size(), and leapfrogKickExtraWithGlobalTimeStepSize().
hydro_predict_extra()
template<typename Particle > void swift2::kernels::legacy::hydro_predict_extra (Particle * localParticle)
Predict additional particle fields forward in time when drifting.
Additional hydrodynamic quantites are drifted forward in time here. These include thermal quantities (thermal energy or total energy or entropy, ...). Note that which and how quantities get updated depends on the specific SPH flavour.
Definition at line 27 of file Leapfrog.cpph.
References dt_therm, h_inv, pressure, soundspeed, and timeStepSize.
Referenced by hydroPredictExtra().
hydro_prepare_force()
template<typename Particle > void swift2::kernels::legacy::hydro_prepare_force (Particle * localParticle)
Prepare a particle for the force calculation.
Convert some quantities coming from the density loop over neighbours into quantities ready to be used in the force loop over neighbours. Quantities are typically read from the density sub-structure and written to the force sub-structure. Examples of calculations done here include the calculation of viscosity term constants, thermal conduction terms, hydro conversions, etc.
Definition at line 46 of file HydroForce.cpph.
References _log, tarch::la::abs(), assertion1, assertion6, h_inv, logWarning, tarch::la::norm2(), and soundspeed.
Referenced by prepareHydroForce().
hydro_reset_acceleration()
template<typename Particle > void swift2::kernels::legacy::hydro_reset_acceleration (Particle * localParticle)
Reset acceleration fields of a particle.
Resets all hydro acceleration and time derivative fields in preparation for the sums taking place in the various force interactions.
Definition at line 170 of file HydroForce.cpph.
Referenced by resetAcceleration().
hydro_reset_predicted_values()
template<typename Particle > void swift2::kernels::legacy::hydro_reset_predicted_values (Particle * localParticle)
Sets the values to be predicted in the drifts to their values at a kick time.
Definition at line 105 of file Leapfrog.cpph.
References pressure, and soundspeed.
Referenced by resetPredictedValues().
hydro_update_smoothing_length_and_rerun_if_required()
template<typename Particle > void swift2::kernels::legacy::hydro_update_smoothing_length_and_rerun_if_required (Particle * localParticle)
Derive smoothing length from density.
This routine is to be called directly after hydro_end_density. It updates the smoothing length according to the updated density quantities and then decides if the smoothing length computation has terminated with something reasonable. If not, the routine triggers an iteration rerun on this species. The rerun will mean that we recalculate the density (as it depends on the smoothing length) and then check again if we have converged.
The smoothing length is defined by a user-set parameter \(\eta \) which specifies it in units of the (local) mean interparticle separation:
\(h = \eta \langle x \rangle = \eta \left(\frac{1}{n(\mathbf{x})} \right)^{1/\nu} \)
where \(n \) is the local number density of particles (which is the same as the inverse of volume), and \(\nu \) is the number of dimensions of the problem.
This is, however, a circular definition: The local number density of particles is estimated via the smoothing length as
\(n_i = \sum_j W(r_{ij}, h_i)\) .
So we must solve this problem iteratively. We can rewrite the equation above as:
\(h^\nu n = \eta^\nu \Rightarrow h^\nu n - \eta^\nu = 0 \)
And use this equation as a function whose root we're trying to find: Let \(f(h) \) be
\(f(h) = h^\nu \sum_j W(r_{ij}, h_i) - \eta^\nu \)
It has an analytic derivative:
\(\frac{\partial f(h)}{\partial h} = \nu h^{\nu-1} \sum_j W(r_{ij}, h_i) + h^\nu \sum_j \frac{\partial W(r_{ij}, h_i)}{\partial h} \)
With an analytic function and its derivative, we make use of the Newton-Raphson iterative root finding method to find the \(h\) for which \(f(h) = 0 \).
Definition at line 6 of file SmoothingLength.cpph.
References _log, std::abs(), assertion4, assertion9, kernel_root, logError, logWarning, swift2::kernels::legacy::hydroDimensions::pow_dimension(), temp, and wcount.
Referenced by updateSmoothingLengthAndRerunIfRequired().
hydroPredictExtra()
template<typename Particle > void swift2::kernels::legacy::hydroPredictExtra (const peano4::datamanagement::VertexMarker & marker, Particle & localParticle)
Definition at line 87 of file Leapfrog.h.
References assertion, hydro_predict_extra(), and hydroPredictExtraUpdateParticlePredicate().
hydroPredictExtraUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::hydroPredictExtraUpdateParticlePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & localParticle)
Definition at line 79 of file Leapfrog.h.
Referenced by hydroPredictExtra().
leapfrog_drift_global_time_step_size()
template<typename Particle > void swift2::kernels::legacy::leapfrog_drift_global_time_step_size (Particle * particle)
Update a particle with the leapfrog KDK integrator.
The code should invoke this routine only in touchVertexLastTime(). It should never change the particle position throughout the mesh traversal, as it might introduce inconsistent particle data structure.
We do not update all particles but merely those which are labelled as local. Virtual particles are mere copies from another tree. We should not alter their states or positions. Any neighbour who is in charge of the particle should do this, and we then expect such a rank to send over a new copy. Drift step.
In this, we move the particles by a full time-step using:
\({\bf x}^{n+1} = {\bf x}^{n} + {\bf v}^{n+1/2}{\Delta t} \)
Notice that this operation modifies the particle topology and hence particles must be re-sorted before further operations can be executed.
It's important to take the "V_full" here, not the fluid velocity V. V_full doesn't get touched outside of kicks. V will be interpolated/ integrated in time as the time step progresses. V_full is the correct choice here.
Note that original SWIFT predicts the velocities at this point. We moved that into hydroPredictExtra().
Definition at line 11 of file Leapfrog.cpph.
References assertion1, tarch::la::isEntryFinite(), and timeStepSize.
Referenced by leapfrogDriftWithGlobalTimeStepSize().
leapfrog_kick_global_time_step_size()
template<typename Particle > void swift2::kernels::legacy::leapfrog_kick_global_time_step_size (Particle * particle)
Kick steps.
There are two kick steps in the KDK scheme, in which we update the particle velocity by a half-timestep using:
Kick1: \({\bf v}^{n+\frac{1}{2}} = {\bf v}^{n} + {\bf a}^{n}\frac{\Delta t}{2} \)
Kick2: \({\bf v}^{n+1} = {\bf v}^{n+\frac{1}{2}} + {\bf a}^{n+1}\frac{\Delta t}{2} \)
Additionally, thermal quantities are being updated. In the case of "Minimal" SPH, we update
Kick1: \({u}^{n+\frac{1}{2}} = u^{n} + \frac{\partial u}{\partial t}^{n}\frac{\Delta t}{2} \)
Kick2: \({u}^{n+1} = u^{n+\frac{1}{2}} + \frac{\partial u}{\partial t}^{n+1}\frac{\Delta t}{2} \)
The update of thermal quantities has been separated into hydro_kick_extra_global_time_step_size as it depends on the SPH flavour used, and needs to be replaceable.
Notice that the last kick in this sequence is implicit if \({\bf a}\) depends on \({\bf v}\) (e.g. due to artificial viscosity terms), which in principle requires extra treatments (see e.g. Price et al. 2017).
While the time integration scheme should be kick1 - drift - kick2, we do a slightly different sequence. First, we do a kick1 during initialization. Then every subsequent normal simulation step does a drift - kick2 - kick1 sequence. The reason for that is to permit individual time step sizes for individual particles: By starting the particle time step with a drift, we can always drift neighbours to their correct positions, even when they are inactive (= not being updated in the current step). The drifts are linear operations which in principle can be concatenated in any number, provided the total time a particle is being drifted sums up to the correct value. So for example, it should be equivalent to compute
\(K_1(\Delta t/2) \circ D(\Delta t) \circ K_2(\Delta t/2) \)
or
\(K_1(\Delta t/2) \circ D(\Delta t/4) \circ D(\Delta t/4) \circ D(\Delta t/4) \circ D(\Delta t/4) \circ K_2(\Delta t/2) \).
Once the kick2 operation is complete, the "predicted" values stemming from the "prediction" step in hydro_predict_extra() after a drift need to be reset to up-to-date current values that the particle carries. So after a kick2, we reset them using hydro_reset_predicted_values().
So in total, there are two additional steps that you have to add afterwards.
This version is tailored towards the SPH time integration, where we access additional particle fields which are otherwise not present, such as the time derivative of the internal energy.
Definition at line 89 of file Leapfrog.cpph.
References hydro_kick_extra_global_time_step_size().
Referenced by leapfrogKickWithGlobalTimeStepSize().
leapfrogDriftWithGlobalTimeStepSize()
template<typename Particle > void swift2::kernels::legacy::leapfrogDriftWithGlobalTimeStepSize (const peano4::datamanagement::VertexMarker & marker, Particle & localParticle)
Definition at line 62 of file Leapfrog.h.
References assertion2, leapfrog_drift_global_time_step_size(), and leapfrogDriftWithGlobalTimeStepSizeParticleUpdatePredicate().
leapfrogDriftWithGlobalTimeStepSizeParticleUpdatePredicate()
template<typename Particle > bool swift2::kernels::legacy::leapfrogDriftWithGlobalTimeStepSizeParticleUpdatePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & localParticle)
Definition at line 54 of file Leapfrog.h.
Referenced by leapfrogDriftWithGlobalTimeStepSize().
leapfrogKickExtraWithGlobalTimeStepSize()
template<typename Particle > void swift2::kernels::legacy::leapfrogKickExtraWithGlobalTimeStepSize (const peano4::datamanagement::VertexMarker & marker, Particle & localParticle)
Definition at line 189 of file Leapfrog.h.
References assertion, hydro_kick_extra_global_time_step_size(), and leapfrogKickExtraWithGlobalTimeStepSizeUpdateParticlePredicate().
leapfrogKickExtraWithGlobalTimeStepSizeUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::leapfrogKickExtraWithGlobalTimeStepSizeUpdateParticlePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & localParticle)
Definition at line 181 of file Leapfrog.h.
Referenced by leapfrogKickExtraWithGlobalTimeStepSize().
leapfrogKickWithGlobalTimeStepSize()
template<typename Particle > void swift2::kernels::legacy::leapfrogKickWithGlobalTimeStepSize (const peano4::datamanagement::VertexMarker & marker, Particle & localParticle)
Definition at line 160 of file Leapfrog.h.
References assertion, leapfrog_kick_global_time_step_size(), and leapfrogKickWithGlobalTimeStepSizeUpdateParticlePredicate().
leapfrogKickWithGlobalTimeStepSizeUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::leapfrogKickWithGlobalTimeStepSizeUpdateParticlePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & localParticle)
Definition at line 152 of file Leapfrog.h.
Referenced by leapfrogKickWithGlobalTimeStepSize().
predict_hyrdro()
template<typename Particle > void swift2::kernels::legacy::predict_hyrdro (Particle * particle)
Predict hydro terms (SWIFT) Relevant for inactive particles when using local-timestepping, but always used.
Referenced by predictHydro().
predictHydro()
template<typename Particle > void swift2::kernels::legacy::predictHydro (const peano4::datamanagement::VertexMarker & marker, Particle & localParticle)
Definition at line 231 of file HydroForce.h.
References assertion, predict_hyrdro(), and predictHydroUpdateParticlePredicate().
predictHydroUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::predictHydroUpdateParticlePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & localParticle)
Definition at line 222 of file HydroForce.h.
Referenced by predictHydro().
prepareDensity()
template<typename Particle > void swift2::kernels::legacy::prepareDensity (const peano4::datamanagement::VertexMarker & marker, Particle & localParticle)
Definition at line 27 of file Density.h.
References assertion, hydro_init_particle(), and prepareDensityUpdateParticlePredicate().
prepareDensityUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::prepareDensityUpdateParticlePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & localParticle)
Prepares a particle for the density calculation.
Definition at line 19 of file Density.h.
Referenced by prepareDensity().
prepareHydroForce()
template<typename Particle > void swift2::kernels::legacy::prepareHydroForce (const peano4::datamanagement::VertexMarker & marker, Particle & localParticle)
Definition at line 36 of file HydroForce.h.
References assertion, hydro_prepare_force(), and prepareHydroForceUpdateParticlePredicate().
prepareHydroForceUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::prepareHydroForceUpdateParticlePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & localParticle)
Definition at line 28 of file HydroForce.h.
Referenced by prepareHydroForce().
resetAcceleration()
template<typename Particle > void swift2::kernels::legacy::resetAcceleration (const peano4::datamanagement::VertexMarker & marker, Particle & localParticle)
Definition at line 62 of file HydroForce.h.
References assertion, hydro_reset_acceleration(), and resetAccelerationUpdateParticlePredicate().
resetAccelerationUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::resetAccelerationUpdateParticlePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & localParticle)
Definition at line 54 of file HydroForce.h.
Referenced by resetAcceleration().
resetPredictedValues()
template<typename Particle > void swift2::kernels::legacy::resetPredictedValues (const peano4::datamanagement::VertexMarker & marker, Particle & localParticle)
Definition at line 207 of file Leapfrog.h.
References assertion, hydro_reset_predicted_values(), and resetPredictedValuesUpdateParticlePredicate().
resetPredictedValuesUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::resetPredictedValuesUpdateParticlePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & localParticle)
Definition at line 202 of file Leapfrog.h.
Referenced by resetPredictedValues().
resetSmoothingLengthIterationCounter()
template<typename Particle > void swift2::kernels::legacy::resetSmoothingLengthIterationCounter (const peano4::datamanagement::VertexMarker & marker, Particle & particle)
Definition at line 112 of file SmoothingLength.h.
References assertion, and resetSmoothingLengthIterationCounterUpdateParticlePredicate().
resetSmoothingLengthIterationCounterUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::resetSmoothingLengthIterationCounterUpdateParticlePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & particle)
Reset smoothing length iteration related flags on a particle.
Definition at line 104 of file SmoothingLength.h.
Referenced by resetSmoothingLengthIterationCounter().
updateSmoothingLengthAndRerunIfRequired()
template<typename Particle > void swift2::kernels::legacy::updateSmoothingLengthAndRerunIfRequired (const peano4::datamanagement::VertexMarker & marker, Particle & localParticle)
Wrapper around hydro_update_smoothing_length_and_rerun_if_required() with only one argument.
Further to that, it also adds some consistency checks as discussed in the context of genericalgorithm remarks".
Definition at line 81 of file SmoothingLength.h.
References assertion, assertion2, hydro_update_smoothing_length_and_rerun_if_required(), tarch::la::min(), and updateSmoothingLengthAndRerunIfRequiredUpdateParticlePredicate().
updateSmoothingLengthAndRerunIfRequiredUpdateParticlePredicate()
template<typename Particle > bool swift2::kernels::legacy::updateSmoothingLengthAndRerunIfRequiredUpdateParticlePredicate (const peano4::datamanagement::VertexMarker & marker, const Particle & localParticle)
Definition at line 67 of file SmoothingLength.h.
Referenced by updateSmoothingLengthAndRerunIfRequired().