Peano
tarch::mpi::tests::StringTest Class Reference
Provides tests for types Vector, DynamicVector and all Vector functionality.
#include <StringTest.h>
Public Member Functions
StringTest ()
virtual void run () override
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testSendReceive ()
Tests constructors.
Static Private Attributes
static tarch::logging::Log _log
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Provides tests for types Vector, DynamicVector and all Vector functionality.
Definition at line 22 of file StringTest.h.
Constructor & Destructor Documentation
StringTest()
tarch::mpi::tests::StringTest::StringTest ()
Definition at line 9 of file StringTest.cpp.
Member Function Documentation
run()
void tarch::mpi::tests::StringTest::run () override virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 14 of file StringTest.cpp.
References testMethod.
testSendReceive()
void tarch::mpi::tests::StringTest::testSendReceive () private
Tests constructors.
Definition at line 19 of file StringTest.cpp.
References tarch::mpi::StringMessage::getData(), tarch::mpi::Rank::getInstance(), tarch::mpi::StringMessage::receive(), tarch::mpi::StringMessage::send(), tarch::mpi::StringMessage::setData(), tarch::mpi::StringMessage::toString(), and validateEqualsWithParams2.
Field Documentation
_log
tarch::logging::Log tarch::mpi::tests::StringTest::_log static private
Definition at line 24 of file StringTest.h.
The documentation for this class was generated from the following files:
src/tarch/mpi/tests/StringTest.h
src/tarch/mpi/tests/StringTest.cpp