Peano
Variant5.cpp File Reference
#include "exahype2/CellData.h"
#include "kernels/AderSolver/BufferSizes.h"
#include "kernels/AderSolver/FaceIntegral.h"
#include "kernels/AderSolver/FusedSpaceTimePredictorVolumeIntegral.h"
#include "kernels/AderSolver/MaxScaledEigenvalue.h"
#include "kernels/AderSolver/RiemannSolver.h"
#include "LRFaceData.h"
#include "repositories/SolverRepository.h"
#include "Utils.h"
#include "Variants.h"
#include <cstring>
Functions
void initialTask (exahype2::CellData< SolverPrecision, SolverPrecision > *myCellData, exahype2::FaceData< SolverPrecision, SolverPrecision > *myFaceData, const int cellId, const int faceId, tarch::timing::Measurement &measurement)
void firstTask (exahype2::FaceData< SolverPrecision, SolverPrecision > *myFaceData, const int leftFaceId, const int rightFaceId, const int faceDirection, tarch::timing::Measurement &measurement)
void secondTask (exahype2::CellData< SolverPrecision, SolverPrecision > *myCellData, exahype2::FaceData< SolverPrecision, SolverPrecision > *myFaceData, const int cellId, const int faceId, tarch::timing::Measurement &measurement)
Function Documentation
firstTask()
void firstTask (exahype2::FaceData< SolverPrecision, SolverPrecision > * myFaceData, const int leftFaceId, const int rightFaceId, const int faceDirection, tarch::timing::Measurement & measurement)
Definition at line 98 of file Variant5.cpp.
References exahype2::FaceData< inType, outType >::dt, exahype2::FaceData< inType, outType >::faceCentre, exahype2::FaceData< inType, outType >::faceSize, tarch::timing::Watch::getCalendarTime(), exahype2::FaceData< inType, outType >::QIn, exahype2::FaceData< inType, outType >::QOut, tarch::timing::Measurement::setValue(), tarch::timing::Watch::stop(), and exahype2::FaceData< inType, outType >::t.
Referenced by variant5::runBenchmarks().
initialTask()
void initialTask (exahype2::CellData< SolverPrecision, SolverPrecision > * myCellData, exahype2::FaceData< SolverPrecision, SolverPrecision > * myFaceData, const int cellId, const int faceId, tarch::timing::Measurement & measurement)
Definition at line 41 of file Variant5.cpp.
References exahype2::CellData< inType, outType, NumFaceTypes >::cellCentre, exahype2::CellData< inType, outType, NumFaceTypes >::cellSize, exahype2::CellData< inType, outType, NumFaceTypes >::dt, tarch::timing::Watch::getCalendarTime(), exahype2::FaceData< inType, outType >::QIn, exahype2::CellData< inType, outType, NumFaceTypes >::QIn, exahype2::FaceData< inType, outType >::QOut, tarch::timing::Measurement::setValue(), tarch::timing::Watch::stop(), and exahype2::CellData< inType, outType, NumFaceTypes >::t.
Referenced by variant5::runBenchmarks().
secondTask()
void secondTask (exahype2::CellData< SolverPrecision, SolverPrecision > * myCellData, exahype2::FaceData< SolverPrecision, SolverPrecision > * myFaceData, const int cellId, const int faceId, tarch::timing::Measurement & measurement)
Definition at line 132 of file Variant5.cpp.
References exahype2::CellData< inType, outType, NumFaceTypes >::cellCentre, exahype2::CellData< inType, outType, NumFaceTypes >::cellSize, exahype2::CellData< inType, outType, NumFaceTypes >::dt, tarch::timing::Watch::getCalendarTime(), exahype2::CellData< inType, outType, NumFaceTypes >::maxEigenvalue, exahype2::FaceData< inType, outType >::QIn, exahype2::CellData< inType, outType, NumFaceTypes >::QIn, exahype2::FaceData< inType, outType >::QOut, tarch::timing::Measurement::setValue(), tarch::timing::Watch::stop(), and exahype2::CellData< inType, outType, NumFaceTypes >::t.
Referenced by variant5::runBenchmarks().