Peano
GridTraversalEventGeneratorTest.cpp File Reference
#include "GridTraversalEventGeneratorTest.h"
#include "../GridTraversalEventGenerator.h"
#include "peano4/utils/Globals.h"
#include "peano4/utils/Loop.h"
#include "tarch/la/Vector.h"
Functions
state setLevel (0)
state setX (0.0)
state setH (1.0)
state setInverted (false)
state setEvenFlags (0)
Variables
AutomatonState state
Function Documentation
setEvenFlags()
state setEvenFlags (0)
Referenced by peano4::grid::AutomatonState::AutomatonState(), and peano4::grid::AutomatonState::operator=().
setH()
state setH (1. 0)
Referenced by peano4::grid::AutomatonState::AutomatonState(), peano4::grid::GridTraversalEvent::GridTraversalEvent(), and peano4::grid::AutomatonState::operator=().
setInverted()
state setInverted (false)
Referenced by peano4::grid::AutomatonState::AutomatonState(), and peano4::grid::AutomatonState::operator=().
setLevel()
state setLevel (0)
Referenced by peano4::grid::AutomatonState::AutomatonState(), peano4::grid::GridVertex::GridVertex(), peano4::grid::AutomatonState::operator=(), and peano4::grid::GridVertex::operator=().
setX()
state setX (0. 0)
Referenced by peano4::grid::AutomatonState::AutomatonState(), peano4::grid::GridTraversalEvent::GridTraversalEvent(), peano4::grid::GridVertex::GridVertex(), peano4::grid::GridVertex::GridVertex(), peano4::grid::AutomatonState::operator=(), and peano4::grid::GridVertex::operator=().
Variable Documentation
state
AutomatonState state
Definition at line 146 of file GridTraversalEventGeneratorTest.cpp.
Referenced by peano4::parallel::SpacetreeSet::addSpacetree(), peano4::parallel::SpacetreeSet::answerQuestions(), peano4::grid::GridTraversalEventGenerator::createEnterCellTraversalEvent(), peano4::grid::GridTraversalEventGenerator::createGenericCellTraversalEvent(), peano4::grid::GridTraversalEventGenerator::createLeaveCellTraversalEvent(), peano4::grid::createVertex(), peano4::grid::Spacetree::descend(), peano4::grid::Spacetree::evaluateGridControlEvents(), peano4::grid::GridTraversalEventGenerator::getAdjacentRanksOfFace(), peano4::grid::PeanoCurve::getCellReadStackNumber(), peano4::grid::PeanoCurve::getCellWriteStackNumber(), peano4::grid::PeanoCurve::getFaceReadStackNumber(), peano4::grid::PeanoCurve::getInputStackNumber(), peano4::grid::PeanoCurve::getLoopDirection(), exahype2::LoadBalancingConfiguration::getMaxLocalTreesPerRank(), peano4::grid::PeanoCurve::getOutputStackNumber(), peano4::grid::PeanoCurve::getVertexReadStackNumber(), peano4::grid::isContained(), peano4::grid::PeanoCurve::isTraversePositiveAlongAxis(), toolbox::loadbalancing::Statistics::notifyOfStateChange(), operator<<(), peano4::grid::overlaps(), peano4::grid::Spacetree::receiveAndMergeUserData(), SpacetreeSorter< Spacetree, PreSortCallback >::run(), peano4::grid::Spacetree::sendUserData(), peano4::grid::tests::GridTraversalEventGeneratorTest::testCreateGenericCellTraversalEvent1(), toString(), peano4::parallel::SpacetreeSet::toString(), and peano4::grid::toString().