Peano
plot_load_distribution Namespace Reference
Functions
get_ranks_and_threads (filename)
parse_file (filename, rank, verbose)
Returns tuple of (x_data,y_data_local,y_data_remote)
flatten (x_data, y_data)
x_data: [Float] Sequence of time stamps
compute_sums (x_data, y_data)
x_data: [Float] Sequence of time stamps
remove_duplicates (x_data, y_data)
plot_cells_per_rank (filename, verbose, plot_remote_cells, sum_per_rank, show_optimum, plot_local_cells=True)
plot_trees_per_rank (filename, verbose)
Variables
parser = argparse.ArgumentParser(description='Peano 4 load balancing plotter')
help
action
default
dest
False
True
choices
type
int
args = parser.parse_args()
base
ncol
bottom
str output_filename = args.file + "-cells-per-rank"
Function Documentation
compute_sums()
plot_load_distribution.compute_sums (x_data, y_data)
x_data: [Float] Sequence of time stamps
y_data: [[Float]] Multiple quantities per time stamp. There might be different numbers of quantities per time stamp.
We return a sequence [Float] with the sum of all entries per time stamp.
Definition at line 103 of file plot_load_distribution.py.
Referenced by plot_cells_per_rank().
flatten()
plot_load_distribution.flatten (x_data, y_data)
x_data: [Float] Sequence of time stamps
y_data: [[Float]] Multiple quantities per time stamp. There might be different numbers of quantities per time stamp.
We return a tuple [Float],[Float].
Definition at line 78 of file plot_load_distribution.py.
Referenced by plot_cells_per_rank().
get_ranks_and_threads()
plot_load_distribution.get_ranks_and_threads (filename)
Definition at line 10 of file plot_load_distribution.py.
References int.
Referenced by plot_cells_per_rank(), and plot_trees_per_rank().
parse_file()
plot_load_distribution.parse_file (filename, rank, verbose)
Returns tuple of (x_data,y_data_local,y_data_remote)
filename: String File to parse (what a surprise)
rank: int Rank number of extract data for (can be -1 if you run serially)
x_data: [Float] A series of time stamps
y_data_local: [[Float]] A set of series of corresponding cell count entries. Each entry within the list is an array again as there might be many trees per rank.
Definition at line 31 of file plot_load_distribution.py.
Referenced by plot_cells_per_rank(), and plot_trees_per_rank().
plot_cells_per_rank()
plot_load_distribution.plot_cells_per_rank (filename, verbose, plot_remote_cells, sum_per_rank, show_optimum, plot_local_cells = True)
Definition at line 136 of file plot_load_distribution.py.
References compute_sums(), flatten(), get_ranks_and_threads(), parse_file(), and remove_duplicates().
plot_trees_per_rank()
plot_load_distribution.plot_trees_per_rank (filename, verbose)
Definition at line 207 of file plot_load_distribution.py.
References get_ranks_and_threads(), and parse_file().
remove_duplicates()
plot_load_distribution.remove_duplicates (x_data, y_data)
Definition at line 125 of file plot_load_distribution.py.
Referenced by plot_cells_per_rank().
Variable Documentation
action
plot_load_distribution.action
Definition at line 247 of file plot_load_distribution.py.
args
plot_load_distribution.args = parser.parse_args()
Definition at line 253 of file plot_load_distribution.py.
base
plot_load_distribution.base
Definition at line 261 of file plot_load_distribution.py.
bottom
plot_load_distribution.bottom
Definition at line 279 of file plot_load_distribution.py.
choices
plot_load_distribution.choices
Definition at line 251 of file plot_load_distribution.py.
default
plot_load_distribution.default
Definition at line 247 of file plot_load_distribution.py.
dest
plot_load_distribution.dest
Definition at line 248 of file plot_load_distribution.py.
False
plot_load_distribution.False
Definition at line 248 of file plot_load_distribution.py.
help
plot_load_distribution.help
Definition at line 246 of file plot_load_distribution.py.
int
plot_load_distribution.int
Definition at line 252 of file plot_load_distribution.py.
Referenced by get_ranks_and_threads().
ncol
plot_load_distribution.ncol
Definition at line 265 of file plot_load_distribution.py.
output_filename
str plot_load_distribution.output_filename = args.file + "-cells-per-rank"
Definition at line 281 of file plot_load_distribution.py.
parser
plot_load_distribution.parser = argparse.ArgumentParser(description='Peano 4 load balancing plotter')
Definition at line 245 of file plot_load_distribution.py.
True
plot_load_distribution.True
Definition at line 250 of file plot_load_distribution.py.
type
plot_load_distribution.type
Definition at line 252 of file plot_load_distribution.py.