Peano
CCZ4Solver Namespace Reference
Data Structures
class AbstractCCZ4Solver
Abstract base class for any CCZ4 solver.
class CCZ4Solver_FD4_GlobalAdaptiveTimeStep
CCZ4 solver using fourth-order finite differences and global adaptive time stepping without enclave tasking.
class CCZ4Solver_FD4_GlobalAdaptiveTimeStepWithEnclaveTasking
CCZ4 solver using fourth-order finite differences and global adaptive time stepping incl enclave tasking.
class CCZ4Solver_FD4_SecondOrderFormulation_GlobalAdaptiveTimeStepWithEnclaveTasking
Variation of classic FD4 which relies on second order PDE formulation.
class CCZ4Solver_FV_GlobalAdaptiveTimeStep
CCZ4 solver using finite volumes and global adaptive time stepping incl enclave tasking.
class CCZ4Solver_FV_GlobalAdaptiveTimeStepWithEnclaveTasking
CCZ4 solver using finite volumes and global adaptive time stepping incl enclave tasking.
class CCZ4Solver_RKDG_GlobalAdaptiveTimeStep
CCZ4 solver using Runge-Kutta Discontinuous Galerkin and global adaptive time stepping incl enclave tasking.
class CCZ4Solver_RKDG_GlobalAdaptiveTimeStepWithEnclaveTasking
CCZ4 solver using Runge-Kutta Discontinuous Galerkin and global adaptive time stepping incl enclave tasking.
Functions
construct_FD4_ncp ()
construct_FV_ncp ()
construct_FD4_source_term ()
construct_FV_source_term ()
construct_FD4_eigenvalues ()
construct_FV_eigenvalues ()
construct_FD4_postprocessing_kernel ()
construct_FV_postprocessing_kernel ()
add_tracer_to_FV_solver (name, coordinates, project, solver, number_of_entries_between_two_db_flushes, data_delta_between_two_snapsots, time_delta_between_two_snapsots, clear_database_after_flush, tracer_unknowns)
Add tracer to project.
add_tracer_to_FD4_solver (name, coordinates, project, solver, number_of_entries_between_two_db_flushes, data_delta_between_two_snapsots, time_delta_between_two_snapsots, clear_database_after_flush, tracer_unknowns)
I realise this as a separate routine, as we need it for all FD4 flavours.
construct_DG_ncp ()
construct_DG_source_term ()
construct_DG_eigenvalues ()
construct_DG_postprocessing_kernel ()
add_tracer_to_DG_solver (name, coordinates, project, self, number_of_entries_between_two_db_flushes, data_delta_between_two_snapsots, time_delta_between_two_snapsots, clear_database_after_flush, tracer_unknowns)
Variables
auxiliary_variables
Function Documentation
add_tracer_to_DG_solver()
CCZ4Solver.add_tracer_to_DG_solver (name, coordinates, project, self, number_of_entries_between_two_db_flushes, data_delta_between_two_snapsots, time_delta_between_two_snapsots, clear_database_after_flush, tracer_unknowns)
Definition at line 1292 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_RKDG_GlobalAdaptiveTimeStepWithEnclaveTasking.add_tracer(), and CCZ4Solver.CCZ4Solver_RKDG_GlobalAdaptiveTimeStep.add_tracer().
add_tracer_to_FD4_solver()
CCZ4Solver.add_tracer_to_FD4_solver (name, coordinates, project, solver, number_of_entries_between_two_db_flushes, data_delta_between_two_snapsots, time_delta_between_two_snapsots, clear_database_after_flush, tracer_unknowns)
I realise this as a separate routine, as we need it for all FD4 flavours.
This is a wrapper around all the tracer handling. It adds the tracer to the exahype2.Project, but it also instantiates the solution to tracer mapping as well as the database bookkeeping.
Parameters
tracer_unknowns Integer You can set this variable to None. In this case, all variables are dumped.
Definition at line 630 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_FD4_GlobalAdaptiveTimeStepWithEnclaveTasking.add_tracer(), and CCZ4Solver.CCZ4Solver_FD4_GlobalAdaptiveTimeStep.add_tracer().
add_tracer_to_FV_solver()
CCZ4Solver.add_tracer_to_FV_solver (name, coordinates, project, solver, number_of_entries_between_two_db_flushes, data_delta_between_two_snapsots, time_delta_between_two_snapsots, clear_database_after_flush, tracer_unknowns)
Add tracer to project.
Consult exahype2.tracer.DumpTracerIntoDatabase for an explanation of some of the arguments. Most of them are simply piped through to this class.
I realise this as a separate routine, as we need it for all FV flavours
Definition at line 546 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_FV_GlobalAdaptiveTimeStep.add_tracer(), and CCZ4Solver.CCZ4Solver_FV_GlobalAdaptiveTimeStepWithEnclaveTasking.add_tracer().
construct_DG_eigenvalues()
CCZ4Solver.construct_DG_eigenvalues ()
Definition at line 1272 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_RKDG_GlobalAdaptiveTimeStepWithEnclaveTasking.__init__(), and CCZ4Solver.CCZ4Solver_RKDG_GlobalAdaptiveTimeStep.__init__().
construct_DG_ncp()
CCZ4Solver.construct_DG_ncp ()
Definition at line 1251 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_RKDG_GlobalAdaptiveTimeStepWithEnclaveTasking.__init__(), and CCZ4Solver.CCZ4Solver_RKDG_GlobalAdaptiveTimeStep.__init__().
construct_DG_postprocessing_kernel()
CCZ4Solver.construct_DG_postprocessing_kernel ()
Definition at line 1278 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_RKDG_GlobalAdaptiveTimeStepWithEnclaveTasking.__init__(), and CCZ4Solver.CCZ4Solver_RKDG_GlobalAdaptiveTimeStep.__init__().
construct_DG_source_term()
CCZ4Solver.construct_DG_source_term ()
Definition at line 1265 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_RKDG_GlobalAdaptiveTimeStepWithEnclaveTasking.__init__(), and CCZ4Solver.CCZ4Solver_RKDG_GlobalAdaptiveTimeStep.__init__().
construct_FD4_eigenvalues()
CCZ4Solver.construct_FD4_eigenvalues ()
Definition at line 506 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_FD4_GlobalAdaptiveTimeStepWithEnclaveTasking.__init__(), and CCZ4Solver.CCZ4Solver_FD4_GlobalAdaptiveTimeStep.__init__().
construct_FD4_ncp()
CCZ4Solver.construct_FD4_ncp ()
Definition at line 464 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_FD4_GlobalAdaptiveTimeStepWithEnclaveTasking.__init__(), and CCZ4Solver.CCZ4Solver_FD4_GlobalAdaptiveTimeStep.__init__().
construct_FD4_postprocessing_kernel()
CCZ4Solver.construct_FD4_postprocessing_kernel ()
Definition at line 518 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_FD4_GlobalAdaptiveTimeStepWithEnclaveTasking.__init__(), and CCZ4Solver.CCZ4Solver_FD4_GlobalAdaptiveTimeStep.__init__().
construct_FD4_source_term()
CCZ4Solver.construct_FD4_source_term ()
Definition at line 492 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_FD4_GlobalAdaptiveTimeStepWithEnclaveTasking.__init__(), and CCZ4Solver.CCZ4Solver_FD4_GlobalAdaptiveTimeStep.__init__().
construct_FV_eigenvalues()
CCZ4Solver.construct_FV_eigenvalues ()
Definition at line 512 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_FV_GlobalAdaptiveTimeStep.__init__(), and CCZ4Solver.CCZ4Solver_FV_GlobalAdaptiveTimeStepWithEnclaveTasking.__init__().
construct_FV_ncp()
CCZ4Solver.construct_FV_ncp ()
Definition at line 478 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_FV_GlobalAdaptiveTimeStep.__init__(), and CCZ4Solver.CCZ4Solver_FV_GlobalAdaptiveTimeStepWithEnclaveTasking.__init__().
construct_FV_postprocessing_kernel()
CCZ4Solver.construct_FV_postprocessing_kernel ()
Definition at line 532 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_FV_GlobalAdaptiveTimeStep.__init__(), and CCZ4Solver.CCZ4Solver_FV_GlobalAdaptiveTimeStepWithEnclaveTasking.__init__().
construct_FV_source_term()
CCZ4Solver.construct_FV_source_term ()
Definition at line 499 of file CCZ4Solver.py.
Referenced by CCZ4Solver.CCZ4Solver_FV_GlobalAdaptiveTimeStep.__init__(), and CCZ4Solver.CCZ4Solver_FV_GlobalAdaptiveTimeStepWithEnclaveTasking.__init__().
Variable Documentation
auxiliary_variables
CCZ4Solver.auxiliary_variables
Definition at line 1304 of file CCZ4Solver.py.