Peano
swift2::dastgenTest Namespace Reference
Functions
template<typename ParticleContainer >
void checkDastgen (ParticleContainer &assignedParticles)
Main testing function.
void checkBooleans (tests::swift2::dastgenTest::globaldata::dummyPart &particle)
Perform all the checks on a particle's boolean members.
void checkDoubles (tests::swift2::dastgenTest::globaldata::dummyPart &particle)
Perform all the checks on a particle's double members.
void checkEnums (tests::swift2::dastgenTest::globaldata::dummyPart &particle)
Perform all the checks on a particle's enum members.
void checkIntegers (tests::swift2::dastgenTest::globaldata::dummyPart &particle)
Perform all the checks on a particle's integer members.
void checkStrings (tests::swift2::dastgenTest::globaldata::dummyPart &particle)
Perform all the checks on a particle's string members.
void checkBooleanArrays (tests::swift2::dastgenTest::globaldata::dummyPart &particle)
Perform all the checks on a particle's boolean array members.
void checkDoubleArrays (tests::swift2::dastgenTest::globaldata::dummyPart &particle)
Perform all the checks on a particle's double array members.
void checkIntegerArrays (tests::swift2::dastgenTest::globaldata::dummyPart &particle)
Perform all the checks on a particle's integer array members.
void checkPeanoDoubleArrays (tests::swift2::dastgenTest::globaldata::dummyPart &particle)
Perform all the checks on a particle's double array members.
void checkPeanoIntegerArrays (tests::swift2::dastgenTest::globaldata::dummyPart &particle)
Perform all the checks on a particle's integer array members.
void checkUserDefinedType (tests::swift2::dastgenTest::globaldata::dummyPart &particle)
Perform all the checks on a particle's user defined types.
void checkConstructors ()
Check the constructor methods.
template<typename Particle >
void dummyMoveForwardInTime ()
A dummy function to move the simulation forward in time.
template<typename Particle >
void reportStep (const std::string &particleName)
Report time-step size and current time at the end of a step.
Function Documentation
checkBooleanArrays()
void swift2::dastgenTest::checkBooleanArrays (tests::swift2::dastgenTest::globaldata::dummyPart & particle)
Perform all the checks on a particle's boolean array members.
Definition at line 536 of file DastgenTest.cpp.
References assert.
Referenced by checkConstructors(), and checkDastgen().
checkBooleans()
void swift2::dastgenTest::checkBooleans (tests::swift2::dastgenTest::globaldata::dummyPart & particle)
Perform all the checks on a particle's boolean members.
Definition at line 4 of file DastgenTest.cpp.
References assert.
Referenced by checkConstructors(), and checkDastgen().
checkConstructors()
void swift2::dastgenTest::checkConstructors (void)
Check the constructor methods.
Definition at line 937 of file DastgenTest.cpp.
References assert, checkBooleanArrays(), checkBooleans(), checkDoubleArrays(), checkDoubles(), checkEnums(), checkIntegerArrays(), checkIntegers(), checkPeanoDoubleArrays(), checkPeanoIntegerArrays(), and checkStrings().
Referenced by checkDastgen().
checkDastgen()
template<typename ParticleContainer > void swift2::dastgenTest::checkDastgen (ParticleContainer & assignedParticles)
Main testing function.
Should call getters and setters for all available variables, where applicable. Also try constructor versions of particles.
Definition at line 8 of file DastgenTest.cpph.
References checkBooleanArrays(), checkBooleans(), checkConstructors(), checkDoubleArrays(), checkDoubles(), checkEnums(), checkIntegerArrays(), checkIntegers(), checkPeanoDoubleArrays(), checkPeanoIntegerArrays(), and checkStrings().
checkDoubleArrays()
void swift2::dastgenTest::checkDoubleArrays (tests::swift2::dastgenTest::globaldata::dummyPart & particle)
Perform all the checks on a particle's double array members.
Definition at line 615 of file DastgenTest.cpp.
References assert.
Referenced by checkConstructors(), and checkDastgen().
checkDoubles()
void swift2::dastgenTest::checkDoubles (tests::swift2::dastgenTest::globaldata::dummyPart & particle)
Perform all the checks on a particle's double members.
Definition at line 90 of file DastgenTest.cpp.
References assert.
Referenced by checkConstructors(), and checkDastgen().
checkEnums()
void swift2::dastgenTest::checkEnums (tests::swift2::dastgenTest::globaldata::dummyPart & particle)
Perform all the checks on a particle's enum members.
Definition at line 250 of file DastgenTest.cpp.
References assert.
Referenced by checkConstructors(), and checkDastgen().
checkIntegerArrays()
void swift2::dastgenTest::checkIntegerArrays (tests::swift2::dastgenTest::globaldata::dummyPart & particle)
Perform all the checks on a particle's integer array members.
Definition at line 693 of file DastgenTest.cpp.
References assert.
Referenced by checkConstructors(), and checkDastgen().
checkIntegers()
void swift2::dastgenTest::checkIntegers (tests::swift2::dastgenTest::globaldata::dummyPart & particle)
Perform all the checks on a particle's integer members.
Definition at line 293 of file DastgenTest.cpp.
References assert.
Referenced by checkConstructors(), and checkDastgen().
checkPeanoDoubleArrays()
void swift2::dastgenTest::checkPeanoDoubleArrays (tests::swift2::dastgenTest::globaldata::dummyPart & particle)
Perform all the checks on a particle's double array members.
Definition at line 771 of file DastgenTest.cpp.
References assert.
Referenced by checkConstructors(), and checkDastgen().
checkPeanoIntegerArrays()
void swift2::dastgenTest::checkPeanoIntegerArrays (tests::swift2::dastgenTest::globaldata::dummyPart & particle)
Perform all the checks on a particle's integer array members.
Definition at line 853 of file DastgenTest.cpp.
References assert.
Referenced by checkConstructors(), and checkDastgen().
checkStrings()
void swift2::dastgenTest::checkStrings (tests::swift2::dastgenTest::globaldata::dummyPart & particle)
Perform all the checks on a particle's string members.
Definition at line 453 of file DastgenTest.cpp.
References assert.
Referenced by checkConstructors(), and checkDastgen().
checkUserDefinedType()
void swift2::dastgenTest::checkUserDefinedType (tests::swift2::dastgenTest::globaldata::dummyPart & particle)
Perform all the checks on a particle's user defined types.
dummyMoveForwardInTime()
template<typename Particle > void swift2::dastgenTest::dummyMoveForwardInTime ()
A dummy function to move the simulation forward in time.
The time step size is hard-coded such that the sim runs for 2 steps.
Definition at line 30 of file DastgenTest.cpph.
reportStep()
template<typename Particle > void swift2::dastgenTest::reportStep (const std::string & particleName)
Report time-step size and current time at the end of a step.
Definition at line 38 of file DastgenTest.cpph.
References _log, tarch::mpi::Rank::getInstance(), and logInfo.