Peano
main.cpp File Reference
#include "config.h"
#include <fenv.h>
#include "peano4/parallel/Node.h"
#include "peano4/peano4.h"
#include "peano4/UnitTests.h"
#include "tarch/logging/ChromeTraceFileLogger.h"
#include "tarch/logging/CommandLineLogger.h"
#include "tarch/logging/Log.h"
#include "tarch/logging/LogFilter.h"
#include "tarch/mpi/Rank.h"
#include "tarch/multicore/Core.h"
#include "tarch/UnitTests.h"
Functions
int runTests ()
int main (int argc, char **argv)
Main routine of the SPH code.
Variables
tarch::logging::Log _log ("unittests")
Function Documentation
main()
int main (int argc, char ** argv)
Main routine of the SPH code.
Definition at line 118 of file main.cpp.
References tarch::logging::LogFilter::addFilterListEntry(), tarch::logging::LogFilter::FilterListEntry::AlwaysOn, tarch::logging::LogFilter::FilterListEntry::AnyRank, tarch::logging::LogFilter::FilterListEntry::BlackListEntry, tarch::logging::LogFilter::getInstance(), peano4::init(), runTests(), peano4::shutdown(), tarch::logging::LogFilter::FilterListEntry::TargetDebug, tarch::logging::LogFilter::FilterListEntry::TargetInfo, tarch::logging::LogFilter::FilterListEntry::TargetTrace, and tarch::logging::LogFilter::FilterListEntry::WhiteListEntry.
runTests()
int runTests ()
Definition at line 47 of file main.cpp.
References exahype2::getUnitTests(), peano4::getUnitTests(), swift2::getUnitTests(), tarch::getUnitTests(), toolbox::blockstructured::getUnitTests(), toolbox::finiteelements::getUnitTests(), toolbox::particles::assignmentchecks::getUnitTests(), toolbox::particles::getUnitTests(), logError, and logInfo.
Variable Documentation
_log
tarch::logging::Log _log("unittests") ("unittests")