Peano
tarch::plotter::PVDTimeSeriesWriter Class Reference
Writes time series in vtk/vtu format.
#include <PVDTimeSeriesWriter.h>
Public Types
enum class IndexFileMode { CreateNew , AppendNewData , NoIndexFile }
Static Public Member Functions
static void createEmptyIndexFile (const std::string &dataFile)
static void appendNewData (const std::string &snapshotFileName, const std::string &dataFile, double timeStamp)
static double getLatestTimeStepInIndexFile (std::string dataFile)
Static Private Member Functions
static std::tuple< double, int, std::vector< std::string > > parseFile (const std::string &filename, bool createBackup=true)
static void writeFile (const std::string &filename, const std::vector< std::string > &lines)
static void addFileTail (std::vector< std::string > &lines)
static void removeFileTail (std::vector< std::string > &lines)
static std::string createFileEntry (const std::string &snapshotFileName, double timestamp, int partCounter)
Detailed Description
Writes time series in vtk/vtu format.
According to the VTK spec, time series are solely written serially, i.e. you may use this class on any rank, but it only writes out data on Peano's global master.
Please note that this file format does not work with VTK files. It only works with the XML variants of the writer.
Definition at line 25 of file PVDTimeSeriesWriter.h.
Member Enumeration Documentation
IndexFileMode
enum class tarch::plotter::PVDTimeSeriesWriter::IndexFileMode strong
Enumerator
CreateNew
Create new meta file.
If a meta data file exists already, we overwrite it.
AppendNewData
Add new data.
This usually adds a new file to the current snapshot (time step).
NoIndexFile
Don't use a meta data file.
Definition at line 44 of file PVDTimeSeriesWriter.h.
Member Function Documentation
addFileTail()
void tarch::plotter::PVDTimeSeriesWriter::addFileTail (std::vector< std::string > & lines) static private
Definition at line 41 of file PVDTimeSeriesWriter.cpp.
appendNewData()
void tarch::plotter::PVDTimeSeriesWriter::appendNewData (const std::string & snapshotFileName, const std::string & dataFile, double timeStamp) static
Definition at line 116 of file PVDTimeSeriesWriter.cpp.
References tarch::la::equals(), logDebug, and timeStamp.
Referenced by tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VTKBinaryFileWriter(), tarch::plotter::griddata::unstructured::vtk::VTKTextFileWriter::VTKTextFileWriter(), and tarch::plotter::griddata::unstructured::vtk::VTUTextFileWriter::VTUTextFileWriter().
createEmptyIndexFile()
void tarch::plotter::PVDTimeSeriesWriter::createEmptyIndexFile (const std::string & dataFile) static
Parameters
dataFile First file entry to insert. Pass an empty string if you don't want Peano to add a file into the original index file.
See also
IndexFileMode
Definition at line 27 of file PVDTimeSeriesWriter.cpp.
Referenced by tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VTKBinaryFileWriter(), tarch::plotter::griddata::unstructured::vtk::VTKTextFileWriter::VTKTextFileWriter(), and tarch::plotter::griddata::unstructured::vtk::VTUTextFileWriter::VTUTextFileWriter().
createFileEntry()
std::string tarch::plotter::PVDTimeSeriesWriter::createFileEntry (const std::string & snapshotFileName, double timestamp, int partCounter) static private
Definition at line 110 of file PVDTimeSeriesWriter.cpp.
References logDebug.
getLatestTimeStepInIndexFile()
double tarch::plotter::PVDTimeSeriesWriter::getLatestTimeStepInIndexFile (std::string dataFile) static
Definition at line 16 of file PVDTimeSeriesWriter.cpp.
References logDebug, and parseFile().
Referenced by tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VTKBinaryFileWriter(), tarch::plotter::griddata::unstructured::vtk::VTKTextFileWriter::VTKTextFileWriter(), and tarch::plotter::griddata::unstructured::vtk::VTUTextFileWriter::VTUTextFileWriter().
parseFile()
std::tuple< double, int, std::vector< std::string > > tarch::plotter::PVDTimeSeriesWriter::parseFile (const std::string & filename, bool createBackup = true) static private
Returns
double Latest timestamp
int Counter of partitions in last snapshot
lines Set of lines
Definition at line 57 of file PVDTimeSeriesWriter.cpp.
References tarch::la::equals(), and tarch::la::smaller().
Referenced by getLatestTimeStepInIndexFile().
removeFileTail()
void tarch::plotter::PVDTimeSeriesWriter::removeFileTail (std::vector< std::string > & lines) static private
Definition at line 46 of file PVDTimeSeriesWriter.cpp.
writeFile()
void tarch::plotter::PVDTimeSeriesWriter::writeFile (const std::string & filename, const std::vector< std::string > & lines) static private
Parameters
lines content without the tail of the format, i.e. the closing brackets
Definition at line 98 of file PVDTimeSeriesWriter.cpp.
References logError.
The documentation for this class was generated from the following files:
src/tarch/plotter/PVDTimeSeriesWriter.h
src/tarch/plotter/PVDTimeSeriesWriter.cpp