Peano
tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter Class Reference
#include <VTKBinaryFileWriter.h>
Public Member Functions
virtual ~CellDataWriter ()
virtual void close () override
If you close your writer, each cell/vertex has to be assigned a value, i.e.
virtual void plotCell (int index, double value) override
Write data for one cell.
virtual void plotCell (int index, const tarch::la::Vector< 2, double > &value) override
virtual void plotCell (int index, const tarch::la::Vector< 3, double > &value) override
virtual void plotCell (int index, double *values, int numberOfValues) override
double getMinValue () const
double getMaxValue () const
virtual void assignRemainingCellsDefaultValues () override
Private Member Functions
CellDataWriter (const std::string &dataIdentifier, VTKBinaryFileWriter &writer, int recordsPerCell)
CellDataWriter (const CellDataWriter &copy)
Private Attributes
const std::string _identifier
Only required for assertions.
int _lastWriteCommandCellNumber
Is set to -1 in the beginning and then incremented by each data plot call.
VTKBinaryFileWriter & _myWriter
Underlying VTK writer.
std::stringstream _out
Output stream.
int _recordsPerCell
double _minValue
double _maxValue
Friends
class VTKBinaryFileWriter
The father class is a friend.
Detailed Description
Definition at line 236 of file VTKBinaryFileWriter.h.
Constructor & Destructor Documentation
CellDataWriter() [1/2]
tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::CellDataWriter (const std::string & dataIdentifier, VTKBinaryFileWriter & writer, int recordsPerCell) private
Definition at line 7 of file VTKBinaryFileWriter_CellDataWriter.cpp.
References tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::_doubleOrFloat, _myWriter, _out, _recordsPerCell, and assertion.
CellDataWriter() [2/2]
tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::CellDataWriter (const CellDataWriter & copy) private
Definition at line 271 of file VTKBinaryFileWriter.h.
References assertion.
~CellDataWriter()
tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::~CellDataWriter () virtual
Reimplemented from tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellDataWriter.
Definition at line 29 of file VTKBinaryFileWriter_CellDataWriter.cpp.
Member Function Documentation
assignRemainingCellsDefaultValues()
void tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::assignRemainingCellsDefaultValues () override virtual
See also
close()
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellDataWriter.
Definition at line 36 of file VTKBinaryFileWriter_CellDataWriter.cpp.
References assertion4.
close()
void tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::close () override virtual
If you close your writer, each cell/vertex has to be assigned a value, i.e.
you may not add less data than you have cells. See
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellDataWriter.
Definition at line 50 of file VTKBinaryFileWriter_CellDataWriter.cpp.
References assertion2, assertionMsg, and logWarning.
getMaxValue()
double tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::getMaxValue () const
Definition at line 298 of file VTKBinaryFileWriter_CellDataWriter.cpp.
getMinValue()
double tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::getMinValue () const
Definition at line 293 of file VTKBinaryFileWriter_CellDataWriter.cpp.
plotCell() [1/4]
void tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::plotCell (int index, const tarch::la::Vector< 2, double > & value) override virtual
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellDataWriter.
Definition at line 133 of file VTKBinaryFileWriter_CellDataWriter.cpp.
References assertion, assertion1, and tarch::plotter::byteSwapForParaviewBinaryFiles().
plotCell() [2/4]
void tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::plotCell (int index, const tarch::la::Vector< 3, double > & value) override virtual
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellDataWriter.
Definition at line 184 of file VTKBinaryFileWriter_CellDataWriter.cpp.
References assertion, assertion1, and tarch::plotter::byteSwapForParaviewBinaryFiles().
plotCell() [3/4]
void tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::plotCell (int index, double * values, int numberOfValues) override virtual
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellDataWriter.
Definition at line 245 of file VTKBinaryFileWriter_CellDataWriter.cpp.
References assertion, assertion1, and tarch::plotter::byteSwapForParaviewBinaryFiles().
plotCell() [4/4]
void tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::plotCell (int index, double value) override virtual
Write data for one cell.
Parameters
index Index of the cell. This index has to equal the index used for the cell within the VTKWriter class interface.
value Value for the cell.
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellDataWriter.
Definition at line 75 of file VTKBinaryFileWriter_CellDataWriter.cpp.
References assertion, assertion6, and tarch::plotter::byteSwapForParaviewBinaryFiles().
Friends And Related Symbol Documentation
VTKBinaryFileWriter
friend class VTKBinaryFileWriter friend
The father class is a friend.
There are no other friends.
Definition at line 242 of file VTKBinaryFileWriter.h.
Field Documentation
_identifier
const std::string tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::_identifier private
Only required for assertions.
Definition at line 247 of file VTKBinaryFileWriter.h.
_lastWriteCommandCellNumber
int tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::_lastWriteCommandCellNumber private
Is set to -1 in the beginning and then incremented by each data plot call.
If we close the writer, the counter is reset to -2.
Definition at line 253 of file VTKBinaryFileWriter.h.
_maxValue
double tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::_maxValue private
Definition at line 268 of file VTKBinaryFileWriter.h.
_minValue
double tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::_minValue private
Definition at line 267 of file VTKBinaryFileWriter.h.
_myWriter
VTKBinaryFileWriter& tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::_myWriter private
Underlying VTK writer.
Definition at line 258 of file VTKBinaryFileWriter.h.
Referenced by CellDataWriter().
_out
std::stringstream tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::_out private
Output stream.
Definition at line 263 of file VTKBinaryFileWriter.h.
Referenced by CellDataWriter().
_recordsPerCell
int tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::_recordsPerCell private
Definition at line 265 of file VTKBinaryFileWriter.h.
Referenced by CellDataWriter().
The documentation for this class was generated from the following files:
src/tarch/plotter/griddata/unstructured/vtk/VTKBinaryFileWriter.h
src/tarch/plotter/griddata/unstructured/vtk/VTKBinaryFileWriter_CellDataWriter.cpp