Peano
toolbox::blockstructured::tests::IandRVolumetricTest Class Reference
#include <IandRVolumetricTest.h>
Public Member Functions
IandRVolumetricTest ()
Cosntructor.
virtual ~IandRVolumetricTest ()=default
Destructor, empty.
virtual void run () override
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testMatrixInterpolation ()
void testSecondOrderInterpolation ()
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Definition at line 17 of file IandRVolumetricTest.h.
Constructor & Destructor Documentation
IandRVolumetricTest()
toolbox::blockstructured::tests::IandRVolumetricTest::IandRVolumetricTest ()
Cosntructor.
Definition at line 7 of file IandRVolumetricTest.cpp.
~IandRVolumetricTest()
virtual toolbox::blockstructured::tests::IandRVolumetricTest::~IandRVolumetricTest () virtual default
Destructor, empty.
Member Function Documentation
run()
void toolbox::blockstructured::tests::IandRVolumetricTest::run () override virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 11 of file IandRVolumetricTest.cpp.
References testMethod.
testMatrixInterpolation()
void toolbox::blockstructured::tests::IandRVolumetricTest::testMatrixInterpolation () private
Definition at line 22 of file IandRVolumetricTest.cpp.
References tarch::allocateMemory(), tarch::freeMemory(), tarch::Heap, toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_linear(), toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_matrix(), and validateNumericalEqualsWithEpsWithParams1.
testSecondOrderInterpolation()
void toolbox::blockstructured::tests::IandRVolumetricTest::testSecondOrderInterpolation () private
Definition at line 116 of file IandRVolumetricTest.cpp.
References double, toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_linear(), toolbox::blockstructured::interpolateCellDataAssociatedToVolumesIntoOverlappingCell_secondOrder(), and validateNumericalEqualsWithEpsWithParams1.
The documentation for this class was generated from the following files:
src/toolbox/blockstructured/tests/IandRVolumetricTest.h
src/toolbox/blockstructured/tests/IandRVolumetricTest.cpp