Peano
tarch::la::tests::LUDecompositionTest Class Reference
#include <LUDecompositionTest.h>
Public Member Functions
LUDecompositionTest ()
Constructor.
virtual ~LUDecompositionTest ()
Destructor, empty.
virtual void run ()
This routine is triggered by the TestCaseCollection.
virtual void setUp ()
Setup your test case.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testLUNoPivoting ()
void testLU ()
void testInversion0 ()
void testInversion1 ()
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Definition at line 15 of file LUDecompositionTest.h.
Constructor & Destructor Documentation
LUDecompositionTest()
tarch::la::tests::LUDecompositionTest::LUDecompositionTest ()
Constructor.
Definition at line 10 of file LUDecompositionTest.cpp.
~LUDecompositionTest()
virtual tarch::la::tests::LUDecompositionTest::~LUDecompositionTest () virtual
Destructor, empty.
Definition at line 36 of file LUDecompositionTest.h.
Member Function Documentation
run()
void tarch::la::tests::LUDecompositionTest::run () virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 15 of file LUDecompositionTest.cpp.
References testMethod.
setUp()
virtual void tarch::la::tests::LUDecompositionTest::setUp () virtual
Setup your test case.
Definition at line 46 of file LUDecompositionTest.h.
testInversion0()
void tarch::la::tests::LUDecompositionTest::testInversion0 () private
Definition at line 45 of file LUDecompositionTest.cpp.
References tarch::la::invert(), tarch::la::max(), and validateEquals.
testInversion1()
void tarch::la::tests::LUDecompositionTest::testInversion1 () private
Definition at line 69 of file LUDecompositionTest.cpp.
References tarch::la::invert(), tarch::la::max(), and validateEquals.
testLU()
void tarch::la::tests::LUDecompositionTest::testLU () private
Definition at line 27 of file LUDecompositionTest.cpp.
References tarch::la::lu(), tarch::la::max(), and validateEquals.
testLUNoPivoting()
void tarch::la::tests::LUDecompositionTest::testLUNoPivoting () private
Definition at line 23 of file LUDecompositionTest.cpp.
The documentation for this class was generated from the following files:
src/tarch/la/tests/LUDecompositionTest.h
src/tarch/la/tests/LUDecompositionTest.cpp