Peano
task.h File Reference
#include <omp.h>
#include <atomic>
#include <condition_variable>
#include <lang/assert.h>
#include <lang/channel.h>
#include <lang/thread_pool.h>
#include <lang/type.h>
Data Structures
struct TaskCtx
class OmpTaskBackend
class ThreadPoolTaskBackend
Concepts
concept CtxUnawareStatelessTask
concept CtxAwareStatelessTask
concept StatelessTask
concept OptionalStatelessTask
concept StatelessTaskGenerator
concept CtxUnawareStatefulTask
concept CtxAwareStatefulTask
concept StatefulTask
concept OptionalStatefulTask
concept StatefulTaskGenerator
Functions
StatefulTaskGenerator< Any > auto ToStatefulGenerator (StatelessTaskGenerator auto generator)
Function Documentation
ToStatefulGenerator()
StatefulTaskGenerator< Any > auto ToStatefulGenerator (StatelessTaskGenerator auto generator)
Definition at line 59 of file task.h.
Referenced by OmpTaskBackend::runParallelGenerator(), ThreadPoolTaskBackend::runParallelGenerator(), OmpTaskBackend::runSerialGenerator(), and ThreadPoolTaskBackend::runSerialGenerator().