Peano
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter Class Reference
#include <PeanoTextPatchFileWriter.h>
Public Member Functions
VertexDataWriter (const std::string &identifier, int unknownsPerAxis, int numberOfUnknowns, const std::string &description, const std::string &metaData, double *mapping, tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter &writer)
~VertexDataWriter ()
void setPrecision (int precision)
int getVerticesPerPatch () const
virtual void plotVertex (int index, double value) override
Write data for one cell.
virtual void plotVertex (int index, double *values) override
Paraview doesn't support extended precision.
template<typename T >
void plotVertex (int index, T *values)
virtual void close () override
virtual void assignRemainingVerticesDefaultValues () override
virtual int getFirstVertexWithinPatch (int index) const override
Protected Member Functions
void flushIfPatchIsComplete ()
Protected Attributes
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter & _writer
const std::string _identifier
const int _numberOfVerticesPerAxis
const int _numberOfUnknowns
int _entryCounter
Number of entries written within a patch.
std::stringstream _out
Detailed Description
Definition at line 165 of file PeanoTextPatchFileWriter.h.
Constructor & Destructor Documentation
VertexDataWriter()
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::VertexDataWriter (const std::string & identifier, int unknownsPerAxis, int numberOfUnknowns, const std::string & description, const std::string & metaData, double * mapping, tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter & writer)
Definition at line 6 of file PeanoTextPatchFileWriter_VertexDataWriter.cpp.
References _numberOfUnknowns, _numberOfVerticesPerAxis, _out, tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::_snapshotFileOut, _writer, getVerticesPerPatch(), tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::writeMapping(), and tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::writeMetaData().
~VertexDataWriter()
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::~VertexDataWriter () virtual
Reimplemented from tarch::plotter::griddata::blockstructured::PatchWriter::VertexDataWriter.
Definition at line 32 of file PeanoTextPatchFileWriter_VertexDataWriter.cpp.
Member Function Documentation
assignRemainingVerticesDefaultValues()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::assignRemainingVerticesDefaultValues () override virtual
See also
close()
Implements tarch::plotter::griddata::blockstructured::PatchWriter::VertexDataWriter.
Definition at line 88 of file PeanoTextPatchFileWriter_VertexDataWriter.cpp.
References assertionMsg.
close()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::close () override virtual
Implements tarch::plotter::griddata::blockstructured::PatchWriter::VertexDataWriter.
Definition at line 86 of file PeanoTextPatchFileWriter_VertexDataWriter.cpp.
flushIfPatchIsComplete()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::flushIfPatchIsComplete () protected
Definition at line 102 of file PeanoTextPatchFileWriter_VertexDataWriter.cpp.
Referenced by plotVertex().
getFirstVertexWithinPatch()
int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::getFirstVertexWithinPatch (int patchIndex) const override virtual
See also
plotVertex()
Implements tarch::plotter::griddata::blockstructured::PatchWriter::VertexDataWriter.
Definition at line 113 of file PeanoTextPatchFileWriter_VertexDataWriter.cpp.
getVerticesPerPatch()
int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::getVerticesPerPatch () const
Definition at line 40 of file PeanoTextPatchFileWriter_VertexDataWriter.cpp.
References tarch::la::aPowI().
Referenced by VertexDataWriter().
plotVertex() [1/3]
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::plotVertex (int index, double * values) override virtual
Paraview doesn't support extended precision.
So if the value in the array is "too small" for single precision, write a 0 into the plotter.
Implements tarch::plotter::griddata::blockstructured::PatchWriter::VertexDataWriter.
Definition at line 68 of file PeanoTextPatchFileWriter_VertexDataWriter.cpp.
References std::abs().
plotVertex() [2/3]
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::plotVertex (int index, double value) override virtual
Write data for one cell.
Parameters
index Index of the vertex. This index has to equal the index used for the cell within the VTKWriter class interface.
value Value for the cell.
Implements tarch::plotter::griddata::blockstructured::PatchWriter::VertexDataWriter.
Definition at line 44 of file PeanoTextPatchFileWriter_VertexDataWriter.cpp.
References std::abs(), and tarch::la::equals().
plotVertex() [3/3]
template<typename T > void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::plotVertex (int index, T * values)
Definition at line 3 of file PeanoTextPatchFileWriter_VertexDataWriter.cpph.
References _entryCounter, _numberOfUnknowns, _out, std::abs(), tarch::la::equals(), and flushIfPatchIsComplete().
setPrecision()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::setPrecision (int precision)
See also
https://www.cplusplus.com/reference/iomanip/setprecision/
Definition at line 34 of file PeanoTextPatchFileWriter_VertexDataWriter.cpp.
Field Documentation
_entryCounter
int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::_entryCounter protected
Number of entries written within a patch.
Definition at line 176 of file PeanoTextPatchFileWriter.h.
Referenced by plotVertex().
_identifier
const std::string tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::_identifier protected
Definition at line 169 of file PeanoTextPatchFileWriter.h.
_numberOfUnknowns
const int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::_numberOfUnknowns protected
Definition at line 171 of file PeanoTextPatchFileWriter.h.
Referenced by plotVertex(), and VertexDataWriter().
_numberOfVerticesPerAxis
const int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::_numberOfVerticesPerAxis protected
Definition at line 170 of file PeanoTextPatchFileWriter.h.
Referenced by VertexDataWriter().
_out
std::stringstream tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::_out protected
Definition at line 177 of file PeanoTextPatchFileWriter.h.
Referenced by plotVertex(), and VertexDataWriter().
_writer
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter& tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::_writer protected
Definition at line 167 of file PeanoTextPatchFileWriter.h.
Referenced by VertexDataWriter().
The documentation for this class was generated from the following files:
src/tarch/plotter/griddata/blockstructured/PeanoTextPatchFileWriter.h
src/tarch/plotter/griddata/blockstructured/PeanoTextPatchFileWriter_VertexDataWriter.cpp
src/tarch/plotter/griddata/blockstructured/PeanoTextPatchFileWriter_VertexDataWriter.cpph