Peano
tarch::plotter Namespace Reference
Namespaces
namespace griddata
namespace pointdata
Data Structures
class PVDTimeSeriesWriter
Writes time series in vtk/vtu format.
struct VectorCompare1e_12
struct VectorCompare1e_14
struct VectorCompare1e_4
struct VectorCompare1e_8
Functions
template<class InType >
InType byteSwap (const InType inVal)
Transform inVal vom little-endian into big-endian.
template<class InType >
InType byteSwapForParaviewBinaryFiles (const InType inVal)
Conditional swap.
Function Documentation
byteSwap()
template<class InType > InType tarch::plotter::byteSwap (const InType inVal)
Transform inVal vom little-endian into big-endian.
Paraview always requires all data to be stored as big-endian. However, many architectures used by Peano, e.g., are little-endian ones. Intel x86 architecture for example always is little-endian.
Definition at line 6 of file ByteSwap.cpph.
Referenced by byteSwapForParaviewBinaryFiles().
byteSwapForParaviewBinaryFiles()
template<class InType > InType tarch::plotter::byteSwapForParaviewBinaryFiles (const InType inVal)
Conditional swap.
This operation forwards to byteSwap if the system is a little-endian one. Otherwise, it reduces to identity.
Definition at line 20 of file ByteSwap.cpph.
References byteSwap().
Referenced by tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::plotCell(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::plotCell(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::plotCell(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellDataWriter::plotCell(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::plotHexahedron(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::plotLine(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::plotPoint(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::plotQuadrangle(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::plotTriangle(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexWriter::plotVertex(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::plotVertex(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::plotVertex(), tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::plotVertex(), and tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::plotVertex().