Peano
tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter Class Reference
Writes the element data.
#include <VTKBinaryFileWriter.h>
Public Member Functions
virtual ~CellWriter ()
virtual int plotHexahedron (int vertexIndex[8]) override
virtual int plotQuadrangle (int vertexIndex[4]) override
virtual int plotLine (int vertexIndex[2]) override
virtual int plotTriangle (int vertexIndex[3]) override
virtual int plotPoint (int vertexIndex) override
virtual void close () override
Private Member Functions
CellWriter (VTKBinaryFileWriter &writer)
CellWriter (const CellWriter &writer)
Private Attributes
int _currentCellNumber
Counter for the elements written.
VTKBinaryFileWriter & _myWriter
Underlying VTK writer.
int _cellListEntries
The tag CELLS in a vtk file requires the number of total entries in the following list of cell-interconnection (for a triangle, an entry could look like this: "3 1 2 4", which states that the triangle has 3 links to vetrices with indices 1, 2 and 4.
std::stringstream _cellOut
Output stream.
std::stringstream _cellTypeOut
Output stream.
Friends
class VTKBinaryFileWriter
The father class is a friend.
Detailed Description
Writes the element data.
Definition at line 171 of file VTKBinaryFileWriter.h.
Constructor & Destructor Documentation
CellWriter() [1/2]
tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::CellWriter (VTKBinaryFileWriter & writer) private
Definition at line 5 of file VTKBinaryFileWriter_CellWriter.cpp.
References _myWriter, tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::_numberOfCellEntries, tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::_numberOfCells, and assertion.
CellWriter() [2/2]
tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::CellWriter (const CellWriter & writer) private
Definition at line 212 of file VTKBinaryFileWriter.h.
References assertion.
~CellWriter()
tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::~CellWriter () virtual
Reimplemented from tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellWriter.
Definition at line 16 of file VTKBinaryFileWriter_CellWriter.cpp.
Member Function Documentation
close()
void tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::close () override virtual
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellWriter.
Definition at line 148 of file VTKBinaryFileWriter_CellWriter.cpp.
References assertion, and assertionMsg.
plotHexahedron()
int tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::plotHexahedron (int vertexIndex[8]) override virtual
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellWriter.
Definition at line 46 of file VTKBinaryFileWriter_CellWriter.cpp.
References assertion, and tarch::plotter::byteSwapForParaviewBinaryFiles().
plotLine()
int tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::plotLine (int vertexIndex[2]) override virtual
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellWriter.
Definition at line 98 of file VTKBinaryFileWriter_CellWriter.cpp.
References assertion, and tarch::plotter::byteSwapForParaviewBinaryFiles().
plotPoint()
int tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::plotPoint (int vertexIndex) override virtual
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellWriter.
Definition at line 23 of file VTKBinaryFileWriter_CellWriter.cpp.
References assertion, and tarch::plotter::byteSwapForParaviewBinaryFiles().
plotQuadrangle()
int tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::plotQuadrangle (int vertexIndex[4]) override virtual
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellWriter.
Definition at line 72 of file VTKBinaryFileWriter_CellWriter.cpp.
References assertion, and tarch::plotter::byteSwapForParaviewBinaryFiles().
plotTriangle()
int tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::plotTriangle (int vertexIndex[3]) override virtual
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::CellWriter.
Definition at line 123 of file VTKBinaryFileWriter_CellWriter.cpp.
References assertion, and tarch::plotter::byteSwapForParaviewBinaryFiles().
Friends And Related Symbol Documentation
VTKBinaryFileWriter
friend class VTKBinaryFileWriter friend
The father class is a friend.
There are no other friends.
Definition at line 177 of file VTKBinaryFileWriter.h.
Field Documentation
_cellListEntries
int tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::_cellListEntries private
The tag CELLS in a vtk file requires the number of total entries in the following list of cell-interconnection (for a triangle, an entry could look like this: "3 1 2 4", which states that the triangle has 3 links to vetrices with indices 1, 2 and 4.
this makes up four entries). For an unstructured mesh, the element type is not fixed and, hence, the total amount of list entries must be counted by summing up the contributions of each element, when adding the element.
Definition at line 198 of file VTKBinaryFileWriter.h.
_cellOut
std::stringstream tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::_cellOut private
Output stream.
Definition at line 203 of file VTKBinaryFileWriter.h.
_cellTypeOut
std::stringstream tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::_cellTypeOut private
Output stream.
Definition at line 208 of file VTKBinaryFileWriter.h.
_currentCellNumber
int tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::_currentCellNumber private
Counter for the elements written.
Holds the maximum index.
Definition at line 182 of file VTKBinaryFileWriter.h.
_myWriter
VTKBinaryFileWriter& tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::CellWriter::_myWriter private
Underlying VTK writer.
Definition at line 187 of file VTKBinaryFileWriter.h.
Referenced by CellWriter().
The documentation for this class was generated from the following files:
src/tarch/plotter/griddata/unstructured/vtk/VTKBinaryFileWriter.h
src/tarch/plotter/griddata/unstructured/vtk/VTKBinaryFileWriter_CellWriter.cpp