Peano
main.cpp File Reference
#include "MyObserver.h"
#include "tarch/logging/Log.h"
#include "tarch/logging/CommandLineLogger.h"
#include "tarch/logging/ChromeTraceFileLogger.h"
#include "tarch/logging/LogFilter.h"
#include "tarch/multicore/Core.h"
#include "tarch/mpi/Rank.h"
#include "peano4/peano4.h"
#include "peano4/grid/Spacetree.h"
#include "peano4/parallel/SpacetreeSet.h"
#include "peano4/parallel/Node.h"
#include "peano4/UnitTests.h"
#include "tarch/UnitTests.h"
Functions
void runTests ()
void runSerial ()
void updateDomainDecomposition ()
void runParallel ()
int main (int argc, char **argv)
Main routine of the SPH code.
Variables
tarch::logging::Log _log ("examples::grid")
std::bitset< Dimensions > periodicBC = 0
Function Documentation
main()
int main (int argc, char ** argv)
Main routine of the SPH code.
Definition at line 247 of file main.cpp.
References tarch::logging::LogFilter::addFilterListEntry(), tarch::logging::LogFilter::FilterListEntry::AnyRank, tarch::logging::CommandLineLogger::getInstance(), tarch::logging::LogFilter::getInstance(), tarch::multicore::Core::getInstance(), logInfo, periodicBC, runParallel(), runSerial(), runTests(), tarch::logging::CommandLineLogger::setOutputFile(), tarch::logging::LogFilter::FilterListEntry::TargetDebug, tarch::logging::LogFilter::FilterListEntry::TargetInfo, and tarch::logging::LogFilter::FilterListEntry::TargetTrace.
runParallel()
void runParallel ()
Definition at line 194 of file main.cpp.
References assertionEquals, tarch::logging::CommandLineLogger::closeOutputStreamAndReopenNewOne(), peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), tarch::logging::CommandLineLogger::getInstance(), tarch::mpi::Rank::getInstance(), examples::grid::MyObserver::GridRefinementIterations, logInfo, periodicBC, peano4::parallel::Node::setNextProgramStep(), examples::grid::MyObserver::StationaryIterations, toString(), peano4::parallel::SpacetreeSet::traverse(), and updateDomainDecomposition().
Referenced by main().
runSerial()
void runSerial ()
Definition at line 47 of file main.cpp.
References tarch::logging::CommandLineLogger::closeOutputStreamAndReopenNewOne(), tarch::logging::CommandLineLogger::getInstance(), examples::grid::MyObserver::GridRefinementIterations, logInfo, periodicBC, and examples::grid::MyObserver::StationaryIterations.
Referenced by main().
runTests()
void runTests ()
Definition at line 25 of file main.cpp.
References tarch::mpi::Rank::abort(), peano4::getUnitTests(), tarch::getUnitTests(), and logError.
Referenced by main().
updateDomainDecomposition()
void updateDomainDecomposition ()
Definition at line 96 of file main.cpp.
References peano4::parallel::SpacetreeSet::getGridStatistics(), peano4::parallel::SpacetreeSet::getInstance(), tarch::mpi::Rank::getInstance(), peano4::grid::GridStatistics::getNumberOfLocalUnrefinedCells(), tarch::mpi::Rank::getNumberOfRanks(), peano4::parallel::SpacetreeSet::isLocalSpacetree(), logInfo, periodicBC, peano4::parallel::SpacetreeSet::split(), and ThreePowerD.
Referenced by runParallel().
Variable Documentation
_log
tarch::logging::Log _log("examples::grid") ("examples::grid")
periodicBC
std::bitset<Dimensions> periodicBC = 0
Definition at line 19 of file main.cpp.
Referenced by toolbox::particles::applyPeriodicBoundaryConditions(), toolbox::particles::SieveParticles< T >::exchangeSieveListsGlobally(), toolbox::particles::ParticleSet< T >::finishedTraversal(), peano4::parallel::SpacetreeSet::init(), peano4::init(), main(), toolbox::particles::mirrorParticleAlongPeriodicDomains(), runParallel(), runSerial(), and updateDomainDecomposition().