Peano
toolbox::loadbalancing::LoadBalancer Class Reference
#include <LoadBalancer.h>
Public Member Functions
LoadBalancer (Configuration *configuration=new DefaultConfiguration)
~LoadBalancer ()
void enable (bool value)
bool isEnabled (bool globally) const
void update ()
int getGlobalNumberOfTrees () const
int getGlobalNumberOfInnerUnrefinedCells () const
bool hasStagnated () const
bool hasSplitRecently () const
std::string toString () const
Static Public Member Functions
static std::string getStatistics ()
Private Member Functions
void updateInterRankLoadBalancing ()
void updateIntraRankLoadBalancing ()
void triggerSplit (int numberOfCells, int targetRank)
Private Attributes
Configuration * _configuration
Blacklist _blacklist
Statistics _statistics
State _state
Static Private Attributes
static tarch::logging::Log _log
Detailed Description
Definition at line 17 of file LoadBalancer.h.
Constructor & Destructor Documentation
LoadBalancer()
toolbox::loadbalancing::LoadBalancer::LoadBalancer (Configuration * configuration = new DefaultConfiguration)
Definition at line 12 of file LoadBalancer.cpp.
References _state, _statistics, toolbox::loadbalancing::InterRankDistribution, and toolbox::loadbalancing::Statistics::notifyOfStateChange().
~LoadBalancer()
toolbox::loadbalancing::LoadBalancer::~LoadBalancer ()
Definition at line 21 of file LoadBalancer.cpp.
Member Function Documentation
enable()
void toolbox::loadbalancing::LoadBalancer::enable (bool value)
Definition at line 26 of file LoadBalancer.cpp.
References _state, toolbox::loadbalancing::InterRankBalancing, logDebug, and toolbox::loadbalancing::SwitchedOff.
getGlobalNumberOfInnerUnrefinedCells()
int toolbox::loadbalancing::LoadBalancer::getGlobalNumberOfInnerUnrefinedCells () const
Definition at line 65 of file LoadBalancer.cpp.
getGlobalNumberOfTrees()
int toolbox::loadbalancing::LoadBalancer::getGlobalNumberOfTrees () const
Definition at line 61 of file LoadBalancer.cpp.
getStatistics()
std::string toolbox::loadbalancing::LoadBalancer::getStatistics () static
Definition at line 179 of file LoadBalancer.cpp.
References peano4::parallel::SpacetreeSet::getGridStatistics(), peano4::parallel::SpacetreeSet::getInstance(), peano4::parallel::SpacetreeSet::getLocalSpacetrees(), peano4::grid::GridStatistics::getNumberOfLocalUnrefinedCells(), and peano4::grid::GridStatistics::getNumberOfRemoteUnrefinedCells().
Referenced by step().
hasSplitRecently()
bool toolbox::loadbalancing::LoadBalancer::hasSplitRecently () const
Definition at line 73 of file LoadBalancer.cpp.
hasStagnated()
bool toolbox::loadbalancing::LoadBalancer::hasStagnated () const
Definition at line 69 of file LoadBalancer.cpp.
References _state, toolbox::loadbalancing::Stagnation, and toolbox::loadbalancing::SwitchedOff.
isEnabled()
bool toolbox::loadbalancing::LoadBalancer::isEnabled (bool globally) const
Definition at line 38 of file LoadBalancer.cpp.
References _state, and toolbox::loadbalancing::SwitchedOff.
toString()
std::string toolbox::loadbalancing::LoadBalancer::toString () const
Definition at line 172 of file LoadBalancer.cpp.
References _state.
triggerSplit()
void toolbox::loadbalancing::LoadBalancer::triggerSplit (int numberOfCells, int targetRank) private
Definition at line 156 of file LoadBalancer.cpp.
References _state, peano4::parallel::SpacetreeSet::getInstance(), peano4::parallel::SpacetreeSet::getLocalSpacetrees(), logError, and peano4::parallel::SpacetreeSet::split().
update()
void toolbox::loadbalancing::LoadBalancer::update ()
Definition at line 42 of file LoadBalancer.cpp.
References _state, toolbox::loadbalancing::InterRankDistribution, toolbox::loadbalancing::IntraRankDistribution, logDebug, toolbox::loadbalancing::SwitchedOff, and toString().
updateInterRankLoadBalancing()
void toolbox::loadbalancing::LoadBalancer::updateInterRankLoadBalancing () private
Definition at line 77 of file LoadBalancer.cpp.
References _state, tarch::mpi::Rank::getInstance(), tarch::mpi::Rank::getNumberOfRanks(), toolbox::loadbalancing::IntraRankDistribution, tarch::mpi::Rank::isGlobalMaster(), and logDebug.
updateIntraRankLoadBalancing()
void toolbox::loadbalancing::LoadBalancer::updateIntraRankLoadBalancing () private
Definition at line 115 of file LoadBalancer.cpp.
References _state, tarch::mpi::Rank::getInstance(), tarch::multicore::Core::getInstance(), tarch::multicore::Core::getNumberOfThreads(), logDebug, and toolbox::loadbalancing::Stagnation.
Field Documentation
_blacklist
Blacklist toolbox::loadbalancing::LoadBalancer::_blacklist private
Definition at line 41 of file LoadBalancer.h.
_configuration
Configuration* toolbox::loadbalancing::LoadBalancer::_configuration private
Definition at line 40 of file LoadBalancer.h.
_log
tarch::logging::Log toolbox::loadbalancing::LoadBalancer::_log static private
Definition at line 38 of file LoadBalancer.h.
_state
State toolbox::loadbalancing::LoadBalancer::_state private
Definition at line 43 of file LoadBalancer.h.
Referenced by LoadBalancer().
_statistics
Statistics toolbox::loadbalancing::LoadBalancer::_statistics private
Definition at line 42 of file LoadBalancer.h.
Referenced by LoadBalancer().
The documentation for this class was generated from the following files:
src/toolbox/loadbalancing/LoadBalancer.h
src/toolbox/loadbalancing/LoadBalancer.cpp