Peano
Leaf Class Reference
#include <leaf.h>
Public Member Functions
Leaf ()
void init (BlockBoundary &a_boundary, uint modes[3])
std::string toString (int depth=0)
Block traverse ()
BlockBoundary traverse (int index[3])
BlockBoundary traverseProjection (double coordinate[3])
void checkInit ()
bool isLeaf () const
Private Attributes
bool isInit
BlockBoundary boundary
Detailed Description
Definition at line 7 of file leaf.h.
Constructor & Destructor Documentation
Leaf()
Leaf::Leaf ()
Definition at line 9 of file leaf.h.
References isInit.
Member Function Documentation
checkInit()
void Leaf::checkInit ()
Definition at line 48 of file leaf.h.
References isInit.
Referenced by toString(), traverse(), traverse(), and traverseProjection().
init()
void Leaf::init (BlockBoundary & a_boundary, uint modes[3]) virtual
Implements Node.
Definition at line 14 of file leaf.h.
References boundary, and isInit.
isLeaf()
bool Leaf::isLeaf () const
Definition at line 54 of file leaf.h.
toString()
std::string Leaf::toString (int depth = 0) virtual
Implements Node.
Definition at line 19 of file leaf.h.
References boundary, checkInit(), and BlockBoundary::toString().
traverse() [1/2]
Block Leaf::traverse () virtual
Implements Node.
Definition at line 31 of file leaf.h.
References boundary, and checkInit().
traverse() [2/2]
BlockBoundary Leaf::traverse (int index[3]) virtual
Implements Node.
Definition at line 38 of file leaf.h.
References boundary, and checkInit().
traverseProjection()
BlockBoundary Leaf::traverseProjection (double coordinate[3]) virtual
Implements Node.
Definition at line 43 of file leaf.h.
References boundary, and checkInit().
Field Documentation
boundary
BlockBoundary Leaf::boundary private
Definition at line 60 of file leaf.h.
Referenced by init(), toString(), traverse(), traverse(), and traverseProjection().
isInit
bool Leaf::isInit private
Definition at line 59 of file leaf.h.
Referenced by checkInit(), init(), and Leaf().
The documentation for this class was generated from the following file:
src/toolbox/curvi/kdTree/leaf.h