Peano
kernel_hydro.h File Reference
Kernel functions for SPH (scalar and vector version).
#include <config.h>
#include <math.h>
#include "dimension.h"
#include "error.h"
#include "inline.h"
#include "minmax.h"
#include "vector.h"
Macros
#define kernel_gamma_inv ((float)(1. / kernel_gamma))
#define kernel_gamma2 ((float)(kernel_gamma * kernel_gamma))
#define kernel_ivals_f ((float)(kernel_ivals))
#define kernel_root
#define kernel_norm ((float)(hydro_dimension_unit_sphere * kernel_gamma_dim))
Functions
__attribute__ ((always_inline)) INLINE static void kernel_deval(float u
Computes the kernel function and its derivative.
for (int k=2;k<=kernel_degree;k++) = x * w + coeffs[k]
for (int k=2;k< kernel_degree;k++) dw_dx
void hydro_kernel_dump (int N)
Test the SPH kernel function by dumping it in the interval [0,1].
Variables
float *restrict W = w * kernel_constant * kernel_gamma_inv_dim
float *restrict float *restrict dW_dx
const int temp = (int)(x * kernel_ivals_f)
const int ind = temp > kernel_ivals ? kernel_ivals : temp
const float *const coeffs = &kernel_coeffs[ind * (kernel_degree + 1)]
float w = coeffs[0] * x + coeffs[1]
float dw_dx = coeffs[0]
Detailed Description
Kernel functions for SPH (scalar and vector version).
All constants and kernel coefficients are taken from table 1 of Dehnen & Aly, MNRAS, 425, pp. 1062-1082 (2012).
Definition in file kernel_hydro.h.
Macro Definition Documentation
kernel_gamma2
#define kernel_gamma2 ((float)(kernel_gamma * kernel_gamma))
Definition at line 206 of file kernel_hydro.h.
kernel_gamma_inv
#define kernel_gamma_inv ((float)(1. / kernel_gamma))
Definition at line 205 of file kernel_hydro.h.
kernel_ivals_f
#define kernel_ivals_f ((float)(kernel_ivals))
Definition at line 233 of file kernel_hydro.h.
kernel_norm
#define kernel_norm ((float)(hydro_dimension_unit_sphere * kernel_gamma_dim))
Definition at line 241 of file kernel_hydro.h.
kernel_root
#define kernel_root
Value:
  ((float)(kernel_coeffs[kernel_degree]) * kernel_constant * \
   kernel_gamma_inv_dim)
Definition at line 236 of file kernel_hydro.h.
Function Documentation
__attribute__()
__attribute__ ((always_inline))
Computes the kernel function and its derivative.
Computes the kernel function derivative.
Computes the kernel function in double precision.
Computes the kernel function.
The kernel function needs to be mutliplied by \(h^{-d}\) and the gradient by \(h^{-(d+1)}\), where \(d\) is the dimensionality of the problem.
Returns 0 if \(u > \gamma = H/h\).
Parameters
u The ratio of the distance to the smoothing length \(u = x/h\).
W (return) The value of the kernel function \(W(x,h)\).
dW_dx (return) The norm of the gradient of \(|\nabla W(x,h)|\).
The kernel function needs to be mutliplied by \(h^{-d}\), where \(d\) is the dimensionality of the problem.
Returns 0 if \(u > \gamma = H/h\)
Parameters
u The ratio of the distance to the smoothing length \(u = x/h\).
W (return) The value of the kernel function \(W(x,h)\).
Required for computing the projected kernel because rounding error causes problems for the GSL integration function if we evaluate in single precision.
The kernel function needs to be mutliplied by \(h^{-d}\), where \(d\) is the dimensionality of the problem.
Returns 0 if \(u > \gamma = H/h\)
Parameters
u The ratio of the distance to the smoothing length \(u = x/h\).
W (return) The value of the kernel function \(W(x,h)\).
The kernel function needs to be mutliplied by \(h^{-d}\) and the gradient by \(h^{-(d+1)}\), where \(d\) is the dimensionality of the problem.
Returns 0 if \(u > \gamma = H/h\).
Parameters
u The ratio of the distance to the smoothing length \(u = x/h\).
dW_dx (return) The norm of the gradient of \(|\nabla W(x,h)|\).
for() [1/2]
for ()
We count faces starting with zero: Let the leftmost volume have the index i. i is typically 0 or -1 (if we have halos). When we call this routine for the index i, we first take the volume i and then we average it with i+1. So we look to the right. The result is stored in i. That means, all the indices are kind of shifted by 1/2 to the left. Index (4,3,2) is actually the face located at (4.5, 3, 2).
Definition at line 205 of file CustomRiemann.template.h.
References maxEigenvalueAfterTimeStep, QInFlattened, QOutFlattened, and TwoTimesD.
for() [2/2]
for (int k = 2;k<=kernel_degree;k++) = x * w + coeffs[k]
Definition at line 273 of file kernel_hydro.h.
References coeffs, dw_dx, and w.
hydro_kernel_dump()
void hydro_kernel_dump (int N)
Test the SPH kernel function by dumping it in the interval [0,1].
Parameters
N number of intervals in [0,1].
Definition at line 31 of file kernel_hydro.c.
References dw_dx, kernel_deval(), and w.
Variable Documentation
coeffs
const float *const coeffs = &kernel_coeffs[ind * (kernel_degree + 1)]
Definition at line 266 of file kernel_hydro.h.
Referenced by for(), swift2::kernels::legacy::kernelHydro::kernel_deval(), and swift2::kernels::legacy::kernelHydro::kernel_eval().
dW_dx
* dW_dx
Initial value:
{
  const float x = u * kernel_gamma_inv
Definition at line 258 of file kernel_hydro.h.
Referenced by swift2::kernels::legacy::kernelHydro::kernel_deval().
dw_dx
float dw_dx = coeffs[0]
Definition at line 270 of file kernel_hydro.h.
Referenced by for(), hydro_kernel_dump(), and swift2::kernels::legacy::kernelHydro::kernel_deval().
ind
const int ind = temp > kernel_ivals ? kernel_ivals : temp
Definition at line 265 of file kernel_hydro.h.
Referenced by toolbox::particles::assignmentchecks::internal::ParticleIdentifier::getVertexInd(), swift2::kernels::legacy::kernelHydro::kernel_deval(), and swift2::kernels::legacy::kernelHydro::kernel_eval().
temp
const int temp = (int)(x * kernel_ivals_f)
Definition at line 264 of file kernel_hydro.h.
Referenced by exahype2::fv::musclhancock::internal::computeTimeDerivative_LoopBody(), swift2::kernels::legacy::hydro_update_smoothing_length_and_rerun_if_required(), swift2::kernels::legacy::kernelHydro::kernel_deval(), swift2::kernels::legacy::kernelHydro::kernel_eval(), tarch::la::lu(), examples::exahype2::mgccz4::ncp(), tl::basic_iterator< C >::operator++(), swift2::kernels::legacy::hydroDimensions::pow_dimension_plus_one(), Face::reverseDimension(), examples::exahype2::mgccz4::source(), and applications::exahype2::ccz4::TestingOutput().
W
* W = w * kernel_constant * kernel_gamma_inv_dim
Definition at line 258 of file kernel_hydro.h.
Referenced by swift2::kernels::legacy::kernelHydro::kernel_deval(), and swift2::kernels::legacy::kernelHydro::kernel_eval().
w
double w = coeffs[0] * x + coeffs[1]
Definition at line 269 of file kernel_hydro.h.
Referenced by riemannSolver::boxcar(), ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::boxcar(), for(), hydro_kernel_dump(), Interpolation::Transfinite::interpolate3D(), swift2::kernels::legacy::kernelHydro::kernel_deval(), swift2::kernels::legacy::kernelHydro::kernel_eval(), and TP::Utilities::scalarproduct().