Peano
exahype2::fv::musclhancock Namespace Reference
Namespaces
namespace internal
Typedefs
typedef std::function< void(const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &volumeX, const tarch::la::Vector< Dimensions, double > &volumeH, double t, double dt, double *__restrict__ S) Source)
typedef std::function< void(const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &faceCentre, const tarch::la::Vector< Dimensions, double > &volumeH, double t, double dt, int normal, double *__restrict__ F) Flux)
typedef std::function< void(const double *__restrict__ Q, const double *__restrict__ deltaQ, const tarch::la::Vector< Dimensions, double > &faceCentre, const tarch::la::Vector< Dimensions, double > &volumeH, double t, double dt, int normal, double *__restrict__ BTimesDeltaQ) NonconservativeProduct)
typedef std::function< double(const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &faceCentre, const tarch::la::Vector< Dimensions, double > &volumeH, double t, double dt, int normal) MaxEigenvalue)
Functions
static void timeStepWithMusclHancock_patchwise_heap_functors (::exahype2::CellData< double, double > &patchData, int numberOfVolumesPerAxisInPatch, int haloSize, int unknowns, int auxiliaryVariables, bool evaluateFlux, bool evaluateNonconservativeProduct, bool evaluateSource, bool evaluateMaximumEigenvalueAfterTimeStep, Flux flux, NonconservativeProduct nonconservativeProduct, Source source, MaxEigenvalue maxEigenvalue)
Variables
constexpr int PickAllEntriesFromOutputVector = -1
Typedef Documentation
Flux
typedef std::function< void(const double * __restrict__ Q, const tarch::la::Vector<Dimensions,double>& faceCentre, const tarch::la::Vector<Dimensions,double>& volumeH, double t, double dt, int normal, double * __restrict__ F) exahype2::fv::musclhancock::Flux)
Definition at line 34 of file Functors.h.
MaxEigenvalue
typedef std::function< double(const double * __restrict__ Q, const tarch::la::Vector<Dimensions,double>& faceCentre, const tarch::la::Vector<Dimensions,double>& volumeH, double t, double dt, int normal) exahype2::fv::musclhancock::MaxEigenvalue)
Definition at line 54 of file Functors.h.
NonconservativeProduct
typedef std::function< void(const double * __restrict__ Q, const double * __restrict__ deltaQ, const tarch::la::Vector<Dimensions,double>& faceCentre, const tarch::la::Vector<Dimensions,double>& volumeH, double t, double dt, int normal, double * __restrict__ BTimesDeltaQ) exahype2::fv::musclhancock::NonconservativeProduct)
Definition at line 45 of file Functors.h.
Source
typedef std::function< void(const double * __restrict__ Q, const tarch::la::Vector<Dimensions,double>& volumeX, const tarch::la::Vector<Dimensions,double>& volumeH, double t, double dt, double * __restrict__ S) exahype2::fv::musclhancock::Source)
Definition at line 24 of file Functors.h.
Function Documentation
timeStepWithMusclHancock_patchwise_heap_functors()
void exahype2::fv::musclhancock::timeStepWithMusclHancock_patchwise_heap_functors (::exahype2::CellData< double, double > & patchData, int numberOfVolumesPerAxisInPatch, int haloSize, int unknowns, int auxiliaryVariables, bool evaluateFlux, bool evaluateNonconservativeProduct, bool evaluateSource, bool evaluateMaximumEigenvalueAfterTimeStep, Flux flux, NonconservativeProduct nonconservativeProduct, Source source, MaxEigenvalue maxEigenvalue) static
The halo size passed in by the user might differ from the one that we have to evaluate/ take into account from the solver's perspective.
Definition at line 5 of file MusclHancock_patchwise_functors.cpph.
References _log, tarch::allocateMemory(), assertionEquals, exahype2::CellData< inType, outType, NumFaceTypes >::cellCentre, exahype2::CellData< inType, outType, NumFaceTypes >::cellSize, exahype2::CellData< inType, outType, NumFaceTypes >::dt, tarch::freeMemory(), tarch::Heap, maxEigenvalue, exahype2::CellData< inType, outType, NumFaceTypes >::maxEigenvalue, nonconservativeProduct(), exahype2::CellData< inType, outType, NumFaceTypes >::numberOfCells, exahype2::CellData< inType, outType, NumFaceTypes >::QIn, exahype2::CellData< inType, outType, NumFaceTypes >::QOut, exahype2::enumerator::AoSLexicographicEnumerator::size(), and exahype2::CellData< inType, outType, NumFaceTypes >::t.
Variable Documentation
PickAllEntriesFromOutputVector
constexpr int exahype2::fv::musclhancock::PickAllEntriesFromOutputVector = -1 constexpr
Definition at line 19 of file LoopBody.h.