Peano
PETScMain.template.cpp File Reference
#include "{{MAIN_NAME}}.h"
#include "{{SUBDIRECTORY}}observers/Assemble.h"
#include "{{SUBDIRECTORY}}observers/CreateGrid.h"
#include "{{SUBDIRECTORY}}observers/EnumerateAndInitSolution.h"
#include "{{SUBDIRECTORY}}observers/MapSolutionOntoMesh.h"
#include "{{SUBDIRECTORY}}observers/Plot.h"
#include "{{SUBDIRECTORY}}observers/Solve.h"
#include "peano4/peano4.h"
#include "peano4/UnitTests.h"
#include "peano4/grid/Spacetree.h"
#include "peano4/parallel/SpacetreeSet.h"
#include "petsc/petsc.h"
#include "petsc/UnitTests.h"
#include "{{subdirectory}}repositories/DataRepository.h"
#include "{{subdirectory}}repositories/StepRepository.h"
#include "repositories/DataRepository.h"
#include "repositories/StepRepository.h"
#include "tarch/UnitTests.h"
#include "tarch/logging/Log.h"
#include "tarch/logging/LogFilter.h"
#include "tarch/logging/LogFilterFileReader.h"
#include "tarch/logging/Statistics.h"
#include "tarch/multicore/Core.h"
#include "tarch/multicore/multicore.h"
#include "tarch/multicore/otter.h"
#include "tarch/tests/TreeTestCaseCollection.h"
#include "tarch/timing/Measurement.h"
#include "tarch/timing/Watch.h"
#include "toolbox/finiteelements/UnitTests.h"
#include "toolbox/loadbalancing/loadbalancing.h"
#include <fenv.h>
Functions
bool selectNextAlgorithmicStep ()
void step ()
int main (int argc, char **argv)
Main routine of the SPH code.
Variables
tarch::logging::Log _log ("::")
tarch::timing::Measurement createGridMeasurement
tarch::timing::Measurement enumerateMeasurement
tarch::timing::Measurement initMeasurement
tarch::timing::Measurement assembleMeasurement
tarch::timing::Measurement solveMeasurement
tarch::timing::Measurement mapSolutionOntoMeshMeasurement
tarch::timing::Measurement plotMeasurement
Function Documentation
main()
int main (int argc, char ** argv)
Main routine of the SPH code.
Definition at line 265 of file PETScMain.template.cpp.
References assembleMeasurement, tarch::logging::Statistics::clear(), createGridMeasurement, enumerateMeasurement, tarch::timing::Measurement::getAccumulatedValue(), peano4::parallel::Node::getInstance(), tarch::logging::Statistics::getInstance(), tarch::mpi::Rank::getInstance(), peano4::init(), initMeasurement, petsc::initParallelEnvironment(), logInfo, logWarning, mapSolutionOntoMeshMeasurement, OTTER_FINALISE, OTTER_INITIALISE, tarch::logging::LogFilterFileReader::parsePlainTextFile(), plotMeasurement, selectNextAlgorithmicStep(), peano4::shutdown(), solveMeasurement, step(), tarch::timing::Measurement::toString(), and tarch::logging::Statistics::writeToCSV().
selectNextAlgorithmicStep()
bool selectNextAlgorithmicStep ()
Control of the parallel grid construction
Returns
continues to run
Definition at line 74 of file PETScMain.template.cpp.
References assertion, peano4::parallel::Node::getCurrentProgramStep(), peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), logInfo, and peano4::parallel::Node::setNextProgramStep().
Referenced by main().
step()
void step ()
Definition at line 158 of file PETScMain.template.cpp.
References _log, assembleMeasurement, assertion, createGridMeasurement, enumerateMeasurement, tarch::timing::Watch::getCalendarTime(), peano4::parallel::Node::getCurrentProgramStep(), peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), tarch::logging::LogFilter::getInstance(), tarch::mpi::Rank::getInstance(), initMeasurement, logInfo, mapSolutionOntoMeshMeasurement, plotMeasurement, tarch::timing::Measurement::setValue(), solveMeasurement, tarch::timing::Watch::start(), tarch::timing::Watch::stop(), tarch::logging::LogFilter::switchProgramPhase(), and peano4::parallel::SpacetreeSet::traverse().
Referenced by main().
Variable Documentation
_log
tarch::logging::Log _log("::") ("::")
Referenced by step().
assembleMeasurement
tarch::timing::Measurement assembleMeasurement
Definition at line 60 of file PETScMain.template.cpp.
Referenced by main(), and step().
createGridMeasurement
tarch::timing::Measurement createGridMeasurement
Definition at line 57 of file PETScMain.template.cpp.
Referenced by main(), and step().
enumerateMeasurement
tarch::timing::Measurement enumerateMeasurement
Definition at line 58 of file PETScMain.template.cpp.
Referenced by main(), and step().
initMeasurement
tarch::timing::Measurement initMeasurement
Definition at line 59 of file PETScMain.template.cpp.
Referenced by main(), and step().
mapSolutionOntoMeshMeasurement
tarch::timing::Measurement mapSolutionOntoMeshMeasurement
Definition at line 62 of file PETScMain.template.cpp.
Referenced by main(), and step().
plotMeasurement
tarch::timing::Measurement plotMeasurement
Definition at line 63 of file PETScMain.template.cpp.
Referenced by main(), and step().
solveMeasurement
tarch::timing::Measurement solveMeasurement
Definition at line 61 of file PETScMain.template.cpp.
Referenced by main(), and step().