Peano
peano4::parallel::StartTraversalMessage Struct Reference
#include <StartTraversalMessage.h>
Public Types
enum ObjectConstruction { NoData }
Public Member Functions
StartTraversalMessage ()
StartTraversalMessage (int __stepIdentifier)
int getStepIdentifier () const
void setStepIdentifier (int value)
StartTraversalMessage (const StartTraversalMessage &copy)=default
int getSenderRank () const
StartTraversalMessage (ObjectConstruction)
std::string toString () const
Static Public Member Functions
static MPI_Datatype getForkDatatype ()
Hands out MPI datatype if we work without the LLVM MPI extension.
static MPI_Datatype getJoinDatatype ()
static MPI_Datatype getBoundaryExchangeDatatype ()
static MPI_Datatype getMultiscaleDataExchangeDatatype ()
static MPI_Datatype getGlobalCommunciationDatatype ()
static void freeForkDatatype ()
static void freeJoinDatatype ()
static void freeBoundaryExchangeDatatype ()
static void freeMultiscaleDataExchangeDatatype ()
static void freeGlobalCommunciationDatatype ()
static void initDatatype ()
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
static void shutdownDatatype ()
Free the underlying MPI datatype.
static void send (const peano4::parallel::StartTraversalMessage &buffer, int destination, int tag, MPI_Comm communicator)
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
static void receive (peano4::parallel::StartTraversalMessage &buffer, int source, int tag, MPI_Comm communicator)
static void send (const peano4::parallel::StartTraversalMessage &buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
static void receive (peano4::parallel::StartTraversalMessage &buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
static void sendAndPollDanglingMessages (const peano4::parallel::StartTraversalMessage &message, int destination, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
static void receiveAndPollDanglingMessages (peano4::parallel::StartTraversalMessage &message, int source, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
Private Attributes
int _stepIdentifier
int _senderDestinationRank
Static Private Attributes
static MPI_Datatype Datatype = MPI_DATATYPE_NULL
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
Detailed Description
Definition at line 27 of file StartTraversalMessage.h.
Member Enumeration Documentation
ObjectConstruction
enum peano4::parallel::StartTraversalMessage::ObjectConstruction
Enumerator
NoData
Definition at line 112 of file StartTraversalMessage.h.
Constructor & Destructor Documentation
StartTraversalMessage() [1/4]
peano4::parallel::StartTraversalMessage::StartTraversalMessage ()
Definition at line 29 of file StartTraversalMessage.h.
StartTraversalMessage() [2/4]
peano4::parallel::StartTraversalMessage::StartTraversalMessage (int __stepIdentifier)
Definition at line 10 of file StartTraversalMessage.cpp.
References setStepIdentifier().
StartTraversalMessage() [3/4]
peano4::parallel::StartTraversalMessage::StartTraversalMessage (const StartTraversalMessage & copy) default
StartTraversalMessage() [4/4]
peano4::parallel::StartTraversalMessage::StartTraversalMessage (ObjectConstruction)
Definition at line 116 of file StartTraversalMessage.h.
Member Function Documentation
freeBoundaryExchangeDatatype()
void peano4::parallel::StartTraversalMessage::freeBoundaryExchangeDatatype () static
Definition at line 107 of file StartTraversalMessage.cpp.
freeForkDatatype()
void peano4::parallel::StartTraversalMessage::freeForkDatatype () static
Definition at line 80 of file StartTraversalMessage.cpp.
freeGlobalCommunciationDatatype()
void peano4::parallel::StartTraversalMessage::freeGlobalCommunciationDatatype () static
Definition at line 89 of file StartTraversalMessage.cpp.
freeJoinDatatype()
void peano4::parallel::StartTraversalMessage::freeJoinDatatype () static
Definition at line 98 of file StartTraversalMessage.cpp.
freeMultiscaleDataExchangeDatatype()
void peano4::parallel::StartTraversalMessage::freeMultiscaleDataExchangeDatatype () static
Definition at line 116 of file StartTraversalMessage.cpp.
getBoundaryExchangeDatatype()
MPI_Datatype peano4::parallel::StartTraversalMessage::getBoundaryExchangeDatatype () static
Definition at line 68 of file StartTraversalMessage.cpp.
getForkDatatype()
MPI_Datatype peano4::parallel::StartTraversalMessage::getForkDatatype () static
Hands out MPI datatype if we work without the LLVM MPI extension.
If we work with this additional feature, this is the routine where the lazy initialisation is done and the datatype is also cached.
Definition at line 50 of file StartTraversalMessage.cpp.
getGlobalCommunciationDatatype()
MPI_Datatype peano4::parallel::StartTraversalMessage::getGlobalCommunciationDatatype () static
Definition at line 56 of file StartTraversalMessage.cpp.
Referenced by peano4::parallel::tests::PingPongTest::testDaStGenArray().
getJoinDatatype()
MPI_Datatype peano4::parallel::StartTraversalMessage::getJoinDatatype () static
Definition at line 62 of file StartTraversalMessage.cpp.
getMultiscaleDataExchangeDatatype()
MPI_Datatype peano4::parallel::StartTraversalMessage::getMultiscaleDataExchangeDatatype () static
Definition at line 74 of file StartTraversalMessage.cpp.
getSenderRank()
int peano4::parallel::StartTraversalMessage::getSenderRank () const
Returns
The rank of the sender of an object. It only make ssense to call this routine after you've invoked receive with MPI_ANY_SOURCE.
Definition at line 124 of file StartTraversalMessage.cpp.
getStepIdentifier()
int peano4::parallel::StartTraversalMessage::getStepIdentifier () const
Definition at line 28 of file StartTraversalMessage.cpp.
Referenced by peano4::parallel::Node::continueToRun(), and peano4::parallel::tests::PingPongTest::testDaStGenTypeStartTraversalMessage().
initDatatype()
void peano4::parallel::StartTraversalMessage::initDatatype () static
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
Definition at line 129 of file StartTraversalMessage.cpp.
Referenced by peano4::parallel::Node::initMPIDatatypes().
receive() [1/2]
void peano4::parallel::StartTraversalMessage::receive (peano4::parallel::StartTraversalMessage & buffer, int source, int tag, MPI_Comm communicator) static
Definition at line 202 of file StartTraversalMessage.cpp.
References _senderDestinationRank.
Referenced by receiveAndPollDanglingMessages(), and peano4::parallel::tests::PingPongTest::testDaStGenTypeStartTraversalMessage().
receive() [2/2]
void peano4::parallel::StartTraversalMessage::receive (peano4::parallel::StartTraversalMessage & buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Definition at line 229 of file StartTraversalMessage.cpp.
References _senderDestinationRank.
receiveAndPollDanglingMessages()
void peano4::parallel::StartTraversalMessage::receiveAndPollDanglingMessages (peano4::parallel::StartTraversalMessage & message, int source, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 269 of file StartTraversalMessage.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), receive(), tarch::services::ServiceRepository::receiveDanglingMessages(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
Referenced by peano4::parallel::Node::continueToRun().
send() [1/2]
void peano4::parallel::StartTraversalMessage::send (const peano4::parallel::StartTraversalMessage & buffer, int destination, int tag, MPI_Comm communicator) static
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
However, this did not work with newer C++11 versions, as a member function using this as pointer usually doesn't see the vtable while the init sees the object from outside, i.e. including a vtable. So this routine now is basically an alias for a blocking MPI_Send.
Definition at line 197 of file StartTraversalMessage.cpp.
Referenced by sendAndPollDanglingMessages(), and peano4::parallel::tests::PingPongTest::testDaStGenTypeStartTraversalMessage().
send() [2/2]
void peano4::parallel::StartTraversalMessage::send (const peano4::parallel::StartTraversalMessage & buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
In systems with heavy MPI usage, this can help to avoid deadlocks.
Definition at line 209 of file StartTraversalMessage.cpp.
sendAndPollDanglingMessages()
void peano4::parallel::StartTraversalMessage::sendAndPollDanglingMessages (const peano4::parallel::StartTraversalMessage & message, int destination, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 252 of file StartTraversalMessage.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), tarch::services::ServiceRepository::receiveDanglingMessages(), send(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
Referenced by peano4::parallel::Node::continueToRun().
setStepIdentifier()
void peano4::parallel::StartTraversalMessage::setStepIdentifier (int value)
Definition at line 33 of file StartTraversalMessage.cpp.
Referenced by peano4::parallel::Node::continueToRun(), StartTraversalMessage(), peano4::parallel::tests::PingPongTest::testDaStGenArray(), and peano4::parallel::tests::PingPongTest::testDaStGenTypeStartTraversalMessage().
shutdownDatatype()
void peano4::parallel::StartTraversalMessage::shutdownDatatype () static
Free the underlying MPI datatype.
Definition at line 183 of file StartTraversalMessage.cpp.
Referenced by peano4::parallel::Node::shutdownMPIDatatypes().
toString()
std::string peano4::parallel::StartTraversalMessage::toString () const
Definition at line 16 of file StartTraversalMessage.cpp.
Referenced by peano4::parallel::Node::continueToRun(), and peano4::parallel::tests::PingPongTest::testDaStGenTypeStartTraversalMessage().
Field Documentation
_senderDestinationRank
int peano4::parallel::StartTraversalMessage::_senderDestinationRank private
Definition at line 132 of file StartTraversalMessage.h.
Referenced by receive(), and receive().
_stepIdentifier
int peano4::parallel::StartTraversalMessage::_stepIdentifier private
Definition at line 128 of file StartTraversalMessage.h.
Datatype
MPI_Datatype peano4::parallel::StartTraversalMessage::Datatype = MPI_DATATYPE_NULL static private
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
However, Peano calls init explicitly in most cases. Without the LLVM extension which caches the MPI datatype once constructed, this field stores the type.
Definition at line 141 of file StartTraversalMessage.h.
The documentation for this struct was generated from the following files:
src/peano4/parallel/StartTraversalMessage.h
src/peano4/parallel/StartTraversalMessage.cpp