var namespaceexahype2_1_1solvers_1_1aderdg_1_1AbstractSolverDeclarations =
[
    [ "AbstractSolverDeclarations", "d1/d70/classexahype2_1_1solvers_1_1aderdg_1_1AbstractSolverDeclarations_1_1AbstractSolverDeclarations.html", "d1/d70/classexahype2_1_1solvers_1_1aderdg_1_1AbstractSolverDeclarations_1_1AbstractSolverDeclarations" ]
];