Peano
plot-sedov-1d Namespace Reference
Functions
calc_a (g, nu=3)
exponents of the polynomials of the sedov solution g - the polytropic gamma nu - the dimension
calc_beta (v, g, nu=3)
beta values for the sedov solution (coefficients of the polynomials of the similarity variables) v - the similarity variable g - the polytropic gamma nu- the dimension
sedov (t, E0, rho0, g, n=1000, nu=3)
solve the sedov problem t - the time E0 - the initial energy rho0 - the initial density n - number of points (10000) nu - the dimension g - the polytropic gas gamma
Variables
dict font = {"size": 14}
family
usetex
str snapshot_dir = ""
snapshot_number = int(sys.argv[1])
files = sorted(glob.glob(snapshot_dir + "*.vtu"), key=len)
time_step_sim = float(sys.argv[2])
int snapshot_rate = 10
int time = float(snapshot_number) * snapshot_rate * time_step_sim
snapshot = files[snapshot_number]
mesh = meshio.read(snapshot)
pos = mesh.point_data["x"]
float x = pos[:, 0] - 0.5
float y = pos[:, 1] - 0.5
vel = mesh.point_data["v"]
vel_x = vel[:, 0]
vel_y = vel[:, 1]
r = np.sqrt(x**2 + y**2)
tuple v_r = (x * vel_x + y * vel_y) / r
density = mesh.point_data["density"][:, 0]
pressure = mesh.point_data["pressure"][:, 0]
mass = mesh.point_data["mass"][:, 0]
energy = mesh.point_data["u"][:, 0]
float E_ini = 1.0
E_kin = mass[0] * np.sum(0.5 * (vel_x**2 + vel_y**2))
E_int = mass[0] * np.sum(energy)
E_tot = E_kin + E_int
x_mask = np.greater_equal(x, 0)
int y_min = -1e-2
int y_max = 1e-2
y_mask = np.less_equal(y, y_max)
pos_mask = x_mask & y_mask
float x_line = x[pos_mask]
float y_line = y[pos_mask]
density_x = density[pos_mask]
pressure_x = pressure[pos_mask]
energy_x = energy[pos_mask]
vel_x_line = vel_x[pos_mask]
float rho_0 = 1.0
float P_0 = 1.0e-6
float u_0 = 1.0
float E_0 = E_ini
float gas_gamma = 5.0 / 3.0
r_s = np.insert(r_s, np.size(r_s), [r_shock, r_shock * 3])
P_s = np.insert(P_s, np.size(P_s), [P_0, P_0])
rho_s = np.insert(rho_s, np.size(rho_s), [rho_0, rho_0])
v_s = np.insert(v_s, np.size(v_s), [0, 0])
r_shock
_
u_s = P_s / (rho_s * (gas_gamma - 1.0))
float s_s = P_s / rho_s**gas_gamma
fig = plt.figure(figsize=(14, 12))
gs = gridspec.GridSpec(2, 2, height_ratios=[1, 1], wspace=0.3)
ax0 = plt.subplot(gs[0])
c
s
direction
top
True
right
ls
lw
zorder
fontsize
transform
ax1 = plt.subplot(gs[1])
ax2 = plt.subplot(gs[2])
ax3 = plt.subplot(gs[3])
bbox_inches
r_bin_edge = np.arange(0.0, 0.5, 0.005)
float r_bin = 0.5 * (r_bin_edge[1:] + r_bin_edge[:-1])
rho_bin
statistic
bins
v_bin
P_bin
u_bin
rho2_bin
v2_bin
P2_bin
u2_bin
rho_sigma_bin = np.sqrt(rho2_bin - rho_bin**2)
v_sigma_bin = np.sqrt(v2_bin - v_bin**2)
P_sigma_bin = np.sqrt(P2_bin - P_bin**2)
u_sigma_bin = np.sqrt(u2_bin - u_bin**2)
str line_color = "k"
str binned_color = "blue"
int binned_marker_size = 8
scatter_props
errorbar_props = dict(color=binned_color, ms=binned_marker_size, fmt=".", lw=1.5)
yerr
Function Documentation
calc_a()
plot-sedov-1d.calc_a (g, nu = 3)
exponents of the polynomials of the sedov solution g - the polytropic gamma nu - the dimension
Definition at line 104 of file plot-sedov-1d.py.
Referenced by sedov().
calc_beta()
plot-sedov-1d.calc_beta (v, g, nu = 3)
beta values for the sedov solution (coefficients of the polynomials of the similarity variables) v - the similarity variable g - the polytropic gamma nu- the dimension
Definition at line 126 of file plot-sedov-1d.py.
Referenced by sedov().
sedov()
plot-sedov-1d.sedov (t, E0, rho0, g, n = 1000, nu = 3)
solve the sedov problem t - the time E0 - the initial energy rho0 - the initial density n - number of points (10000) nu - the dimension g - the polytropic gas gamma
Definition at line 163 of file plot-sedov-1d.py.
References calc_a(), and calc_beta().
Variable Documentation
_
plot-sedov-1d._ protected
Definition at line 243 of file plot-sedov-1d.py.
ax0
plot-sedov-1d.ax0 = plt.subplot(gs[0])
Definition at line 262 of file plot-sedov-1d.py.
ax1
plot-sedov-1d.ax1 = plt.subplot(gs[1])
Definition at line 273 of file plot-sedov-1d.py.
ax2
plot-sedov-1d.ax2 = plt.subplot(gs[2])
Definition at line 281 of file plot-sedov-1d.py.
ax3
plot-sedov-1d.ax3 = plt.subplot(gs[3])
Definition at line 289 of file plot-sedov-1d.py.
bbox_inches
plot-sedov-1d.bbox_inches
Definition at line 300 of file plot-sedov-1d.py.
binned_color
str plot-sedov-1d.binned_color = "blue"
Definition at line 332 of file plot-sedov-1d.py.
binned_marker_size
int plot-sedov-1d.binned_marker_size = 8
Definition at line 333 of file plot-sedov-1d.py.
bins
plot-sedov-1d.bins
Definition at line 310 of file plot-sedov-1d.py.
c
plot-sedov-1d.c
Definition at line 263 of file plot-sedov-1d.py.
density
plot-sedov-1d.density = mesh.point_data["density"][:, 0]
Definition at line 63 of file plot-sedov-1d.py.
density_x
plot-sedov-1d.density_x = density[pos_mask]
Definition at line 89 of file plot-sedov-1d.py.
direction
plot-sedov-1d.direction
Definition at line 268 of file plot-sedov-1d.py.
E_0
float plot-sedov-1d.E_0 = E_ini
Definition at line 239 of file plot-sedov-1d.py.
E_ini
float plot-sedov-1d.E_ini = 1.0
Definition at line 69 of file plot-sedov-1d.py.
E_int
plot-sedov-1d.E_int = mass[0] * np.sum(energy)
Definition at line 71 of file plot-sedov-1d.py.
E_kin
plot-sedov-1d.E_kin = mass[0] * np.sum(0.5 * (vel_x**2 + vel_y**2))
Definition at line 70 of file plot-sedov-1d.py.
E_tot
plot-sedov-1d.E_tot = E_kin + E_int
Definition at line 72 of file plot-sedov-1d.py.
energy
plot-sedov-1d.energy = mesh.point_data["u"][:, 0]
Definition at line 66 of file plot-sedov-1d.py.
energy_x
plot-sedov-1d.energy_x = energy[pos_mask]
Definition at line 91 of file plot-sedov-1d.py.
errorbar_props
plot-sedov-1d.errorbar_props = dict(color=binned_color, ms=binned_marker_size, fmt=".", lw=1.5)
Definition at line 344 of file plot-sedov-1d.py.
family
plot-sedov-1d.family
Definition at line 26 of file plot-sedov-1d.py.
fig
plot-sedov-1d.fig = plt.figure(figsize=(14, 12))
Definition at line 259 of file plot-sedov-1d.py.
files
plot-sedov-1d.files = sorted(glob.glob(snapshot_dir + "*.vtu"), key=len)
Definition at line 37 of file plot-sedov-1d.py.
font
dict plot-sedov-1d.font = {"size": 14}
Definition at line 24 of file plot-sedov-1d.py.
fontsize
plot-sedov-1d.fontsize
Definition at line 271 of file plot-sedov-1d.py.
gas_gamma
float plot-sedov-1d.gas_gamma = 5.0 / 3.0
Definition at line 240 of file plot-sedov-1d.py.
gs
plot-sedov-1d.gs = gridspec.GridSpec(2, 2, height_ratios=[1, 1], wspace=0.3)
Definition at line 260 of file plot-sedov-1d.py.
line_color
plot-sedov-1d.line_color = "k"
Definition at line 331 of file plot-sedov-1d.py.
ls
plot-sedov-1d.ls
Definition at line 269 of file plot-sedov-1d.py.
lw
plot-sedov-1d.lw
Definition at line 269 of file plot-sedov-1d.py.
mass
plot-sedov-1d.mass = mesh.point_data["mass"][:, 0]
Definition at line 65 of file plot-sedov-1d.py.
mesh
plot-sedov-1d.mesh = meshio.read(snapshot)
Definition at line 50 of file plot-sedov-1d.py.
P2_bin
plot-sedov-1d.P2_bin
Definition at line 318 of file plot-sedov-1d.py.
P_0
float plot-sedov-1d.P_0 = 1.0e-6
Definition at line 237 of file plot-sedov-1d.py.
P_bin
plot-sedov-1d.P_bin
Definition at line 312 of file plot-sedov-1d.py.
P_s
plot-sedov-1d.P_s = np.insert(P_s, np.size(P_s), [P_0, P_0])
Definition at line 243 of file plot-sedov-1d.py.
P_sigma_bin
plot-sedov-1d.P_sigma_bin = np.sqrt(P2_bin - P_bin**2)
Definition at line 324 of file plot-sedov-1d.py.
pos
plot-sedov-1d.pos = mesh.point_data["x"]
Definition at line 55 of file plot-sedov-1d.py.
pos_mask
plot-sedov-1d.pos_mask = x_mask & y_mask
Definition at line 85 of file plot-sedov-1d.py.
pressure
plot-sedov-1d.pressure = mesh.point_data["pressure"][:, 0]
Definition at line 64 of file plot-sedov-1d.py.
pressure_x
plot-sedov-1d.pressure_x = pressure[pos_mask]
Definition at line 90 of file plot-sedov-1d.py.
r
plot-sedov-1d.r = np.sqrt(x**2 + y**2)
Definition at line 61 of file plot-sedov-1d.py.
r_bin
plot-sedov-1d.r_bin = 0.5 * (r_bin_edge[1:] + r_bin_edge[:-1])
Definition at line 309 of file plot-sedov-1d.py.
r_bin_edge
plot-sedov-1d.r_bin_edge = np.arange(0.0, 0.5, 0.005)
Definition at line 308 of file plot-sedov-1d.py.
r_s
plot-sedov-1d.r_s = np.insert(r_s, np.size(r_s), [r_shock, r_shock * 3])
Definition at line 243 of file plot-sedov-1d.py.
r_shock
plot-sedov-1d.r_shock
Definition at line 243 of file plot-sedov-1d.py.
rho2_bin
plot-sedov-1d.rho2_bin
Definition at line 314 of file plot-sedov-1d.py.
rho_0
plot-sedov-1d.rho_0 = 1.0
Definition at line 236 of file plot-sedov-1d.py.
rho_bin
plot-sedov-1d.rho_bin
Definition at line 310 of file plot-sedov-1d.py.
rho_s
plot-sedov-1d.rho_s = np.insert(rho_s, np.size(rho_s), [rho_0, rho_0])
Definition at line 243 of file plot-sedov-1d.py.
rho_sigma_bin
plot-sedov-1d.rho_sigma_bin = np.sqrt(rho2_bin - rho_bin**2)
Definition at line 322 of file plot-sedov-1d.py.
right
plot-sedov-1d.right
Definition at line 268 of file plot-sedov-1d.py.
s
plot-sedov-1d.s
Definition at line 264 of file plot-sedov-1d.py.
s_s
float plot-sedov-1d.s_s = P_s / rho_s**gas_gamma
Definition at line 253 of file plot-sedov-1d.py.
scatter_props
plot-sedov-1d.scatter_props
Initial value:
=  dict(
    color="red",
    marker=".",
    ms=3,
    markeredgecolor="none",
    alpha=0.5,
    zorder=-1,
    rasterized=True,
    linestyle="none",
)
Definition at line 334 of file plot-sedov-1d.py.
snapshot
plot-sedov-1d.snapshot = files[snapshot_number]
Definition at line 45 of file plot-sedov-1d.py.
snapshot_dir
str plot-sedov-1d.snapshot_dir = ""
Definition at line 35 of file plot-sedov-1d.py.
snapshot_number
plot-sedov-1d.snapshot_number = int(sys.argv[1])
Definition at line 36 of file plot-sedov-1d.py.
snapshot_rate
int plot-sedov-1d.snapshot_rate = 10
Definition at line 42 of file plot-sedov-1d.py.
statistic
plot-sedov-1d.statistic
Definition at line 310 of file plot-sedov-1d.py.
time
int plot-sedov-1d.time = float(snapshot_number) * snapshot_rate * time_step_sim
Definition at line 43 of file plot-sedov-1d.py.
time_step_sim
plot-sedov-1d.time_step_sim = float(sys.argv[2])
Definition at line 41 of file plot-sedov-1d.py.
top
plot-sedov-1d.top
Definition at line 268 of file plot-sedov-1d.py.
transform
plot-sedov-1d.transform
Definition at line 271 of file plot-sedov-1d.py.
True
plot-sedov-1d.True
Definition at line 268 of file plot-sedov-1d.py.
u2_bin
plot-sedov-1d.u2_bin
Definition at line 321 of file plot-sedov-1d.py.
u_0
float plot-sedov-1d.u_0 = 1.0
Definition at line 238 of file plot-sedov-1d.py.
u_bin
plot-sedov-1d.u_bin
Definition at line 313 of file plot-sedov-1d.py.
u_s
plot-sedov-1d.u_s = P_s / (rho_s * (gas_gamma - 1.0))
Definition at line 252 of file plot-sedov-1d.py.
u_sigma_bin
plot-sedov-1d.u_sigma_bin = np.sqrt(u2_bin - u_bin**2)
Definition at line 325 of file plot-sedov-1d.py.
usetex
plot-sedov-1d.usetex
Definition at line 27 of file plot-sedov-1d.py.
v2_bin
plot-sedov-1d.v2_bin
Definition at line 317 of file plot-sedov-1d.py.
v_bin
plot-sedov-1d.v_bin
Definition at line 311 of file plot-sedov-1d.py.
v_r
plot-sedov-1d.v_r = (x * vel_x + y * vel_y) / r
Definition at line 62 of file plot-sedov-1d.py.
v_s
plot-sedov-1d.v_s = np.insert(v_s, np.size(v_s), [0, 0])
Definition at line 243 of file plot-sedov-1d.py.
v_sigma_bin
plot-sedov-1d.v_sigma_bin = np.sqrt(v2_bin - v_bin**2)
Definition at line 323 of file plot-sedov-1d.py.
vel
plot-sedov-1d.vel = mesh.point_data["v"]
Definition at line 58 of file plot-sedov-1d.py.
vel_x
plot-sedov-1d.vel_x = vel[:, 0]
Definition at line 59 of file plot-sedov-1d.py.
vel_x_line
plot-sedov-1d.vel_x_line = vel_x[pos_mask]
Definition at line 92 of file plot-sedov-1d.py.
vel_y
plot-sedov-1d.vel_y = vel[:, 1]
Definition at line 60 of file plot-sedov-1d.py.
x
float plot-sedov-1d.x = pos[:, 0] - 0.5
Definition at line 56 of file plot-sedov-1d.py.
x_line
plot-sedov-1d.x_line = x[pos_mask]
Definition at line 87 of file plot-sedov-1d.py.
x_mask
plot-sedov-1d.x_mask = np.greater_equal(x, 0)
Definition at line 80 of file plot-sedov-1d.py.
y
float plot-sedov-1d.y = pos[:, 1] - 0.5
Definition at line 57 of file plot-sedov-1d.py.
y_line
float plot-sedov-1d.y_line = y[pos_mask]
Definition at line 88 of file plot-sedov-1d.py.
y_mask
plot-sedov-1d.y_mask = np.less_equal(y, y_max)
Definition at line 83 of file plot-sedov-1d.py.
y_max
int plot-sedov-1d.y_max = 1e-2
Definition at line 82 of file plot-sedov-1d.py.
y_min
int plot-sedov-1d.y_min = -1e-2
Definition at line 81 of file plot-sedov-1d.py.
yerr
plot-sedov-1d.yerr
Definition at line 349 of file plot-sedov-1d.py.
zorder
plot-sedov-1d.zorder
Definition at line 269 of file plot-sedov-1d.py.