Peano
Interpolation::Lagrange Class Reference
#include <lagrangeInterpolation.h>
Static Public Member Functions
static void interpolate3D (const double position[3], Block const &block, std::vector< int > range_z, std::vector< int > range_y, std::vector< int > range_x, double result[NCOORDS])
static void interpolate1D (double position, std::vector< double > nodes, std::vector< double > values, double result[NCOORDS])
static double lagrangePolynomial (double position, int i, std::vector< double > range)
static double uniformLagrangePolynomial (double position, int i, int range)
Static Private Member Functions
static std::vector< double > getUniformMesh (int range)
static double getLagrangeDenominator (int i, int range)
Detailed Description
Definition at line 9 of file lagrangeInterpolation.h.
Member Function Documentation
getLagrangeDenominator()
static double Interpolation::Lagrange::getLagrangeDenominator (int i, int range) static private
Definition at line 122 of file lagrangeInterpolation.h.
References getUniformMesh().
Referenced by uniformLagrangePolynomial().
getUniformMesh()
static std::vector< double > Interpolation::Lagrange::getUniformMesh (int range) static private
Definition at line 102 of file lagrangeInterpolation.h.
Referenced by getLagrangeDenominator(), and uniformLagrangePolynomial().
interpolate1D()
static void Interpolation::Lagrange::interpolate1D (double position, std::vector< double > nodes, std::vector< double > values, double result[NCOORDS]) static
Definition at line 47 of file lagrangeInterpolation.h.
References Index::getIndexRange(), lagrangePolynomial(), and NCOORDS.
Referenced by Edge::interpolate().
interpolate3D()
static void Interpolation::Lagrange::interpolate3D (const double position[3], Block const & block, std::vector< int > range_z, std::vector< int > range_y, std::vector< int > range_x, double result[NCOORDS]) static
Definition at line 11 of file lagrangeInterpolation.h.
References dx, NCOORDS, uniformLagrangePolynomial(), X, Y, and Z.
Referenced by Curvi::Interface::getElement(), and Block::interpolate().
lagrangePolynomial()
static double Interpolation::Lagrange::lagrangePolynomial (double position, int i, std::vector< double > range) static
Definition at line 67 of file lagrangeInterpolation.h.
Referenced by interpolate1D().
uniformLagrangePolynomial()
static double Interpolation::Lagrange::uniformLagrangePolynomial (double position, int i, int range) static
Definition at line 84 of file lagrangeInterpolation.h.
References getLagrangeDenominator(), and getUniformMesh().
Referenced by interpolate3D().
The documentation for this class was generated from the following file:
src/toolbox/curvi/interpolation/lagrangeInterpolation.h