Peano
tarch::la::ShallowMatrix< Rows, Cols, Scalar > Class Template Reference
Shallow matrix wrapping an existing array.
#include <ShallowMatrix.h>
Public Member Functions
ShallowMatrix (Scalar *values)
Constructs a non-initialized matrix.
ShallowMatrix (const ShallowMatrix &copy)
Shallow copy.
ShallowMatrix & operator= (const ShallowMatrix &copy)
Shallow copy.
int rows () const
Returns the number of rows in the matrix.
int cols () const
Returns the number of columns in the matrix.
int size () const
Returns the number of total elements in the matrix.
Scalar & operator() (int rowIndex, int colIndex)
Returns element at given row and column index (from 0..size-1).
const Scalar & operator() (int rowIndex, int colIndex) const
Returns const element at given row and column index (from 0..size-1).
std::string toString () const
std::string toPrettyString (int numberOfDigits=4) const
template<typename NewScalarType >
tarch::la::Matrix< Rows, Cols, NewScalarType > convertScalar () const
Convert the scalar type.
Scalar * data ()
Return pointer back to original data.
const Scalar * data () const
Private Attributes
Scalar * _values
Values of the matrix components.
Detailed Description
template<int Rows, int Cols, typename Scalar>
class tarch::la::ShallowMatrix< Rows, Cols, Scalar >
Shallow matrix wrapping an existing array.
You are in charge of handling the underlying memory, i.e. the class does neither allocate anything nor destroy anything
Definition at line 29 of file ShallowMatrix.h.
Constructor & Destructor Documentation
ShallowMatrix() [1/2]
template<int Rows, int Cols, typename Scalar > tarch::la::ShallowMatrix< Rows, Cols, Scalar >::ShallowMatrix (Scalar * values)
Constructs a non-initialized matrix.
Definition at line 9 of file ShallowMatrix.cpph.
ShallowMatrix() [2/2]
template<int Rows, int Cols, typename Scalar > tarch::la::ShallowMatrix< Rows, Cols, Scalar >::ShallowMatrix (const ShallowMatrix< Rows, Cols, Scalar > & copy)
Shallow copy.
Definition at line 15 of file ShallowMatrix.cpph.
Member Function Documentation
cols()
template<int Rows, int Cols, typename Scalar > int tarch::la::ShallowMatrix< Rows, Cols, Scalar >::cols () const
Returns the number of columns in the matrix.
Definition at line 33 of file ShallowMatrix.cpph.
References tarch::la::max().
convertScalar()
template<int Rows, int Cols, typename Scalar > template<typename NewScalarType > tarch::la::Matrix< Rows, Cols, NewScalarType > tarch::la::ShallowMatrix< Rows, Cols, Scalar >::convertScalar () const
Convert the scalar type.
Can also be used to convert a shallow matrix into a proper one, i.e. to deep copy.
Definition at line 94 of file ShallowMatrix.cpph.
References tarch::la::max().
data() [1/2]
template<int Rows, int Cols, typename Scalar > Scalar * tarch::la::ShallowMatrix< Rows, Cols, Scalar >::data ()
Return pointer back to original data.
Definition at line 121 of file ShallowMatrix.h.
References tarch::la::ShallowMatrix< Rows, Cols, Scalar >::_values.
Referenced by peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__generate_dastgen_input_file(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__get_file_name(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__get_full_qualified_file_name(), swift2.particle.Particle.Particle::__init__(), swift2.particle.Particle.Particle::_add_dependency_checks(), swift2.particle.Particle.Particle::_dependency_checks_modify_steps(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_boolean_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_boolean_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_double_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_double_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_enum_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_integer_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_integer_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_peano_double_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_peano_integer_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_string_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_user_defined_attributes(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::_get_dictionary_for_output(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::construct_output(), peano4.datamodel.DynamicArrayOverPrimitivesToStdVector.DynamicArrayOverPrimitivesToStdVector::construct_output(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::construct_output(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::construct_output(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::construct_output(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::get_header_file_include(), peano4.datamodel.DynamicArrayOverPrimitivesToStdVector.DynamicArrayOverPrimitivesToStdVector::get_header_file_include(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::get_header_file_include(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::get_header_file_include(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::get_header_file_include(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::get_stack_container(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::get_stack_container(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::get_stack_container(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::get_stack_container(), peano4.datamodel.DaStGen2.DaStGen2::hosts_smart_pointer_attribute(), swift2.particle.Particle.Particle::readme_descriptor(), swift2.particle.SPHLeapfrogFixedSearchRadius.SPHLeapfrogFixedSearchRadius::set_parameters(), swift2.particle.SPHParticle.SPHParticle::set_parameters(), and swift2.particle.tests.testLeapfrogFixedTimeStepSize.testLeapfrogFixedTimeStepSize::set_parameters().
data() [2/2]
template<int Rows, int Cols, typename Scalar > const Scalar * tarch::la::ShallowMatrix< Rows, Cols, Scalar >::data () const
Definition at line 125 of file ShallowMatrix.h.
References tarch::la::ShallowMatrix< Rows, Cols, Scalar >::_values.
Referenced by peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__generate_dastgen_input_file(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__get_file_name(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__get_full_qualified_file_name(), swift2.particle.Particle.Particle::__init__(), swift2.particle.Particle.Particle::_add_dependency_checks(), swift2.particle.Particle.Particle::_dependency_checks_modify_steps(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_boolean_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_boolean_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_double_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_double_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_enum_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_integer_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_integer_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_peano_double_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_peano_integer_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_string_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_user_defined_attributes(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::_get_dictionary_for_output(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::construct_output(), peano4.datamodel.DynamicArrayOverPrimitivesToStdVector.DynamicArrayOverPrimitivesToStdVector::construct_output(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::construct_output(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::construct_output(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::construct_output(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::get_header_file_include(), peano4.datamodel.DynamicArrayOverPrimitivesToStdVector.DynamicArrayOverPrimitivesToStdVector::get_header_file_include(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::get_header_file_include(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::get_header_file_include(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::get_header_file_include(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::get_stack_container(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::get_stack_container(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::get_stack_container(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::get_stack_container(), peano4.datamodel.DaStGen2.DaStGen2::hosts_smart_pointer_attribute(), swift2.particle.Particle.Particle::readme_descriptor(), swift2.particle.SPHLeapfrogFixedSearchRadius.SPHLeapfrogFixedSearchRadius::set_parameters(), swift2.particle.SPHParticle.SPHParticle::set_parameters(), and swift2.particle.tests.testLeapfrogFixedTimeStepSize.testLeapfrogFixedTimeStepSize::set_parameters().
operator()() [1/2]
template<int Rows, int Cols, typename Scalar > Scalar & tarch::la::ShallowMatrix< Rows, Cols, Scalar >::operator() (int rowIndex, int colIndex)
Returns element at given row and column index (from 0..size-1).
See also
Vector::operator[] for remarks on SSE efficiency
Definition at line 72 of file ShallowMatrix.h.
References tarch::la::ShallowMatrix< Rows, Cols, Scalar >::_values, assertion5, tarch::la::max(), and tarch::la::ShallowMatrix< Rows, Cols, Scalar >::toString().
operator()() [2/2]
template<int Rows, int Cols, typename Scalar > const Scalar & tarch::la::ShallowMatrix< Rows, Cols, Scalar >::operator() (int rowIndex, int colIndex) const
Returns const element at given row and column index (from 0..size-1).
Definition at line 90 of file ShallowMatrix.h.
References tarch::la::ShallowMatrix< Rows, Cols, Scalar >::_values, assertion5, tarch::la::max(), and tarch::la::ShallowMatrix< Rows, Cols, Scalar >::toString().
operator=()
template<int Rows, int Cols, typename Scalar > tarch::la::ShallowMatrix< Rows, Cols, Scalar > & tarch::la::ShallowMatrix< Rows, Cols, Scalar >::operator= (const ShallowMatrix< Rows, Cols, Scalar > & copy)
Shallow copy.
Definition at line 21 of file ShallowMatrix.cpph.
References tarch::la::ShallowMatrix< Rows, Cols, Scalar >::_values, and tarch::la::max().
rows()
template<int Rows, int Cols, typename Scalar > int tarch::la::ShallowMatrix< Rows, Cols, Scalar >::rows () const
Returns the number of rows in the matrix.
Definition at line 27 of file ShallowMatrix.cpph.
References tarch::la::max().
size()
template<int Rows, int Cols, typename Scalar > int tarch::la::ShallowMatrix< Rows, Cols, Scalar >::size () const
Returns the number of total elements in the matrix.
Definition at line 39 of file ShallowMatrix.cpph.
References tarch::la::max().
Referenced by peano4.visualisation.input.Patch.Patch::__repr__().
toPrettyString()
template<int Rows, int Cols, typename Scalar > std::string tarch::la::ShallowMatrix< Rows, Cols, Scalar >::toPrettyString (int numberOfDigits = 4) const
Definition at line 67 of file ShallowMatrix.cpph.
References tarch::la::abs(), and tarch::la::max().
toString()
template<int Rows, int Cols, typename Scalar > std::string tarch::la::ShallowMatrix< Rows, Cols, Scalar >::toString () const
Definition at line 45 of file ShallowMatrix.cpph.
References tarch::la::max().
Referenced by tarch::la::ShallowMatrix< Rows, Cols, Scalar >::operator()(), and tarch::la::ShallowMatrix< Rows, Cols, Scalar >::operator()().
Field Documentation
_values
template<int Rows, int Cols, typename Scalar > Scalar* tarch::la::ShallowMatrix< Rows, Cols, Scalar >::_values private
Values of the matrix components.
Definition at line 34 of file ShallowMatrix.h.
Referenced by tarch::la::ShallowMatrix< Rows, Cols, Scalar >::data(), tarch::la::ShallowMatrix< Rows, Cols, Scalar >::data(), tarch::la::ShallowMatrix< Rows, Cols, Scalar >::operator()(), tarch::la::ShallowMatrix< Rows, Cols, Scalar >::operator()(), and tarch::la::ShallowMatrix< Rows, Cols, Scalar >::operator=().
The documentation for this class was generated from the following files:
src/tarch/la/ShallowMatrix.h
src/tarch/la/ShallowMatrix.cpph