Peano
Tutorial02-main.h File Reference
#include <string>
Functions
int main (int argc, char **argv)
Main routine of the SPH code.
Function Documentation
main()
int main (int argc, char ** argv)
Main routine of the SPH code.
Definition at line 270 of file MatrixFreeMain.template.cpp.
References tarch::mpi::Rank::abort(), tarch::logging::LogFilter::addFilterListEntry(), tarch::tests::TreeTestCaseCollection::addTestCase(), tarch::logging::LogFilter::FilterListEntry::AlwaysOn, tarch::logging::LogFilter::FilterListEntry::AnyRank, assembleMeasurement, tarch::logging::LogFilter::FilterListEntry::BlackListEntry, cellCenter, cellSize, tarch::logging::Statistics::clear(), createGridMeasurement, enumerateMeasurement, examples::regulargridupscaling::MyObserver::FractionOfCellsYieldingIntegrationTask, freeOutcome(), tarch::timing::Measurement::getAccumulatedValue(), tarch::timing::Watch::getCalendarTime(), peano4::parallel::Node::getInstance(), tarch::logging::ChromeTraceFileLogger::getInstance(), tarch::logging::CommandLineLogger::getInstance(), tarch::logging::LogFilter::getInstance(), tarch::logging::Statistics::getInstance(), tarch::mpi::Rank::getInstance(), tarch::multicore::Core::getInstance(), tarch::tests::TestCase::getNumberOfErrors(), tarch::timing::Measurement::getNumberOfMeasurements(), tarch::mpi::Rank::getNumberOfRanks(), tarch::multicore::Core::getNumberOfThreads(), exahype2::getUnitTests(), peano4::getUnitTests(), tarch::getUnitTests(), toolbox::blockstructured::getUnitTests(), toolbox::finiteelements::getUnitTests(), tarch::timing::Measurement::getValue(), gridConstructionMeasurement, haveReceivedNonCriticalAssertion, peano4::init(), initGridTraversalEvent(), initMeasurement, tarch::initNonCriticalAssertionEnvironment(), petsc::initParallelEnvironment(), examples::regulargridupscaling::MyObserver::IntegrationAccuracy, tarch::mpi::Rank::isGlobalMaster(), logDebug, logError, logInfo, logWarning, main(), mapSolutionOntoMeshMeasurement, OTTER_FINALISE, OTTER_INITIALISE, outcomeIsInvalid, swift2::parseCommandLineArguments(), tarch::logging::LogFilterFileReader::parsePlainTextFile(), periodicBC, plotMeasurement, tarch::tests::TreeTestCaseCollection::run(), runBenchmark(), runBenchmarks(), variant1::runBenchmarks(), variant2::runBenchmarks(), variant3::runBenchmarks(), variant4::runBenchmarks(), variant5::runBenchmarks(), variant6::runBenchmarks(), runParallel(), runSerial(), runTests(), selectNextAlgorithmicStep(), tarch::logging::ChromeTraceFileLogger::setOutputFile(), tarch::logging::CommandLineLogger::setOutputFile(), tarch::timing::Measurement::setValue(), peano4::shutdown(), tarch::shutdownNonCriticalAssertionEnvironment(), solveMeasurement, tarch::timing::Watch::start(), step(), tarch::timing::Watch::stop(), tarch::logging::LogFilter::FilterListEntry::TargetDebug, tarch::logging::LogFilter::FilterListEntry::TargetInfo, tarch::logging::LogFilter::FilterListEntry::TargetTrace, timePerMeshSweepMeasurement, timeStamp, timeStepMeasurement, timeStepSize, tarch::timing::Measurement::toString(), tarch::logging::LogFilter::FilterListEntry::WhiteListEntry, and tarch::logging::Statistics::writeToCSV().