Peano
exahype2::fd::tests::CCZ4KernelTest Class Reference
#include <CCZ4KernelTest.h>
Public Member Functions
CCZ4KernelTest ()
virtual void run ()
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void AppleWithAppleTest ()
void prepareFieldData (double **g, double &phi, double **K, double &trK, double &Theta, double *Gamma, double &alpha, double *beta, double *b, double x, double y, double z)
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Definition at line 19 of file CCZ4KernelTest.h.
Constructor & Destructor Documentation
CCZ4KernelTest()
exahype2::fd::tests::CCZ4KernelTest::CCZ4KernelTest ()
Definition at line 25 of file CCZ4KernelTest.cpp.
Member Function Documentation
AppleWithAppleTest()
void exahype2::fd::tests::CCZ4KernelTest::AppleWithAppleTest () private
Definition at line 35 of file CCZ4KernelTest.cpp.
References exahype2::enumerator::AoSLexicographicEnumerator::_numberOfDoFsPerAxisInCell, beta, exahype2::CellData< inType, outType, NumFaceTypes >::cellCentre, cellSize, exahype2::CellData< inType, outType, NumFaceTypes >::cellSize, exahype2::fd::fd4::CentralDifferencesWithLopsidedAdvection, peano4::utils::dLinearised(), double, applications::exahype2::ccz4::ncp(), exahype2::fd::fd4::reconstruct_first_derivatives(), applications::exahype2::ccz4::source(), exahype2::fd::fd4::timeStep_patchwise_heap_functors(), and exahype2::volumeIndex().
prepareFieldData()
void exahype2::fd::tests::CCZ4KernelTest::prepareFieldData (double ** g, double & phi, double ** K, double & trK, double & Theta, double * Gamma, double & alpha, double * beta, double * b, double x, double y, double z) private
Definition at line 312 of file CCZ4KernelTest.cpp.
References beta.
run()
void exahype2::fd::tests::CCZ4KernelTest::run () virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 30 of file CCZ4KernelTest.cpp.
References testMethod.
The documentation for this class was generated from the following files:
src/exahype2/fd/tests/CCZ4KernelTest.h
src/exahype2/fd/tests/CCZ4KernelTest.cpp