Peano
SpinlockedIterator< InnerIterator > Class Template Reference
#include <linked_grid_iterator.h>
Public Member Functions
SpinlockedIterator ()=default
SpinlockedIterator (InnerIterator *inner)
std::optional< typename InnerIterator::Item > next ()
Private Attributes
Spinlock spinLock
InnerIterator * iter
Detailed Description
template<typename InnerIterator>
class SpinlockedIterator< InnerIterator >
Definition at line 456 of file linked_grid_iterator.h.
Constructor & Destructor Documentation
SpinlockedIterator() [1/2]
template<typename InnerIterator > SpinlockedIterator< InnerIterator >::SpinlockedIterator () explicit default
SpinlockedIterator() [2/2]
template<typename InnerIterator > SpinlockedIterator< InnerIterator >::SpinlockedIterator (InnerIterator * inner) explicit
Definition at line 463 of file linked_grid_iterator.h.
Member Function Documentation
next()
template<typename InnerIterator > std::optional< typename InnerIterator::Item > SpinlockedIterator< InnerIterator >::next ()
Definition at line 467 of file linked_grid_iterator.h.
References Spinlock::lock(), SpinlockedIterator< InnerIterator >::next(), and Spinlock::unlock().
Referenced by SpinlockedIterator< InnerIterator >::next().
Field Documentation
iter
template<typename InnerIterator > InnerIterator* SpinlockedIterator< InnerIterator >::iter private
Definition at line 458 of file linked_grid_iterator.h.
spinLock
template<typename InnerIterator > Spinlock SpinlockedIterator< InnerIterator >::spinLock private
Definition at line 457 of file linked_grid_iterator.h.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/grid/linked_grid_iterator.h