Peano
main.cpp File Reference
#include "MyObserver.h"
#include "tarch/logging/Log.h"
#include "tarch/logging/CommandLineLogger.h"
#include "tarch/logging/ChromeTraceFileLogger.h"
#include "tarch/logging/LogFilter.h"
#include "tarch/multicore/Core.h"
#include "tarch/mpi/Rank.h"
#include "peano4/peano4.h"
#include "peano4/grid/Spacetree.h"
#include "peano4/parallel/SpacetreeSet.h"
#include "peano4/parallel/Node.h"
#include "peano4/UnitTests.h"
#include "tarch/UnitTests.h"
Functions
void runTests ()
void runParallel (double h, int flopsPerCell)
int main (int argc, char **argv)
Main routine of the SPH code.
Variables
tarch::logging::Log _log ("examples::regulargridupscaling")
Function Documentation
main()
int main (int argc, char ** argv)
Main routine of the SPH code.
Definition at line 167 of file main.cpp.
References tarch::logging::LogFilter::addFilterListEntry(), tarch::logging::LogFilter::FilterListEntry::AnyRank, examples::regulargridupscaling::MyObserver::FractionOfCellsYieldingIntegrationTask, tarch::logging::ChromeTraceFileLogger::getInstance(), tarch::logging::LogFilter::getInstance(), tarch::mpi::Rank::getInstance(), tarch::multicore::Core::getInstance(), tarch::mpi::Rank::getNumberOfRanks(), tarch::multicore::Core::getNumberOfThreads(), examples::regulargridupscaling::MyObserver::IntegrationAccuracy, logError, logInfo, runParallel(), runTests(), tarch::logging::ChromeTraceFileLogger::setOutputFile(), tarch::logging::LogFilter::FilterListEntry::TargetDebug, tarch::logging::LogFilter::FilterListEntry::TargetInfo, and tarch::logging::LogFilter::FilterListEntry::TargetTrace.
runParallel()
void runParallel (double h, int flopsPerCell)
Definition at line 47 of file main.cpp.
References assertion1, assertionEquals, peano4::parallel::SpacetreeSet::getGridStatistics(), peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), tarch::mpi::Rank::getInstance(), tarch::multicore::Core::getInstance(), peano4::parallel::SpacetreeSet::getLocalSpacetrees(), peano4::grid::GridStatistics::getNumberOfLocalUnrefinedCells(), tarch::mpi::Rank::getNumberOfRanks(), tarch::multicore::Core::getNumberOfThreads(), peano4::parallel::SpacetreeSet::init(), logDebug, logError, logInfo, logTraceInWith1Argument, logTraceOut, logWarning, examples::regulargridupscaling::MyObserver::RanksObserverTemplate, peano4::parallel::Node::setNextProgramStep(), peano4::parallel::SpacetreeSet::split(), ThreePowerD, toString(), and peano4::parallel::SpacetreeSet::traverse().
runTests()
void runTests ()
Definition at line 23 of file main.cpp.
References peano4::getUnitTests(), tarch::getUnitTests(), and logError.
Variable Documentation
_log
tarch::logging::Log _log("examples::regulargridupscaling") ("examples::regulargridupscaling")