Peano
exahype2::dg::tests Namespace Reference
Data Structures
class CellIntegralTest
class DGUtilsTest
class RiemannTest
Functions
void eulerFlux (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &x, double t, double dt, int normal, double *__restrict__ F)
void eulerSource (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &x, double t, double dt, double *__restrict__ S)
double eulerEigenvalue (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &x, double t, double dt, int normal)
void eulerBoundaryConditions (const double *__restrict__ Qinside, double *__restrict__ Qoutside, const tarch::la::Vector< Dimensions, double > &x, double t, double dt, int normal)
void eulerInitial (double *__restrict__ Q, int node=0)
void elasticInitial (double *__restrict__ Q)
void elasticFlux (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &x, double t, double dt, int normal, double *__restrict__ F)
void elasticSource (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &x, double t, double dt, double *__restrict__ S)
double elasticEigenvalue (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &x, double t, double dt, int normal)
void elasticBoundaryConditions (const double *__restrict__ Qinside, double *__restrict__ Qoutside, const tarch::la::Vector< Dimensions, double > &x, double t, double dt, int normal)
void elasticNonConservativeProduct (const double *__restrict__ Q, const double *__restrict__ deltaQ, const tarch::la::Vector< Dimensions, double > &faceCentre, double t, double dt, int normal, double *__restrict__ BgradQ)
void testBoundaryConditions (const double *__restrict__ Qinside, double *__restrict__ Qoutside, const tarch::la::Vector< Dimensions, double > &x, double t, double dt, int normal)
void secondTestBoundaryConditions (const double *__restrict__ Qinside, double *__restrict__ Qoutside, const tarch::la::Vector< Dimensions, double > &x, double t, double dt, int normal)
double testEigenvalue (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &x, double t, double dt, int normal)
Variables
constexpr double QuadratureNodes1dP1 [] = { 0.21132486540518713,0.7886751345948129 }
constexpr double QuadratureNodes1dP2 [] = { 0.1127016653792583,0.5,0.8872983346207417}
constexpr double DerivativeOperatorLagrangeP3 []
constexpr double BasisFunctionValuesLeftP0 []
constexpr double BasisFunctionValuesLeftP3 []
Function Documentation
elasticBoundaryConditions()
void exahype2::dg::tests::elasticBoundaryConditions (const double *__restrict__ Qinside, double *__restrict__ Qoutside, const tarch::la::Vector< Dimensions, double > & x, double t, double dt, int normal)
Definition at line 167 of file TestUtils.cpp.
elasticEigenvalue()
double exahype2::dg::tests::elasticEigenvalue (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & x, double t, double dt, int normal)
Definition at line 156 of file TestUtils.cpp.
References std::abs().
elasticFlux()
void exahype2::dg::tests::elasticFlux (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & x, double t, double dt, int normal, double *__restrict__ F)
Definition at line 105 of file TestUtils.cpp.
elasticInitial()
void exahype2::dg::tests::elasticInitial (double *__restrict__ Q)
Definition at line 95 of file TestUtils.cpp.
elasticNonConservativeProduct()
void exahype2::dg::tests::elasticNonConservativeProduct (const double *__restrict__ Q, const double *__restrict__ deltaQ, const tarch::la::Vector< Dimensions, double > & faceCentre, double t, double dt, int normal, double *__restrict__ BgradQ)
Definition at line 189 of file TestUtils.cpp.
elasticSource()
void exahype2::dg::tests::elasticSource (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & x, double t, double dt, double *__restrict__ S)
Definition at line 138 of file TestUtils.cpp.
eulerBoundaryConditions()
void exahype2::dg::tests::eulerBoundaryConditions (const double *__restrict__ Qinside, double *__restrict__ Qoutside, const tarch::la::Vector< Dimensions, double > & x, double t, double dt, int normal)
Definition at line 69 of file TestUtils.cpp.
eulerEigenvalue()
double exahype2::dg::tests::eulerEigenvalue (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & x, double t, double dt, int normal)
Definition at line 38 of file TestUtils.cpp.
References std::abs(), and assertion8.
eulerFlux()
void exahype2::dg::tests::eulerFlux (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & x, double t, double dt, int normal, double *__restrict__ F)
Definition at line 3 of file TestUtils.cpp.
Referenced by exahype2::dg::tests::CellIntegralTest::runEulerOrder2OnStationarySetup(), and exahype2::dg::tests::CellIntegralTest::runEulerOrder4OnStationarySetup().
eulerInitial()
void exahype2::dg::tests::eulerInitial (double *__restrict__ Q, int node = 0)
Definition at line 84 of file TestUtils.cpp.
eulerSource()
void exahype2::dg::tests::eulerSource (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & x, double t, double dt, double *__restrict__ S)
Definition at line 24 of file TestUtils.cpp.
secondTestBoundaryConditions()
void exahype2::dg::tests::secondTestBoundaryConditions (const double *__restrict__ Qinside, double *__restrict__ Qoutside, const tarch::la::Vector< Dimensions, double > & x, double t, double dt, int normal)
Definition at line 261 of file TestUtils.cpp.
testBoundaryConditions()
void exahype2::dg::tests::testBoundaryConditions (const double *__restrict__ Qinside, double *__restrict__ Qoutside, const tarch::la::Vector< Dimensions, double > & x, double t, double dt, int normal)
Definition at line 236 of file TestUtils.cpp.
testEigenvalue()
double exahype2::dg::tests::testEigenvalue (const double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & x, double t, double dt, int normal)
Definition at line 250 of file TestUtils.cpp.
Variable Documentation
BasisFunctionValuesLeftP0
constexpr double exahype2::dg::tests::BasisFunctionValuesLeftP0[] constexpr
Initial value:
= {
        1.0
      }
Definition at line 26 of file TestUtils.h.
Referenced by exahype2::dg::tests::RiemannTest::testProjectVolumetricDataOntoFacesForConstantSolutionOrder0().
BasisFunctionValuesLeftP3
constexpr double exahype2::dg::tests::BasisFunctionValuesLeftP3[] constexpr
Initial value:
= {
        1.5267881254572663873858573424513451755046844482421875,-0.8136324494869271450880887641687877476215362548828125,
        0.40076152031165046540905905203544534742832183837890625,-0.11391719628198997138479597879268112592399120330810546875}
Definition at line 29 of file TestUtils.h.
Referenced by exahype2::dg::tests::RiemannTest::testProjectVolumetricDataOntoFacesForConstantSolutionOrder3().
DerivativeOperatorLagrangeP3
constexpr double exahype2::dg::tests::DerivativeOperatorLagrangeP3[] constexpr
Initial value:
= {
          -6.6640004727045631938153746887110173702239990234375,9.7203088313703940315235740854404866695404052734375,-4.21756469699035818621268845163285732269287109375,1.161256338324529568950538305216468870639801025390625,
          -1.5151152295984677831341969067580066621303558349609375,-0.7688287844464174458636307463166303932666778564453125,2.941340462561433444221847821609117090702056884765625,-0.6573964485165488813578349436284042894840240478515625,
          0.65739644851654832624632263105013407766819000244140625,-2.941340462561433444221847821609117090702056884765625,0.768828784446416335640606121160089969635009765625,1.515115229598468449268011681851930916309356689453125,
          -1.161256338324528680772118605091236531734466552734375,4.21756469699035729803426875150762498378753662109375,-9.720308831370392255166734685190021991729736328125,6.66400047270456497017221408896148204803466796875}
Definition at line 20 of file TestUtils.h.
Referenced by exahype2::dg::tests::DGUtilsTest::testComputeGradientOnConstantSolution().
QuadratureNodes1dP1
constexpr double exahype2::dg::tests::QuadratureNodes1dP1[] = { 0.21132486540518713,0.7886751345948129 } constexpr
Definition at line 17 of file TestUtils.h.
Referenced by exahype2::dg::tests::DGUtilsTest::testEvaluatePolynomialOrder1(), and exahype2::dg::tests::DGUtilsTest::testEvaluatePolynomialOrder2().
QuadratureNodes1dP2
constexpr double exahype2::dg::tests::QuadratureNodes1dP2[] = { 0.1127016653792583,0.5,0.8872983346207417} constexpr
Definition at line 18 of file TestUtils.h.
Referenced by exahype2::dg::tests::DGUtilsTest::testEvaluatePolynomialOrder2().