Peano
TaskNumber.cpp File Reference
#include "TaskNumber.h"
#include <sstream>
#include "tarch/Assertions.h"
#include "tarch/Enumerator.h"
Functions
bool operator== (const swift2::TaskNumber &lhs, const swift2::TaskNumber &rhs)
bool operator!= (const swift2::TaskNumber &lhs, const swift2::TaskNumber &rhs)
Function Documentation
operator!=()
bool operator!= (const swift2::TaskNumber & lhs, const swift2::TaskNumber & rhs)
Definition at line 45 of file TaskNumber.cpp.
References swift2::TaskNumber::equals().
operator==()
bool operator== (const swift2::TaskNumber & lhs, const swift2::TaskNumber & rhs)
Definition at line 40 of file TaskNumber.cpp.
References swift2::TaskNumber::equals().
Referenced by tarch::logging::LogFilter::FilterListEntry::operator!=().