Peano
RefinementControl.cpp File Reference
#include "RefinementControl.h"
#include "peano4/grid/grid.h"
#include "peano4/parallel/SpacetreeSet.h"
#include "tarch/multicore/Lock.h"
Functions
exahype2::RefinementCommand operator&& (exahype2::RefinementCommand lhs, exahype2::RefinementCommand rhs)
If one of the flags says refine, then refine.
std::string toString (exahype2::RefinementCommand value)
Function Documentation
operator&&()
exahype2::RefinementCommand operator&& (exahype2::RefinementCommand lhs, exahype2::RefinementCommand rhs)
If one of the flags says refine, then refine.
If one of the two flags says keep and noone says refine, return keep. Coarsen if and only if both say coarsen.
Definition at line 11 of file RefinementControl.cpp.
References exahype2::Erase, exahype2::Keep, and exahype2::Refine.
toString()
std::string toString (exahype2::RefinementCommand value)
Definition at line 21 of file RefinementControl.cpp.
References exahype2::Erase, exahype2::Keep, and exahype2::Refine.
Referenced by exahype2::RefinementControl::addCommand(), tarch::accelerator::allocateRawData(), peano4::stacks::STDVectorStackOverObjectsWithSmartPointers< T >::clone(), peano4::stacks::STDVectorStackOverSmartPointers< T >::clone(), toolbox::particles::SieveParticles< T >::cloneParticlesToBeSieved(), tarch::accelerator::copyFrom(), tarch::accelerator::copyTo(), toolbox::particles::ensureAllParticleListsAreGatheredOrEmpty(), peano4::stacks::STDVectorStackOverSmartPointers< T >::gather(), peano4::parallel::Node::getGridDataExchangeMetaInformation(), peano4::datamanagement::CellMarker::getInvokingParentCellsCentre(), peano4::datamanagement::VertexMarker::getInvokingParentCellsCentre(), peano4::datamanagement::VertexMarker::getNumberOfAdjacentTrees(), peano4::datamanagement::FaceMarker::getRelativePositionWithinFatherCell(), peano4::datamanagement::FaceMarker::getRelativePositionWithinFatherCell(), peano4::datamanagement::VertexMarker::isAdjacentToParallelDomainBoundary(), exahype2::enumerator::FaceAoSLexicographicEnumerator::operator()(), operator<<(), peano4::stacks::STDVectorOverContainerOfPointers< T >::prepareMetaDataToSendOut(), tarch::accelerator::reallocateRawData(), mghype::matrixfree::solvers::cgmultigrid::restrictToNextLevel(), runParallel(), runParallel(), peano4::datamanagement::VertexMarker::select(), selectNextAlgorithmicStep(), tarch::la::slice(), peano4::stacks::STDVectorStackOverSmartPointers< T >::startReceive(), peano4::parallel::tests::PingPongTest::testDaStGenArray(), peano4::SplitInstruction::toString(), peano4::stacks::STDVectorStackOverObjectsWithSmartPointers< T >::toString(), peano4::stacks::STDVectorStackOverSmartPointers< T >::toString(), toolbox::particles::assignmentchecks::internal::ParticleIdentifier::toString(), peano4::stacks::STDVectorOverContainerOfPointers< T >::tryToFinishSendOrReceive(), peano4::stacks::STDVectorStackOverObjectsWithSmartPointers< T >::tryToFinishSendOrReceive(), peano4::stacks::STDVectorStackOverSmartPointers< T >::tryToFinishSendOrReceive(), toolbox::loadbalancing::LoadBalancer::update(), mghype::matrixfree::solvers::dgcgcoupling::updateRestrictionCounters(), and peano4::stacks::STDVectorOverContainerOfPointers< T >::workInReceivedMetaData().