Peano
tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > > Class Template Reference
#include <cartesian_product.h>
Data Structures
class cursor
Public Member Functions
cartesian_product_view ()=default
constexpr cartesian_product_view (std::ranges::iota_view< W, B > xs, std::ranges::iota_view< W, B > ys, std::ranges::iota_view< W, B > zs)
constexpr auto begin ()
constexpr auto begin () const
constexpr auto size ()
constexpr auto size () const
constexpr auto end ()
constexpr auto end () const
Data Fields
W x_b
W y_b
W z_b
B nx
B ny
B nz
Private Types
using self
Detailed Description
template<typename W, typename B>
requires std::is_integral_v<W> && std::is_integral_v<B>
class tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >
Definition at line 1363 of file cartesian_product.h.
Member Typedef Documentation
self
template<typename W , typename B > using tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::self private
Initial value:
 cartesian_product_view<
            std::ranges::iota_view<W, B>,
            std::ranges::iota_view<W, B>,
            std::ranges::iota_view<W, B>
    >
Definition at line 1376 of file cartesian_product.h.
Constructor & Destructor Documentation
cartesian_product_view() [1/2]
template<typename W , typename B > tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::cartesian_product_view () default
cartesian_product_view() [2/2]
template<typename W , typename B > constexpr tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::cartesian_product_view (std::ranges::iota_view< W, B > xs, std::ranges::iota_view< W, B > ys, std::ranges::iota_view< W, B > zs) explicit constexpr
Definition at line 1464 of file cartesian_product.h.
Member Function Documentation
begin() [1/2]
template<typename W , typename B > constexpr auto tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::begin () constexpr
Definition at line 1476 of file cartesian_product.h.
begin() [2/2]
template<typename W , typename B > constexpr auto tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::begin () const constexpr
Definition at line 1479 of file cartesian_product.h.
end() [1/2]
template<typename W , typename B > constexpr auto tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::end () constexpr
Definition at line 1491 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::begin(), and tl::cartesian_product_view< Vs >::size().
end() [2/2]
template<typename W , typename B > constexpr auto tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::end () const constexpr
Definition at line 1495 of file cartesian_product.h.
References tl::cartesian_product_view< Vs >::begin(), and tl::cartesian_product_view< Vs >::size().
size() [1/2]
template<typename W , typename B > constexpr auto tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::size () constexpr
Definition at line 1483 of file cartesian_product.h.
Referenced by peano4.visualisation.input.Patch.Patch::__repr__().
size() [2/2]
template<typename W , typename B > constexpr auto tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::size () const constexpr
Definition at line 1487 of file cartesian_product.h.
Referenced by peano4.visualisation.input.Patch.Patch::__repr__().
Field Documentation
nx
template<typename W , typename B > B tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::nx
Definition at line 1383 of file cartesian_product.h.
ny
template<typename W , typename B > B tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::ny
Definition at line 1383 of file cartesian_product.h.
nz
template<typename W , typename B > B tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::nz
Definition at line 1383 of file cartesian_product.h.
x_b
template<typename W , typename B > W tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::x_b
Definition at line 1382 of file cartesian_product.h.
y_b
template<typename W , typename B > W tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::y_b
Definition at line 1382 of file cartesian_product.h.
z_b
template<typename W , typename B > W tl::cartesian_product_view< std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B >, std::ranges::iota_view< W, B > >::z_b
Definition at line 1382 of file cartesian_product.h.
The documentation for this class was generated from the following file:
src/tarch/accelerator/cpp/cartesian_product.h