Peano
tarch::multicore::Task Class Reference abstract
Abstract super class for a job.
#include <Task.h>
Public Member Functions
Task (int taskType, int priority)
Construct task.
virtual ~Task ()
int getTaskType () const
int getPriority () const
void setPriority (int priority)
Set priority.
virtual bool run ()=0
virtual void fuse (const std::list< Task * > &otherTasks)
Fuse multiple tasks.
virtual std::string toString () const
Static Public Attributes
static constexpr int NoTaskType = -1
static constexpr int DefaultPriority = 1024
Protected Attributes
const int _taskType
int _priority
Detailed Description
Abstract super class for a job.
Definition at line 20 of file Task.h.
Constructor & Destructor Documentation
Task()
tarch::multicore::Task::Task (int taskType, int priority)
Construct task.
Task types and task numbers
Each task in Peano has to have a task type. All tasks that do the same, i.e. are of the same type, should have the same task type integer marker.
It is totally up to the user to manage the task type numbers. Peano for example offers a factory mechanism peano4::parallel::getTaskType() to create task types, which Peano applications should use. However, the generation of the task types is not baked into the tarch.
Some codes also have task numbers. They need this, if they have to identify tasks uniquely. Applications for that are task dependencies or tasks that are offloaded to other ranks. For the latter tasks, we have to match data sent back by another rank to the task that would have produced these results locally. Anyway, task numbers are not baked into the generic interface, as we don't need them for all tasks all the time, and I want to avoid that the construction of unique task numbers becomes too expensive. If you should need unique task numbers, I recommend you use reserveTaskNumber().
Parameters
taskType Unique task (type) number for this task.
priority Integer value that indicates what priority you want to assign a task. Value has to be non-negative. Use DefaultPriority if there is no bespoke priority.
Definition at line 24 of file Task.cpp.
References assertion2.
~Task()
virtual tarch::multicore::Task::~Task () virtual
Definition at line 62 of file Task.h.
Member Function Documentation
fuse()
void tarch::multicore::Task::fuse (const std::list< Task * > & otherTasks) virtual
Fuse multiple tasks.
Fuse the task with a list of further tasks. The routine is guaranteed to be called only for tasks with the same taskType. So if you carefully distinguish your tasks, you can downcast all the arguments, as you might know the real type.
Definition at line 39 of file Task.cpp.
Referenced by exahype2::EnclaveBookkeeping::fusePendingTasks().
getPriority()
int tarch::multicore::Task::getPriority () const
Definition at line 30 of file Task.cpp.
Referenced by operator<().
getTaskType()
int tarch::multicore::Task::getTaskType () const
Definition at line 37 of file Task.cpp.
Referenced by exahype2::EnclaveBookkeeping::bookmarkTask().
run()
virtual bool tarch::multicore::Task::run () pure virtual
Returns
This task has to be executed again. In most cases, you should return false, to indicate that this task has finished.
Implemented in exahype2::EnclaveTask< T, NumFaceTypes >, FusableTask, peano4::parallel::SpacetreeSet::TraverseTask, tarch::multicore::TaskWithCopyOfFunctor, tarch::multicore::EmptyTask, tarch::multicore::TaskWithoutCopyOfFunctor, ProducerTask, and ConsumerTask.
setPriority()
void tarch::multicore::Task::setPriority (int priority)
Set priority.
Parameters
priority Has to be non-negative
Definition at line 32 of file Task.cpp.
References assertion3.
toString()
std::string tarch::multicore::Task::toString () const virtual
Reimplemented in tarch::multicore::TaskWithCopyOfFunctor, and tarch::multicore::EmptyTask.
Definition at line 47 of file Task.cpp.
Field Documentation
_priority
int tarch::multicore::Task::_priority protected
Definition at line 23 of file Task.h.
_taskType
const int tarch::multicore::Task::_taskType protected
Definition at line 22 of file Task.h.
DefaultPriority
constexpr int tarch::multicore::Task::DefaultPriority = 1024 static constexpr
Definition at line 27 of file Task.h.
NoTaskType
constexpr int tarch::multicore::Task::NoTaskType = -1 static constexpr
Definition at line 26 of file Task.h.
The documentation for this class was generated from the following files:
src/tarch/multicore/Task.h
src/tarch/multicore/Task.cpp