var rkdg_2actionsets_2ComputeFinalLinearCombination_8py =
[
    [ "exahype2.solvers.rkdg.actionsets.ComputeFinalLinearCombination.ComputeFinalLinearCombination", "d8/d73/classexahype2_1_1solvers_1_1rkdg_1_1actionsets_1_1ComputeFinalLinearCombination_1_1ComputeFinalLinearCombination.html", "d8/d73/classexahype2_1_1solvers_1_1rkdg_1_1actionsets_1_1ComputeFinalLinearCombination_1_1ComputeFinalLinearCombination" ]
];