Peano
tarch::la::tests::MatrixTest Class Reference
Provides tests for types Vector, DynamicVector and all Vector functionality.
#include <MatrixTest.h>
Public Member Functions
MatrixTest ()
Cosntructor.
virtual ~MatrixTest ()
Destructor, empty.
virtual void run ()
This routine is triggered by the TestCaseCollection.
virtual void setUp ()
Setup your test case.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testConstruction ()
Tests constructors.
void testAssignment ()
Tests methods from MatrixAssign.h.
void testMatrixOperations ()
Tests methods from MatrixOperations.h.
void testMatrixMatrixOperations ()
Tests methods from MatrixMatrixOperations.h.
void testTransposedMatrix ()
Tests operations with TransposedMatrix.h.
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Provides tests for types Vector, DynamicVector and all Vector functionality.
Definition at line 18 of file MatrixTest.h.
Constructor & Destructor Documentation
MatrixTest()
tarch::la::tests::MatrixTest::MatrixTest ()
Cosntructor.
Definition at line 12 of file MatrixTest.cpp.
~MatrixTest()
virtual tarch::la::tests::MatrixTest::~MatrixTest () virtual
Destructor, empty.
Definition at line 57 of file MatrixTest.h.
Member Function Documentation
run()
void tarch::la::tests::MatrixTest::run () virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 17 of file MatrixTest.cpp.
References testMethod.
setUp()
virtual void tarch::la::tests::MatrixTest::setUp () virtual
Setup your test case.
Definition at line 67 of file MatrixTest.h.
testAssignment()
void tarch::la::tests::MatrixTest::testAssignment () private
Tests methods from MatrixAssign.h.
Definition at line 40 of file MatrixTest.cpp.
References tarch::la::max(), and validateEquals.
testConstruction()
void tarch::la::tests::MatrixTest::testConstruction () private
Tests constructors.
Definition at line 26 of file MatrixTest.cpp.
References tarch::la::max(), and validateEquals.
testMatrixMatrixOperations()
void tarch::la::tests::MatrixTest::testMatrixMatrixOperations () private
Tests methods from MatrixMatrixOperations.h.
Definition at line 68 of file MatrixTest.cpp.
References tarch::la::equalsReturnIndex(), tarch::la::max(), validate, and validateEquals.
testMatrixOperations()
void tarch::la::tests::MatrixTest::testMatrixOperations () private
Tests methods from MatrixOperations.h.
Definition at line 53 of file MatrixTest.cpp.
References tarch::la::max(), and validateEquals.
testTransposedMatrix()
void tarch::la::tests::MatrixTest::testTransposedMatrix () private
Tests operations with TransposedMatrix.h.
Definition at line 101 of file MatrixTest.cpp.
References tarch::la::max(), tarch::la::transpose(), validate, and validateEquals.
The documentation for this class was generated from the following files:
src/tarch/la/tests/MatrixTest.h
src/tarch/la/tests/MatrixTest.cpp