Peano
Transformation Class Reference
#include <transformation.h>
Static Public Member Functions
static void metricDerivativesAndJacobian3D (double **dudx, Block const &in, const double *const dx, std::vector< int > range_z, std::vector< int > range_y, std::vector< int > range_x, Block &out)
static void computeDerivatives_x_3D (double **dudx, int k, int j, int i, double *values, int num_nodes, double &der_x, double dx)
static void computeDerivatives_y_3D (double **dudx, int k, int j, int i, double *values, int num_nodes, double &der_y, double dy)
static void computeDerivatives_z_3D (double **dudx, int k, int j, int i, double *values, int num_nodes, double &der_z, double dz)
Detailed Description
Definition at line 8 of file transformation.h.
Member Function Documentation
computeDerivatives_x_3D()
static void Transformation::computeDerivatives_x_3D (double ** dudx, int k, int j, int i, double * values, int num_nodes, double & der_x, double dx) static
Definition at line 98 of file transformation.h.
References dx.
Referenced by metricDerivativesAndJacobian3D().
computeDerivatives_y_3D()
static void Transformation::computeDerivatives_y_3D (double ** dudx, int k, int j, int i, double * values, int num_nodes, double & der_y, double dy) static
Definition at line 109 of file transformation.h.
Referenced by metricDerivativesAndJacobian3D().
computeDerivatives_z_3D()
static void Transformation::computeDerivatives_z_3D (double ** dudx, int k, int j, int i, double * values, int num_nodes, double & der_z, double dz) static
Definition at line 121 of file transformation.h.
Referenced by metricDerivativesAndJacobian3D().
metricDerivativesAndJacobian3D()
static void Transformation::metricDerivativesAndJacobian3D (double ** dudx, Block const & in, const double *const dx, std::vector< int > range_z, std::vector< int > range_y, std::vector< int > range_x, Block & out) static
Definition at line 10 of file transformation.h.
References computeDerivatives_x_3D(), computeDerivatives_y_3D(), computeDerivatives_z_3D(), dx, Block::getCoord(), NCOORDS, X, Y, and Z.
Referenced by Block::getMetricDerivatives().
The documentation for this class was generated from the following file:
src/toolbox/curvi/transformation/transformation.h