Peano
Tutorial01-main.cpp File Reference
#include "Tutorial01-main.h"
#include "peano4/peano.h"
#include "peano4/UnitTests.h"
#include "peano4/grid/Spacetree.h"
#include "peano4/parallel/SpacetreeSet.h"
#include "observers/CreateGrid.h"
#include "observers/InitSolution.h"
#include "observers/Solve.h"
#include "observers/Plot.h"
#include "repositories/DataRepository.h"
#include "repositories/StepRepository.h"
#include "repositories/SolverRepository.h"
#include "tarch/UnitTests.h"
#include "tarch/logging/Log.h"
#include "tarch/logging/LogFilter.h"
#include "tarch/logging/LogFilterFileReader.h"
#include "tarch/logging/Statistics.h"
#include "tarch/multicore/Core.h"
#include "tarch/multicore/multicore.h"
#include "tarch/multicore/otter.h"
#include "tarch/tests/TreeTestCaseCollection.h"
#include "tarch/timing/Measurement.h"
#include "tarch/timing/Watch.h"
#include "toolbox/finiteelements/UnitTests.h"
#include "toolbox/loadbalancing/loadbalancing.h"
Functions
bool selectNextAlgorithmicStep ()
void step ()
int main (int argc, char **argv)
Main routine of the SPH code.
Variables
tarch::logging::Log _log ("::")
tarch::timing::Measurement createGridMeasurement
tarch::timing::Measurement initMeasurement
tarch::timing::Measurement solveMeasurement
tarch::timing::Measurement plotMeasurement
Function Documentation
main()
int main (int argc, char ** argv)
Main routine of the SPH code.
Definition at line 217 of file Tutorial01-main.cpp.
References tarch::mpi::Rank::abort(), tarch::tests::TreeTestCaseCollection::addTestCase(), tarch::logging::Statistics::clear(), createGridMeasurement, tarch::timing::Measurement::getAccumulatedValue(), peano4::parallel::Node::getInstance(), tarch::logging::Statistics::getInstance(), tarch::mpi::Rank::getInstance(), tarch::multicore::Core::getInstance(), tarch::tests::TestCase::getNumberOfErrors(), peano4::getUnitTests(), tarch::getUnitTests(), toolbox::finiteelements::getUnitTests(), initMeasurement, tarch::mpi::Rank::isGlobalMaster(), logError, logInfo, logWarning, OTTER_FINALISE, OTTER_INITIALISE, tarch::logging::LogFilterFileReader::parsePlainTextFile(), plotMeasurement, tarch::tests::TreeTestCaseCollection::run(), selectNextAlgorithmicStep(), solveMeasurement, step(), tarch::timing::Measurement::toString(), and tarch::logging::Statistics::writeToCSV().
selectNextAlgorithmicStep()
bool selectNextAlgorithmicStep ()
Definition at line 43 of file Tutorial01-main.cpp.
References assertionMsg, peano4::parallel::Node::getCurrentProgramStep(), peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), logInfo, and peano4::parallel::Node::setNextProgramStep().
Referenced by main().
step()
void step ()
Definition at line 135 of file Tutorial01-main.cpp.
References _log, assertion, createGridMeasurement, tarch::timing::Watch::getCalendarTime(), peano4::parallel::Node::getCurrentProgramStep(), peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), tarch::logging::LogFilter::getInstance(), tarch::mpi::Rank::getInstance(), initMeasurement, logInfo, plotMeasurement, tarch::timing::Measurement::setValue(), solveMeasurement, tarch::timing::Watch::start(), tarch::timing::Watch::stop(), tarch::logging::LogFilter::switchProgramPhase(), and peano4::parallel::SpacetreeSet::traverse().
Referenced by main().
Variable Documentation
_log
tarch::logging::Log _log("::") ("::")
Referenced by step().
createGridMeasurement
tarch::timing::Measurement createGridMeasurement
Definition at line 37 of file Tutorial01-main.cpp.
Referenced by main(), and step().
initMeasurement
tarch::timing::Measurement initMeasurement
Definition at line 38 of file Tutorial01-main.cpp.
Referenced by main(), and step().
plotMeasurement
tarch::timing::Measurement plotMeasurement
Definition at line 40 of file Tutorial01-main.cpp.
Referenced by main(), and step().
solveMeasurement
tarch::timing::Measurement solveMeasurement
Definition at line 39 of file Tutorial01-main.cpp.
Referenced by main(), and step().