Peano
VtkGridBinaryWriter< FileWriter, fp > Class Template Reference
#include <grid.h>
Public Member Functions
VtkGridBinaryWriter ()=default
VtkGridBinaryWriter (FileWriter *writer)
void add (fp xmin, fp ymin, fp zmin, fp xmax, fp ymax, fp zmax)
void finish ()
Private Member Functions
void addPoint (fp x, fp y, fp z)
void addCell (unsigned long idx)
void addCells ()
void addCellTypes ()
Additional Inherited Members
Protected Member Functions inherited from VtkGridWriterBase< FileWriter >
constexpr int particleCountPosition () const
template<typename T >
T byteswapped (T val)
void updatePointsCount ()
VtkGridWriterBase (FileWriter *writer)
VtkGridWriterBase ()=default
Protected Attributes inherited from VtkGridWriterBase< FileWriter >
FileWriter * writer = nullptr
unsigned long cellCount = 0
Detailed Description
template<typename FileWriter, typename fp = float>
requires IoWriter<FileWriter> and std::is_floating_point_v<fp>
class VtkGridBinaryWriter< FileWriter, fp >
Definition at line 140 of file grid.h.
Constructor & Destructor Documentation
VtkGridBinaryWriter() [1/2]
template<typename FileWriter , typename fp = float> VtkGridBinaryWriter< FileWriter, fp >::VtkGridBinaryWriter () explicit default
VtkGridBinaryWriter() [2/2]
template<typename FileWriter , typename fp = float> VtkGridBinaryWriter< FileWriter, fp >::VtkGridBinaryWriter (FileWriter * writer) explicit
Definition at line 187 of file grid.h.
References assert.
Member Function Documentation
add()
template<typename FileWriter , typename fp = float> void VtkGridBinaryWriter< FileWriter, fp >::add (fp xmin, fp ymin, fp zmin, fp xmax, fp ymax, fp zmax)
Definition at line 201 of file grid.h.
References VtkGridBinaryWriter< FileWriter, fp >::addPoint(), and VtkGridWriterBase< FileWriter >::cellCount.
addCell()
template<typename FileWriter , typename fp = float> void VtkGridBinaryWriter< FileWriter, fp >::addCell (unsigned long idx) private
Definition at line 147 of file grid.h.
References VtkGridWriterBase< FileWriter >::byteswapped(), and VtkGridWriterBase< FileWriter >::writer.
Referenced by VtkGridBinaryWriter< FileWriter, fp >::addCells().
addCells()
template<typename FileWriter , typename fp = float> void VtkGridBinaryWriter< FileWriter, fp >::addCells () private
Definition at line 159 of file grid.h.
References VtkGridBinaryWriter< FileWriter, fp >::addCell(), assert, VtkGridWriterBase< FileWriter >::cellCount, and VtkGridWriterBase< FileWriter >::writer.
Referenced by VtkGridBinaryWriter< FileWriter, fp >::finish().
addCellTypes()
template<typename FileWriter , typename fp = float> void VtkGridBinaryWriter< FileWriter, fp >::addCellTypes () private
Definition at line 171 of file grid.h.
References assert, VtkGridWriterBase< FileWriter >::byteswapped(), VtkGridWriterBase< FileWriter >::cellCount, and VtkGridWriterBase< FileWriter >::writer.
Referenced by VtkGridBinaryWriter< FileWriter, fp >::finish().
addPoint()
template<typename FileWriter , typename fp = float> void VtkGridBinaryWriter< FileWriter, fp >::addPoint (fp x, fp y, fp z) private
Definition at line 141 of file grid.h.
References VtkGridWriterBase< FileWriter >::byteswapped(), and VtkGridWriterBase< FileWriter >::writer.
Referenced by VtkGridBinaryWriter< FileWriter, fp >::add().
finish()
template<typename FileWriter , typename fp = float> void VtkGridBinaryWriter< FileWriter, fp >::finish ()
Definition at line 217 of file grid.h.
References VtkGridBinaryWriter< FileWriter, fp >::addCells(), VtkGridBinaryWriter< FileWriter, fp >::addCellTypes(), VtkGridWriterBase< FileWriter >::updatePointsCount(), and VtkGridWriterBase< FileWriter >::writer.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/vtk/writer/grid.h