Peano
ThreadPool::PooledThread Struct Reference
Public Member Functions
bool isBusy () const
bool isDead () const
void assignWork (std::function< void()> newRunnable)
void sendShutdown ()
void join ()
Static Public Member Functions
static void threadLoop (PooledThread *self)
Data Fields
std::thread thread
std::mutex mutex
std::condition_variable cv
std::function< void()> runnable = nullptr
std::atomic_bool busy = false
std::atomic_bool shutdown = false
std::atomic_bool dead = false
Detailed Description
Definition at line 12 of file thread_pool.h.
Member Function Documentation
assignWork()
void ThreadPool::PooledThread::assignWork (std::function< void()> newRunnable)
Definition at line 29 of file thread_pool.h.
References assert, and isBusy().
isBusy()
bool ThreadPool::PooledThread::isBusy () const
Definition at line 21 of file thread_pool.h.
Referenced by assignWork().
isDead()
bool ThreadPool::PooledThread::isDead () const
Definition at line 25 of file thread_pool.h.
Referenced by join().
join()
void ThreadPool::PooledThread::join ()
Definition at line 41 of file thread_pool.h.
References assert, and isDead().
sendShutdown()
void ThreadPool::PooledThread::sendShutdown ()
Definition at line 36 of file thread_pool.h.
threadLoop()
static void ThreadPool::PooledThread::threadLoop (PooledThread * self) static
Definition at line 46 of file thread_pool.h.
References busy, cv, dead, mutex, runnable, and shutdown.
Referenced by ThreadPool::ThreadPool().
Field Documentation
busy
std::atomic_bool ThreadPool::PooledThread::busy = false
Definition at line 17 of file thread_pool.h.
Referenced by threadLoop().
cv
std::condition_variable ThreadPool::PooledThread::cv
Definition at line 15 of file thread_pool.h.
Referenced by threadLoop().
dead
std::atomic_bool ThreadPool::PooledThread::dead = false
Definition at line 19 of file thread_pool.h.
Referenced by threadLoop().
mutex
std::mutex ThreadPool::PooledThread::mutex
Definition at line 14 of file thread_pool.h.
Referenced by threadLoop().
runnable
std::function<void()> ThreadPool::PooledThread::runnable = nullptr
Definition at line 16 of file thread_pool.h.
Referenced by threadLoop().
shutdown
std::atomic_bool ThreadPool::PooledThread::shutdown = false
Definition at line 18 of file thread_pool.h.
Referenced by threadLoop().
thread
std::thread ThreadPool::PooledThread::thread
Definition at line 13 of file thread_pool.h.
The documentation for this struct was generated from the following file:
benchmarks/other/noh2d-common/spacetree/lang/thread_pool.h