Peano
toolbox::blockstructured::tests::IandRInMatricesTest Class Reference
#include <IandRInMatricesTest.h>
Public Member Functions
IandRInMatricesTest ()
Cosntructor.
virtual ~IandRInMatricesTest ()=default
Destructor, empty.
virtual void run () override
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void compareInterpolateLinearCaseToTensorProductPatch ()
The matrix interpolation and restriction scheme is tested by comparing the results to the tensor product scheme.
void compareRestrictLinearCaseToTensorProductPatch ()
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Definition at line 17 of file IandRInMatricesTest.h.
Constructor & Destructor Documentation
IandRInMatricesTest()
toolbox::blockstructured::tests::IandRInMatricesTest::IandRInMatricesTest ()
Cosntructor.
Definition at line 10 of file IandRInMatricesTest.cpp.
~IandRInMatricesTest()
virtual toolbox::blockstructured::tests::IandRInMatricesTest::~IandRInMatricesTest () virtual default
Destructor, empty.
Member Function Documentation
compareInterpolateLinearCaseToTensorProductPatch()
void toolbox::blockstructured::tests::IandRInMatricesTest::compareInterpolateLinearCaseToTensorProductPatch () private
The matrix interpolation and restriction scheme is tested by comparing the results to the tensor product scheme.
Definition at line 18 of file IandRInMatricesTest.cpp.
References tarch::freeMemory(), peano4::datamanagement::FaceMarker::getRelativePositionWithinFatherCell(), tarch::Heap, toolbox::blockstructured::interpolateHaloLayer_AoS_matrix(), toolbox::blockstructured::interpolateHaloLayer_AoS_tensor_product(), peano4::grid::GridTraversalEvent::setRelativePositionToFather(), and validateNumericalEqualsWithEpsWithParams2.
compareRestrictLinearCaseToTensorProductPatch()
void toolbox::blockstructured::tests::IandRInMatricesTest::compareRestrictLinearCaseToTensorProductPatch () private
Definition at line 1078 of file IandRInMatricesTest.cpp.
References tarch::freeMemory(), peano4::datamanagement::FaceMarker::getRelativePositionWithinFatherCell(), tarch::Heap, toolbox::blockstructured::restrictHaloLayer_AoS_matrix(), toolbox::blockstructured::restrictHaloLayer_AoS_tensor_product(), peano4::grid::GridTraversalEvent::setRelativePositionToFather(), and validateNumericalEqualsWithEpsWithParams3.
run()
void toolbox::blockstructured::tests::IandRInMatricesTest::run () override virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 13 of file IandRInMatricesTest.cpp.
References testMethod.
The documentation for this class was generated from the following files:
src/toolbox/blockstructured/tests/IandRInMatricesTest.h
src/toolbox/blockstructured/tests/IandRInMatricesTest.cpp