var AbstractRungeKuttaDGActionSet_8py =
[
    [ "exahype2.solvers.rkdg.actionsets.AbstractRungeKuttaDGActionSet.AbstractRungeKuttaDGActionSet", "d3/d49/classexahype2_1_1solvers_1_1rkdg_1_1actionsets_1_1AbstractRungeKuttaDGActionSet_1_1AbstractRungeKuttaDGActionSet.html", "d3/d49/classexahype2_1_1solvers_1_1rkdg_1_1actionsets_1_1AbstractRungeKuttaDGActionSet_1_1AbstractRungeKuttaDGActionSet" ]
];