Peano
tarch::la::tests::VectorTest Class Reference
Provides tests for types Vector, DynamicVector and all Vector functionality.
#include <VectorTest.h>
Public Member Functions
VectorTest ()
Cosntructor.
virtual ~VectorTest ()
Destructor, empty.
virtual void run ()
This routine is triggered by the TestCaseCollection.
virtual void setUp ()
Setup your test case.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void testConstruction ()
Tests constructors.
void testAssignment ()
Tests methods from VectorAssign.h and operator= from Vector types.
void testVectorOperations ()
Tests methods from VectorOperations.h.
void testVectorScalarOperations ()
Tests methods from VectorScalarOperations.h.
void testVectorVectorOperations ()
Tests methods from VectorVectorOperations.h.
void testWrappedVector ()
Tests wrapping a raw array with (static) vector semantics.
void testVectorCompare ()
Tests methods from VectorCompare.h.
void testVectorVectorCompare ()
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Provides tests for types Vector, DynamicVector and all Vector functionality.
Definition at line 18 of file VectorTest.h.
Constructor & Destructor Documentation
VectorTest()
tarch::la::tests::VectorTest::VectorTest ()
Cosntructor.
Definition at line 9 of file VectorTest.cpp.
~VectorTest()
virtual tarch::la::tests::VectorTest::~VectorTest () virtual
Destructor, empty.
Definition at line 69 of file VectorTest.h.
Member Function Documentation
run()
void tarch::la::tests::VectorTest::run () virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 14 of file VectorTest.cpp.
References testMethod.
setUp()
virtual void tarch::la::tests::VectorTest::setUp () virtual
Setup your test case.
Definition at line 79 of file VectorTest.h.
testAssignment()
void tarch::la::tests::VectorTest::testAssignment () private
Tests methods from VectorAssign.h and operator= from Vector types.
Definition at line 84 of file VectorTest.cpp.
References tarch::toString(), validateEquals, and validateEqualsWithParams1.
testConstruction()
void tarch::la::tests::VectorTest::testConstruction () private
Tests constructors.
Definition at line 52 of file VectorTest.cpp.
References tarch::la::max(), and validateEquals.
testVectorCompare()
void tarch::la::tests::VectorTest::testVectorCompare () private
Tests methods from VectorCompare.h.
Definition at line 331 of file VectorTest.cpp.
testVectorOperations()
void tarch::la::tests::VectorTest::testVectorOperations () private
Tests methods from VectorOperations.h.
Definition at line 125 of file VectorTest.cpp.
References tarch::la::indexMax(), tarch::la::indexMin(), tarch::la::max(), tarch::la::min(), tarch::la::norm1(), tarch::la::sum(), and validateEquals.
testVectorScalarOperations()
void tarch::la::tests::VectorTest::testVectorScalarOperations () private
Tests methods from VectorScalarOperations.h.
Definition at line 149 of file VectorTest.cpp.
References tarch::toString(), validateEquals, and validateEqualsWithParams1.
testVectorVectorCompare()
void tarch::la::tests::VectorTest::testVectorVectorCompare () private
Definition at line 28 of file VectorTest.cpp.
testVectorVectorOperations()
void tarch::la::tests::VectorTest::testVectorVectorOperations () private
Tests methods from VectorVectorOperations.h.
Definition at line 201 of file VectorTest.cpp.
References a, tarch::la::allGreater(), tarch::la::cross(), tarch::la::dot(), tarch::la::equals(), tarch::la::equalsReturnIndex(), tarch::la::firstGreater(), tarch::la::max(), tarch::la::oneGreater(), tarch::la::oneGreaterEquals(), validate, validateEquals, validateWithParams2, and validateWithParams3.
testWrappedVector()
void tarch::la::tests::VectorTest::testWrappedVector () private
Tests wrapping a raw array with (static) vector semantics.
Definition at line 313 of file VectorTest.cpp.
References tarch::la::max(), tarch::la::slice(), tarch::toString(), validateEquals, and validateEqualsWithParams1.
The documentation for this class was generated from the following files:
src/tarch/la/tests/VectorTest.h
src/tarch/la/tests/VectorTest.cpp