Peano
Edge Class Reference
#include <edge.h>
Public Member Functions
Edge (Coordinate a_direction)
Edge (std::vector< double > a_data, Coordinate a_direction)
Edge (Coordinate a_direction, double start[3], double stop[3], int n)
Edge (const Edge &other)
Edge & operator= (Edge other)
Edge subedge (int start, int stop)
void split (double intersection_node[3], Edge &left_edge, Edge &right_edge)
Edge remesh (int numNodesNew)
Edge interpolate (std::vector< double > const &range_in, std::vector< double > const &range_out, int window=11)
void resize (int i)
void push_back (double d)
int size () const
int numNodes () const
std::string printEdge () const
double & operator() (int coord, int i)
double const & operator() (int coord, int i) const
std::vector< double > & getData ()
Coordinate getDirection ()
Private Attributes
Coordinate direction
std::vector< double > data
Friends
std::ostream & operator<< (std::ostream &ss, const Edge &e)
Detailed Description
Definition at line 8 of file edge.h.
Constructor & Destructor Documentation
Edge() [1/4]
Edge::Edge (Coordinate a_direction)
Definition at line 6 of file edge.cpp.
References data, and direction.
Referenced by interpolate(), and subedge().
Edge() [2/4]
Edge::Edge (std::vector< double > a_data, Coordinate a_direction)
Definition at line 12 of file edge.cpp.
References data, and direction.
Edge() [3/4]
Edge::Edge (Coordinate a_direction, double start[3], double stop[3], int n)
Definition at line 18 of file edge.cpp.
References data, direction, Index::getRange(), and NCOORDS.
Edge() [4/4]
Edge::Edge (const Edge & other)
Definition at line 31 of file edge.cpp.
References data, and direction.
Member Function Documentation
getData()
std::vector< double > & Edge::getData ()
Definition at line 214 of file edge.cpp.
References data.
getDirection()
Coordinate Edge::getDirection ()
Definition at line 43 of file edge.h.
References direction.
Referenced by FaceBoundary::checkConformity(), and FaceBoundary::split().
interpolate()
Edge Edge::interpolate (std::vector< double > const & range_in, std::vector< double > const & range_out, int window = 11)
Definition at line 148 of file edge.cpp.
References std::abs(), data, direction, Edge(), int, Interpolation::Lagrange::interpolate1D(), and NCOORDS.
Referenced by remesh(), and split().
numNodes()
int Edge::numNodes () const
Definition at line 210 of file edge.cpp.
References NCOORDS, and size().
Referenced by FaceBoundary::checkConformity(), FaceBoundary::FaceBoundary(), operator()(), operator()(), printEdge(), remesh(), FaceBoundary::split(), split(), and subedge().
operator()() [1/2]
double & Edge::operator() (int coord, int i)
Definition at line 218 of file edge.cpp.
References data, NCOORDS, and numNodes().
operator()() [2/2]
double const & Edge::operator() (int coord, int i) const
Definition at line 223 of file edge.cpp.
References data, NCOORDS, and numNodes().
operator=()
Edge & Edge::operator= (Edge other)
Definition at line 36 of file edge.cpp.
References data, and direction.
printEdge()
std::string Edge::printEdge () const
Definition at line 229 of file edge.cpp.
References coordToString(), NCOORDS, and numNodes().
Referenced by FaceBoundary::printNodes().
push_back()
void Edge::push_back (double d)
Definition at line 198 of file edge.cpp.
References data.
Referenced by FaceBoundary::FaceBoundary().
remesh()
Edge Edge::remesh (int numNodesNew)
Definition at line 132 of file edge.cpp.
References Index::getRange(), interpolate(), and numNodes().
Referenced by FaceBoundary::split().
resize()
void Edge::resize (int i)
Definition at line 201 of file edge.cpp.
References data.
Referenced by FaceBoundary::FaceBoundary(), and Face::split().
size()
int Edge::size () const
Definition at line 206 of file edge.cpp.
References data.
Referenced by peano4.visualisation.input.Patch.Patch::__repr__(), numNodes(), and FaceBoundary::split().
split()
void Edge::split (double intersection_node[3], Edge & left_edge, Edge & right_edge)
Definition at line 64 of file edge.cpp.
References coordToString(), data, direction, double, Index::getRange(), interpolate(), NCOORDS, numNodes(), and subedge().
Referenced by FaceBoundary::split().
subedge()
Edge Edge::subedge (int start, int stop)
Definition at line 43 of file edge.cpp.
References data, direction, Edge(), NCOORDS, and numNodes().
Referenced by split().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & ss, const Edge & e) friend
Definition at line 249 of file edge.cpp.
Field Documentation
data
std::vector<double> Edge::data private
Definition at line 49 of file edge.h.
Referenced by peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__generate_dastgen_input_file(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__get_file_name(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::__get_full_qualified_file_name(), swift2.particle.Particle.Particle::__init__(), swift2.particle.Particle.Particle::_add_dependency_checks(), swift2.particle.Particle.Particle::_dependency_checks_modify_steps(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_boolean_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_boolean_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_double_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_double_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_enum_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_integer_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_integer_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_peano_double_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_peano_integer_array_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_string_attributes(), swift2.particle.tests.DastgenTestDummyParticle.DastgenTestDummyParticle::_generate_user_defined_attributes(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::_get_dictionary_for_output(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::construct_output(), peano4.datamodel.DynamicArrayOverPrimitivesToStdVector.DynamicArrayOverPrimitivesToStdVector::construct_output(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::construct_output(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::construct_output(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::construct_output(), Edge(), Edge(), Edge(), Edge(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::get_header_file_include(), peano4.datamodel.DynamicArrayOverPrimitivesToStdVector.DynamicArrayOverPrimitivesToStdVector::get_header_file_include(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::get_header_file_include(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::get_header_file_include(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::get_header_file_include(), peano4.datamodel.DaStGenToLegacyTool.DaStGenToLegacyTool::get_stack_container(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::get_stack_container(), peano4.datamodel.PatchToDoubleArrayOnHeap.PatchToDoubleArrayOnHeap::get_stack_container(), peano4.datamodel.PatchToDoubleArrayWithSmartPointer.PatchToDoubleArrayWithSmartPointer::get_stack_container(), getData(), peano4.datamodel.DaStGen2.DaStGen2::hosts_smart_pointer_attribute(), interpolate(), operator()(), operator()(), operator=(), push_back(), swift2.particle.Particle.Particle::readme_descriptor(), resize(), swift2.particle.SPHLeapfrogFixedSearchRadius.SPHLeapfrogFixedSearchRadius::set_parameters(), swift2.particle.SPHParticle.SPHParticle::set_parameters(), swift2.particle.tests.testLeapfrogFixedTimeStepSize.testLeapfrogFixedTimeStepSize::set_parameters(), size(), split(), and subedge().
direction
Coordinate Edge::direction private
Definition at line 48 of file edge.h.
Referenced by Edge(), Edge(), Edge(), Edge(), getDirection(), interpolate(), operator=(), split(), and subedge().
The documentation for this class was generated from the following files:
src/toolbox/curvi/geometry/edge.h
src/toolbox/curvi/geometry/edge.cpp