Peano
tarch::timing::GlidingAverageMeasurement Class Reference
GlidingAverageMeasurement.
#include <GlidingAverageMeasurement.h>
Public Member Functions
GlidingAverageMeasurement (double weight=0.7, int maxEntries=16)
~GlidingAverageMeasurement ()=default
double getValue () const
double getStandardDeviation () const
To compute the standard deviation, we rely on the formula.
bool hasFullSetOfMeasurements () const
bool isAccurateValue (double factor=0.1) const
Is value accurate.
void setValue (const double &value)
Set the value.
std::string toString () const
double max () const
double min () const
void erase ()
int getObservationSpan () const
Private Attributes
const double _weight
The weights q determine the weight via $q^0,q^1,q^2,...$.
const int _maxEntries
std::vector< double > _values
Data.
Static Private Attributes
static tarch::logging::Log _log
Detailed Description
GlidingAverageMeasurement.
This is an alternative implementation to Measurement which uses a gliding average rather than the real average over all data.
Author
Tobias Weinzierl
Definition at line 26 of file GlidingAverageMeasurement.h.
Constructor & Destructor Documentation
GlidingAverageMeasurement()
tarch::timing::GlidingAverageMeasurement::GlidingAverageMeasurement (double weight = 0.7, int maxEntries = 16)
Definition at line 18 of file GlidingAverageMeasurement.cpp.
References assertion1, and max().
~GlidingAverageMeasurement()
tarch::timing::GlidingAverageMeasurement::~GlidingAverageMeasurement () default
Member Function Documentation
erase()
void tarch::timing::GlidingAverageMeasurement::erase ()
Definition at line 26 of file GlidingAverageMeasurement.cpp.
getObservationSpan()
int tarch::timing::GlidingAverageMeasurement::getObservationSpan () const
Returns
How many values do feed into a single result, i.e. how many entries do we keep track of?
Definition at line 129 of file GlidingAverageMeasurement.cpp.
getStandardDeviation()
double tarch::timing::GlidingAverageMeasurement::getStandardDeviation () const
To compute the standard deviation, we rely on the formula.
sigma =sqrt(E(x^2) - E(x)^2)
with E being the weighted mean value.
Definition at line 46 of file GlidingAverageMeasurement.cpp.
References tarch::la::NUMERICAL_ZERO_DIFFERENCE.
getValue()
double tarch::timing::GlidingAverageMeasurement::getValue () const
Returns
Averaged value (mean value) of all measurements.
Definition at line 29 of file GlidingAverageMeasurement.cpp.
hasFullSetOfMeasurements()
bool tarch::timing::GlidingAverageMeasurement::hasFullSetOfMeasurements () const
Returns
Number of setValue() calls has exceeded the maxEntries argument from the constructor
Definition at line 124 of file GlidingAverageMeasurement.cpp.
isAccurateValue()
bool tarch::timing::GlidingAverageMeasurement::isAccurateValue (double factor = 0.1) const
Is value accurate.
A value is accurate if its standard deviation divided by its mean is smaller than the factor.
Definition at line 71 of file GlidingAverageMeasurement.cpp.
References std::abs().
max()
double tarch::timing::GlidingAverageMeasurement::max () const
Definition at line 106 of file GlidingAverageMeasurement.cpp.
Referenced by exahype2.ArgumentParser.ArgumentParser::__init__(), peano4.dastgen2.MPIAndStorageAspect.MPIAndStorageAspect::__str__(), exahype2.solvers.limiting.kernels.Limiter.Limiter::_build_gemms(), mgccz4.MGCCZ4Solver::add_derivative_calculation(), package.Exahype2::cmake_args(), peano4.toolbox.particles.api.UpdateParticleGridAssociation_Reassign.UpdateParticleGridAssociation_Reassign::get_body_of_operation(), mghype.api.matrixgenerators.DLinear.DLinear::get_cell_identity_matrix(), api.solvers.CollocatedLowOrderDiscretisation.AssemblePetscMatrix::get_constructor_body(), api.solvers.DiscontinuousGalerkinDiscretisation.AssemblePetscMatrix::get_constructor_body(), matrices.DgGenerator::getCellCellMassMatrix(), matrices.DgGenerator::getCellCellSystemMatrix(), matrices.DgGenerator::getCellToFaceMatrix(), matrices.DgGenerator::getFaceFaceMatrix(), GlidingAverageMeasurement(), package.Exahype2::install(), and package.Exahype2::setup_run_environment().
min()
double tarch::timing::GlidingAverageMeasurement::min () const
Definition at line 115 of file GlidingAverageMeasurement.cpp.
setValue()
void tarch::timing::GlidingAverageMeasurement::setValue (const double & value)
Set the value.
If the measurement already holds a value, this value is not overwritten. Instead, the measurement accumulates all values and returns the average.
Definition at line 82 of file GlidingAverageMeasurement.cpp.
toString()
std::string tarch::timing::GlidingAverageMeasurement::toString () const
Definition at line 95 of file GlidingAverageMeasurement.cpp.
Field Documentation
_log
tarch::logging::Log tarch::timing::GlidingAverageMeasurement::_log static private
Definition at line 28 of file GlidingAverageMeasurement.h.
_maxEntries
const int tarch::timing::GlidingAverageMeasurement::_maxEntries private
Definition at line 34 of file GlidingAverageMeasurement.h.
_values
std::vector<double> tarch::timing::GlidingAverageMeasurement::_values private
Data.
Definition at line 39 of file GlidingAverageMeasurement.h.
_weight
const double tarch::timing::GlidingAverageMeasurement::_weight private
The weights q determine the weight via $q^0,q^1,q^2,...$.
Definition at line 33 of file GlidingAverageMeasurement.h.
The documentation for this class was generated from the following files:
src/tarch/timing/GlidingAverageMeasurement.h
src/tarch/timing/GlidingAverageMeasurement.cpp