Peano
TP_Logging.cpp File Reference
#include "libtwopunctures/TP_Logging.h"
#include <vector>
#include <cstdio>
Functions
std::string vformat (const char *fmt, va_list ap)
Function Documentation
vformat()
std::string vformat (const char * fmt, va_list ap)
Definition at line 7 of file TP_Logging.cpp.
Referenced by TP::LoggingAdapter::TP_ERROR(), TP::LoggingAdapter::TP_INFO(), TP::LoggingAdapter::TP_LOG(), and TP::LoggingAdapter::TP_WARN().