Peano
exahype2::FaceData< inType, outType > Struct Template Reference
Represents the sides of one face, with 2 sides (left and right) to a face For ADER QIn will contain the values, QOut would contain the fluxes QIn[faceId][0][...] will contain the values of the left side relative to the face QIn[faceId][1][...] will contain the values of the right side relative to the face.
#include <LRFaceData.h>
Public Member Functions
FaceData (inType *QIn_[2], const tarch::la::Vector< Dimensions, double > &faceCentre_, const tarch::la::Vector< Dimensions, double > &faceSize_, double t_, double dt_, outType *QOut_[2], tarch::MemoryLocation memoryLocation_=tarch::MemoryLocation::Heap, int targetDevice_=tarch::accelerator::Device::DefaultDevice)
Construct patch data object for one single cell.
FaceData (int numberOfFaces_, tarch::MemoryLocation memoryLocation_=tarch::MemoryLocation::Heap, int targetDevice_=tarch::accelerator::Device::DefaultDevice)
FaceData (const FaceData &copy)=delete
FaceData & operator= (const FaceData &)=delete
~FaceData ()
std::string toString () const
Data Fields
inType *(* QIn)[2]
QIn may not be const, as some kernels delete it straightaway once the input data has been handled.
tarch::la::Vector< Dimensions, double > * faceCentre
tarch::la::Vector< Dimensions, double > * faceSize
double * t
double * dt
int * id
Id of underlying task.
const int numberOfFaces
As we store data as SoA, we have to know how big the actual arrays are.
const tarch::MemoryLocation memoryLocation
We might want to allocate data on the heap or an accelerator, therefore we save the target device id.
const int targetDevice
We might want to allocate data on an accelerator, therefore we save the target device id.
outType *(* QOut)[2]
Out values.
Detailed Description
template<typename inType = double, typename outType = double>
struct exahype2::FaceData< inType, outType >
Represents the sides of one face, with 2 sides (left and right) to a face For ADER QIn will contain the values, QOut would contain the fluxes QIn[faceId][0][...] will contain the values of the left side relative to the face QIn[faceId][1][...] will contain the values of the right side relative to the face.
Definition at line 21 of file LRFaceData.h.
Constructor & Destructor Documentation
FaceData() [1/3]
template<typename inType , typename outType > exahype2::FaceData< inType, outType >::FaceData (inType * QIn_[2], const tarch::la::Vector< Dimensions, double > & faceCentre_, const tarch::la::Vector< Dimensions, double > & faceSize_, double t_, double dt_, outType * QOut_[2], tarch::MemoryLocation memoryLocation_ = tarch::MemoryLocation::Heap, int targetDevice_ = tarch::accelerator::Device::DefaultDevice)
Construct patch data object for one single cell.
Usually, I do so only to be able to use the same kernels everywhere: Kernels accept FaceData, i.e. multiple patches. Even if we have only one cell, we thus wrap this cell's data into an instance of FaceData and pass it in. The id can be set to any dummy in this case, as we know which task has wrapped this single cell, i.e. we usually do not read it later.
Definition at line 101 of file LRFaceData.h.
References exahype2::FaceData< inType, outType >::dt, exahype2::FaceData< inType, outType >::faceCentre, exahype2::FaceData< inType, outType >::faceSize, exahype2::FaceData< inType, outType >::QIn, exahype2::FaceData< inType, outType >::QOut, and exahype2::FaceData< inType, outType >::t.
FaceData() [2/3]
template<typename inType , typename outType > exahype2::FaceData< inType, outType >::FaceData (int numberOfFaces_, tarch::MemoryLocation memoryLocation_ = tarch::MemoryLocation::Heap, int targetDevice_ = tarch::accelerator::Device::DefaultDevice)
Definition at line 122 of file LRFaceData.h.
References tarch::accelerator::MemoryManager::allocate(), exahype2::FaceData< inType, outType >::dt, exahype2::FaceData< inType, outType >::faceCentre, exahype2::FaceData< inType, outType >::faceSize, tarch::accelerator::MemoryManager::getInstance(), exahype2::FaceData< inType, outType >::QIn, exahype2::FaceData< inType, outType >::QOut, and exahype2::FaceData< inType, outType >::t.
FaceData() [3/3]
template<typename inType = double, typename outType = double> exahype2::FaceData< inType, outType >::FaceData (const FaceData< inType, outType > & copy) delete
~FaceData()
template<typename inType , typename outType > exahype2::FaceData< inType, outType >::~FaceData ()
Definition at line 157 of file LRFaceData.h.
References tarch::accelerator::MemoryManager::free(), tarch::accelerator::MemoryManager::getInstance(), and targetDevice.
Member Function Documentation
operator=()
template<typename inType = double, typename outType = double> FaceData & exahype2::FaceData< inType, outType >::operator= (const FaceData< inType, outType > &) delete
toString()
template<typename inType , typename outType > std::string exahype2::FaceData< inType, outType >::toString () const
Definition at line 175 of file LRFaceData.h.
Field Documentation
dt
template<typename inType = double, typename outType = double> double* exahype2::FaceData< inType, outType >::dt
Definition at line 31 of file LRFaceData.h.
Referenced by exahype2::FaceData< inType, outType >::FaceData(), exahype2::FaceData< inType, outType >::FaceData(), firstTask(), firstTask(), variant4::runBenchmarks(), variant5::runBenchmarks(), variant6::runBenchmarks(), and runKernels().
faceCentre
template<typename inType = double, typename outType = double> tarch::la::Vector<Dimensions, double>* exahype2::FaceData< inType, outType >::faceCentre
Definition at line 27 of file LRFaceData.h.
Referenced by exahype2::FaceData< inType, outType >::FaceData(), exahype2::FaceData< inType, outType >::FaceData(), firstTask(), firstTask(), variant4::runBenchmarks(), variant5::runBenchmarks(), variant6::runBenchmarks(), and runKernels().
faceSize
template<typename inType = double, typename outType = double> tarch::la::Vector<Dimensions, double>* exahype2::FaceData< inType, outType >::faceSize
Definition at line 28 of file LRFaceData.h.
Referenced by exahype2::FaceData< inType, outType >::FaceData(), exahype2::FaceData< inType, outType >::FaceData(), firstTask(), firstTask(), variant4::runBenchmarks(), variant5::runBenchmarks(), variant6::runBenchmarks(), and runKernels().
id
template<typename inType = double, typename outType = double> int* exahype2::FaceData< inType, outType >::id
Id of underlying task.
Required when we fuse many enclave tasks and load them off to the GPU, as we have to know afterwards which outcome corresponds to which task.
Definition at line 38 of file LRFaceData.h.
memoryLocation
template<typename inType = double, typename outType = double> const tarch::MemoryLocation exahype2::FaceData< inType, outType >::memoryLocation
We might want to allocate data on the heap or an accelerator, therefore we save the target device id.
Definition at line 50 of file LRFaceData.h.
numberOfFaces
template<typename inType = double, typename outType = double> const int exahype2::FaceData< inType, outType >::numberOfFaces
As we store data as SoA, we have to know how big the actual arrays are.
Definition at line 44 of file LRFaceData.h.
QIn
template<typename inType = double, typename outType = double> inType*(* exahype2::FaceData< inType, outType >::QIn)[2]
QIn may not be const, as some kernels delete it straightaway once the input data has been handled.
Definition at line 26 of file LRFaceData.h.
Referenced by exahype2::FaceData< inType, outType >::FaceData(), exahype2::FaceData< inType, outType >::FaceData(), firstTask(), firstTask(), initialTask(), variant4::runBenchmarks(), variant5::runBenchmarks(), variant6::runBenchmarks(), runKernels(), and secondTask().
QOut
template<typename inType = double, typename outType = double> outType*(* exahype2::FaceData< inType, outType >::QOut)[2]
Out values.
Definition at line 61 of file LRFaceData.h.
Referenced by exahype2::FaceData< inType, outType >::FaceData(), exahype2::FaceData< inType, outType >::FaceData(), firstTask(), firstTask(), initialTask(), variant4::runBenchmarks(), variant5::runBenchmarks(), variant6::runBenchmarks(), runKernels(), and secondTask().
t
template<typename inType = double, typename outType = double> double* exahype2::FaceData< inType, outType >::t
Definition at line 30 of file LRFaceData.h.
Referenced by exahype2::FaceData< inType, outType >::FaceData(), exahype2::FaceData< inType, outType >::FaceData(), firstTask(), firstTask(), variant4::runBenchmarks(), variant5::runBenchmarks(), variant6::runBenchmarks(), and runKernels().
targetDevice
template<typename inType = double, typename outType = double> const int exahype2::FaceData< inType, outType >::targetDevice
We might want to allocate data on an accelerator, therefore we save the target device id.
Definition at line 56 of file LRFaceData.h.
The documentation for this struct was generated from the following file:
benchmarks/exahype2/kernel-benchmarks/aderdg-fused/LRFaceData.h