Peano
peano4::parallel::Node Class Reference
Node is Peano's abstraction for the hybrid of MPI/threads.
#include <Node.h>
Public Types
enum class ExchangeMode { HorizontalData , VerticalData }
typedef std::pair< int, int > PeriodicBoundaryStackIdentifier
A periodic boundary stack is basically a stack (an integer), but I do augment it by a bitset which identifies which symmetry axis belong to this stack number.
typedef std::pair< int, MPI_Comm > GridDataExchangeMetaInformation
Public Member Functions
~Node ()=default
int getLocalTreeId (int treeId) const
int getGlobalTreeId (int treeId) const
int getNumberOfRegisteredTrees () const
int reserveId (int rank, int forTreeId)
This operation is not const as it does some internal bookkeeping.
int getRank (int treeId) const
You hand in a tree number and the node tells you on which rank such a tree is hosted.
void deregisterId (int id)
Only the SpacetreeSet should call this operation.
bool continueToRun ()
You should call this operation only on the ranks >0 to find out whether you should do more iteration/sweeps.
void setNextProgramStep (int number)
The user tells the set which program step to use, i.e.
int getCurrentProgramStep () const
void init ()
void shutdown ()
The shutdown is invoked by peano4::shutdownSingletons()
void createPendingCommunicators ()
GridDataExchangeMetaInformation getGridDataExchangeMetaInformation (int sendingTreeId, int receivingTreeId, ExchangeMode exchange) const
I use two tags per spacetree per rank: one for boundary data (horizontal) and one for up-down and synchronous (forks) data exchanges (vertical and fork/join).
Static Public Member Functions
static Node & getInstance ()
static void initMPIDatatypes ()
I originally wanted to embed these guys into the singleton's constructor.
static void shutdownMPIDatatypes ()
static bool isGlobalMaster (int treeId)
Is this the global master?
static int getOutputStackNumberForHorizontalDataExchange (int id)
Hand in a spacetree id and get back the number that we should use to send something to this tree.
static int getInputStackNumberForVerticalDataExchange (int id)
Get the input stack where a tree writes all of its vertical data to/from when it exchanges information with id.
static int getOutputStackNumberForVerticalDataExchange (int id)
static int getInputStackNumberForHorizontalDataExchange (int id)
Counterpart of getOutputStackNumberOfBoundaryExchange(int)
static std::set< PeriodicBoundaryStackIdentifier > getOutputStacksForPeriodicBoundaryExchange (const tarch::la::Vector< TwoPowerD, int > &flags)
You hand in a the flags of a vertex and you get the boundary stack identifiers including their directions.
static std::string toString (const std::set< PeriodicBoundaryStackIdentifier > &data)
static int getOutputStackForPeriodicBoundaryExchange (int faceNumber)
Identify output stack for periodic boundary data written by face.
static int getPeriodicBoundaryExchangeInputStackNumberForOutputStack (int outputStackNumber)
Hand in an output stack number of a face and you get back the input stack number.
static PeriodicBoundaryStackIdentifier getPeriodicBoundaryExchangeInputStackNumberForOutputStack (PeriodicBoundaryStackIdentifier outputStackIdentifier)
static int mapPeriodicBoundaryExchangeOutputStackOntoInputStack (int outputStack)
static bool isHorizontalDataExchangeOutputStackNumber (int number)
See getOutputStackNumberOfBoundaryExchange().
static bool isHorizontalDataExchangeInputStackNumber (int number)
static bool isVerticalDataExchangeOutputStackNumber (int number)
static bool isVerticalDataExchangeInputStackNumber (int number)
static bool isPeriodicBoundaryExchangeOutputStackNumber (int number)
static bool isStorageStackNumber (int number)
There are communication stacks and storage stacks.
static int getTreeNumberTiedToExchangeStackNumber (int number)
Gives you back the id of a communication partner, i.e.
static std::string toString (ExchangeMode mode)
static std::string getSemanticsForTag (int tag)
I use this for debugging.
Static Public Attributes
static constexpr int Terminate = -2
static constexpr int MaxSpacetreesPerRank = 1024
static constexpr int UndefProgramStep = -1
Value for _currentProgramStep.
Private Member Functions
Node ()=default
The standard constructor assigns the attributes default values and checks whether the program is compiled using the -DParallel option.
Node (const Node &node)=delete
The copy constructor is private.
int getId (int rank, int localTreeId) const
Peano maps grid instance threads + MPI ranks onto global IDs through this routine.
void registerId (int id, int masterId)
The operation is not thread-safe as we call it only internally, i.e.
Static Private Member Functions
static std::bitset< 2 *Dimensions > getPeriodicBoundaryNumber (const tarch::la::Vector< TwoPowerD, int > &flags)
Analyse to which of the 2d faces it is adjacent.
Private Attributes
tarch::multicore::BooleanSemaphore _semaphore
MPI_Comm _dataExchangeCommunicators [MaxSpacetreesPerRank]
bool _needCommunicator [MaxSpacetreesPerRank]
int _currentProgramStep
int _rankOrchestrationTag
std::map< int, TreeEntry > _treeEntries
Static Private Attributes
static tarch::logging::Log _log
Logging device.
static Node _singleton
static constexpr int StacksPerCommunicationPartner = 4
We need one stack for outgoing data, one for incoming data, and we distinguish horizontal and vertical data flow.
Friends
class peano4::parallel::tests::NodeTest
Detailed Description
Node is Peano's abstraction for the hybrid of MPI/threads.
It represents one spacetree instance basically.
Author
Tobias Weinzierl
Definition at line 29 of file Node.h.
Member Typedef Documentation
GridDataExchangeMetaInformation
typedef std::pair<int, MPI_Comm> peano4::parallel::Node::GridDataExchangeMetaInformation
Definition at line 317 of file Node.h.
PeriodicBoundaryStackIdentifier
typedef std::pair<int, int> peano4::parallel::Node::PeriodicBoundaryStackIdentifier
A periodic boundary stack is basically a stack (an integer), but I do augment it by a bitset which identifies which symmetry axis belong to this stack number.
So if we return (23,010), then data goes to stack 23 and it is a stack that does realise periodic boundary conditions along the y axis.
The second argument (as sketched above) is of type std::bitset<Dimensions>. Unfortunately, bitsets do not work properly within the pair type as they seem not to define the comparison operator properly. So I use an int here and wrap it into a bitset whenever necessary.
See also
toString()
Definition at line 145 of file Node.h.
Member Enumeration Documentation
ExchangeMode
enum class peano4::parallel::Node::ExchangeMode strong
Enumerator
HorizontalData
VerticalData
Vertical data is data running from the master to the worker and the other way round.
Consequently, some tree management data are vertical data, too. See for example peano4::parallel::SpacetreeSet::addSpacetree().
Definition at line 305 of file Node.h.
Constructor & Destructor Documentation
~Node()
peano4::parallel::Node::~Node () default
Node() [1/2]
peano4::parallel::Node::Node () private default
The standard constructor assigns the attributes default values and checks whether the program is compiled using the -DParallel option.
If this is not the case, a warning is logged.
Node() [2/2]
peano4::parallel::Node::Node (const Node & node) private delete
The copy constructor is private.
Member Function Documentation
continueToRun()
bool Node::continueToRun ()
You should call this operation only on the ranks >0 to find out whether you should do more iteration/sweeps.
The spacetree set internally hijacks this operation also on rank 0 to trigger the send out of startup messages. Therefore, the operation is not const.
Definition at line 393 of file Node.cpp.
References tarch::mpi::Rank::getGlobalMasterRank(), tarch::mpi::Rank::getInstance(), tarch::mpi::Rank::getNumberOfRanks(), peano4::parallel::StartTraversalMessage::getStepIdentifier(), logDebug, logTraceIn, logTraceOutWith1Argument, peano4::parallel::StartTraversalMessage::receiveAndPollDanglingMessages(), peano4::parallel::StartTraversalMessage::sendAndPollDanglingMessages(), peano4::parallel::StartTraversalMessage::setStepIdentifier(), and peano4::parallel::StartTraversalMessage::toString().
Referenced by peano4::parallel::SpacetreeSet::traverse().
createPendingCommunicators()
void Node::createPendingCommunicators ()
Definition at line 138 of file Node.cpp.
References tarch::mpi::Rank::getCommunicator(), and tarch::mpi::Rank::getInstance().
Referenced by peano4::parallel::SpacetreeSet::traverse().
deregisterId()
void Node::deregisterId (int id)
Only the SpacetreeSet should call this operation.
See also
getId(int,int)
Definition at line 159 of file Node.cpp.
References assertion1, and logDebug.
Referenced by peano4::parallel::SpacetreeSet::cleanUpTrees().
getCurrentProgramStep()
int Node::getCurrentProgramStep () const
Definition at line 420 of file Node.cpp.
Referenced by selectNextAlgorithmicStep(), and step().
getGlobalTreeId()
int peano4::parallel::Node::getGlobalTreeId (int treeId) const
Definition at line 64 of file Node.h.
References tarch::mpi::Rank::getInstance(), tarch::mpi::Rank::getNumberOfRanks(), and tarch::mpi::Rank::getRank().
getGridDataExchangeMetaInformation()
peano4::parallel::Node::GridDataExchangeMetaInformation Node::getGridDataExchangeMetaInformation (int sendingTreeId, int receivingTreeId, ExchangeMode exchange) const
I use two tags per spacetree per rank: one for boundary data (horizontal) and one for up-down and synchronous (forks) data exchanges (vertical and fork/join).
The nice thing about Peano's new data management is that it is stack-only. Furthermore, all stack data exchange is triggered via the spacetree set, i.e. the order of the stacks is known externally, too. So we effectively do not need that many tags even though we need different tags per tree pair.
Definition at line 446 of file Node.cpp.
References assertion, logTraceInWith3Arguments, logTraceOutWith1Argument, and toString().
Referenced by peano4::parallel::SpacetreeSet::exchangeAllHorizontalDataExchangeStacks(), peano4::parallel::SpacetreeSet::streamDataFromSplittingTreeToNewTree(), and peano4::parallel::tests::NodeTest::testTagCalculation().
getId()
int peano4::parallel::Node::getId (int rank, int localTreeId) const private
Peano maps grid instance threads + MPI ranks onto global IDs through this routine.
To identify a global stack number, please use this function and add it to your local stack number.
Definition at line 387 of file Node.h.
References tarch::mpi::Rank::getInstance(), and tarch::mpi::Rank::getNumberOfRanks().
getInputStackNumberForHorizontalDataExchange()
int Node::getInputStackNumberForHorizontalDataExchange (int id) static
Counterpart of getOutputStackNumberOfBoundaryExchange(int)
Definition at line 184 of file Node.cpp.
References peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance.
Referenced by peano4::parallel::SpacetreeSet::exchangeAllHorizontalDataExchangeStacks(), peano4::grid::Spacetree::receiveAndMergeGridVertexAtHorizontalBoundary(), and peano4::grid::Spacetree::receiveAndMergeUserData().
getInputStackNumberForVerticalDataExchange()
int Node::getInputStackNumberForVerticalDataExchange (int id) static
Get the input stack where a tree writes all of its vertical data to/from when it exchanges information with id.
Such vertical data is multiscale information or split/join data.
Definition at line 192 of file Node.cpp.
References peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance.
Referenced by peano4::grid::Spacetree::receiveAndMergeGridVertexAtVerticalBoundary().
getInstance()
peano4::parallel::Node & Node::getInstance () static
Definition at line 77 of file Node.cpp.
Referenced by peano4::parallel::SpacetreeSet::addSpacetree(), peano4::parallel::SpacetreeSet::answerQuestions(), peano4::parallel::SpacetreeSet::cleanUpTrees(), peano4::maps::HierarchicalStackMap< T >::clear(), peano4::maps::STDStackMap< T >::clear(), peano4::parallel::SpacetreeSet::deleteAllStacks(), peano4::maps::HierarchicalStackMap< T >::empty(), peano4::parallel::SpacetreeSet::exchangeAllHorizontalDataExchangeStacks(), peano4::parallel::SpacetreeSet::exchangeAllPeriodicBoundaryDataStacks(), peano4::maps::HierarchicalStackMap< T >::garbageCollection(), peano4::maps::STDStackMap< T >::garbageCollection(), peano4::parallel::SpacetreeSet::getAnswerTag(), peano4::maps::HierarchicalStackMap< T >::getForPop(), peano4::maps::HierarchicalStackMap< T >::getForPush(), peano4::maps::HierarchicalStackMap< T >::getKeys(), peano4::maps::HierarchicalStackMap< T >::holdsStack(), peano4::parallel::SpacetreeSet::init(), peano4::init(), main(), peano4::grid::Spacetree::receiveAndMergeGridVertexAtHorizontalBoundary(), peano4::grid::Spacetree::receiveAndMergeGridVertexAtVerticalBoundary(), peano4::grid::Spacetree::receiveAndMergeUserData(), runParallel(), runParallel(), selectNextAlgorithmicStep(), peano4::grid::Spacetree::sendGridVertex(), peano4::grid::Spacetree::sendUserData(), peano4::shutdown(), peano4::parallel::SpacetreeSet::split(), step(), peano4::parallel::SpacetreeSet::streamDataFromSplittingTreeToNewTree(), peano4::parallel::tests::NodeTest::testTagCalculation(), peano4::parallel::SpacetreeSet::traverse(), and peano4::grid::Spacetree::updateVertexAfterLoad().
getLocalTreeId()
int peano4::parallel::Node::getLocalTreeId (int treeId) const
Definition at line 59 of file Node.h.
References tarch::mpi::Rank::getInstance(), and tarch::mpi::Rank::getNumberOfRanks().
Referenced by peano4::maps::HierarchicalStackMap< T >::clear(), peano4::maps::STDStackMap< T >::clear(), peano4::maps::HierarchicalStackMap< T >::empty(), peano4::maps::HierarchicalStackMap< T >::garbageCollection(), peano4::maps::STDStackMap< T >::garbageCollection(), peano4::parallel::SpacetreeSet::getAnswerTag(), peano4::maps::HierarchicalStackMap< T >::getForPop(), peano4::maps::HierarchicalStackMap< T >::getForPush(), peano4::maps::HierarchicalStackMap< T >::holdsStack(), and peano4::parallel::tests::NodeTest::testTagCalculation().
getNumberOfRegisteredTrees()
int Node::getNumberOfRegisteredTrees () const
Returns
Number of registered trees on this rank
Definition at line 157 of file Node.cpp.
getOutputStackForPeriodicBoundaryExchange()
int Node::getOutputStackForPeriodicBoundaryExchange (int faceNumber) static
Identify output stack for periodic boundary data written by face.
To make the mapping of face and vertex stacks consistent, we take the face number and determine what the adjacent, i.e. face-connected neighbour volume out of the \(3^d \) adjacent, i.e. vertex-connected volumes is.
Take care that the result is not a mere linearisation of the index. You have to explicitly exclude the centre volume.
See also
getPeriodicBoundaryExchangeInputStackNumberForOutputStack() for a description how to compute an input stack index from the output index.
mapPeriodicBoundaryExchangeOutputStackOntoInputStack() for a mapping of periodic output stacks onto input stacks
Returns
The output stack for a periodic boundary data exchange for one face
Definition at line 212 of file Node.cpp.
References peano4::utils::dLinearised(), peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance, peano4::grid::PeanoCurve::NumberOfPeriodicBoundaryConditionStacks, and ThreePowerD.
Referenced by peano4::grid::Spacetree::receiveAndMergeUserData(), and peano4::grid::Spacetree::sendUserData().
getOutputStackNumberForHorizontalDataExchange()
int Node::getOutputStackNumberForHorizontalDataExchange (int id) static
Hand in a spacetree id and get back the number that we should use to send something to this tree.
Definition at line 180 of file Node.cpp.
References peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance.
Referenced by peano4::parallel::SpacetreeSet::exchangeAllHorizontalDataExchangeStacks(), peano4::grid::Spacetree::sendGridVertex(), and peano4::grid::Spacetree::sendUserData().
getOutputStackNumberForVerticalDataExchange()
int Node::getOutputStackNumberForVerticalDataExchange (int id) static
Definition at line 188 of file Node.cpp.
References peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance.
Referenced by peano4::grid::Spacetree::sendUserData(), peano4::parallel::SpacetreeSet::streamDataFromSplittingTreesToNewTrees(), peano4::parallel::SpacetreeSet::streamDataFromSplittingTreeToNewTree(), and peano4::grid::Spacetree::updateVertexAfterLoad().
getOutputStacksForPeriodicBoundaryExchange()
std::set< peano4::parallel::Node::PeriodicBoundaryStackIdentifier > Node::getOutputStacksForPeriodicBoundaryExchange (const tarch::la::Vector< TwoPowerD, int > & flags) static
You hand in a the flags of a vertex and you get the boundary stack identifiers including their directions.
Algorithm
We first analyse which faces with a periodic boundary flag are adjacent to the vertex. For this, we employ getPeriodicBoundaryNumber(). After that, we build the power set over the result: If a face is adjacent to the upper face and the left face, it also has to communicate along the diagonal, i.e. the logical combination of the two.
We now have to translate these powerset entries into stack indices. For this, we run over the \(3^d \) neighbour cells or a cell, construct the index for this direction, and then look whether this index is contained within the power set.
Implementation
For the powerset, I'd like to use
 std::set< std::bitset<2*Dimensions> > powerSet;
but C++ defines no comparison operator on bitsets and therefore you can't use it in a set.
Definition at line 243 of file Node.cpp.
References assertion5, dfor3, enddforx, logTraceInWith2Arguments, logTraceOutWith2Arguments, peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance, and peano4::grid::PeanoCurve::NumberOfPeriodicBoundaryConditionStacks.
Referenced by peano4::grid::Spacetree::receiveAndMergeGridVertexAtHorizontalBoundary(), peano4::grid::Spacetree::receiveAndMergeUserData(), peano4::grid::Spacetree::sendGridVertex(), peano4::grid::Spacetree::sendUserData(), and peano4::parallel::tests::NodeTest::testGetOutputStacksForPeriodicBoundaryExchange().
getPeriodicBoundaryExchangeInputStackNumberForOutputStack() [1/2]
int Node::getPeriodicBoundaryExchangeInputStackNumberForOutputStack (int outputStackNumber) static
Hand in an output stack number of a face and you get back the input stack number.
If you want to use it for merging data, you have to be careful: Think about the right face of your domain. It is assigned a BC output stack. This routine tells you onto which input stack this output stack is mapped. In return, if you read in the periodic BC data for the right face, you will merge a data with its own! You however have to merge it with the input BC stack from the left face.
This routine is not made to orchestrate the stack exchange! It is meant that you hand in number to which a vertex or face would write to. And then you get the number back which it should read from. This is not how the stacks are permuted after each step! If you want to achieve this, you have to call mapPeriodicBoundaryExchangeOutputStackOntoInputStack().
See also
peano4::parallel::SpacetreeSet::exchangeAllPeriodicBoundaryDataStacks() for a routine which uses this one in return.
peano4::grid::PeanoCurve:MaxNumberOfCoreStacksPerSpacetreeInstance for a discussion of the ordering of the stacks.
Definition at line 323 of file Node.cpp.
References assertion, logTraceInWith4Arguments, logTraceOutWith1Argument, peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance, and peano4::grid::PeanoCurve::NumberOfPeriodicBoundaryConditionStacks.
Referenced by peano4::grid::Spacetree::receiveAndMergeGridVertexAtHorizontalBoundary(), peano4::grid::Spacetree::receiveAndMergeUserData(), and peano4::parallel::tests::NodeTest::testGetOutputStacksForPeriodicBoundaryExchange().
getPeriodicBoundaryExchangeInputStackNumberForOutputStack() [2/2]
peano4::parallel::Node::PeriodicBoundaryStackIdentifier Node::getPeriodicBoundaryExchangeInputStackNumberForOutputStack (PeriodicBoundaryStackIdentifier outputStackIdentifier) static
Definition at line 338 of file Node.cpp.
References assertion, logTraceInWith5Arguments, logTraceOutWith2Arguments, peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance, and peano4::grid::PeanoCurve::NumberOfPeriodicBoundaryConditionStacks.
getPeriodicBoundaryNumber()
std::bitset< 2 *Dimensions > Node::getPeriodicBoundaryNumber (const tarch::la::Vector< TwoPowerD, int > & flags) static private
Analyse to which of the 2d faces it is adjacent.
We enumerate again in the way we always enumerate, i.e. first the face with the x axis as normal, then the one with the y axis, ... And after these d faces, we enumerate all the opposite faces on the cube.
The routine is non-trivial: We store the \(2^d \) adjacency flags per vertex, and now have to work backwards which periodic faces they do represent.
Definition at line 196 of file Node.cpp.
References dfor2, peano4::utils::dLinearised(), enddforx, and peano4::grid::Spacetree::RankOfPeriodicBoundaryCondition.
Referenced by peano4::parallel::tests::NodeTest::testGetPeriodicBoundaryNumber().
getRank()
int peano4::parallel::Node::getRank (int treeId) const
You hand in a tree number and the node tells you on which rank such a tree is hosted.
See also
getId(int,int)
Definition at line 101 of file Node.h.
References tarch::mpi::Rank::getInstance(), and tarch::mpi::Rank::getNumberOfRanks().
Referenced by peano4::parallel::SpacetreeSet::addSpacetree(), peano4::parallel::SpacetreeSet::cleanUpTrees(), peano4::parallel::SpacetreeSet::exchangeAllHorizontalDataExchangeStacks(), and peano4::parallel::SpacetreeSet::streamDataFromSplittingTreeToNewTree().
getSemanticsForTag()
std::string Node::getSemanticsForTag (int tag) static
I use this for debugging.
When I have a tag, I can ask the node whether the node is aware what this tag actually means.
Definition at line 472 of file Node.cpp.
References assertion.
getTreeNumberTiedToExchangeStackNumber()
int Node::getTreeNumberTiedToExchangeStackNumber (int number) static
Gives you back the id of a communication partner, i.e.
a spacetree number, which corresponds to stack number. This works for all kinds of stacks.
Definition at line 389 of file Node.cpp.
References peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance.
Referenced by peano4::parallel::SpacetreeSet::exchangeAllHorizontalDataExchangeStacks().
init()
void Node::init ()
Definition at line 53 of file Node.cpp.
References tarch::mpi::Rank::getInstance(), and tarch::mpi::Rank::reserveFreeTag().
Referenced by peano4::init().
initMPIDatatypes()
void Node::initMPIDatatypes () static
I originally wanted to embed these guys into the singleton's constructor.
However, the singleton might not yet be up when I run the (MPI) tests.
Definition at line 25 of file Node.cpp.
References peano4::datamanagement::CellMarker::initDatatype(), peano4::grid::AutomatonState::initDatatype(), peano4::grid::GridControlEvent::initDatatype(), peano4::grid::GridStatistics::initDatatype(), peano4::grid::GridVertex::initDatatype(), peano4::parallel::StartTraversalMessage::initDatatype(), and peano4::parallel::TreeManagementMessage::initDatatype().
Referenced by peano4::init().
isGlobalMaster()
bool Node::isGlobalMaster (int treeId) static
Is this the global master?
Definition at line 75 of file Node.cpp.
isHorizontalDataExchangeInputStackNumber()
bool Node::isHorizontalDataExchangeInputStackNumber (int number) static
Definition at line 372 of file Node.cpp.
References peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance.
isHorizontalDataExchangeOutputStackNumber()
bool Node::isHorizontalDataExchangeOutputStackNumber (int number) static
See getOutputStackNumberOfBoundaryExchange().
Definition at line 365 of file Node.cpp.
References peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance.
Referenced by peano4::parallel::SpacetreeSet::exchangeAllHorizontalDataExchangeStacks().
isPeriodicBoundaryExchangeOutputStackNumber()
bool Node::isPeriodicBoundaryExchangeOutputStackNumber (int number) static
Definition at line 357 of file Node.cpp.
References peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance, and peano4::grid::PeanoCurve::NumberOfPeriodicBoundaryConditionStacks.
Referenced by peano4::parallel::SpacetreeSet::exchangeAllPeriodicBoundaryDataStacks(), and peano4::parallel::tests::NodeTest::testGetOutputStacksForPeriodicBoundaryExchange().
isStorageStackNumber()
bool Node::isStorageStackNumber (int number) static
There are communication stacks and storage stacks.
This is a storage stack.
Definition at line 168 of file Node.cpp.
References peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance.
Referenced by peano4::maps::HierarchicalStackMap< T >::garbageCollection(), and peano4::maps::STDStackMap< T >::garbageCollection().
isVerticalDataExchangeInputStackNumber()
bool Node::isVerticalDataExchangeInputStackNumber (int number) static
Definition at line 384 of file Node.cpp.
References peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance.
isVerticalDataExchangeOutputStackNumber()
bool Node::isVerticalDataExchangeOutputStackNumber (int number) static
Definition at line 379 of file Node.cpp.
References peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance.
mapPeriodicBoundaryExchangeOutputStackOntoInputStack()
int Node::mapPeriodicBoundaryExchangeOutputStackOntoInputStack (int outputStack) static
See also
tests::NodeTest::testGetOutputStacksForPeriodicBoundaryExchange()
Definition at line 172 of file Node.cpp.
References peano4::grid::PeanoCurve::MaxNumberOfCoreStacksPerSpacetreeInstance, and peano4::grid::PeanoCurve::NumberOfPeriodicBoundaryConditionStacks.
Referenced by peano4::parallel::SpacetreeSet::exchangeAllPeriodicBoundaryDataStacks(), and peano4::parallel::tests::NodeTest::testGetOutputStacksForPeriodicBoundaryExchange().
registerId()
void Node::registerId (int id, int masterId) private
The operation is not thread-safe as we call it only internally, i.e.
you are not supposed to call this function directly.
See also
getId(int,int)
Definition at line 119 of file Node.cpp.
References assertion, assertion2, logDebug, peano4::parallel::TreeEntry::setId(), and peano4::parallel::TreeEntry::setMaster().
reserveId()
int Node::reserveId (int rank, int forTreeId)
This operation is not const as it does some internal bookkeeping.
It internally invokes registerId() on the result.
Parameters
forTreeId If we run a split, this is the rank that wants to split. In general, this always is the parent/master of the new rank. So if you move a rank, you have to ensure that the master is preserved.
Returns
-1 If there are no ids left anymore. In principle, we do not limit the number of threads at all. However, we have to work with a limited number of tags in MPI, so we put a cap on the number of trees per node.
See also
getId(int,int)
Definition at line 79 of file Node.cpp.
References logDebug, logError, and logWarning.
Referenced by peano4::parallel::SpacetreeSet::answerQuestions(), and peano4::parallel::SpacetreeSet::split().
setNextProgramStep()
void Node::setNextProgramStep (int number)
The user tells the set which program step to use, i.e.
which adapter to use for the next grid run or which step to run next. Should only be called on global master.
Definition at line 415 of file Node.cpp.
References assertion1.
Referenced by runParallel(), runParallel(), and selectNextAlgorithmicStep().
shutdown()
void Node::shutdown ()
The shutdown is invoked by peano4::shutdownSingletons()
If we run it on the global master, we set the program state to terminate and distribute this message. For this, we hijack the routine continueToRun(). This is really a hack. We in particular have to be careful and may not call the continue operation on the other ranks. They typically are stuck in a continue while loop in their main routine and just wait for the global master to send out this terminate command.
It is important that this is the very first call when you want your application to go down. Invoked on the global master, it triggers the shutdown on all the other ranks. You will get deadlocks if you try to free any common memory (RDMA) or free datatypes if you don't call the node's shutdown first.
Other ranks might struggle to receive the shutdown command as they might still ask for further subtrees, e.g., or issue load balancing. Therefore, I insert a barrier right after we've issued the shutdown. It makes the rank that goes down handle all incoming data until we can be sure that everybody is in shutdown mode.
Definition at line 422 of file Node.cpp.
References tarch::mpi::Rank::barrier(), tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), logTraceIn, logTraceOut, tarch::services::ServiceRepository::receiveDanglingMessages(), and Terminate.
Referenced by peano4::shutdown().
shutdownMPIDatatypes()
void Node::shutdownMPIDatatypes () static
Definition at line 39 of file Node.cpp.
References peano4::datamanagement::CellMarker::shutdownDatatype(), peano4::grid::AutomatonState::shutdownDatatype(), peano4::grid::GridControlEvent::shutdownDatatype(), peano4::grid::GridStatistics::shutdownDatatype(), peano4::grid::GridVertex::shutdownDatatype(), peano4::parallel::StartTraversalMessage::shutdownDatatype(), and peano4::parallel::TreeManagementMessage::shutdownDatatype().
Referenced by peano4::shutdown().
toString() [1/2]
std::string Node::toString (const std::set< PeriodicBoundaryStackIdentifier > & data) static
Definition at line 225 of file Node.cpp.
Referenced by peano4::parallel::tests::NodeTest::testGetOutputStacksForPeriodicBoundaryExchange().
toString() [2/2]
std::string Node::toString (ExchangeMode mode) static
Definition at line 65 of file Node.cpp.
Friends And Related Symbol Documentation
peano4::parallel::tests::NodeTest
friend class peano4::parallel::tests::NodeTest friend
Definition at line 343 of file Node.h.
Field Documentation
_currentProgramStep
int peano4::parallel::Node::_currentProgramStep private
Definition at line 364 of file Node.h.
_dataExchangeCommunicators
MPI_Comm peano4::parallel::Node::_dataExchangeCommunicators[MaxSpacetreesPerRank] private
Definition at line 361 of file Node.h.
_log
tarch::logging::Log Node::_log static private
Logging device.
Definition at line 348 of file Node.h.
_needCommunicator
bool peano4::parallel::Node::_needCommunicator[MaxSpacetreesPerRank] private
Definition at line 362 of file Node.h.
_rankOrchestrationTag
int peano4::parallel::Node::_rankOrchestrationTag private
Definition at line 366 of file Node.h.
_semaphore
tarch::multicore::BooleanSemaphore peano4::parallel::Node::_semaphore private
Definition at line 352 of file Node.h.
_singleton
peano4::parallel::Node Node::_singleton static private
Definition at line 350 of file Node.h.
_treeEntries
std::map<int, TreeEntry> peano4::parallel::Node::_treeEntries private
Definition at line 368 of file Node.h.
MaxSpacetreesPerRank
constexpr int peano4::parallel::Node::MaxSpacetreesPerRank = 1024 static constexpr
Definition at line 40 of file Node.h.
Referenced by peano4::parallel::SpacetreeSet::init(), and peano4::parallel::tests::NodeTest::testTagCalculation().
StacksPerCommunicationPartner
constexpr int peano4::parallel::Node::StacksPerCommunicationPartner = 4 static constexpr private
We need one stack for outgoing data, one for incoming data, and we distinguish horizontal and vertical data flow.
Definition at line 359 of file Node.h.
Referenced by peano4::parallel::tests::NodeTest::testTagCalculation().
Terminate
constexpr int peano4::parallel::Node::Terminate = -2 static constexpr
Definition at line 38 of file Node.h.
Referenced by shutdown().
UndefProgramStep
constexpr int peano4::parallel::Node::UndefProgramStep = -1 static constexpr
Value for _currentProgramStep.
Definition at line 45 of file Node.h.
The documentation for this class was generated from the following files:
src/peano4/parallel/Node.h
src/peano4/parallel/Node.cpp