Peano
peano4 Namespace Reference
Namespaces
namespace dastgen2
namespace datamanagement
namespace datamodel
namespace grid
The grid namespace is Peano's core.
namespace maps
The map namespaces hosts various map implementations.
namespace output
namespace parallel
namespace Project
namespace runner
namespace solversteps
namespace stacks
namespace toolbox
namespace utils
namespace visualisation
Data Structures
struct SplitInstruction
Instruction to split.
Typedefs
typedef std::map< int, SplitInstruction > SplitSpecification
Functions
void init (int *argc, char ***argv, const tarch::la::Vector< Dimensions, double > &offset, const tarch::la::Vector< Dimensions, double > &width, const std::bitset< Dimensions > &periodicBC=0)
void shutdown ()
tarch::tests::TestCase * getUnitTests ()
Please destroy after usage.
Typedef Documentation
SplitSpecification
typedef std::map<int, SplitInstruction> peano4::SplitSpecification
Definition at line 44 of file grid.h.
Function Documentation
getUnitTests()
tarch::tests::TestCase * peano4::getUnitTests ()
Please destroy after usage.
Definition at line 13 of file UnitTests.cpp.
References tarch::tests::TreeTestCaseCollection::addTestCase().
Referenced by main(), and runTests().
init()
void peano4::init (int * argc, char *** argv, const tarch::la::Vector< Dimensions, double > & offset, const tarch::la::Vector< Dimensions, double > & width, const std::bitset< Dimensions > & periodicBC = 0)
Definition at line 99 of file peano4.cpp.
References peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), tarch::accelerator::Device::getInstance(), tarch::mpi::BooleanSemaphore::BooleanSemaphoreService::getInstance(), tarch::mpi::Rank::getInstance(), tarch::multicore::Core::getInstance(), tarch::services::ServiceRepository::getInstance(), peano4::parallel::Node::init(), tarch::mpi::BooleanSemaphore::BooleanSemaphoreService::init(), tarch::services::ServiceRepository::init(), peano4::parallel::SpacetreeSet::init(), init(), peano4::parallel::Node::initMPIDatatypes(), tarch::initNonCriticalAssertionEnvironment(), periodicBC, tarch::mpi::Rank::setDeadlockTimeOut(), tarch::mpi::Rank::setTimeOutWarning(), peano4::utils::setupLookupTableForDDelinearised(), peano4::utils::setupLookupTableForDLinearised(), and writeCopyrightMessage().
Referenced by init(), and main().
shutdown()
void peano4::shutdown ()
Definition at line 138 of file peano4.cpp.
References peano4::parallel::Node::getInstance(), peano4::parallel::SpacetreeSet::getInstance(), tarch::accelerator::Device::getInstance(), tarch::mpi::BooleanSemaphore::BooleanSemaphoreService::getInstance(), tarch::mpi::Rank::getInstance(), tarch::multicore::Core::getInstance(), tarch::services::ServiceRepository::getInstance(), peano4::parallel::Node::shutdown(), tarch::accelerator::Device::shutdown(), tarch::mpi::Rank::shutdown(), tarch::multicore::Core::shutdown(), peano4::parallel::SpacetreeSet::shutdown(), tarch::mpi::BooleanSemaphore::BooleanSemaphoreService::shutdown(), tarch::services::ServiceRepository::shutdown(), peano4::parallel::Node::shutdownMPIDatatypes(), and tarch::shutdownNonCriticalAssertionEnvironment().
Referenced by main().