Peano
Curvi::Interface Class Reference
#include <interface.h>
Public Member Functions
Interface (std::string file, double a_offset[3], double a_size[3], uint a_elements[3], int a_order)
~Interface ()
void initTree ()
Root * getRoot ()
double invertProjection (Coordinate coord, double coords[3])
Block getElement (double *nodes, int ez, int ey, int ex)
Private Attributes
int order
Root * root
double offset [3]
double size [3]
uint elements [3]
uint modes [3]
uint grid [3]
Detailed Description
Definition at line 10 of file interface.h.
Constructor & Destructor Documentation
Interface()
Curvi::Interface::Interface (std::string file, double a_offset[3], double a_size[3], uint a_elements[3], int a_order)
Definition at line 12 of file interface.h.
References elements, modes, offset, order, root, size, X, Y, and Z.
~Interface()
Curvi::Interface::~Interface ()
Definition at line 46 of file interface.h.
References root.
Member Function Documentation
getElement()
Block Curvi::Interface::getElement (double * nodes, int ez, int ey, int ex)
Definition at line 111 of file interface.h.
References elements, Block::getIndexRange(), Interpolation::Lagrange::interpolate3D(), modes, NCOORDS, order, Block::resample(), root, Root::traverse(), void, X, Y, and Z.
Referenced by ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::initUnknownsPatch().
getRoot()
Root * Curvi::Interface::getRoot ()
Definition at line 55 of file interface.h.
References root.
initTree()
void Curvi::Interface::initTree ()
Definition at line 50 of file interface.h.
References Root::init(), modes, root, and Root::toString().
invertProjection()
double Curvi::Interface::invertProjection (Coordinate coord, double coords[3])
Definition at line 60 of file interface.h.
References Face::getIndexRange(), getPlane(), offset, root, size, and Root::traverseProjection().
Referenced by ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::correctPointSourceLocation().
Field Documentation
elements
uint Curvi::Interface::elements[3] private
Definition at line 198 of file interface.h.
Referenced by getElement(), and Interface().
grid
uint Curvi::Interface::grid[3] private
Definition at line 200 of file interface.h.
modes
uint Curvi::Interface::modes[3] private
Definition at line 199 of file interface.h.
Referenced by getElement(), initTree(), and Interface().
offset
double Curvi::Interface::offset[3] private
Definition at line 196 of file interface.h.
Referenced by peano4.visualisation.input.Patch.Patch::__repr__(), Interface(), and invertProjection().
order
int Curvi::Interface::order private
Definition at line 192 of file interface.h.
Referenced by getElement(), exahype2.solvers.LagrangeBasisWithDiagonalMassMatrix.LagrangeBasisWithDiagonalMassMatrix::init_dictionary_with_default_parameters(), and Interface().
root
Root* Curvi::Interface::root private
Definition at line 194 of file interface.h.
Referenced by getElement(), getRoot(), initTree(), Interface(), invertProjection(), and ~Interface().
size
double Curvi::Interface::size[3] private
Definition at line 197 of file interface.h.
Referenced by peano4.visualisation.input.Patch.Patch::__repr__(), Interface(), and invertProjection().
The documentation for this class was generated from the following file:
src/toolbox/curvi/interface/interface.h