Peano
tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter Class Reference
#include <VTKBinaryFileWriter.h>
Public Member Functions
virtual ~VertexDataWriter ()
virtual void close () override
virtual void plotVertex (int index, double value) override
Write data for one cell.
virtual void plotVertex (int index, const tarch::la::Vector< 2, double > &value) override
virtual void plotVertex (int index, const tarch::la::Vector< 3, double > &value) override
virtual void plotVertex (int index, double *values, int numberOfValues) override
double getMinValue () const
double getMaxValue () const
virtual void assignRemainingVerticesDefaultValues () override
Private Member Functions
VertexDataWriter (const std::string &dataIdentifier, VTKBinaryFileWriter &writer, int recordsPerVertex)
VertexDataWriter (const VertexDataWriter &copy)
Private Attributes
int _lastWriteCommandVertexNumber
VTKBinaryFileWriter & _myWriter
Underlying VTK writer.
std::stringstream _out
Output stream.
int _recordsPerVertex
double _minValue
double _maxValue
std::string _identifier
Friends
class VTKBinaryFileWriter
The father class is a friend.
Detailed Description
Definition at line 297 of file VTKBinaryFileWriter.h.
Constructor & Destructor Documentation
VertexDataWriter() [1/2]
tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::VertexDataWriter (const std::string & dataIdentifier, VTKBinaryFileWriter & writer, int recordsPerVertex) private
Definition at line 7 of file VTKBinaryFileWriter_VertexDataWriter.cpp.
References tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::_doubleOrFloat, _identifier, _myWriter, _out, _recordsPerVertex, and assertion.
VertexDataWriter() [2/2]
tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::VertexDataWriter (const VertexDataWriter & copy) private
Definition at line 329 of file VTKBinaryFileWriter.h.
References assertion.
~VertexDataWriter()
tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::~VertexDataWriter () virtual
Reimplemented from tarch::plotter::griddata::unstructured::UnstructuredGridWriter::VertexDataWriter.
Definition at line 29 of file VTKBinaryFileWriter_VertexDataWriter.cpp.
Member Function Documentation
assignRemainingVerticesDefaultValues()
void tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::assignRemainingVerticesDefaultValues () override virtual
See also
close()
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::VertexDataWriter.
Definition at line 36 of file VTKBinaryFileWriter_VertexDataWriter.cpp.
References assertion4.
close()
void tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::close () override virtual
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::VertexDataWriter.
Definition at line 50 of file VTKBinaryFileWriter_VertexDataWriter.cpp.
References assertion2, assertionMsg, and logWarning.
getMaxValue()
double tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::getMaxValue () const
Definition at line 281 of file VTKBinaryFileWriter_VertexDataWriter.cpp.
getMinValue()
double tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::getMinValue () const
Definition at line 276 of file VTKBinaryFileWriter_VertexDataWriter.cpp.
plotVertex() [1/4]
void tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::plotVertex (int index, const tarch::la::Vector< 2, double > & value) override virtual
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::VertexDataWriter.
Definition at line 115 of file VTKBinaryFileWriter_VertexDataWriter.cpp.
References assertion, assertion1, and tarch::plotter::byteSwapForParaviewBinaryFiles().
plotVertex() [2/4]
void tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::plotVertex (int index, const tarch::la::Vector< 3, double > & value) override virtual
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::VertexDataWriter.
Definition at line 166 of file VTKBinaryFileWriter_VertexDataWriter.cpp.
References assertion, assertion1, and tarch::plotter::byteSwapForParaviewBinaryFiles().
plotVertex() [3/4]
void tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::plotVertex (int index, double * values, int numberOfValues) override virtual
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::VertexDataWriter.
Definition at line 228 of file VTKBinaryFileWriter_VertexDataWriter.cpp.
References assertion, assertion1, and tarch::plotter::byteSwapForParaviewBinaryFiles().
plotVertex() [4/4]
void tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::plotVertex (int index, double value) override virtual
Write data for one cell.
Parameters
index Index of the vertex. This index has to equal the index used for the cell within the VTKWriter class interface.
value Value for the cell.
Implements tarch::plotter::griddata::unstructured::UnstructuredGridWriter::VertexDataWriter.
Definition at line 75 of file VTKBinaryFileWriter_VertexDataWriter.cpp.
References assertion, assertion3, and tarch::plotter::byteSwapForParaviewBinaryFiles().
Friends And Related Symbol Documentation
VTKBinaryFileWriter
friend class VTKBinaryFileWriter friend
The father class is a friend.
There are no other friends.
Definition at line 303 of file VTKBinaryFileWriter.h.
Field Documentation
_identifier
std::string tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::_identifier private
Definition at line 325 of file VTKBinaryFileWriter.h.
Referenced by VertexDataWriter().
_lastWriteCommandVertexNumber
int tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::_lastWriteCommandVertexNumber private
Definition at line 308 of file VTKBinaryFileWriter.h.
_maxValue
double tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::_maxValue private
Definition at line 323 of file VTKBinaryFileWriter.h.
_minValue
double tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::_minValue private
Definition at line 322 of file VTKBinaryFileWriter.h.
_myWriter
VTKBinaryFileWriter& tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::_myWriter private
Underlying VTK writer.
Definition at line 313 of file VTKBinaryFileWriter.h.
Referenced by VertexDataWriter().
_out
std::stringstream tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::_out private
Output stream.
Definition at line 318 of file VTKBinaryFileWriter.h.
Referenced by VertexDataWriter().
_recordsPerVertex
int tarch::plotter::griddata::unstructured::vtk::VTKBinaryFileWriter::VertexDataWriter::_recordsPerVertex private
Definition at line 320 of file VTKBinaryFileWriter.h.
Referenced by VertexDataWriter().
The documentation for this class was generated from the following files:
src/tarch/plotter/griddata/unstructured/vtk/VTKBinaryFileWriter.h
src/tarch/plotter/griddata/unstructured/vtk/VTKBinaryFileWriter_VertexDataWriter.cpp