Peano
examples::exahype2::mgccz4 Namespace Reference
Data Structures
class ADERDGMGCCZ4
class FiniteVolumeMGCCZ4
Functions
void gaugeWave (double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &x, double t)
void linearWave (double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &X, double t)
void forcedflat (double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > &X, double t)
void ncp (double *BgradQ, const double *const Q, const double *const gradQSerialised, const int normal, const int MGCCZ4LapseType, const double MGCCZ4ds, const double MGCCZ4c, const double MGCCZ4e, const double MGCCZ4f, const double MGCCZ4bs, const double MGCCZ4sk, const double MGCCZ4xi, const double MGCCZ4mu)
void source (double *S, const double *const Q, const int MGCCZ4LapseType, const double MGCCZ4ds, const double MGCCZ4c, const double MGCCZ4e, const double MGCCZ4f, const double MGCCZ4bs, const double MGCCZ4sk, const double MGCCZ4xi, const double MGCCZ4itau, const double MGCCZ4eta, const double MGCCZ4k1, const double MGCCZ4k2, const double MGCCZ4k3)
void admconstraints (double *constraints, const double *const Q, const double *const gradQSerialised)
void enforceMGCCZ4constraints (double *luh)
Function Documentation
admconstraints()
void examples::exahype2::mgccz4::admconstraints (double * constraints, const double *const Q, const double *const gradQSerialised)
Definition at line 972 of file MGCCZ4Kernels.cpp.
References m, and u.
enforceMGCCZ4constraints()
void examples::exahype2::mgccz4::enforceMGCCZ4constraints (double * luh)
Definition at line 16 of file MGCCZ4Kernels.cpp.
Referenced by examples::exahype2::mgccz4::FiniteVolumeMGCCZ4::adjustSolution(), and examples::exahype2::mgccz4::ADERDGMGCCZ4::adjustSolution().
forcedflat()
void examples::exahype2::mgccz4::forcedflat (double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & X, double t)
< Amplitude of the wave
Definition at line 81 of file InitialValues.cpp.
Referenced by examples::exahype2::mgccz4::FiniteVolumeMGCCZ4::adjustSolution().
gaugeWave()
void examples::exahype2::mgccz4::gaugeWave (double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & x, double t)
* This file is automatically created by Peano. I need it to interact with
* the Python API, i.e. to read out data set there.
< Amplitude of the wave
Definition at line 19 of file InitialValues.cpp.
Referenced by examples::exahype2::mgccz4::FiniteVolumeMGCCZ4::adjustSolution(), and examples::exahype2::mgccz4::ADERDGMGCCZ4::adjustSolution().
linearWave()
void examples::exahype2::mgccz4::linearWave (double *__restrict__ Q, const tarch::la::Vector< Dimensions, double > & X, double t)
< Amplitude of the wave, should be very small to keep linearized.
Definition at line 55 of file InitialValues.cpp.
References X.
Referenced by examples::exahype2::mgccz4::FiniteVolumeMGCCZ4::adjustSolution(), and examples::exahype2::mgccz4::ADERDGMGCCZ4::adjustSolution().
ncp()
void examples::exahype2::mgccz4::ncp (double * BgradQ, const double *const Q, const double *const gradQSerialised, const int normal, const int MGCCZ4LapseType, const double MGCCZ4ds, const double MGCCZ4c, const double MGCCZ4e, const double MGCCZ4f, const double MGCCZ4bs, const double MGCCZ4sk, const double MGCCZ4xi, const double MGCCZ4mu)
Now assemble all this terrible stuff...
Main variables of the MGCCZ4 system
Definition at line 504 of file MGCCZ4Kernels.cpp.
References beta, m, temp, u, and Z.
Referenced by examples::exahype2::mgccz4::ADERDGMGCCZ4::nonconservativeProduct().
source()
void examples::exahype2::mgccz4::source (double * S, const double *const Q, const int MGCCZ4LapseType, const double MGCCZ4ds, const double MGCCZ4c, const double MGCCZ4e, const double MGCCZ4f, const double MGCCZ4bs, const double MGCCZ4sk, const double MGCCZ4xi, const double MGCCZ4itau, const double MGCCZ4eta, const double MGCCZ4k1, const double MGCCZ4k2, const double MGCCZ4k3)
Main variables of the MGCCZ4 system
Definition at line 112 of file MGCCZ4Kernels.cpp.
References beta, m, temp, u, and Z.
Referenced by examples::exahype2::mgccz4::ADERDGMGCCZ4::algebraicSource().