Peano
TP::std_cerr_logger Struct Reference
Default stdout logger, using iostream.
#include <TP_Logging.h>
Public Member Functions
void print (const std::string &msg)
void log (const std::string &msg) override
void error (const std::string &msg) override
void info (const std::string &msg) override
void warn (const std::string &msg) override
Detailed Description
Default stdout logger, using iostream.
You might want to take this as a basis for coupling to your own logging system.
Definition at line 31 of file TP_Logging.h.
Member Function Documentation
error()
void TP::std_cerr_logger::error (const std::string & msg) override virtual
Implements TP::logger.
Definition at line 35 of file TP_Logging.h.
References print().
info()
void TP::std_cerr_logger::info (const std::string & msg) override virtual
Implements TP::logger.
Definition at line 36 of file TP_Logging.h.
References print().
log()
void TP::std_cerr_logger::log (const std::string & msg) override virtual
Implements TP::logger.
Definition at line 34 of file TP_Logging.h.
References print().
print()
void TP::std_cerr_logger::print (const std::string & msg)
Definition at line 32 of file TP_Logging.h.
Referenced by error(), info(), log(), and warn().
warn()
void TP::std_cerr_logger::warn (const std::string & msg) override virtual
Implements TP::logger.
Definition at line 37 of file TP_Logging.h.
References print().
The documentation for this struct was generated from the following file:
applications/exahype2/ccz4/libtwopunctures/TP_Logging.h