Peano
peano4::grid::GridControlEvent Struct Reference
#include <GridControlEvent.h>
Public Types
enum class RefinementControl : int { Refine = 0 , Erase = 1 }
enum ObjectConstruction { NoData }
Public Member Functions
GridControlEvent ()=default
GridControlEvent (const RefinementControl __refinementControl, const tarch::la::Vector< Dimensions, double > &__offset, const tarch::la::Vector< Dimensions, double > &__width, const tarch::la::Vector< Dimensions, double > &__h)
GridControlEvent (const GridControlEvent &copy)=default
peano4::grid::GridControlEvent::RefinementControl getRefinementControl () const
void setRefinementControl (RefinementControl value)
tarch::la::Vector< Dimensions, double > getOffset () const
void setOffset (const tarch::la::Vector< Dimensions, double > &value)
double getOffset (int index) const
void setOffset (int index, double value)
tarch::la::Vector< Dimensions, double > getWidth () const
void setWidth (const tarch::la::Vector< Dimensions, double > &value)
double getWidth (int index) const
void setWidth (int index, double value)
tarch::la::Vector< Dimensions, double > getH () const
void setH (const tarch::la::Vector< Dimensions, double > &value)
double getH (int index) const
void setH (int index, double value)
int getSenderRank () const
GridControlEvent (ObjectConstruction)
std::string toString () const
Static Public Member Functions
static MPI_Datatype getForkDatatype ()
Hands out MPI datatype if we work without the LLVM MPI extension.
static MPI_Datatype getJoinDatatype ()
static MPI_Datatype getBoundaryExchangeDatatype ()
static MPI_Datatype getMultiscaleDataExchangeDatatype ()
static MPI_Datatype getGlobalCommunciationDatatype ()
static void freeForkDatatype ()
static void freeJoinDatatype ()
static void freeBoundaryExchangeDatatype ()
static void freeMultiscaleDataExchangeDatatype ()
static void freeGlobalCommunciationDatatype ()
static void initDatatype ()
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
static void shutdownDatatype ()
Free the underlying MPI datatype.
static void send (const peano4::grid::GridControlEvent &buffer, int destination, int tag, MPI_Comm communicator)
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
static void receive (peano4::grid::GridControlEvent &buffer, int source, int tag, MPI_Comm communicator)
static void send (const peano4::grid::GridControlEvent &buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
static void receive (peano4::grid::GridControlEvent &buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator)
static void sendAndPollDanglingMessages (const peano4::grid::GridControlEvent &message, int destination, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
static void receiveAndPollDanglingMessages (peano4::grid::GridControlEvent &message, int source, int tag, MPI_Comm communicator=tarch::mpi::Rank::getInstance().getCommunicator())
Private Attributes
RefinementControl _refinementControl
tarch::la::Vector< Dimensions, double > _offset
tarch::la::Vector< Dimensions, double > _width
tarch::la::Vector< Dimensions, double > _h
int _senderDestinationRank
Static Private Attributes
static MPI_Datatype Datatype = MPI_DATATYPE_NULL
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
Detailed Description
Definition at line 25 of file GridControlEvent.h.
Member Enumeration Documentation
ObjectConstruction
enum peano4::grid::GridControlEvent::ObjectConstruction
Enumerator
NoData
Definition at line 126 of file GridControlEvent.h.
RefinementControl
enum class peano4::grid::GridControlEvent::RefinementControl : int strong
Enumerator
Refine
Erase
Definition at line 27 of file GridControlEvent.h.
Constructor & Destructor Documentation
GridControlEvent() [1/4]
peano4::grid::GridControlEvent::GridControlEvent () default
GridControlEvent() [2/4]
peano4::grid::GridControlEvent::GridControlEvent (const RefinementControl __refinementControl, const tarch::la::Vector< Dimensions, double > & __offset, const tarch::la::Vector< Dimensions, double > & __width, const tarch::la::Vector< Dimensions, double > & __h)
Definition at line 8 of file GridControlEvent.cpp.
References setH(), setOffset(), setRefinementControl(), and setWidth().
GridControlEvent() [3/4]
peano4::grid::GridControlEvent::GridControlEvent (const GridControlEvent & copy) default
GridControlEvent() [4/4]
peano4::grid::GridControlEvent::GridControlEvent (ObjectConstruction)
Definition at line 128 of file GridControlEvent.h.
Member Function Documentation
freeBoundaryExchangeDatatype()
void peano4::grid::GridControlEvent::freeBoundaryExchangeDatatype () static
Definition at line 68 of file GridControlEvent.cpp.
freeForkDatatype()
void peano4::grid::GridControlEvent::freeForkDatatype () static
Definition at line 47 of file GridControlEvent.cpp.
freeGlobalCommunciationDatatype()
void peano4::grid::GridControlEvent::freeGlobalCommunciationDatatype () static
Definition at line 54 of file GridControlEvent.cpp.
freeJoinDatatype()
void peano4::grid::GridControlEvent::freeJoinDatatype () static
Definition at line 61 of file GridControlEvent.cpp.
freeMultiscaleDataExchangeDatatype()
void peano4::grid::GridControlEvent::freeMultiscaleDataExchangeDatatype () static
Definition at line 75 of file GridControlEvent.cpp.
getBoundaryExchangeDatatype()
MPI_Datatype peano4::grid::GridControlEvent::getBoundaryExchangeDatatype () static
Definition at line 44 of file GridControlEvent.cpp.
getForkDatatype()
MPI_Datatype peano4::grid::GridControlEvent::getForkDatatype () static
Hands out MPI datatype if we work without the LLVM MPI extension.
If we work with this additional feature, this is the routine where the lazy initialisation is done and the datatype is also cached.
Definition at line 41 of file GridControlEvent.cpp.
getGlobalCommunciationDatatype()
MPI_Datatype peano4::grid::GridControlEvent::getGlobalCommunciationDatatype () static
Definition at line 42 of file GridControlEvent.cpp.
Referenced by exahype2::RefinementControlService::receiveDanglingMessages(), and exahype2::RefinementControlService::triggerSendOfCopyOfCommittedEvents().
getH() [1/2]
tarch::la::Vector< Dimensions, double > peano4::grid::GridControlEvent::getH () const
Definition at line 51 of file GridControlEvent.h.
References _h.
Referenced by exahype2::RefinementControl::addCommand(), peano4::grid::internal::equals(), peano4::grid::internal::refinementEventOverrulesCoarsening(), peano4::grid::internal::sort(), and peano4::grid::internal::twoEventsAreAdjacent().
getH() [2/2]
double peano4::grid::GridControlEvent::getH (int index) const
Definition at line 53 of file GridControlEvent.h.
References _h.
getJoinDatatype()
MPI_Datatype peano4::grid::GridControlEvent::getJoinDatatype () static
Definition at line 43 of file GridControlEvent.cpp.
getMultiscaleDataExchangeDatatype()
MPI_Datatype peano4::grid::GridControlEvent::getMultiscaleDataExchangeDatatype () static
Definition at line 45 of file GridControlEvent.cpp.
getOffset() [1/2]
tarch::la::Vector< Dimensions, double > peano4::grid::GridControlEvent::getOffset () const
Definition at line 41 of file GridControlEvent.h.
References _offset.
Referenced by peano4::grid::internal::createBoundingBoxEvent(), peano4::grid::internal::equals(), peano4::grid::isContained(), peano4::grid::overlaps(), peano4::grid::overlaps(), peano4::grid::internal::sort(), peano4::grid::internal::twoEventsAreAdjacent(), and peano4::grid::internal::twoEventsOverlap().
getOffset() [2/2]
double peano4::grid::GridControlEvent::getOffset (int index) const
Definition at line 43 of file GridControlEvent.h.
References _offset.
getRefinementControl()
peano4::grid::GridControlEvent::RefinementControl peano4::grid::GridControlEvent::getRefinementControl () const
Definition at line 38 of file GridControlEvent.h.
References _refinementControl.
Referenced by peano4::grid::internal::equals(), and peano4::grid::internal::refinementEventOverrulesCoarsening().
getSenderRank()
int peano4::grid::GridControlEvent::getSenderRank () const
Returns
The rank of the sender of an object. It only make ssense to call this routine after you've invoked receive with MPI_ANY_SOURCE.
Definition at line 82 of file GridControlEvent.cpp.
getWidth() [1/2]
tarch::la::Vector< Dimensions, double > peano4::grid::GridControlEvent::getWidth () const
Definition at line 46 of file GridControlEvent.h.
References _width.
Referenced by exahype2::RefinementControl::addCommand(), peano4::grid::internal::createBoundingBoxEvent(), peano4::grid::internal::equals(), peano4::grid::isContained(), peano4::grid::overlaps(), peano4::grid::overlaps(), peano4::grid::internal::twoEventsAreAdjacent(), and peano4::grid::internal::twoEventsOverlap().
getWidth() [2/2]
double peano4::grid::GridControlEvent::getWidth (int index) const
Definition at line 48 of file GridControlEvent.h.
References _width.
initDatatype()
void peano4::grid::GridControlEvent::initDatatype () static
Wrapper around getDatatype() to trigger lazy evaluation if we use the lazy initialisation.
Definition at line 84 of file GridControlEvent.cpp.
Referenced by peano4::parallel::Node::initMPIDatatypes().
receive() [1/2]
void peano4::grid::GridControlEvent::receive (peano4::grid::GridControlEvent & buffer, int source, int tag, MPI_Comm communicator) static
Definition at line 174 of file GridControlEvent.cpp.
References _senderDestinationRank.
Referenced by receiveAndPollDanglingMessages().
receive() [2/2]
void peano4::grid::GridControlEvent::receive (peano4::grid::GridControlEvent & buffer, int source, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Definition at line 200 of file GridControlEvent.cpp.
References _senderDestinationRank.
receiveAndPollDanglingMessages()
void peano4::grid::GridControlEvent::receiveAndPollDanglingMessages (peano4::grid::GridControlEvent & message, int source, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 248 of file GridControlEvent.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), receive(), tarch::services::ServiceRepository::receiveDanglingMessages(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
send() [1/2]
void peano4::grid::GridControlEvent::send (const peano4::grid::GridControlEvent & buffer, int destination, int tag, MPI_Comm communicator) static
In DaStGen (the first version), I had a non-static version of the send as well as the receive.
However, this did not work with newer C++11 versions, as a member function using this as pointer usually doesn't see the vtable while the init sees the object from outside, i.e. including a vtable. So this routine now is basically an alias for a blocking MPI_Send.
Definition at line 169 of file GridControlEvent.cpp.
Referenced by sendAndPollDanglingMessages().
send() [2/2]
void peano4::grid::GridControlEvent::send (const peano4::grid::GridControlEvent & buffer, int destination, int tag, std::function< void()> startCommunicationFunctor, std::function< void()> waitFunctor, MPI_Comm communicator) static
Alternative to the other send() where I trigger a non-blocking send an then invoke the functor until the corresponding MPI_Test tells me that the message went through.
In systems with heavy MPI usage, this can help to avoid deadlocks.
Definition at line 181 of file GridControlEvent.cpp.
sendAndPollDanglingMessages()
void peano4::grid::GridControlEvent::sendAndPollDanglingMessages (const peano4::grid::GridControlEvent & message, int destination, int tag, MPI_Comm communicator = tarch::mpi::Rank::getInstance().getCommunicator()) static
Definition at line 223 of file GridControlEvent.cpp.
References tarch::mpi::Rank::getInstance(), tarch::services::ServiceRepository::getInstance(), tarch::services::ServiceRepository::receiveDanglingMessages(), send(), tarch::mpi::Rank::setDeadlockTimeOutTimeStamp(), tarch::mpi::Rank::setDeadlockWarningTimeStamp(), tarch::mpi::Rank::triggerDeadlockTimeOut(), and tarch::mpi::Rank::writeTimeOutWarning().
setH() [1/2]
void peano4::grid::GridControlEvent::setH (const tarch::la::Vector< Dimensions, double > & value)
Definition at line 52 of file GridControlEvent.h.
References _h.
Referenced by examples::grid::MyObserver::getGridControlEvents(), examples::regulargridupscaling::MyObserver::getGridControlEvents(), and GridControlEvent().
setH() [2/2]
void peano4::grid::GridControlEvent::setH (int index, double value)
Definition at line 54 of file GridControlEvent.h.
References _h.
setOffset() [1/2]
void peano4::grid::GridControlEvent::setOffset (const tarch::la::Vector< Dimensions, double > & value)
Definition at line 42 of file GridControlEvent.h.
References _offset.
Referenced by examples::grid::MyObserver::getGridControlEvents(), examples::regulargridupscaling::MyObserver::getGridControlEvents(), and GridControlEvent().
setOffset() [2/2]
void peano4::grid::GridControlEvent::setOffset (int index, double value)
Definition at line 44 of file GridControlEvent.h.
References _offset.
setRefinementControl()
void peano4::grid::GridControlEvent::setRefinementControl (RefinementControl value)
Definition at line 39 of file GridControlEvent.h.
References _refinementControl.
Referenced by examples::grid::MyObserver::getGridControlEvents(), examples::regulargridupscaling::MyObserver::getGridControlEvents(), and GridControlEvent().
setWidth() [1/2]
void peano4::grid::GridControlEvent::setWidth (const tarch::la::Vector< Dimensions, double > & value)
Definition at line 47 of file GridControlEvent.h.
References _width.
Referenced by examples::grid::MyObserver::getGridControlEvents(), examples::regulargridupscaling::MyObserver::getGridControlEvents(), and GridControlEvent().
setWidth() [2/2]
void peano4::grid::GridControlEvent::setWidth (int index, double value)
Definition at line 49 of file GridControlEvent.h.
References _width.
shutdownDatatype()
void peano4::grid::GridControlEvent::shutdownDatatype () static
Free the underlying MPI datatype.
Definition at line 156 of file GridControlEvent.cpp.
Referenced by peano4::parallel::Node::shutdownMPIDatatypes().
toString()
std::string peano4::grid::GridControlEvent::toString () const
Definition at line 20 of file GridControlEvent.cpp.
Referenced by exahype2::RefinementControl::addCommand(), and peano4::grid::internal::mergeAdjacentRefinementEvents().
Field Documentation
_h
tarch::la::Vector<Dimensions, double> peano4::grid::GridControlEvent::_h private
Definition at line 152 of file GridControlEvent.h.
Referenced by getH(), getH(), setH(), and setH().
_offset
tarch::la::Vector<Dimensions, double> peano4::grid::GridControlEvent::_offset private
Definition at line 150 of file GridControlEvent.h.
Referenced by getOffset(), getOffset(), scenarios.scenario.Scenario::set_global_simulation_parameters(), setOffset(), and setOffset().
_refinementControl
RefinementControl peano4::grid::GridControlEvent::_refinementControl private
Definition at line 149 of file GridControlEvent.h.
Referenced by getRefinementControl(), and setRefinementControl().
_senderDestinationRank
int peano4::grid::GridControlEvent::_senderDestinationRank private
Definition at line 156 of file GridControlEvent.h.
Referenced by receive(), and receive().
_width
tarch::la::Vector<Dimensions, double> peano4::grid::GridControlEvent::_width private
Definition at line 151 of file GridControlEvent.h.
Referenced by getWidth(), getWidth(), setWidth(), and setWidth().
Datatype
MPI_Datatype peano4::grid::GridControlEvent::Datatype = MPI_DATATYPE_NULL static private
Whenever we use LLVM's MPI extension (DaStGe), we rely on lazy initialisation of the datatype.
However, Peano calls init explicitly in most cases. Without the LLVM extension which caches the MPI datatype once constructed, this field stores the type.
Definition at line 165 of file GridControlEvent.h.
The documentation for this struct was generated from the following files:
src/peano4/grid/GridControlEvent.h
src/peano4/grid/GridControlEvent.cpp