Peano
tarch::accelerator Namespace Reference
Namespaces
namespace tests
Data Structures
class Device
Device.
class MemoryManager
Singleton that manages persistent memory on different accelerators.
Functions
void * allocateRawData (std::size_t sizeInBytes, MemoryLocation location, int device)
void * reallocateRawData (void *data, std::size_t sizeInBytes, MemoryLocation location, int device)
void freeRawData (void *data, MemoryLocation location, int device)
void copyTo (void *target, const void *source, std::size_t sizeInBytes, MemoryLocation location, int device)
void copyFrom (const void *source, void *target, std::size_t sizeInBytes, MemoryLocation location, int device)
Function Documentation
allocateRawData()
void * tarch::accelerator::allocateRawData (std::size_t sizeInBytes, MemoryLocation location, int device)
Definition at line 16 of file accelerator.cpp.
References AlignmentOnHeap, assertion, assertion2, tarch::padSizeToAlignment(), and toString().
Referenced by tarch::accelerator::MemoryManager::allocate(), tarch::allocateMemory(), and reallocateRawData().
copyFrom()
void tarch::accelerator::copyFrom (const void * source, void * target, std::size_t sizeInBytes, MemoryLocation location, int device)
Definition at line 75 of file accelerator.cpp.
References assertion2, logDebug, and toString().
Referenced by tarch::copyFrom().
copyTo()
void tarch::accelerator::copyTo (void * target, const void * source, std::size_t sizeInBytes, MemoryLocation location, int device)
Definition at line 60 of file accelerator.cpp.
References assertion2, logDebug, and toString().
Referenced by tarch::copyTo().
freeRawData()
void tarch::accelerator::freeRawData (void * data, MemoryLocation location, int device)
Definition at line 40 of file accelerator.cpp.
References logDebug.
Referenced by tarch::accelerator::MemoryManager::clearWithoutLock(), and reallocateRawData().
reallocateRawData()
void * tarch::accelerator::reallocateRawData (void * data, std::size_t sizeInBytes, MemoryLocation location, int device)
Definition at line 92 of file accelerator.cpp.
References allocateRawData(), assertion, assertion2, freeRawData(), and toString().
Referenced by tarch::reallocateMemory().