Peano
DynamicMatrix.cpp File Reference
#include "DynamicMatrix.h"
#include <cstring>
#include <iostream>
#include "tarch/accelerator/accelerator.h"
#include "tarch/multicore/multicore.h"
Functions
tarch::la::DynamicMatrix kroneckerProduct (const tarch::la::DynamicMatrix &lhs, const tarch::la::DynamicMatrix &rhs)
Wrapper around static routine, so I don't have to use full-qualified name.
tarch::la::DynamicMatrix operator* (const tarch::la::DynamicMatrix &A, const tarch::la::DynamicMatrix &B)
Function Documentation
kroneckerProduct()
tarch::la::DynamicMatrix kroneckerProduct (const tarch::la::DynamicMatrix & lhs, const tarch::la::DynamicMatrix & rhs)
Wrapper around static routine, so I don't have to use full-qualified name.
Definition at line 13 of file DynamicMatrix.cpp.
operator*()
tarch::la::DynamicMatrix operator* (const tarch::la::DynamicMatrix & A, const tarch::la::DynamicMatrix & B)
Definition at line 569 of file DynamicMatrix.cpp.
References assertionEquals, tarch::la::col(), tarch::la::max(), and tarch::la::row().