Peano
tarch::multicore Namespace Reference
This page describes Peano 4's multithreading namespace.
Namespaces
namespace native
namespace tbb
namespace tests
Data Structures
class BooleanSemaphore
class Core
Core.
class EmptyTask
An empty task.
class Lock
Create a lock around a boolean semaphore region.
class MultiReadSingleWriteLock
Create a lock around a boolean semaphore region.
class MultiReadSingleWriteSemaphore
Read/write Semaphore.
class RecursiveLock
Create a lock around a boolean semaphore region.
class RecursiveSemaphore
Recursive Semaphore.
class Task
Abstract super class for a job.
class TaskComparison
Helper class if you wanna administer tasks with in a queue.
class TaskWithCopyOfFunctor
Frequently used implementation for job with a functor.
class TaskWithoutCopyOfFunctor
Frequently used implementation for job with a functor.
Typedefs
using TaskNumber = int
Functions
int getNumberOfUnmaskedThreads ()
This routine runs through the Unix thread mask and counts how many threads SLURM allows a code to use.
std::string printUnmaskedThreads ()
Creates a string representation of those threads which are available to the processes.
void spawnTask (Task *task, const void *const inDependency=nullptr, const void *const outDependency=nullptr)
Spawns a single task in a non-blocking fashion.
void spawnTasks (const std::vector< Task * > &tasks)
void waitForTask (const void *const inDependency)
void waitForAllTasks ()
Variables
constexpr TaskNumber NoOutDependencies = -1
const auto NoInDependencies = std::set<TaskNumber>()
Detailed Description
This page describes Peano 4's multithreading namespace.
A more high-level overview is provided through Multicore programming.
Writing your own code with multithreading features
If you wanna distinguish in your code between multicore and no-multicore variants, please use
#include "tarch/multicore/multicore.h"
and
#if defined(SharedMemoryParallelisation)
With the symbol SharedMemoryParallelisation, you make your code independent of OpenMP, TBB or C++ threading.
Multicore architecture
The multithreading environment is realised through a small set of classes. User codes work with these classes. Each type/function has an implementation within src/multicore. This implementation is a dummy that ensures that all code works properly without any multithreading support. Subdirectories hold alternative implementations (backends) which are enabled once the user selects a certain multithreading implementation variant, i.e. depending on the ifdefs set, one of the subdirectories is used. Some implementations introduce further headers, but user code is never supposed to work against functions or classes held within subdirectories.
Statistics
If the Peano statistics are enabled, the tasking back-end will sample several quantities such as "tarch::multicore::bsp-concurrency-level" or "tarch::multicore::spawned-tasks". Depending on the chosen back-end, you might get additional counters on top. Please start to look into tarch/multicore/Tasks.cpp for an overview of the most generic counters.
Tasking model in Peano
Peano models all of its interna as tasks. Each Peano 4 task is a subclass of tarch::multicore::Task. However, these classes might not be mapped 1:1 onto native tasks. In line with other APIs such as OneTBB, we distinguish different task types or task graph types, respectively:
Tasks. The most generic type of tasks is submitted via spawnTask(). Each task can be assigned a unique number and incoming dependencies. The number in return can be used to specify outgoing dependencies.
Fork-join tasks. These are created via tarch::multicore::spawnTasks() which accepts a sequence of tasks. They are all run in parallel but then wait for each other, i.e. we define a tree (sub)task graph. With fork-join calls, we mirror the principles behind bulk-synchronous programming (BSP).
Fusable tasks. A subtype of the normal tasks.
Tasks with dependencies
In Peano, task DAGs are built up along the task workflow. That is, each task that is not used within a fork-join region or is totally free is assigned a unique number when we spawn it.
Whenever we define a task, we can also define its dependencies. This is a sole completion dependency: you tell the task system which task has to be completed before the currently submitted one is allowed to start. A DAG thus can be built up layer by layer. We start with the first task. This task might be immediately executed - we do not care - and then we continue to work our way down through the graph adding node by node.
In line with OpenMP and TBB - where we significantly influenced the development of the dynamic task API - outgoing dependencies should be declared before we use them.
Typedef Documentation
TaskNumber
using tarch::multicore::TaskNumber = int
Definition at line 110 of file multicore.h.
Function Documentation
getNumberOfUnmaskedThreads()
int tarch::multicore::getNumberOfUnmaskedThreads ()
This routine runs through the Unix thread mask and counts how many threads SLURM allows a code to use.
It returns this count. If you use multiple MPI ranks per node, each rank usually gets the permission to access the same number of cores exclusively.
Definition at line 38 of file Core.cpp.
References u.
printUnmaskedThreads()
std::string tarch::multicore::printUnmaskedThreads ()
Creates a string representation of those threads which are available to the processes.
You get a string similar to
  0000xxxx0000xxxx00000000000000
The example above means that cores 4-7 and 12-15 are available to the process, the other cores are not.
Definition at line 17 of file Core.cpp.
References u.
spawnTask()
void tarch::multicore::spawnTask (Task * task, const void *const inDependency = nullptr, const void *const outDependency = nullptr)
Spawns a single task in a non-blocking fashion.
Ownership goes over to Peano's multicore namespace, i.e. you don't have to delete the pointer.
Handling tasks without outgoing dependencies
If outDependency equals nullptr, we know that no one is (directly) waiting for this task, i.e. we won't add dependencies to the task graph afterwards.
spawnTask() will never commit a task to the global task queue and therefore is inherently thread-safe.
Spawn a task that may depend on other tasks' data.
See also
tarch::multicore and the section "Tasks with dependencies" therein for further documentation.
Parameters
task Pointer to a task. The responsibility for this task is handed over to the tasking system, i.e. you are not allowed to delete it.
inDependency Incoming data dependency that has to finish before the present task is allowed to run. You can pass nullptr to indicate no dependency.
outDependency Outcoming data dependency of the task. You can pass nullptr to indicate no dependency.
Definition at line 21 of file multicore.cpp.
References assertion.
Referenced by tarch::multicore::tests::SpawnTaskTest::testSpawnIndependentTask(), tarch::multicore::tests::SpawnTaskTest::testSpawnTaskWithInAndOutDependency(), and tarch::multicore::tests::SpawnTaskTest::testSpawnTaskWithOutDependency().
spawnTasks()
void tarch::multicore::spawnTasks (const std::vector< Task * > & tasks)
Definition at line 34 of file multicore.cpp.
Referenced by peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithBlockingReceives(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithBlockingSends(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithBlockingSendsAndReceives(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithNonblockingReceives(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithNonblockingSends(), peano4::parallel::tests::PingPongTest::testMultithreadedPingPongWithNonblockingSendsAndReceives(), tarch::multicore::tests::SpawnTaskTest::testSpawnTasks(), and peano4::parallel::SpacetreeSet::traverse().
waitForAllTasks()
void tarch::multicore::waitForAllTasks ()
Definition at line 38 of file multicore.cpp.
Referenced by tarch::multicore::tests::SpawnTaskTest::testSpawnIndependentTask().
waitForTask()
void tarch::multicore::waitForTask (const void *const inDependency)
Definition at line 36 of file multicore.cpp.
Referenced by tarch::multicore::tests::SpawnTaskTest::testSpawnTaskWithInAndOutDependency(), and tarch::multicore::tests::SpawnTaskTest::testSpawnTaskWithOutDependency().
Variable Documentation
NoInDependencies
const auto tarch::multicore::NoInDependencies = std::set<TaskNumber>()
Definition at line 112 of file multicore.h.
NoOutDependencies
constexpr TaskNumber tarch::multicore::NoOutDependencies = -1 constexpr
Definition at line 111 of file multicore.h.
Referenced by swift2::TaskNumber::flatten(), swift2::TaskNumber::TaskNumber(), and swift2::TaskNumber::toString().