Peano
peano4.cpp File Reference
#include "peano4.h"
#include "parallel/Node.h"
#include "parallel/SpacetreeSet.h"
#include "tarch/accelerator/Device.h"
#include "tarch/mpi/BooleanSemaphore.h"
#include "tarch/mpi/Rank.h"
#include "tarch/multicore/Core.h"
#include "tarch/multicore/multicore.h"
#include "tarch/NonCriticalAssertions.h"
#include "tarch/tarch.h"
#include "utils/Globals.h"
#include <fstream>
#include <list>
Functions
void writeCopyrightMessage ()
Function Documentation
writeCopyrightMessage()
void writeCopyrightMessage ()
Definition at line 31 of file peano4.cpp.
References tarch::mpi::Rank::getGlobalMasterRank(), tarch::accelerator::Device::getInstance(), tarch::mpi::Rank::getInstance(), tarch::multicore::Core::getInstance(), and logInfo.
Referenced by peano4::init().