Peano
TP::Utilities Namespace Reference
Functions
int * ivector (long nl, long nh)
double * dvector (long nl, long nh)
int ** imatrix (long nrl, long nrh, long ncl, long nch)
double ** dmatrix (long nrl, long nrh, long ncl, long nch)
double *** d3tensor (long nrl, long nrh, long ncl, long nch, long ndl, long ndh)
void free_ivector (int *v, long nl, long nh)
void free_dvector (double *v, long nl, long nh)
void free_imatrix (int **m, long nrl, long nrh, long ncl, long nch)
void free_dmatrix (double **m, long nrl, long nrh, long ncl, long nch)
void free_d3tensor (double ***t, long nrl, long nrh, long ncl, long nch, long ndl, long ndh)
int minimum2 (int i, int j)
int minimum3 (int i, int j, int k)
int maximum2 (int i, int j)
int maximum3 (int i, int j, int k)
int pow_int (int mantisse, int exponent)
void chebft_Zeros (double u[], int n, int inv)
void chebft_Extremes (double u[], int n, int inv)
void chder (double *c, double *cder, int n)
double chebev (double a, double b, double c[], int m, double x)
void fourft (double *u, int N, int inv)
void fourder (double u[], double du[], int N)
void fourder2 (double u[], double d2u[], int N)
double fourev (double *u, int N, double x)
double norm1 (double *v, int n)
double norm2 (double *v, int n)
double scalarproduct (double *v, double *w, int n)
void nrerror (char error_text[])
Function Documentation
chder()
void TP::Utilities::chder (double * c, double * cder, int n)
Definition at line 342 of file TP_Utilities.cpp.
Referenced by TP::TwoPunctures::Derivatives_AB3().
chebev()
double TP::Utilities::chebev (double a, double b, double c[], int m, double x)
Definition at line 354 of file TP_Utilities.cpp.
References a, and m.
Referenced by TP::TwoPunctures::PunctEvalAtArbitPosition(), and TP::TwoPunctures::PunctEvalAtArbitPositionFast().
chebft_Extremes()
void TP::Utilities::chebft_Extremes (double u[], int n, int inv)
Definition at line 298 of file TP_Utilities.cpp.
References dvector(), free_dvector(), Pi, and u.
chebft_Zeros()
void TP::Utilities::chebft_Zeros (double u[], int n, int inv)
Definition at line 250 of file TP_Utilities.cpp.
References dvector(), free_dvector(), Pi, and u.
Referenced by TP::TwoPunctures::Derivatives_AB3(), TP::TwoPunctures::PunctEvalAtArbitPosition(), and TP::TwoPunctures::SpecCoef().
d3tensor()
double *** TP::Utilities::d3tensor (long nrl, long nrh, long ncl, long nch, long ndl, long ndh)
Definition at line 102 of file TP_Utilities.cpp.
References assert.
Referenced by TP::TwoPunctures::SpecCoef().
dmatrix()
double ** TP::Utilities::dmatrix (long nrl, long nrh, long ncl, long nch)
Definition at line 73 of file TP_Utilities.cpp.
References assert.
Referenced by TP::TwoPunctures::bicgstab(), TP::TwoPunctures::PunctEvalAtArbitPosition(), TP::TwoPunctures::PunctEvalAtArbitPositionFast(), and TP::TwoPunctures::TestRelax().
dvector()
double * TP::Utilities::dvector (long nl, long nh)
Definition at line 30 of file TP_Utilities.cpp.
Referenced by TP::TwoPunctures::allocate_derivs(), TP::TwoPunctures::bicgstab(), chebft_Extremes(), chebft_Zeros(), TP::TwoPunctures::Derivatives_AB3(), TP::TwoPunctures::F_of_v(), fourft(), TP::TwoPunctures::J_times_dv(), TP::TwoPunctures::Newton(), TP::TwoPunctures::PunctEvalAtArbitPosition(), TP::TwoPunctures::PunctEvalAtArbitPositionFast(), TP::TwoPunctures::Run(), TP::TwoPunctures::SetMatrix_JFD(), TP::TwoPunctures::SpecCoef(), and TP::TwoPunctures::TestRelax().
fourder()
void TP::Utilities::fourder (double u[], double du[], int N)
Definition at line 441 of file TP_Utilities.cpp.
References u.
Referenced by TP::TwoPunctures::Derivatives_AB3().
fourder2()
void TP::Utilities::fourder2 (double u[], double d2u[], int N)
Definition at line 458 of file TP_Utilities.cpp.
References u.
Referenced by TP::TwoPunctures::Derivatives_AB3().
fourev()
double TP::Utilities::fourev (double * u, int N, double x)
Definition at line 476 of file TP_Utilities.cpp.
References u.
Referenced by TP::TwoPunctures::PunctEvalAtArbitPosition(), TP::TwoPunctures::PunctEvalAtArbitPositionFast(), TP::TwoPunctures::PunctEvalAtArbitPositionFaster(), and TP::TwoPunctures::PunctEvalAtArbitPositionFasterLowRes().
fourft()
void TP::Utilities::fourft (double * u, int N, int inv)
Definition at line 378 of file TP_Utilities.cpp.
References a, dvector(), free_dvector(), Pi, and u.
Referenced by TP::TwoPunctures::Derivatives_AB3(), TP::TwoPunctures::PunctEvalAtArbitPosition(), and TP::TwoPunctures::SpecCoef().
free_d3tensor()
void TP::Utilities::free_d3tensor (double *** t, long nrl, long nrh, long ncl, long nch, long ndl, long ndh)
Definition at line 183 of file TP_Utilities.cpp.
Referenced by TP::TwoPunctures::SpecCoef().
free_dmatrix()
void TP::Utilities::free_dmatrix (double ** m, long nrl, long nrh, long ncl, long nch)
Definition at line 174 of file TP_Utilities.cpp.
References m.
Referenced by TP::TwoPunctures::bicgstab(), TP::TwoPunctures::PunctEvalAtArbitPosition(), TP::TwoPunctures::PunctEvalAtArbitPositionFast(), and TP::TwoPunctures::TestRelax().
free_dvector()
void TP::Utilities::free_dvector (double * v, long nl, long nh)
Definition at line 157 of file TP_Utilities.cpp.
Referenced by TP::TwoPunctures::bicgstab(), chebft_Extremes(), chebft_Zeros(), TP::TwoPunctures::Derivatives_AB3(), TP::TwoPunctures::F_of_v(), fourft(), TP::TwoPunctures::free_derivs(), TP::TwoPunctures::Interpolate(), TP::TwoPunctures::J_times_dv(), TP::TwoPunctures::Newton(), TP::TwoPunctures::PunctEvalAtArbitPosition(), TP::TwoPunctures::PunctEvalAtArbitPositionFast(), TP::TwoPunctures::SetMatrix_JFD(), TP::TwoPunctures::SpecCoef(), and TP::TwoPunctures::TestRelax().
free_imatrix()
void TP::Utilities::free_imatrix (int ** m, long nrl, long nrh, long ncl, long nch)
Definition at line 165 of file TP_Utilities.cpp.
References m.
Referenced by TP::TwoPunctures::bicgstab(), and TP::TwoPunctures::TestRelax().
free_ivector()
void TP::Utilities::free_ivector (int * v, long nl, long nh)
Definition at line 149 of file TP_Utilities.cpp.
Referenced by TP::TwoPunctures::bicgstab(), TP::TwoPunctures::Derivatives_AB3(), and TP::TwoPunctures::TestRelax().
imatrix()
int ** TP::Utilities::imatrix (long nrl, long nrh, long ncl, long nch)
Definition at line 44 of file TP_Utilities.cpp.
References assert.
Referenced by TP::TwoPunctures::bicgstab(), and TP::TwoPunctures::TestRelax().
ivector()
int * TP::Utilities::ivector (long nl, long nh)
Definition at line 16 of file TP_Utilities.cpp.
Referenced by TP::TwoPunctures::bicgstab(), TP::TwoPunctures::Derivatives_AB3(), and TP::TwoPunctures::TestRelax().
maximum2()
int TP::Utilities::maximum2 (int i, int j)
Definition at line 216 of file TP_Utilities.cpp.
Referenced by TP::TwoPunctures::SetMatrix_JFD().
maximum3()
int TP::Utilities::maximum3 (int i, int j, int k)
Definition at line 226 of file TP_Utilities.cpp.
Referenced by TP::TwoPunctures::Derivatives_AB3(), TP::TwoPunctures::PunctEvalAtArbitPosition(), TP::TwoPunctures::PunctEvalAtArbitPositionFast(), and TP::TwoPunctures::SpecCoef().
minimum2()
int TP::Utilities::minimum2 (int i, int j)
Definition at line 194 of file TP_Utilities.cpp.
Referenced by TP::TwoPunctures::SetMatrix_JFD().
minimum3()
int TP::Utilities::minimum3 (int i, int j, int k)
Definition at line 204 of file TP_Utilities.cpp.
norm1()
double TP::Utilities::norm1 (double * v, int n)
Definition at line 492 of file TP_Utilities.cpp.
Referenced by TP::TwoPunctures::TestRelax().
norm2()
double TP::Utilities::norm2 (double * v, int n)
Definition at line 506 of file TP_Utilities.cpp.
Referenced by TP::TwoPunctures::bicgstab().
nrerror()
void TP::Utilities::nrerror (char error_text[])
pow_int()
int TP::Utilities::pow_int (int mantisse, int exponent)
Definition at line 238 of file TP_Utilities.cpp.
scalarproduct()
double TP::Utilities::scalarproduct (double * v, double * w, int n)
Definition at line 519 of file TP_Utilities.cpp.
References w.
Referenced by TP::TwoPunctures::bicgstab().