var namespacemghype_1_1api_1_1matrixgenerators_1_1blockmatrix_1_1DGPoisson2dPenaltyBlockMatrix =
[
    [ "DGPoisson2dPenaltyBlockMatrix", "d3/de6/classmghype_1_1api_1_1matrixgenerators_1_1blockmatrix_1_1DGPoisson2dPenaltyBlockMatrix_1_1DGPoisson2dPenaltyBlockMatrix.html", "d3/de6/classmghype_1_1api_1_1matrixgenerators_1_1blockmatrix_1_1DGPoisson2dPenaltyBlockMatrix_1_1DGPoisson2dPenaltyBlockMatrix" ]
];