Peano
VtkPolylineBinaryWriter< FileWriter, fp > Class Template Reference
#include <polyline.h>
Public Member Functions
VtkPolylineBinaryWriter (FileWriter *writer)
VtkPolylineBinaryWriter ()=default
void add (fp x, fp y, fp z)
void finish ()
Private Member Functions
void addPolyline ()
Additional Inherited Members
Protected Member Functions inherited from VtkPointBinaryWriter< FileWriter, fp >
VtkPointBinaryWriter (FileWriter *writer)
VtkPointBinaryWriter ()=default
void add (fp x, fp y, fp z)
void addPointDataHeader ()
void addScalarPointDataHeader (const char *name)
void addScalar (fp value)
void finish ()
Protected Member Functions inherited from VtkPointWriterBase< FileWriter >
constexpr int particleCountPosition () const
template<typename T >
T byteswapped (T val)
void updatePointsCount ()
VtkPointWriterBase (FileWriter *writer)
VtkPointWriterBase ()=default
Protected Attributes inherited from VtkPointWriterBase< FileWriter >
FileWriter * writer = nullptr
unsigned long pointCount = 0
Detailed Description
template<typename FileWriter, typename fp = float>
requires IoWriter<FileWriter> and std::is_floating_point_v<fp>
class VtkPolylineBinaryWriter< FileWriter, fp >
Definition at line 43 of file polyline.h.
Constructor & Destructor Documentation
VtkPolylineBinaryWriter() [1/2]
template<typename FileWriter , typename fp = float> VtkPolylineBinaryWriter< FileWriter, fp >::VtkPolylineBinaryWriter (FileWriter * writer) explicit
Definition at line 62 of file polyline.h.
VtkPolylineBinaryWriter() [2/2]
template<typename FileWriter , typename fp = float> VtkPolylineBinaryWriter< FileWriter, fp >::VtkPolylineBinaryWriter () explicit default
Member Function Documentation
add()
template<typename FileWriter , typename fp = float> void VtkPolylineBinaryWriter< FileWriter, fp >::add (fp x, fp y, fp z)
Definition at line 66 of file polyline.h.
References VtkPointBinaryWriter< FileWriter, fp >::add().
addPolyline()
template<typename FileWriter , typename fp = float> void VtkPolylineBinaryWriter< FileWriter, fp >::addPolyline () private
Definition at line 45 of file polyline.h.
References assert, VtkPointWriterBase< FileWriter >::byteswapped(), VtkPointWriterBase< FileWriter >::pointCount, and VtkPointWriterBase< FileWriter >::writer.
Referenced by VtkPolylineBinaryWriter< FileWriter, fp >::finish().
finish()
template<typename FileWriter , typename fp = float> void VtkPolylineBinaryWriter< FileWriter, fp >::finish ()
Definition at line 70 of file polyline.h.
References VtkPolylineBinaryWriter< FileWriter, fp >::addPolyline(), VtkPointWriterBase< FileWriter >::updatePointsCount(), and VtkPointWriterBase< FileWriter >::writer.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/vtk/writer/polyline.h