Peano
ExaSeis::Derivatives< Shortcuts, T, num_nodes, numberOfData > Class Template Reference
#include <CurvilinearDerivatives.h>
Static Public Member Functions
static void metricDerivatives (double dudx[][num_nodes], const T *const coordinates, const double *const dx, T *derivatives)
Static Private Member Functions
static void computeDerivatives_x_3D (double dudx[][num_nodes], int k, int j, int i, const T *values, int coordinate, T &der_x, const double dx)
static void computeDerivatives_y_3D (double dudx[][num_nodes], int k, int j, int i, const T *values, int coordinate, T &der_y, const double dy)
static void computeDerivatives_z_3D (double dudx[][num_nodes], int k, int j, int i, const T *values, int coordinate, T &der_z, const double dz)
Detailed Description
template<class Shortcuts, typename T, int num_nodes, int numberOfData>
class ExaSeis::Derivatives< Shortcuts, T, num_nodes, numberOfData >
Definition at line 7 of file CurvilinearDerivatives.h.
Member Function Documentation
computeDerivatives_x_3D()
template<class Shortcuts , typename T , int num_nodes, int numberOfData> static void ExaSeis::Derivatives< Shortcuts, T, num_nodes, numberOfData >::computeDerivatives_x_3D (double dudx[][num_nodes], int k, int j, int i, const T * values, int coordinate, T & der_x, const double dx) static private
Definition at line 56 of file CurvilinearDerivatives.h.
References dx.
Referenced by ExaSeis::Derivatives< Shortcuts, T, num_nodes, numberOfData >::metricDerivatives().
computeDerivatives_y_3D()
template<class Shortcuts , typename T , int num_nodes, int numberOfData> static void ExaSeis::Derivatives< Shortcuts, T, num_nodes, numberOfData >::computeDerivatives_y_3D (double dudx[][num_nodes], int k, int j, int i, const T * values, int coordinate, T & der_y, const double dy) static private
Definition at line 67 of file CurvilinearDerivatives.h.
Referenced by ExaSeis::Derivatives< Shortcuts, T, num_nodes, numberOfData >::metricDerivatives().
computeDerivatives_z_3D()
template<class Shortcuts , typename T , int num_nodes, int numberOfData> static void ExaSeis::Derivatives< Shortcuts, T, num_nodes, numberOfData >::computeDerivatives_z_3D (double dudx[][num_nodes], int k, int j, int i, const T * values, int coordinate, T & der_z, const double dz) static private
Definition at line 78 of file CurvilinearDerivatives.h.
Referenced by ExaSeis::Derivatives< Shortcuts, T, num_nodes, numberOfData >::metricDerivatives().
metricDerivatives()
template<class Shortcuts , typename T , int num_nodes, int numberOfData> static void ExaSeis::Derivatives< Shortcuts, T, num_nodes, numberOfData >::metricDerivatives (double dudx[][num_nodes], const T *const coordinates, const double *const dx, T * derivatives) static
Definition at line 9 of file CurvilinearDerivatives.h.
References ExaSeis::Derivatives< Shortcuts, T, num_nodes, numberOfData >::computeDerivatives_x_3D(), ExaSeis::Derivatives< Shortcuts, T, num_nodes, numberOfData >::computeDerivatives_y_3D(), ExaSeis::Derivatives< Shortcuts, T, num_nodes, numberOfData >::computeDerivatives_z_3D(), and dx.
Referenced by ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::initUnknownsPatch().
The documentation for this class was generated from the following file:
applications/exahype2/exaseis/ExaSeis_core/Curvilinear/CurvilinearDerivatives.h