Peano
exahype2.tracer.InsertParticlesByCoordinates.InsertParticlesByCoordinates Class Reference
Basically superclass, though we add these numbers.
Public Member Functions
__init__ (self, particle_set, coordinates, additional_includes="")
See superclass.
get_action_set_name (self)
Return unique action set name.
get_constructor_body (self)
Initialise the coordinates.
get_attributes (self)
Return attributes as copied and pasted into the generated class.
Public Member Functions inherited from peano4.toolbox.particles.InsertParticlesByCoordinates.InsertParticlesByCoordinates
get_body_of_operation (self, operation_name)
Return actual C++ code snippets to be inserted into C++ code.
get_body_of_getGridControlEvents (self)
user_should_modify_template (self)
Is the user allowed to modify the output.
get_includes (self)
Return include statements that you need.
get_static_initialisations (self, full_qualified_classname)
Public Member Functions inherited from peano4.solversteps.ActionSet.ActionSet
get_destructor_body (self)
get_body_of_prepareTraversal (self)
get_body_of_unprepareTraversal (self)
Additional Inherited Members
Data Fields inherited from peano4.toolbox.particles.InsertParticlesByCoordinates.InsertParticlesByCoordinates
d
additional_includes
Data Fields inherited from peano4.solversteps.ActionSet.ActionSet
descend_invocation_order
parallel
Static Public Attributes inherited from peano4.solversteps.ActionSet.ActionSet
str OPERATION_BEGIN_TRAVERSAL = "beginTraversal"
str OPERATION_END_TRAVERSAL = "endTraversal"
str OPERATION_CREATE_PERSISTENT_VERTEX = "createPersistentVertex"
str OPERATION_DESTROY_PERSISTENT_VERTEX = "destroyPersistentVertex"
str OPERATION_CREATE_HANGING_VERTEX = "createHangingVertex"
str OPERATION_DESTROY_HANGING_VERTEX = "destroyHangingVertex"
str OPERATION_CREATE_PERSISTENT_FACE = "createPersistentFace"
str OPERATION_DESTROY_PERSISTENT_FACE = "destroyPersistentFace"
str OPERATION_CREATE_HANGING_FACE = "createHangingFace"
str OPERATION_DESTROY_HANGING_FACE = "destroyHangingFace"
str OPERATION_CREATE_CELL = "createCell"
str OPERATION_DESTROY_CELL = "destroyCell"
str OPERATION_TOUCH_VERTEX_FIRST_TIME = "touchVertexFirstTime"
str OPERATION_TOUCH_VERTEX_LAST_TIME = "touchVertexLastTime"
str OPERATION_TOUCH_FACE_FIRST_TIME = "touchFaceFirstTime"
str OPERATION_TOUCH_FACE_LAST_TIME = "touchFaceLastTime"
str OPERATION_TOUCH_CELL_FIRST_TIME = "touchCellFirstTime"
str OPERATION_TOUCH_CELL_LAST_TIME = "touchCellLastTime"
Protected Attributes inherited from peano4.toolbox.particles.InsertParticlesByCoordinates.InsertParticlesByCoordinates
_coordinates
Detailed Description
Basically superclass, though we add these numbers.
Definition at line 12 of file InsertParticlesByCoordinates.py.
Constructor & Destructor Documentation
__init__()
exahype2.tracer.InsertParticlesByCoordinates.InsertParticlesByCoordinates.__init__ (self, particle_set, coordinates, additional_includes = "")
See superclass.
Reimplemented from peano4.toolbox.particles.InsertParticlesByCoordinates.InsertParticlesByCoordinates.
Definition at line 21 of file InsertParticlesByCoordinates.py.
References exahype2.tracer.InsertParticlesByCoordinates.InsertParticlesByCoordinates.__init__().
Referenced by exahype2.tracer.InsertParticlesByCoordinates.InsertParticlesByCoordinates.__init__().
Member Function Documentation
get_action_set_name()
exahype2.tracer.InsertParticlesByCoordinates.InsertParticlesByCoordinates.get_action_set_name (self)
Return unique action set name.
Returns a description (word) for the mapping which is also used as class name for the generated type. As a consequence, the result should be one word (if possible) and uppercase. Also, every subclass should overwrite this routine.
The generator will take the result and construct eventually classes similar to MyStep2Dummy.h and MyStep2Dummy.cpp or similar for the example below, where we return Dummy.
Reimplemented from peano4.toolbox.particles.InsertParticlesByCoordinates.InsertParticlesByCoordinates.
Definition at line 50 of file InsertParticlesByCoordinates.py.
get_attributes()
exahype2.tracer.InsertParticlesByCoordinates.InsertParticlesByCoordinates.get_attributes (self)
Return attributes as copied and pasted into the generated class.
Please note that action sets are not persistent, i.e. there is one object creation per grid sweep per tree.
Reimplemented from peano4.toolbox.particles.InsertParticlesByCoordinates.InsertParticlesByCoordinates.
Definition at line 61 of file InsertParticlesByCoordinates.py.
References exahype2.tracer.InsertParticlesByCoordinates.InsertParticlesByCoordinates.get_attributes().
Referenced by exahype2.tracer.InsertParticlesByCoordinates.InsertParticlesByCoordinates.get_attributes().
get_constructor_body()
exahype2.tracer.InsertParticlesByCoordinates.InsertParticlesByCoordinates.get_constructor_body (self)
Initialise the coordinates.
This routine initialises the coordinates array, but it does so if and only if this hasn't been done yet. Each tree traversal creates its own action set. However, it would be ridiculously stupid to create the coordinates multiple times. Rather, I
Reimplemented from peano4.toolbox.particles.InsertParticlesByCoordinates.InsertParticlesByCoordinates.
Definition at line 53 of file InsertParticlesByCoordinates.py.
References exahype2.tracer.InsertParticlesByCoordinates.InsertParticlesByCoordinates.get_constructor_body().
Referenced by exahype2.tracer.InsertParticlesByCoordinates.InsertParticlesByCoordinates.get_constructor_body().
The documentation for this class was generated from the following file:
python/exahype2/tracer/InsertParticlesByCoordinates.py