Peano
SWIFTMain.SWIFTMain Class Reference
Public Member Functions
__init__ (self, project, initialisation_steps, solver_steps, overwrite=False)
solversteps: [peano4.solversteps.Steps]
Public Member Functions inherited from peano4.runner.DefaultSequence.DefaultSequence
construct_output (self, output, main_name)
Pass in a version of output.
merge (self, main)
Make subproject's data a part of the project (will be extended)
Data Fields
overwrite
Data Fields inherited from peano4.runner.DefaultSequence.DefaultSequence
project
overwrite
d
is_extended
Protected Member Functions
_get_header_file_template (self)
_get_implementation_file_template (self)
Detailed Description
Definition at line 7 of file SWIFTMain.py.
Constructor & Destructor Documentation
__init__()
SWIFTMain.SWIFTMain.__init__ (self, project, initialisation_steps, solver_steps, overwrite = False)
solversteps: [peano4.solversteps.Steps]
overwrite: Boolean Shall I keep an existing main, or shall I overwrite it. You can reset this behaviour after you've created the main object.
Reimplemented from peano4.runner.DefaultSequence.DefaultSequence.
Definition at line 8 of file SWIFTMain.py.
References SWIFTMain.SWIFTMain.__init__().
Referenced by SWIFTMain.SWIFTMain.__init__().
Member Function Documentation
_get_header_file_template()
SWIFTMain.SWIFTMain._get_header_file_template (self) protected
Reimplemented from peano4.runner.DefaultSequence.DefaultSequence.
Definition at line 24 of file SWIFTMain.py.
Referenced by peano4.runner.DefaultSequence.DefaultSequence.construct_output().
_get_implementation_file_template()
SWIFTMain.SWIFTMain._get_implementation_file_template (self) protected
Reimplemented from peano4.runner.DefaultSequence.DefaultSequence.
Definition at line 28 of file SWIFTMain.py.
Referenced by peano4.runner.DefaultSequence.DefaultSequence.construct_output().
Field Documentation
overwrite
SWIFTMain.SWIFTMain.overwrite
Definition at line 19 of file SWIFTMain.py.
Referenced by peano4.runner.DefaultSequence.DefaultSequence.construct_output().
The documentation for this class was generated from the following file:
python/swift2/output/SWIFTMain.py