Peano
coordinate.cpp File Reference
#include "coordinate.h"
Functions
std::string coordToString (Coordinate c)
std::string coordToLowercaseString (Coordinate c)
Coordinate stringToCoord (std::string s)
Coordinate getNormal (Coordinate c1, Coordinate c2)
void getPlane (Coordinate c1, Coordinate &c2, Coordinate &c3)
Function Documentation
coordToLowercaseString()
std::string coordToLowercaseString (Coordinate c)
Definition at line 17 of file coordinate.cpp.
References X, Y, and Z.
Referenced by InnerNode::InnerNode(), and Root::Root().
coordToString()
std::string coordToString (Coordinate c)
Definition at line 5 of file coordinate.cpp.
References X, Y, and Z.
Referenced by FaceBoundary::FaceBoundary(), Edge::printEdge(), FaceBoundary::split(), Edge::split(), BlockBoundary::split(), Face::split(), stringToCoord(), Face::subface(), BlockBoundary::toNetCDF(), Block::toString(), InnerNode::toString(), Root::toString(), and BlockBoundary::toString().
getNormal()
Coordinate getNormal (Coordinate c1, Coordinate c2)
Definition at line 41 of file coordinate.cpp.
Referenced by BlockBoundary::BlockBoundary(), BlockBoundary::checkConformity(), Face::Face(), FaceBoundary::FaceBoundary(), FaceBoundary::FaceBoundary(), InnerNode::getFaceNormal(), InnerNode::init(), Root::init(), InnerNode::InnerNode(), Root::Root(), BlockBoundary::setupSplittingFace(), BlockBoundary::split(), Face::split(), InnerNode::traverse(), and InnerNode::traverseProjection().
getPlane()
void getPlane (Coordinate c1, Coordinate & c2, Coordinate & c3)
Definition at line 45 of file coordinate.cpp.
Referenced by Curvi::Interface::invertProjection().
stringToCoord()
Coordinate stringToCoord (std::string s)
Definition at line 29 of file coordinate.cpp.
References coordToString(), X, Y, and Z.
Referenced by InnerNode::InnerNode(), and Root::Root().