Peano
exahype2::fd::fd4::omp::internal Namespace Reference
Functions
template<typename Solver , int numberOfGridCellsPerPatchPerAxis, int haloSize, int unknowns, int auxiliaryVariables, typename TempDataEnumerator >
static void timeStep_batched_heap_multicore_static_calls (::exahype2::CellData< double, double > &patchData, double KOSigma, bool evaluateFlux, bool evaluateDifferentialSource, bool evaluateAlgebraicSource, bool copyOldTimeStepAndScaleWithTimeStepSize, DifferentialSourceTermVariant variant, const exahype2::enumerator::AoSLexicographicEnumerator &QInEnumerator, const exahype2::enumerator::AoSLexicographicEnumerator &QOutEnumerator, const TempDataEnumerator &fluxEnumerator, const TempDataEnumerator &differentialSourceEnumerator, const TempDataEnumerator &KODissipationEnumerator, double *tempFluxX, double *tempFluxY, double *tempFluxZ, double *tempDifferentialSourceX, double *tempDifferentialSourceY, double *tempDifferentialSourceZ, double *tempKODissipationX, double *tempKODissipationY, double *tempKODissipationZ)
Function Documentation
timeStep_batched_heap_multicore_static_calls()
template<typename Solver , int numberOfGridCellsPerPatchPerAxis, int haloSize, int unknowns, int auxiliaryVariables, typename TempDataEnumerator > static void exahype2::fd::fd4::omp::internal::timeStep_batched_heap_multicore_static_calls (::exahype2::CellData< double, double > & patchData, double KOSigma, bool evaluateFlux, bool evaluateDifferentialSource, bool evaluateAlgebraicSource, bool copyOldTimeStepAndScaleWithTimeStepSize, DifferentialSourceTermVariant variant, const exahype2::enumerator::AoSLexicographicEnumerator & QInEnumerator, const exahype2::enumerator::AoSLexicographicEnumerator & QOutEnumerator, const TempDataEnumerator & fluxEnumerator, const TempDataEnumerator & differentialSourceEnumerator, const TempDataEnumerator & KODissipationEnumerator, double * tempFluxX, double * tempFluxY, double * tempFluxZ, double * tempDifferentialSourceX, double * tempDifferentialSourceY, double * tempDifferentialSourceZ, double * tempKODissipationX, double * tempKODissipationY, double * tempKODissipationZ) static
Definition at line 22 of file FD4_batched_static_calls.cpph.
References exahype2::CellData< inType, outType, NumFaceTypes >::cellCentre, exahype2::CellData< inType, outType, NumFaceTypes >::cellSize, exahype2::fd::internal::clearSolution_LoopBody(), exahype2::fd::fd4::internal::computeKreissOligerDissipationTerm_LoopBody(), exahype2::fd::internal::copySolution_LoopBody(), exahype2::CellData< inType, outType, NumFaceTypes >::dt, exahype2::CellData< inType, outType, NumFaceTypes >::numberOfCells, exahype2::CellData< inType, outType, NumFaceTypes >::QIn, exahype2::CellData< inType, outType, NumFaceTypes >::QOut, exahype2::CellData< inType, outType, NumFaceTypes >::t, timeStepSize, exahype2::fd::fd4::internal::updateSolutionWithDifferentialSourceTerm_LoopBody(), exahype2::fd::fd4::internal::updateSolutionWithFlux_LoopBody(), and exahype2::fd::fd4::internal::updateSolutionWithKODissipationTerm_LoopBody().