Peano
toolbox::particles::assignmentchecks::tests::TestParticle Class Reference
#include <TestParticle.h>
Public Types
enum class ParallelState : int { Local = 0 , Virtual = 1 }
Public Member Functions
TestParticle (const tarch::la::Vector< Dimensions, double > &x, int particleID, bool local=false)
int getDepth () const
int getPartid () const
tarch::la::Vector< Dimensions, double > getVertexH () const
tarch::la::Vector< Dimensions, double > getX () const
bool isLocal () const
TestParticle::ParallelState getParallelState () const
void setDepth (const int depth)
void setPartid (const int partid)
void setIsLocal (const bool isLocal)
void setVertexH (const tarch::la::Vector< Dimensions, double > &x)
void setX (const tarch::la::Vector< Dimensions, double > &x)
void setParallelState (const TestParticle::ParallelState parallelState)
Private Attributes
tarch::la::Vector< Dimensions, double > _x
int _partid
bool _isLocal
tarch::la::Vector< Dimensions, double > _vertexH
int _depth
Detailed Description
Definition at line 17 of file TestParticle.h.
Member Enumeration Documentation
ParallelState
enum class toolbox::particles::assignmentchecks::tests::TestParticle::ParallelState : int strong
Enumerator
Local
Virtual
Definition at line 29 of file TestParticle.h.
Constructor & Destructor Documentation
TestParticle()
toolbox::particles::assignmentchecks::tests::TestParticle::TestParticle (const tarch::la::Vector< Dimensions, double > & x, int particleID, bool local = false)
Definition at line 6 of file TestParticle.cpp.
Member Function Documentation
getDepth()
int toolbox::particles::assignmentchecks::tests::TestParticle::getDepth () const
Definition at line 16 of file TestParticle.cpp.
Referenced by toolbox::particles::assignmentchecks::tests::internal::mirrorParticleAlongPeriodicBoundary().
getParallelState()
toolbox::particles::assignmentchecks::tests::TestParticle::ParallelState toolbox::particles::assignmentchecks::tests::TestParticle::getParallelState () const
Definition at line 41 of file TestParticle.cpp.
References Local, and Virtual.
getPartid()
int toolbox::particles::assignmentchecks::tests::TestParticle::getPartid () const
Definition at line 21 of file TestParticle.cpp.
Referenced by toolbox::particles::assignmentchecks::tests::internal::mirrorParticleAlongPeriodicBoundary(), and toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditions().
getVertexH()
tarch::la::Vector< Dimensions, double > toolbox::particles::assignmentchecks::tests::TestParticle::getVertexH () const
Definition at line 26 of file TestParticle.cpp.
Referenced by toolbox::particles::assignmentchecks::tests::internal::mirrorParticleAlongPeriodicBoundary(), and toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditions().
getX()
tarch::la::Vector< Dimensions, double > toolbox::particles::assignmentchecks::tests::TestParticle::getX () const
Definition at line 31 of file TestParticle.cpp.
Referenced by toolbox::particles::assignmentchecks::tests::internal::mirrorParticleAlongPeriodicBoundary(), and toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditions().
isLocal()
bool toolbox::particles::assignmentchecks::tests::TestParticle::isLocal () const
Definition at line 36 of file TestParticle.cpp.
setDepth()
void toolbox::particles::assignmentchecks::tests::TestParticle::setDepth (const int depth)
Definition at line 52 of file TestParticle.cpp.
Referenced by toolbox::particles::assignmentchecks::tests::internal::mirrorParticleAlongPeriodicBoundary(), and toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditions().
setIsLocal()
void toolbox::particles::assignmentchecks::tests::TestParticle::setIsLocal (const bool isLocal)
Definition at line 64 of file TestParticle.cpp.
setParallelState()
void toolbox::particles::assignmentchecks::tests::TestParticle::setParallelState (const TestParticle::ParallelState parallelState)
Definition at line 83 of file TestParticle.cpp.
References Local.
setPartid()
void toolbox::particles::assignmentchecks::tests::TestParticle::setPartid (const int partid)
Definition at line 58 of file TestParticle.cpp.
setVertexH()
void toolbox::particles::assignmentchecks::tests::TestParticle::setVertexH (const tarch::la::Vector< Dimensions, double > & x)
Definition at line 71 of file TestParticle.cpp.
Referenced by toolbox::particles::assignmentchecks::tests::internal::mirrorParticleAlongPeriodicBoundary(), and toolbox::particles::assignmentchecks::tests::TestHelpers::testPeriodicBoundaryConditions().
setX()
void toolbox::particles::assignmentchecks::tests::TestParticle::setX (const tarch::la::Vector< Dimensions, double > & x)
Definition at line 77 of file TestParticle.cpp.
Field Documentation
_depth
int toolbox::particles::assignmentchecks::tests::TestParticle::_depth private
Definition at line 25 of file TestParticle.h.
_isLocal
bool toolbox::particles::assignmentchecks::tests::TestParticle::_isLocal private
Definition at line 21 of file TestParticle.h.
_partid
int toolbox::particles::assignmentchecks::tests::TestParticle::_partid private
Definition at line 20 of file TestParticle.h.
_vertexH
tarch::la::Vector<Dimensions, double> toolbox::particles::assignmentchecks::tests::TestParticle::_vertexH private
Definition at line 24 of file TestParticle.h.
_x
tarch::la::Vector<Dimensions, double> toolbox::particles::assignmentchecks::tests::TestParticle::_x private
Definition at line 19 of file TestParticle.h.
The documentation for this class was generated from the following files:
src/toolbox/particles/assignmentchecks/tests/TestParticle.h
src/toolbox/particles/assignmentchecks/tests/TestParticle.cpp