var CellCenteredFiniteDifferences_8py =
[
    [ "exahype2.solvers.rkfd.CellCenteredFiniteDifferences.CellCenteredFiniteDifferences", "d5/db2/classexahype2_1_1solvers_1_1rkfd_1_1CellCenteredFiniteDifferences_1_1CellCenteredFiniteDifferences.html", "d5/db2/classexahype2_1_1solvers_1_1rkfd_1_1CellCenteredFiniteDifferences_1_1CellCenteredFiniteDifferences" ]
];