Peano
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter Class Reference
Plot Peano's mesh data in Peano's text file format.
#include <PeanoTextPatchFileWriter.h>
Data Structures
class CellDataWriter
class VertexDataWriter
Public Types
enum class IndexFileMode { CreateNew , AppendNewData , NoIndexFile }
Public Member Functions
PeanoTextPatchFileWriter (int dimension, const std::string &fileName, const std::string &indexFileName, IndexFileMode appendToIndexFile, double timeStamp)
Create a new Peano text file output.
virtual ~PeanoTextPatchFileWriter ()
Destructor.
virtual CellDataWriter * createCellDataWriter (const std::string &identifier, int unknownsPerAxis, int recordsPerCell, const std::string &description) override
Caller has to destroy this instance manually.
virtual CellDataWriter * createCellDataWriter (const std::string &identifier, int unknownsPerAxis, int recordsPerCell, const std::string &description, const std::string &metaData) override
Create cell data writer.
virtual CellDataWriter * createCellDataWriter (const std::string &identifier, int unknownsPerAxis, int recordsPerCell, const std::string &description, const std::string &metaData, double *mapping) override
Create writer.
virtual VertexDataWriter * createVertexDataWriter (const std::string &identifier, int unknownsPerAxis, int recordsPerVertex, const std::string &description) override
Caller has to destroy this instance manually.
virtual VertexDataWriter * createVertexDataWriter (const std::string &identifier, int unknownsPerAxis, int recordsPerVertex, const std::string &description, const std::string &metaData) override
Create vertex data writer.
virtual VertexDataWriter * createVertexDataWriter (const std::string &identifier, int unknownsPerAxis, int recordsPerVertex, const std::string &description, const std::string &metaData, double *mapping) override
Create writer.
virtual int plotPatch (const tarch::la::Vector< 2, double > &offset, const tarch::la::Vector< 2, double > &size) override
virtual int plotPatch (const tarch::la::Vector< 3, double > &offset, const tarch::la::Vector< 3, double > &size) override
virtual bool writeToFile () override
virtual bool isOpen () override
virtual void clear () override
Clear local data.
Public Member Functions inherited from tarch::plotter::griddata::blockstructured::PatchWriter
virtual ~PatchWriter ()=default
Protected Member Functions
void writeMetaData (const std::string &metaData)
void writeMapping (int totalEntries, double *values)
void createBackupOfMetaFile ()
void createEmptyIndexFile ()
void addNewDatasetToIndexFile (double timestamp)
void addNewFileToCurrentDataSetInIndexFile (const std::string &filename)
double getLatestTimeStepInIndexFile () const
Find latest time step in index file.
Protected Attributes
std::string _fileName
std::string _indexFile
bool _writtenToFile
int _dimensions
int _patchCounter
std::stringstream _snapshotFileOut
bool _haveWrittenAtLeastOnePatch
Static Protected Attributes
static tarch::logging::Log _log
static const std::string HEADER
Detailed Description
Plot Peano's mesh data in Peano's text file format.
Consult the general plotting remarks on rationale and patterns behind the realisation of this class. This is a technical view. If you are interested in the file format that is written, you have to read the documentation of the Peano patch file format.
Meta file construction modes
There are different configuration modes. They are passed as an argument to the constructor:
IndexFileMode::CreateNew Create a new index file. The old one is thrown away.
IndexFileMode::NoIndexFile Ignore the whole index file stuff. Every instance of the plotter dumps its own data and they do not synchronise in any way.
IndexFileMode::AppendNewData Try to append a new data set to a given index file.
The last one is the most sophisticated variant and deserves further explanation. First of all, the code searches for the index (or meta) file. If there is none, the code basically falls back to IndexFileMode::CreateNew, i.e. creates a new index file.
If there is a file, we open it and look what the latest time stamp in there is. For this, we call getLatestTimeStepInIndexFile(). If that time stamp is bigger than the current time stamp, we know that this index file is from a previous run. We create a backup (some people do appreciate if we do so) and then again create a new index file.
If our own time stamp matches the last time stamp in the index file, we know that the current dump is one (of many) dumps by a spacetree which contributes towards the overall picture. That is, we add our own data set to the existing time stamp.
If our own time stamp is bigger than the last one, we know that we are the first plotter of all the plotters out there which started to dump the data of the next time stamp. We append a new section for a new dump and add our own file there.
Definition at line 73 of file PeanoTextPatchFileWriter.h.
Member Enumeration Documentation
IndexFileMode
enum class tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::IndexFileMode strong
Enumerator
CreateNew
AppendNewData
NoIndexFile
Definition at line 229 of file PeanoTextPatchFileWriter.h.
Constructor & Destructor Documentation
PeanoTextPatchFileWriter()
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::PeanoTextPatchFileWriter (int dimension, const std::string & fileName, const std::string & indexFileName, IndexFileMode appendToIndexFile, double timeStamp)
Create a new Peano text file output.
An instance of this class has to be owned by each action set that wants to dump data.
Parameters
dimension I make this a free parameter, even though most codes will pass in the compile time parameter Dimensions. However, there are codes which plot submanifolds for example or want to write 3d data within a 2d code, as they implement a 2.5d model.
fileName Name of the file to write. Has to be unique per dump.
indexFileName Name of the index file. Can we empty if you select NoIndexFile.
Definition at line 135 of file PeanoTextPatchFileWriter.cpp.
References _fileName, _indexFile, _snapshotFileOut, addNewDatasetToIndexFile(), addNewFileToCurrentDataSetInIndexFile(), AppendNewData, assertion, clear(), createBackupOfMetaFile(), createEmptyIndexFile(), CreateNew, getLatestTimeStepInIndexFile(), logDebug, logWarning, NoIndexFile, tarch::la::relativeEpsNormaledAgainstValueGreaterOne(), tarch::la::smaller(), and timeStamp.
~PeanoTextPatchFileWriter()
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::~PeanoTextPatchFileWriter () virtual
Destructor.
The destructor is empty, i.e. if you destroy this object, your data are lost. You have to dump the data beforehand manually by calling writeToFile().
Definition at line 218 of file PeanoTextPatchFileWriter.cpp.
Member Function Documentation
addNewDatasetToIndexFile()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::addNewDatasetToIndexFile (double timestamp) protected
Definition at line 70 of file PeanoTextPatchFileWriter.cpp.
Referenced by PeanoTextPatchFileWriter().
addNewFileToCurrentDataSetInIndexFile()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::addNewFileToCurrentDataSetInIndexFile (const std::string & filename) protected
Definition at line 81 of file PeanoTextPatchFileWriter.cpp.
References assertion2, logDebug, and logWarning.
Referenced by PeanoTextPatchFileWriter().
clear()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::clear () override virtual
Clear local data.
Clear the writer, i.e. erase all the data. However, as the writer does not track how many vertex and cell writers you've created, it's up to you to ensure that none of these instances is left. So we clear the core data, but we do not clear the data within any data writer which you have created by calling routines such as createCellDataWriter().
Implements tarch::plotter::griddata::blockstructured::PatchWriter.
Definition at line 472 of file PeanoTextPatchFileWriter.cpp.
Referenced by peano4.output.Makefile.Makefile::__init__(), and PeanoTextPatchFileWriter().
createBackupOfMetaFile()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::createBackupOfMetaFile () protected
Definition at line 29 of file PeanoTextPatchFileWriter.cpp.
References _indexFile.
Referenced by PeanoTextPatchFileWriter().
createCellDataWriter() [1/3]
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter * tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::createCellDataWriter (const std::string & identifier, int unknownsPerAxis, int recordsPerCell, const std::string & description) override virtual
Caller has to destroy this instance manually.
Implements tarch::plotter::griddata::blockstructured::PatchWriter.
Definition at line 326 of file PeanoTextPatchFileWriter.cpp.
createCellDataWriter() [2/3]
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter * tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::createCellDataWriter (const std::string & identifier, int unknownsPerAxis, int recordsPerCell, const std::string & description, const std::string & metaData) override virtual
Create cell data writer.
Wrapper around createCellDataWriter(std::string, int, int, std::string, std::string, double*) with default values. Please consult description of the more elaborate routine for details.
Implements tarch::plotter::griddata::blockstructured::PatchWriter.
Definition at line 333 of file PeanoTextPatchFileWriter.cpp.
createCellDataWriter() [3/3]
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter * tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::createCellDataWriter (const std::string & identifier, int unknownsPerAxis, int recordsPerCell, const std::string & description, const std::string & metaData, double * mapping) override virtual
Create writer.
Caller has to destroy this instance manually.
Parameters
identifier Name of your data. I recommend to stick to C++ identifier rules for this one, i.e. no fancy chars and no spaces
unknownsPerAxis We plot a (logically) Cartesian piece of data. This is the number of unknowns per axis
recordsPerVertex Number of entries stores per unknown. Data is, by default, written as AoS
description This is a description of the data. Should be a one-liner.
metaData Further meta data without prescribed semantics. Can be a longer text block.
mapping Array of positions within a unit cube/square. It is an AoS of vectors within the unit square which distorts all the plotting points within the logical Cartesian mesh imposed over the unit cube. By default, all data are Cartesian and spaced out equidistantly, i.e. if you have 4x4 data points per cell, then you get a chess board pattern of 16 smaller cubes over the cell in 2d. However, you might prefer something like Gauss Lobatto nodes, and then the data are not spaced out uniformly anymore.
Implements tarch::plotter::griddata::blockstructured::PatchWriter.
Definition at line 344 of file PeanoTextPatchFileWriter.cpp.
createEmptyIndexFile()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::createEmptyIndexFile () protected
Definition at line 116 of file PeanoTextPatchFileWriter.cpp.
References logError, and logInfo.
Referenced by PeanoTextPatchFileWriter().
createVertexDataWriter() [1/3]
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter * tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::createVertexDataWriter (const std::string & identifier, int unknownsPerAxis, int recordsPerVertex, const std::string & description) override virtual
Caller has to destroy this instance manually.
Implements tarch::plotter::griddata::blockstructured::PatchWriter.
Definition at line 356 of file PeanoTextPatchFileWriter.cpp.
createVertexDataWriter() [2/3]
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter * tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::createVertexDataWriter (const std::string & identifier, int unknownsPerAxis, int recordsPerVertex, const std::string & description, const std::string & metaData) override virtual
Create vertex data writer.
Wrapper around createVertexDataWriter(std::string, int, int, std::string, std::string, double*) with default values. Please consult description of the more elaborate routine for details.
Implements tarch::plotter::griddata::blockstructured::PatchWriter.
Definition at line 363 of file PeanoTextPatchFileWriter.cpp.
createVertexDataWriter() [3/3]
tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter * tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::createVertexDataWriter (const std::string & identifier, int unknownsPerAxis, int recordsPerVertex, const std::string & description, const std::string & metaData, double * mapping) override virtual
Create writer.
Caller has to destroy this instance manually.
Parameters
identifier Name of your data. I recommend to stick to C++ identifier rules for this one, i.e. no fancy chars and no spaces
unknownsPerAxis We plot a (logically) Cartesian piece of data. This is the number of unknowns per axis
recordsPerVertex Number of entries stores per unknown. Data is, by default, written as AoS
description This is a description of the data. Should be a one-liner.
metaData Further meta data without prescribed semantics. Can be a longer text block.
mapping Array of positions within a unit cube/square. It is an AoS of vectors within the unit square which distorts all the plotting points within the logical Cartesian mesh imposed over the unit cube. By default, all data are Cartesian and spaced out equidistantly, i.e. if you have 4x4 data points per cell, then you get a chess board pattern of 16 smaller cubes over the cell in 2d. However, you might prefer something like Gauss Lobatto nodes, and then the data are not spaced out uniformly anymore.
Implements tarch::plotter::griddata::blockstructured::PatchWriter.
Definition at line 374 of file PeanoTextPatchFileWriter.cpp.
getLatestTimeStepInIndexFile()
double tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::getLatestTimeStepInIndexFile () const protected
Find latest time step in index file.
This routine runs through the index file and searches for the latest entry in there which looks similar to
timestamp  0.000000000000000000000000e+00
It will then return the value of this time stamp.
Definition at line 37 of file PeanoTextPatchFileWriter.cpp.
References logError, and timeStamp.
Referenced by PeanoTextPatchFileWriter().
isOpen()
bool tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::isOpen () override virtual
Returns
Whether writer is ready to accept data.
Implements tarch::plotter::griddata::blockstructured::PatchWriter.
Definition at line 470 of file PeanoTextPatchFileWriter.cpp.
plotPatch() [1/2]
int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::plotPatch (const tarch::la::Vector< 2, double > & offset, const tarch::la::Vector< 2, double > & size) override virtual
Returns
Patch index, i.e. unique number of this patch
Implements tarch::plotter::griddata::blockstructured::PatchWriter.
Definition at line 386 of file PeanoTextPatchFileWriter.cpp.
plotPatch() [2/2]
int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::plotPatch (const tarch::la::Vector< 3, double > & offset, const tarch::la::Vector< 3, double > & size) override virtual
Returns
Patch index, i.e. unique number of this patch
Implements tarch::plotter::griddata::blockstructured::PatchWriter.
Definition at line 419 of file PeanoTextPatchFileWriter.cpp.
References assertion.
writeMapping()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::writeMapping (int totalEntries, double * values) protected
Definition at line 305 of file PeanoTextPatchFileWriter.cpp.
Referenced by tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::CellDataWriter(), and tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::VertexDataWriter().
writeMetaData()
void tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::writeMetaData (const std::string & metaData) protected
Definition at line 317 of file PeanoTextPatchFileWriter.cpp.
Referenced by tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::CellDataWriter(), and tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::VertexDataWriter().
writeToFile()
bool tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::writeToFile () override virtual
Returns
Write has been successful
Implements tarch::plotter::griddata::blockstructured::PatchWriter.
Definition at line 448 of file PeanoTextPatchFileWriter.cpp.
References assertion, logDebug, and logError.
Field Documentation
_dimensions
int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::_dimensions protected
Definition at line 83 of file PeanoTextPatchFileWriter.h.
Referenced by exahype2.Project.Project::__configure_makefile(), swift2.Project.Project::__configure_makefile(), api.Project.Project::__configure_makefile(), exahype2.Project.Project::__export_constants(), swift2.Project.Project::__export_constants(), api.Project.Project::__export_constants(), api.Project.Project::__init__(), exahype2.solvers.aderdg.ADERDG.ADERDG::__str__(), exahype2.solvers.fv.FV.FV::__str__(), solvers.api.ContinuousGalerkinDiscretisationGaussLobattoWithBlockJacobi.ContinuousGalerkinDiscretisationGaussLobattoWithBlockJacobi::_construct_narrow_to_interior_matrix(), exahype2.solvers.fv.FV.FV::_init_dictionary_with_default_parameters(), exahype2.solvers.aderdg.ADERDG.ADERDG::add_implementation_files_to_project(), scenarios.elastic_planar_waves.ElasticPlanarWaves::analytical_solution(), peano4.visualisation.output.Visualiser.PatchFileData::apply_renderer_to_data(), exahype2.Project.Project::generate_Peano4_project(), scenarios.elastic_planar_waves.ElasticPlanarWaves::initial_conditions(), swift2.Project.Project::set_global_simulation_parameters(), api.Project.Project::set_global_simulation_parameters(), api.Project.Project::set_global_simulation_parameters(), exahype2.Project.Project::set_global_simulation_parameters(), and scenarios.scenario.Scenario::set_global_simulation_parameters().
_fileName
std::string tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::_fileName protected
Definition at line 78 of file PeanoTextPatchFileWriter.h.
Referenced by PeanoTextPatchFileWriter().
_haveWrittenAtLeastOnePatch
bool tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::_haveWrittenAtLeastOnePatch protected
Definition at line 88 of file PeanoTextPatchFileWriter.h.
_indexFile
std::string tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::_indexFile protected
Definition at line 79 of file PeanoTextPatchFileWriter.h.
Referenced by createBackupOfMetaFile(), and PeanoTextPatchFileWriter().
_log
tarch::logging::Log tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::_log static protected
Definition at line 75 of file PeanoTextPatchFileWriter.h.
_patchCounter
int tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::_patchCounter protected
Definition at line 85 of file PeanoTextPatchFileWriter.h.
_snapshotFileOut
std::stringstream tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::_snapshotFileOut protected
Definition at line 87 of file PeanoTextPatchFileWriter.h.
Referenced by tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::CellDataWriter::CellDataWriter(), PeanoTextPatchFileWriter(), and tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::VertexDataWriter::VertexDataWriter().
_writtenToFile
bool tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::_writtenToFile protected
Definition at line 81 of file PeanoTextPatchFileWriter.h.
HEADER
const std::string tarch::plotter::griddata::blockstructured::PeanoTextPatchFileWriter::HEADER static protected
Initial value:
= "# \n"
    "# Peano patch file \n"
    "# Version 0.2 \n"
    "# \n"
Definition at line 76 of file PeanoTextPatchFileWriter.h.
The documentation for this class was generated from the following files:
src/tarch/plotter/griddata/blockstructured/PeanoTextPatchFileWriter.h
src/tarch/plotter/griddata/blockstructured/PeanoTextPatchFileWriter.cpp