Peano
exahype2::dg::tests::CellIntegralTest Class Reference
#include <CellIntegralTest.h>
Public Member Functions
CellIntegralTest ()
virtual ~CellIntegralTest ()=default
virtual void run () override
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void runEulerOrder2OnStationarySetup ()
I initialise all velocity data with zero, and set density to 1.
void runEulerOrder4OnStationarySetup ()
Private Attributes
const double _Order4_QuadraturePoints1d [4+1]
const double _Order4_MassMatrixDiagonal1d [4+1]
const double _Order4_StiffnessOperator1d [(4+1) *(4+1)]
const double _Order4_DerivativeOperator1d [(4+1) *(4+1)]
const double _Order4_BasisFunctionValuesLeft1d [4+1]
const double _Order2_QuadraturePoints1d [2+1]
const double _Order2_MassMatrixDiagonal1d [2+1]
const double _Order2_StiffnessOperator1d [(2+1) *(2+1)]
const double _Order2_DerivativeOperator1d [(2+1) *(2+1)]
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Definition at line 15 of file CellIntegralTest.h.
Constructor & Destructor Documentation
CellIntegralTest()
exahype2::dg::tests::CellIntegralTest::CellIntegralTest ()
Definition at line 19 of file CellIntegralTest.cpp.
~CellIntegralTest()
virtual exahype2::dg::tests::CellIntegralTest::~CellIntegralTest () virtual default
Member Function Documentation
run()
void exahype2::dg::tests::CellIntegralTest::run () override virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 43 of file CellIntegralTest.cpp.
References testMethod.
runEulerOrder2OnStationarySetup()
void exahype2::dg::tests::CellIntegralTest::runEulerOrder2OnStationarySetup () private
I initialise all velocity data with zero, and set density to 1.
First, we set the inner energy to zero. After that, we set it to 4.
One might think that the result should always be 0 for all components, but the result is not zero if the inner energy is positive. You get a zero update for the density, and you get a zero update for the energy. The velocity however becomes star shaped, i.e. looks like matter pressed out from the centre.
This behaviour is due to the internal energy pushing matter out of the domain. If the inner energy equals zero, then nothing moves at all.
Definition at line 48 of file CellIntegralTest.cpp.
References exahype2::dg::cellIntegral_patchwise_in_situ_GaussLegendre_functors(), cellSize, dfor, peano4::utils::dLinearised(), exahype2::dg::tests::eulerFlux(), exahype2::dg::plotCell(), validateNumericalEqualsWithParams2, and validateWithParams2.
runEulerOrder4OnStationarySetup()
void exahype2::dg::tests::CellIntegralTest::runEulerOrder4OnStationarySetup () private
Definition at line 179 of file CellIntegralTest.cpp.
References exahype2::dg::cellIntegral_patchwise_in_situ_GaussLegendre_functors(), cellSize, exahype2::dg::tests::eulerFlux(), exahype2::dg::plotCell(), and validateNumericalEqualsWithParams2.
Field Documentation
_Order2_DerivativeOperator1d
const double exahype2::dg::tests::CellIntegralTest::_Order2_DerivativeOperator1d[(2+1) *(2+1)] private
Definition at line 26 of file CellIntegralTest.h.
_Order2_MassMatrixDiagonal1d
const double exahype2::dg::tests::CellIntegralTest::_Order2_MassMatrixDiagonal1d[2+1] private
Definition at line 24 of file CellIntegralTest.h.
_Order2_QuadraturePoints1d
const double exahype2::dg::tests::CellIntegralTest::_Order2_QuadraturePoints1d[2+1] private
Definition at line 23 of file CellIntegralTest.h.
_Order2_StiffnessOperator1d
const double exahype2::dg::tests::CellIntegralTest::_Order2_StiffnessOperator1d[(2+1) *(2+1)] private
Definition at line 25 of file CellIntegralTest.h.
_Order4_BasisFunctionValuesLeft1d
const double exahype2::dg::tests::CellIntegralTest::_Order4_BasisFunctionValuesLeft1d[4+1] private
Definition at line 21 of file CellIntegralTest.h.
_Order4_DerivativeOperator1d
const double exahype2::dg::tests::CellIntegralTest::_Order4_DerivativeOperator1d[(4+1) *(4+1)] private
Definition at line 20 of file CellIntegralTest.h.
_Order4_MassMatrixDiagonal1d
const double exahype2::dg::tests::CellIntegralTest::_Order4_MassMatrixDiagonal1d[4+1] private
Definition at line 18 of file CellIntegralTest.h.
_Order4_QuadraturePoints1d
const double exahype2::dg::tests::CellIntegralTest::_Order4_QuadraturePoints1d[4+1] private
Definition at line 17 of file CellIntegralTest.h.
_Order4_StiffnessOperator1d
const double exahype2::dg::tests::CellIntegralTest::_Order4_StiffnessOperator1d[(4+1) *(4+1)] private
Definition at line 19 of file CellIntegralTest.h.
The documentation for this class was generated from the following files:
src/exahype2/dg/tests/CellIntegralTest.h
src/exahype2/dg/tests/CellIntegralTest.cpp