Peano
toolbox::blockstructured::tests::IandRThirdOrderTest Class Reference
#include <IandRThirdOrderTest.h>
Public Member Functions
IandRThirdOrderTest ()
Cosntructor.
virtual ~IandRThirdOrderTest ()=default
Destructor, empty.
virtual void run () override
This routine is triggered by the TestCaseCollection.
Public Member Functions inherited from tarch::tests::TestCase
TestCase (const std::string &testCaseName)
Constructor.
virtual ~TestCase ()
Destructor.
int getNumberOfErrors () const
std::string getTestCaseName () const
Private Member Functions
void compareInterpolateLinearCaseToTensorProduct ()
The third order interpolation and restriction scheme is tested by comparing the results to the tensor product scheme for linear source data.
void compareRestrictLinearCaseToTensorProduct ()
Additional Inherited Members
Protected Member Functions inherited from tarch::tests::TestCase
TestCase ()=delete
Protected Attributes inherited from tarch::tests::TestCase
const std::string _testCaseName
Name of the test case.
int _errors
Error counter.
bool _error
Indicate within macro if one specific validation failed.
Detailed Description
Definition at line 17 of file IandRThirdOrderTest.h.
Constructor & Destructor Documentation
IandRThirdOrderTest()
toolbox::blockstructured::tests::IandRThirdOrderTest::IandRThirdOrderTest ()
Cosntructor.
Definition at line 6 of file IandRThirdOrderTest.cpp.
~IandRThirdOrderTest()
virtual toolbox::blockstructured::tests::IandRThirdOrderTest::~IandRThirdOrderTest () virtual default
Destructor, empty.
Member Function Documentation
compareInterpolateLinearCaseToTensorProduct()
void toolbox::blockstructured::tests::IandRThirdOrderTest::compareInterpolateLinearCaseToTensorProduct () private
The third order interpolation and restriction scheme is tested by comparing the results to the tensor product scheme for linear source data.
Definition at line 14 of file IandRThirdOrderTest.cpp.
References peano4::datamanagement::FaceMarker::getRelativePositionWithinFatherFace(), toolbox::blockstructured::interpolateHaloLayer_AoS_tensor_product(), toolbox::blockstructured::interpolateHaloLayer_AoS_third_order(), peano4::grid::GridTraversalEvent::setRelativePositionToFather(), and validateNumericalEqualsWithEpsWithParams3.
compareRestrictLinearCaseToTensorProduct()
void toolbox::blockstructured::tests::IandRThirdOrderTest::compareRestrictLinearCaseToTensorProduct () private
Definition at line 155 of file IandRThirdOrderTest.cpp.
References peano4::datamanagement::FaceMarker::getRelativePositionWithinFatherFace(), toolbox::blockstructured::restrictInnerHalfOfHaloLayer_AoS_tensor_product(), toolbox::blockstructured::restrictInnerHalfOfHaloLayer_AoS_third_order(), peano4::grid::GridTraversalEvent::setRelativePositionToFather(), and validateNumericalEqualsWithEpsWithParams3.
run()
void toolbox::blockstructured::tests::IandRThirdOrderTest::run () override virtual
This routine is triggered by the TestCaseCollection.
Implements tarch::tests::TestCase.
Definition at line 9 of file IandRThirdOrderTest.cpp.
References testMethod.
The documentation for this class was generated from the following files:
src/toolbox/blockstructured/tests/IandRThirdOrderTest.h
src/toolbox/blockstructured/tests/IandRThirdOrderTest.cpp