Peano
Variant3.cpp File Reference
#include "CellFaceData.h"
#include "exahype2/CellData.h"
#include "kernels/AderSolver/BufferSizes.h"
#include "kernels/AderSolver/FaceIntegral.h"
#include "kernels/AderSolver/FusedSpaceTimePredictorVolumeIntegral.h"
#include "kernels/AderSolver/MaxScaledEigenvalue.h"
#include "kernels/AderSolver/RiemannSolver.h"
#include "repositories/SolverRepository.h"
#include "Utils.h"
#include "Variants.h"
#include <cstring>
Functions
void initialTask (exahype2::CellData< SolverPrecision, SolverPrecision > *myCellData, exahype2::CellFaceData< SolverPrecision, SolverPrecision > *myFaceData, const int cellId, const int faceId, tarch::timing::Measurement &measurement)
void firstTask (exahype2::CellFaceData< SolverPrecision, SolverPrecision > *myFaceData, const int faceId, const int faceDirection, tarch::timing::Measurement &measurement)
void secondTask (exahype2::CellData< SolverPrecision, SolverPrecision > *myCellData, exahype2::CellFaceData< SolverPrecision, SolverPrecision > *myFaceData, const int cellId, const int faceId, tarch::timing::Measurement &measurement)
Function Documentation
firstTask()
void firstTask (exahype2::CellFaceData< SolverPrecision, SolverPrecision > * myFaceData, const int faceId, const int faceDirection, tarch::timing::Measurement & measurement)
Definition at line 99 of file Variant3.cpp.
References exahype2::CellFaceData< inType, outType >::cellCentre, exahype2::CellFaceData< inType, outType >::cellSize, exahype2::CellFaceData< inType, outType >::dt, tarch::timing::Watch::getCalendarTime(), exahype2::CellFaceData< inType, outType >::QIn, exahype2::CellFaceData< inType, outType >::QOut, tarch::timing::Measurement::setValue(), tarch::timing::Watch::stop(), and exahype2::CellFaceData< inType, outType >::t.
Referenced by variant3::runBenchmarks().
initialTask()
void initialTask (exahype2::CellData< SolverPrecision, SolverPrecision > * myCellData, exahype2::CellFaceData< SolverPrecision, SolverPrecision > * myFaceData, const int cellId, const int faceId, tarch::timing::Measurement & measurement)
Definition at line 44 of file Variant3.cpp.
References exahype2::CellData< inType, outType, NumFaceTypes >::cellCentre, exahype2::CellData< inType, outType, NumFaceTypes >::cellSize, exahype2::CellData< inType, outType, NumFaceTypes >::dt, tarch::timing::Watch::getCalendarTime(), exahype2::CellFaceData< inType, outType >::QIn, exahype2::CellData< inType, outType, NumFaceTypes >::QIn, exahype2::CellFaceData< inType, outType >::QOut, tarch::timing::Measurement::setValue(), tarch::timing::Watch::stop(), and exahype2::CellData< inType, outType, NumFaceTypes >::t.
Referenced by variant3::runBenchmarks().
secondTask()
void secondTask (exahype2::CellData< SolverPrecision, SolverPrecision > * myCellData, exahype2::CellFaceData< SolverPrecision, SolverPrecision > * myFaceData, const int cellId, const int faceId, tarch::timing::Measurement & measurement)
Definition at line 134 of file Variant3.cpp.
References exahype2::CellData< inType, outType, NumFaceTypes >::cellCentre, exahype2::CellData< inType, outType, NumFaceTypes >::cellSize, exahype2::CellData< inType, outType, NumFaceTypes >::dt, tarch::timing::Watch::getCalendarTime(), exahype2::CellData< inType, outType, NumFaceTypes >::maxEigenvalue, exahype2::CellFaceData< inType, outType >::QIn, exahype2::CellData< inType, outType, NumFaceTypes >::QIn, exahype2::CellFaceData< inType, outType >::QOut, tarch::timing::Measurement::setValue(), tarch::timing::Watch::stop(), and exahype2::CellData< inType, outType, NumFaceTypes >::t.
Referenced by variant3::runBenchmarks().