Peano
LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder > Class Template Reference
#include <linked_grid_iterator.h>
Public Types
using Grid = Base::Grid
using Item = Spacetree*
Public Types inherited from DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >
using Grid = TGrid
using Item = Item<TGrid>
Public Member Functions
std::optional< Item > next ()
Public Member Functions inherited from DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >
DefaultIteratorCRTP ()=default
DefaultIteratorCRTP (TIterationOrder order)
DefaultIteratorCRTP (Grid *top)
std::optional< Item > next ()
Protected Types
using Base = DefaultIteratorCRTP<Spacetree, Derived, TIterationOrder>
Protected Member Functions
constexpr EventEmitFlag emitFlags ()
bool enter (Spacetree *spacetree)
bool exit (Spacetree *spacetree)
Protected Member Functions inherited from DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >
constexpr EventEmitFlag emitFlags ()
bool enter (TGrid *)
bool exit (TGrid *)
bool hasNext ()
Protected Attributes
friend Base
Protected Attributes inherited from DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >
TIterationOrder iterationOrder
TGrid * cell = nullptr
Direction state = Direction::Enter
bool hasEmittedLast = false
Detailed Description
template<typename Spacetree, typename Derived, typename TIterationOrder = NaturalOrder<Spacetree>>
class LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >
Definition at line 142 of file linked_grid_iterator.h.
Member Typedef Documentation
Base
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> Base = DefaultIteratorCRTP<Spacetree, Derived, TIterationOrder> protected
Definition at line 144 of file linked_grid_iterator.h.
Grid
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> using LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::Grid = Base::Grid
Definition at line 160 of file linked_grid_iterator.h.
Item
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> using LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::Item = Spacetree*
Definition at line 161 of file linked_grid_iterator.h.
Member Function Documentation
emitFlags()
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> constexpr EventEmitFlag LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::emitFlags () constexpr protected
Definition at line 147 of file linked_grid_iterator.h.
References EmitEnter.
enter()
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> bool LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::enter (Spacetree * spacetree) protected
Definition at line 151 of file linked_grid_iterator.h.
Referenced by BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::enter(), InsideRegionLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::enter(), and OutsideRegionLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::enter().
exit()
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> bool LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::exit (Spacetree * spacetree) protected
Definition at line 155 of file linked_grid_iterator.h.
next()
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> std::optional< Item > LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::next ()
Definition at line 165 of file linked_grid_iterator.h.
References DefaultIteratorCRTP< TGrid, Derived, TIterationOrder >::next(), and LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::next().
Referenced by LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::next(), BoundaryLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::next(), InsideRegionLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::next(), and OutsideRegionLeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::next().
Field Documentation
Base
template<typename Spacetree , typename Derived , typename TIterationOrder = NaturalOrder<Spacetree>> friend LeafsIteratorCRTP< Spacetree, Derived, TIterationOrder >::Base protected
Definition at line 145 of file linked_grid_iterator.h.
The documentation for this class was generated from the following file:
benchmarks/other/noh2d-common/spacetree/grid/linked_grid_iterator.h