var namespaceexahype2_1_1solvers_1_1rkdg_1_1rusanov_1_1GlobalAdaptiveTimeStep =
[
    [ "GlobalAdaptiveTimeStep", "de/dd0/classexahype2_1_1solvers_1_1rkdg_1_1rusanov_1_1GlobalAdaptiveTimeStep_1_1GlobalAdaptiveTimeStep.html", "de/dd0/classexahype2_1_1solvers_1_1rkdg_1_1rusanov_1_1GlobalAdaptiveTimeStep_1_1GlobalAdaptiveTimeStep" ]
];