Peano
GenericRusanov.template.h File Reference
Functions
for (int unknown=0;unknown< {{NUMBER_OF_UNKNOWNS}}+{{NUMBER_OF_AUXILIARY_VARIABLES}};unknown++)
solver flux (QInGatheredRight, volumeCentreRight, volumeSize, timeStamp, timeStepSize, normal, fluxGatheredRight)
solver nonconservativeProduct (QAverageGatheredLeft, DeltaQGatheredLeft, volumeCentreLeft, volumeSize, timeStamp, timeStepSize, normal, ncpGatheredLeft)
Variables
const auto volumeCentreRight = ::exahype2::fv::getVolumeCentre(patchCentre, patchSize, {{NUMBER_OF_VOLUMES_PER_AXIS}}, volumeRight)
const {{COMPUTE_PRECISION}} maxEigenvalueGatheredLeft = {{FULL_QUALIFIED_SOLVER_NAME}}::maxEigenvalue(QInGatheredLeft, volumeCentreLeft, volumeSize, timeStamp, timeStepSize, normal)
Function Documentation
flux()
solver flux (QInGatheredRight , volumeCentreRight , volumeSize , timeStamp , timeStepSize , normal , fluxGatheredRight)
Referenced by exahype2::dg::cellIntegral_patchwise_in_situ_GaussLegendre_functors(), exahype2::fv::musclhancock::internal::computeTimeDerivative_LoopBody(), exahype2::dg::fluxaverage::solveRiemannProblem_pointwise_in_situ(), exahype2::dg::rusanov::solveRiemannProblem_pointwise_in_situ(), and exahype2::dg::laxfriedrichs::solveRiemannProblem_pointwise_in_situ().
for()
for ()
We count faces starting with zero: Let the leftmost volume have the index i. i is typically 0 or -1 (if we have halos). When we call this routine for the index i, we first take the volume i and then we average it with i+1. So we look to the right. The result is stored in i. That means, all the indices are kind of shifted by 1/2 to the left. Index (4,3,2) is actually the face located at (4.5, 3, 2).
Definition at line 123 of file GenericRusanov.template.h.
nonconservativeProduct()
solver nonconservativeProduct (QAverageGatheredLeft , DeltaQGatheredLeft , volumeCentreLeft , volumeSize , timeStamp , timeStepSize , normal , ncpGatheredLeft)
Referenced by exahype2::dg::cellIntegral_patchwise_in_situ_GaussLegendre_functors(), applications::exahype2::ccz4::CCZ4::nonconservativeProduct(), benchmarks::exahype2::ccz4::CCZ4::nonconservativeProduct(), and exahype2::fv::musclhancock::timeStepWithMusclHancock_patchwise_heap_functors().
Variable Documentation
const
const {{COMPUTE_PRECISION}} maxEigenvalueGatheredLeft = {{FULL_QUALIFIED_SOLVER_NAME}}::maxEigenvalue(QInGatheredLeft, volumeCentreLeft, volumeSize, timeStamp, timeStepSize, normal)
Definition at line 155 of file GenericRusanov.template.h.
volumeCentreRight
const auto volumeCentreRight = ::exahype2::fv::getVolumeCentre(patchCentre, patchSize, {{NUMBER_OF_VOLUMES_PER_AXIS}}, volumeRight)
Definition at line 116 of file GenericRusanov.template.h.