Peano
create-plots Namespace Reference
Functions
filter_file (filename)
get_shared_memory_file_name (cores, d, h, flops)
get_distributed_memory_file_name (nodes, d, h, flops)
filter_shared_memory ()
parse_file (filename)
return a tuple of new entry plus max cells.
normalise_raw_times (time_data, max_cells)
Divides each entry through max number of cells and iterations.
plot_shared_memory ()
Variables
list D = [2,3]
list H = [ 0.5, 0.2, 0.1, 0.05, 0.02, 0.01, 0.005, 0.002, 0.001 ]
list Flops = [ 1, 100, 10000, 1000000 ]
list Color = [ "#ff0000", "#00ff00", "#0000ff", "#a0a000", "#a000a0", "#00a0a0", "#998899", "#aa8888", "#88aa88", "#8888aa" ]
int BenchmarkIterations = 20
Function Documentation
filter_file()
create-plots.filter_file (filename)
Definition at line 15 of file create-plots.py.
Referenced by filter_shared_memory().
filter_shared_memory()
create-plots.filter_shared_memory ()
Definition at line 33 of file create-plots.py.
References filter_file(), and get_shared_memory_file_name().
Referenced by plot_shared_memory().
get_distributed_memory_file_name()
create-plots.get_distributed_memory_file_name (nodes, d, h, flops)
Definition at line 29 of file create-plots.py.
get_shared_memory_file_name()
create-plots.get_shared_memory_file_name (cores, d, h, flops)
Definition at line 25 of file create-plots.py.
Referenced by filter_shared_memory(), and plot_shared_memory().
normalise_raw_times()
create-plots.normalise_raw_times (time_data, max_cells)
Divides each entry through max number of cells and iterations.
Definition at line 61 of file create-plots.py.
Referenced by plot_shared_memory().
parse_file()
create-plots.parse_file (filename)
return a tuple of new entry plus max cells.
First entry in tuple is 0.0 if no data found
Definition at line 42 of file create-plots.py.
References int.
Referenced by plot_shared_memory().
plot_shared_memory()
create-plots.plot_shared_memory ()
Definition at line 67 of file create-plots.py.
References filter_shared_memory(), get_shared_memory_file_name(), normalise_raw_times(), parse_file(), and plot_shared_memory().
Referenced by plot_shared_memory().
Variable Documentation
BenchmarkIterations
int create-plots.BenchmarkIterations = 20
Definition at line 11 of file create-plots.py.
Color
list create-plots.Color = [ "#ff0000", "#00ff00", "#0000ff", "#a0a000", "#a000a0", "#00a0a0", "#998899", "#aa8888", "#88aa88", "#8888aa" ]
Definition at line 10 of file create-plots.py.
D
list create-plots.D = [2,3]
Definition at line 7 of file create-plots.py.
Flops
list create-plots.Flops = [ 1, 100, 10000, 1000000 ]
Definition at line 9 of file create-plots.py.
H
list create-plots.H = [ 0.5, 0.2, 0.1, 0.05, 0.02, 0.01, 0.005, 0.002, 0.001 ]
Definition at line 8 of file create-plots.py.