Peano
benchmarks::swift2::hydro::kernel_throughput Namespace Reference
Functions
void initNohProblemIC (globaldata::HydroPart &particle, const tarch::la::Vector< Dimensions, double > &h, double HYDRO_PART_NUMBER, double HYDRO_DIMENSIONS)
Function Documentation
initNohProblemIC()
void benchmarks::swift2::hydro::kernel_throughput::initNohProblemIC (globaldata::HydroPart & particle, const tarch::la::Vector< Dimensions, double > & h, double HYDRO_PART_NUMBER, double HYDRO_DIMENSIONS)
Definition at line 6 of file NohProblem.cpp.
References _log, tarch::la::equals(), logDebug, tarch::la::norm2(), pressure, and soundspeed.
Referenced by initParticle().