Peano
Prediction.EnclaveTask.template.cpp File Reference
#include "{{CLASSNAME}}.h"
#include "repositories/SolverRepository.h"
#include "kernels/{{SOLVER_NAME}}/FusedSpaceTimePredictorVolumeIntegral.h"
#include "kernels/{{SOLVER_NAME}}/PointSources.h"
#include "kernels/{{SOLVER_NAME}}/FusedSpaceTimePredictorVolumeIntegralWithPointSources.h"
#include "exahype2/CellData.h"
#include "peano4/parallel/parallel.h"
#include <algorithm>
#include <cstring>
Variables
int {{NAMESPACE | join("::")}}::{{CLASSNAME}}::_enclaveTaskTypeId(peano4::parallel::getTaskType("{{NAMESPACE | join("::")}}::{{CLASSNAME}}"))
Variable Documentation
int
int {{NAMESPACE | join("::")}}::{{CLASSNAME}}::_enclaveTaskTypeId(peano4::parallel::getTaskType("{{NAMESPACE | join("::")}}::{{CLASSNAME}}"))
Definition at line 21 of file Prediction.EnclaveTask.template.cpp.
Referenced by SBH.Limiter::__init__(), peano4.visualisation.input.PatchFileParser.PatchFileParser::__parse_meta_data_region(), peano4.toolbox.blockstructured.ReconstructPatch.ReconstructPatch::_add_action_set_entries_to_dictionary(), peano4.datamodel.PatchToDoubleArray.PatchToDoubleArray::_get_dictionary_for_output(), exahype2.solvers.fv.FV.FV::_init_dictionary_with_default_parameters(), exahype2.solvers.rkfd.CellCenteredFiniteDifferences.CellCenteredFiniteDifferences::_init_dictionary_with_default_parameters(), swift2.api.graphcompiler.AMRLogic::add_dynamic_mesh_refinement_and_particle_resorting(), postProcess::construct_dg_function(), mghype.api.matrixgenerators.StencilToElement::convertStencilToElementMatrix2d(), mghype.api.matrixgenerators.StencilToElement::convertStencilToElementMatrix3d(), toolbox::multiprecision::decomposeIntoFourVariants(), swift2.sphtools.smltools::find_smoothing_length(), peano4.toolbox.blockstructured.MPI::get_cell_merge_implementation(), peano4.toolbox.blockstructured.MPI::get_face_merge_implementation(), exahype2.solvers.aderdg.Architectures.Architectures::get_size_with_padding(), ContextCurvilinear< Shortcuts, basisSize, numberOfData, T >::getElementCenter(), petscReader::getFirstColNumberAndEntryFromLine(), InnerNode::init(), Edge::interpolate(), swift2::kernels::legacy::kernelHydro::kernel_deval(), swift2::kernels::legacy::kernelHydro::kernel_eval(), exahype2.postprocessing.utils::next_markevery(), exahype2.postprocessing.PerformanceData.PerformanceData::parse(), create-plots::parse_file(), peano4.visualisation.input.PatchFileParser.PatchFileParser::parse_file(), postProcess::plot_field_dg(), ContextDynamicRupture< Shortcuts, basisSize, numberOfVariables, numberOfParameters, T >::riemannSolver(), peano4.toolbox.particles.postprocessing.MatplotlibPlotter::seismogram(), and exahype2.postprocessing.plot-scaling::visualise().