Peano
Face Class Reference
#include <face.h>
Public Member Functions
Face ()
Face (int a_index_offset[3], FaceBoundary &boundary, std::function< double(double, double)> a_perturbation=[](double y, double x){return 0.0;}, bool keepBoundary=false)
Face (const Coordinate a_coords[2], const int a_index_offset[3], const int a_index_size[3], const double offset_mu, std::function< double(double, double)> a_perturbation=[](double y, double x){return 0.0;})
Face (const Face &other)
Face & operator= (Face other)
Coordinate getCoord (int i) const
void getCoord (Coordinate a_coord[2]) const
int getIndexOffset (Coordinate coord) const
void getIndexOffset (int a_indexoffset[3]) const
int getIndexSize (Coordinate coord) const
void getIndexSize (int a_size[3]) const
void getIndexRange (Coordinate coord, std::vector< int > &range) const
std::function< double(double, double)> getPerturbation () const
double getPosition () const
Edge split (Face &other, Face &left, Face &right) const
bool intersect (double f0, double f1, double t0, double t1, double x0, double x1, double y0, double y1, double &x, double &y) const
void reverseDimension (Coordinate coord)
void remesh ()
void subface (int subface_index_offset[3], int subface_index_size[3], Face &subface) const
const std::vector< double > & getNodes () const
double & operator() (int coord, int j, int i)
const double & operator() (int coord, int j, int i) const
const double & operator() (int coord, Coordinate coord_j, int j, Coordinate coord_i, int i) const
double & operator() (int coord, Coordinate coord_j, int j, Coordinate coord_i, int i)
void toNetCDF (std::string filename) const
std::string printNodes () const
Private Attributes
Coordinate coords [2]
int index_offset [3]
int index_size [3]
double position
std::function< double(double, double)> perturbation
std::vector< double > nodes
Friends
std::ostream & operator<< (std::ostream &ss, const Face &f)
Detailed Description
Definition at line 23 of file face.h.
Constructor & Destructor Documentation
Face() [1/4]
Face::Face ()
Definition at line 25 of file face.cpp.
Referenced by split(), and subface().
Face() [2/4]
Face::Face (int a_index_offset[3], FaceBoundary & boundary, std::function< double(double, double)> a_perturbation = [](double y, double x){return 0.0;}, bool keepBoundary = false)
Definition at line 55 of file face.cpp.
References coords, getIndexRange(), getNormal(), index_offset, index_size, Interpolation::Transfinite::interpolate2D(), NCOORDS, nodes, perturbation, and position.
Face() [3/4]
Face::Face (const Coordinate a_coords[2], const int a_index_offset[3], const int a_index_size[3], const double offset_mu, std::function< double(double, double)> a_perturbation = [](double y, double x){return 0.0;})
Definition at line 31 of file face.cpp.
References coords, index_offset, index_size, NCOORDS, and nodes.
Face() [4/4]
Face::Face (const Face & other)
Definition at line 100 of file face.cpp.
References coords, getNodes(), index_offset, index_size, nodes, perturbation, and position.
Member Function Documentation
getCoord() [1/2]
void Face::getCoord (Coordinate a_coord[2]) const
Definition at line 125 of file face.cpp.
References coords.
getCoord() [2/2]
Coordinate Face::getCoord (int i) const
Definition at line 121 of file face.cpp.
References coords.
Referenced by BlockBoundary::BlockBoundary(), BlockBoundary::checkConformity(), FaceBoundary::FaceBoundary(), BlockBoundary::getBoundingBox(), and BlockBoundary::split().
getIndexOffset() [1/2]
int Face::getIndexOffset (Coordinate coord) const
Definition at line 139 of file face.cpp.
References index_offset.
Referenced by BlockBoundary::BlockBoundary(), BlockBoundary::checkConformity(), and BlockBoundary::split().
getIndexOffset() [2/2]
void Face::getIndexOffset (int a_indexoffset[3]) const
Definition at line 135 of file face.cpp.
References index_offset.
getIndexRange()
void Face::getIndexRange (Coordinate coord, std::vector< int > & range) const
Definition at line 170 of file face.cpp.
References index_offset, and index_size.
Referenced by BlockBoundary::BlockBoundary(), Face(), FaceBoundary::FaceBoundary(), BlockBoundary::getBoundingBox(), Curvi::Interface::invertProjection(), printNodes(), reverseDimension(), and split().
getIndexSize() [1/2]
int Face::getIndexSize (Coordinate coord) const
Definition at line 144 of file face.cpp.
References index_size.
Referenced by BlockBoundary::BlockBoundary(), BlockBoundary::checkConformity(), FaceBoundary::FaceBoundary(), and BlockBoundary::split().
getIndexSize() [2/2]
void Face::getIndexSize (int a_size[3]) const
Definition at line 148 of file face.cpp.
References index_size.
getNodes()
const std::vector< double > & Face::getNodes () const
Definition at line 176 of file face.cpp.
References nodes.
Referenced by Face().
getPerturbation()
std::function< double(double, double)> Face::getPerturbation () const
Definition at line 273 of file face.cpp.
References perturbation.
Referenced by BlockBoundary::split().
getPosition()
double Face::getPosition () const
Definition at line 130 of file face.cpp.
References position.
Referenced by BlockBoundary::BlockBoundary(), FaceBoundary::FaceBoundary(), and BlockBoundary::split().
intersect()
bool Face::intersect (double f0, double f1, double t0, double t1, double x0, double x1, double y0, double y1, double & x, double & y) const
Definition at line 411 of file face.cpp.
Referenced by split().
operator()() [1/4]
double & Face::operator() (int coord, Coordinate coord_j, int j, Coordinate coord_i, int i)
Definition at line 216 of file face.cpp.
References coords.
operator()() [2/4]
const double & Face::operator() (int coord, Coordinate coord_j, int j, Coordinate coord_i, int i) const
Definition at line 196 of file face.cpp.
References coords.
operator()() [3/4]
double & Face::operator() (int coord, int j, int i)
Definition at line 180 of file face.cpp.
References coords, index_offset, index_size, NCOORDS, and nodes.
operator()() [4/4]
const double & Face::operator() (int coord, int j, int i) const
Definition at line 188 of file face.cpp.
References coords, index_offset, index_size, NCOORDS, and nodes.
operator=()
Face & Face::operator= (Face other)
Definition at line 110 of file face.cpp.
References coords, index_offset, index_size, nodes, perturbation, and position.
printNodes()
std::string Face::printNodes () const
Definition at line 486 of file face.cpp.
References coords, and getIndexRange().
remesh()
void Face::remesh ()
reverseDimension()
void Face::reverseDimension (Coordinate coord)
Definition at line 152 of file face.cpp.
References coords, getIndexRange(), and temp.
split()
Edge Face::split (Face & other, Face & left, Face & right) const
Cut faces
Definition at line 277 of file face.cpp.
References coords, coordToString(), Face(), getIndexRange(), getNormal(), index_offset, index_size, intersect(), NCOORDS, perturbation, Edge::resize(), and FaceBoundary::split().
Referenced by BlockBoundary::split().
subface()
void Face::subface (int subface_index_offset[3], int subface_index_size[3], Face & subface) const
Definition at line 236 of file face.cpp.
References a, coords, coordToString(), Face(), index_offset, index_size, perturbation, position, subface(), X, Y, and Z.
Referenced by subface().
toNetCDF()
void Face::toNetCDF (std::string filename) const
Definition at line 466 of file face.cpp.
References NetCDFWriter::close(), coords, index_offset, index_size, NetCDFWriter::init(), nodes, and NetCDFWriter::write().
Referenced by BlockBoundary::split(), and BlockBoundary::toNetCDF().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & ss, const Face & f) friend
Definition at line 443 of file face.cpp.
Field Documentation
coords
Coordinate Face::coords[2] private
Definition at line 80 of file face.h.
Referenced by Face(), Face(), Face(), getCoord(), getCoord(), operator()(), operator()(), operator()(), operator()(), operator=(), printNodes(), reverseDimension(), split(), subface(), and toNetCDF().
index_offset
int Face::index_offset[3] private
Definition at line 81 of file face.h.
Referenced by Face(), Face(), Face(), getIndexOffset(), getIndexOffset(), getIndexRange(), operator()(), operator()(), operator=(), split(), subface(), and toNetCDF().
index_size
int Face::index_size[3] private
Definition at line 82 of file face.h.
Referenced by Face(), Face(), Face(), getIndexRange(), getIndexSize(), getIndexSize(), operator()(), operator()(), operator=(), split(), subface(), and toNetCDF().
nodes
std::vector<double> Face::nodes private
Definition at line 85 of file face.h.
Referenced by Face(), Face(), Face(), getNodes(), operator()(), operator()(), operator=(), and toNetCDF().
perturbation
std::function<double(double,double)> Face::perturbation private
Definition at line 84 of file face.h.
Referenced by Face(), Face(), getPerturbation(), operator=(), split(), and subface().
position
double Face::position private
Definition at line 83 of file face.h.
Referenced by Face(), Face(), getPosition(), operator=(), and subface().
The documentation for this class was generated from the following files:
src/toolbox/curvi/geometry/face.h
src/toolbox/curvi/geometry/face.cpp